IntersectMBO/plutus

- .gitignore
- language-plutus-napkin/.hlint.yaml
- language-plutus-napkin/.stylish-haskell.yaml
- language-plutus-napkin/.travis.yml
- language-plutus-napkin/LICENSE
- language-plutus-napkin/appveyor.yml
- language-plutus-napkin/bench/Bench.hs
- language-plutus-napkin/cabal.project.local
- language-plutus-napkin/language-plutus-napkin.cabal
- language-plutus-napkin/src/Language/PlutusNapkin.hs
- language-plutus-napkin/src/Language/PlutusNapkin/Type.hs
- language-plutus-napkin/stack.yaml
- language-plutus-napkin/test/Spec.hs
This provides a potential AST based on the latest spec in the `docs` folder.
> [WIP] Plutus napkin/cgp 165

- language-plutus-core/.hlint.yaml
- language-plutus-core/Justfile
- language-plutus-core/TODO.md
- language-plutus-core/language-plutus-core.cabal
- language-plutus-core/src/Language/PlutusCore.hs
- language-plutus-core/src/Language/PlutusCore/Lexer.x
- language-plutus-core/src/Language/PlutusCore/Name.hs
- language-plutus-core/src/Language/PlutusCore/Parser.y
- language-plutus-core/src/Language/PlutusCore/Type.hs
- language-plutus-core/src/Language/PlutusCore/TypeRenamer.hs
- language-plutus-core/src/PlutusPrelude.hs
- language-plutus-core/stack.yaml
- language-plutus-core/test/Spec.hs
- language-plutus-core/test/data/addInteger.plc
- language-plutus-core/test/data/addInteger.plc.golden
- language-plutus-core/test/scopes/apply.plc
- language-plutus-core/test/scopes/apply.plc.golden
- language-plutus-core/test/scopes/fix.plc
- language-plutus-core/test/scopes/fix.plc.golden
- language-plutus-core/test/scopes/lambda.plc
- language-plutus-core/test/scopes/lambda.plc.golden
- language-plutus-core/test/scopes/lambda2.plc
- language-plutus-core/test/scopes/lambda2.plc.golden
This needs a better test suite. Currently I have simply ensured it works by running `cabal new-repl` and trying out an example, but this is not fully rigorous.
> Implement type renamer

- docs/fomega/evaluation/machines.md
I added some docs. Will implement the CK machine and likely add more docs, so do not merge yet.
> [WIP] Add the CK machine and related docs

- README.md
- default.nix
Adds haddock documentation to hydra
> [DEVOPS-940] add haddock documentation hydra artifact

- docs/fomega/examples/booleans.md
- docs/fomega/examples/lists.md
- docs/fomega/examples/lists/cons.plc
- docs/fomega/examples/lists/fold.plc
- docs/fomega/examples/lists/head.plc
- docs/fomega/examples/lists/nil.plc
- docs/fomega/examples/lists/tail.plc
- docs/fomega/no-fix-value/writeup.md
> Documentation

- language-plutus-core/README.md
- language-plutus-core/language-plutus-core.cabal
- language-plutus-core/run-ck/Main.hs
Lucas asked for a more convenient way to run programs using the CK machine.
> Added the 'run-ck' executable

- README.md
Fix an issue noticed by @effectfully
> Tweak readme about docs

- language-plutus-core/language-plutus-core.cabal
- language-plutus-core/src/Language/PlutusCore/Quote.hs
- language-plutus-core/src/Language/PlutusCore/TH.hs
Address comments from @effectfully .
> Quote.hs review changes

- docs/fomega/deep-isorecursive/proposal.md
I want to talk about this during the meeting in 45 minutes, and I figure it's unfair not to give everyone who isn't in Edinburgh something to look at.
> how to do isorecursive types at higher kinds

- .buildkite/hooks/pre-command
- .buildkite/pipeline.yml
- check-hydra.sh
- fetch-nixpkgs.nix
- fetchNixpkgs.nix
Adds a hydra eval buildkite job so CI gets alerted if the build has eval errors.
> [DEVOPS-1024] add hydra eval buildkite job

- git-pre-commit-hook
- language-plutus-core/generate-evaluation-test/Main.hs
- language-plutus-core/language-plutus-core.cabal
- language-plutus-core/run-ck/Main.hs
This fixes several warnings as well.
> Format cabal file and get rid of warnings

- language-plutus-core/src/Language/PlutusCore/Renamer.hs
- language-plutus-core/test/types/CGP277.plc
- language-plutus-core/test/types/CGP277.plc.golden
This fixes the renamer and adds a test.
It is based on @michaelpj's pull request.
> fix renamer

- language-plutus-core/bench/Bench.hs
- language-plutus-core/language-plutus-core.cabal
- language-plutus-core/test/Evaluation/TypeCheck.hs
- language-plutus-core/test/types/CGP277.plc
This also fixes some other things.
> Fix build of benchmarks

- language-plutus-core/src/Language/PlutusCore/TypeSynthesis.hs
This allows compilation with GHC 8.6.1, among other things.
> remove bad pattern match

- docs/fomega/evaluation/machines.md
A few more references on abstract machines.
> Added some abstract machine references

- docs/extended-utxo/README.md
* Add the 2x2 matrix of who signs what, and some notes on the wallet API extensions
> Expand UTxO model documentation

- language-plutus-core/language-plutus-core.cabal
This will be useful to users when they are using our library via Hackage.
> Add category to cabal file

- .hlint.yaml
- language-plutus-core/generate-evaluation-test/Main.hs
- language-plutus-core/language-plutus-core.cabal
- language-plutus-core/src/Language/PlutusCore.hs
- language-plutus-core/src/Language/PlutusCore/Evaluation/CkMachine.hs
- language-plutus-core/src/Language/PlutusCore/Evaluation/MachineException.hs
- language-plutus-core/src/Language/PlutusCore/Evaluation/Result.hs
- language-plutus-core/test/Evaluation/CkMachine.hs
Added the 'Evaluation' folder, moved the CK machine there, abstracted 'MachineException' and 'EvaluationResult'
> Preparations for merging the CEK machine in

- CONTRIBUTING.md
This is not all totally obvious and worth documenting.
> Add a note about adding a new package

- plutus-core-spec/figures/PlutusCoreTypeCorrectness.tex
as discussed in team meeting, I have updated the kind synthesis judgement figure to remove tyrec and change the type of tyfix, and have updated the type synthesis judgement figure, changing the wrap and unwrap rules.
> updated fix/wrap/unwrap

- plutus-core-spec/figures/PlutusCoreTypeCorrectness.tex
- plutus-core-spec/main.tex
> rewrote introduction

- docs/fomega/datatypes/fixpoints-and-type-lambdas.md
- docs/fomega/datatypes/matching-and-laziness.md
I'm not saying anything prescriptive about booleans yet, just laying out the options.
> Docs: add notes about laziness and pattern matching; and fixpoints and datatypes

- language-plutus-core/language-plutus-core.cabal
Fixes a warning that otherwise occurs during compilation
> fix cabal file

- language-plutus-core/src/Language/PlutusCore/TypeSynthesis.hs
Fixes code for type synthesis.
> use NormalizedType in state

- language-plutus-core/src/Language/PlutusCore.hs
- language-plutus-core/src/Language/PlutusCore/Lexer/Type.hs
- language-plutus-core/test/TypeSynthesis/Golden/AddInteger.plc.golden
- language-plutus-core/test/TypeSynthesis/Golden/Concatenate.plc.golden
- language-plutus-core/test/TypeSynthesis/Golden/DivideInteger.plc.golden
- language-plutus-core/test/TypeSynthesis/Golden/DropByteString.plc.golden
- language-plutus-core/test/TypeSynthesis/Golden/EqByteString.plc.golden
- language-plutus-core/test/TypeSynthesis/Golden/EqInteger.plc.golden
- language-plutus-core/test/TypeSynthesis/Golden/GreaterThanEqInteger.plc.golden
- language-plutus-core/test/TypeSynthesis/Golden/GreaterThanInteger.plc.golden
- language-plutus-core/test/TypeSynthesis/Golden/IntToByteString.plc.golden
- language-plutus-core/test/TypeSynthesis/Golden/LessThanEqInteger.plc.golden
- language-plutus-core/test/TypeSynthesis/Golden/LessThanInteger.plc.golden
- language-plutus-core/test/TypeSynthesis/Golden/MultiplyInteger.plc.golden
- language-plutus-core/test/TypeSynthesis/Golden/RemainderInteger.plc.golden
- language-plutus-core/test/TypeSynthesis/Golden/ResizeByteString.plc.golden
- language-plutus-core/test/TypeSynthesis/Golden/ResizeInteger.plc.golden
- language-plutus-core/test/TypeSynthesis/Golden/SHA2.plc.golden
- language-plutus-core/test/TypeSynthesis/Golden/SHA3.plc.golden
- language-plutus-core/test/TypeSynthesis/Golden/SubtractInteger.plc.golden
- language-plutus-core/test/TypeSynthesis/Golden/TakeByteString.plc.golden
- language-plutus-core/test/TypeSynthesis/Golden/TxHash.plc.golden
- language-plutus-core/test/TypeSynthesis/Golden/VerifySignature.plc.golden
- language-plutus-core/test/TypeSynthesis/Spec.hs
Please check the golden files.
> [CGP-364] [Tests] [Type checker] Added tests for 'typeOfBuiltinName'

- .hlint.yaml
- pkgs/default.nix
- plutus-use-cases/plutus-use-cases.cabal
- plutus-use-cases/src/Language/Plutus/Coordination/Contracts.hs
- plutus-use-cases/src/Language/Plutus/Coordination/Contracts/CrowdFunding.hs
- plutus-use-cases/src/Language/Plutus/Coordination/Contracts/Vesting.hs
- plutus-use-cases/src/Language/Plutus/Runtime.hs
- plutus-use-cases/test/Spec.hs
- plutus-use-cases/test/Spec/Vesting.hs
* Add a vesting scheme in which funds are released in two tranches
* Add some test cases using the emulator
The tests are not exhaustive, but I would prefer to not add any more tests until https://iohk.myjetbrains.com/youtrack/issue/CGP-228 is implemented because the current situation (all PLC values have to be written in TH at compile time) causes a lot of duplication in the code and makes the tests & contracts harder to read.
> [CGP-304] Add vesting contract

- docs/fomega/evaluation/machines.md
Sorry about the multiple commits: it's difficult to tell how it's going to render until it's actually on GitHub.  Also, GitHub doesn't appear to support ftp links.  
I tried to fix the multiple commits by doing what it said on https://stackoverflow.com/questions/5667884/how-to-squash-commits-in-git-after-they-have-been-pushed but that doesn't seem to have worked.  Is it possible to squash everything into one during the merge?
> Added some lazy machine references to the 

- .hlint.yaml
- plutus-use-cases/plutus-use-cases.cabal
- plutus-use-cases/src/Language/Plutus/Coordination/Contracts/CrowdFunding.hs
- plutus-use-cases/src/Language/Plutus/Coordination/Contracts/Swap.hs
- plutus-use-cases/src/Language/Plutus/Coordination/Contracts/Vesting.hs
- plutus-use-cases/src/Language/Plutus/Runtime.hs
- plutus-use-cases/src/Language/Plutus/Runtime/TH.hs
- plutus-use-cases/src/Language/Plutus/Runtime/Types.hs
- plutus-use-cases/test/Spec/Crowdfunding.hs
- plutus-use-cases/test/Spec/TH.hs
- wallet-api/src/Wallet/API.hs
- wallet-api/src/Wallet/Generators.hs
- wallet-api/src/Wallet/UTXO.hs
* Transactions and their inputs can have signatures
* Properly check signatures in crowdfunding script
* `Language.Plutus.Runtime.TH` module for common functions
> Add signatures to mockchain

- wallet-api/src/Wallet/Emulator/Types.hs
- wallet-api/test/Spec.hs
This means we can use them in the http api
Once this PR has been merged I will add assertions as endpoints to the http api and fit it into the Trace api.
> Hardcoded Trace Assertions rather than arbitrary functions

- core-to-plc/src/Language/Plutus/CoreToPLC.hs
- core-to-plc/src/Language/Plutus/CoreToPLC/Definitions.hs
- core-to-plc/src/Language/Plutus/CoreToPLC/PLCTypes.hs
I'm going to attempt dismembering `CoreToPLC.hs` in another PR, but that's going to conflict with everything ever, so I want to do it in one go.
> Address comments on #209

- CONTRIBUTING.md
- core-to-plc/core-to-plc.cabal
- language-plutus-core/README.md
- language-plutus-core/language-plutus-core.cabal
- language-plutus-core/src/Language/PlutusCore/Constant/Typed.hs
- language-plutus-core/stdlib/Language/PlutusCore/StdLib/Data/Function.hs
- plutus-core-interpreter/plutus-core-interpreter.cabal
- plutus-exe/plutus-exe.cabal
- plutus-prototype/plutus-prototype.cabal
- plutus-th/plutus-th.cabal
- plutus-use-cases/plutus-use-cases.cabal
- plutus-use-cases/src/Language/Plutus/Runtime.hs
- wallet-api/wallet-api.cabal
These links will work, but better to use the right ones.
> Fix references to old repository name

- docs/plutus-ir/plutus-ir.md
This is a first draft of a design document for Plutus IR (name
bikeshedding welcome in general).
We should bear in mind that we can change the details of Plutus IR much
more easily, so even if we're unsure we can start with one approach and
see if it works out.
> Plutus IR: initial design draft

- language-plutus-core/generators/Language/PlutusCore/Generators/Internal/Denotation.hs
- language-plutus-core/language-plutus-core.cabal
- language-plutus-core/prelude/PlutusPrelude.hs
- language-plutus-core/src/Language/PlutusCore/CBOR.hs
- language-plutus-core/src/Language/PlutusCore/Constant/Apply.hs
- language-plutus-core/src/Language/PlutusCore/Constant/Typed.hs
- language-plutus-core/src/Language/PlutusCore/Lexer.x
- language-plutus-core/src/Language/PlutusCore/Lexer/Type.hs
- language-plutus-core/test/Evaluation/Constant/Success.hs
This adds `quotientInteger` and `remainderInteger` as per the spec.
> add quotientInteger and remainderInteger

- .gitignore
- plutus-core-spec/main.tex
This PR removes a bunch of old newcommands that are no longer used, and reorganizes the definitions to be more readable and skimmable.
> Cleanup newcommands

- CONTRIBUTING.md
Missed this when I updated the other docs.
> CONTRIBUTING.md: update for changes to build infra

- .hlint.yaml
- default.nix
- plutus-ir/src/Language/PlutusIR/Compiler/Term.hs
- plutus-ir/test/Spec.hs
I forgot to add it to the list of projects that hlint runs on when I
added it, and then that got carried over to the new hlint test.
> Make plutus-ir pass hlint

- shell.nix
Another bit of fallout from the iohk-nix business.
> Fix fixStylishHaskell

- wallet-api/src/Wallet/Emulator/AddressMap.hs
- wallet-api/src/Wallet/Emulator/Http.hs
- wallet-api/src/Wallet/Emulator/Types.hs
- wallet-api/src/Wallet/UTXO/Types.hs
- wallet-api/test/Spec.hs
- wallet-api/wallet-api.cabal
I still need to run `./pkgs/generate.sh` - for some reason it is hanging.
> Use lens instead of microlens for fewer dependencies

- pkgs/default.nix
> Update nix packages

- plutus-use-cases/test/Spec/Crowdfunding.hs
- plutus-use-cases/test/Spec/Future.hs
- plutus-use-cases/test/Spec/Vesting.hs
- wallet-api/src/Wallet/Emulator/Http.hs
- wallet-api/src/Wallet/Emulator/Types.hs
- wallet-api/test/Spec.hs
* Replace hand-written lenses with TH-generated ones
> wallet-api: makeLenses

- language-plutus-core/src/Language/PlutusCore/Constant/Dynamic/BuiltinName.hs
- language-plutus-core/src/Language/PlutusCore/Constant/Dynamic/Instances.hs
- plutus-core-interpreter/test/DynamicBuiltins/Logging.hs
- plutus-core-interpreter/test/DynamicBuiltins/String.hs
> Returned dynamic chars

- plutus-use-cases/src/Language/Plutus/Coordination/Contracts/CrowdFunding.hs
- wallet-api/src/Wallet/API.hs
- wallet-api/src/Wallet/Emulator/Types.hs
* Add `LoggingWallet` type with the ability to log messages and throw
errors
> [CGP-438] Log text messages in WalletAPI

- docs/fomega/deep-isorecursive/TreeForest.md
Wrote a 150 lines doc, then realized that it's better to throw away most of it.
> [CGP-428] [Docs] Added the 'TreeForest' example

- default.nix
- iohk-nix.json
- lib.nix
- nix/overlays/required.nix
- pkgs/regen.nix
- release.nix
- shell.nix
I think this is doing the right thing!
Also a few other minor fixes.
> Bump iohk nix and fix platform passing

- wallet-api/src/Wallet/Emulator/Types.hs
* Get the final distribution of funds from an `EmulatorState`
> wallet-api: Add `fundsDistribution`

- default.nix
- pkgs/default.nix
- plutus-use-cases/README.md
- plutus-use-cases/plutus-use-cases.cabal
- plutus-use-cases/src/Language/PlutusTx/Coordination/Contracts/CrowdFunding.hs
- plutus-use-cases/src/Language/PlutusTx/Coordination/Contracts/Future.hs
- plutus-use-cases/src/Language/PlutusTx/Coordination/Contracts/Swap.hs
- plutus-use-cases/src/Language/PlutusTx/Coordination/Contracts/Vesting.hs
- plutus-use-cases/tutorial/Tutorial.lhs
- plutus-use-cases/tutorial/Tutorial.md
- plutus-use-cases/tutorial/tutorial-doctests.hs
- wallet-api/src/Ledger/Index.hs
- wallet-api/src/Ledger/Types.hs
- wallet-api/src/Ledger/Validation.hs
- wallet-api/src/Wallet/API.hs
- wallet-api/src/Wallet/Emulator.hs
- wallet-api/src/Wallet/Emulator/Client.hs
- wallet-api/src/Wallet/Emulator/Http.hs
- wallet-api/src/Wallet/Emulator/Types.hs
- wallet-api/test/Spec.hs
* Add a tutorial that shows how the crowdfunding contract works
> plutus-use-cases: Add tutorial

- wallet-api/src/Wallet/Emulator/Types.hs
- wallet-api/test/Spec.hs
* In some cases the coin selection algorithm did not select enough funds
to spend.
> wallet-api: Fix bug in coin selection

- plutus-playground/plutus-playground-server/src/Playground/Server.hs
Previously the interpreter would time out on the request time
however this means if there is a queue of requests waiting for the
interpreter, they will time out. That's not fair!
This commit changes things so that the timeout only starts counting
when the interpreter is run
> Fix interpreter timeout

- README.md
Adds a small glossary to the readme. Not trying to be comprehensive, just give simple definitions of a few key terms.
> Add a glossary to the readme

- plutus-playground/plutus-playground-lib/plutus-playground-lib.cabal
- plutus-playground/plutus-playground-lib/src/Playground/Contract.hs
- plutus-playground/plutus-playground-server/src/Playground/Interpreter.hs
- plutus-playground/plutus-playground-server/test/Playground/UsecasesSpec.hs
- plutus-playground/plutus-playground-server/usecases/CrowdFunding.hs
- plutus-playground/plutus-playground-server/usecases/Game.hs
- plutus-playground/plutus-playground-server/usecases/Messages.hs
- plutus-playground/plutus-playground-server/usecases/Vesting.hs
- plutus-tx/plutus-tx.cabal
- plutus-tx/src/Language/PlutusTx/Prelude.hs
- plutus-use-cases/src/Language/PlutusTx/Coordination/Contracts/CrowdFunding.hs
- plutus-use-cases/src/Language/PlutusTx/Coordination/Contracts/Future.hs
- plutus-use-cases/src/Language/PlutusTx/Coordination/Contracts/Vesting.hs
- wallet-api/src/Ledger/Validation.hs
- wallet-api/src/Wallet/API.hs
- wallet-api/test/Spec.hs
* Add hashes to guessing game
* Add trigger to vesting contract
(based on #392)
> playground: Guessing game with hashes

- pkgs/default.nix
- wallet-api/src/Wallet/Emulator/Types.hs
- wallet-api/src/Wallet/Generators.hs
- wallet-api/test/Spec.hs
- wallet-api/wallet-api.cabal
* Adds a proper test for coin selection 
* Fixes a bug introduced in #382 ...
> wallet-api: Property tests for coin selection

- plutus-playground/Changelog.md
- plutus-playground/plutus-playground-server/usecases/CrowdFunding.hs
- plutus-playground/plutus-playground-server/usecases/Game.hs
* More comments in documentation
* Fix some inconsistencies
* Add changelog
> playground: Docs, etc.

- plutus-core-spec/plutus-core-specification.tex
> Some small corrections to the spec

- plutus-tx/tutorial/Tutorial.md
Added a bit more of an intro, and I also ended up writing a more detailed explanation of the type of `compile` and the general staged programming approach.
> Plutus Tx tutorial: add intro and explain staged programming more

- wallet-api/tutorial/Tutorial.md
> fix link to plutus-tx tutorial

- language-plutus-core/generators/Language/PlutusCore/Generators/Interesting.hs
- language-plutus-core/generators/Language/PlutusCore/Generators/Test.hs
- plutus-exe/src/Main.hs
As per request of the RV team. Also fixed a few typos.
> [Test] Added a naive exponential function computing fibonacci numbers

- language-plutus-core/test/Spec.hs
This is a bit nicer, and gives better output when it fails. 
I also happened to find a bug this way: the current
term generators will generate integers which are outside their sizes,
causing the parser to give an overflow error when we parse it. I
don't know how this didn't trigger before. For now I just made sure that
the generators always generate big enough sizes, in the long run this
should presuambly use Roman's fancier sized generators, but I don't
know how to do that atm.
> language-plutus-core: use Hedgehog's tripping assertion

- docs/fomega/mutual-term-level-recursion/FixN.agda
> [Docs] Fixed universe levels in an Agda doc

- wallet-api/tutorial/Tutorial.md
A number of small fixes that don't require changes to the API
> wallet-api: Tutorial fixes

- plutus-playground/deployment/nixops/playground.nix
- plutus-playground/plutus-playground-client/src/Editor.purs
- plutus-playground/plutus-playground-client/src/MainFrame.purs
- plutus-playground/plutus-playground-client/src/Types.purs
- plutus-playground/plutus-playground-lib/src/Playground/API.hs
- plutus-playground/plutus-playground-server/app/PSGenerator.hs
- plutus-playground/plutus-playground-server/src/Playground/Interpreter.hs
- plutus-playground/plutus-playground-server/src/Playground/Server.hs
- plutus-playground/plutus-playground-server/test/Playground/UsecasesSpec.hs
If you neglect to add a `mkFunctions` call then you will get a nice warning but not an error. It also means that you will get compiler errors that would have been hidden by an obscure error because you didn't add this function. If you don't add this function you will still have `payToPublicKey` available.
> Playground warnings

- plutus-playground/plutus-playground-client/src/MainFrame.purs
See https://github.com/ajaxorg/ace/issues/905 for why the previous
code should have been right, but wasn't. :-D
> Playground: Bugfix for #472 - Compiler error annotations aligned incorrectly.

- wallet-api/tutorial/Tutorial.md
* links to haddocks
* (WalletAPI m) instead of MockWallet
* Explain intervals
* Comments and clarifications
> wallet-api: Tutorial

- plutus-playground/plutus-playground-server/usecases/CrowdFunding.hs
- plutus-playground/plutus-playground-server/usecases/Vesting.hs
- plutus-tx/compiler/Language/PlutusTx/Builtins.hs
- plutus-tx/src/Language/PlutusTx/Prelude.hs
- plutus-tx/src/Language/PlutusTx/Prelude/Stage0.hs
- plutus-use-cases/src/Language/PlutusTx/Coordination/Contracts/CrowdFunding.hs
- wallet-api/tutorial/Tutorial.md
* Export the operators from 'Num Int' and 'Ord Int' as quoted template
Haskell expressions for greater consistency with the rest of the
Plutus prelude
> plutus-tx: Quoted 'Int' operators

- plutus-tx/tutorial/Tutorial.md
There is a broken link. I believe its referring to this tutorial?
> Broken Link in Tutorial.md

- nix/overlays/required.nix
- pkgs/default.nix
- wallet-api/test/Spec.hs
- wallet-api/wallet-api.cabal
Rewrite wallet-api.cabal in the style of plutus-tx.cabal.
Just putting this up for a test.
> wallet-api: Cabal file

- plutus-playground/plutus-playground-client/src/MainFrame.purs
Te linked file was moved in 5b9e7970aeb69d581645b24231b63a1754aa3327.
> Fixing a link to the tutorial from the playground.

- wallet-api/src/Ledger/Types.hs
I tried the simplest thing just to see if this helps. @vmchale can you check if this makes a difference to your profiles?
----
This saves us from repeated serializing and deserializing during
`applyProgram`. We still serialize to do comparisons, since we don't
have an `Ord` instance for `Program`, but this is *probably* okay.
If we still show up as spending lots of time on serialization, we can
switch to doing something with hashing.
If we show up as doing lots of *deserialization* then that's interesting - 
the only place that turns up is deserializing the main script, so that would
imply it is very big (quite possible) or our serialization code is slow.
> wallet-api: don't store scripts serialized

- language-plutus-core/language-plutus-core.cabal
- language-plutus-core/src/Language/PlutusCore/Lexer.x
- language-plutus-core/src/Language/PlutusCore/Name.hs
- language-plutus-core/src/Language/PlutusCore/Parser.y
This closes https://github.com/input-output-hk/plutus/issues/527
> Remove redundant bits of identifier state

- marlowe/marlowe.cabal
- plutus-ir/plutus-ir.cabal
- plutus-playground/plutus-playground-lib/plutus-playground-lib.cabal
- plutus-playground/plutus-playground-server/plutus-playground-server.cabal
- plutus-tutorial/plutus-tutorial.cabal
- wallet-api/wallet-api.cabal
This removes various redundant packages from the relevant `.cabal` files.
> remove redundant packages

- language-plutus-core/test/Spec.hs
- language-plutus-core/test/evaluation/verifySignature.plc
- language-plutus-core/test/evaluation/verifySignature.plc.golden
This adds `verifySignature.plc.golden` which was mistakenly not added with a past PR.
> Add verifySignature.plc.golden

- docs/multi-currency/multi-currency.md
Add a summary of the new proposal for multi-currency ledger. I pulled the content from #536 and the mailing list and tried to make it self-contained.
> docs: Describe multi-currency proposal

- docs/raml/README.md
I wrote this at the start of January and almost finished it but got distracted.  It's still not quite complete, but I'll fix it at some later date.  The essential information is in this version.
> Updated RAML notes

- cabal.project
Update the `cabal.project` file
> Add interpreter package

- plutus-playground/deployment/nixops/meadow.nix
- plutus-playground/deployment/nixops/playground.nix
* better sandboxing of plutus playground and meadow services
* rate limiting
> improve security of playground and meadow

- cabal.project
> Add meadow

- docs/multi-currency/multi-currency.md
I've written up the less conservative proposal, since I think it's both simpler and better.
> Writeup of native NFT proposal

- plutus-playground-client/src/Action.purs
- plutus-playground-client/src/Wallet.purs
My mistake - I had the wrong event type, so we only got changes when the
user tabbed out of the form field, not as soon as something was typed.
> Playground: Changing some input form handlers so they fire more responsively.

- plutus-playground-server/test/Playground/UsecasesSpec.hs
- plutus-playground-server/usecases/Vesting.hs
* Vesting example now has a proper "withdraw" endpoint that locks the
remaining funds in the scheme.
> playground: Better vesting example

- language-plutus-core/src/Language/PlutusCore/Constant/Make.hs
- language-plutus-core/src/Language/PlutusCore/MkPlc.hs
- language-plutus-core/stdlib/Language/PlutusCore/StdLib/Data/Bool.hs
- language-plutus-core/stdlib/Language/PlutusCore/StdLib/Data/ChurchNat.hs
- language-plutus-core/stdlib/Language/PlutusCore/StdLib/Data/Function.hs
- language-plutus-core/stdlib/Language/PlutusCore/StdLib/Data/Integer.hs
- language-plutus-core/stdlib/Language/PlutusCore/StdLib/Data/List.hs
- language-plutus-core/stdlib/Language/PlutusCore/StdLib/Data/Nat.hs
- language-plutus-core/stdlib/Language/PlutusCore/StdLib/Data/Sum.hs
- language-plutus-core/stdlib/Language/PlutusCore/StdLib/Data/Unit.hs
- language-plutus-core/stdlib/Language/PlutusCore/StdLib/Meta.hs
- language-plutus-core/stdlib/Language/PlutusCore/StdLib/Meta/Data/Tuple.hs
- language-plutus-core/stdlib/Language/PlutusCore/StdLib/Type.hs
- language-plutus-core/test/Evaluation/CkMachine.hs
- language-plutus-core/test/evaluation/verifySignature.plc.golden
- plutus-ir/src/Language/PlutusIR/Compiler/Recursion.hs
Final encoding of PLC terms, the lesser of two evils, as discussed in #610
> [PLC] Final-encode PLC terms to allow for more sharing with the PIR compiler

- .hlint.yaml
- plutus-tutorial/doctest/Tutorial/03-wallet-api.md
- plutus-tutorial/plutus-tutorial.cabal
- plutus-tutorial/tutorial/Tutorial/ExUtil.hs
- plutus-tutorial/tutorial/Tutorial/Solutions0.hs
- plutus-tutorial/tutorial/Tutorial/Solutions0Mockchain.hs
- plutus-tutorial/tutorial/Tutorial/Vesting.hs
Add solutions for the problems in wallet API tutorials I and II
> plutus-tutorial: Solutions

- language-plutus-core/src/Language/PlutusCore/Constant/Dynamic/Instances.hs
Can't believe I spent that much time thinking about a trivial problem. We can easily unlift recursive structures provided we know how to sensibly unlift sums and products (which we don't currently, we use `unsafePerformIO` there, but this is surely an easier task than the one that we had previously).
> [PLC] [Builtins] Changed unlifting ot lists to a straightforward one

- default.nix
I removed this since it doesn't work on darwin.
> Fix shell.nix mistake

- default.nix
> And another mistake

- wallet-api/src/Ledger/Ada.hs
- wallet-api/src/Ledger/Ada/TH.hs
- wallet-api/src/Ledger/Index.hs
- wallet-api/src/Ledger/Interval.hs
- wallet-api/src/Ledger/Types.hs
- wallet-api/src/Ledger/Value.hs
- wallet-api/src/Ledger/Value/TH.hs
- wallet-api/src/Wallet/API.hs
- wallet-api/src/Wallet/Emulator/AddressMap.hs
- wallet-api/src/Wallet/Emulator/Client.hs
- wallet-api/src/Wallet/Emulator/Http.hs
- wallet-api/src/Wallet/Emulator/Types.hs
More to come, but this is what I did this morning.
> wallet-api: round 1 of Haddocks

- wallet-api/src/Ledger/Types.hs
- wallet-api/src/Ledger/Validation.hs
- wallet-api/src/Wallet/API.hs
- wallet-api/src/Wallet/Generators.hs
- wallet-api/src/Wallet/Graph.hs
This is a rough first pass, some things could do with some examples etc. I'm going to do some housekeeping next and maybe slim things down a little, which will also reduce the documentation effort.
> wallet-api: more Haddocks

- plutus-playground-client/src/Action.purs
- plutus-playground-client/src/AjaxUtils.purs
- plutus-playground-client/src/Bootstrap.purs
- plutus-playground-client/src/Gists.purs
- plutus-playground-client/src/MainFrame.purs
- plutus-playground-client/static/main.scss
- plutus-playground-client/test/MainFrameTests.purs
...and some small improvements to affected unit tests.
> Playground UI/UX improvements.

- wallet-api/src/Ledger/Map.hs
- wallet-api/src/Ledger/Map/TH.hs
- wallet-api/src/Ledger/Value/TH.hs
```
*> Aeson.encode (Ledger.Map.fromList [(0 :: Int, 1 :: Int), (2, 12)])
"{\"0\":1,\"2\":12}"
*> Aeson.decode @(Ledger.Map.TH.Map Int Int) (Aeson.encode (Ledger.Map.fromList [(0 :: Int, 1 :: Int), (2, 12)]))
Just (Map {unMap = [(0,1),(2,12)]})
```
> wallet-api: JSON instances for Ledger.Map

- meadow-client/src/MainFrame.purs
- meadow-client/src/Simulation.purs
- meadow-client/src/StaticData.purs
- meadow/app/PSGenerator.hs
- meadow/contracts/Escrow.hs
- meadow/src/Meadow/Contracts.hs
- meadow/src/Server.hs
- meadow/test/Spec.hs
See issues #798, #799, and #800.
> Small fixes in Meadow 2.0 for clarity and usability

- README.md
> Make the README louder about enabling the binary caches

- web-common/static/main.scss
This was easier than I expected. :-D
> Fix #756: Improve the editor display size.

- plutus-tutorial/README.md
- plutus-tutorial/doctest/Tutorial/01-plutus-tx.md
- plutus-tutorial/tutorial/Intro.md
- plutus-tx/README.md
I think it's probably now readable as part of the main series of tutorials?
> plutus-tx: improve tutorial

- cabal.project
This makes things usable with cabal-install
> Add plutus-contract-exe to cabal

- cabal.project
- interpreter/interpreter.cabal
- interpreter/src/Servant/Extra.hs
- interpreter/src/Servant/Prometheus.hs
- iohk-nix.json
- lib.nix
- marlowe/test/Spec/Common.hs
- meadow/meadow.cabal
- pkgs/default.nix
- plutus-ir/plutus-ir.cabal
- plutus-ir/src/Language/PlutusIR/Optimizer/DeadCode.hs
- plutus-ir/src/Language/PlutusIR/Parser.hs
- plutus-ir/test/TestLib.hs
- plutus-playground-server/plutus-playground-server.cabal
- plutus-playground-server/src/Servant/Extra.hs
- plutus-tutorial/doctest/Tutorial/01-plutus-tx.md
- plutus-tutorial/plutus-tutorial.cabal
- plutus-tx/compiler/Language/PlutusTx/Compiler/Expr.hs
- plutus-tx/compiler/Language/PlutusTx/Compiler/Kind.hs
- plutus-tx/compiler/Language/PlutusTx/Plugin.hs
- plutus-tx/plutus-tx.cabal
- plutus-tx/test/Lift/nested.plc.golden
- plutus-tx/test/Plugin/errors/integer.plc.golden
- stack.yaml
- wallet-api/test/Spec.hs
Putting this up in case the GHCJS folks are interested. I'm getting 8.6.4 into `iohk-nix`, then I'll bump to that, then it's probably worth merging.
> Update to GHC 8.6.4

- plutus-playground-lib/src/Playground/Interpreter/Util.hs
- plutus-playground-server/test/Playground/UsecasesSpec.hs
> fix 'runTrace'

- plutus-tx/compiler/Language/PlutusTx/Builtins.hs
- plutus-tx/compiler/Language/PlutusTx/Compiler/Builtins.hs
- plutus-tx/src/Language/PlutusTx/Prelude.hs
- plutus-tx/src/Language/PlutusTx/Prelude/Stage0.hs
- plutus-tx/test/Lift/boolInterop.plc.golden
- plutus-tx/test/Plugin/primitives/andApply.plc.golden
- plutus-tx/test/Plugin/primitives/equalsByteString.plc.golden
- plutus-tx/test/Plugin/primitives/intEqApply.plc.golden
- plutus-tx/test/Plugin/recursiveFunctions/even3.plc.golden
- plutus-tx/test/Plugin/recursiveFunctions/even4.plc.golden
- plutus-tx/test/Plugin/recursiveTypes/sameEmptyRoseEval.plc.golden
- plutus-tx/test/TH/all.plc.golden
It's broken, and I don't know how to fix it yet.
> Remove resizeBytestring for now

- plutus-playground-lib/plutus-playground-lib.cabal
Everything seems to be working fine with nix but we might as well get it working with cabal
> Add hspec-discover dep

- language-plutus-core/src/Language/PlutusCore/Pretty/Readable.hs
Just some minor improvements of the mixfix pretty-printing framework.
> [PLC] [Textual] Improved readable pretty-printing

- deployment/nixops/prometheus.nix
These are the only alerts I think we need for the summit. This PR only sets up the triggering of them (tested on a staging env), in addition we need to point prometheus to an alert manager.
> add basic prometheus alerts

- plutus-exe/src/Main.hs
This adds "interesting" examples to `plutus-exe`, so that James can use them for testing `plc-agda`.
> [PlutusExe] Added interesting examples

- wallet-api/src/Wallet/API.hs
* 'collectFromScriptTxn' prints a warning if
an empty transaction is produced
* Also clean up the implementation a little.
> wallet-api: Warn on empty transaction

- shell.nix
Otherwise it does annoying IFD every time you commit.
> Pass a fake revision when loading in the nix-shell

- deployment/nixpkgs-src.json
- deployment/shell.nix
* terraform
* aws_shell
* awscli
> add shell.nix with pinned 19.03 nixpkgs containing

- plutus-playground-client/src/Action.purs
- plutus-playground-client/src/MainFrame.purs
- plutus-playground-client/src/Wallet.purs
- web-common/src/Bootstrap.purs
- web-common/static/main.scss
This isn't the whole story for mobile support, but by golly it goes a
long way towards it.
> Playground: Improved responsive display.

- plutus-playground-client/src/MainFrame.purs
- web-common/src/Bootstrap.purs
- web-common/static/main.scss
> Playground: Adding a CHANGELOG banner.

- plutus-playground-server/test/Playground/UsecasesSpec.hs
- plutus-playground-server/usecases/Game.hs
- plutus-playground-server/usecases/Vesting.hs
> playground: Multi-currency in game and vesting

- plutus-core-spec/figures/PlutusCoreBuiltins.tex
- plutus-core-spec/figures/PlutusCoreExampleAgain.tex
- plutus-core-spec/plutus-core-specification.tex
Merging documentation.
Actually, let's not merge it just yet in case I notice something that needs fixed.
> Explain the role of singleton types in sizes; improve typesetting

- pkgs/default.nix
Not sure why this causes a change but it does seem to.
> Run ./pkgs/generate.sh

- plutus-playground-server/test/Playground/UsecasesSpec.hs
- plutus-playground-server/usecases/CrowdFunding.hs
- plutus-use-cases/src/Language/PlutusTx/Coordination/Contracts/CrowdFunding.hs
- plutus-use-cases/test/Spec/Crowdfunding.hs
* Gets rid of the "NegativeNumber" error that appears occasionally in the logs
* Uses wallet ID (int) instead of wallet public key to identify campaign owner
> playground: Better crowdfunding example

- meadow-client/src/Data/BigInteger.purs
- meadow-client/src/MainFrame.purs
- meadow-client/src/Marlowe/Semantics.purs
- meadow-client/src/Marlowe/Test.purs
- meadow-client/src/Marlowe/Types.purs
- meadow-client/src/Simulation.purs
- meadow-client/src/Types.purs
- meadow-client/test/Main.purs
- meadow-client/test/Marlowe/ContractTests.purs
There is currently a lot of boiler plate, I think we just need a load of smart constructors in `Marlowe.Test` but suggestions would be welcome.
> Marlowe tests

- plutus-playground-client/.gitignore
- plutus-playground-client/package.json
...to generate Haddock-style PureScript docs.
> Playground: Adding `yarn docs` command.

- language-plutus-core/src/Language/PlutusCore.hs
- plutus-tx/compiler/Language/PlutusTx/Compiler/Error.hs
- plutus-tx/compiler/Language/PlutusTx/Plugin.hs
This makes it such that the plugin checks the value restriction as well as checking types.
> Plugin now checks value restriction as well as type

- plutus-use-cases/src/Language/PlutusTx/Coordination/Contracts/CrowdFunding.hs
- plutus-use-cases/src/Language/PlutusTx/Coordination/Contracts/Currency.hs
- plutus-use-cases/src/Language/PlutusTx/Coordination/Contracts/Currency/Stage0.hs
- plutus-use-cases/src/Language/PlutusTx/Coordination/Contracts/GameStateMachine.hs
- plutus-use-cases/src/Language/PlutusTx/Coordination/Contracts/MultiSig/Stage0.hs
- plutus-use-cases/src/Language/PlutusTx/Coordination/Contracts/MultiSigStateMachine.hs
- plutus-wallet-api/src/Language/PlutusTx/StateMachine.hs
Depends on https://github.com/input-output-hk/plutus/pull/1019
> plutus-use-cases: remove the last bit of TH

- language-plutus-core/src/Language/PlutusCore/Quote.hs
- plutus-tx/compiler/Language/PlutusTx/Compiler/Expr.hs
- plutus-tx/compiler/Language/PlutusTx/Plugin.hs
- plutus-tx/test/Plugin/Laziness/Spec.hs
- plutus-tx/test/Plugin/Laziness/lazyDepUnit.plc.golden
> plutus-tx: lazy bindings need a dependency on unit

- docs/extended-utxo/ValidatingTheNextDataScript.md
This adds an overview of the problem. It's a stub and needs to be expanded, but I do not have any more time for this. I started writing the doc, because I thought I had a good solution, but it turned out that the Haskell's `Typeable` approach is the best approach I have and it's neither something new, nor terrible appealing.
We still need to describe all the alternatives and their trade-offs, though, and discuss the topic once again.
> [Docs] Added the validating the next data script doc

- plutus-use-cases/src/Language/PlutusTx/Coordination/Contracts/Game.hs
- plutus-use-cases/src/Language/PlutusTx/Coordination/Contracts/GameStateMachine.hs
- plutus-use-cases/src/Language/PlutusTx/Coordination/Contracts/Vesting.hs
- plutus-use-cases/test/Spec/Game.hs
- plutus-use-cases/test/Spec/GameStateMachine.hs
- plutus-use-cases/test/Spec/Vesting.hs
> plutus-use-cases: make game and vesting multi-currency aware

- plutus-tutorial/plutus-tutorial.cabal
- plutus-tx/README.md
- plutus-use-cases/plutus-use-cases.cabal
Fixes #1046. Also added a note in the readme, but this
is something we'll probably just have to whack-a-mole
a bit.
> Set -fobject-code in cabal files where appropriate

- extended-utxo-spec/extended-utxo-specification.tex
I'm abandoning the old branch kwxm/extended-utxo-spec because there are a lot of conflicts with the master branch (caused by me accidentally making another branch off the previous spec branch and then merging with master).
> New branch for EUTXO spec

- plutus-tutorial/plutus-tutorial.cabal
- plutus-tx/README.md
- plutus-use-cases/plutus-use-cases.cabal
- plutus-wallet-api/plutus-wallet-api.cabal
> plutus-wallet-api: add options for ghci

- marlowe/src/Language/Marlowe/Client.hs
- marlowe/src/Language/Marlowe/Common.hs
- marlowe/test/Spec/Actus.hs
- marlowe/test/Spec/Marlowe.hs
While I'm at it. More simplifications we could do, but this helps already.
> marlowe: purge TH

- marlowe/src/Language/Marlowe/Common.hs
- plutus-tutorial/doctest/Tutorial/01-plutus-tx.md
- plutus-tx/README.md
- plutus-tx/compiler/Language/PlutusTx/Compiler/Expr.hs
- plutus-tx/compiler/Language/PlutusTx/Compiler/Type.hs
- plutus-tx/src/Language/PlutusTx/Prelude.hs
- plutus-tx/test/TH/all.plc.golden
- plutus-use-cases/src/Language/PlutusTx/Coordination/Contracts/MultiSigStateMachine.hs
- plutus-use-cases/src/Language/PlutusTx/Coordination/Contracts/Vesting.hs
- plutus-wallet-api/ledger/Ledger/Ada.hs
- plutus-wallet-api/ledger/Ledger/Map.hs
- plutus-wallet-api/ledger/Ledger/These.hs
- plutus-wallet-api/ledger/Ledger/Validation.hs
- plutus-wallet-api/ledger/Ledger/Value.hs
- plutus-wallet-api/src/Language/PlutusTx/StateMachine.hs
Fixes #1057.
Seems to work! Cuts down on the annotation load a lot.
I did have to add a couple more hacks to deal with some awkward optimization, but I can live with them.
> plutus-tx: try using `-fexpose-all-unfoldings`

- default.nix
- docs/multi-currency/IEEEtran.bst
- docs/multi-currency/default.nix
It was also missing the bibliography style file.
> Add nix build for multi-currency paper

- plutus-playground-server/plutus-playground-server.cabal
Courtesy of @brunjlar (who can't contribute to this repo yet)
> Add dep. on plutus-playground-usecases to make stack happy

- cabal.project
> Bump max-backjumps

- .gitignore
- default.nix
- docs/fomega/lazy-machine/default.nix
- docs/multi-currency/default.nix
- extended-utxo-spec/default.nix
- nix/latex.nix
- plutus-core-spec/default.nix
Factors out a bunch of repeated work. Plus now e.g. all the docs advertise themselves on hydra.
> Add a latex builder

- meadow-client/src/MainFrame.purs
- meadow-client/src/MonadApp.purs
- meadow-client/src/Simulation.purs
- meadow-client/src/Types.purs
- plutus-playground-client/src/MonadApp.purs
- web-common/src/Editor.purs
This will allow us to write tests for the `evalF` function. This is quite important because some of the logic of the simulation is quite tricky. Now we could write property tests for the Undo button for example.
This is quite a big PR already so tests can come separately.
> add MonadApp class for meadow

- iohk-nix.json
- release.nix
Should be able to build the update script on macOS now.
> Bump iohk-nix for iconv fix

- plutus-core-spec/Makefile
- plutus-core-spec/figures/CkMachine.tex
- plutus-core-spec/plutus-core-specification.bib
- plutus-core-spec/plutus-core-specification.tex
Reverts input-output-hk/plutus#1146
> Revert "Kwxm/core spec updates"

- plutus-core-spec/plutus-core-specification.tex
Reverts input-output-hk/plutus#1155
Damn!  Still didn't work.
> Revert "Kwxm/core spec updates2"

- plutus-emulator/src/Wallet/Emulator/Types.hs
Adds `runTraceChainDefault :: EmulatorAction a -> (Either AssertionError a, EmulatorState)` and `runTraceChainDefaultWallet :: MockWallet a -> (Either AssertionError (Either WalletAPIError a, [Tx]), EmulatorState)` for testing emulator & wallet actions on a mockchain with default settings. 
cc @krisajenkins
> Add functions for running traces with defaults

- marlowe/src/Language/Marlowe/Client.hs
- plutus-emulator/src/Wallet/Emulator/Types.hs
- plutus-playground-server/usecases/CrowdFunding.hs
- plutus-playground-server/usecases/Vesting.hs
- plutus-tutorial/doc/03-wallet-api.adoc
- plutus-tutorial/doc/04-vesting.adoc
- plutus-tx/plutus-tx.cabal
- plutus-tx/src/Language/PlutusTx/Monoid.hs
- plutus-tx/src/Language/PlutusTx/Prelude.hs
- plutus-tx/src/Language/PlutusTx/Semigroup.hs
- plutus-use-cases/src/Language/PlutusTx/Coordination/Contracts/CrowdFunding.hs
- plutus-use-cases/src/Language/PlutusTx/Coordination/Contracts/Future.hs
- plutus-use-cases/src/Language/PlutusTx/Coordination/Contracts/MultiSigStateMachine.hs
- plutus-use-cases/src/Language/PlutusTx/Coordination/Contracts/Vesting.hs
- plutus-wallet-api/ledger/Ledger/AddressMap.hs
- plutus-wallet-api/ledger/Ledger/Index.hs
- plutus-wallet-api/ledger/Ledger/Interval.hs
- plutus-wallet-api/ledger/Ledger/Map.hs
- plutus-wallet-api/ledger/Ledger/Slot.hs
- plutus-wallet-api/ledger/Ledger/Validation.hs
- plutus-wallet-api/ledger/Ledger/Value.hs
- plutus-wallet-api/src/Wallet/API.hs
- plutus-wallet-api/test/Spec.hs
Also fix up `Interval`: use typeclasses instead of passing a function,
therefore get rid of forwarders in `Slot`.
> plutus-tx: add Semigroup and Monoid

- deployment/nixops/server.nix
- deployment/terraform/loadbalancing.tf
- deployment/terraform/main.tf
- plutus-playground-client/src/MainFrame.purs
See https://david.plutus.iohkdev.io/ for demo
> Plutus playground API and Tutorial now hosted

- plutus-playground-server/usecases/CrowdFunding.hs
- plutus-playground-server/usecases/Game.hs
- plutus-playground-server/usecases/Messages.hs
- plutus-playground-server/usecases/Vesting.hs
Some of these were very long indeed, resulting in ugly horizontal scrollbars in the editor window.
> playground usecases: wrap to 80 characters

- extended-utxo-spec/Makefile
- extended-utxo-spec/extended-utxo-specification.tex
Reverts input-output-hk/plutus#1177
> Revert "Kwxm/eutxo spec"

- stack.yaml
Fixes #1180.
Workaround for https://github.com/commercialhaskell/stack/issues/4913.
> Fix new stack by removing absolute symlink

- .gitignore
Not entirely sure what this is or whether we should check it, so ignoring it for now.
> Gitignore stack.yaml.lock

- language-plutus-core/test/TypeSynthesis/Golden/GtByteString.plc.golden
- language-plutus-core/test/TypeSynthesis/Golden/LtByteString.plc.golden
I really need to work out how to make the tests fail on CI if the
expected output file is missing, rather than silently creating it.
> Add missing test files

- plutus-use-cases/bench/Bench.hs
- plutus-use-cases/bench/Opt.hs
- plutus-use-cases/plutus-use-cases.cabal
This seems to gain us between 0% and 25%.
> plutus-use-cases: include benchmarks using optimized functions

- meadow-client/src/MonadApp.purs
* stack overflow (comment in code explains)
* wrong editor contents used (this is a worryingly easy mistake to make)
> marlowe pg bug fixes

- meadow-client/src/MainFrame.purs
- meadow-client/src/MonadApp.purs
Another error that I can maybe avoid in future with some more newtyping however looking into it briefly it requires some thought as to where things should go. Newtyping would be quite far reaching.
> marlowe data going to the wrong editor

- nix/overlays/required.nix
- plutus-book/doc/game/guess.adoc
It was having trouble with https://github.com/input-output-hk/plutus/issues/1213
> Fix book Haddock errors

- deployment/nixops/default.nix
- deployment/nixops/secrets.json.example
I have asked @JonathanWessels to help with this since currently login to github on Malrowe Playground in production is broken 😢
> we need separate github apps for marlowe and plutus

- plutus-book/doc/09-extended.adoc
- plutus-book/doc/10-PlutusTx.adoc
- plutus-book/doc/game/game.adoc
- plutus-book/doc/off-chain/off-chain.adoc
- plutus-book/doc/off-chain/payToWallet1.adoc
- added a note in off-chain file for hopefully better flow
> Mostly extended UTxO and off-chain edits

- plutus-book/doc/10-PlutusTx.adoc
- plutus-book/doc/glossary.adoc
- plutus-book/doc/plutus.adoc
- sorted glossary alphabetically
- added terms "Plutus Playground" and "Fungible token"
Also fixed broken hyperlink.
> book: cleaned up glossary

- deployment-server/app/Main.hs
- deployment-server/src/Deploy/Server.hs
- deployment-server/src/Deploy/Types.hs
- deployment-server/src/Deploy/Worker.hs
- deployment/nixops/prometheus.nix
If we want to automatically deploy to production we will want to deploy from a ref other than `master` so this should be configurable.
Tested on https://david.plutus.iohkdev.io/
> configure which branch should be deployed

- plutus-book/doc/endmatter.adoc
I think this is nicer.
That said, I think it's possible to go overboard with the linking...
> book: use refexts for glossary anchors

- deployment-server/app/Main.hs
- deployment-server/deployment-server.cabal
- deployment-server/src/Deploy/Types.hs
- deployment-server/src/Deploy/Worker.hs
- deployment/nixops/prometheus.nix
If the initial create github deployment fails you will know because it should have appeared almost as soon as you clicked the merge button
If the deployment fails to update within a few minutes you can check the logs
I don't feel there is a real need for the slack alerts therefore I have removed them
Just going to test on my personal env.
> Create a github deployment and don't bother using slack

- plutus-playground-server/test/Playground/UsecasesSpec.hs
- plutus-playground-server/usecases/Vesting.hs
> playground: Wallet instead of pubkey in vesting example

- plutus-tx/compiler/Language/PlutusTx/Compiler/Utils.hs
- plutus-tx/test/Plugin/Errors/mutualRecursionUnfoldingsLocal.plc.golden
- plutus-tx/test/Plugin/Errors/recursiveNewtype.plc.golden
This helps a lot with working out what errors are referring to.
> plutus-tx: print names qualified

- .gitignore
- papers/unraveling-recursion/compiling-to-fomega.tex
- papers/unraveling-recursion/default.nix
- Point to the Plutus repo for source artifacts.
- Include style files in the sources zip.
> MPC paper fixes

- papers/unraveling-recursion/compiling-to-fomega.tex
After some soul-searching I've gone with me first and then alphabetical.
> Unraveling recursion: change author order

- docs/ethereum-contracts/README.md
> Minor corrections

- default.nix
With this I can run cabal in a nix shell, and hence dante.
> Making git and standard SSL certs available from nix-shell.

- plutus-contract/src/Language/Plutus/Contract/App.hs
- plutus-contract/src/Language/Plutus/Contract/IOTS.hs
* Generate a single `HList` with all the endpoints and export it in one go, instead of generating the schema for each endpoint individually and concatenating the results
* This creates the correct calls to `createEndpoint`, and ensures that types such as `Ada` are not declared more than once in the IOTS file.
Sample output (note the `createEndpoint` bits):
```
// Language.PlutusTx.Coordination.Contracts.Game.GuessParams
const GuessParams = t.type({
guessWord: t.string
});
const GuessArgs = t.type({
a: GuessParams
});
const GuessReturn = t.null;
export const Guess = createEndpoint<typeof GuessArgs, typeof GuessReturn, t.NullC>(
'Guess',
GuessArgs,
GuessReturn
);
// Ledger.Ada.Ada
const Ada = t.type({
getLovelace: t.number
});
// Language.PlutusTx.Coordination.Contracts.Game.LockParams …
```
> plutus-contract: Better iots schema

- README.adoc
- plutus-tutorial/doc/02-validator-scripts.adoc
- plutus-tutorial/doc/03-wallet-api.adoc
- plutus-tutorial/doc/04-vesting.adoc
- plutus-tutorial/doc/index.adoc
- plutus-tutorial/doc/intro.adoc
Did another editorial pass, not really time to do much more.
> tutorial improvements

- pkgs/default.nix
- plutus-playground-client/src/Chain/Types.purs
- plutus-playground-client/src/Chain/View.purs
- plutus-playground-client/test/evaluation_response1.json
- plutus-playground-lib/src/Playground/Rollup.hs
- plutus-playground-lib/src/Playground/Rollup/Render.hs
- plutus-playground-lib/src/Playground/Types.hs
- plutus-playground-server/app/PSGenerator.hs
- plutus-playground-server/test/Playground/Rollup/renderCrowdfunding.txt
- plutus-playground-server/test/Playground/Rollup/renderVestFunds.txt
- stack.yaml
...rather than the contents of the datascript.
> Rollup: Scripts are now shown by their address.

- plutus-playground-server/usecases/Vesting.hs
See #1448.  The redeemer has the wrong type.
> Fix for #1448 (I think)

- plutus-contract/src/Language/Plutus/Contract/App.hs
- plutus-contract/src/Language/Plutus/Contract/Test.hs
- plutus-contract/src/Language/Plutus/Contract/Trace.hs
- plutus-contract/test/Spec/Contract.hs
- plutus-use-cases/src/Language/PlutusTx/Coordination/Contracts/CrowdFunding.hs
- plutus-use-cases/src/Language/PlutusTx/Coordination/Contracts/Game.hs
* Remove a type parameter that was not used for anything
> contracts: Remove spurious type parameter

- plutus-ir/src/Language/PlutusIR/Transform/Rename.hs
Type parameters of a data type are not visible in the mutual block where that data type is defined and so we shouldn't rename them during the first stage where we bring everything visible in the mutual block in scope.
> [PlutusIR] Made type parameters of a data type be not visible in the mutual block

- docs/smart-contract-backend/scb.md
Import of the current version from https://docs.google.com/document/d/1OZMPITIAK10bjP2OBUlS8SxlOnXNXQf2q4IU6sZMDeQ (going to retire the google doc when this is merged)
> Initial import of SCB document

- docs/smart-contract-backend/scb.md
Update the SCB docs with the two types of queries we can ask the node client (it occurred to me that there is a third type, namely "what is the current slot number", which should be uncontroversial)
> SCB: Update docs

- plutus-contract/src/Language/Plutus/Contract/Effects/AwaitSlot.hs
- plutus-contract/src/Language/Plutus/Contract/Effects/WatchAddress.hs
- plutus-contract/src/Language/Plutus/Contract/Effects/WriteTx.hs
- plutus-contract/src/Language/Plutus/Contract/Test.hs
- plutus-contract/src/Language/Plutus/Contract/Trace.hs
Just a small follow-up to #1469
> contracts: Synonyms for symbols

- cabal.project
There was one missing and one old package in the cabal file.
> Resyncing cabal.project with stack.yaml.

- plutus-wallet-api/ledger/Ledger/Typed/Tx.hs
This is checking the *real* validator type. We therefore can't check the
"non-data" validator type, but we rather have to check the wrapped type.
Consequently, this just checks that it's a sensical validator (which is
fine). The hash lookup ensures that it's exactly the function we're
expecting, anyway!
This wasn't used, hence no error.
> ledger: fix checking for validator type

- plutus-tx/src/Language/PlutusTx/Prelude.hs
- plutus-tx/src/Language/PlutusTx/Ratio.hs
- plutus-use-cases/src/Language/PlutusTx/Coordination/Contracts/Swap.hs
> use-cases: Use new Language.PlutusTx.Ratio in swap contract

- cabal.project
> Fix cabal project file

- README.adoc
> Improve the binary cache section of the readme a little

- .stylish-haskell.yaml
- language-plutus-core/generators/Language/PlutusCore/Generators/Internal/TypeEvalCheck.hs
- plutus-contract/src/Language/Plutus/Contract.hs
- plutus-tx/compiler/Language/PlutusTx/Compiler/Error.hs
- plutus-tx/src/Language/PlutusTx/IsData/Class.hs
- plutus-wallet-api/ledger/Ledger/Typed/Scripts.hs
So now it can check and tidy more of the codebase.
> Teaching sylish haskell about some of our fruitier language extensions.

- marlowe-playground-client/src/MonadApp.purs
- marlowe-playground-client/src/Simulation.purs
- marlowe-playground-client/src/Types.purs
- marlowe-playground-client/static/main.scss
- marlowe-playground-client/test/Marlowe/ContractTests.purs
Addresses issues #1530, #1531, and #1532, and applies small adjustments to the layout of the simulator.
> Marlowe playground refinements

- plutus-wallet-api/ledger/Ledger/Typed/Tx.hs
- plutus-wallet-api/src/Wallet/Typed/API.hs
Inputs no longer need to be parameterized by the list of output types.
More to come but this stands alone.
> Typed tx: simplify

- plutus-use-cases/test/Spec/Rollup.hs
> use-cases: Fix test

- README.adoc
- papers/system-f-in-agda/bibliography.bib
- papers/unraveling-recursion/references.bib
The two MPC 2019 papers have now been published:
https://link.springer.com/book/10.1007/978-3-030-33636-3
> [WIP] link to published paper DOIs

- marlowe-playground-client/src/Halogen/Blockly.purs
- marlowe-playground-client/src/MainFrame.purs
- marlowe-playground-client/src/Marlowe/Blockly.purs
- marlowe-playground-client/src/Marlowe/Gen.purs
- marlowe-playground-client/src/Marlowe/Parser.purs
- marlowe-playground-client/src/Marlowe/Semantics.purs
- marlowe-playground-client/src/MonadApp.purs
- marlowe-playground-client/src/Simulation.purs
- marlowe-playground-client/src/Types.purs
- marlowe-playground-client/test/Marlowe/BlocklyTests.purs
- marlowe-playground-client/test/Marlowe/ContractTests.purs
- marlowe-playground-client/test/Marlowe/GenWithHoles.purs
- marlowe-playground-client/test/Marlowe/ParserTests.purs
- web-common/src/Control/Monad/Except/Extra.purs
- web-common/src/Data/RawJson.purs
This has 2 parts:
1. Parameterize the Marlowe types
2. Implement holes in the parser
This commit provides no additional user functionality, instead it enables future functionality to be added now that you can parse value holes.
> Introduce Marlowe value holes in Purescript

- papers/system-f-in-agda/README.md
- papers/unraveling-recursion/README.md
Add links in README files for MPC papers.
> Update README files with pulbication information

- papers/system-f-in-agda/README.md
- papers/unraveling-recursion/README.md
Add DOI info for the papers, as suggested by @jmchapman.
> Kwxm/plutus papers/add doi info

- plutus-use-cases/test/Spec/crowdfundingTestOutput.txt
This test output is very sensitive...
> Fix a semantic merge conflict

- plutus-contract/src/Language/Plutus/Contract.hs
- plutus-contract/src/Language/Plutus/Contract/Test.hs
- plutus-contract/src/Language/Plutus/Contract/Trace.hs
- plutus-contract/src/Language/Plutus/Contract/Tx.hs
- plutus-contract/test/Spec/Contract.hs
- plutus-use-cases/src/Language/PlutusTx/Coordination/Contracts/CrowdFunding.hs
- plutus-use-cases/test/Spec/Crowdfunding.hs
- plutus-use-cases/test/Spec/Currency.hs
- plutus-use-cases/test/Spec/Escrow.hs
- plutus-use-cases/test/Spec/PubKey.hs
- plutus-wallet-api/ledger/Ledger/Index.hs
* until there are no more events to handle.
> contracts: handleBlockchainEvents keeps going

- default.nix
- release.nix
Trying https://github.com/input-output-hk/plutus/pull/1586 again.
> Don't build updateClientDeps on darwin

- extended-utxo-spec/extended-utxo-specification.tex
This is no longer definitive, so I've removed the word specification from the title and elsewhere.
> Minor updates to the EUTXO document

- extended-utxo-spec/extended-utxo-specification.tex
Change the name of The Object Formerly Known As The Data Script to "data value".
> Validation data -> data value

- plutus-use-cases/test/Spec/Crowdfunding.hs
- plutus-use-cases/test/Spec/Currency.hs
- plutus-use-cases/test/Spec/Escrow.hs
- plutus-use-cases/test/Spec/Future.hs
- plutus-use-cases/test/Spec/Game.hs
- plutus-use-cases/test/Spec/GameStateMachine.hs
- plutus-use-cases/test/Spec/MultiSigStateMachine.hs
- plutus-use-cases/test/Spec/Vesting.hs
Everything was way under, so this seems reasonably safe.
> use-cases: lower asserted size thresholds

- ARCHITECTURE.adoc
- README.adoc
- plutus-tutorial/doc/index.adoc
> docs: add a document describing the architecture of the repository

- plutus-contract/src/Language/Plutus/Contract/Record.hs
- plutus-contract/src/Language/Plutus/Contract/Resumable.hs
- plutus-contract/test/Spec/Contract.hs
- plutus-contract/test/Spec/State.hs
- plutus-use-cases/plutus-use-cases.cabal
- plutus-use-cases/src/Language/PlutusTx/Coordination/Contracts/Currency.hs
- plutus-use-cases/src/Language/PlutusTx/Coordination/Contracts/TokenAccount.hs
- plutus-use-cases/test/Spec.hs
- plutus-use-cases/test/Spec/Currency.hs
- plutus-use-cases/test/Spec/TokenAccount.hs
* The token account contract lets you pay "to a token", by releasing the
funds locked with it to whoever presents the token.
> use-cases: Add token account

- plutus-contract/plutus-contract.cabal
- plutus-contract/src/Language/Plutus/Contract.hs
- plutus-contract/src/Language/Plutus/Contract/Effects/OwnPubKey.hs
- plutus-contract/src/Language/Plutus/Contract/Trace.hs
- plutus-contract/test/Spec/Contract.hs
- plutus-use-cases/src/Language/PlutusTx/Coordination/Contracts/CrowdFunding.hs
- plutus-use-cases/src/Language/PlutusTx/Coordination/Contracts/Escrow.hs
- plutus-use-cases/test/Spec/Escrow.hs
- plutus-use-cases/test/Spec/crowdfundingTestOutput.txt
* Add "ownPubKey" endpoint
* Use "ownPubKey" in escrow and crowdfunding examples
> contracts: Add "ownPubKey" endpoint

- marlowe-symbolic/src/Language/Marlowe/Analysis/FSSemantics.hs
Restricting the starting slot does not prevent transactions for containing slot intervals that start with a negative slot number.
Add an extra restriction to Marlowe symbolic counter-examples: no slot numbers in transaction slot intervals can be negative.
> Restrict symbolic execution to produce positive slot intervals

- README.adoc
- extended-utxo-spec/extended-utxo-specification.tex
I think it's in a good enough state that we can advertise it.
> Add link to eutxo model doc in readme

- docs/plutus-core/Erasure-Merklisation.md
Just a small document about the effects of type erasure on code size. I'll merge it myself.
> Add document about type erasure

- marlowe-playground-client/src/Marlowe/Parser.purs
- marlowe-playground-client/src/Types.purs
> Two fixes for Marlowe playground

- language-plutus-core/generators/Language/PlutusCore/Generators/AST.hs
- language-plutus-core/prelude/PlutusPrelude.hs
- language-plutus-core/src/Language/PlutusCore.hs
- language-plutus-core/src/Language/PlutusCore/Lexer/Type.hs
- language-plutus-core/src/Language/PlutusCore/Name.hs
- language-plutus-core/src/Language/PlutusCore/Subst.hs
- language-plutus-core/src/Language/PlutusCore/Type.hs
- language-plutus-core/test/Check/Spec.hs
- language-plutus-core/test/Normalization/Type.hs
- language-plutus-core/test/Spec.hs
- plutus-core-interpreter/src/Language/PlutusCore/Interpreter/CekMachine.hs
- plutus-ir/src/Language/PlutusIR/Generators/AST.hs
- plutus-ir/test/ParserSpec.hs
As per [this comment](https://github.com/input-output-hk/plutus/issues/1613#issuecomment-553440425) this doesn't actually catch the existing bug. But it's still useful I think.
I also reimplemented the untyped generators machinery to make it more sensible.
> [PLC] [Test] [NameHandling] Added a 'propMangle' test

- docs/plutus-core/Erasure-Merklisation.md
> Messed up the table in the erasure document

- nix/sources.nix
See https://github.com/nmattia/niv/issues/143. Hopefully I'll fix this
upstream in a bit.
> Avoid lorri looping

- plutus-contract/src/Language/Plutus/Contract/Test.hs
- plutus-contract/src/Language/Plutus/Contract/Trace.hs
- plutus-contract/src/Language/Plutus/Contract/Wallet.hs
- plutus-use-cases/bench/Bench.hs
- plutus-use-cases/src/Language/PlutusTx/Coordination/Contracts/MultiSig.hs
- plutus-use-cases/test/Spec/MultiSig.hs
- plutus-use-cases/test/Spec/multisig.pir
* Update the multisig contract to use the new contracts API
* Add the ability to customise the signing process to
'Language.Plutus.Contract.Trace'
> usecases: Update multisig

- plutus-contract/src/Language/Plutus/Contract/Tx.hs
- plutus-use-cases/src/Language/PlutusTx/Coordination/Contracts/GameStateMachine.hs
- plutus-use-cases/test/Spec/GameStateMachine.hs
Change the endpoints to use the new contracts API, leave everything else as it was
> contracts: Update game state machine

- papers/system-f-in-agda/errata.txt
- papers/system-f-in-agda/paper.lagda
> fixed value restriction in beta-wrap rule in fun-and-profit paper

- default.nix
- hie.yaml
- nix/sources.json
- release.nix
> + hie-bios

- nix/sources.json
- release.nix
Forgot this one. And also, this signs the previous PR (#1658)
> updated HIE bios

- docs/fomega/deep-isorecursive/ifix.md
Some references regarding `ifix`. I didn't do any extensive search, there should be more references, but I think even just these are already convincing that `ifix` is well-known.
> [Docs] Added 'ifix.md'

- default.nix
- nix/sources.json
I'll add it later once it's more stable.
> The world is not ready for hie-bios

- plutus-playground-server/usecases/CrowdFunding.hs
- plutus-playground-server/usecases/Vesting.hs
- plutus-use-cases/src/Language/PlutusTx/Coordination/Contracts/CrowdFunding.hs
- plutus-use-cases/src/Language/PlutusTx/Coordination/Contracts/Escrow.hs
- plutus-use-cases/src/Language/PlutusTx/Coordination/Contracts/Future.hs
- plutus-use-cases/src/Language/PlutusTx/Coordination/Contracts/GameStateMachine.hs
- plutus-use-cases/src/Language/PlutusTx/Coordination/Contracts/MultiSigStateMachine.hs
- plutus-use-cases/src/Language/PlutusTx/Coordination/Contracts/TokenAccount.hs
- plutus-use-cases/src/Language/PlutusTx/Coordination/Contracts/Vesting.hs
- plutus-wallet-api/ledger/Ledger/Typed/Scripts.hs
* Change the `ScriptInstance` type to include the validator script and the script address
* Slightly rearrange things in the multi sig state machine contract to increase sharing
Before:
After:
> scripts: Avoid recomputing the validator scripts

- plutus-tx/compiler/Language/PlutusTx/Data.hs
See the note in the code for details.
@krisajenkins I suspect this will fix your issue.
> Data: be more permissive in decoding

- plutus-playground-client/src/View.purs
- web-common/src/Bootstrap.purs
- web-common/src/Editor.purs
The demo buttons morally belong with the publish/load buttons -
they're both about switching to a different contract.
And the compile button is so central/useful that I think you want one
at the top of the screen too.
> Playground: Changing the layout of the top section.

- extended-utxo-spec/extended-utxo-specification.tex
This applies #1738 to the EUTXO document, and fixes one or two minor issues at the same time.
> Rename redeemer script to redeemer value

- plutus-playground-client/src/Chain/Types.purs
- plutus-playground-client/src/Chain/View.purs
A little tweak on top of the fix for #1515.
> ledger: generalize the fee field to Value - tidying the frontend code.

- marlowe-playground-client/entry.js
- marlowe-playground-client/src/Main.purs
- marlowe-playground-client/src/MainFrame.purs
- marlowe-playground-client/src/MonadApp.purs
- marlowe-playground-client/src/Simulation.purs
- marlowe-playground-client/src/Types.purs
- marlowe-playground-client/test/Marlowe/ContractTests.purs
- plutus-playground-client/entry.js
- plutus-playground-client/src/Main.purs
- plutus-playground-client/src/MainFrame.purs
- plutus-playground-client/src/MonadApp.purs
- plutus-playground-client/src/Types.purs
- plutus-playground-client/src/View.purs
- plutus-playground-client/test/EditorTests.purs
- plutus-playground-client/test/Main.purs
- plutus-playground-client/test/MainFrameTests.purs
- web-common/src/Bootstrap.purs
- web-common/src/Editor.purs
- web-common/static/main.scss
As part of this we introduce the notion of persistent editor
preferences, so your editing preferences are permanent across sessions.
> Enabling popular editor keybindings.

- docs/plutus-core/Merklisation/Erasure.md
- docs/plutus-core/Merklisation/Merklisation-notes.md
- docs/plutus-core/Merklisation/Merklising-programs.md
> Minor improvements to documents

- plutus-playground-client/src/View.purs
- web-common/src/Bootstrap.purs
- web-common/static/main.scss
I think it's too hard to notice them, yet they're one of the first
things you want to find.
> Playground: Making the documentation links more prominent.

- plutus-playground-client/src/Chain.purs
- plutus-playground-client/src/Chartist.js
- plutus-playground-client/src/Chartist.purs
- plutus-playground-client/src/Halogen/Chartist.purs
- plutus-playground-client/src/MainFrame.purs
- plutus-playground-client/src/MonadApp.purs
- plutus-playground-client/test/MainFrameTests.purs
> Bugfix - Balances chart can fail to rerender correctly when you switch tabs.

- CONTRIBUTING.adoc
- README.adoc
Simon was looking at these which prompted me to read them again and make a few changes.
> Improve README and CONTRIBUTING somewhat

- extended-utxo-spec/extended-utxo-specification.tex
This fixes a few minor errors in the EUTXO document.  At least one of these will have to be propagated to the EUTXO paper as well.
> Fix some problems pointed out by @jmchapman

- papers/eutxo/formal-model.tex
This fixes a small error in the validity rules pointed out by @jmchapman .
> Correct small error in validity rules

- default.nix
> The marlowe test suite assumes you have z3 installed.

- marlowe-playground-client/src/MainFrame.purs
- marlowe-playground-client/src/Marlowe/Gen.purs
- marlowe-playground-client/src/Marlowe/Holes.purs
- marlowe-playground-client/src/Marlowe/Linter.purs
- marlowe-playground-client/src/Marlowe/Parser.purs
- marlowe-playground-client/src/MonadApp.purs
- marlowe-playground-client/src/Simulation.purs
Collect negative payments and negative deposits in contracts and warn the user about them
Also make demo contracts pretty
Deployed to https://david.marlowe.iohkdev.io/ - just load a contract and change a payment or deposit to have a negative value, e.g. `Constant -100` or `NegValue (Constant 100)`
> Marlowe Playground - New warnings

- marlowe-playground-client/src/Simulation.purs
- marlowe-symbolic/src/Language/Marlowe/Analysis/FSSemantics.hs
- marlowe-symbolic/src/Language/Marlowe/Analysis/IntegerArray.hs
Simplify some aspects of symbolic execution and small fix to simulator presentation.
> Optimise symbolic execution

- marlowe-playground-client/src/Marlowe/Holes.purs
- marlowe-playground-client/src/Marlowe/Linter.purs
- marlowe-playground-client/src/MonadApp.purs
- marlowe-playground-client/src/Simulation.purs
- marlowe-playground-client/webpack.config.js
This adds some new warnings as well as tidying up (and messing up) a few things.
It does affect performance slightly however I plan to move to Monaco editor which does this type of thing in a web worker so the editor and page should always feel responsive.
> Marlowe editor warnings part deux

- extended-utxo-spec/extended-utxo-specification.tex
Just in the same vein as equality, but worth mentioning so it's
obvious.
> eutxo doc: add a note about partial order of finitely-supported functions

- default.nix
- marlowe-playground-client/entry.js
- marlowe-playground-client/grammar.ne
- marlowe-playground-client/package.json
- marlowe-playground-client/spago.dhall
- marlowe-playground-client/src/Main.purs
- marlowe-playground-client/src/MainFrame.purs
- marlowe-playground-client/src/Marlowe/Gen.purs
- marlowe-playground-client/src/Marlowe/Holes.purs
- marlowe-playground-client/src/Marlowe/Linter.purs
- marlowe-playground-client/src/Marlowe/Parser.js
- marlowe-playground-client/src/Marlowe/Parser.purs
- marlowe-playground-client/src/MonadApp.purs
- marlowe-playground-client/src/Simulation.purs
- marlowe-playground-client/src/Text/Parsing/Parser/Basic.purs
- marlowe-playground-client/src/Types.purs
- marlowe-playground-client/test/Marlowe/ParserTests.purs
- marlowe-playground-client/test/entry.js
- marlowe-playground-client/webpack.config.js
- marlowe-playground-client/webpack.test.config.js
- marlowe-playground-client/yarn.lock
- marlowe-playground-client/yarn.nix
- nix/purescript.nix
This is about 5 times faster than the standard parser
* The parser generator isn't quite suitable for us so we use a hacked version
of nearley-webpack-loader to compile it
* Given the above we need to use webpack to compile the tests
* We still have the old parser as it is used by Blockly, we should be
able to remove this in another PR
> Use parser generator for parsing contracts

- marlowe/test/Spec/Marlowe/Marlowe.hs
- plutus-contract-tasty/test/Spec/Contract.hs
- plutus-contract/src/Language/Plutus/Contract/Trace.hs
- plutus-contract/src/Language/Plutus/Contract/Wallet.hs
- plutus-emulator/plutus-emulator.cabal
- plutus-emulator/src/Control/Monad/Freer/Extras.hs
- plutus-emulator/src/Wallet/Emulator/ChainIndex.hs
- plutus-emulator/src/Wallet/Emulator/MultiAgent.hs
- plutus-emulator/src/Wallet/Emulator/Types.hs
- plutus-emulator/src/Wallet/Emulator/Wallet.hs
- plutus-playground-client/src/Chain.purs
- plutus-playground-server/app/PSGenerator.hs
- plutus-scb/src/Cardano/Wallet/Client.hs
- plutus-scb/src/Plutus/SCB/App.hs
- plutus-scb/src/Plutus/SCB/Core.hs
- plutus-scb/test/Plutus/SCB/TestApp.hs
- plutus-tutorial/doc/02-validator-scripts.adoc
- plutus-tutorial/doc/04-vesting.adoc
- plutus-wallet-api/src/Wallet/API.hs
* Add a chain index for each wallet
* This is an index of the entire UTXO set (for now)
* Change the `watchedAddresses` from `WalletAPI` to `ownOutputs`, which returns outputs at the wallet's address
> emulator: Add ChainIndex effect

- marlowe/src/Language/Marlowe/Client.hs
- marlowe/test/Spec/Marlowe/Marlowe.hs
- plutus-contract/src/Language/Plutus/Contract/Trace.hs
- plutus-contract/src/Language/Plutus/Contract/Wallet.hs
- plutus-emulator/plutus-emulator.cabal
- plutus-emulator/src/Control/Monad/Freer/Extras.hs
- plutus-emulator/src/Wallet/Emulator/MultiAgent.hs
- plutus-emulator/src/Wallet/Emulator/SigningProcess.hs
- plutus-emulator/src/Wallet/Emulator/Types.hs
- plutus-emulator/src/Wallet/Emulator/Wallet.hs
- plutus-scb/src/Cardano/Wallet/API.hs
- plutus-scb/src/Cardano/Wallet/Client.hs
- plutus-scb/src/Cardano/Wallet/Mock.hs
- plutus-scb/src/Cardano/Wallet/Server.hs
- plutus-scb/src/Plutus/SCB/App.hs
- plutus-scb/test/Plutus/SCB/TestApp.hs
- plutus-tutorial/doc/02-validator-scripts.adoc
- plutus-tutorial/doc/04-vesting.adoc
- plutus-use-cases/test/Spec/MultiSig.hs
- plutus-wallet-api/src/Wallet/API.hs
* Add a multi-agent effect for signing transactions to the emulator
* Remove the `sign` function from `WalletAPI`
> emulator: Add signing process effect

- marlowe-symbolic/marlowe-symbolic.cabal
- marlowe-symbolic/src/Language/Marlowe/Analysis/FSSemantics.hs
- marlowe-symbolic/test/OldAnalysis/FSMap.hs
- marlowe-symbolic/test/OldAnalysis/FSSemantics.hs
- marlowe-symbolic/test/OldAnalysis/FSSet.hs
- marlowe-symbolic/test/OldAnalysis/IntegerArray.hs
- marlowe-symbolic/test/OldAnalysis/MkSymb.hs
- marlowe-symbolic/test/OldAnalysis/Numbering.hs
- marlowe-symbolic/test/Spec.hs
- marlowe-symbolic/test/Tests.hs
- marlowe/src/Language/Marlowe/Semantics.hs
Continuation of pull-request #1854.
>  Optimise static analysis (continuation)

- papers/eutxo/formal-model.tex
* Also add Makefile for explicit build instructions.
> EUTXO paper: back to 15 pages

- marlowe-playground-client/src/Blockly/Generator.js
- marlowe-playground-client/src/Blockly/Generator.purs
- marlowe-playground-client/src/Marlowe/Blockly.purs
- Changed colors to make them different
- Adjusted layouts to make contracts occupy less (especially horizontally)
- Remove Case block (merged it into the different actions)
- Make a new block for currency/token (e.g: because we will probably end up having an ADA token, and it occupies less vertically)
> Improve blockly layout and usability

- language-plutus-core/common/PlcTestUtils.hs
- language-plutus-core/src/Language/PlutusCore/Evaluation/Machine/Cek.hs
- language-plutus-core/src/Language/PlutusCore/Name.hs
- language-plutus-core/src/Language/PlutusCore/Subst.hs
- language-plutus-core/test/Evaluation/DynamicBuiltins/Definition.hs
- language-plutus-core/test/Evaluation/Golden.hs
- language-plutus-core/test/Evaluation/Golden/closure.plc.golden
See https://github.com/input-output-hk/plutus/issues/1882
> [Bug] [PLC] [Builtin] [Evaluation] Added environment discharging to fix #1882

- plutus-scb/app/Main.hs
- plutus-scb/plutus-scb.cabal
- plutus-scb/plutus-scb.yaml.sample
- plutus-scb/src/Cardano/SigningProcess/API.hs
- plutus-scb/src/Cardano/SigningProcess/Client.hs
- plutus-scb/src/Cardano/SigningProcess/Server.hs
- plutus-scb/src/Cardano/Wallet/Mock.hs
- plutus-scb/src/Plutus/SCB/App.hs
- plutus-scb/src/Plutus/SCB/Types.hs
* Add the signing process as a separate service, similar to node and chain index
> scb: add signing process

- marlowe-playground-client/grammar.ne
- marlowe-playground-client/src/Data/BigInteger.purs
- marlowe-playground-client/src/Marlowe/Blockly.purs
- marlowe-playground-client/src/Marlowe/Gen.purs
- marlowe-playground-client/src/Marlowe/Holes.purs
- marlowe-playground-client/src/Marlowe/Linter.purs
- marlowe-playground-client/src/Marlowe/Parser.purs
- marlowe-playground-client/src/Marlowe/Semantics.purs
- marlowe-symbolic/src/Language/Marlowe/Analysis/FSSemantics.hs
- marlowe-tutorial/doc/marlowe-data.adoc
- marlowe/src/Language/Marlowe/Pretty.hs
- marlowe/src/Language/Marlowe/Semantics.hs
- marlowe/test/Spec.hs
- marlowe/test/Spec/Marlowe/Common.hs
- marlowe/test/Spec/Marlowe/Marlowe.hs
- plutus-tx/src/Language/PlutusTx/Prelude.hs
- plutus-tx/src/Language/PlutusTx/Ratio.hs
Add Scale Value - rational constant multiplication with 'banking' rounding.
> Add Scale Value - rational constant multiplication.

- plutus-core-spec/plutus-core-specification.tex
Just fixing a couple of minor typos in the PLC specification.
> Fix a couple of typos

- plutus-emulator/src/Wallet/Emulator/NodeClient.hs
- plutus-emulator/src/Wallet/Emulator/Wallet.hs
- plutus-scb/src/Plutus/SCB/EventLog.hs
This is now handled by the ChainIndex effect.
> Removing the ClientIndex constructor.

- language-plutus-core/src/Language/PlutusCore/Evaluation/Machine/Cek.hs
- language-plutus-core/src/Language/PlutusCore/Quote.hs
An alternative solution to the evaluation of polymorphic built-in functions problem.
> [PLC] [Evaluation] [Builtins] Generating mappings during evaluation of builtins in the polymorphic case

- marlowe-playground-client/src/Halogen/Classes.purs
- marlowe-playground-client/src/MainFrame.purs
- marlowe-playground-client/src/Simulation.purs
- marlowe-playground-client/src/Simulation/BottomPanel.purs
- marlowe-playground-client/src/StaticData.purs
- marlowe-playground-client/src/Types.purs
- marlowe-playground-client/static/css/globals.css
- marlowe-playground-client/static/css/panels.css
- marlowe-playground-client/test/Marlowe/ContractTests.purs
- make it obvious that buttons are disabled
- improve errors and warnings display
> Scp 166 - Next round of changes

- ci.nix
- default.nix
- marlowe-symbolic/lambda.nix
- nix/ci-lib.nix
- nix/dev.nix
- nix/purescript.nix
- nix/tests/default.nix
- release.nix
> Build more stuff in ci.nix, reuse in release.nix

- marlowe-playground-client/src/Halogen/Classes.js
- marlowe-playground-client/src/Halogen/Classes.purs
- marlowe-playground-client/src/HaskellEditor.purs
- marlowe-playground-client/src/Help.purs
- marlowe-playground-client/src/Simulation.purs
- marlowe-playground-client/src/Simulation/BottomPanel.purs
- marlowe-playground-client/static/css/globals.css
- marlowe-playground-client/static/css/layout.css
- marlowe-playground-client/static/css/main-tabs.css
- marlowe-playground-client/static/css/main.scss
- marlowe-playground-client/static/css/panels.css
- marlowe-playground-client/static/images/icon-18.svg
- marlowe-playground-client/static/images/icon-19.svg
* replace minimize icon
* update help
* add tooltip to blockly button
* improve some text
* fix main panel width
* remove top header
* reduce padding overall to increase space
* fix auth button position
> SCP-166 - Latest design updates

- shell.nix
(I recently cleaned my laptop up, and am discovering a few things I
thought were part of our environment, but are actually just hoped to
magically be available.)
> Adding nodejs to the list of shell.nix tools.

- extended-utxo-spec/extended-utxo-specification.tex
A minor documentation update: I'll merge this myself.
> Remarks about finiteness

- extended-utxo-spec/extended-utxo-specification.tex
Minor updates to document. Will merge without review.
> Clear up a couple of issues in the EUTXO document

- deployment-server/deployment-server.cabal
- marlowe-playground-client/entry.js
- marlowe-playground-client/package.json
- marlowe-playground-client/src/Halogen/Monaco.purs
- marlowe-playground-client/src/HaskellEditor.purs
- marlowe-playground-client/src/MainFrame.purs
- marlowe-playground-client/src/Monaco.js
- marlowe-playground-client/src/Monaco.purs
- marlowe-playground-client/src/MonadApp.purs
- marlowe-playground-client/src/Simulation.purs
- marlowe-playground-client/src/Types.purs
- marlowe-playground-client/static/css/css_var_colors.css
- marlowe-playground-client/static/css/panels.css
- marlowe-playground-client/static/images/down-arrow.svg
- marlowe-playground-client/test/Marlowe/ContractTests.purs
- marlowe-playground-client/yarn.lock
- marlowe-playground-client/yarn.nix
- nix/haskell.nix
This one is for you @krisajenkins deployed to https://david.marlowe.iohkdev.io/
> Add vim and emacs keybindings to monaco editor

- nix/haskell.nix
- plutus-emulator/src/Control/Monad/Freer/Extras.hs
- plutus-scb/plutus-scb.cabal
- plutus-scb/test/Plutus/SCB/CoreSpec.hs
- plutus-scb/test/Plutus/SCB/Effects/ContractTest.hs
- plutus-scb/test/Plutus/SCB/Effects/MultiAgent.hs
- plutus-scb/test/Plutus/SCB/TestApp.hs
* Add `Plutus.SCB.Effects.MultiAgent` - similar to `Wallet.Emulator.MultiAgent` in that it lets you run actions in the context of agents, but different in the effects that are allowed
* `Plutus.SCB.TestApp.runTestApp` looks a bit nicer now
> scb: Multi-agent tests

- marlowe-playground-client/spago-packages.nix
- marlowe-playground-client/src/Data/BigInteger.purs
- marlowe-playground-client/src/MainFrame.purs
- marlowe-playground-client/src/Marlowe/Semantics.purs
- marlowe-playground-client/test/BridgeTests.purs
- marlowe-playground-client/test/contract.json
- marlowe-symbolic/src/App.hs
- marlowe/marlowe.cabal
- marlowe/src/Language/Marlowe/Pretty.hs
- marlowe/src/Language/Marlowe/Semantics.hs
- marlowe/test/Spec/Marlowe/Common.hs
- marlowe/test/Spec/Marlowe/Marlowe.hs
- marlowe/test/contract.json
- plutus-ledger/src/Ledger/Crypto.hs
- plutus-tx/src/Language/PlutusTx/Ratio.hs
Marlowe Contract JSON serialization for Haskell and PureScript interaction.
> Marlowe Contract JSON serialization

- deployment/shell.nix
- docs/plutus-report/applications.tex
- docs/plutus-report/intro.tex
- docs/plutus-report/ledger.tex
- docs/plutus-report/plutus.tex
- docs/plutus-report/scripting.tex
- language-plutus-core/src/Language/PlutusCore.hs
- nix/haskell.nix
- nix/sources.json
- shell.nix
Latest stable is released, let's see how this goes.
> Update nixpkgs to 20.03

- marlowe-playground-client/grammar.ne
- marlowe-playground-client/src/Marlowe/Blockly.purs
- marlowe-playground-client/src/Marlowe/Holes.purs
- marlowe-playground-client/src/Marlowe/Linter.purs
- marlowe-playground-client/src/Marlowe/Monaco.ts
- marlowe-playground-client/src/Marlowe/Parser.purs
- marlowe-playground-client/src/Marlowe/Semantics.purs
- marlowe-playground-client/test/BridgeTests.purs
- marlowe-playground-client/test/Marlowe/CompletionItemsTests.purs
- marlowe-playground-client/test/Marlowe/ParserTests.purs
- marlowe-playground-client/test/contract.json
- marlowe-playground-server/contracts/Escrow.hs
- marlowe-symbolic/src/Language/Marlowe/Analysis/FSSemantics.hs
- marlowe-symbolic/test/OldAnalysis/FSSemantics.hs
- marlowe-symbolic/test/Tests.hs
- marlowe-tutorial/doc/marlowe-data.adoc
- marlowe/src/Language/Marlowe/Semantics.hs
- marlowe/test/Spec/Marlowe/Common.hs
- marlowe/test/Spec/Marlowe/Marlowe.hs
- plutus-scb-client/src/Types.purs
This PR introduces If-expressions to Marlowe DSL:
- Marlowe semantics for Plutus
- Playground support
Story link: [SCP-285](https://jira.iohk.io/browse/SCP-285). Practical need for if-expressions is described in [this epic](https://jira.iohk.io/browse/SCP-255)
TODO:
> If expressions for Marlowe DSL

- marlowe-playground-client/packages.dhall
- marlowe-playground-client/spago.dhall
- nix/sources.json
- plutus-playground-client/packages.dhall
- plutus-scb-client/packages.dhall
tested both playgrounds locally with locally running servers to check communication is fine
> upgrade to the latest purescript package set

- language-plutus-core/docs/Builtins.md
Not saying anything about costing. It might make sense to reference this doc from the technical report as I've attempted to make it more or less comprehensive (I'll think more, if I forgot anything substantial).
Fixes https://jira.iohk.io/browse/SCP-252
> SCP-252: [PLC] [Docs] Added a writeup on builtins

- marlowe-playground-client/src/Halogen/Monaco.purs
- marlowe-playground-client/src/Help.purs
- marlowe-playground-client/src/Language/Haskell/Monaco.purs
- marlowe-playground-client/src/Marlowe/Holes.purs
- marlowe-playground-client/src/Marlowe/Linter.purs
- marlowe-playground-client/src/Marlowe/Monaco.js
- marlowe-playground-client/src/Marlowe/Monaco.purs
- marlowe-playground-client/src/Marlowe/Monaco.ts
- marlowe-playground-client/src/Monaco.js
- marlowe-playground-client/src/Monaco.purs
> Add hover provider with simple help text for marlowe constructors

- language-plutus-core/src/Language/PlutusCore/Evaluation/Machine/Cek.hs
Reflecting our yesterday's discussion.
> [PLC] [Evaluation] Drop environments of constants

- marlowe-playground-client/package.json
- marlowe-playground-client/webpack.config.js
- marlowe-playground-client/yarn.lock
- marlowe-playground-client/yarn.nix
- plutus-playground-client/webpack.config.js
- plutus-scb-client/webpack.config.js
Uncompressed 25.6Mb -> 5.01Mb
Compressed 5.2Mb -> 1.1Mb
* also upgrade monaco webpack plugin
> Reduce javascript artefact size

- .buildkite/pipeline.yml
It does nothing now there's a better hydra notifier.
> Remove buildkite check

- plutus-playground-client/test/CursorTests.purs
- plutus-playground-client/test/Data/Array/ExtraTests.purs
- plutus-playground-client/test/Data/Foldable/ExtraTests.purs
- plutus-playground-client/test/Data/String/ExtraTests.purs
Minor tweak, but much better when things go wrong.
> Using a few special QuickCheck operators to give better error messages.

- hie-cabal.yaml
- nix/dev.nix
- nix/haskell-extra.nix
- shell.nix
Turned out to be very easy: it compiles and works fine as far as I can tell.
> Add hls to our dev packages

- marlowe-playground-client/src/Simulation/BottomPanel.purs
- marlowe-playground-client/static/css/panels.css
- plutus-scb-client/src/MainFrame.purs
- plutus-scb-client/src/Types.purs
* Small changes to css to show indentantion and bullet points in static analysis.
* Move warnings to the top of the enumeration.
> SCP-267 - Improve presentation of static analysis counterexamples

- marlowe-playground-client/grammar.ne
- marlowe-playground-client/package.json
- marlowe-playground-client/src/Marlowe/Blockly.purs
- marlowe-playground-client/src/Marlowe/Gen.purs
- marlowe-playground-client/src/Marlowe/Holes.purs
- marlowe-playground-client/src/Marlowe/Linter.purs
- marlowe-playground-client/src/Marlowe/Monaco.ts
- marlowe-playground-client/src/Marlowe/Parser.purs
- marlowe-playground-client/src/Marlowe/Semantics.purs
- marlowe/doc/marlowe-data.adoc
- marlowe/src/Language/Marlowe/Analysis/FSSemantics.hs
- marlowe/src/Language/Marlowe/Semantics.hs
- marlowe/test/OldAnalysis/FSSemantics.hs
- marlowe/test/Spec/Marlowe/Common.hs
- marlowe/test/Spec/Marlowe/Marlowe.hs
This introduces `Mul` operation to Marlowe DSL
> Scp 286: Arithmetics in Marlowe DSL

- plutus-scb/src/Cardano/Node/Mock.hs
* Don't submit empty transactions
* Don't generate a transaction right away (wait first)
> PAB: Tx generator improvements

- marlowe-playground-client/src/Halogen/Monaco.purs
- marlowe-playground-client/src/Language/Haskell/Monaco.purs
- marlowe-playground-client/src/MainFrame.purs
- marlowe-playground-client/src/Marlowe/Linter.purs
- marlowe-playground-client/src/Marlowe/Monaco.purs
- marlowe-playground-client/src/Simulation.purs
- marlowe-playground-client/src/Simulation/State.purs
- marlowe-playground-client/test/Marlowe/LintTests.purs
See https://jira.iohk.io/browse/SCP-633 for details
> Add current state to linter

- plutus-playground-client/src/Chain.purs
- plutus-playground-client/src/MainFrame.purs
- plutus-playground-client/src/MonadApp.purs
- plutus-playground-client/src/Types.purs
- plutus-playground-client/test/MainFrameTests.purs
- plutus-scb-client/src/MainFrame.purs
- plutus-scb-client/src/Types.purs
- plutus-scb-client/src/View.purs
- web-common/src/Bootstrap.purs
- web-common/src/Chain/Eval.purs
- web-common/src/Chain/Types.purs
- web-common/src/Chain/View.purs
- web-common/src/Clipboard.js
- web-common/src/Clipboard.purs
- web-common/src/Icons.purs
- web-common/static/main.scss
...like the hashes. We display them abbreviated but make it easy to
copy the full version.
> Adding copy-to-clipboard support for the long blockchain IDs.

- plutus-contract/src/Language/Plutus/Contract/Effects/AwaitTxConfirmed.hs
- plutus-contract/src/Language/Plutus/Contract/Effects/OwnPubKey.hs
- plutus-ledger/src/Ledger/Crypto.hs
- plutus-scb/app/PSGenerator.hs
- web-common/src/Data/Json/JsonMap.purs
...and better testing thereof.
> Bugfixes for some JSON encoding errors.

- plutus-scb-client/src/MainFrame.purs
- plutus-scb-client/src/Types.purs
- plutus-scb-client/src/View.purs
- plutus-scb/app/Main.hs
- plutus-scb/src/Plutus/SCB/Core.hs
- plutus-scb/src/Plutus/SCB/Core/ContractInstance.hs
- plutus-scb/src/Plutus/SCB/Query.hs
- plutus-scb/src/Plutus/SCB/Webserver/Server.hs
- plutus-scb/src/Plutus/SCB/Webserver/Types.hs
It was always returning the first status, not the last.
As part of this, I've merged two similar queries and made them a little
easier to work with.
> Bugfix for the latest contract status map.

- plutus-scb/plutus-scb.yaml
- plutus-scb/plutus-scb.yaml.sample
- plutus-scb/src/Cardano/Wallet/Mock.hs
- plutus-scb/src/Cardano/Wallet/Server.hs
- plutus-scb/src/Cardano/Wallet/Types.hs
- plutus-scb/src/Plutus/SCB/MockApp.hs
We need to be able to start the wallet server with different wallets, so that we can spend money from different addresses, etc.
> PAB: Configurable wallet server

- plutus-scb/src/Cardano/ChainIndex/Types.hs
- plutus-scb/src/Cardano/Node/Types.hs
- plutus-scb/src/Cardano/SigningProcess/Server.hs
- plutus-scb/src/Cardano/Wallet/Types.hs
- plutus-scb/src/Plutus/SCB/App.hs
- plutus-scb/src/Plutus/SCB/Effects/Contract.hs
- plutus-scb/src/Plutus/SCB/Effects/ContractTest/AtomicSwap.hs
- plutus-scb/src/Plutus/SCB/Effects/MultiAgent.hs
- plutus-scb/src/Plutus/SCB/Events/Contract.hs
- plutus-scb/src/Plutus/SCB/MockApp.hs
- plutus-scb/src/Plutus/SCB/Query.hs
- plutus-scb/src/Plutus/SCB/Relation.hs
- plutus-scb/src/Plutus/SCB/Types.hs
- plutus-scb/src/Plutus/SCB/Webserver/Types.hs
...with the `StrictData` pragma. We're definitely running into some
space problems if you leave the SCB running overnight. This is a good
first step before some proper profiling.
> Fixing some potential space leak warnings.

- plutus-scb-client/src/View.purs
- plutus-scb-client/src/View/Blockchain.purs
- plutus-scb-client/src/View/Contracts.purs
- plutus-scb-client/src/View/Events.purs
- plutus-scb-client/src/View/Utils.purs
It's become unweildly. Time to separate.
> SCB: Refactoring the UI.

- plutus-scb/plutus-scb.yaml
- plutus-scb/plutus-scb.yaml.sample
- plutus-scb/src/Cardano/Node/Server.hs
- plutus-scb/src/Cardano/Node/Types.hs
- plutus-scb/src/Plutus/SCB/MockApp.hs
* The list of wallets that receive money from the initial transaction is
now configurable.
> PAB: Configurable list of initial wallets

- plutus-scb/src/Plutus/SCB/Core/ContractInstance.hs
Handling contract requests has two phases.
1) Look at the current requests of the contract and handle one of them (if possible) using the PAB components: Chain index, wallet, node, ...
2) Invoke the contract executable with the result of step (1) and update the list of open requests that the contract instance has.
We weren't doing step (2) so nothing ever happened. We need to call `processContractInbox` after handling a request for the contract instance. 
This was fixed on the demo branch but somehow got lost in the process.
> PAB: Actually invoke contract

- docs/CEK.md
- docs/fomega/evaluation/CEK.md
- metatheory/Algorithmic/CK.lagda.md
This pull request adds a markdown document describing two different versions of the CEK machine:
https://github.com/jmchapman/plutus/blob/master/docs/CEK.md
> CEK proposal

- plutus-scb-client/src/MainFrame.purs
- plutus-scb-client/src/Types.purs
- plutus-scb-client/src/View.purs
- plutus-scb-client/src/View/Contracts.purs
- plutus-scb-client/src/View/Events.purs
- web-common/src/Bootstrap.purs
- web-common/src/Chain/Types.purs
- web-common/src/Chain/View.purs
- web-common/src/Playground/Lenses.purs
* Added much better formatting to the event log.
* Reused some Chain.View code to improve the UtxoIndex.
* Removed the Tx view, as it really doesn't add anything that the
Blockchain view doesn't show better.
> SCB: Sprucing up the Event page.

- nix/stack.materialized/plutus-scb.nix
- plutus-scb/pay-to-wallet-contract/Main.hs
- plutus-scb/plutus-scb.cabal
- plutus-scb/src/Plutus/SCB/Effects/ContractTest.hs
- plutus-scb/src/Plutus/SCB/Effects/ContractTest/PayToWallet.hs
Just like what we have in the Playground. Useful for trading tokens, etc.
> PAB: Add a 'payToWallet' contract for testing

- deployment/terraform/variables.tf
@krisajenkins @palas can you apply this in your environments and check that everything is ok
> reduce playground instance size

- default.nix
- nix/haddock-combine.nix
Was just having a look at this, a tiny fix to use the right GHC.
> Use the right GHC package for haddock

- marlowe-playground-client/src/Marlowe/Blockly.purs
> change blockly colours

- marlowe-playground-client/src/Halogen/Classes.purs
- marlowe-playground-client/src/HaskellEditor.purs
- marlowe-playground-client/src/Simulation.purs
- marlowe-playground-client/src/Simulation/BottomPanel.purs
- marlowe-playground-client/src/Types.purs
- marlowe-playground-client/src/Wallet.purs
- marlowe-playground-client/static/css/css_var_globals.css
- marlowe-playground-client/static/css/main.scss
- marlowe-playground-client/static/css/panels.css
Also changed layout of Choice in input composer to avoid double wrap issue
> SCP 433 - resize bottom panel on Simulation and Haskell Editor

- marlowe-playground-client/grammar.ne
- marlowe-playground-client/src/Marlowe/Blockly.purs
- marlowe-playground-client/src/Marlowe/Gen.purs
- marlowe-playground-client/src/Marlowe/Holes.purs
- marlowe-playground-client/src/Marlowe/Linter.purs
- marlowe-playground-client/src/Marlowe/Parser.purs
- marlowe-playground-client/src/Marlowe/Semantics.purs
- marlowe-playground-client/test/BridgeTests.purs
- marlowe-playground-client/test/contract.json
- marlowe-playground-server/contracts/Escrow.hs
- marlowe-playground-server/contracts/Option.hs
- marlowe-playground-server/test/Spec.hs
- marlowe/doc/embedded-marlowe.adoc
- marlowe/doc/marlowe-data.adoc
- marlowe/doc/potential-problems-with-contracts.adoc
- marlowe/src/Language/Marlowe/Analysis/FSSemantics.hs
- marlowe/src/Language/Marlowe/Semantics.hs
- marlowe/test/OldAnalysis/FSSemantics.hs
- marlowe/test/Spec/Marlowe/Common.hs
- marlowe/test/Spec/Marlowe/Marlowe.hs
- marlowe/test/contract.json
> SCP-844 - Remove default value for ChoiceValue

- marlowe-playground-client/src/Types.purs
- marlowe-playground-client/static/css/panels.css
> SCP-901 - Fix bottom panel bugs

- marlowe-playground-client/src/Help.purs
- marlowe-playground-client/src/Simulation.purs
- marlowe-playground-client/static/css/panels.css
Please review the text, deployed to https://david.marlowe.iohkdev.io/
> add marlowe editor help

- marlowe-playground-client/src/Marlowe/Blockly.purs
- marlowe-playground-client/src/Marlowe/Holes.purs
- marlowe-playground-client/src/Marlowe/Monaco.ts
- marlowe-playground-client/src/Simulation.purs
- marlowe-playground-client/test/Marlowe/LintTests.purs
* Don't insert a hole when creating a When
* Improve messages for missing bounds and choice validation
* Fix type-ahead for empty array
> SCP-884 - Some editor updates

- doc/tutorials/plutus-tx.rst
Fixed the conflicts and comments on https://github.com/input-output-hk/plutus/pull/2147 so we can get it in.
> Updated version of Fernando's comments on the Plutus Tx tutorial

- doc/default.nix
- doc/plutus-doc.cabal
- doc/reference/glossary.rst
- doc/tutorials/BasicValidators.hs
- doc/tutorials/basic-validators.rst
- doc/tutorials/index.rst
- doc/tutorials/plutus-tx.rst
- nix/stack.materialized/plutus-doc.nix
Next up: basic forging policies.
The previous PR seemed to be broken somehow.
> Basic validator tutorial

- doc/plutus-doc.cabal
- doc/reference/glossary.rst
- doc/tutorials/BasicPolicies.hs
- doc/tutorials/basic-forging-policies.rst
- doc/tutorials/basic-validators.rst
- doc/tutorials/index.rst
- nix/stack.materialized/plutus-doc.nix
Bit shorter, since it's mostly the same ideas.
> Basic forging policy tutorial

- language-plutus-core/src/Language/PlutusCore/Constant/Apply.hs
- language-plutus-core/src/Language/PlutusCore/Constant/Dynamic/OffChain.hs
- language-plutus-core/src/Language/PlutusCore/Constant/Name.hs
- language-plutus-core/src/Language/PlutusCore/Constant/Typed.hs
- language-plutus-core/src/Language/PlutusCore/Evaluation/Machine/Cek.hs
- language-plutus-core/src/Language/PlutusCore/Evaluation/Machine/Ck.hs
- language-plutus-core/src/Language/PlutusCore/Evaluation/Machine/ExBudgeting.hs
- language-plutus-core/src/Language/PlutusCore/Evaluation/Machine/ExMemory.hs
- language-plutus-core/src/Language/PlutusCore/MkPlc.hs
- language-plutus-core/src/Language/PlutusCore/Universe/Core.hs
- language-plutus-core/test/Evaluation/DynamicBuiltins/Definition.hs
It seems, this does help a lot. The generalized version is still slower than the non-generalized one, but not as much as it was before.
@kwxm could you confirm this is an improvement indeed?
> [PLC] [Builtins] [Evaluation] Made budgeting step pure again

- marlowe-playground-client/src/Marlowe/Linter.purs
- marlowe-playground-client/test/Marlowe/LintTests.purs
Also fix some of the linting messages and parametrised some of the tests
> SCP-906 - Add linting for invalid bounds

- language-plutus-core/test-cost-model/TestCostModels.hs
> Less R property tests

- marlowe-playground-client/src/Reachability.purs
- marlowe-playground-client/src/Simulation.purs
- marlowe-playground-client/src/Simulation/BottomPanel.purs
- marlowe-playground-client/src/Simulation/Types.purs
- marlowe-playground-server/src/Server.hs
- marlowe-playground-server/src/WebSocket.hs
- marlowe-symbolic/src/App.hs
- marlowe-symbolic/src/Marlowe/Symbolic/Types/Request.hs
- marlowe/src/Language/Marlowe/Analysis/FSSemantics.hs
Implement fundamental mechanism for reachability analysis
> SCP-914 - Implement reachability analysis

- marlowe-playground-client/grammar.ne
- marlowe-playground-client/package.json
- marlowe-playground-client/src/HaskellEditor.purs
- marlowe-playground-client/src/Marlowe/Holes.purs
- marlowe-playground-client/src/Marlowe/Parser.js
- marlowe-playground-client/src/Marlowe/Parser.purs
- marlowe-playground-client/yarn.lock
- marlowe-playground-client/yarn.nix
This reverts commit cdc62cc4d50727b3e8ea498e469f455a2841f5c7.
It turns out that this works in a webpack development server but not in a proper bundle ;-(
> Revert "get rid of nearley hack"

- README.adoc
- default.nix
- papers/eutxo/README.md
- papers/eutxoma/Makefile
- papers/eutxoma/README.md
- papers/eutxoma/appendix.tex
- papers/eutxoma/applications.tex
- papers/eutxoma/default.nix
- papers/eutxoma/eutxoma.bib
- papers/eutxoma/eutxoma.tex
- papers/eutxoma/formalisation.tex
- papers/eutxoma/informal.tex
- papers/eutxoma/intro.tex
- papers/eutxoma/llncs.cls
- papers/eutxoma/related-work.tex
- papers/eutxoma/splncs04.bst
- papers/utxoma/Makefile
- papers/utxoma/README.md
- papers/utxoma/applications.tex
- papers/utxoma/default.nix
- papers/utxoma/discussion.tex
- papers/utxoma/intro.tex
- papers/utxoma/llncs.cls
- papers/utxoma/model.tex
- papers/utxoma/mps-language.tex
- papers/utxoma/multicurrency.tex
- papers/utxoma/splncs04.bst
- papers/utxoma/utxoma.bib
- papers/utxoma/utxoma.tex
The final versions have been submitted, so we're not revealing anything any more.
I also renamed the files a little to make them more consistent:
- `plain-multicurrency` -> `utxoma`
- `multicurrency` -> `eutxoma`
> Move ISOLA papers to the main repository

- language-plutus-core/generators/Language/PlutusCore/Generators/Internal/Denotation.hs
- language-plutus-core/generators/Language/PlutusCore/Generators/Internal/Entity.hs
- language-plutus-core/src/Language/PlutusCore/Constant/Apply.hs
- language-plutus-core/src/Language/PlutusCore/Constant/Function.hs
- language-plutus-core/src/Language/PlutusCore/Constant/Name.hs
- language-plutus-core/src/Language/PlutusCore/Constant/Typed.hs
- language-plutus-core/stdlib/Language/PlutusCore/StdLib/Data/List.hs
- language-plutus-core/stdlib/Language/PlutusCore/StdLib/Data/Nat.hs
- language-plutus-core/test/Evaluation/DynamicBuiltins/Definition.hs
Turned out to be fairly straightforward.
> [PLC] [Builtins] Allow binding type variables of any kind in the type of a built-in function

- language-plutus-core/docs/Typechecking PIR.md
[Rendered](https://github.com/input-output-hk/plutus/blob/ec1540a2da65280002f5877c64cda3480b81edef/language-plutus-core/docs/Typechecking%20PIR.md)
> [PIR] [Docs] Added a doc about type checking PIR

- plutus-contract/src/Wallet/Emulator/Chain.hs
- plutus-scb/plutus-scb.yaml.sample
- plutus-scb/src/Cardano/Node/Mock.hs
- plutus-scb/src/Cardano/Node/Server.hs
- plutus-scb/src/Cardano/Node/Types.hs
- plutus-scb/src/Cardano/Protocol/ChainEffect.hs
- plutus-scb/src/Cardano/Protocol/FollowerEffect.hs
- plutus-scb/src/Cardano/Protocol/Socket/Client.hs
- plutus-scb/src/Cardano/Protocol/Socket/Server.hs
1) Hoisting of ChainSyncServer onto IO.
2) Use MTL for writing the state transition code.
3) Remove a bunch of where blocks, make variable provenance clearer.
> Refactoring the node server and client.

- language-plutus-core/src/Language/PlutusCore/Evaluation/Machine/Cek.hs
This is a minor update to the CEK machine.  In the previous version, variable bindings were stored in an environment in a reader monad and retrieved/updated as required.  This version threads environments through the machine instead.  I think this has several advantages:
* It makes the structure of the machine a bit clearer.
* It corresponds more closely to what's in the specification.
* The stuff in the Reader monad now never needs to be updated: we could just store it in read-only global variables if we had such things.
* The `returnCek` function never actually needs the "current" environment: all the environments it needs are in the CekValues and the frames.  Now it's impossible for it to use the current environment by mistake.
I have some figures that show that it makes the machine …
> Thread environments through CEK machine

- marlowe-playground-client/src/MainFrame.purs
- marlowe-playground-client/src/Router.purs
- marlowe-playground-client/src/Simulation.purs
By entering the gist id in the URL it will be loaded, e.g. https://david.marlowe.iohkdev.io/#/simulation?gistid=67db48f4b146ccb85d09b734d640977e will display the simulation tab and will have loaded gist with id 67db48f4b146ccb85d09b734d640977e (to test, it should be waiing for Participant bob to make a choice).
> Load gist from URL

- marlowe-playground-client/src/Main.purs
- plutus-scb-client/src/Main.purs
- web-common/src/WebSocket/Support.purs
...causing messages to the server to not be sent.
Fixes #96.
> FE: Fixing some websockets code that was lost in a rebase.

- plutus-contract/src/Wallet/Emulator/ChainIndex.hs
- plutus-contract/src/Wallet/Emulator/ChainIndex/Index.hs
- plutus-contract/src/Wallet/Emulator/MultiAgent.hs
- plutus-playground-client/src/Chain.purs
- plutus-playground-server/app/PSGenerator.hs
- plutus-scb/src/Cardano/ChainIndex/Server.hs
- plutus-scb/src/Plutus/SCB/Effects/MultiAgent.hs
Use `LogMsg` instead of `Writer`, and add a new log message.
> SCP-1096: Chain index improvements

- marlowe-playground-client/src/Simulation.purs
- marlowe-playground-client/src/Simulation/BottomPanel.purs
- marlowe-playground-client/src/Simulation/State.purs
- marlowe-playground-client/src/Simulation/Types.purs
- marlowe-playground-client/src/Wallet.purs
- marlowe-playground-client/static/css/panels.css
- remove "Next Slot"
- Add "Other Action" that will move forward n slots
- Default value for n is the next "interesting" slot
See any contract in https://david.marlowe.iohkdev.io/ and you can compare to the same contract in https://alpha.marlowe.iohkdev.io/
> Move multiple slots

- web-common/src/WebSocket/Support.purs
The sending thread was completing after the first message. :-o
> Websockets bugfix.

- marlowe-playground-client/packages.dhall
- marlowe-playground-client/spago-packages.nix
- marlowe-playground-client/src/HaskellEditor.purs
- marlowe-playground-client/webpack.config.js
due to the headers we can't currently generate this client. Also I needed to add functionality to servant-support as it only worked with JSON requests.
It looks like we're just adding more complexity with this PR but it is just temporary, I want to keep PRs small so I'm adding stuff and removing stuff in different PRs.
> post to web-ghc working

- default.nix
- marlowe-playground-client/src/HaskellEditor.purs
- web-ghc/app/Webserver.hs
- web-ghc/src/Interpreter.hs
Various fixes that should have been tested! Deployed to https://david.marlowe.iohkdev.io/
> marlowe playground server-side fixes

- plutus-scb/src/Plutus/SCB/MockApp.hs
IMO this is easier to read, and so hopefully easier to modify.
Reviwers - what do you think?
> SCB: Refactoring the MockApp effects resovler.

- plutus-playground-client/src/Chain.purs
> Simplifying a lens lookup.

- cabal.project
- nix/haskell-extra.nix
- nix/sources.json
I did this while I was trying it out again, might as well commit it.
> Update hls to 0.3.0.0

- marlowe-playground-client/src/Language/Javascript/MarloweJS.ts
- marlowe/src/Language/Marlowe/Semantics.hs
- marlowe/test/contract.json
- marlowe/test/state.json
Update Haskell side to use numbers instead of strings for numbers.
Also change intermediate JavaScript representation to use BigNumber instead of strings.
> SCP-1194 - Change JSON serialisation/deserialisation on Haskell side to use numbers in JSON

- marlowe-playground-client/src/Marlowe/Semantics.purs
- marlowe-playground-client/src/Reachability.purs
- marlowe-playground-client/src/Simulation/BottomPanel.purs
- marlowe-playground-client/static/css/main-tabs.css
- marlowe-playground-server/app/PSGenerator.hs
- marlowe-symbolic/marlowe-symbolic.cabal
- marlowe-symbolic/src/Marlowe/Symbolic/Server.hs
- marlowe-symbolic/src/Marlowe/Symbolic/Types/Response.hs
- marlowe/src/Language/Marlowe/Semantics.hs
- nix/stack.materialized/marlowe-symbolic.nix
This fixes two bugs:
- Parsing of PK values on result of static analysis
- Misalignment of the simulation icon (that can only be seen for long widths of screen)
> SCP-1157 - Pass result of static analysis using JSON

- marlowe-playground-client/src/Marlowe/Semantics.purs
- marlowe-playground-client/src/Reachability.purs
- marlowe-playground-client/src/Simulation/BottomPanel.purs
- marlowe-playground-client/static/css/main-tabs.css
- marlowe-playground-server/app/PSGenerator.hs
- marlowe-symbolic/marlowe-symbolic.cabal
- marlowe-symbolic/src/Marlowe/Symbolic/Server.hs
- marlowe-symbolic/src/Marlowe/Symbolic/Types/Response.hs
- marlowe/src/Language/Marlowe/Semantics.hs
- nix/stack.materialized/marlowe-symbolic.nix
Since this is a bug fix, I think it would be good to patch Wyoming deployment too
> Wyohack branch - SCP-1157 - Pass result of static analysis using JSON #2321

- plutus-scb/src/Plutus/SCB/ContractCLI.hs
- plutus-scb/src/Plutus/SCB/Core/ContractInstance.hs
- plutus-scb/src/Plutus/SCB/Monitoring.hs
- plutus-scb/test/Plutus/SCB/Events/ContractSpec.hs
* Tweak the logging output (couldn't see the forest for all the trees)
* Add a variant of 'commandLineApp' that hides a user-defined subset of
the schema from the UI
> PAB: Fixes for demo

- marlowe-playground-client/src/Marlowe/Semantics.purs
- marlowe-playground-client/test/contract.json
- marlowe/test/contract.json
Yet another error in the JSON serialisation/deserialisation
> Fix typo in JSON serialisation/deserialisation

- nix/stack.materialized/plutus-ledger.nix
- plutus-ledger/plutus-ledger.cabal
- plutus-ledger/src/Data/Either/Extras.hs
- plutus-ledger/src/Ledger/Crypto.hs
- plutus-ledger/src/LedgerBytes.hs
- plutus-ledger/test/Spec.hs
...which returns an `Either`, instead of throwing an `error`.
> Adding a safe version of LedgerBytes.fromHex.

- cabal.project
- nix/haskell-extra.nix
- nix/sources.json
Has some fixes for emacs from Yours Truly which I would like to use.
> Bump HLS to 0.5.0

- marlowe/src/Language/Marlowe/Pretty.hs
- marlowe/src/Language/Marlowe/Semantics.hs
- nix/stack.materialized/plutus-tx.nix
- nix/stack.materialized/plutus-use-cases.nix
- plutus-ledger/src/Ledger/Oracle.hs
- plutus-ledger/src/Ledger/Tx.hs
- plutus-tx/plutus-tx.cabal
- plutus-tx/src/Language/PlutusTx/Functor.hs
- plutus-tx/src/Language/PlutusTx/Ratio.hs
- plutus-use-cases/plutus-use-cases.cabal
- plutus-use-cases/src/Language/PlutusTx/Coordination/Contracts/Stablecoin.hs
- plutus-use-cases/test/Spec.hs
- plutus-use-cases/test/Spec/Stablecoin.hs
* A simple stablecoin prototype using state machines
> SCP-1193: Stablecoin prototype

- marlowe-playground-client/src/Examples/JS/Contracts.purs
- marlowe-playground-client/src/Language/Javascript/MarloweJS.ts
- marlowe-playground-client/src/StaticData.purs
Deployed in https://pablo.marlowe.iohkdev.io/#/javascript
> SCP-1233 - Make JavaScript Marlowe constructors closer by using capital first letters

- marlowe-playground-client/src/MainFrame.purs
Deployed at https://pablo.marlowe.iohkdev.io/
> SCP-1270 - Send to simulator button in JS doesn't work

- marlowe-playground-client/packages.dhall
- marlowe-playground-client/spago-packages.nix
- plutus-playground-client/packages.dhall
- plutus-playground-client/spago-packages.nix
- plutus-scb-client/packages.dhall
- plutus-scb-client/spago-packages.nix
- plutus-scb-client/src/Types.purs
- plutus-scb-client/src/View.purs
- plutus-scb-client/src/View/Blockchain.purs
- plutus-scb/app/PSGenerator.hs
- plutus-scb/plutus-scb.cabal
- plutus-scb/src/Plutus/SCB/Webserver/Handler.hs
- plutus-scb/src/Plutus/SCB/Webserver/Server.hs
- plutus-scb/src/Plutus/SCB/Webserver/Types.hs
- plutus-scb/test/Plutus/SCB/CoreSpec.hs
- plutus-scb/test/Plutus/SCB/Events/ContractSpec.hs
- plutus-scb/test/Plutus/SCB/RelationSpec.hs
- web-common/packages.dhall
- web-common/spago-packages.nix
- web-common/yarn.nix
> Various small refactorings.

- marlowe-playground-client/src/Examples/JS/Contracts.purs
- marlowe/doc/javascript-embedding.adoc
Deployed at https://pablo.marlowe.iohkdev.io/
> SCP-1232 - Expand tutorial section about JavaScript

- marlowe-playground-server/src/API.hs
- marlowe-playground-server/src/Lambda.hs
- marlowe-playground-server/src/Server.hs
- plutus-playground-server/app/Main.hs
- plutus-playground-server/src/Playground/Lambda.hs
- plutus-playground-server/src/Playground/Server.hs
- plutus-scb/atomic-swap-contract/Main.hs
- plutus-scb/src/Cardano/Protocol/ChainEffect.hs
- plutus-scb/src/Cardano/Protocol/Socket/Server.hs
- plutus-scb/src/Plutus/SCB/Core.hs
- plutus-scb/src/Plutus/SCB/Core/ContractInstance.hs
- plutus-scb/src/Plutus/SCB/Effects/ContractRuntime.hs
- plutus-scb/src/Plutus/SCB/MonadLoggerBridge.hs
- plutus-scb/src/Plutus/SCB/Monitoring.hs
- plutus-scb/src/Plutus/SCB/ParseStringifiedJSON.hs
> Hlint suggestions.

- nix/stack.materialized/plutus-scb.nix
- plutus-scb-client/src/MainFrame.purs
- plutus-scb/plutus-scb.cabal
- plutus-scb/src/Cardano/Metadata/API.hs
- plutus-scb/src/Cardano/Metadata/Client.hs
- plutus-scb/src/Cardano/Metadata/Server.hs
- plutus-scb/src/Cardano/Metadata/Types.hs
- plutus-scb/src/Plutus/SCB/Webserver/Handler.hs
- plutus-scb/src/Plutus/SCB/Webserver/Types.hs
- plutus-scb/test/Cardano/Metadata/ServerSpec.hs
- plutus-scb/test/Spec.hs
The next step will be to add this to the spec, then get Steve to update his
live implementation.
> SCB: Adding batched metadata queries.

- deployment/README.md
- shell.nix
Since Yubikeys are becoming ubiquitous at IOHK, it's worth a special
note.
This PR also added the required Yubikey manager tool `ykman` to `shell.nix`.
> Adding a Yubikey setup guide the the deployment README.

- deployment/default.nix
- marlowe-playground-server/src/API.hs
- marlowe-playground-server/src/Server.hs
- nix/purescript.nix
- playground-common/src/Auth.hs
- playground-common/src/Control/Monad/Web.hs
- plutus-playground-server/src/Playground/Server.hs
Plus a few other small changes that triggered.
> Adding some github debugging code.

- deployment/default.nix
- nix/dev.nix
- shell.nix
* Adding shellcheck to shell.nix.
* Running shellcheck over some of our nix-written shell scripts.
* Fixing the warnings it throws up.
> Shellcheck pass.

- marlowe-playground-client/README.md
- marlowe-playground-client/package.json
- marlowe-playground-client/spago-packages.nix
- marlowe-playground-client/src/Examples/JS/Contracts.purs
- marlowe-playground-client/src/Halogen/Monaco.purs
- marlowe-playground-client/src/JSEditor.purs
- marlowe-playground-client/src/Language/Javascript/Interpreter.js
- marlowe-playground-client/src/Language/Javascript/Interpreter.purs
- marlowe-playground-client/src/Language/Javascript/MarloweJS.ts
- marlowe-playground-client/src/MainFrame.purs
- marlowe-playground-client/src/Marlowe/ActusBlockly.purs
- marlowe-playground-client/src/StaticData.purs
- marlowe-playground-client/yarn.lock
- marlowe-playground-client/yarn.nix
- marlowe/doc/javascript-embedding.adoc
- Replace not-evil with safe-eval
- Improve presentation of errors
- Remove `BigNumber` from the interface of the JavaScript API
- Update examples
Include SCP-1308 by @dk14 
> SCP-1309 - JavaScript safe eval doesn't support all modern JavaScript features

- marlowe/src/Language/Marlowe/Client.hs
- nix/stack.materialized/plutus-scb.nix
- pab-demo-scripts.nix
- plutus-contract/src/Language/Plutus/Contract.hs
- plutus-contract/src/Language/Plutus/Contract/Effects/AwaitSlot.hs
- plutus-contract/src/Language/Plutus/Contract/Effects/RPC.hs
- plutus-scb/plutus-scb.cabal
- plutus-scb/prism/credential-manager/Main.hs
- plutus-scb/prism/mirror/Main.hs
- plutus-scb/prism/unlock-exchange/Main.hs
- plutus-scb/prism/unlock-sto/Main.hs
- plutus-use-cases/src/Language/PlutusTx/Coordination/Contracts/Escrow.hs
- plutus-use-cases/src/Language/PlutusTx/Coordination/Contracts/Prism/Credential.hs
- plutus-use-cases/src/Language/PlutusTx/Coordination/Contracts/Prism/Mirror.hs
- plutus-use-cases/src/Language/PlutusTx/Coordination/Contracts/Prism/Unlock.hs
- plutus-use-cases/src/Language/PlutusTx/Coordination/Contracts/RPC.hs
- plutus-use-cases/test/Spec/Prism.hs
* Add mirror apps to `plutus-scb` and to the demo environment
* Add a retry policy to RPC calls, in case the target instance is busy
> PAB: Add Mirror apps

- shell.nix
> Fix shell affinity for darwin

- plutus-benchmark/validation/Main.hs
Fixing a small problem with paths in the validation benchmarks.  It's only one line, so I'll merge it without review.
> Fix path in validation benhcmarks

- marlowe-playground-client/src/HaskellEditor/State.purs
- marlowe-playground-client/src/HaskellEditor/Types.purs
- marlowe-playground-client/src/JavascriptEditor/State.purs
- marlowe-playground-client/src/JavascriptEditor/Types.purs
- marlowe-playground-client/src/JavascriptEditor/View.purs
- marlowe-playground-client/src/Language/Javascript/Interpreter.purs
- marlowe-playground-client/src/MainFrame/State.purs
- marlowe-playground-client/src/MainFrame/Types.purs
- marlowe-playground-client/src/MainFrame/View.purs
Happy to accept any other refactorings within the scope of the changes too!
> javascript editor should be almost the same as haskell editor

- marlowe-playground-client/src/Halogen/Monaco.purs
- marlowe-playground-client/src/Monaco.js
- playground-common/src/Auth.hs
- plutus-playground-client/src/Chain.purs
- plutus-playground-client/webpack.config.js
- plutus-scb/test/Plutus/SCB/CoreSpec.hs
Mostly tidying and refacotring.
> A few small tweaks that have dropped out of my SCP-1223 work.

- .github/PULL_REQUEST_TEMPLATE.md
- CONTRIBUTING.adoc
We don't have very consistent approaches to some aspects of our process.
I'd like us to be a bit more consistent, especially as we might have
some new people joining.
What I've written here is my opinion: please do say if you disagree!
I would like us to all buy in to whatever we say we're going to do.
> Update CONTRIBUTING and add a PR template with checklists

- .ignore
- shell.nix
> Fix .ignore pattern

- plutus-use-cases/src/Language/PlutusTx/Coordination/Contracts/Stablecoin.hs
- Branch
- PR
----
Fees should always be positive. Thanks to Bruno for spotting this.
> Fix a bug in the stablecoin fee calculation

- plutus-playground-server/src/Playground/Usecases.hs
> Playground bugfix: The demo files appeared with an extra newline at the start.

- .github/PULL_REQUEST_TEMPLATE.md
> Changed the update materialized nix files command.

- nix/stack.materialized/default.nix
- nix/stack.materialized/plutus-benchmark.nix
- plutus-benchmark/.gitignore
- plutus-benchmark/flat/Codec.hs
- plutus-benchmark/flat/Dataset.hs
- plutus-benchmark/flat/Main.hs
- plutus-benchmark/flat/Report.hs
- plutus-benchmark/plutus-benchmark.cabal
- stack.yaml
> Add flat benchmarks.

- hie-cabal.yaml
I ran `haskell-language-server` in the background for a bit and fixed a
few things.
- Branch
- PR
> Minor hie-cabal.yaml improvements

- ci.nix
- nix/lib/ci.nix
This commit doesn't (should not!) introduce any meaningful changes to
ci.nix but extracts some functions, adds comments and hopefully makes it
a bit easier to understand what is happening.
----
- Branch
- PR
> Refactor ci.nix slightly

- default.nix
- marlowe-playground-client/src/Blockly.purs
- marlowe-playground-client/src/Halogen/ActusBlockly.purs
- marlowe-playground-client/src/Halogen/Blockly.purs
- marlowe-playground-client/src/MainFrame/State.purs
- marlowe-playground-client/src/Marlowe/ActusBlockly.purs
- marlowe-playground-client/src/Marlowe/Blockly.purs
- marlowe-playground-client/src/Marlowe/Semantics.purs
- marlowe-playground-client/src/Reachability.purs
- marlowe-playground-client/src/Wallet.purs
- nix/pkgs/default.nix
- nix/pkgs/haskell/extra.nix
- nix/sources.json
- nix/tests/default.nix
- plutus-playground-client/src/Chain.purs
- plutus-playground-client/src/MainFrame.purs
- plutus-playground-client/test/ChainTests.purs
- plutus-playground-client/test/JsonEncodingTests.purs
- plutus-playground-client/test/Schema/TypesTests.purs
- plutus-scb-client/src/MainFrame.purs
- shell.nix
- web-common/src/Chartist.purs
- web-common/src/Halogen/Chartist.purs
- web-common/src/Halogen/Monaco.purs
- web-common/src/Ledger/Extra.purs
Also bump easyPS so we get a new version of purty, leading to some
formatting changes.
- Branch
- PR
> Move to easyPS purty

- README.adoc
- ci.nix
- default.nix
- marlowe-playground-client/default.nix
- nix/docs.nix
- plutus-playground-client/default.nix
- plutus-scb-client/default.nix
- release.nix
We lost some jobs from our jobset, trying to get them back. Nothing to see here yet.
- Branch
- PR
> Fix missing hydra jobs

- deployment/README.md
- deployment/terraform/lambdas.tf
- deployment/terraform/ssh_config.tf
> A pair of small deployment script tweaks.

- marlowe-playground-client/src/MainFrame/State.purs
- marlowe-playground-client/src/MainFrame/Types.purs
- marlowe-playground-client/src/Marlowe/Linter.purs
- marlowe-playground-client/src/Reachability.purs
- marlowe-playground-client/src/Simulation/State.purs
- marlowe-playground-client/src/Simulation/Types.purs
- marlowe-playground-client/src/Wallet.purs
- marlowe-playground-client/src/WalletSimulation/Types.purs
Contents of PR:
- Connect the results of Reachability analysis with Linting mechanism, so they are shown in the code
- Fix bug in first step of reachability analysis
- Move types in Wallet.purs to their own file so that they don't produce cycles in dependencies.
Example test:
- Paste the following example in the simulator:
```haskell
When [Case (Deposit (Role "alice") (Role "alice") (Token "" "") (Constant 450)) (When [Case (Choice (ChoiceId "choice" (Role "alice")) [Bound 0 1]) (When [Case (Choice (ChoiceId "choice" (Role "bob")) [Bound 0 1]) (If (ValueEQ (ChoiceValue (ChoiceId "choice" (Role "alice"))) (ChoiceValue (ChoiceId "choice" (Role "bob")))) (If (ValueEQ (ChoiceValue (ChoiceId "choice" (Role "alice"))) (Constant 2)) (Pay (Role …
```
> SCP-952 - Find a good way of showing the result of reachability analysis

- marlowe-playground-client/src/JavascriptEditor/State.purs
Fixes bug: The whole Marlowe Playground hangs when local storage is empty
- Branch
- PR
> SCP-1506 - Fix inifinite loop problem with JavaScript editor

- marlowe/marlowe.cabal
- marlowe/src/Language/Marlowe/Client.hs
- marlowe/src/Language/Marlowe/Semantics.hs
- marlowe/src/Language/Marlowe/Util.hs
- marlowe/test/Spec.hs
- marlowe/test/Spec/Marlowe/AutoExecute.hs
- marlowe/test/Spec/Marlowe/Marlowe.hs
- nix/stack.materialized/marlowe.nix
- plutus-contract/src/Language/Plutus/Contract/StateMachine.hs
Works only for simple deposits, and `When [] timeout cont` contracts for now.
> SCP-1331 Automatic Execution of Marlowe Contracts

- marlowe-actus/src/Language/Marlowe/ACTUS/Generator.hs
- marlowe-playground-client/src/Halogen/ActusBlockly.purs
> disable rate reset for static contracts

- nix/stack.materialized/plutus-tx-plugin.nix
- plutus-tx-plugin/plutus-tx-plugin.cabal
- plutus-tx-plugin/test/StdLib/Spec.hs
We were already guarding against this properly in some places, but not
all.
- Branch
- PR
> Catch exceptions in Plutus Tx tests

- plutus-core/src/Language/PlutusCore/Builtins.hs
- plutus-core/src/Language/PlutusCore/Constant/Apply.hs
- plutus-core/src/Language/PlutusCore/Constant/Typed.hs
- plutus-core/src/Language/PlutusCore/Evaluation/Machine/Cek.hs
- plutus-core/src/Language/PlutusCore/Evaluation/Machine/Ck.hs
- plutus-core/src/Language/PlutusCore/Evaluation/Machine/Exception.hs
- plutus-core/src/Language/PlutusCore/Evaluation/Result.hs
- plutus-core/test/Evaluation/ApplyBuiltinName.hs
- plutus-core/test/Evaluation/Golden.hs
- plutus-core/test/Evaluation/Golden/takeTooMuch.plc.golden
- plutus-core/test/Evaluation/Golden/takeTooMuch.type.golden
- plutus-core/untyped-plutus-core-test/Evaluation/ApplyBuiltinName.hs
- plutus-core/untyped-plutus-core/Language/UntypedPlutusCore/Evaluation/Machine/Cek.hs
This fixes an embarrassing bug found by @bezirg. 
- Branch
- PR
> [Bug] [PLC] [Builtins] Unlifting to 'Int' can fail

- marlowe/marlowe.cabal
- marlowe/src/Language/Marlowe/Client.hs
- marlowe/test/Spec/Marlowe/AutoExecute.hs
- marlowe/test/Spec/Marlowe/Marlowe.hs
- nix/stack.materialized/marlowe.nix
- plutus-tx/src/Language/PlutusTx/AssocMap.hs
- plutus-tx/src/Language/PlutusTx/Monoid.hs
- plutus-tx/src/Language/PlutusTx/Semigroup.hs
> Create and distribute role tokens

- .gitignore
>  Some more .gitignore haskell files

- plutus-tx/src/Language/PlutusTx/Lift/Class.hs
This fixes the test failure for the nixpkgs up date branch.
I don't understand why this might have made things fail, but what was
happening certainly seemed wrong. There's a long note in the code
explaning the problem.
(I pulled this out since it's independently reviewable, but I verified that it fixes the other branch, which I'll update after this is done.)
- Branch
- PR
> Be more careful with the 'fun' variable in TH

- README.adoc
> Fix some nix attribute names in the readme

- doc/index.rst
> Adding references to the documentation

- default.nix
- marlowe-playground-client/default.nix
- marlowe-playground-server/lambda.nix
- marlowe-symbolic/lambda.nix
- nix/patches/ghcide_partial_iface.patch
- nix/pkgs/default.nix
- nix/pkgs/haskell/default.nix
- nix/pkgs/haskell/extra.nix
- nix/pkgs/haskell/haskell.nix
- nix/sources.json
- plutus-playground-client/default.nix
- plutus-playground-server/lambda.nix
- shell.nix
> Use ghc8102-experimental from haskell.nix

- ci.nix
Not 100% sure this will be sufficient, let's see.
- Branch
- PR
> Fix uncached GHC 8.8.4 dependency

- marlowe/src/Language/Marlowe/Client.hs
- marlowe/test/Spec/Marlowe/AutoExecute.hs
- marlowe/test/Spec/Marlowe/Marlowe.hs
> Redeem role payouts

- plutus-core/src/Language/PlutusCore/Flat.hs
- plutus-core/untyped-plutus-core/Language/UntypedPlutusCore/Core/Instance/Flat.hs
- plutus-use-cases/test/Spec/crowdfundingTestOutput.txt
- plutus-use-cases/test/Spec/renderCrowdfunding.txt
- plutus-use-cases/test/Spec/renderGuess.txt
- plutus-use-cases/test/Spec/renderVesting.txt
We need the encoding not to rely on word witdth.
- Branch
- PR
> Change encoding of constants.

- ci.nix
- deployment/shell.nix
- nix/pkgs/thorp/default.nix
- nix/pkgs/thorp/missing-lock.json
- nix/pkgs/thorp/mvn2nix-lock.json
- nix/sources.json
- release.nix
- shell.nix
> fix thorp after it was upgraded and add to ci

- marlowe-playground-client/src/Marlowe/Linter.purs
- marlowe-playground-client/src/Marlowe/Semantics.purs
- marlowe-playground-client/src/Pretty.purs
- marlowe-playground-client/src/Simulation.purs
- marlowe-playground-client/src/Simulation/BottomPanel.purs
- marlowe-playground-client/src/Simulation/State.purs
- marlowe-playground-client/src/Wallet.purs
- marlowe-playground-client/test/Marlowe/LintTests.purs
> Pretty party, money, tokens, and payee in Marlowe Playground

- nix/pkgs/haskell/extra.nix
- nix/sources.json
Early Christmas present.
- Branch
- PR
> Bump HLS to 0.7.1

- plutus-core/exe/Main.hs
> Breaks compilation with `-haddock` enabled.

- nix/docker.nix
- nix/pkgs/web-ghc/default.nix
> webghc (and docker image) was broken

- nix/stack.materialized/plutus-contract.nix
- nix/stack.materialized/plutus-tx.nix
- plutus-contract/plutus-contract.cabal
- plutus-contract/src/Wallet/Emulator/Chain.hs
- plutus-ledger/src/Ledger/Address.hs
- plutus-ledger/src/Ledger/Crypto.hs
- plutus-ledger/src/Ledger/Index.hs
- plutus-ledger/src/Ledger/Interval.hs
- plutus-ledger/src/Ledger/Scripts.hs
- plutus-ledger/src/Ledger/Slot.hs
- plutus-ledger/src/Ledger/Tx.hs
- plutus-ledger/src/Ledger/TxId.hs
- plutus-ledger/src/Ledger/Value.hs
- plutus-ledger/src/LedgerBytes.hs
- plutus-tx/plutus-tx.cabal
- plutus-tx/src/Language/PlutusTx/AssocMap.hs
- plutus-tx/src/Language/PlutusTx/Data.hs
> Add NFData instances for Tx and ChainState

- .github/PULL_REQUEST_TEMPLATE.md
> Correcting an out-of-date reference in the PR template.

- nix/stack.materialized/plutus-contract.nix
- plutus-contract/plutus-contract.cabal
- plutus-contract/src/Data/UUID/Extras.hs
- plutus-contract/src/Plutus/Trace/Tag.hs
- plutus-contract/src/Wallet/Emulator/Notify.hs
- plutus-contract/src/Wallet/Types.hs
- plutus-scb/src/Plutus/SCB/Types.hs
- plutus-use-cases/test/Spec/contractError.txt
- plutus-use-cases/test/Spec/crowdfundingEmulatorTestOutput.txt
- plutus-use-cases/test/Spec/crowdfundingWallet1TestOutput.txt
> A couple of patches to fix JSON encoding in the playground.

- shell.nix
This bit of https://github.com/input-output-hk/plutus/pull/2590 actually
seems to help.
- Branch
- PR
> Don't include hoogle in the shell

- playground-common/src/Playground/Interpreter/Util.hs
- playground-common/src/Playground/Types.hs
- web-common/.gitignore
* Reverse order of logs (newest first)
* Filter out irrevelant events
- Branch
- PR
> playground-common: Improve emulator logs

- nix/stack.materialized/plutus-use-cases.nix
- playground-common/src/PSGenerator/Common.hs
- plutus-contract/src/Language/Plutus/Contract/Test.hs
- plutus-contract/src/Language/Plutus/Contract/Util.hs
- plutus-contract/src/Wallet/Emulator/Chain.hs
- plutus-contract/src/Wallet/Emulator/Folds.hs
- plutus-contract/src/Wallet/Rollup.hs
- plutus-contract/test/Spec/Emulator.hs
- plutus-ledger/src/Ledger/Generators.hs
- plutus-ledger/src/Ledger/Index.hs
- plutus-ledger/src/Ledger/Scripts.hs
- plutus-playground-client/src/Chain.purs
- plutus-use-cases/ARCHITECTURE.adoc
- plutus-use-cases/plutus-use-cases.cabal
- plutus-use-cases/scripts/Main.hs
- plutus-use-cases/src/Language/PlutusTx/Coordination/Contracts/Currency.hs
- plutus-use-cases/test/Spec/Currency.hs
- plutus-use-cases/test/Spec/Escrow.hs
- plutus-use-cases/test/Spec/Future.hs
- plutus-use-cases/test/Spec/GameStateMachine.hs
- plutus-use-cases/test/Spec/MultiSig.hs
- plutus-use-cases/test/Spec/MultiSigStateMachine.hs
- plutus-use-cases/test/Spec/PingPong.hs
- plutus-use-cases/test/Spec/Prism.hs
- plutus-use-cases/test/Spec/PubKey.hs
- plutus-use-cases/test/Spec/Stablecoin.hs
- plutus-use-cases/test/Spec/TokenAccount.hs
* Add applied validators & monetary policy scripts to emulated node event log
* Write out all scripts from `plutus-use-cases` to `${folder}` with `cabal new-run plutus-use-cases-scripts -- ${folder}`
- Branch
- PR
> SCP-1514 Extract scripts

- playground-common/src/PSGenerator/Common.hs
- plutus-scb/app/PSGenerator.hs
* Fix some conflicts in the generated Purescript
- Branch
- PR
> plutus-scb: Fix psgenerator

- marlowe-playground-client/grammar.ne
- marlowe-playground-client/src/Text/Parsing/Parser/Basic.purs
- marlowe-playground-client/test/Marlowe/ParserTests.purs
- marlowe-playground-server/contracts/ZeroCouponBond.hs
- web-ghc/src/Interpreter.hs
> SCP-1617 Allow underscores in numeric literals in Marlowe

- marlowe-playground-client/packages.dhall
- marlowe-playground-client/spago-packages.nix
- marlowe-playground-client/src/MainFrame/State.purs
- marlowe-playground-client/src/MarloweEditor/BottomPanel.purs
- playground-common/src/Auth.hs
- plutus-pab-client/packages.dhall
- plutus-pab-client/spago-packages.nix
- plutus-playground-client/packages.dhall
- plutus-playground-client/spago-packages.nix
- web-common/src/AjaxUtils.purs
> Adding 404 handling to Ajax Requests, and to Gist fetches.

- nix/lib/latex.nix
- nix/sources.json
> Make nix work with MacOS Big Sur

- doc/tutorials/basic-apps.rst
- doc/tutorials/plutus-playground.rst
> Playground refresh tutorial updates

- doc/tutorials/basic-apps.rst
> Fix inline markup

- hie-cabal.yaml
- hie-stack.yaml
- nix/stack.materialized/plutus-pab.nix
- plutus-pab/plutus-pab.cabal
- plutus-pab/src/Cardano/Node/RandomTx.hs
- plutus-pab/tx-inject/Main.hs
- plutus-pab/tx-inject/config.yaml
- plutus-pab/tx-inject/start-all-servers.sh
> Inject transactions into the PAB.

- plutus-playground-client/src/MainFrame/View.purs
> A few last minute weaks and fixes needed for the frontend release.

- plutus-pab/test/Cardano/Metadata/query_response2.json
Very minor, but just to keep it in perfectly in sync.
- Branch
- PR
> Updating the golden test files for the metadata queries.

- doc/tutorials/basic-apps.rst
> Fix a literal include in basic-apps.rst

- plutus-playground-client/webpack.config.js
- web-common/static/index.html
This doesn't include fine-grained event tracking, which is a bigger PR.
- Branch
- PR
> Adding basic Segment.com tracking code.

- web-common-plutus/src/Schema/Types.purs
This fixes the bug described in SCP-1697.
The simplicity of the solution does not reflect the complexity of the hunt to figure out what the damn problem was... 😓
> SCP-1697: Correcting the algebra for the nested tuple form event handler.

- notes/pab-client-interaction/README.md
- plutus-pab/src/Plutus/PAB/Webserver/API.hs
* Add a document explaining how an appliation such as the Marlowe dashboard can interact with the PAB
* Add a new API that supports this interaction
- Branch
- PR
> SCP-1685: PAB client interaction docs & API

- marlowe/app/Main.hs
- marlowe/marlowe.cabal
- nix/pkgs/haskell/materialized-musl/.plan.nix/marlowe.nix
- nix/pkgs/haskell/materialized-unix/.plan.nix/marlowe.nix
* Add an executable that wraps the Marlowe app so that it can be installed in the PAB.
- Branch
- PR
> SCP-1266: Marlowe app for PAB

- plutus-pab-client/default.nix
- plutus-pab-client/pab-demo-scripts.nix
- plutus-pab/README.md
plutus-pab has been around for a while but never got a README so i'm adding one. Should make things easier for the next person starting out on working on this code.
[README.md](https://github.com/input-output-hk/plutus/blob/pab-readme/plutus-pab/README.md)
**Notes**:
This PR also contains changes to pab-demo-scripts:
- **pab-demo-scripts.nix** was refactored: It doesn't require passing of a local sqlite database file anymore. Instead a database migration takes place to a temporary directory on startup. Also has some useful output now.
----
- Branch
- PR
> plutus-pab: Add README.md

- plutus-contract/src/Language/Plutus/Contract.hs
- plutus-contract/src/Language/Plutus/Contract/Effects/Notify.hs
- plutus-contract/src/Language/Plutus/Contract/Effects/RPC.hs
- plutus-pab/src/Plutus/PAB/Effects/Contract.hs
- plutus-pab/src/Plutus/PAB/Events/Contract.hs
- plutus-use-cases/src/Language/PlutusTx/Coordination/Contracts/Auction.hs
* Follow-up from #2683
- Branch
- PR
> plutus-contract: Add notify placeholder

- plutus-metatheory/src/Algorithmic/Erasure.lagda
- plutus-metatheory/src/Algorithmic/Erasure/Reduction.lagda
- plutus-metatheory/src/Algorithmic/Reduction.lagda
- plutus-metatheory/src/Declarative/Erasure.lagda.md
- plutus-metatheory/src/Scoped/Erasure.lagda
- plutus-metatheory/src/Untyped.lagda
- plutus-metatheory/src/Untyped/Reduction.lagda
- plutus-metatheory/src/Untyped/RenamingSubstitution.lagda
- plutus-metatheory/src/index.lagda.md
> SCP-1822 formalising builtins for untyped PLC 

- plutus-pab/src/Plutus/PAB/Webserver/API.hs
> Fix a type in the API

- cabal.project
- nix/pkgs/haskell/haskell.nix
- nix/pkgs/haskell/materialized-musl/default.nix
- nix/pkgs/haskell/materialized-unix/default.nix
- stack.yaml
- web-ghc/app/Webserver.hs
- web-ghc/web-ghc.cabal
> update 2 libs

- plutus-pab/app/Main.hs
- plutus-pab/src/Cardano/Wallet/Server.hs
- plutus-pab/src/Cardano/Wallet/Types.hs
- plutus-pab/src/Plutus/PAB/PABLogMsg.hs
**Description**: Switch logging in `Cardano.Wallet` to freer logging
- Added `WalletMsg` type for the structural logging
- Massaging the types for Wallet.Server.main
- Very minor code refactoring in `Wallet.Server.main`
----
- Branch
- PR
> SCP-1687: adjust WalletServer logging

- doc/index.rst
The link to Haddock is broken:
https://github.com/input-output-hk/plutus/blob/master/doc/haddock/index.html
- Branch
- PR
> Broken link for Haddock

- plutus-pab/app/Main.hs
- plutus-pab/src/Cardano/Metadata/Server.hs
- plutus-pab/src/Cardano/Metadata/Types.hs
- plutus-pab/src/Plutus/PAB/PABLogMsg.hs
Adjust logging and types in MetaDataServer to use structured logging
via Tracer from the iohk-monitoring library.
- Branch
- PR
> SCP-1687: Switch MetaDataServer to freer logging

- stack.yaml
> Fix some errors preventing "stack build" from finishing.

- nix/pkgs/haskell/materialized-musl/.plan.nix/plutus-benchmark.nix
- nix/pkgs/haskell/materialized-unix/.plan.nix/plutus-benchmark.nix
- plutus-benchmark/flat/Dataset.hs
- plutus-benchmark/plutus-benchmark.cabal
> Add Marlowe to benchmarks

- doc/conf.py
> Fix a link in the documentation

- README.adoc
> Add link for the online version of the tutorial

- plutus-core/generators/Language/PlutusCore/Generators/NEAT/Spec.hs
This PR simply adds a check that
`erase . typed_CEK == untyped_CEK . erase` 
in the NEAT tests of `plutus-core-test`.
- Branch
- PR
> SCP -1289 untyped vs typed CEK in plutus-core-test NEAT

- plutus-pab/src/Cardano/Node/Mock.hs
Refactor Cardano.Node.Mock.runChainEffects slightly to make it easier to
follow what is going on.
I've struggled parsing `runChainEffects` multiple times and rearranging
it this way has definitely helped me. With the extracted where clauses
you can nicely inspect the types and see how they individually run/peel
off effects. Switching to `(&)` the code can now also be read in the
order of sequential execution.
*TL&DR*: Nothing big, but helps with readability (I hope).
- Branch
- PR
> plutus-pab: Refactor runChainEffects

- marlowe-playground-client/src/Demos/View.purs
- marlowe-playground-client/src/Examples/JS/Contracts.purs
- marlowe-playground-client/src/StaticData.purs
- marlowe-playground-server/app/PSGenerator.hs
- marlowe-playground-server/contracts/EscrowWithCollateral.hs
- marlowe-playground-server/marlowe-playground-server.cabal
- marlowe-playground-server/src/Marlowe/Contracts.hs
- nix/pkgs/haskell/materialized-musl/.plan.nix/marlowe-playground-server.nix
- nix/pkgs/haskell/materialized-unix/.plan.nix/marlowe-playground-server.nix
> collaterized escrow example

- marlowe-playground-client/src/Examples/JS/Contracts.purs
- marlowe-playground-client/src/JavascriptEditor/State.purs
- marlowe-playground-client/src/JavascriptEditor/Types.purs
- marlowe-playground-client/src/JavascriptEditor/View.purs
- marlowe-playground-client/src/Language/Javascript/MarloweJS.ts
This PR adds Extended Marlowe to JavaScript tab and modifies its static analysis to support it too.
In particular:
- Disables analysis buttons when not compiled
- Adds "Clear" button to Static Analysis
- Updates template parameters on compilation of JS
- Fixes JavaScript version of Escrow with collateral (which had headers and shouldn't)
- Adds `SlotParam` construct to JavaScript
- Adds `ConstantParam` to JavaScript
Example:
```javascript
/* Parties */
const alice : Party = Role("alice");
const bob : Party = Role("bob");
const carol : Party = Role("carol");
/* Value under escrow */
const price : Value = ConstantParam("Escrow amount");
/* helper function to build Actions */
const choiceName : string = "choice";
const choiceIdBy = function …
```
> SCP-1842 - Add "Extended Marlowe" types to JavaScript

- nix/pkgs/haskell/materialized-musl/.plan.nix/plutus-pab.nix
- nix/pkgs/haskell/materialized-unix/.plan.nix/plutus-pab.nix
- plutus-pab/plutus-pab.cabal
- plutus-pab/src/Plutus/PAB/Core/ContractInstance.hs
- plutus-pab/src/Plutus/PAB/Core/ContractInstance/STM.hs
* Add some types for the new contract instance model in the PAB
- Branch
- PR
- x ] `nix-shell shell.nix --run fix-stylish-haskell` to fix any formatting issues
> SCP-1857: Add some types for the new contract instance model in the PAB

- plutus-pab/app/Cli.hs
- plutus-pab/src/Cardano/ChainIndex/Client.hs
- plutus-pab/src/Cardano/Metadata/Client.hs
- plutus-pab/src/Cardano/Node/Client.hs
- plutus-pab/src/Cardano/SigningProcess/Client.hs
- plutus-pab/src/Cardano/Wallet/Client.hs
- plutus-pab/src/Cardano/Wallet/Server.hs
- plutus-pab/src/Plutus/PAB/App.hs
- plutus-pab/src/Plutus/PAB/Types.hs
- plutus-pab/src/Plutus/PAB/Webserver/Server.hs
- plutus-pab/src/Plutus/PAB/Webserver/WebSocket.hs
* Remove the `Error ClientError` effects from `AppBackend`
* Remove most of the `LogMsg` effects from `AppBackend`
* Now we only have one top-level `LogMsg` effect and one top-level `Error` effect
- Branch
- PR
> SCP-1920: Simplify `AppBackend`

- default.nix
- deployment/morph/configurations.nix
- deployment/morph/pab.nix
- marlowe-dashboard-client/default.nix
- marlowe-dashboard-client/package-lock.json
- marlowe-dashboard-client/package.json
- marlowe-dashboard-client/plutus-pab.yaml
- marlowe-dashboard-client/src/Contract/State.purs
- marlowe-dashboard-client/src/Main.purs
- marlowe-dashboard-client/src/MainFrame/Lenses.purs
- marlowe-dashboard-client/src/MainFrame/State.purs
- marlowe-dashboard-client/src/MainFrame/Types.purs
- marlowe-dashboard-client/src/MainFrame/View.purs
- marlowe-dashboard-client/src/WalletData/Lenses.purs
- marlowe-dashboard-client/src/WalletData/Types.purs
- marlowe-dashboard-client/src/WalletData/Validation.purs
- marlowe-dashboard-client/src/WalletData/View.purs
- marlowe-dashboard-client/webpack.config.js
Also set up placeholder for dealing with PAB messages
- Branch
- PR
> change marlowe-dash to use PAB backend and deploy to env

- example/cabal.project
> Add missing package to cabal.project

- plutus-metatheory/src/Type/CC.lagda.md
- plutus-metatheory/src/Type/CK.lagda.md
- plutus-metatheory/src/Type/ReductionC.lagda.md
- plutus-metatheory/src/Type/ReductionCI.lagda.md
- plutus-metatheory/src/Type/ReductionStack.lagda.md
properties of evaluation contexts
properties of the CC machine
properties of EC style reduction
- Branch
- PR
> SCP-1960 properties of ECs, EC style reduction and CC machine

- marlowe-dashboard-client/src/Template/Types.purs
- marlowe-playground-client/src/Examples/JS/Contracts.purs
- marlowe-playground-client/src/Marlowe/Linter.purs
- marlowe-playground-client/src/StaticData.purs
- marlowe-playground-server/app/PSGenerator.hs
- marlowe-playground-server/contracts/CouponBondGuaranteed.hs
- web-common-marlowe/src/Marlowe/Extended.purs
This PR fixes two bugs:
- Marlowe and Blockly version of Coupon Bond Guaranteed was not created by PSGenerator (SCP-1975)
- Rethink linting for `Pay` because linting was failing for the following contract (SCP-1957) and no wonder:
```haskell
When [Case (Deposit (Role "Seller") (Role "Buyer") (Token "" "") (ConstantParam "Price")) (When [Case (Choice (ChoiceId "Everything is alright" (Role "Buyer")) [Bound 0 0]) Close, Case (Choice (ChoiceId "Report problem" (Role "Buyer")) [Bound 1 1]) (Pay (Role "Seller") (Account (Role "Buyer")) (Token "" "") (ConstantParam "Price") (When [Case (Choice (ChoiceId "Confirm problem" (Role "Seller")) [Bound 1 1]) Close, Case (Choice (ChoiceId "Dispute problem" (Role "Seller")) [Bound 0 0]) (When [Case (Choice (ChoiceId "Dismiss claim" (Role "Arbiter")) …
```
> SCP-1975, SCP-1957, and move MetaData types to web-common-marlowe

- plutus-core/untyped-plutus-core-test/Evaluation/Machines/Budget/IdNat/0.plc.golden
- plutus-core/untyped-plutus-core-test/Evaluation/Machines/Budget/IdNat/3.plc.golden
- plutus-core/untyped-plutus-core-test/Evaluation/Machines/Budget/IdNat/6.plc.golden
- plutus-core/untyped-plutus-core-test/Evaluation/Machines/Budget/IdNat/9.plc.golden
- plutus-core/untyped-plutus-core-test/Evaluation/Machines/Budget/IfThenElse/0.plc.golden
- plutus-core/untyped-plutus-core-test/Evaluation/Machines/Budget/IfThenElse/1.plc.golden
- plutus-core/untyped-plutus-core-test/Evaluation/Machines/Budget/IfThenElse/2.plc.golden
- plutus-core/untyped-plutus-core-test/Evaluation/Machines/Budget/IfThenElse/3.plc.golden
- plutus-core/untyped-plutus-core-test/Evaluation/Machines/Budget/IfThenElse/4.plc.golden
Just fixing stuff in golden files, nothing to look at.
> [Bug] [Test] Fixed the ordering in golden files

- .gitignore
- notes/plutus-report/costing.tex
- notes/plutus-report/glossary.tex
- notes/plutus-report/plutus.tex
- notes/plutus-report/scripting.tex
I think this is where it should live in the end. It needs more detail in
a lot of places and cross-referencing, but the skeleton is there.
- Branch
- PR
> SCP-1962: First version of a costing section in the technical report

- marlowe-dashboard-client/src/Contract/Lenses.purs
- marlowe-dashboard-client/src/Contract/State.purs
- marlowe-dashboard-client/src/Contract/Types.purs
- marlowe-dashboard-client/src/Contract/View.purs
- marlowe-dashboard-client/src/Css.purs
- marlowe-dashboard-client/src/Icons.purs
- marlowe-dashboard-client/src/Pickup/State.purs
- marlowe-dashboard-client/src/Pickup/Types.purs
- marlowe-dashboard-client/src/Pickup/View.purs
- marlowe-dashboard-client/src/Play/State.purs
- marlowe-dashboard-client/src/Play/View.purs
- marlowe-dashboard-client/src/Template/View.purs
- marlowe-dashboard-client/src/WalletData/View.purs
- marlowe-dashboard-client/static/css/main.css
- marlowe-dashboard-client/tailwind.config.js
Moving things in the direction of the visual designs.
> Making things start to look more like the visual design.

- notes/plutus-report/applications.tex
- notes/plutus-report/glossary.tex
- notes/plutus-report/plutus.tex
> Plutus report: Describe plutus app concurrency

- shell.nix
This makes lorri watch literally everything.
- Branch
- PR
> Avoid references to ./. in shell.nix

- marlowe-playground-client/src/MainFrame/State.purs
- marlowe-playground-client/src/Marlowe/Gists.purs
if a newgist has an empty file then the request to github fails
- Branch
- PR
> SCP-2006 - part 1 (new gists)

- nix/pkgs/haskell/materialized-unix/.plan.nix/plutus-ledger-api.nix
- plutus-ledger-api/plutus-ledger-api.cabal
- plutus-ledger-api/src/Plutus/V1/Ledger/Api.hs
- plutus-ledger-api/src/Plutus/V1/Ledger/Examples.hs
For the ledger folks to use for testing.
- Branch
- PR
> SCP-1961: Add some trivial scripts to the ledger API module

- plutus-ledger-api/src/Plutus/V1/Ledger/Api.hs
It's just an arbitrary string to be used in the "envelopes" the node API
uses.
- Branch
- PR
> SCP-1878: Add an envelope type for Plutus scripts

- notes/plutus-report/applications.tex
- notes/plutus-report/glossary.tex
- notes/plutus-report/plutus.bib
* Explain a bit about state machines
* Update glossary
- Branch
- PR
> Add some text on app design

- deployment/morph/playgrounds.nix
Tutorials (for both Marlowe and Plutus) were removed from S3 but not added to playground server.
This PR does that and it also increases the request rate limits and sets them to be more generous for the static files.
Deployed to https://alpha.marlowe.iohkdev.io/
and to https://alpha.plutus.iohkdev.io/
- Branch
- PR
> SCP-2013 - Add tutorials to playground deployment

- infrastructure/modules/user/README.md
Add info about editing aws configuration files
- Branch
- PR
> Update documentation for aws user creation

- deployment/morph/playgrounds.nix
Request rate limit was causing some images to not be loaded. This PR increases the request rate limit.
- Branch
- PR
- ~Reviewer requested~ Very minor change
- ~Someone approved it~ Very minor change
> Increase request rate limit and memory for static pages

- marlowe-dashboard-client/src/Contract/Lenses.purs
- marlowe-dashboard-client/src/Contract/State.purs
- marlowe-dashboard-client/src/Contract/Types.purs
- marlowe-dashboard-client/src/Contract/View.purs
- marlowe-dashboard-client/src/ContractHome/Lenses.purs
- marlowe-dashboard-client/src/ContractHome/State.purs
- marlowe-dashboard-client/src/ContractHome/Types.purs
- marlowe-dashboard-client/src/ContractHome/View.purs
- marlowe-dashboard-client/src/Css.purs
- marlowe-dashboard-client/src/Icons.purs
- marlowe-dashboard-client/src/Play/Lenses.purs
- marlowe-dashboard-client/src/Play/State.purs
- marlowe-dashboard-client/src/Play/Types.purs
- marlowe-dashboard-client/src/Play/View.purs
- marlowe-dashboard-client/static/css/main.css
- marlowe-dashboard-client/tailwind.config.js
- web-common-marlowe/src/Marlowe/Extended.purs
- web-common/src/Halogen/Extra.purs
This PR is a first part on implementing the running of contracts. It is part of task SCP-1862. The changes include:
* Moved single contract in `Contract` to an array of contracts in `ContractHome`
* Created the list of contract view, with running and completed clickable but not filtering.
* Created the basis for the running contract card.
- Branch
- PR
> Marlowe Dashboard Client: Implement running contract part 1

- marlowe-dashboard-client/src/Contract/View.purs
- marlowe-dashboard-client/src/ContractHome/View.purs
- marlowe-dashboard-client/src/Css.purs
- marlowe-dashboard-client/src/Icons.purs
- marlowe-dashboard-client/src/Pickup/View.purs
- marlowe-dashboard-client/src/Play/State.purs
- marlowe-dashboard-client/src/Play/Types.purs
- marlowe-dashboard-client/src/Play/View.purs
- marlowe-dashboard-client/src/Template/Lenses.purs
- marlowe-dashboard-client/src/Template/State.purs
- marlowe-dashboard-client/src/Template/Types.purs
- marlowe-dashboard-client/src/Template/View.purs
- marlowe-dashboard-client/src/WalletData/View.purs
- marlowe-dashboard-client/static/css/main.css
- marlowe-dashboard-client/static/index.html
- marlowe-dashboard-client/tailwind.config.js
This PR starts to make the contract setup look more like the designs. Work in progress, the only reason I'm submitting a PR now is because I have to stop for the day and Hernan will still be working - so I want him to see (and potentially merge) what I've been doing so that we can avoid merge problems later.
> Redo contract setup part 1

- marlowe-dashboard-client/src/Css.purs
- marlowe-dashboard-client/src/Icons.purs
- marlowe-dashboard-client/src/MainFrame/State.purs
- marlowe-dashboard-client/src/Pickup/View.purs
- marlowe-dashboard-client/src/Play/State.purs
- marlowe-dashboard-client/src/Play/Types.purs
- marlowe-dashboard-client/src/Play/View.purs
- marlowe-dashboard-client/src/Template/Lenses.purs
- marlowe-dashboard-client/src/Template/State.purs
- marlowe-dashboard-client/src/Template/Types.purs
- marlowe-dashboard-client/src/Template/Validation.purs
- marlowe-dashboard-client/src/Template/View.purs
- marlowe-dashboard-client/src/WalletData/View.purs
- marlowe-dashboard-client/static/css/main.css
- marlowe-dashboard-client/tailwind.config.js
More work in progress. The only reason for stopping here is it's the end of the day (for me), and @hrajchert  might find it easier to merge this before carrying on with stuff his end. Up to you Hernán...
> Improving contract setup (part 2 of 3).

- plutus-contract/src/Wallet/Emulator/Chain.hs
* Log tx validation failures on the WARN level to make them easier to find.
- Branch
- PR
> Log tx validation failures on WARN

- doc/tutorials/plutus-tx.rst
Just noticed a simple typo while reading the docs.
- Branch
- PR
> small typo

- marlowe-dashboard-client/src/Contract/Lenses.purs
- marlowe-dashboard-client/src/Contract/State.purs
- marlowe-dashboard-client/src/Contract/Types.purs
- marlowe-dashboard-client/src/Contract/View.purs
- marlowe-dashboard-client/src/ContractHome/State.purs
- marlowe-dashboard-client/src/Marlowe/Execution.purs
- marlowe-dashboard-client/src/Play/State.purs
- marlowe-dashboard-client/src/Play/View.purs
- web-common-marlowe/src/Marlowe/Extended.purs
- web-common-marlowe/src/Marlowe/Extended/Template.purs
- web-common-marlowe/src/Marlowe/Semantics.purs
- web-common/src/Data/Set/Extra.purs
- web-common/src/Data/String/Extra.purs
This PR continues the implementation of running a contract. It adds the layout for the basic actions (close, choice and deposit) with a logic of expanding the actions that could be taken by all participants and only enabling the ones that are available to the currently logged role.
it also implements the layout for the Balances tab
- Branch
- PR
> Marlowe Dashboard Client - Implement running contract part2

- marlowe-dashboard-client/package-lock.json
- marlowe-dashboard-client/package.json
- marlowe-dashboard-client/src/Contract/View.purs
- marlowe-dashboard-client/src/ContractHome/View.purs
- marlowe-dashboard-client/src/Css.purs
- marlowe-dashboard-client/src/Icons.purs
- marlowe-dashboard-client/src/Pickup/View.purs
- marlowe-dashboard-client/src/Play/View.purs
- marlowe-dashboard-client/src/Template/View.purs
- marlowe-dashboard-client/src/WalletData/View.purs
- marlowe-dashboard-client/tailwind.config.js
This PR fixes the layout of different cards and add some more styles 
- Branch
- PR
> Marlowe Dashboard Client: Fix card styles

- marlowe/src/Language/Marlowe/Semantics.hs
- plutus-ledger-api/src/Plutus/V1/Ledger/Value.hs
- plutus-ledger/src/Ledger/Generators.hs
- plutus-use-cases/test/Spec/crowdfundingEmulatorTestOutput.txt
> SCP-2037: Add support for non-UTF-8 token names.

- doc/tutorials/index.rst
- doc/tutorials/troubleshooting.rst
> SCP-2033: Add troubleshooting page to docs

- plutus-pab/plutus-pab.yaml
- plutus-pab/src/Cardano/Node/Server.hs
- plutus-pab/src/Cardano/Wallet/Mock.hs
- plutus-pab/src/Cardano/Wallet/Server.hs
> SCP-1888 Per-session funds 2

- nix/pkgs/haskell/default.nix
I removed the base cause of this some time ago.
- Branch
- PR
> Remove a nix workaround

- plutus-core/untyped-plutus-core/src/UntypedPlutusCore/Evaluation/Machine/Cek.hs
- plutus-core/untyped-plutus-core/src/UntypedPlutusCore/Evaluation/Machine/Cek/ExBudgetMode.hs
- plutus-core/untyped-plutus-core/src/UntypedPlutusCore/Evaluation/Machine/Cek/Internal.hs
> [Evaluation] Fixed the performance issue introduced by the handle pattern PR

- plutus-ledger-api/src/Plutus/V1/Ledger/Value.hs
- plutus-ledger/test/Spec.hs
Well, this looks more and more like a bad idea. But I don't have a better one yet. (Except for changing the TokenName datatype, which seems too big of a rewrite.)
- Branch
- PR
> Support utf-8 tokennames starting with \NUL

- plutus-ledger/src/Ledger/Typed/Scripts.hs
- plutus-playground-server/usecases/Crowdfunding.hs
- plutus-playground-server/usecases/Vesting.hs
- plutus-use-cases/src/Plutus/Contracts/Crowdfunding.hs
- plutus-use-cases/src/Plutus/Contracts/Escrow.hs
- plutus-use-cases/src/Plutus/Contracts/MultiSig.hs
- plutus-use-cases/src/Plutus/Contracts/PubKey.hs
- plutus-use-cases/src/Plutus/Contracts/TokenAccount.hs
- plutus-use-cases/src/Plutus/Contracts/Vesting.hs
- plutus-use-cases/test/Spec/crowdfundingEmulatorTestOutput.txt
- plutus-use-cases/test/Spec/renderCrowdfunding.txt
- plutus-use-cases/test/Spec/renderVesting.txt
> Simplify making parameterised script instances

- plutus-pab/src/Cardano/Protocol/Socket/Client.hs
- plutus-pab/src/Cardano/Protocol/Socket/Server.hs
* Use nullTrace instead of stdout
- Branch
- PR
> SCP-2067: Reduce node client log output

- marlowe-dashboard-client/src/ContractHome/State.purs
- web-common-marlowe/src/Marlowe/Market/Contract1.purs
- web-common-marlowe/src/Marlowe/Market/Contract2.purs
- web-common-marlowe/src/Marlowe/Market/Contract3.purs
- web-common-marlowe/src/Marlowe/Market/Contract4.purs
- web-common-marlowe/src/Marlowe/Market/Contract5.purs
This updates the web-common-marlowe Market with the new contract templates by @palas available here: https://gist.github.com/palas.
> Updating Marlowe market contract templates.

- plutus-core-spec/Makefile
- plutus-core-spec/figures/Builtins.tex
- plutus-core-spec/figures/LexicalGrammar.tex
- plutus-core-spec/figures/Makefile
- plutus-core-spec/figures/TypeErasure.tex
- plutus-core-spec/figures/TypeSynthesis-Algorithmic.tex
- plutus-core-spec/figures/TypedCekMachine.tex
- plutus-core-spec/figures/TypedCkMachine.tex
- plutus-core-spec/figures/TypedGrammar.tex
- plutus-core-spec/figures/UntypedCekMachine.tex
- plutus-core-spec/figures/UntypedCkMachine.tex
- plutus-core-spec/figures/UntypedGrammar.tex
- plutus-core-spec/plutus-core-specification.tex
A stopgap version of the PLC specification to get it at least approximately up to date.  This is another attempt at https://github.com/input-output-hk/plutus/pull/2927 (abandoned because of a git disaster), so see the comments there for more information.
- Branch
- PR
> Another attempt at updating the PLC specification (SCP-601)

- marlowe-dashboard-client/src/Contract/State.purs
- marlowe-dashboard-client/src/Contract/View.purs
- marlowe-dashboard-client/src/ContractHome/State.purs
- marlowe-dashboard-client/src/ContractHome/Types.purs
- marlowe-dashboard-client/src/Marlowe/Execution.purs
- marlowe-dashboard-client/src/Play/State.purs
This PR implements the balance cards in the contracts
Changes are available in this URL https://hernan.marlowe-dash.iohkdev.io/ 
- Branch
- PR
> scp-2089: Marlowe Dashboard Client: implement balances in contracts

- marlowe/marlowe.cabal
- marlowe/pab/Main.hs
- nix/pkgs/haskell/materialized-unix/.plan.nix/marlowe.nix
Add a `marlowe-pab` executable that has the marlowe contract built in.
> SCP-2046: Marlowe-pab 

- marlowe/src/Language/Marlowe/Client.hs
- marlowe/src/Language/Marlowe/Semantics.hs
- marlowe/test/Spec/Marlowe/Marlowe.hs
> SCP-2024 Marlowe Companion Contract

- README.adoc
> Make the cache warning more aggressive

- README.adoc
> Move location of note about `~/.config/nix/nix.conf`.

- deployment/terraform/locals.tf
Add tobias ssh keys to alpha environment
- Branch
- PR
> terraform: add tobias to alpha

- default.nix
- deployment/morph/machines/marlowe-dash.nix
- deployment/morph/network.nix
- marlowe/companion/Main.hs
- marlowe/marlowe.cabal
- nix/pkgs/haskell/materialized-unix/.plan.nix/marlowe.nix
- nix/tests/default.nix
- nix/tests/vm-tests/all.nix
- nix/tests/vm.nix
> Marlowe Companion contract app

- marlowe-dashboard-client/src/Bridge.purs
- marlowe-dashboard-client/src/Capability/Wallet.purs
- marlowe-dashboard-client/src/MainFrame/State.purs
- marlowe-dashboard-client/src/WalletData/Types.purs
- plutus-pab/app/PSGenerator.hs
- plutus-pab/src/Cardano/Wallet/API.hs
- plutus-pab/src/Cardano/Wallet/Client.hs
- plutus-pab/src/Cardano/Wallet/Mock.hs
- plutus-pab/src/Cardano/Wallet/Server.hs
- plutus-pab/src/Cardano/Wallet/Types.hs
- plutus-pab/src/Plutus/PAB/Simulator.hs
- plutus-pab/src/Plutus/PAB/Webserver/Handler.hs
- plutus-pab/src/Plutus/PAB/Webserver/Server.hs
- plutus-pab/src/Plutus/PAB/Webserver/Types.hs
* We need to return `Wallet` and `PubKeyHash` in a couple of places
- Branch
- PR
> SCP-2015: Some API tweaks

- default.nix
- marlowe-dashboard-client/default.nix
- marlowe-dashboard-client/src/Capability/ContractExe.js
> Integrating the wallet companion contract with the dashboard frontend.

- plutus-core/README.md
For nix build instruction, update the installable name.
> update nix installable name

- marlowe-playground-server/marlowe-playground-server.cabal
- marlowe-playground-server/src/Marlowe/Mermaid.hs
- nix/pkgs/haskell/materialized-unix/.plan.nix/marlowe-playground-server.nix
This is a first pass at converting a Marlowe contract into a graph that can be displayed nicely by Mermaid: <https://mermaid-js.github.io/mermaid/#/>.
The context for this is just that I wanted to see the contracts as a flow chart, and then I figured it was easy to hack this conversion together.
I'm not totally sure who is the best person to review this ( still waiting to get access to the relevant slack channels :) ), so forgive me @michaelpj for assigning you; if you can please point me at some other people that'd be great :)
Here's what some of the contracts look like:
Swap contract:
Escrow contract:
Coupon Bond Guaranteed contract:
Questions to be answered before merging:
- Do we want this code at all?
- Where does this code belong? I just put it where it was most convenient for me.
- …
> Export Contract as Mermaid graph

- plutus-pab/src/Plutus/PAB/ContractCLI.hs
- plutus-pab/src/Plutus/PAB/Effects/Contract/ContractExe.hs
- plutus-pab/test/Plutus/PAB/Events/ContractSpec.hs
* We have types that help us get the encoding right, we should actually use them.
- Branch
- PR
> SCP-2107: JSON encoding bug

- marlowe-dashboard-client/src/Contract/Types.purs
- marlowe-dashboard-client/src/ContractHome/Lenses.purs
- marlowe-dashboard-client/src/ContractHome/State.purs
- marlowe-dashboard-client/src/ContractHome/Types.purs
- marlowe-dashboard-client/src/ContractHome/View.purs
- marlowe-dashboard-client/src/Play/Lenses.purs
- marlowe-dashboard-client/src/Play/State.purs
- marlowe-dashboard-client/src/Play/View.purs
- marlowe-dashboard-client/tailwind.config.js
This PR implements the ContractHome grid layout and it filters the running from the history.
- Branch
- PR
> SCP-2090: Marlowe Dashboard Client - Implement contract home running/history

- plutus-core/plutus-core/examples/PlutusCore/Examples/Data/TreeForest.hs
- plutus-pab/src/Cardano/Protocol/Socket/Type.hs
- plutus-tx-plugin/test/Plugin/Basic/Spec.hs
- plutus-tx-plugin/test/Plugin/Data/Spec.hs
- plutus-tx-plugin/test/Plugin/Errors/Spec.hs
- plutus-tx-plugin/test/Plugin/Functions/Spec.hs
- plutus-tx-plugin/test/Plugin/Laziness/Spec.hs
- plutus-tx-plugin/test/Plugin/Primitives/Spec.hs
- plutus-tx-plugin/test/Plugin/Typeclasses/Spec.hs
- plutus-tx-plugin/test/StdLib/Spec.hs
- plutus-tx-plugin/test/TH/Spec.hs
- plutus-use-cases/src/Plutus/Contracts/Crowdfunding.hs
- plutus-use-cases/src/Plutus/Contracts/Escrow.hs
- plutus-use-cases/src/Plutus/Contracts/Future.hs
- plutus-use-cases/src/Plutus/Contracts/GameStateMachine.hs
- plutus-use-cases/src/Plutus/Contracts/PingPong.hs
- plutus-use-cases/test/Spec/MultiSigStateMachine.hs
> change deprecated OPTIONS pragma to OPTIONS_GHC

- marlowe-dashboard-client/src/Contract/State.purs
- marlowe-dashboard-client/src/ContractHome/State.purs
- marlowe-dashboard-client/src/MainFrame/State.purs
- marlowe-dashboard-client/src/Pickup/State.purs
- marlowe-dashboard-client/src/Play/State.purs
- marlowe-dashboard-client/src/Template/State.purs
This PR replaces the several "fake" submodules with "real" ones (whose `handleAction` functions range over the substate). There should be no functional changes, but this makes the code nicer.
> Making proper submodules.

- nix/devcontainer/devcontainer.nix
Just adds `jq` and `curl` to the devcontainer image; these are useful for interacting with the PAB API.
- Branch
- PR
> add jq and curl to devcontainer

- nix/modules/pab.nix
- plutus-pab-client/config.nix
- plutus-pab/plutus-pab.yaml.sample
- plutus-pab/src/Cardano/ChainIndex/Server.hs
- plutus-pab/src/Cardano/Node/RandomTx.hs
- plutus-pab/src/Cardano/Node/Server.hs
- plutus-pab/src/Cardano/Node/Types.hs
- plutus-pab/src/Cardano/Protocol/Socket/Client.hs
- plutus-pab/src/Cardano/Protocol/Socket/Server.hs
- plutus-pab/tx-inject/config.yaml
* Remove blocks older than K from the server's broadcast channel.
* Retry connecting the client if anything fails.
- Branch
- PR
> Limit the buffer of the node server to K blocks.

- deployment/terraform/locals.tf
Update config to use their actual keys
- Branch
- PR
- ~[ ] Reviewer requested~
- ~[ ] Someone approved it~
> Update keys for Bozhidar and Dimitar

- nix/pkgs/haskell/materialized-unix/.plan.nix/plutus-pab.nix
- plutus-pab/plutus-pab.cabal
- plutus-pab/plutus-pab.yaml
- plutus-pab/plutus-pab.yaml.sample
- plutus-pab/src/Plutus/PAB/App.hs
- plutus-pab/src/Plutus/PAB/Core.hs
- plutus-pab/src/Plutus/PAB/Core/ContractInstance/STM.hs
- plutus-pab/src/Plutus/PAB/Simulator.hs
- plutus-pab/src/Plutus/PAB/Timeout.hs
- plutus-pab/src/Plutus/PAB/Types.hs
> SCP-2134: Optional timeout for endpoint calls

- plutus-contract/src/Plutus/Trace/Emulator.hs
- plutus-contract/src/Wallet/Emulator/Wallet.hs
- plutus-pab/src/Plutus/PAB/Simulator.hs
Adds a little helper to print the balances of the simulator; I'm using this in the plutus-starter PAB implementation:
```
main :: IO ()
main = void $ Simulator.runSimulationWith handlers $ do
...
-- Pressing enter results in the balances being printed
void $ liftIO getLine
Simulator.logString @(Builtin StarterContracts) "Balances at the end of the simulation"
b <- Simulator.currentBalances
Simulator.logBalances @(Builtin StarterContracts) b
shutdown
```
to show the balances when the pab quits.
@j-mueller let me know if things should be moved around/etc. I ended up slightly duplicating the `printBalances ...` function; but I couldn't quite see how to make that cleaner without doing a bit too much reshuffling; but happy for hints!
- Branch
- PR
> shuffle around code related to computing wallet balances on the chain

- marlowe-playground-client/src/Language/Javascript/MarloweJS.ts
The JS program:
```javascript
return Let("valueId", Constant("invalid number"), Close);
```
Used to produce the following error:
```
There was an error when parsing the resulting JSON:
(NonEmptyList (NonEmpty (TypeMismatch "String" "Object") ((TypeMismatch "object" "undefined") : (TypeMismatch "object" "undefined") : (TypeMismatch "Boolean" "Undefined") : (TypeMismatch "Boolean" "Undefined") : (TypeMismatch "object" "undefined") : (TypeMismatch "object" "undefined") : (TypeMismatch "object" "undefined") : (TypeMismatch "object" "undefined") : (TypeMismatch "object" "undefined") : (TypeMismatch "object" "undefined") : (TypeMismatch "object" "undefined") : (TypeMismatch "object" "undefined") : (TypeMismatch "object" "undefined") : (TypeMismatch "array" "Undefined") : (ForeignError "Not …
```
> SCP-2047 - Capture malformed numbers in JS API and throw exception

- nix/patches/haskell-language-server-dynamic.patch
- nix/pkgs/haskell/extra.nix
> Patch HLS so it doesn't crash on macOS

- plutus-metatheory/src/Type/CC.lagda.md
- plutus-metatheory/src/Type/CK.lagda.md
- plutus-metatheory/src/Type/ReductionC.lagda.md
> SCP-1972 CK => CC (types)

- plutus-core/untyped-plutus-core/src/UntypedPlutusCore/Evaluation/Machine/Cek/Internal.hs
> Fix comment in the CEK machine

- plutus-metatheory/src/Type/CC.lagda.md
- plutus-metatheory/src/Type/CK.lagda.md
- plutus-metatheory/src/Type/ReductionC.lagda.md
> SCP-1971 CC => reduction

- deployment/terraform/locals.tf
> Add ci-deployer ssh-keys to terraform configuration allowing it to perform deployments.

- marlowe-dashboard-client/src/API/Contract.purs
- marlowe-dashboard-client/src/Capability/Contract.purs
- plutus-pab/app/PSGenerator.hs
- plutus-pab/src/Plutus/PAB/Webserver/API.hs
- plutus-pab/src/Plutus/PAB/Webserver/Handler.hs
- plutus-pab/src/Plutus/PAB/Webserver/Types.hs
> SCP-2157: Include contract def. in instance status

- .gitignore
- marlowe-dashboard-client/src/Contract/Lenses.purs
- marlowe-dashboard-client/src/Contract/State.purs
- marlowe-dashboard-client/src/Contract/Types.purs
- marlowe-dashboard-client/src/Contract/View.purs
- marlowe-dashboard-client/src/ContractHome/State.purs
- marlowe-dashboard-client/src/ContractHome/Types.purs
- marlowe-dashboard-client/src/Env.purs
- marlowe-dashboard-client/src/Main.purs
- marlowe-dashboard-client/src/Play/State.purs
- marlowe-dashboard-client/static/css/main.css
- marlowe-dashboard-client/tailwind.config.js
- web-common/src/Halogen/ElementVisible.purs
- web-common/src/Web/DOM/ElementExtra.js
- web-common/src/Web/DOM/ElementExtra.purs
- web-common/src/Web/DOM/IntersectionObserver.js
- web-common/src/Web/DOM/IntersectionObserver.purs
This PR modifies the step carousel scrolling to automatically activate the step in the center.
Can be tested on https://hernan.marlowe-dash.iohkdev.io/ 
- Branch
- PR
> scp-2093: Marlowe Dashboard Client: Improve step carrousel

- nix/pkgs/haskell/materialized-unix/.plan.nix/plutus-pab.nix
- nix/pkgs/haskell/materialized-unix/.plan.nix/plutus-tx.nix
- nix/pkgs/haskell/materialized-unix/.plan.nix/plutus-use-cases.nix
- plutus-ledger-api/src/Plutus/V1/Ledger/Contexts.hs
- plutus-ledger-api/src/Plutus/V1/Ledger/Value.hs
- plutus-pab/plutus-pab.cabal
- plutus-pab/src/Plutus/PAB/Effects/ContractTest/Uniswap.hs
- plutus-pab/uniswap/Main.hs
- plutus-tx/plutus-tx.cabal
- plutus-tx/src/PlutusTx/Sqrt.hs
- plutus-tx/test/Spec.hs
- plutus-use-cases/plutus-use-cases.cabal
- plutus-use-cases/src/Plutus/Contracts/Uniswap.hs
This is a port of the Uniswap code from @brunjlar 
- https://github.com/input-output-hk/plutus/blob/brunjlar/uniswap-pab/plutus-use-cases/src/Plutus/Contracts/Uniswap.hs
- https://github.com/input-output-hk/plutus/blob/brunjlar/uniswap-pab/plutus-pab/uniswap/Main.hs
I made a few changes; and there is one question I have @j-mueller , specifically [in this line](https://github.com/input-output-hk/plutus/pull/3047/files#diff-9bfc85d63477fbeee08a1338452f07e52dd2631331a8d2ff22a27c703484775fR113) I wasn't sure what to put for the Uniswap contract that takes a parameter; so I just left the entire list empty. There's probably something better to do?
Otherwise, let me know any other feedback!
Maybe the main note is that there are no tests. Because I think testing this might be a bit complicated, I …
> SCP-2106 - port over uniswap

- deployment/README.md
Update README.md in deployment folder to add an explanation on how to create a local profile for aws client.
- Branch
- PR
> Add explanation on how to create a local profile for aws client

- deployment/envs.nix
- deployment/terraform/locals.tf
Add a production environment for aws deployments
- Branch
- PR
> Add a `production` environment

- nix/modules/pab.nix
Drop the pab database file form the service config during pab-init.
There seems to be some race-condition or other bug related to eventful
which causes pab to crash during startup. This can be circumvented by
dropping the sqlite database completely before migration/starting any
services.
**NOTE**: THIS IS NOT A FIX, THIS IS A WORKAROUND. Dropping the database
masks the actual problem which needs to be investigated separately.
----
- Branch
- PR
> PAB: Drop database on initialization

- doc/plutus/tutorials/basic-apps.rst
I believe this is a small typo, as it references the code above.  I noticed it while following along, so I figured I'd open a PR to fix it.
- Branch
- PR
> Fixes a small typo

- plutus-pab/src/Plutus/PAB/Core.hs
- plutus-pab/src/Plutus/PAB/Core/ContractInstance.hs
- plutus-pab/src/Plutus/PAB/Core/ContractInstance/STM.hs
- plutus-pab/src/Plutus/PAB/Simulator.hs
- plutus-pab/src/Plutus/PAB/Types.hs
- plutus-pab/src/Plutus/PAB/Webserver/API.hs
- plutus-pab/src/Plutus/PAB/Webserver/Handler.hs
- plutus-pab/test/Plutus/PAB/CoreSpec.hs
> SCP-2204: Add an HTTP route for stopping instances

- marlowe-dashboard-client/src/Contract/Lenses.purs
- marlowe-dashboard-client/src/Contract/State.purs
- marlowe-dashboard-client/src/Contract/Types.purs
- marlowe-dashboard-client/src/Contract/View.purs
- marlowe-dashboard-client/src/ContractHome/State.purs
- marlowe-dashboard-client/src/MainFrame/State.purs
- marlowe-dashboard-client/src/Play/State.purs
- marlowe-dashboard-client/src/Play/View.purs
This feels a bit ugly, but it works. To make it less ugly we probably need to rethink some of the types (notably `MarloweParams`) and add some lenses for the `Marlowe.PAB` things.
> SCP-2166: Disabling god mode and determining roles from wallet assets

- CONTRIBUTING.adoc
- fix formatting for unordered lists,
- add note about --force-with-lease
> Fix minor issues in CONTRIBUTING.adoc

- marlowe-playground-client/src/Blockly/Internal.js
This PR disables the "Disable Block" functionality of Blockly, since we are not taking it into consideration.
Resolves #2901
- Branch
- PR
> SCP-2065 - Disable disabling blocks in Blockly

- plutus-pab/src/Plutus/PAB/Core.hs
- plutus-pab/src/Plutus/PAB/Simulator.hs
- plutus-pab/test/Plutus/PAB/CoreSpec.hs
Making the tests a bit more reliable by waiting longer
- Branch
- PR
> SCP-2155: PAB tests

- marlowe-dashboard-client/src/Play/State.purs
This PR enables the creation of contracts in the client. It is intended to help us get further with testing while the problems with running contracts in the PAB are sorted out.
> Temporary: enable contracts to be simulated on the client.

- plutus-pab/src/Cardano/Wallet/Mock.hs
- plutus-pab/src/Plutus/PAB/Simulator.hs
- plutus-pab/src/Plutus/PAB/Webserver/WebSocket.hs
- plutus-pab/test/Plutus/PAB/CoreSpec.hs
- plutus-tx/src/PlutusTx/AssocMap.hs
- plutus-use-cases/src/Plutus/Contracts/Currency.hs
> PAB: Add test, fix wallet -> pubkeyhash conversion

- marlowe-dashboard-client/src/Contract/View.purs
- marlowe-dashboard-client/src/Css.purs
- marlowe-dashboard-client/src/MainFrame/State.purs
- marlowe-dashboard-client/src/Play/State.purs
- marlowe-dashboard-client/src/Toast/Types.purs
This commit was mainly going to be improving the error messages, but while I was at it I tweaked a few other small things. These should be self-explanatory from the diff.
> Improving error messages and fixing a few miscellaneous things.

- plutus-ledger/src/Ledger/Constraints/OffChain.hs
> Make mustIncludeDatum a default constraint (fix #3119)

- plutus-playground-client/README.md
- plutus-playground-server/README.md
> Remove mentions of plutus-playground.server-invoker (fix #2988)

- plutus-pab-client/pab-demo-scripts.nix
> Disable pab-demo-scripts on darwin

- plutus-ledger/src/Ledger/Index.hs
> SCP-2159: Include trace logs in result of successful script evaluation

- marlowe-dashboard-client/src/Contract/State.purs
- marlowe-dashboard-client/src/Contract/Types.purs
- marlowe-dashboard-client/src/MainFrame/Lenses.purs
- marlowe-dashboard-client/src/MainFrame/State.purs
- marlowe-dashboard-client/src/MainFrame/Types.purs
- marlowe-dashboard-client/src/MainFrame/View.purs
- marlowe-dashboard-client/src/Play/Lenses.purs
- marlowe-dashboard-client/src/Play/State.purs
- marlowe-dashboard-client/src/Play/Types.purs
- marlowe-dashboard-client/src/Play/View.purs
This will hopefully solve the problem observed in deployment, with the server clock potentially being out of sync with the user's system clock.
> Using PAB as single source of truth for current slot.

- plutus-pab/src/Cardano/Chain.hs
- plutus-pab/src/Cardano/Node/RandomTx.hs
- plutus-pab/src/Cardano/Node/Server.hs
- plutus-pab/src/Cardano/Node/Types.hs
- plutus-pab/src/Cardano/Protocol/Socket/Server.hs
- plutus-pab/src/Cardano/Wallet/Mock.hs
* The mock node should update its own index (ie. UTXO set) after each block
* Add proper logging to the mock node. We can now see transaction validation events in the logs.
- Branch
- PR
> Fix a bug in the mock node

- marlowe-playground-client/test/Marlowe/LintTests.purs
This PR adds tests that ensure our examples don't have linter warnings
- Branch
- PR
> SCP-1981 - Create test that ensures example contracts don't have linter warnings

- plutus-pab/src/Cardano/Node/Server.hs
I am now pushing the new blocks from the interpreter and we don't need to update the server state in this convoluted way, anymore.
- Branch
- PR
> Blocks are pushed in the interpreter now.

- plutus-pab-client/src/View/Pretty.purs
- plutus-pab/src/Plutus/PAB/Db/Eventful/Command.hs
- plutus-pab/src/Plutus/PAB/Db/Eventful/ContractStore.hs
- plutus-pab/src/Plutus/PAB/Db/Eventful/Query.hs
- plutus-pab/src/Plutus/PAB/Effects/Contract.hs
- plutus-pab/src/Plutus/PAB/Events.hs
- plutus-pab/src/Plutus/PAB/Simulator.hs
- plutus-pab/src/Plutus/PAB/Types.hs
* Improve the eventful schema & queries a little bit
* Add events for starting and stopping of instances
This change does not make anything faster (saving this for the next PR :) )
- Branch
- PR
> SCP-2154: Improve DB schema

- plutus-core/cost-model/CostModel.md
This is just a small update to some markdown documentation.  This will be superseded by SCP-1895 in the near future.
- Branch
- PR
> SCP-2077: update CostModel.md

- plutus-tx-plugin/test/Lift/bytestring.plc.golden
- plutus-tx-plugin/test/Lift/list.plc.golden
- plutus-tx-plugin/test/Lift/mono.plc.golden
- plutus-tx-plugin/test/Lift/nested.plc.golden
- plutus-tx-plugin/test/Lift/poly.plc.golden
- plutus-tx-plugin/test/Lift/record.plc.golden
- plutus-tx-plugin/test/Lift/syn.plc.golden
- plutus-tx-plugin/test/Lift/tuple.plc.golden
- plutus-tx/src/PlutusTx/Lift.hs
- plutus-use-cases/test/Spec/crowdfundingEmulatorTestOutput.txt
- plutus-use-cases/test/Spec/renderCrowdfunding.txt
- plutus-use-cases/test/Spec/renderVesting.txt
> Remember to run the UPLC simplifier when lifting

- deployment/README.md
Add first part of documentation providing a basic overview and info on
available commands provided by deployment/shell.nix
Rendered: [deployment/README.md](https://github.com/input-output-hk/plutus/tree/deployment-docs/deployment)
----
- Branch
- PR
> deployment/README.md: Add overview and basic usage

- nix/modules/pab.nix
- plutus-pab-client/pab-demo-scripts.nix
- plutus-pab/app/Cli.hs
- plutus-pab/app/Command.hs
- plutus-pab/app/CommandParser.hs
- plutus-pab/app/Main.hs
- plutus-pab/src/Plutus/PAB/Types.hs
* Some of the `pab` commands don't need the full config.
- Branch
- PR
> SCP-2202: pab migrate doesn't require config.yaml

- plutus-pab/app/Cli.hs
- plutus-pab/app/CommandParser.hs
- plutus-pab/app/Main.hs
- plutus-pab/src/Plutus/PAB/App.hs
- plutus-pab/src/Plutus/PAB/Db/Eventful.hs
- plutus-pab/src/Plutus/PAB/Effects/EventLog.hs
* Add a `-m` flag for the memory-backed eventful store
* If the flag is enabled then no events will be written to / read from the sqlite file
- Branch
- PR
> SCP-2245: Optional memory-backed eventful store

- .buildkite/pipeline.yml
Trying to coax buildkite to build the tag. The "branches" field didn't seem to work for tags, so maybe this one does.
- Branch
- PR
> try conditional instead of branches match

- .buildkite/pipeline.yml
is the if statement didn't seem to fire - https://buildkite.com/input-output-hk/plutus/builds/122
> use 'branches' instead of 'if statement'

- plutus-ledger-api/src/Plutus/V1/Ledger/Contexts.hs
- plutus-ledger/src/Ledger/Index.hs
- plutus-use-cases/bench/Bench.hs
- plutus-use-cases/test/Spec/crowdfunding.pir
- plutus-use-cases/test/Spec/crowdfundingEmulatorTestOutput.txt
- plutus-use-cases/test/Spec/future.pir
- plutus-use-cases/test/Spec/gameStateMachine.pir
- plutus-use-cases/test/Spec/governance.pir
- plutus-use-cases/test/Spec/multisigStateMachine.pir
- plutus-use-cases/test/Spec/renderCrowdfunding.txt
- plutus-use-cases/test/Spec/renderGuess.txt
- plutus-use-cases/test/Spec/renderVesting.txt
- plutus-use-cases/test/Spec/vesting.pir
These don't exist any more, instead there will be separate collateral
inputs which we don't see.
Fortunately, we hadn't even got around to using them.
- Branch
- PR
> SCP-2256: remove fee inputs

- marlowe-playground-server/README.md
> Small fix on documentation of a nix command

- deployment/README.md
- deployment/aws-upload-secrets.nix
Add information on maintenance tasks:
- adding users
- adding environments
Add aws-upload-secrets.nix for uplading credentials
to the aws secrets manager
--------------
- Branch
- PR
> deployment/README.md: add maintenance info

- CONTRIBUTING.adoc
Link the deployment README from the CONTRIBUTING document
----
- Branch
- PR
> deployment: link deployment docs in CONTRIBUTING

- cabal.project
- nix/pkgs/haskell/haskell.nix
- nix/pkgs/haskell/materialized-unix/.plan.nix/iohk-monitoring.nix
- plutus-pab/src/Plutus/PAB/Core.hs
- plutus-pab/src/Plutus/PAB/Simulator.hs
- plutus-pab/uniswap/Main.hs
Bumping the version of [iohk-monitoring-framework](https://github.com/input-output-hk/iohk-monitoring-framework/commit/34abfb7f4f5610cabb45396e0496472446a0b2ca) to reap the benefits of `ToObject`-based rendering of log messages via the pretty-printer (and some minor cleanup).
Fixes SCP-2229.
Before (output from `cabal run plutus-pab -- all-servers --config plutus-pab.yaml`)
```
Starting: MockNode
Started: MockNode
[pab:Info:17] [2021-05-18 13:31:55.06 UTC] {"contents":{"contents":{"contents":["2020-07-29T21:44:51Z",1],"tag":"StartingSlotCoordination"},"tag":"SMockserverLogMsg"},"tag":"PABMsg"}
[pab:Info:17] [2021-05-18 13:31:55.06 UTC] {"contents":{"contents":{"tag":"NoRandomTxGeneration"},"tag":"SMockserverLogMsg"},"tag":"PABMsg"}
Starting: ChainIndex
Started: ChainIndex
[pab:Info:17] …
```
> Use new iohk-monitoring-framework and cleanup

- plutus-core/README.md
> Fix some typos on plutus-core Readme

- .github/workflows/niv-update.yml
See linked issue.
- Branch
- PR
> Fix the niv updater

- marlowe-dashboard-client/src/Pickup/View.purs
I was in a hurry, and carelessly did something wrong in my last PR (#3228). This fixes it. 🙃
> SCP-2266 (fixup): Fixing the pickup wallet dropdown.

- nix/pkgs/haskell/materialized-unix/.plan.nix/plutus-core.nix
- plutus-core/plutus-core.cabal
- plutus-core/plutus-core/src/Data/SatInt.hs
- plutus-core/untyped-plutus-core/src/UntypedPlutusCore/Evaluation/Machine/Cek/ExBudgetMode.hs
Surprisingly effective!
```
crowdfunding/1            1.467 ms       1.347 ms       -8.2%
crowdfunding/2            1.462 ms       1.344 ms       -8.1%
crowdfunding/3            1.457 ms       1.340 ms       -8.0%
crowdfunding/4            706.4 μs       655.3 μs       -7.2%
crowdfunding/5            709.5 μs       654.0 μs       -7.8%
future/1                  833.7 μs       762.6 μs       -8.5%
future/2                  1.729 ms       1.564 ms       -9.5%
future/3                  1.727 ms       1.567 ms       -9.3%
future/4                  2.158 ms       1.960 ms       -9.2%
future/5                  2.642 ms       2.395 ms       -9.3%
future/6                  2.201 ms       2.017 ms       -8.4%
future/7                  2.638 ms       2.392 ms       -9.3%
multisigSM/1 …
```
> SCP-2293: use PrimArray instead of STRef

- plutus-core/untyped-plutus-core/src/UntypedPlutusCore/Evaluation/Machine/Cek/Internal.hs
Easy enough, and it nets us a modest win.
```
crowdfunding/1            1.467 ms       1.443 ms       -1.6%
crowdfunding/2            1.462 ms       1.441 ms       -1.4%
crowdfunding/3            1.457 ms       1.439 ms       -1.2%
crowdfunding/4            706.4 μs       691.4 μs       -2.1%
crowdfunding/5            709.5 μs       692.5 μs       -2.4%
future/1                  833.7 μs       812.0 μs       -2.6%
future/2                  1.729 ms       1.693 ms       -2.1%
future/3                  1.727 ms       1.690 ms       -2.1%
future/4                  2.158 ms       2.079 ms       -3.7%
future/5                  2.642 ms       2.578 ms       -2.4%
future/6                  2.201 ms       2.142 ms       -2.7%
future/7                  2.638 ms       2.586 ms       -2.0% …
```
> SCP-2285: Remove ExMemory annotations from CekValue

- marlowe-dashboard-client/src/Pickup/View.purs
what the title says
- Branch
- PR
> fix typo on marlowe dashboard

- CONTRIBUTING.adoc
Fixed some trailing sentences noticed by Marty, did some updating while I was there.
- Branch
- PR
> Update CONTRIBUTING a bit

- doc/plutus/explanations/platform.rst
> Just added a missing word for clarity.

- plutus-ledger-api/src/Plutus/V1/Ledger/Time.hs
> Fix compilation errors after Prelude export is removed.

- plutus-ledger-api/src/Plutus/V1/Ledger/Value.hs
> Add INLINABLE pragma for Value.split (fix #3256)

- plutus-benchmark/nofib/src/Plutus/Benchmark/Queens.hs
- plutus-tx/src/PlutusTx/List.hs
> Add nub and nubBy to PlutusTx.List (fix #3250)

- cabal.project
- nix/pkgs/haskell/materialized-unix/.plan.nix/plutus-chain-index.nix
- nix/pkgs/haskell/materialized-unix/default.nix
- plutus-chain-index/LICENSE
- plutus-chain-index/NOTICE
- plutus-chain-index/plutus-chain-index.cabal
- plutus-chain-index/src/Plutus/ChainIndex.hs
- plutus-chain-index/test/Spec.hs
- stack.yaml
> SCP-2230: Plutus chain index package skeleton

- plutus-pab/src/Plutus/PAB/Simulator.hs
- plutus-pab/test/Plutus/PAB/CoreSpec.hs
* Replace a couple of `waitNSlots` statements in the tests with STM actions that wait until the condition holds
- Branch
- PR
> SCP-2130: Less 'waitNSlots' in core spec

- plutus-ledger-api/src/Plutus/V1/Ledger/Tx.hs
- plutus-ledger/src/Ledger/Generators.hs
- plutus-pab/src/Cardano/ChainIndex/Server.hs
- plutus-pab/src/Cardano/Node/Client.hs
- plutus-pab/src/Cardano/Node/Mock.hs
- plutus-pab/src/Cardano/Node/RandomTx.hs
- plutus-pab/src/Cardano/Node/Server.hs
- plutus-pab/src/Cardano/Node/Types.hs
- plutus-pab/src/Cardano/Protocol/Socket/Client.hs
- plutus-pab/src/Cardano/Protocol/Socket/Server.hs
- plutus-pab/src/Cardano/Protocol/Socket/Type.hs
- plutus-pab/src/Cardano/Wallet/Mock.hs
- plutus-pab/src/Cardano/Wallet/Server.hs
- plutus-pab/src/Plutus/PAB/App.hs
- plutus-pab/src/Plutus/PAB/Core/ContractInstance/BlockchainEnv.hs
- plutus-pab/tx-inject/Main.hs
- plutus-pab/tx-inject/config.yaml
- plutus-pab/tx-inject/start-all-servers.sh
Split the socket client into an application/client that performs chain synchronisation and one that sends transactions to the node.
- Branch
- PR
> Split the client handlers.

- plutus-playground-server/test/Playground/UsecasesSpec.hs
- plutus-playground-server/usecases/CrowdfundingSimulations.hs
- plutus-playground-server/usecases/GameSimulations.hs
- plutus-playground-server/usecases/StarterSimulations.hs
- plutus-playground-server/usecases/Vesting.hs
- plutus-playground-server/usecases/VestingSimulations.hs
Changed the playground simulations to higher lovelace values, in order to work with the change in the higher fee calculation.
- Branch
- PR
> SCP-2322 Changed the playground simulations to higher lovelace values

- marlowe-website/src/index.njk
This PR updates the copy of the website with the latest text available.
- Branch
- PR
> SCP-1865 Changes in the marlowe website copy

- plutus-ledger-api/src/Plutus/V1/Ledger/Tx.hs
> Fix comment to fix docs

- plutus-playground-server/usecases/Starter.hs
Fix typo in the comment of plutus playground example source. changed data type.
- Branch
- PR
> Fix typo - plutus playground example source

- doc/plutus/explanations/platform.rst
This PR fixes a typo in the documentation.
- Branch
- PR
> Fix typo in platform.rst

- plutus-core/plutus-core/src/PlutusCore/Builtins.hs
- plutus-core/plutus-core/test/TypeSynthesis/Golden/DecodeUtf8.plc.golden
- plutus-core/plutus-core/test/TypeSynthesis/Golden/EncodeUtf8.plc.golden
- plutus-tx-plugin/src/PlutusTx/Compiler/Builtins.hs
- plutus-tx-plugin/test/Plugin/Primitives/Spec.hs
- plutus-tx-plugin/test/Plugin/Primitives/decodeUtf8.plc.golden
- plutus-tx-plugin/test/Plugin/Primitives/encodeUtf8.plc.golden
- plutus-tx/src/PlutusTx/Builtins.hs
This PR fills the gap in strings/bytestrings functionality and will help for further literal bytestrings support.
---
- Branch
- PR
> Add encodeUtf8/decodeUtf8 for bytestrings and strings.

- web-common-marlowe/src/Decode/Helpers.purs
- web-common-marlowe/src/Decode/helpers.purs
- web-common-marlowe/src/Marlowe/Extended.purs
- web-common-marlowe/src/Marlowe/Semantics.purs
This PR modifies the contracts JSON decoding to be lazy instead of eager.
- Branch
- PR
> SCP-1165: improve performance on json decoding

- doc/plutus-doc.cabal
- doc/plutus/howtos/exporting-a-script.rst
- doc/plutus/howtos/index.rst
- doc/plutus/tutorials/BasicValidators.hs
- doc/plutus/tutorials/basic-validators.rst
- doc/reference/glossary.rst
- nix/pkgs/haskell/materialized-unix/.plan.nix/plutus-doc.nix
Extend the basic validators tutorial to talk about the typed interface,
also add a short how-to about how to export a script. It has a big TODO
though, since we don't have the envelope support yet, but that should be
easy to add later.
- Branch
- PR
> SCP-2325: How to export a script

- plutus-tx/src/PlutusTx/Data.hs
This decoder also adds the following restrictions:
- integers cannot be more than 64 bytes.
- constructor tags are nonnegative 64 bit values.
- Branch
- PR
> Direct decoder for plutus data
