- plutus-contract/src/Plutus/Contract/Types.hs
- plutus-contract/src/Plutus/Trace/Emulator/ContractInstance.hs
* `ResumableState` should keep all the log messages, not just the most recent ones. Otherwise we will never see them in the web API.
- Branch
- PR
> SCP-2147: Keep all logs in ResumableState

- marlowe-dashboard-client/src/Toast/State.purs
- marlowe-dashboard-client/src/Toast/View.purs
- marlowe-dashboard-client/tailwind.config.js
- web-common/src/Halogen/Animation.js
- web-common/src/Halogen/Animation.purs
This PR adds a closing animation to the toast messages
- Branch
- PR
> Add animation when the toast closes

- marlowe-playground-client/src/Blockly/Internal.js
- marlowe-playground-client/src/Marlowe/Blockly.purs
- marlowe-playground-client/test/Blockly/Headless.js
Having the `Slot` and `SlotParam` in the same field is problematic. For example, it breaks the roundtrip when the `SlotParam` label is a number and is confusing (see issue #2896).
This PR:
- Adds a dropdown menu to choose between `SlotParam` and `Slot` 
- Adds a custom validator that ensures only integer numbers are input when `Slot` is selected
- Branch
- PR
> SCP-2062 - Separate SlotParam from Slot in Blockly

- nix/modules/pab.nix
- nix/pkgs/haskell/materialized-unix/.plan.nix/plutus-pab.nix
- plutus-contract/src/Plutus/Trace/Emulator.hs
- plutus-contract/src/Plutus/Trace/Emulator/System.hs
- plutus-contract/src/Plutus/Trace/Playground.hs
- plutus-contract/src/Wallet/Emulator/Chain.hs
- plutus-contract/test/Spec/golden/traceOutput - pubKeyTransactions.txt
- plutus-contract/test/Spec/golden/traceOutput - pubKeyTransactions2.txt
- plutus-contract/test/Spec/golden/traceOutput - wait1.txt
- plutus-pab-client/config.nix
- plutus-pab/app/Cli.hs
- plutus-pab/plutus-pab.cabal
- plutus-pab/plutus-pab.yaml
- plutus-pab/plutus-pab.yaml.sample
- plutus-pab/src/Cardano/ChainIndex/Server.hs
- plutus-pab/src/Cardano/Node/Client.hs
- plutus-pab/src/Cardano/Node/Mock.hs
- plutus-pab/src/Cardano/Node/Server.hs
- plutus-pab/src/Cardano/Node/Types.hs
- plutus-pab/src/Cardano/Protocol/Socket/Client.hs
- plutus-pab/src/Cardano/Protocol/Socket/Server.hs
- plutus-pab/src/Cardano/Protocol/Socket/Type.hs
- plutus-pab/src/Cardano/Wallet/Server.hs
- plutus-pab/src/Plutus/PAB/App.hs
- plutus-pab/src/Plutus/PAB/Core/ContractInstance/BlockchainEnv.hs
- plutus-pab/src/Plutus/PAB/Simulator.hs
- plutus-pab/tx-inject/Main.hs
- plutus-use-cases/test/Spec/crowdfundingEmulatorTestOutput.txt
* Add a config field `mscZeroSlotTime` to the mock node's configuration. The mock node will start its slot count from that date.
* Separate `ModifySlot` from `AddBlock` in `ChainIndexControlEffect`. We need this so that we can change the slot number independently.
- Branch
- PR
> SCP-2132: Configurable slot 0

- marlowe/test/Spec/Marlowe/AutoExecute.hs
- plutus-contract/src/Plutus/Contract/Effects/WatchAddress.hs
- plutus-contract/src/Plutus/Contract/StateMachine.hs
- plutus-contract/src/Plutus/Contract/Trace.hs
- plutus-contract/src/Plutus/Contract/Trace/RequestHandler.hs
- plutus-contract/src/Wallet/Effects.hs
- plutus-contract/src/Wallet/Emulator/ChainIndex.hs
- plutus-contract/src/Wallet/Emulator/ChainIndex/Index.hs
- plutus-contract/src/Wallet/Emulator/LogMessages.hs
- plutus-contract/src/Wallet/Types.hs
- plutus-ledger-api/src/Plutus/V1/Ledger/Interval.hs
- plutus-ledger-api/src/Plutus/V1/Ledger/Slot.hs
- plutus-pab-client/src/View/Pretty.purs
- plutus-pab/src/Cardano/ChainIndex/Client.hs
- plutus-pab/src/Cardano/ChainIndex/Server.hs
- plutus-pab/src/Plutus/PAB/Arbitrary.hs
- plutus-pab/src/Plutus/PAB/Core/ContractInstance.hs
- plutus-pab/src/Plutus/PAB/Core/ContractInstance/RequestHandlers.hs
- plutus-pab/src/Plutus/PAB/Core/ContractInstance/STM.hs
- plutus-pab/src/Plutus/PAB/Events/Contract.hs
- plutus-pab/src/Plutus/PAB/Simulator.hs
- plutus-use-cases/src/Plutus/Contracts/Auction.hs
Modify `AddressChangeRequest` to use `SlotRange`. Now it returns all transactions that modify an address within the SlotRange. 
This modified `AddressChangeRequest` now can be used to get a history of a contract execution. This is needed for Marlowe Run contract execution in particular.
- Branch
- PR
> Modify AddressChangeRequest to use SlotRange

- deployment/morph/machines/marlowe-dash.nix
- marlowe-dashboard-client/plutus-pab.yaml
- nix/modules/pab.nix
- plutus-pab/plutus-pab.yaml.sample
Following #3004, this adds the zero slot time config parameter to Marlowe Run in development and production.
> Sorting out PAB config.

- plutus-ledger-api/src/Plutus/V1/Ledger/Api.hs
- plutus-ledger-api/test/Spec.hs
This puts the conversio of the `CostModelParams` into the `CostModel`
into our hot path again, but it's a pain for the ledger to maintain this
in the ledger state without a) a bunch of instances, b) us being on the
hook for not accidentally breaking them in future.
So the best path forward seems to be for us to process the paramters
when we get them, and work out a way to make that fast if it turns out
to be a problem.
- Branch
- PR
> Tweak the ledger interface for the cost model again

- marlowe-playground-client/src/HaskellEditor/State.purs
- marlowe-playground-client/src/HaskellEditor/Types.purs
- marlowe-playground-client/src/HaskellEditor/View.purs
- marlowe-playground-client/src/MainFrame/State.purs
- web-common-marlowe/src/Marlowe/Extended/Metadata.purs
This PR adds the Metadata tab to the Haskell editor and adds the loading of metadata hints to Gists, Demos, and LocalStorage.
- Branch
- PR
> SCP-2098 - Connect metadata to contracts in the Haskell editor

- default.nix
- deployment/morph/machines/marlowe-dash.nix
- deployment/morph/mk-machine.nix
- marlowe-dashboard-client/default.nix
- marlowe/follow/Main.hs
- marlowe/marlowe.cabal
- marlowe/src/Language/Marlowe/Client.hs
- marlowe/test/Spec/Marlowe/Marlowe.hs
- nix/pkgs/haskell/materialized-unix/.plan.nix/marlowe.nix
- nix/tests/default.nix
- nix/tests/vm-tests/all.nix
- nix/tests/vm.nix
- plutus-contract/src/Plutus/Contract/StateMachine.hs
- plutus-ledger/src/Ledger/AddressMap.hs
- plutus-pab/plutus-pab.yaml
- plutus-pab/run-zcb.sh
We add a new follower contract that tracks Marlowe contract execution history in form of `MarloweParams`, initial `MarloweData`, and a list of `TransactionInput`s
This is needed for Marlowe Run.
- Branch
- PR
> SCP-2103 Store contract history in Marlowe follower contract state

- marlowe-playground-client/src/HaskellEditor/Types.purs
- marlowe-playground-client/src/JavascriptEditor/State.purs
- marlowe-playground-client/src/JavascriptEditor/Types.purs
- marlowe-playground-client/src/JavascriptEditor/View.purs
- marlowe-playground-client/src/MainFrame/State.purs
This PR adds the Metadata tab to the JavaScript editor and adds the loading of metadata hints to Gists, Demos, and LocalStorage.
It also sets the Metadata as default both for JavaScript and for Haskell editor.
- Branch
- PR
> SCP-2150 - Connect metadata to contracts in the JavaScript editor

- deployment/shell.nix
Adjust the `deploy-nix` script to always re-create the "bridge files"
between terraform and morph.
The bridge files provide 2 things:
1. ssh configuration
2. per ec2 instance dns/ip information
Both provide information that `morph` cannot derive independently.
This commit chnages the script to always re-create these files before
performing the "is terraform state up to date" check. Without the files
`terraform plan` will report that there are 2 local files that have to
be created.
- Branch
- PR
> deployment-shell: always recreate terraform bridge files

- nix/pkgs/haskell/materialized-unix/.plan.nix/plutus-tx.nix
- plutus-tx/plutus-tx.cabal
- plutus-tx/src/PlutusTx/Data.hs
- plutus-use-cases/test/Spec/crowdfundingEmulatorTestOutput.txt
- plutus-use-cases/test/Spec/renderCrowdfunding.txt
- plutus-use-cases/test/Spec/renderGuess.txt
- plutus-use-cases/test/Spec/renderVesting.txt
We've added a number of special tags for constructors to the CBOR
standard, which saves us some space and makes the encoding
non-ambiguous.
They are not *quite* accepted yet, but they nearly are, and it'll be a
lot easier to use them from the beginning than to change to using them
later, so this PR does it.
- Branch
- PR
> SCP-2158: use the new CBOR tags that we have proposed

- .buildkite/deploy.sh
- deployment/shell.nix
Wait for the github ci status on the commit to deploy to turn to
"success" before deploying.
The deployment process should itself not build deployment artifacts,
instead it should use what hydra as central CI and single source of
truth is providing.
The buildkite pipeline is triggered when PRs have been merged to
master. At this point however hydra hasn't yet processed the new
master branch. This commit adds `wait-github-status` which polls
the GitHub API using hub to wait until the commit to be deployed
has been processed:
GitHub merge -> Hydra -> GitHub ci status -> buildkite deploy
- Branch
- PR
> deploy.sh: wait for github status

- CONTRIBUTING.adoc
- nix/pkgs/default.nix
- nix/pkgs/haskell/agda.sha
- nix/pkgs/haskell/cabal-install.sha
- nix/pkgs/haskell/default.nix
- nix/pkgs/haskell/extra.nix
- nix/pkgs/haskell/hlint.sha
- nix/pkgs/haskell/hls-darwin.sha
- nix/pkgs/haskell/hls-linux.sha
- nix/pkgs/haskell/stylish-haskell.sha
- nix/sources.json
This has been bugging me for ages. Now it's completely mechanical and rolled into `updateMaterialized`. Much better!
While I was at it, I made the HLS source a niv source, so it should now be updatable by doing `niv update` followed by `updateMaterialized`.
- Branch
- PR
> Teach updateMaterialized to update the tool shas as well

- marlowe-playground-client/src/MainFrame/State.purs
- marlowe-playground-client/src/MainFrame/View.purs
- playground-common/src/Gist.hs
- plutus-playground-client/src/MainFrame/MonadApp.purs
- plutus-playground-client/src/MainFrame/State.purs
- plutus-playground-client/src/MainFrame/Types.purs
- plutus-playground-client/test/MainFrameTests.purs
- web-common-playground/src/Gists/Types.purs
- web-common-playground/src/Gists/View.purs
This PR:
- Fixes the `Save` button in Marlowe Playground (it seems it didn't work because servant had some problem with `PATCH` requests, so I just replaced it with a `POST` request)
- Makes sure that `gistId` is set to `Nothing` when loading a demo, otherwise it would have saved to to the most recently openeded gist
- Renames `PublishGist` to `PublishOrUpdateGist` because the name was misleading (I realised it was meant to update half-way through implementing `UpdateGist`)
- It changes behaviour of `Save` so that, if the gist wasn't saved before (`gistId = Nothing`) it behaves as `Save as...`.
Because the code for gists is shared with Plutus Playground, I had to rename some calls to generated functions in there too, but I imagine it had the same problem.
Deployed to …
> SCP-2150 - Fix `Save` button in Marlowe Playground

- deployment/shell.nix
Implement a bash script that polls the github commit status until all
relevant checks (excluding buildkite) are available and set to
"success".
The loop exits whenever any check has a non-success state. For
authentication the github app client id/secret is used which is already
made available as environment variable of the script.
------
- Branch
- PR
> Implement curl/jq based wait-github-status

- .buildkite/deploy.sh
**Summary**
Change the buildkite deploy script to always apply terraform changes
instead of bailing out when the terraform state is not up to date.
**Details**
Up until now the deploy script executed `deploy-nix` instead of
`deploy`. The former verifies that the terraform state is up to date and
no changes are necessary. This turned out to be less practical for a
staging scenario where we just want to apply whatever the current state
of master might be.
_Note_: As a drive-by fix this also passes the previously omitted `rev` switch providing the git commit which is going to be served from `/version`. 
-----
- Branch
- PR
> buildkite deployment: apply terraform

- .buildkite/deploy.sh
Do not wait for GitHub ci status before starting the deployment. This
means that some builds are most likely going to occur which ideally
should not happen.
Ideally hydra should invoke the buildkite pipeline. Since this isn't
currently possible the next best thing was to have buildkite wait for
hydra to complete the build.
The hydra API does not provide any straight forward way to do so. The
workaround to that in turn was to poll the GitHub CI status. Sadly this
simply isn't a reliable alternative:
- Sometimes hydra evaluation will fail and the failed job will be queued
again. Hydra will thus succeeed eventually but buildkite will have
aborted with the first failure and won't have been invoked when hydra
tries a second time.
- Sometimes PRs are merged in closed succession and hydra just …
> Drop waiting for GitHub status

- marlowe/pab/Main.hs
- plutus-contract/src/Plutus/Contract/State.hs
- plutus-contract/src/Plutus/Contract/Types.hs
- plutus-contract/src/Plutus/Trace/Emulator/ContractInstance.hs
- plutus-pab/app/Cli.hs
- plutus-pab/src/Plutus/PAB/App.hs
- plutus-pab/src/Plutus/PAB/Core/ContractInstance.hs
- plutus-pab/src/Plutus/PAB/Core/ContractInstance/RequestHandlers.hs
- plutus-pab/src/Plutus/PAB/Effects/Contract.hs
- plutus-pab/src/Plutus/PAB/Effects/Contract/Builtin.hs
- plutus-pab/src/Plutus/PAB/Effects/Contract/ContractExe.hs
- plutus-pab/src/Plutus/PAB/Effects/Contract/ContractTest.hs
- plutus-pab/src/Plutus/PAB/Events/ContractInstanceState.hs
- plutus-pab/src/Plutus/PAB/Monitoring/PABLogMsg.hs
- plutus-pab/src/Plutus/PAB/Simulator.hs
* Log contract messages in the PAB's logging system (in addition to writing them into the contract state)
* This involved adding a `lastLogs` field with only the new messages, to avoid logging all the messages on every step
* Also had to shuffle some types around in `plutus-pab` to avoid cyclical imports
- Branch
- PR
> SCP-2151: PAB handles contract logs as part of its own logging

- deployment/morph/machines.nix
- deployment/terraform/loadbalancing.tf
- deployment/terraform/machines.tf
- deployment/terraform/marlowe-dashboard.tf
- deployment/terraform/playgrounds.tf
- deployment/terraform/ssh_config.tf
- deployment/terraform/webghc.tf
**Summary**
This PR drops the `_b` instances of all servers (webghc, marlowe-dash & playgrounds).
**Details**
The `_a` and `_b` instances of each server are part of the 2-availability-zone approach where each ec2 instance is deployed twice for the sake of a higher availability in case one zone becomes unreachable.
In practical terms this isn't currently helpful, desirable or necessary. There are no high-availability demands and the most likely scenario of complication would be too much load on PAB or web-ghc. Deploying to 2 availability zones does not help with that at all.
**NOTE**:
This does drop the deployment of machines to both availability zones. What this dosen't do is to drop the load balancer in general. This needs to happen as a follow-up
---------
- Branch …
> Drop availability zone

- marlowe-dashboard-client/src/ContractHome/State.purs
- marlowe-playground-client/test/Marlowe/ContractTests.purs
- marlowe-playground-client/test/Marlowe/DeinstantiatorTests.purs
- web-common-marlowe/src/Examples/PureScript/Escrow.purs
- web-common-marlowe/src/Examples/PureScript/EscrowWithCollateral.purs
- web-common-marlowe/src/Examples/PureScript/Swap.purs
- web-common-marlowe/src/Examples/PureScript/ZeroCouponBond.purs
This PR instantiates the timeout parameters for the examples as seen by the dashboard. It keeps the fully parametrised versions both for the Marlowe Playground and for the future
Deployed to https://pablo.marlowe.iohkdev.io/ and https://pablo.marlowe-dash.iohkdev.io/
- Branch
- PR
> SCP-2200 - Instantiate timeouts in all examples for the Dashboard

- marlowe/src/Language/Marlowe/Client.hs
- plutus-contract/src/Plutus/Contract/Effects/WatchAddress.hs
- plutus-contract/src/Plutus/Contract/StateMachine.hs
- plutus-contract/src/Plutus/Contract/Trace/RequestHandler.hs
- plutus-contract/src/Wallet/Emulator/ChainIndex.hs
- plutus-contract/src/Wallet/Types.hs
- plutus-pab/src/Plutus/PAB/Arbitrary.hs
- plutus-pab/src/Plutus/PAB/Core.hs
- plutus-pab/src/Plutus/PAB/Core/ContractInstance.hs
- plutus-pab/src/Plutus/PAB/Core/ContractInstance/STM.hs
- plutus-pab/src/Plutus/PAB/Effects/Contract/Builtin.hs
- plutus-pab/src/Plutus/PAB/Effects/Contract/ContractTest.hs
- plutus-pab/src/Plutus/PAB/Simulator.hs
- plutus-pab/test/Plutus/PAB/CoreSpec.hs
- plutus-use-cases/src/Plutus/Contracts/Auction.hs
- plutus-use-cases/src/Plutus/Contracts/PingPong.hs
The core of the problem was a discrepancy between emulator and PAB: In the emulator we retry all the request handlers whenever something changes, but in the PAB we don't (deliberately - to avoid polling).
The handler for `addressChangeRequest` just failed when the request was for a future slot. In the emulator this doesn't matter, because the handler is going to be retried, but in the PAB it just fails. Therefore I changed `addressChangeRequest` to wait until the slot that we're asking for has passed.
In the course of this, I changed the interval type in `AddressChangeRequest` to be definite on both ends. Otherwise we don't know how long to wait for.
- Branch
- PR
> SCP-2153: Fix wait action not working

- marlowe-playground-client/src/HaskellEditor/State.purs
- marlowe-playground-client/src/JavascriptEditor/State.purs
- marlowe-playground-client/src/MainFrame/State.purs
- marlowe-playground-client/src/MarloweEditor/State.purs
- marlowe-playground-client/src/SimulationPage/State.purs
- web-common/src/Halogen/Monaco.purs
This PR makes the trigger for resizing part of the Monaco component and gets rid of all the adhoc calls throughout
- Branch
- PR
> SCP-2043 - Open example doesn't refresh title nor size of code panel

- marlowe-dashboard-client/src/MainFrame/State.purs
- marlowe-dashboard-client/src/Pickup/State.purs
- marlowe-dashboard-client/src/Pickup/Types.purs
- marlowe-dashboard-client/src/Pickup/View.purs
We are currently showing the pickup wallet card on page load if the user has a previously picked up wallet in their `localStorage`. But if the deployment has been updated, all data (including previously used wallets) will have disappeared. This PR changes it so that we first check whether the wallet still exists on the server - if it doesn't, we show a warning to the user inviting them to clear their browser's cache (because "cache" is likely a more familiar word - in fact, we clear the `localStorage`).
> SCP-2206: Add a warning card for when cached wallet details are not found.

- marlowe-playground-client/src/Blockly/Internal.js
This PR disables the "Add comment" functionality of Blockly, since we are not using the comments. Ideally in the future we would like to include Blockly comments as Marlowe comments and re-enable this functionality.
Resolves #2897
- Branch
- PR
> SCP-2063 - Disable comments in Blockly

- nix/pkgs/haskell/materialized-unix/.plan.nix/plutus-pab.nix
- plutus-contract/src/Wallet/Emulator/Wallet.hs
- plutus-pab/plutus-pab.cabal
- plutus-pab/src/Cardano/Wallet/Mock.hs
- plutus-pab/src/Plutus/PAB/Core/ContractInstance/BlockchainEnv.hs
- plutus-pab/src/Plutus/PAB/Simulator.hs
- plutus-pab/src/Plutus/PAB/Webserver/WebSocket.hs
- plutus-pab/test/Plutus/PAB/CoreSpec.hs
There were two issues preventing this from working properly
1. The `AddressMap` maintained by the PAB was not watching the addresses of newly created wallets
2. The conversion of `Wallet` to `Address` was assuming that it was dealing with one of the emulated wallets.
- Branch
- PR
> SCP-2207: PAB wallet notifications

- nix/pkgs/haskell/materialized-unix/default.nix
- plutus-contract/plutus-contract.cabal
- plutus-contract/src/Data/Row/Extras.hs
- plutus-contract/src/Plutus/Contract.hs
- plutus-contract/src/Plutus/Contract/Request.hs
- plutus-contract/src/Plutus/Contract/Schema.hs
- plutus-pab/src/Plutus/PAB/ContractCLI.hs
Turned out `type (.\\)` is the reason of #3080. This PR replaces it with a working version. Also bumps the version of `row-types` to `1.0.1.0` with correct version of `type (.\/)`.
Tested against https://github.com/emiflake/plutus-3080-minimum-example.
----
- Branch
- PR
> Fix diff type operator (.\\). Bump row-types to 1.0.1.0.

- nix/pkgs/haskell/materialized-unix/.plan.nix/plutus-ledger-api.nix
- plutus-ledger-api/plutus-ledger-api.cabal
- plutus-ledger-api/src/Plutus/V1/Ledger/Interval.hs
- plutus-ledger-api/test/Spec.hs
- plutus-ledger-api/test/Spec/Interval.hs
A fellow Plutus Pioneer Program student (BC Chuah) noticed an odd behavior of the `overlaps` function.
Upon further investigation, I noticed that both `overlaps` and `isEmpty` needed a change to work as expected.
- Branch
- PR
> Fix implementation of isEmpty and overlaps in Interval.hs

- deployment/terraform/certificates.tf
- deployment/terraform/loadbalancing.tf
- deployment/terraform/network.tf
- deployment/terraform/variables.tf
**Summary**
Configure marlowe-finance.io records and certificates in terraform
**Details**
- Add the marlowe-finance.io public hosted zone
- Configure the load balancer for access via marlowe-finance.io
- Configure marlowe-finance.io certificates using aws DNS certificates
~_NOTE_: The changes in this PR still rely on some manual changes that still need to be added to terraform in a separate PR:~
~- CNAME record for play.marlowe-finance.io pointing to the production environment~
~- CNAME record for run.marlowe-finance.io pointing to the production environment~
~- A record for marlowe-finance.io pointing to marlowe-web on the production environment~
----
https://marlowe-finance.io/
https://run.marlowe-finance.io/
https://play.marlowe-finance.io/
----
- Branch
- PR …
> Marlowe finance routing

- marlowe-website/default.nix
Change the npmlock2nix build to copy node_modules.
The css tooling cannot deal with `node_modules` being a symlink so the
node_modules folder has to be copied instead.
-----
- Branch
- PR
> marlowe-website: Fix css build

- nix/pkgs/haskell/materialized-unix/.plan.nix/plutus-core.nix
- plutus-core/cost-model/create-cost-model/CostModelCreation.hs
- plutus-core/cost-model/test/TestCostModels.hs
- plutus-core/plc/Main.hs
- plutus-core/plutus-core.cabal
- plutus-core/plutus-core/src/Data/SatInt.hs
- plutus-core/plutus-core/src/PlutusCore/Evaluation/Machine/ExBudget.hs
- plutus-core/plutus-core/src/PlutusCore/Evaluation/Machine/ExBudgeting.hs
- plutus-core/plutus-core/src/PlutusCore/Evaluation/Machine/ExMemory.hs
Using machine integers rather than arbitrary-sized `Integer`s gives us a
decent speedup.
However, we do need to worry about overflow. It's hard to find an
existing type that has the semantics that we want. The closest is
`Data.SafeInt`, but this _throws_ on overflow. We could do with this,
but it's simpler for us to deal with _saturating_ arithmetic, since our
operations are always monotonic. Then we don't have to worry about
exceptions.
Consequently, this PR includes a copy of `Data.SafeInt` adapted to do
saturated arithmetic instead.
Overall, this is slower than just using `Int64`, but we need the
safety. I don't know why it's slower than `Int64`, though, apart from
the overflow checks.
- Branch
- PR
> SCP-1973: use machine integers for costing

- marlowe-playground-client/src/Blockly/Internal.js
- marlowe-playground-client/src/Marlowe/Blockly.purs
- marlowe-playground-client/src/Marlowe/Holes.purs
- marlowe-playground-client/test/Blockly/Headless.js
This PR adds a validator and fixes the default values for PK and token currency symbols (so that they are/accept only valid hexadecimal sequences).
- Branch
- PR
> SCP-2066 - Add validator and change default for PK and token hash in Blockly

- marlowe-playground-client/src/Blockly/Internal.js
The instructions that unregistered the context menus in blockly caused an exception that prevented subscriptions from succeeding (which resulted in JS disabled bits being editable, and buttons not refreshing). This PR wraps it in a `try ... catch` so that this doesn't have side-effects
- Branch
- PR
> SCP-2210 and SCP-2211 - Catch exception that caused subscriptions to fail

- marlowe-playground-client/src/Blockly/Internal.js
- marlowe-playground-client/src/Blockly/Internal.purs
- marlowe-playground-client/src/BlocklyComponent/State.purs
- marlowe-playground-client/src/BlocklyComponent/Types.purs
- marlowe-playground-client/src/BlocklyEditor/State.purs
- marlowe-playground-client/src/BlocklyEditor/Types.purs
- marlowe-playground-client/src/MainFrame/State.purs
- marlowe-playground-client/src/Marlowe/Blockly.purs
- marlowe-playground-client/src/MarloweEditor/State.purs
- marlowe-playground-client/src/MarloweEditor/Types.purs
This PR:
- First commit:
- Clears the stack when initialising Blockly
- Second commit:
- Groups events that populate Blockly (in `SetCode`), so that they are undone as one
- It doesn't clear the stack when returning from a roundtrip from Blockly (so that modifications done using Marlowe editor can be undone from Blockly in one step, as suggested by #2899).
Resolves #2899
- Branch
- PR
> SCP-2064 - Fix handling of undo stack for blockly

- marlowe-dashboard-client/src/Template/Format.purs
- marlowe-dashboard-client/src/Template/View.purs
- web-common-marlowe/src/Examples/Metadata.purs
I investigated the possibility of including a Markdown parser, and a library on top of that for converting its output to Halogen HTML. It looked like too much work, and entirely unnecessary for our simple needs. So I just wrote a very crude parser to put text surrounded by asterisks in bold.
> SCP-1948: Basic formatting for metadata.

- plutus-contract/src/Plutus/Contract/State.hs
- plutus-pab-client/src/MainFrame.purs
- plutus-pab-client/src/Types.purs
- plutus-pab-client/src/View.purs
- plutus-pab-client/src/View/Events.purs
- plutus-pab-client/src/View/Pretty.purs
- plutus-pab/app/Cli.hs
- plutus-pab/app/PSGenerator.hs
- plutus-pab/src/Plutus/PAB/Arbitrary.hs
- plutus-pab/src/Plutus/PAB/Core.hs
- plutus-pab/src/Plutus/PAB/Core/ContractInstance.hs
- plutus-pab/src/Plutus/PAB/Core/ContractInstance/RequestHandlers.hs
- plutus-pab/src/Plutus/PAB/Db/Eventful/Command.hs
- plutus-pab/src/Plutus/PAB/Db/Eventful/ContractStore.hs
- plutus-pab/src/Plutus/PAB/Db/Eventful/Query.hs
- plutus-pab/src/Plutus/PAB/Effects/Contract.hs
- plutus-pab/src/Plutus/PAB/Effects/Contract/Builtin.hs
- plutus-pab/src/Plutus/PAB/Effects/Contract/ContractExe.hs
- plutus-pab/src/Plutus/PAB/Events.hs
- plutus-pab/src/Plutus/PAB/Events/Contract.hs
- plutus-pab/src/Plutus/PAB/Events/ContractInstanceState.hs
- plutus-pab/src/Plutus/PAB/Monitoring/PABLogMsg.hs
- plutus-pab/src/Plutus/PAB/Webserver/Handler.hs
- plutus-pab/src/Plutus/PAB/Webserver/WebSocket.hs
- plutus-pab/test/Plutus/PAB/CoreSpec.hs
- plutus-pab/test/Plutus/PAB/Events/ContractSpec.hs
* Delete `newState` from `PartiallyDecodedResponse` - it can get quite big and we don't need it in the client
* Use `ContractResponse` instead of `PartiallyDecodedResponse` in the PAB whenever we actually need `newState`
- Branch
- PR
> SCP-2205: Don't send 'newState' to client

- plutus-core/plutus-core/src/PlutusCore/Constant/Apply.hs
- plutus-core/plutus-core/src/PlutusCore/Constant/Dynamic/Emit.hs
- plutus-core/plutus-core/src/PlutusCore/Evaluation/Machine/Ck.hs
- plutus-core/plutus-core/src/PlutusCore/Evaluation/Machine/ExBudget.hs
- plutus-core/plutus-core/test/Evaluation/ApplyBuiltinName.hs
- plutus-core/untyped-plutus-core/src/UntypedPlutusCore/Evaluation/Machine/Cek.hs
- plutus-core/untyped-plutus-core/src/UntypedPlutusCore/Evaluation/Machine/Cek/ExBudgetMode.hs
- plutus-core/untyped-plutus-core/src/UntypedPlutusCore/Evaluation/Machine/Cek/Internal.hs
- plutus-core/untyped-plutus-core/test/Evaluation/ApplyBuiltinName.hs
- plutus-ledger-api/src/Plutus/V1/Ledger/Api.hs
This is another one of Ed's suggestions. The use of `ImplicitParams` is
inessential: the real point here is using function args instead of
`ReaderT`.
I'm not sure this is quite the way to go, in particular I killed
`SpendBudget` in favour of just passing a spending function, since it
only seemed to be used in one place by `applyTypeSchemed`.
Seems to give a ~1-2% performance improvement (benchmarks in a comment).
- Branch
- PR
> Eliminate ReaderT in the CEK machine

- marlowe-playground-client/src/Blockly/Internal.js
- marlowe-playground-client/src/Marlowe/Blockly.purs
- marlowe-playground-client/test/Blockly/Headless.js
Closes #2903 
Closes #3028 
For #2903, adds a precision of 1.0 to all number fields. This makes sure they are rounded to the nearest integer.
For #3028, adds a validator that returns `null` (ie invalid) if the number is infinite (either `Infinity` or `-Infinity`). This uses a slightly different patter for setting the validator than the method used in #3113. Instead of looping over field names, this loops over all of the fields on the block using the blocks inputList and each input's fieldRow, checking for fields that are instances of FieldNumber. If the field is a FieldNumber, it sets the validator.
I decided to do it this way because I didn't want people to have to remember to append their field names to the list when creating new blocks (especially new people that might not even know it …
> Add number field validator - Marlowe blocks editor

- README.adoc
- doc/bibliography.bib
- doc/index.rst
- doc/marlowe/tutorials/index.rst
- doc/plutus/howtos/getting-started.rst
- doc/plutus/howtos/index.rst
- Remove some old content from the doc landing page, point to the new explainer pages.
- Add a getting started page (our first "how-to") that has some of the content from the `plutus-starter` README. I think it's better here, and I'm planning to make `plutus-starter` refer to the doc instead.
- Maybe the "tutorial" content from there should also be moved into a tutorial in the main doc? WDYT @silky ?
- Remove some stuff from the main README and point into the doc, tidy up some prose.
- Branch
- PR
> Work on landing pages a bit

- plutus-tx/src/PlutusTx/IsData/Class.hs
- plutus-tx/src/PlutusTx/Lift/Instances.hs
@effectfully suggested to report an error suggesting to use `Integer` instead of `Int` in #3161.
---
- Branch
- PR
> Suggest to use Integer instead of Int for Data, Lift and Typeable (fix #3161).

- marlowe-dashboard-client/src/Contract/State.purs
- marlowe-dashboard-client/src/Contract/View.purs
- marlowe-dashboard-client/src/InputField/Lenses.purs
- marlowe-dashboard-client/src/InputField/State.purs
- marlowe-dashboard-client/src/InputField/Types.purs
- marlowe-dashboard-client/src/InputField/View.purs
- marlowe-dashboard-client/src/MainFrame/State.purs
- marlowe-dashboard-client/src/Pickup/State.purs
- marlowe-dashboard-client/src/Pickup/View.purs
- marlowe-dashboard-client/src/Play/Lenses.purs
- marlowe-dashboard-client/src/Play/State.purs
- marlowe-dashboard-client/src/Play/Types.purs
- marlowe-dashboard-client/src/Play/View.purs
- marlowe-dashboard-client/src/Template/Lenses.purs
- marlowe-dashboard-client/src/Template/State.purs
- marlowe-dashboard-client/src/Template/Types.purs
- marlowe-dashboard-client/src/Template/Validation.purs
- marlowe-dashboard-client/src/Template/View.purs
- marlowe-dashboard-client/src/WalletData/Validation.purs
- marlowe-dashboard-client/src/WalletData/View.purs
This PR uses the new `InputField` component for role inputs in the contract setup screen. I'm not using it for contract parameters (yet), but that will be a sizable chunk of extra work (we'll have to generalise the inputs to cover numbers and datetimes as well as strings), and it's not urgent - we're not using slot parameters at the moment, and value parameters have a default value of zero, so they don't show up as invalid by default anyway. So I think I'd better stop here and focus on some other more urgent things for the initial release.
Note I've replaced the `Show` instance for errors with a proper custom `InputFieldError` class. I've also fixed a couple of things in the Pickup workflow that part 1 didn't get quite right.
UPDATE: I've pushed an unrelated modification that didn't feel …
> SCP-2254 (part 2): Improving the input elements 

- marlowe-playground-client/packages.dhall
- marlowe-playground-client/spago-packages.nix
- marlowe-playground-client/spago.dhall
- marlowe-playground-client/src/SimulationPage/View.purs
- marlowe-playground-client/src/Text/Markdown/TrimmedInline.purs
- marlowe-playground-client/static/css/panels.scss
This PR applies a trimmed down version of SlamDown before showing metadata in the Marlowe Playground
Deployed to: http://pablo.marlowe.iohkdev.io/
- Branch
- PR
> SCP-2252 - Add trimmed down markdown processing to playground metadata

- .buildkite/pipeline.yml
- .buildkite/plutus-starter-devcontainer-push.sh
- default.nix
- nix/devcontainer/deploy/default.nix
Fixes SCP-2127
I think this is ready; but I can't test it until I push a tag and this code is in master; so it'd be good for people to take a glance now and see if anything seems a-miss.
Thanks! :)
I this to be pushed to the right reop if the tag is named for example, `plutus-starter-devcontainer/v1.0`, which is enforced via the .buildkit config ( thanks @gilligan ! )
- Branch
- PR
> deploy plutus-starter devcontainer to dockerhub wip

- nix/pkgs/haskell/extra.nix
Enable hls/ghcide special flag to make it aware that we are using a patched ghc, that can handle `UnboxedTuples`.
- Branch
- PR
> Notify hls/ghcide that we are using a patched ghc

- plutus-tx/src/PlutusTx/List.hs
- plutus-tx/src/PlutusTx/Prelude.hs
The problem in #3187 is that `PlutusTx.Prelude` re-exports `Prelude.head` which fails to compile. The fix is to add Plutus's own implementation.
---
- Branch
- PR
> Add Plutus implementation of head (fix #3187).

- marlowe-playground-client/src/Examples/JS/Contracts.purs
- marlowe-playground-client/test/Marlowe/DeinstantiatorTests.purs
- marlowe-playground-server/contracts/ZeroCouponBond.hs
- web-common-marlowe/src/Examples/PureScript/ZeroCouponBond.purs
The parameter name in the contract didn't match the parameter name in the metadata.
> Zero Coupon Bond example - fixing a parameter name.

- nix/pkgs/haskell/materialized-unix/.plan.nix/plutus-tx.nix
- plutus-tx/plutus-tx.cabal
Doctest cannot be built when cross compiling for windows.
This will allow projects that do not want to build the tests to avoid the dependency on `doctest`.
Is there a reason for this dependency needs to be on the library?
> Move doctest dependency from plutus-tx lib to test

- .buildkite/pipeline.yml
- deployment/README.md
- deployment/envs.nix
- deployment/terraform/locals.tf
Add a 'staging' environment which replaces 'alpha' as the continuous
integration environment reflecting the master branch.
- Add staging to envs.nix in eu-west-3
- Add staging in the terraform configuration
- Configure staging in the buildkite pipeline
- Add staging badge for staging in the deployment README
Notes:
- The buildkite pipeline was updated to include the alpha branch
- credentials for staging were uploaded to the aws secrets manager
--------------
- Branch
- PR
> Add 'staging' environment

- plutus-tx/src/PlutusTx/List.hs
- plutus-tx/src/PlutusTx/Prelude.hs
The problem in #3202 is that PlutusTx.Prelude re-exports Prelude.take which fails to compile. The fix is to add Plutus's own implementation.
---
- Branch
- PR
> Add Plutus implementation of take (fix #3202)

- ci.nix
- default.nix
- nix/default.nix
- nix/pkgs/default.nix
- release.nix
- shell.nix
Drop the unused `rev` nix argument which was used to set the git
revision in packages using `set-git-rev`
The use of set-git-rev was dropped by #2984
----
- Branch
- PR
> Drop git rev argument

- nix/pkgs/haskell/materialized-unix/.plan.nix/plutus-core.nix
- nix/pkgs/haskell/materialized-unix/default.nix
- plutus-core/plutus-core.cabal
- plutus-core/plutus-core/satint-test/TestSatInt.hs
- plutus-core/plutus-core/src/Data/SatInt.hs
- plutus-core/plutus-core/src/PlutusCore/Evaluation/Machine/ExBudget.hs
- plutus-core/plutus-core/src/PlutusCore/Evaluation/Machine/ExMemory.hs
- plutus-core/untyped-plutus-core/src/UntypedPlutusCore/Evaluation/Machine/Cek/ExBudgetMode.hs
This changes `SatInt` to use a safer implementation, and adds tests (mirroring those in `safeint`, so they're a bit weird in case I want to upstream later).
Unfortuantely, this loses us some performance, but I think we just have to eat it. It's very unclear to me what is making the difference now, and inspecting the core of `ExBudgetingMode` shows everything inlining nicely still.
```
crowdfunding/1           1.464 ms       1.476 ms    +0.8%
crowdfunding/2           1.466 ms       1.481 ms    +1.0%
crowdfunding/3           1.465 ms       1.484 ms    +1.3%
crowdfunding/4           713.7 μs       724.3 μs    +1.5%
crowdfunding/5           713.8 μs       724.6 μs    +1.5%
future/1                 836.7 μs       848.7 μs    +1.4%
future/2                 1.718 ms       1.741 ms    +1.3% …
```
> Fix SatInt (take 2)

- nix/devcontainer/devcontainer.nix
- nix/devcontainer/plutus-devcontainer.nix
This is needed on WSL, but not Ubuntu, apparently.
See:
https://cardano.stackexchange.com/questions/382/problem-starting-a-plutus-devcontainer-in-windows/444#444
and https://github.com/NixOS/docker/issues/7.
Fixes #3178
- Branch
- PR
> Add nsswitch.conf back

- nix/pkgs/haskell/materialized-unix/.plan.nix/plutus-pab.nix
- plutus-pab/plutus-pab.cabal
- plutus-pab/plutus-pab.yaml
- plutus-pab/src/Plutus/PAB/App.hs
- plutus-pab/src/Plutus/PAB/Db/Memory/ContractStore.hs
* When the `InMemory` backend is selected we now handle the `ContractStore` effect by writing everything to a TVar
* Previously the sqlite memory backend was used, which resulted in a massive memory leak because the old events weren't discarded
- Branch
- PR
> SCP-2263: Replace eventful memory backend with TVar

- nix/pkgs/haskell/materialized-unix/.plan.nix/plutus-ledger-api.nix
- nix/pkgs/haskell/materialized-unix/.plan.nix/plutus-ledger.nix
- plutus-ledger-api/plutus-ledger-api.cabal
- plutus-ledger-api/src/Plutus/V1/Ledger/Contexts.hs
- plutus-ledger-api/src/Plutus/V1/Ledger/Interval.hs
- plutus-ledger-api/src/Plutus/V1/Ledger/Time.hs
- plutus-ledger/plutus-ledger.cabal
- plutus-ledger/src/Ledger.hs
- plutus-ledger/src/Ledger/Constraints/OnChain.hs
- plutus-ledger/src/Ledger/Constraints/TxConstraints.hs
- plutus-ledger/src/Ledger/Index.hs
- plutus-ledger/src/Ledger/TimeSlot.hs
- plutus-ledger/test/Spec.hs
- plutus-playground-server/usecases/Crowdfunding.hs
- plutus-playground-server/usecases/Vesting.hs
- plutus-use-cases/bench/Bench.hs
- plutus-use-cases/src/Plutus/Contracts/Crowdfunding.hs
- plutus-use-cases/src/Plutus/Contracts/Escrow.hs
- plutus-use-cases/src/Plutus/Contracts/MultiSigStateMachine.hs
- plutus-use-cases/src/Plutus/Contracts/SimpleEscrow.hs
- plutus-use-cases/src/Plutus/Contracts/Vesting.hs
- plutus-use-cases/test/Spec/crowdfunding.pir
- plutus-use-cases/test/Spec/crowdfundingEmulatorTestOutput.txt
- plutus-use-cases/test/Spec/gameStateMachine.pir
- plutus-use-cases/test/Spec/governance.pir
- plutus-use-cases/test/Spec/multisigStateMachine.pir
- plutus-use-cases/test/Spec/renderCrowdfunding.txt
- plutus-use-cases/test/Spec/renderGuess.txt
- plutus-use-cases/test/Spec/renderVesting.txt
- plutus-use-cases/test/Spec/vesting.pir
Created a new type called `POSIXTime` similar to the one in `https://hackage.haskell.org/package/time-1.6.0.1`. The goal of this type is to use it in the on-chain part of Plutus. Most notably, `TxInfo` now uses `POSIXTimeRange` instead of `SlotRange`. Updated the rest of the code to work with this change.
- Branch
- PR
> SCP-2214 Switch to POSIXTime instead of Slot in TxInfo

- marlowe-dashboard-client/src/Pickup/Lenses.purs
- marlowe-dashboard-client/src/Pickup/State.purs
- marlowe-dashboard-client/src/Pickup/Types.purs
- marlowe-dashboard-client/src/Pickup/View.purs
- web-common/src/Halogen/HTML/Events/Extra.purs
This PR changes the wallet dropdown menu on the pickup screen so that it appears when you focus on the input box, and shows all wallet nicknames in your library when the input is empty.
> SCP-2266: Improving the pickup wallet dropdown menu.

- plutus-pab-client/src/View/Contracts.purs
- plutus-playground-client/src/Action/View.purs
- web-common-plutus/src/Schema/View.purs
[plutus-playground-client]
This PR makes use of the action index in order to give input ids a unique name which fixes #3196
> Use action index to give labels a unique id

- marlowe-dashboard-client/src/Contract/Lenses.purs
- marlowe-dashboard-client/src/Contract/State.purs
- marlowe-dashboard-client/src/Contract/Types.purs
- marlowe-dashboard-client/src/Contract/View.purs
Does what it says in the title. I want to get this up quickly in time for the video recording, so I've left out a bonus feature (remembering which tab is showing for previous steps whenever a new transaction or timeout moves things forward).
> SCP-2295: Make tasks and balances tabs independent for each step.

- deployment/terraform/network.tf
Just add CNAME entry for webinar and make sure that DNS entries are only created when deployin `production`
- Branch
- PR
> Add CNAME entry for webinar

- marlowe-playground-client/package.json
This PR fixes a build issue were the CSS was not being minified and purged.
I've tried the same option that the dashboard uses `--node-env=production` but it didn't work for this version of webpack, so I had to use the `NODE_ENV` env variable.
The CSS changes from 231kb compressed to 45kb compressed.
- Branch
- PR
> Marlowe Playground: Fix build optimization

- plutus-core/untyped-plutus-core/src/UntypedPlutusCore/Core/Type.hs
This gives us a percent or so in the benchmarks. Making only some of the
fields strict does not give this benefit (?). I haven't experimented
exhaustively, but at least making the annotations non-strict destroys
the improvement.
- Branch
- PR
> Make fields of Term strict

- plutus-tx/src/PlutusTx/Foldable.hs
- plutus-tx/src/PlutusTx/Prelude.hs
The problem in #3203 is that PlutusTx.Prelude re-exports Prelude.mapM_ which fails to compile. The fix is to add Plutus's own implementation.
---
- Branch
- PR
> Add Plutus implementation of mapM_ (fix #3203).

- plutus-contract/src/Plutus/Contract/Test.hs
- plutus-contract/src/Plutus/Contract/Test/ContractModel.hs
- plutus-contract/src/Plutus/Trace/Emulator/Types.hs
- plutus-contract/src/Wallet/Emulator/Folds.hs
State machine property tests that use multiple contract instances per wallet are likely to fail with a `JSONDecodingError`. This is because all those instances use the same `ContractInstanceTag`. The `ContractInstanceTag` is used in `Wallet.Emulator.Folds` to identify events for a specific instance, so folds such as `Wallet.Emulator.Folds.instanceState` break because they are fed the wrong events.
This PR adds an `instanceTag` function to the `ContractModel` class. The default implementation of `instanceTag` gives the old behavior (ie. `walletInstanceTag`). I tried it on the sample code fom #3249 and the JSON decoding error went away (the test failed for some other reason though).
- Branch
- PR
> SCP-2299: Fix a Json decoding error when using ContractModel

- plutus-core/plutus-core/src/PlutusCore/Builtins.hs
- plutus-tx-plugin/src/PlutusTx/Compiler/Builtins.hs
- plutus-tx-plugin/test/Plugin/Primitives/Spec.hs
- plutus-tx-plugin/test/Plugin/Primitives/equalsString.plc.golden
- plutus-tx/src/PlutusTx/Builtins.hs
- plutus-tx/src/PlutusTx/Eq.hs
- plutus-tx/src/PlutusTx/Lift/Instances.hs
The PR adds `equalsString` and `Eq` instance for `Builtins.String` (should help in #3254).
---
- Branch
- PR
> Add equalsString to Plutus core

- nix/pkgs/haskell/materialized-unix/.plan.nix/plutus-core.nix
- nix/pkgs/haskell/materialized-unix/default.nix
- plutus-core/plutus-core.cabal
- plutus-core/untyped-plutus-core/bench/Main.hs
- plutus-core/untyped-plutus-core/src/Data/RandomAccessList/SkewBinary.hs
- plutus-core/untyped-plutus-core/test/TestRAList.hs
This PR introduces a binary random access list (BRAL) implementation, 
influenced by Okasaki book (purely functional data structures) and Kmett: https://github.com/ekmett/coda/blob/bca7e36ab00036f92d94eb86298712ab1dbf9b8d/wip/bdd/Data/List/Skew.hs
BRAL is supposed to be faster (overall) than IntMap patricia trees (what we use right now for the CEK environments), and this PR would help us eventually switch CEK environments to use BRAL.
There is also quickcheck&unit testing and a criterion micro-benchmark comparing it against IntMap and [ral](https://hackage.haskell.org/package/ral).
- Branch
- PR
> SCP-2313  Binary Random Access List implementation, benchmarks, test suite

- marlowe-playground-client/src/Marlowe/Holes.purs
- marlowe-playground-client/test/Main.purs
- marlowe-playground-client/test/Marlowe/Holes/SemanticTest.purs
This PR is a pre-requisite to fix the functionality of the simulator replacing the contract with the continuation (instead of highlighting) and also for adding a blockly or flow simulator.
- Branch
- PR
> scp 2321 - Add computeTransaction for terms

- plutus-core/plutus-ir/src/PlutusIR/Transform/LetFloat.hs
- plutus-core/plutus-ir/test/TransformSpec.hs
- plutus-core/plutus-ir/test/TypeSpec.hs
- plutus-core/plutus-ir/test/transform/letFloat/strictNonValueDeep
- plutus-core/plutus-ir/test/transform/letFloat/strictNonValueDeep.golden
- plutus-core/plutus-ir/test/types/strictNonValueDeep
- plutus-core/plutus-ir/test/types/strictNonValueDeep.golden
This fixes a bug where the letfloat algorithm would not increment the "depth" for effectful-lets, although they are "anchors".
The bug was encountered in `ea3e1c0a0ffdeebed2226c8d651f4c4528bd2f9e`, when the Currency plutus-use-case was prior applied to multiple (>2) inliner pir passes.
- Branch
- PR
> Fix for missing depth increment in LetFloat

- marlowe-dashboard-client/src/Contract/View.purs
- marlowe-dashboard-client/src/ContractHome/View.purs
A couple of tiny visual bug fixes:
1. The vertical position of the "back" arrow in the contract card is different on the last step (because the "next" button is absent there, making the containing element slightly shorter). Adding vertical padding to match the button fixes this.
2. The gray bit at the bottom of contract boxes isn't always right at the bottom (see the Simple escrow box in the screenshot attached). Flexbox to the rescue.
> Two small CSS tweaks.

- playground-common/src/Schema.hs
- plutus-ledger/src/Ledger.hs
- plutus-use-cases/src/Plutus/Contracts/Uniswap/Types.hs
> Add ToSchema instance for AssetClass (fix #3298)

- nix/tests/vm-tests/all.nix
- nix/tests/vm-tests/marlowe-playground.nix
- nix/tests/vm-tests/pab.nix
- nix/tests/vm-tests/plutus-playground.nix
- nix/tests/vm-tests/web-ghc.nix
**Summary**: 
Improve NixOS vm tests by providing better output
**Details**:
This PR introduces the following changes:
- Add python subtests for logical grouping of asserts
- Proper asserts with expected and actual output
- Improve playground config reload testing with additional assert
The VM tests have been annoying because of the very limited information that was provided in case of errors. With the changes in this PR it definitely going to be easy to reason about the cause of error.
Example output:
```
(1.98 seconds)
Test "********************************************************************************************* TEST: Can process a valid compilation request" failed with error: "Expected response wrapped in 'Right'. Actual: {"Right":{"result":"","warnings":[]}}"
error:
Traceback …
```
> Improve NixOS vm test asserts

- marlowe-dashboard-client/src/Contract/View.purs
- marlowe-dashboard-client/src/MainFrame/State.purs
- marlowe-dashboard-client/src/Pickup/State.purs
- marlowe-dashboard-client/src/Pickup/Types.purs
- marlowe-dashboard-client/src/Pickup/View.purs
- marlowe-dashboard-client/src/Play/State.purs
- marlowe-dashboard-client/src/Play/Types.purs
- marlowe-dashboard-client/src/Play/View.purs
- marlowe-dashboard-client/src/Template/View.purs
- marlowe-dashboard-client/src/WalletData/View.purs
This PR prevents transactions on the frontend for which the wallet has insufficient funds. When we move to the real thing, we'll have to think this through a bit more carefully, given that we don't know in advance exactly how much each transaction will cost. (E.g. maybe we just discount the transaction fee from the calculation, and only rule out deposits for which the wallet has insufficient funds. Or maybe we assume a minimum transaction fee.) Anyway, for now this seems sensible.
While I was at it I noticed an odd case: if an action times out while you have the action confirmation card open, you are still able to complete the action. Of course the PAB would rule it out on the other end, but since we can already determine that it won't work, we shouldn't let the user do it in the first …
> Making transactions impossible if wallet has insufficient funds.

- plutus-core/generators/PlutusCore/Generators/Internal/Entity.hs
- plutus-core/generators/PlutusCore/Generators/Internal/TypedBuiltinGen.hs
- plutus-core/plutus-core/src/PlutusCore/Default/Builtins.hs
This is a simplification on its own, but there's a chance that the 
```
- instance (GShow uni, GEq uni, DefaultUni <: uni) => ToBuiltinMeaning uni DefaultFun where
+ instance uni ~ DefaultUni => ToBuiltinMeaning uni DefaultFun where
```
change can give us some speed-up. Haven't run the benchmarks yet.
> [Builtins] Removed usages of '<:'

- plutus-contract/src/Plutus/Contract/Wallet.hs
This PR fixes the problem occurred in #3246 where the token gets passed into two transactions for pubkey and script using `mustSpendPubKeyOutput` constraint.
---
- Branch
- PR
> Filter out input values before coin selection (fix #3246).

- plutus-pab-client/default.nix
by also generating the test files that plutus-pab-client imports
Fixes https://github.com/input-output-hk/plutus/issues/3328
- Branch
- PR
> Fix plutus-pab-client npm start

- plutus-pab-client/default.nix
This command deliberately calls out to nix instead of directly using the
derivation, so that we can put it in the shell without incurring a
dependency on those derivations.
cc @luigy 
I _do_ have a check for this in `ci.nix`, so I'm not sure why it passed :/
- Branch
- PR
> Fix shell depending on haskell libraries

- marlowe-dashboard-client/src/Capability/Marlowe.purs
- marlowe-dashboard-client/src/Env.purs
- marlowe-dashboard-client/src/MainFrame/State.purs
- marlowe-dashboard-client/src/Play/State.purs
When using the localStorage dummy data, we were still subscribing to contracts and wallets in the PAB. I thought this wouldn't matter (I still think it doesn't for contracts), but when subscribing to a wallet that doesn't exist, the PAB gives us a websocket update saying that it has no funds. This is because there is no way of distinguishing between a wallet that doesn't exist and one that has no funds (there are no outputs in the UTXO set in both cases).
So this fixes the frontend to only subscribe/unsubscribe when we're not using the localStorage dummy data.
> Fixing websocket subscription bug.

- nix/pkgs/default.nix
- nix/pkgs/haskell/default.nix
Exported the variable `compiler-nix-name` in Nix to use it in other projects such as `plutus-starter`. The goal is to reuse the exact same GHC version in both projects.
- Branch
- PR
> Exported the variable 'compiler-nix-name' in Nix

- nix/modules/web-ghc.nix
- nix/pkgs/haskell/materialized-unix/.plan.nix/web-ghc.nix
- nix/tests/vm-tests/web-ghc.nix
- web-ghc/app/Main.hs
- web-ghc/app/Webserver.hs
- web-ghc/src/Interpreter.hs
- web-ghc/src/Webghc/Server.hs
- web-ghc/web-ghc.cabal
**Summary**: 
Make the interpretation timeout period for `web-ghc` configurable
**Details**:
Several VM tests have been very unstable in CI. After adding better asserts with more useful error messages we could recently see that in the case of `web-ghc` related tests, the failures are triggered by timeouts: Inside `web-ghc` the ghc invocation is limited to 80s - Apparently insufficient for CI runs (_argh_).
This PR adds `-t <seconds>` option to `webghc` and extends the webghc nixos service with a `timeout` option. The default value remains at 80s but for tests the value is bumped up to `180`.
**Note**: We could extend the timeout further if this is not sufficient but maybe then we would also have to consider finding out where these enormous delays come from.
---
- …
> Webghc fixes

- plutus-ledger-api/src/Plutus/V1/Ledger/Api.hs
- plutus-ledger-api/src/Plutus/V1/Ledger/Examples.hs
- plutus-ledger-api/src/Plutus/V1/Ledger/Scripts.hs
The whole point of having the CBOR serialization wrapping the Flat one
was so that we could present the "standard" format downstream. As it is,
I accidentally used Flat, so the ledger has been using it, and it's all
a mess.
The root technical cause insofar as there is one is that `Script` has
two serialization instances for different formats, which is asking for
trouble. I got rid of the Flat one.
While I was at it I fixed another papercut reported by Jordan: it's confusing to have multiple things called `Script`, let's just make the type alias be `SerializedScript` for clarity.
- Branch
- PR
> Fix the serialization format for scripts.

- plutus-playground-server/usecases/Game.hs
Improved game contract playground example by adding logs and applying the validator function in the off-chain part of the code before submitting a transaction.
Same change as https://github.com/input-output-hk/plutus-starter/pull/15, except for a small difference in the `guess` function. In the `plutus-starter` PR, we would call `fundsAtAddressGeq` before `endpoint` to ensure that the `guess` endpoint is only available when script has at least one UTxO of a least 1 lovelace. However, doing that doesn't work when combined with the `select` function between two contracts. 
Therefore, in the game contract of the playground, which needs to use the `select` function, I swapped the call order. The `guess` endpoint will first wait for an endpoint call, and then wait for the script to have at …
> Improved game contract playground example

- cabal.project
This is quite irritating:
- Before this version `dependent-sum` had its own `GEq`.
- After this version they use the one from `some`.
- We used to use the version from `dependent-sum`, now we use the one
from `some`.
- We only depend on `dependent-sum-template`, *not* `dependent-sum`.
- `dependent-sum-template` does not constrain `dependent-sum` very
heavily.
The result is that the old `dependent-sum` appears in our build plan, so
the call to `deriveGEq` generates an instance of *its* `GEq`, which is
wrong.
Since we don't depend on `dependent-sum` directly (and we insist that
`plutus-core` doesn't have excess dependencies), the only way I can
see to ensure that we don't pick the old `dependent-sum` is to add a
constraint in `cabal.project`.
(tagging @effectfully in case you know of any …
> Bound dependent-sum

- nix/pkgs/haskell/cardano-repo-tool.sha
- nix/pkgs/haskell/extra.nix
We weren't passing `checkMaterialization` down to `cardano-repo-tool`,
so the CI wasn't telling us if it was out-of-date.
`updateMaterialized` fixed the sha file actually being wrong.
- Branch
- PR
> Fix materialization checking for cardano-repo-tool

- marlowe-playground-client/src/Examples/JS/Contracts.purs
- marlowe-playground-client/test/Marlowe/DeinstantiatorTests.purs
- marlowe-playground-server/contracts/ContractForDifferences.hs
- marlowe-playground-server/contracts/ContractForDifferencesWithOracle.hs
- marlowe-playground-server/contracts/CouponBondGuaranteed.hs
- web-common-marlowe/src/Examples/PureScript/ContractForDifferences.purs
- web-common-marlowe/src/Examples/PureScript/ContractForDifferencesWithOracle.purs
- web-common-marlowe/src/Examples/PureScript/CouponBondGuaranteed.purs
- web-common-marlowe/src/Examples/PureScript/Escrow.purs
- web-common-marlowe/src/Examples/PureScript/EscrowWithCollateral.purs
- web-common-marlowe/src/Examples/PureScript/Swap.purs
- web-common-marlowe/src/Examples/PureScript/ZeroCouponBond.purs
This PR multiplies all timeouts in the example contracts by 10. They were all quite short before, and Russ said this was making users nervous in testing. We'll proabably want to think about the numbers more carefully later, but I'm pushing this through for now because there's more testing later today.
> Multiplying timeouts by 10.

- nix/devcontainer/devcontainer.nix
This is needed for people who ( 😱 ) don't have a ~/.cabal folder yet.
Very uncontroversial change; but I'll release a new devcontainer image once it's merged.
- Branch
- PR
> devcontainer - Ensure ~/.cabal/packages exists with ownership

- doc/plutus-doc.cabal
- doc/plutus/howtos/exporting-a-script.rst
- doc/plutus/tutorials/BasicValidators.hs
- nix/pkgs/haskell/materialized-unix/.plan.nix/plutus-doc.nix
- nix/pkgs/haskell/materialized-unix/.plan.nix/plutus-ledger.nix
- plutus-ledger-api/src/Plutus/V1/Ledger/Api.hs
- plutus-ledger/plutus-ledger.cabal
- plutus-ledger/src/Ledger.hs
- plutus-ledger/src/Ledger/Scripts.hs
Add the ability to export serialised PLC programs with Cardano API envelopes.
- Branch
- PR
> SCP-1879: Export serialised PLC programs with envelopes

- marlowe-dashboard-client/src/Capability/Marlowe.purs
- marlowe-dashboard-client/src/Contract/Lenses.purs
- marlowe-dashboard-client/src/Contract/State.purs
- marlowe-dashboard-client/src/Contract/Types.purs
- marlowe-dashboard-client/src/Contract/View.purs
- marlowe-dashboard-client/src/ContractHome/State.purs
- marlowe-dashboard-client/src/ContractHome/View.purs
- marlowe-dashboard-client/src/Main.purs
- marlowe-dashboard-client/src/MainFrame/State.purs
- marlowe-dashboard-client/src/Play/State.purs
- marlowe-dashboard-client/src/WalletData/Lenses.purs
- marlowe-dashboard-client/src/WalletData/State.purs
- marlowe-dashboard-client/src/WalletData/Types.purs
This PR makes the necessary state modifications and view tweaks to enable showing placeholders after creating a contract or submitting a transaction (which are then replaced when we receive confirmation through the PAB).
They look ugly at the moment (see screenshots below) - part 2 will be making them look nice, once we get some designs from Russ.
> SCP-2377: Add placeholders for contracts/transactions while waiting confirmation (part 1 of 2).

- marlowe-dashboard-client/src/Css.purs
- marlowe-dashboard-client/src/InputField/Lenses.purs
- marlowe-dashboard-client/src/InputField/State.purs
- marlowe-dashboard-client/src/InputField/Types.purs
- marlowe-dashboard-client/src/InputField/View.purs
- marlowe-dashboard-client/src/Pickup/Lenses.purs
- marlowe-dashboard-client/src/Pickup/State.purs
- marlowe-dashboard-client/src/Pickup/Types.purs
- marlowe-dashboard-client/src/Pickup/View.purs
- marlowe-dashboard-client/src/Play/State.purs
- marlowe-dashboard-client/src/Template/View.purs
- marlowe-dashboard-client/src/WalletData/Validation.purs
- marlowe-dashboard-client/src/WalletData/View.purs
Russ reported a "bug" with Firefox not showing the datalist dropdown when you click inside an input with a linked datalist (that's just the way Firefox does it, but it does make things quite unfriendly in our use case). Using a version of the custom dropdown already implemented for the wallet pickup screen solves this problem.
> SCP 2384 - Implement custom dropdowns everywhere.

- README.adoc
`docs.cardano.org` is now the new doc site which doesn't have any of our
docs on it. Go back to the RTD site which works fine.
- Branch
- PR
> Fix link to docs

- doc/plutus/tutorials/BasicPolicies.hs
- doc/plutus/tutorials/basic-forging-policies.rst
- plutus-ledger-api/src/Plutus/V1/Ledger/Scripts.hs
- plutus-ledger/src/Ledger/Index.hs
- plutus-ledger/src/Ledger/Typed/Scripts/MonetaryPolicies.hs
- plutus-ledger/src/Ledger/Typed/Scripts/Validators.hs
- plutus-ledger/src/Ledger/Typed/TypeUtils.hs
- plutus-pab/src/Plutus/PAB/Arbitrary.hs
- plutus-use-cases/src/Plutus/Contracts/Currency.hs
- plutus-use-cases/src/Plutus/Contracts/Prism/Credential.hs
- plutus-use-cases/src/Plutus/Contracts/Prism/STO.hs
- plutus-use-cases/src/Plutus/Contracts/Uniswap/OnChain.hs
- plutus-use-cases/test/Spec/renderGuess.txt
This is really only the beginning of this: it completely punts on
handling actually passing the redeemers around properly, instead just
conjuring `()` in all cases. The main point of this is so that
downstream can use our libraries to make minting policies that will work
with the real ledger, which will pass the extra argument (and does
already handle the redeemers).
I will make a follow-up PR for actually doing things properly, but it's
a bit of a rabbit-hole, so I thought I should get this one done first.
- Branch
- PR
> SCP-2370: let minting policies take redeemers

- plutus-core/plutus-core/src/PlutusCore/Evaluation/Machine/ExBudget.hs
- plutus-core/plutus-core/src/PlutusCore/Evaluation/Machine/ExMemory.hs
- plutus-core/plutus-core/test/Spec.hs
- plutus-ledger-api/src/Plutus/V1/Ledger/Api.hs
This rescales costs as seen by the ledger by a factor of ~10^6~ 10^3, shifting them into ~microseconds~ nanoesconds.  For the validation benchmarks reported [here](https://github.com/input-output-hk/plutus/pull/3378#issuecomment-861749038) that gives cpu costs roughly in the range 500,000 - 4,000,000 (microseconds gives 500-4,000 which is maybe a bit too coarse). We could divide by another 10 or 100 to get smaller numbers but that might get a bit confusing when trying to compare costs with times.
- Branch
- PR
> SCP-2375: Kwxm/rescale ledger costs

- plutus-core/plutus-core/src/PlutusCore/Evaluation/Machine/ExBudget.hs
- plutus-core/plutus-core/src/PlutusCore/Evaluation/Machine/ExMemory.hs
- plutus-core/plutus-core/test/Spec.hs
- plutus-ledger-api/src/Plutus/V1/Ledger/Api.hs
Reverts input-output-hk/plutus#3379
In a [Slack discussion](https://input-output-rnd.slack.com/archives/C21UF2WVC/p1624308474236900?thread_ts=1623683048.160500&cid=C21UF2WVC) the ledger people have decided that they'll do cost scaling on their side.  It seems risky to scale costs in multiple places, so let's revert this and use picoseconds everywhere in `plutus-core`.
> Revert "SCP-2375: Kwxm/rescale ledger costs"

- marlowe-dashboard-client/package-lock.json
- marlowe-dashboard-client/package.json
- marlowe-dashboard-client/src/Contract/View.purs
- marlowe-dashboard-client/src/Template/Lenses.purs
- marlowe-playground-client/src/MetadataTab/State.purs
- marlowe-playground-client/src/MetadataTab/Types.purs
- marlowe-playground-client/src/MetadataTab/View.purs
- marlowe-playground-client/src/SimulationPage/View.purs
- web-common-marlowe/src/Examples/Metadata.purs
- web-common-marlowe/src/Marlowe/Extended/Metadata.purs
This PR modifies the type of metadata to include information about the format that the choices have.
In the end, I am suggesting the following formatting options for now:
```haskell
data ChoiceFormat
= DefaultFormat
| Decimal Int String
```
Where `DefaultFormat` just represents that we didn't bother setting up a formatting for the choice (we can have the same behaviour as until now, some kind of "auto" option). And `Decimal` means that this is a number representing a number with `Int` decimals and the `String` decorating label, which could be used for currency symbol or something else that is very brief.
I found this to be most useful when looking at the current examples because we currently use it for:
- Ada, which I have defined to be `Decimal 6 "₳"`
- And conversion coefficients, which …
> SCP-2394 - Add choice format information to metadata and examples

- marlowe-playground-client/src/MetadataTab/View.purs
- marlowe-playground-client/static/css/panels.css
- web-common-marlowe/src/Marlowe/Extended/Metadata.purs
This PR adds choice format editing to the metadata editor:
Deployed to: http://pablo.marlowe.iohkdev.io/
- Branch
- PR
> SCP-2408 - Add choice format info editing to metadata editor

- plutus-core/untyped-plutus-core/src/UntypedPlutusCore/Evaluation/Machine/Cek/Internal.hs
This lets us match once on a known, tagged context value
instead of matching on an unknown list and then an unknown frame.
- Branch
- PR
> Make frames strict and have them include their own tail.

- plutus-core/plutus-core/src/PlutusCore/Name.hs
- plutus-core/untyped-plutus-core/src/UntypedPlutusCore/Evaluation/Machine/Cek/Internal.hs
Making the parameter patterns strict is crucial otherwise this is a
regression! Making the remaining occurence of `CekValEnv` strict is also
a regression, perhaps unsurprisingly.
- Branch
- PR
> SCP-2435: Use strict environments and make many uses of them strict

- marlowe-playground-client/src/Halogen/CurrencyInput.js
- marlowe-playground-client/src/Halogen/CurrencyInput.purs
- marlowe-playground-client/src/Pretty.purs
- marlowe-playground-client/src/SimulationPage/View.purs
- web-common-marlowe/src/Marlowe/Extended/Metadata.purs
This PR applies information about choice formatting to simulator (both in inputs and rendering of values).
As part of this PR, I have implemented a custom input component for decimal numbers, and I have also added it to other things that are not choices, because it seems to work much better than the default one.
Deployed to http://pablo.marlowe.iohkdev.io/
Just realised I need to add formatting to constant parameters too, but I will do that in a separate PR (SCP-2438)
- Branch
- PR
> SCP-2409 - Apply format info to simulator

- plutus-contract/src/Wallet/Emulator/Folds.hs
- plutus-contract/src/Wallet/Emulator/LogMessages.hs
- plutus-contract/src/Wallet/Emulator/MultiAgent.hs
- plutus-contract/src/Wallet/Emulator/Wallet.hs
- plutus-contract/test/Spec/Emulator.hs
https://github.com/input-output-hk/plutus/pull/3222 added validations to transactions in the Wallet Emulator that excluded invalid ones from being submitted to the chain, but `assertFailedTransactions` was only "listening" for transactions that have been submitted to the chain. This PR adds Validation Failed messages to the Wallet Emulator and updates `failedTransactions` to also "listen" for them to recover the previous behavior
Fixes https://github.com/input-output-hk/plutus/issues/3338
- Branch
- PR
> Fix assertFailedTransactions

- plutus-use-cases/scripts/Main.hs
- plutus-use-cases/src/Plutus/Contracts/Uniswap/OffChain.hs
- plutus-use-cases/src/Plutus/Contracts/Uniswap/Trace.hs
- plutus-use-cases/test/Spec/Auction.hs
- plutus-use-cases/test/Spec/Uniswap.hs
Fixed auction and uniswap trace not working in plutus-use-cases-scripts. They would wait for an infinite amount of slots when calling `observableState`. Basically fixed my adding a few `await` actions. Also, the auctioned token needs to be part of the initial emulator distribution.
- Branch
- PR
> SCP-2380: Fixed auction and uniswap trace in in plutus-use-cases-scripts

- plutus-contract/src/Plutus/Contract/Request.hs
- plutus-pab/src/Plutus/PAB/Core/ContractInstance.hs
We can only respond to the request if the request's slot range is in the past (some time for the chain index to update itself). `targetSlot` is the earliest time at which we can answer the request, so we may need to wait a little before we submit it.
This caused the marlowe follower contract to miss the past updates when it is first started.
- Branch
- PR
> SCP-2440: Fix an error with address change request

- marlowe-playground-client/src/SimulationPage/View.purs
- marlowe-playground-client/src/Simulator/Lenses.purs
- marlowe-playground-client/src/Simulator/State.purs
- marlowe-playground-client/src/Simulator/Types.purs
This PR add contract start and contract end to the simulator log
- Branch
- PR
> Add start and close events to the logs of the simulator

- scripts/ci-plutus-benchmark.sh
Run the 'cabal bench' commands in nix-shells to ensure that potentially
different haskell dependencies are being actually used.
--------
- Branch
- PR
> ci-plutus-benchmark: use separate nix-shells

- marlowe-playground-client/src/Home.purs
This small PR fixes the "open existing project" in the Marlowe playground home. It was opening the new project modal instead.
- Branch
- PR
> Fix “open project” button

- marlowe-dashboard-client/src/Template/View.purs
- marlowe-playground-client/src/MetadataTab/State.purs
- marlowe-playground-client/src/MetadataTab/Types.purs
- marlowe-playground-client/src/MetadataTab/View.purs
- marlowe-playground-client/src/Pretty.purs
- marlowe-playground-client/src/SimulationPage/View.purs
- marlowe-playground-client/src/StaticAnalysis/BottomPanel.purs
- marlowe-playground-client/static/css/panels.css
- web-common-marlowe/src/Examples/Metadata.purs
- web-common-marlowe/src/Marlowe/Extended/Metadata.purs
This PR essentially adds the formatting options to value template parameters in the same way as we added it for choices in SCP-2394, SCP-2408, and SCP-2409.
It also adds formatting to the errors when adding choices out of range (which was missing)
Probably easiest to look at the commits independently than the full diff at once
Deployed to: http://pablo.marlowe.iohkdev.io/
- Branch
- PR
> SCP-2438 - Add formatting to constant params

- marlowe-dashboard-client/src/Contract/View.purs
- marlowe-dashboard-client/src/Css.purs
- marlowe-dashboard-client/src/Dashboard/Lenses.purs
- marlowe-dashboard-client/src/Dashboard/State.purs
- marlowe-dashboard-client/src/Dashboard/Types.purs
- marlowe-dashboard-client/src/Dashboard/View.purs
- marlowe-dashboard-client/src/InputField/View.purs
- marlowe-dashboard-client/src/MainFrame/State.purs
- marlowe-dashboard-client/src/MainFrame/View.purs
- marlowe-dashboard-client/src/Template/View.purs
- marlowe-dashboard-client/src/Toast/View.purs
- marlowe-dashboard-client/src/WalletData/View.purs
- marlowe-dashboard-client/src/Welcome/Lenses.purs
- marlowe-dashboard-client/src/Welcome/State.purs
- marlowe-dashboard-client/src/Welcome/Types.purs
- marlowe-dashboard-client/src/Welcome/View.purs
- marlowe-dashboard-client/tailwind.config.js
I've tried to do as little as possible in this PR, to make things easier to review. The aim is to move things a step closer to the new designs by implementing the new sidebar card/modal, and putting things on that that were previously in separate screens. And also putting things that were on cards (notably the contract card) onto their own screens. On top of that, I did the minimum required to keep things basically functional - but the result is a lot of stuff looking a bit weird or ugly.
The next step(s), obviously, will be making all the component parts look pretty. As I do that, I'll also tidy up the names of the various view functions (some cards are still called screens here, and vice versa).
I don't think there's much point including screenshots (since I'd have to include loads). I …
> SCP-2447 - Implement outline of new designs.

- deployment/morph/machines/marlowe-dash.nix
- nix/modules/pab.nix
- plutus-contract/src/Plutus/Contract.hs
- plutus-contract/src/Plutus/Contract/Request.hs
- plutus-contract/src/Plutus/Trace/Effects/Waiting.hs
- plutus-contract/src/Plutus/Trace/Emulator.hs
- plutus-ledger-api/src/Plutus/V1/Ledger/Time.hs
- plutus-ledger/src/Data/Time/Units/Extra.hs
- plutus-ledger/src/Ledger/TimeSlot.hs
- plutus-ledger/test/Spec.hs
- plutus-pab-client/config.nix
- plutus-pab/src/Cardano/Node/Mock.hs
- plutus-pab/src/Cardano/Node/Server.hs
- plutus-pab/src/Cardano/Node/Types.hs
- plutus-use-cases/test/Spec/crowdfundingEmulatorTestOutput.txt
- plutus-use-cases/test/Spec/renderCrowdfunding.txt
- plutus-use-cases/test/Spec/renderVesting.txt
Slot configuration now represented by milliseconds instead of seconds. POSIXTime is also now in ms.
- Branch
- PR
> SCP-2398: Slot configuration now represented by milliseconds instead of seconds

- plutus-contract/src/Plutus/Contract/StateMachine.hs
we have nice function  `submitTxConstraintsWith` that allows to pass additional constraints and lookups.
It would be great to have the same counterpart for StateMachine.
* **problem**:
We have useful functions for SM transitions: `runStep` and `runInitialise`.
But I've found that they are often not enough because we want to supply additional constraints and lookups 
for transaction that relies on SM. For `runStep` we can make a workaround with `mkStep`, but for `runInitialise` there is no such way.
* **solution**:
With this PR we can define functions similar to `submitTxConstraintsWith` that allow SM-user to pass additional constraints and lookups. They are called `runStepWith`, `runInitialiseWith`.
> StateMachine step and initialise with additional constraints and lookups

- fake-pab/src/Server.hs
- marlowe-playground-client/src/SimulationPage/View.purs
- marlowe/src/Language/Marlowe/Client.hs
- marlowe/src/Language/Marlowe/Semantics.hs
- marlowe/src/Language/Marlowe/Util.hs
- web-common-marlowe/src/Marlowe/Semantics.purs
This PR extends the `Payment` type (part of the `TransactionOutput`) to include the account from which the payment is made, and changes `Party` to `Payee` so that it covers internal transfers as well.
I don't know what I'm doing with the Haskell side of things, so @nau and @palas please check that closely. :flushed:
> SCP-2415 - Extending payment type to include source account and transfers.

- nix/overlays/r.nix
It's deprecated and will disapper in upstream nixpkgs soon.
> Drop `lib` from `pkgs`.

- marlowe-dashboard-client/src/Contract/View.purs
- marlowe-playground-client/src/BlocklyComponent/State.purs
- marlowe-playground-client/src/BlocklyComponent/Types.purs
- marlowe-playground-client/src/BlocklyEditor/State.purs
- marlowe-playground-client/src/BlocklyEditor/Types.purs
- marlowe-playground-client/src/HaskellEditor/State.purs
- marlowe-playground-client/src/HaskellEditor/Types.purs
- marlowe-playground-client/src/JavascriptEditor/State.purs
- marlowe-playground-client/src/JavascriptEditor/Types.purs
- marlowe-playground-client/src/MainFrame/State.purs
- marlowe-playground-client/src/MainFrame/Types.purs
- marlowe-playground-client/src/MainFrame/View.purs
- marlowe-playground-client/src/Marlowe/Blockly.purs
- marlowe-playground-client/src/MarloweEditor/State.purs
- marlowe-playground-client/src/MarloweEditor/Types.purs
- marlowe-playground-client/src/Router.purs
- marlowe-playground-client/src/SimulationPage/State.purs
- marlowe-playground-client/src/SimulationPage/Types.purs
- marlowe-playground-client/src/SimulationPage/View.purs
- plutus-playground-client/src/Editor/State.purs
- web-common/src/Halogen/Extra.purs
- web-common/src/Halogen/Monaco.purs
- web-common/src/Web/DOM/ResizeObserver.js
This PR solves a long-standing issue in the playground where all the components were drawn at the same time even if they weren't in view. This issue was a blocker for adding the hints widget, as halogen requires the slots components id's to be unique, and if we reutilize a component in a different view it collides, resulting in weird errors.
Changes are deployed to https://hernan.marlowe.iohkdev.io/
- Branch
- PR
> SCP-2445: Make playground only draw the active page

- plutus-ledger-api/src/Plutus/V1/Ledger/Api.hs
- plutus-ledger-api/src/Plutus/V1/Ledger/Examples.hs
- plutus-ledger-api/src/Plutus/V1/Ledger/Interval.hs
My goal is to *only* expose `Plutus.V1.Ledger.Api` and
`Plutus.V1.Ledger.Examples`, which means they'd better export everything
the ledger uses.
Steps:
1. This PR
2. Update ledger to use this commit
3. Bump us to use new ledger
4. Remove access to other things (now that the ledger won't use them)
5. Update the ledger again
6. Update us again (optional)
- Branch
- PR
> Expand the exports of plutus-ledger-api to cover the needs of the ledger better

- marlowe-dashboard-client/src/Contract/View.purs
- marlowe-dashboard-client/src/Css.purs
- marlowe-dashboard-client/src/Dashboard/State.purs
- marlowe-dashboard-client/src/Humanize.purs
- marlowe-dashboard-client/src/InputField/State.purs
- marlowe-dashboard-client/src/InputField/Types.purs
- marlowe-dashboard-client/src/InputField/View.purs
- marlowe-dashboard-client/src/Template/Lenses.purs
- marlowe-dashboard-client/src/Template/State.purs
- marlowe-dashboard-client/src/Template/Types.purs
- marlowe-dashboard-client/src/Template/View.purs
- marlowe-dashboard-client/src/WalletData/View.purs
- marlowe-dashboard-client/src/Welcome/State.purs
- marlowe-dashboard-client/src/Welcome/View.purs
- web-common/src/Data/String/Extra.purs
I tried several things before settling on this solution, which I think is quite neat - some of the other things I tried were certainly a lot more complicated... :sweat_smile: Explanations of the various things are in the comments.
I've thrown in a dummy number input in the contract setup card, just for testing. Don't look too closely at the contract setup card itself, which continues to be visually broken - making that look like the new designs is the very next thing on my list.
Here's a screenshot showing the dummy number input (but you probably need to try it for yourself to get the full idea):
> SCP-2458: Extend InputField to include number inputs (using NumberFormat).

- nix/modules/pab.nix
- nix/pkgs/haskell/materialized-darwin/.plan.nix/plutus-pab.nix
- nix/pkgs/haskell/materialized-linux/.plan.nix/plutus-pab.nix
- plutus-pab/plutus-pab.cabal
- plutus-pab/plutus-pab.yaml.sample
- plutus-pab/src/Plutus/PAB/Types.hs
- plutus-pab/src/Plutus/PAB/Webserver/Server.hs
Adds a permissive CORS policy for the PAB.
It's configured in the yaml file like so:
```
pabWebserverConfig:
...
permissiveCorsPolicy: False
```
The `.sample` yaml file, and the nix pab vm-tests, sets it to `False` by default.
Fixes SCP-2421
----
Before:
```
> curl -I -X OPTIONS -H "Origin: http://example.com" -H 'Access-Control-Request-Method: GET' \
http://localhost:9080
HTTP/1.1 405 Method Not Allowed
Transfer-Encoding: chunked
Date: Wed, 07 Jul 2021 14:35:43 GMT
Server: Warp/3.3.16
Content-Type: text/plain
```
After:
```
> curl -I -X OPTIONS -H "Origin: http://example.com" -H 'Access-Control-Request-Method: GET' \
http://localhost:9080
HTTP/1.1 200 OK
Transfer-Encoding: chunked
Date: Wed, 07 Jul 2021 14:36:21 GMT
Server: Warp/3.3.16
Access-Control-Allow-Origin: * …
```
> permissive CORS policy for the pab

- marlowe-dashboard-client/src/Contract/Lenses.purs
- marlowe-dashboard-client/src/Contract/State.purs
- marlowe-dashboard-client/src/Contract/Types.purs
- marlowe-dashboard-client/src/Contract/View.purs
- marlowe-dashboard-client/src/Dashboard/State.purs
- marlowe-dashboard-client/src/Dashboard/Types.purs
- marlowe-dashboard-client/src/MainFrame/State.purs
- marlowe-dashboard-client/src/Marlowe/Execution/Lenses.purs
- marlowe-dashboard-client/src/Marlowe/Execution/State.purs
- marlowe-dashboard-client/src/Marlowe/Execution/Types.purs
This PR adds functionality to automatially redeem any payments made to the currently active wallet, so that the user doesn't have to worry about doing this manually. With these changes, the frontend app calls the "redeem" endpoint of the marlowe plutus app once for each payment made to the current wallet by a contract, every time we receive a notification that the state of that contract has changed (including when the wallet is first picked up, and we check the current state of all of its contracts). This means it will be called far too many times. If performance becomes an issue, we can revisit this - but I'm not sure what could be done about it anyway, for two reasons:
1. The most we could do is keep track of which payments have been redeemed in the browser, so duplicate requests will …
> Calling redeem for any payments a contract makes.

- playground-common/src/Schema.hs
- plutus-playground-client/src/MainFrame/State.purs
Fixed issue with POSIXTime in endpoint parameter. ToSchema POSIXTime now uses a number field. Also, added higher opening balances in playground.
- Branch
- PR
> Fixed issue with POSIXTime in endpoint parameter.

- marlowe-dashboard-client/plutus-pab.yaml
#3507 added a new parameter to the pab config, so the `plutus-pab.yaml` file in `marlowe-dashboard-client` needs updating to include it. (This is only needed for local development, but needed nonetheless.)
Going to go ahead and merge without review, because there's really nothing to it. But also going to flag @silky - just so you know, for future reference.
> Adding new necessary property to pab config.

- nix/tests/vm-tests/marlowe-playground.nix
- nix/tests/vm-tests/plutus-playground.nix
Disable the tests that verify the config reload mechanism.
For reasons unknown this test has always been unstable when executed on
hydra. Considering the fact that this setup will soon be replaced
(because of a move to bitte deployments) and the time i have already
spent on replicating any of the hydra-failures locally *and* the fact
that so far i haven't noticed any problems with the actual behavior
being tested in production it seems like the most sensible decision to
actually remove these asserts.
----
- Branch
- PR
> Remove unstable playground vm tests

- marlowe-playground-client/src/Blockly/Internal.js
- marlowe-playground-client/src/Blockly/Internal.purs
- marlowe-playground-client/src/Blockly/Types.purs
- marlowe-playground-client/src/BlocklyComponent/State.purs
- marlowe-playground-client/src/Halogen/ActusBlockly.purs
- marlowe-playground-client/src/Marlowe/ActusBlockly.purs
- marlowe-playground-client/src/Marlowe/Blockly.purs
- marlowe-playground-client/test/Blockly/Headless.purs
This PR fixes a problem in the BlocklyActus component were the BaseContract type was not appearing.
The main functionality still needs some work as now we have the following response from the BE
```
ACTUS Term Validation Failed:
Missing required term: At least one of the conditional terms in group ["cycle anchor date of fee","cycle of fee"] must be defined when fee rate is defined for contract type 'PAM'
Missing required term: Contract term 'nominal interest rate' is required for contract type 'PAM'
Missing required term: At least one of the conditional terms in group ["cycle anchor date of scaling index","cycle of scaling index"] must be defined when scaling effect is defined for contract type 'PAM'
Missing required term: The unconditional terms ["cycle anchor date of rate reset","cycle …
```
> Marlowe Playground Client: Fix actus main block type dissapear

- web-common-plutus/src/Chain/Types.purs
but different output index.
Fixes #3487
The issue was that inputs with different output index but same txid were wrongly being marked as unspent given that the check was only comparing against the first matching txid regardless of output index. This pr fixes this.
- Branch
- PR
> Fix findConsumptionPoint for inputs with same txid

- plutus-use-cases/src/Plutus/Contracts/Uniswap/OffChain.hs
- plutus-use-cases/src/Plutus/Contracts/Uniswap/Trace.hs
The emulator can't get the observable states for contract instances that have stopped, that's why we have the waiting actions at the end of some of the uniswap contracts. This PR fixes the problem that `plutus-use-cases-scripts` hangs when it gets to the uniswap examples, by increasing the timeouts.
A better solution would be to change the emulator so that it can answer requests for the observable state even after the instance has finished. I'll add a ticket for that to Jira.
- Branch
- PR
> Increase some waiting times for the uniswap traces

- plutus-tx/src/PlutusTx/Ratio.hs
- plutus-tx/test/Spec.hs
recip should not produce a number with a negative denominator because this will mess with the ordering relation, violating the law tested in reciprocal ordering 3, one of the tests added by this commit.
> recip should not produce a number with a negative denominator

- nix/lib/haddock-combine.nix
Fixes https://github.com/input-output-hk/plutus/issues/3541
locally for chromium based browsers. This patch can be dropped once
haddock is > 2.24.0.
based on https://github.com/haskell/haddock/pull/1235
This can be tested locally using:
```sh
nix-shell
build-and-serve-docs
```
- Branch
- PR
> docs: Fix quick-jump.css search scroll

- marlowe-dashboard-client/src/Capability/Marlowe.purs
- marlowe-dashboard-client/src/Contract/State.purs
- marlowe-dashboard-client/src/Contract/View.purs
- marlowe-dashboard-client/src/Css.purs
- marlowe-dashboard-client/src/Dashboard/View.purs
- marlowe-dashboard-client/src/LoadingSubmitButton/Lenses.purs
- marlowe-dashboard-client/src/LoadingSubmitButton/State.purs
- marlowe-dashboard-client/src/LoadingSubmitButton/Types.purs
- marlowe-dashboard-client/src/LoadingSubmitButton/View.purs
- marlowe-dashboard-client/src/MainFrame/Types.purs
- marlowe-dashboard-client/src/Toast/State.purs
- marlowe-dashboard-client/src/Welcome/State.purs
- marlowe-dashboard-client/static/css/main.css
- marlowe-dashboard-client/tailwind.config.js
- plutus-pab-client/spago-packages.nix
- plutus-pab-client/spago.dhall
- plutus-playground-client/spago-packages.nix
- plutus-playground-client/spago.dhall
- web-common/src/Halogen/Animation.js
- web-common/src/Halogen/Animation.purs
This PR adds a new submit button that has a loading/success/error animation.
Deployed to https://hernan.marlowe-dash.iohkdev.io/
- Branch
- PR
> SCP-2446: Marlowe Dashboard: Add LoadingSubmit button with animation

- nix/pkgs/haskell/materialized-darwin/.plan.nix/plutus-use-cases.nix
- nix/pkgs/haskell/materialized-linux/.plan.nix/plutus-use-cases.nix
- plutus-contract/src/Plutus/Contract/CardanoAPI.hs
- plutus-contract/src/Wallet/Emulator/Folds.hs
- plutus-contract/src/Wallet/Emulator/LogMessages.hs
- plutus-use-cases/plutus-use-cases.cabal
- plutus-use-cases/scripts/Main.hs
* Extend the `plutus-use-cases-scripts` program to also print out some partial transactions (if desired)
* The partial transactions are produced in two different formats: JSON (from our `UnbalancedTx` type) and CBOR (using a new `ExportTx` type).
* The CBOR serialisation isn't working yet. One reason is that address hashes in the emulator are 32 bytes, but in the network they are 28 bytes
* Sorting this out should be done in a separate PR.
- Branch
- PR
> SCP-2484: Extend plutus-use-cases-scripts to produce partial txns

- marlowe-playground-client/src/Marlowe/ViewPartials.purs
- marlowe-playground-client/src/SimulationPage/BottomPanel.purs
- marlowe-playground-client/src/SimulationPage/Types.purs
- marlowe-playground-client/src/SimulationPage/View.purs
- marlowe-playground-client/src/Simulator/State.purs
- marlowe-playground-client/src/StaticAnalysis/BottomPanel.purs
This PR adds warnings and errors to the Marlowe Playground simulator.
NOTE: I wasn't sure how to explain to an end-user the possible Errors (and not sure how to reach that point). @palas, I appreciate your input in that regard. 
Changes are deployed to https://hernan.marlowe.iohkdev.io/
- Branch
- PR
> SCP-1759: Marlowe playground Client - Add warnings and errors tab to the simulation

- marlowe-dashboard-client/src/Bridge.purs
- marlowe-dashboard-client/src/Contract/Lenses.purs
- marlowe-dashboard-client/src/Contract/State.purs
- marlowe-dashboard-client/src/Contract/Types.purs
- marlowe-dashboard-client/src/Contract/View.purs
- marlowe-dashboard-client/src/Css.purs
- marlowe-dashboard-client/src/Dashboard/Lenses.purs
- marlowe-dashboard-client/src/Dashboard/State.purs
- marlowe-dashboard-client/src/Dashboard/Types.purs
- marlowe-dashboard-client/src/Dashboard/View.purs
- marlowe-dashboard-client/src/Humanize.purs
- marlowe-dashboard-client/src/Template/View.purs
- marlowe-dashboard-client/tailwind.config.js
- web-common/src/Material/Icons.purs
- web-common/src/Tooltip/View.purs
- web-common/static/icons.css
This implements the new designs for the dashboard, with the contract summary cards including the actions possible at the current step. I haven't changed the style of the actions themselves, since that change also applies to the current step card on the contract screen - and I'll attack the contract screen in the next PR. This PR already feels quite big enough, especially the diff of the Contract.View module.
Until now, the `selectedContractIndex` in the `Dashboard.State` was doing two things: determining which contract screen was visible, and also which contract any `Contract.Action` applied to. In the new designs, a `Contract.Action` for any contract can be called from the dashboard, without the need to first go into the screen for that contract, so these two things needed to come apart. …
> SCP-2092: Implement new design of contract cards.

- marlowe-playground-client/src/MainFrame/State.purs
- marlowe-playground-client/src/Marlowe/Gists.purs
This small PR solves a bug where the blockly project was saved with Marlowe format into an XML file. Now Blockly and Marlowe uses the same file, so if you save a Marlowe project you can open it as Blockly and vice-versa.
- Branch
- PR
> SCP-2451 - Marlowe Playground Client - Fix save a blockly project

- playground-common/src/PSGenerator/Common.hs
Fixes #3563
- Fix purescript decoding for `Datum` and `Redeemer` matching with the encoding in haskell
Fixup from aeson instance changes in #3539
- Fix purescript decoding for `ExBudget` by treating it as json. The haskell side is not using the generic aeson instance which is what the generated purescript expects. This is ok as the value is not used in the playground and maintains consistency in hs. Also fixed purescript decoding for `SatInt`
Fixup bridges from #3502
- Branch
- PR
> Fix playground decoding errors

- ci.nix
- default.nix
- plutus-use-cases/ARCHITECTURE.adoc
- plutus-use-cases/default.nix
- plutus-use-cases/scripts/Main.hs
plutus-use-cases-scripts is now run during Hydra CI and the result is available for download from Hydra.
- Branch
- PR
> SCP-2512: plutus-use-cases-scripts is now run during Hydra CI

- marlowe-dashboard-client/src/Marlowe/Execution/State.purs
- marlowe/src/Language/Marlowe/Analysis/FSSemantics.hs
- marlowe/src/Language/Marlowe/Client.hs
- marlowe/src/Language/Marlowe/Semantics.hs
- web-common-marlowe/src/Marlowe/Semantics.purs
This PR removes the need for comparing the type `Contract` (using the `Eq` instance), which hopefully should translate into a smaller and faster validator for Marlowe.
This covers the semantics of Marlowe in Haskel/Plutus and Purescript
- Branch
- PR
> SCP-2500 - Remove need for Eq instance for `Contract` in Marlowe semantics

- marlowe-dashboard-client/package-lock.json
- marlowe-dashboard-client/package.json
- marlowe-dashboard-client/src/Contract/View.purs
- marlowe-dashboard-client/src/Dashboard/View.purs
- marlowe-dashboard-client/tailwind.config.js
- web-common/src/Halogen/Extra.purs
- web-common/src/Material/Icons.purs
This PR makes the first part in the contract screen redesign:
Things to note:
* When it comes to deposits the design makes a distinction between accounts and wallet, but I'm not sure if we have this information. I think we can assume that deposits always comes from "wallet -> account", but we'll have to see when we do the transaction summary if we can always tell.
* In the choice input we don't have access to the original choice bounds, so I cant use the same hack that I used for the singleChoice and sadly the input reads "1 for Report problem" etc. 
* There is a bug with lifeCycleEvent that prevents tooltips and other halogen components from rendering
* I've changed box-shadow to drop-shadow in the step cards and now the top right corner doesn't have the "shadow artifact" 🎉
Pre-submit …
> SCP-2334 - Marlowe Dashboard - implement new design of contract screen part 1

- plutus-ledger-api/src/Plutus/V1/Ledger/Interval.hs
There was an incorrect documentation for the `to` function of `Interval`. The upper bound is inclusive.
```
> member 20 (to (20 :: Integer))
True
```
- Branch
- PR
> Fix documentation of Interval to (upper bound included)

- marlowe-dashboard-client/src/Template/State.purs
I broke the way slot resolution works in #3578. Or possibly it was already broken, but the bug was masked by the fact that we were pre-filling slot parameters before instantiating contracts. Either way, this fixes it. The code is probably self-explanatory - basically the resolution was being done too soon (before filling the contract with the parameters).
> Fixing resolution of slots from relative to absolute.

- marlowe-playground-client/src/Examples/JS/Contracts.purs
- marlowe-playground-server/contracts/ContractForDifferences.hs
- marlowe-playground-server/contracts/ContractForDifferencesWithOracle.hs
- web-common-marlowe/src/Examples/PureScript/ContractForDifferences.purs
- web-common-marlowe/src/Examples/PureScript/ContractForDifferencesWithOracle.purs
This PR modifies the contract for differences examples logic to support two different commitments (it removes assumptions on the amounts committed). So far this is just a refactoring, I will make some of the parameters part of the template in a separate PR (when metadata is clear)
Deployed to `pablo` environment
- Branch
- PR
> SCP-2535 - Update contract for differences examples to support two different commitments

- marlowe-dashboard-client/src/Contract/View.purs
- marlowe-dashboard-client/src/MainFrame/Types.purs
- web-common/src/Halogen/Extra.purs
This PR fixes a bug with the lifeCycle property that prevented tooltips from appearing in certain scenarios.
- Branch
- PR
> SCP-2546 - Web Commons - Fix lifecycle event

- plutus-contract/src/Plutus/Trace/Emulator/ContractInstance.hs
- plutus-contract/test/Spec/Contract.hs
- plutus-use-cases/scripts/Main.hs
- plutus-use-cases/src/Plutus/Contracts/Uniswap/OffChain.hs
- plutus-use-cases/src/Plutus/Contracts/Uniswap/Trace.hs
- plutus-use-cases/src/Plutus/Contracts/Vesting.hs
Emulator can answer observable state queries even after a contract instance has stopped.
- Branch
- PR
> SCP-2491: Emulator can answer observable state queries even after a contract instance has stopped

- nix/tests/vm-tests/web-ghc.nix
- plutus-ledger/src/Ledger/Index.hs
- plutus-use-cases/default.nix
- plutus-use-cases/scripts/Main.hs
Add a flag `--unapplied-validators|-u` that, when set, causes the program to write out the unapplied validator scripts. If the flag is not set, fully applied validators are produced.
- Branch
- PR
> use-cases-scripts: Extract unapplied validators

- playground-common/src/PSGenerator/Common.hs
- plutus-contract/src/Plutus/Contract/Effects.hs
- plutus-contract/src/Plutus/Contract/Request.hs
- plutus-contract/src/Plutus/Contract/Trace.hs
- plutus-contract/src/Plutus/Contract/Trace/RequestHandler.hs
- plutus-contract/src/Plutus/Trace/Emulator/ContractInstance.hs
- plutus-contract/src/Wallet/Effects.hs
- plutus-contract/src/Wallet/Emulator/ChainIndex.hs
- plutus-pab-client/src/View/Pretty.purs
- plutus-pab/src/Cardano/ChainIndex/API.hs
- plutus-pab/src/Cardano/ChainIndex/Client.hs
- plutus-pab/src/Cardano/ChainIndex/Server.hs
- plutus-pab/src/Plutus/PAB/Arbitrary.hs
- plutus-pab/src/Plutus/PAB/Core.hs
- plutus-pab/src/Plutus/PAB/Core/ContractInstance.hs
- plutus-pab/src/Plutus/PAB/Core/ContractInstance/BlockchainEnv.hs
- plutus-pab/src/Plutus/PAB/Core/ContractInstance/STM.hs
- plutus-pab/src/Plutus/PAB/Run/PSGenerator.hs
- plutus-pab/src/Plutus/PAB/Simulator.hs
Change "awaitTxConfirmed" to "awaitTxStatusChange". The `TxStatus` type reflects the different degrees of confirmation that transactions can have.
* When handling `AwaitTxStatusChangeReq` in the emulator, we previously queried the chain index every time to see if the transaction had been added to it. I changed `Plutus.Trace.Emulator.ContractInstance.runInstance` to "push" notifications about new blocks to the threads instead. This is much closer to the way `AwaitTxStatusChangeReq` is handled in the PAB, and it allows us to get rid of one of the constructors of the old chain index effect.
* The emulator still doesn't support rollbacks, so all transactions are immediately committed.
- Branch
- PR
> SCP-2569: Await tx status change

- marlowe-playground-client/src/StaticAnalysis/StaticTools.purs
- marlowe-playground-client/webpack.config.js
- marlowe-symbolic/src/Marlowe/Symbolic/Server.hs
Moves the static analysis endpoint so that it is under `/api`
Deployed to http://pablo.marlowe.iohkdev.io/
- Branch
- PR
> SCP-2575 - Move static analysis end-point to /api/*

- marlowe-playground-client/src/BlocklyEditor/State.purs
This PR solves an issue introduced by [PR-3478](https://github.com/input-output-hk/plutus/pull/3478) in which when we create and modify a marlowe/blockly project and then create a new blockly project, instead of getting a clean project, we started with the previous code. 
- Branch
- PR
> SCP-2587 - Marlowe Playground Client - Fix new blockly project

- scripts/ci-plutus-benchmark.sh
**Summary**:
Update origin before figuring out the branch to compare to via `git merge-base`.
**Details**
@kwxm described some weird behavior with the benchmarking picking revisions that seemingly make no sense. I _think_ the issue was with not comparing with a recent revision of `master`. Hence this PR adds a `git fetch origin` in combination with using `git merge-base HEAD origin/master`.
----
- Branch
- PR
> ci-plutus-benchmark: Update origin

- plutus-core/plutus-ir/src/PlutusIR/Compiler.hs
- plutus-core/plutus-ir/src/PlutusIR/Compiler/Types.hs
- plutus-core/plutus-ir/src/PlutusIR/Transform/LetFloat.hs
- plutus-core/plutus-ir/test/transform/letFloat/listMatch.golden
- plutus-core/plutus-ir/test/transform/letFloat/mutuallyRecursiveValues.golden
This came up in my other branch, but was clearly pre-existing (we even had a wrong testcase!). I think this is a reasonable fix, but @bezirg should think about it when he's back.
Fortunately, this case doesn't come up that often in practice! 
I also added a paranoid typechecking mode like "core lint" in GHC, that runs the typechecker after every stage. This is helpful for debugging. I had to stop after recursive binding elimination since we apparently generate a wrong type signature somewhere, which is concerning even though apparently it somehow sorts itself out by the time we get to PLC typechecking...
- Branch
- PR
> SCP-2590: Fix a bug in the let-floater

- marlowe-dashboard-client/src/Contract/Lenses.purs
- marlowe-dashboard-client/src/Contract/State.purs
- marlowe-dashboard-client/src/Contract/Types.purs
- marlowe-dashboard-client/src/Contract/View.purs
- marlowe-dashboard-client/src/Humanize.purs
- web-common/src/Material/Icons.purs
- web-common/src/Tooltip/State.purs
- web-common/static/icons.css
This PR adds a tooltip to the past actions card with the timezone information and includes an initial version of the transaction/payment summary.
While I was implementing this feature, I discovered a bug in the balance tab of the simple escrow example. When the buyer deposits and chooses to report a problem, there is a payment from the Sellers account to the Buyers account (which is shown by the new payment summary). But in the balances tab the money is removed from the Sellers account but is not added to the Buyers.
- Branch
- PR
> SCP-2545 - Marlowe Run Client - Implement transaction summary

- plutus-pab-client/default.nix
- plutus-pab/src/Plutus/PAB/Effects/DbStore.hs
- plutus-pab/src/Plutus/PAB/Run.hs
- plutus-pab/src/Plutus/PAB/Run/Cli.hs
- plutus-pab/src/Plutus/PAB/Types.hs
- shell.nix
Execute `migrate` command before starting dev servers and better logging
* Execute the `migrate` command which creates the database file before launching the `PAB` dev servers.
* Read the db file from the `YAML` file using `yq` when launching `PAB` dev servers
* Log an error message when we get `no such table: instances` when running `runBeamSqliteDebug` in the `PAB`
Here's the log output when running the `PAB` without running the `migrate` command first:
```
$ cabal run plutus-pab:exe:plutus-pab-examples -- --config plutus-pab/plutus-pab.yaml all-servers
Starting: MockNode WithMockServer
Started: MockNode WithMockServer
[pab:Info:13] [2021-07-29 22:08:38.59 UTC] Starting slot coordination thread. Initial slot time: 2020-06-07T21:44:51Z Slot length: 1000ms
[pab:Info:13] [2021-07-29 …
```
> SCP-2580: Execute migrate command before starting dev servers and better logging

- CONTRIBUTING.adoc
- shell.nix
Nix 2.4pre is unstable and segfaults often.
- Branch
- PR
> Hide flake-enabled Nix behind an alias.

- nix/modules/pab.nix
- plutus-pab-client/default.nix
- plutus-pab-client/pab-demo-scripts.nix
- plutus-pab/app/CommandParser.hs
- plutus-pab/app/Main.hs
- plutus-pab/src/Plutus/PAB/Run/Cli.hs
- plutus-pab/src/Plutus/PAB/Run/Command.hs
- plutus-pab/src/Plutus/PAB/Run/CommandParser.hs
- plutus-pab/src/Plutus/PAB/Types.hs
Modified the migrate command in plutus-pab to use the database filepath from the config file instead of the CLI.
- Branch
- PR
> SCP-2600: Modified the migrate command in PAB

- nix/pkgs/haskell/materialized-darwin/.plan.nix/playground-common.nix
- nix/pkgs/haskell/materialized-darwin/.plan.nix/plutus-chain-index.nix
- nix/pkgs/haskell/materialized-linux/.plan.nix/playground-common.nix
- nix/pkgs/haskell/materialized-linux/.plan.nix/plutus-chain-index.nix
- playground-common/playground-common.cabal
- playground-common/src/PSGenerator/Common.hs
- plutus-chain-index/plutus-chain-index.cabal
- plutus-chain-index/src/Plutus/ChainIndex/Tx.hs
- plutus-chain-index/src/Plutus/ChainIndex/Types.hs
- plutus-contract/src/Plutus/Contract/Effects.hs
- plutus-ledger/src/Ledger/Blockchain.hs
- plutus-ledger/src/Ledger/Constraints/OffChain.hs
- plutus-pab-client/src/View/Pretty.purs
Defined a effect types for chain index queries and responses in plutus-contract. These effects mirror the effects in the module `Plutus.ChainIndex.Effects.ChainIndexQueryEffect`. Now it is possible to make a `PABReq` to the chain index.
Added a lot of pretty instances which can probably be improved in the future.
@raduom FYI since you're also working on the chain index
- Branch
- PR
> SCP-2565: Define chain index query effect types in plutus-contract

- plutus-report/ledger.tex
- plutus-report/scripting.tex
This fixes a small typo in the ledger documentation.
- Branch
- PR
> no-op: fix typos in technical documentation

- plutus-pab/src/Plutus/PAB/Core/ContractInstance.hs
- plutus-pab/src/Plutus/PAB/Effects/Contract.hs
- plutus-pab/src/Plutus/PAB/Effects/Contract/Builtin.hs
- plutus-pab/src/Plutus/PAB/Events.hs
- plutus-pab/src/Plutus/PAB/Events/ContractInstanceState.hs
- plutus-pab/src/Plutus/PAB/Monitoring/PABLogMsg.hs
in order to minimize mismatches similar to the one on https://github.com/input-output-hk/plutus/pull/3628/commits/83a1f3908117ce2e75bd403bdea7f0f574d722eb #3628 
- Branch
- PR
> ContractResponse: enforce PABResp with PABReq

- .gitignore
- marlowe-dashboard-client/plutus-pab.yaml
- nix/modules/pab.nix
- nix/pkgs/haskell/materialized-darwin/.plan.nix/plutus-pab.nix
- nix/pkgs/haskell/materialized-linux/.plan.nix/plutus-pab.nix
- plutus-pab-client/config.nix
- plutus-pab/examples/ContractExample.hs
- plutus-pab/examples/ContractExample/WaitForTx.hs
- plutus-pab/plutus-pab.cabal
- plutus-pab/plutus-pab.yaml.sample
- plutus-pab/src/Cardano/Node/Client.hs
- plutus-pab/src/Cardano/Node/Server.hs
- plutus-pab/src/Cardano/Node/Types.hs
- plutus-pab/src/Cardano/Protocol/Socket/Client.hs
- plutus-pab/src/Cardano/Wallet/Mock.hs
- plutus-pab/src/Cardano/Wallet/Server.hs
- plutus-pab/src/Plutus/PAB/App.hs
- plutus-pab/src/Plutus/PAB/Core/ContractInstance/BlockchainEnv.hs
- plutus-pab/src/Plutus/PAB/Monitoring/PABLogMsg.hs
- plutus-pab/src/Plutus/PAB/Run/Cli.hs
- plutus-pab/src/Plutus/PAB/Run/Command.hs
- plutus-pab/src/Plutus/PAB/Run/CommandParser.hs
- plutus-pab/src/Plutus/PAB/Simulator.hs
- plutus-pab/sync-client/Main.hs
- plutus-pab/test-node/activate-contract.sh
- plutus-pab/test-node/activation.json
- plutus-pab/test/full/Plutus/PAB/CliSpec.hs
- plutus-pab/tx-inject/config.yaml
The main change is in `Plutus.PAB.Core.ContractInstance.BlockchainEnv`:
* Add a `NodeMode` argument
* Use the "real" chain sync client when `AlonzoNode` is specified
* Update the set of validated transactions when a new block is received
Other changes:
* Add `mscNodeMode :: NodeMode` to the node config. If it is set to `AlonzoNode` then the mock node is not started at all.
* Configurable network ID
* Add a `TxId` parameter to the `WaitForTx` example.
I tested this against a local test-net node.
- Branch
- PR
> SCP-2404: PAB updates its internal state with txns from Alonzo node

- nix/pkgs/haskell/materialized-darwin/.plan.nix/plutus-ledger-api.nix
- nix/pkgs/haskell/materialized-darwin/default.nix
- nix/pkgs/haskell/materialized-linux/.plan.nix/plutus-ledger-api.nix
- nix/pkgs/haskell/materialized-linux/default.nix
- plutus-ledger-api/plutus-ledger-api.cabal
- plutus-ledger-api/src/Plutus/V1/Ledger/Scripts.hs
- plutus-use-cases/scripts/Main.hs
- plutus-use-cases/test/Spec/crowdfundingEmulatorTestOutput.txt
- plutus-use-cases/test/Spec/renderCrowdfunding.txt
- plutus-use-cases/test/Spec/renderGuess.txt
- plutus-use-cases/test/Spec/renderVesting.txt
Simple enough to implement, I'm still unsure if we should pull the trigger.
I made `plutus-use-cases` scripts dump out both formats, both the ASTs in flat and the scripts in our odd combination of nested flat+z+cbor (hence the unwieldy filed extension). I think it's worth having both, since we can continue to use the simple flat ASTs for evaluator benchmarking.
- Branch
- PR
> SCP-2605: Add compression to script serialization

- nix/pkgs/haskell/materialized-darwin/.plan.nix/plutus-core.nix
- nix/pkgs/haskell/materialized-darwin/default.nix
- nix/pkgs/haskell/materialized-linux/.plan.nix/plutus-core.nix
- nix/pkgs/haskell/materialized-linux/default.nix
- plutus-core/executables/pir/Main.hs
- plutus-core/executables/pir/README.md
- plutus-core/plutus-core.cabal
- plutus-core/plutus-ir/src/PlutusIR/Core/Instance.hs
- plutus-core/plutus-ir/src/PlutusIR/Core/Instance/Flat.hs
- plutus-core/plutus-ir/src/PlutusIR/Core/Type.hs
- plutus-tx-plugin/src/PlutusTx/Plugin.hs
- plutus-tx-plugin/test/Plugin/Basic/Spec.hs
- Move flat instances for PlutusIR to PlutusIR.Core.Instance.Flat,
- Change dump-pir option to dump binary PlutusIR representation, and
- Add a small cli tool for loading and compiling binary PlutusIR files.
- Branch
- PR
> Add dumping flat pir

- plutus-contract/src/Plutus/Contract.hs
- plutus-contract/src/Plutus/Contract/Resumable.hs
- plutus-contract/src/Plutus/Contract/Types.hs
This was deliberately left out in earlier versions, to avoid users accidentally writing `Contract`s that get stuck. But now that we have the promise API we should put it back in because it's convenient and the risk of suprises is lower. What do you think @sjoerdvisscher ?
- Branch
- PR
> Add 'never' promise

- flake.lock
- flake.nix
- nix/default.nix
- nix/overlays/nixpkgs-overrides.nix
- nix/pkgs/default.nix
This updates nixpkgs to the nixpkgs-unstable pin used by haskell.nix.
This will help to get windows cross compilation working #3430 (there is an issue with mingw or wine in the older version that causes GHC builds to fail).
- Branch
- PR
> Update to a more recent nixpkgs

- default.nix
- deployment/shell.nix
- flake.lock
- flake.nix
- nix/tests/default.nix
The latest terraform breaks our workflow, and this terraform
deployment will be going away soon so not worth fixing the workflow.
nixpkgs update needed to bring in NixOS/nixpkgs#127239
Also update haskell.nix since we're rebuilding anyway.
> Deployment: Pin to terraform 0.12. 

- plutus-core/plutus-core/src/PlutusCore/Default/Builtins.hs
Use `decodeUtf8'` instead.
---
- Branch
- PR
> Make decodeUtf8 builtin safe.

- cabal.project
- nix/pkgs/haskell/haskell.nix
Currently, flat uses `decodeUtf8` in its instance for `Text`. We now
rely on this for our string literals. The upshot of this is that if a
malicious user submitted a program with invalid UTF8 data in a string
literal, flat would throw an exception (which we wouldn't catch) and
which would presumably then wreak some havoc elsewhere.
Fortunately, it's an easy fix (and the maintainer has taken our patches
before), so I fixed it upstream. For now, I've pointed this to my PR
branch, but hopefully it will get merged before too long (and I might
ask for a Hackage release).
- Branch
- PR
> Use flat with safe UTF decoding

- marlowe/src/Language/Marlowe/Client.hs
- plutus-contract/src/Plutus/Contract.hs
- plutus-contract/src/Plutus/Contract/Effects.hs
- plutus-contract/src/Plutus/Contract/Request.hs
- plutus-contract/src/Plutus/Contract/StateMachine.hs
- plutus-contract/src/Plutus/Trace/Emulator/ContractInstance.hs
- plutus-contract/test/Spec/Contract.hs
- plutus-ledger/src/Ledger/Blockchain.hs
- plutus-pab-client/src/View/Pretty.purs
- plutus-pab/src/Plutus/PAB/App.hs
- plutus-pab/src/Plutus/PAB/Core/ContractInstance.hs
- plutus-pab/src/Plutus/PAB/Core/ContractInstance/BlockchainEnv.hs
- plutus-pab/src/Plutus/PAB/Core/ContractInstance/STM.hs
- plutus-pab/src/Plutus/PAB/Simulator.hs
- plutus-pab/test/full/Spec.hs
- plutus-use-cases/src/Plutus/Contracts/Auction.hs
- plutus-use-cases/src/Plutus/Contracts/PingPong.hs
- plutus-use-cases/src/Plutus/Contracts/Stablecoin.hs
- plutus-use-cases/test/Spec/multisigStateMachine.pir
* Add `awaitUtxoSpent` and `awaitUtxoProduced` requests to `Plutus.Contract.Request`
* The two requests can be handled efficiently by the PAB
* Replace most uses of `addressChangeRequest` with the new requests
* The biggest change happened in the state machine client, where `waitForUpdate` etc now don't need to call `addressChangeRequest` once every slot
* The last remaining use of `waitForUpdate` is in `marloweFollowContract`. The follow contract needs to know every single transaction that interacted with the marlowe contract, instead of just the last one. I asked @nau why this is necessary and if there was a way around it
* Extend `Plutus.Contract.StateMachine.waitForUpdateTimeout`:
* The `WaitingResult` type now informs about the kind of transition that happend
* `OnChainState` is a …
> SCP-2460: Wait for address changed without polling

- nix/pkgs/haskell/materialized-darwin/.plan.nix/plutus-tx.nix
- nix/pkgs/haskell/materialized-linux/.plan.nix/plutus-tx.nix
- plutus-core/plutus-core/src/PlutusCore/Default/Builtins.hs
- plutus-core/untyped-plutus-core/test/Evaluation/Builtins/Definition.hs
- plutus-tx/plutus-tx.cabal
- plutus-tx/src/PlutusTx/Builtins.hs
- plutus-tx/src/PlutusTx/Builtins/Internal.hs
- plutus-tx/src/PlutusTx/Prelude.hs
- plutus-tx/test/Spec.hs
@bezirg noticed yesterday that our `sliceByteString` differs from slice operations in other languages:
```
python: "hello world"[0:1] == java's "hello world".substring(0,1) == javascript  "hello world".slice(0,1) == "h"
```
While in Plutus we do `"hello world".slice(0,1) == "he"` which is incorrect.
- This PR changes the behaviour to the same as in `slice` from `vector` package.
- Add tests.
---
- Branch
- PR
> Fix slice bytestring and add builtin tests

- plutus-tx-plugin/src/PlutusTx/Compiler/Expr.hs
- plutus-tx-plugin/src/PlutusTx/Compiler/Type.hs
- plutus-tx-plugin/test/Plugin/Errors/Spec.hs
- plutus-tx-plugin/test/Plugin/Errors/stringLiteral.plc.golden
I was just looking in here and I realised that all this is redundant,
now we're only ever working with overloaded string literals. Thank
goodness!
I also merged a few pattern matches to simplify the big case expression
a bit.
- Branch
- PR
> Remove some redundant handling of literals

- cabal.project
- flake.lock
- flake.nix
- nix/pkgs/haskell/agda.sha
- nix/pkgs/haskell/cabal-install.sha
- nix/pkgs/haskell/cardano-repo-tool.sha
- nix/pkgs/haskell/hlint.sha
- nix/pkgs/haskell/hls-darwin.sha
- nix/pkgs/haskell/hls-linux.sha
- nix/pkgs/haskell/materialized-darwin/default.nix
- nix/pkgs/haskell/materialized-linux/default.nix
- nix/pkgs/haskell/stylish-haskell.sha
After:
```
result/bin/cabal build all --dry-run  12.06s user 1.20s system 72% cpu 18.296 total
```
I also updated some other minor things and the hackage index, if I'm going to get hydra to do some work.
- Branch
- PR
> Bump haskell.nix for the dependency resolution speed fixes

- plutus-core/plutus-core/src/PlutusCore/Data.hs
- plutus-core/plutus-core/src/PlutusCore/Evaluation/Machine/ExMemory.hs
The `ExMemoryUsage` instance for `Data` just counted the number of nodes, but that's not ideal for `equalsData`, which uses `==.  This extends the instance to take account of the size of the contents of the nodes, which should be better, if not ideal.
- Branch
- PR
> A better (?) ExMemoryUsage instance for Data

- nix/pkgs/haskell/materialized-darwin/.plan.nix/plutus-core.nix
- nix/pkgs/haskell/materialized-linux/.plan.nix/plutus-core.nix
- plutus-core/plutus-core.cabal
- plutus-core/plutus-ir/src/PlutusIR/Compiler.hs
- plutus-core/plutus-ir/src/PlutusIR/Transform/LetFloat.hs
- plutus-core/plutus-ir/src/PlutusIR/Transform/LetMerge.hs
- plutus-core/plutus-ir/test/TransformSpec.hs
- plutus-core/plutus-ir/test/recursion/even3.golden
- plutus-core/plutus-ir/test/recursion/stupidZero.golden
- plutus-core/plutus-ir/test/transform/letFloat/even3Eval.golden
- plutus-core/plutus-ir/test/transform/letFloat/nonrec2.golden
- plutus-core/plutus-ir/test/transform/letFloat/regression1
- plutus-core/plutus-ir/test/transform/letFloat/regression1.golden
- plutus-tx-plugin/test/Plugin/Data/monomorphic/strictPattern.plc.golden
Immovable let bindings did *not* act as anchors for lets inside the
*body* of the let. This let the let-floater produce ill-scoped terms.
The fix is:
- Do create anchors for the lets in the body of a let with immovable
bindings, by picking a single binding to be the representative.
- Distinguish different kinds of anchors in order to avoid this getting
confused with the existing anchors which can be created from bindings
(for their RHSs).
I did some simplification while I was at it. I couldn't resist moving
out let-merging into its own pass, given how simple it is...
- Branch
- PR
> Fix another let-floating bug with immovable bindings

- cabal.project
- nix/pkgs/haskell/haskell.nix
- nix/pkgs/haskell/materialized-darwin/.plan.nix/iohk-monitoring.nix
- nix/pkgs/haskell/materialized-linux/.plan.nix/iohk-monitoring.nix
It was changed here - https://github.com/input-output-hk/plutus/commit/6615b507082b133ce611e546b08ed57810f8a38f
Still trying to track down why master on https://github.com/input-output-hk/iohk-monitoring-framework has lost those commits, but nevertheless the precise commit we need still lives in that repo, so we can just reference it?
- Branch
- PR
> iohk-monitoring got bumped down; but it should be this commit.

- nix/pkgs/haskell/materialized-darwin/.plan.nix/plutus-use-cases.nix
- nix/pkgs/haskell/materialized-linux/.plan.nix/plutus-use-cases.nix
- plutus-contract/src/Plutus/Contract.hs
- plutus-contract/src/Plutus/Contract/Request.hs
- plutus-ledger/src/Ledger/Constraints.hs
- plutus-ledger/src/Ledger/Constraints/OffChain.hs
- plutus-use-cases/plutus-use-cases.cabal
- plutus-use-cases/scripts/Main.hs
- plutus-use-cases/src/Plutus/Contracts/MultiSig.hs
- plutus-use-cases/test/Spec/MultiSig.hs
- plutus-use-cases/test/Spec/PubKey.hs
The `signatories` field of the partial tx should contain a list of (64 byte) [`XPub`](https://github.com/input-output-hk/cardano-crypto/blob/develop/src/Cardano/Crypto/Wallet.hs#L79) keys. This is quite different from the emulator, where only deal with _hashes_ of 32 byte keys.
Fixing this involves two steps.
1) Change the `ExportTx` type, and `UnbalancedTx` which it is based on, to include public keys instead of public key hashes. This required some changes to the constraint mechanism. I first tried changing the constraints themselves to use public keys instead of public key hashes, but the subsequent changes to the validators meant that we would have to hash public keys in on-chain code, which we really want to avoid (because there is a high risk that we will do it wrong). So instead I …
> Changes to support the partial tx format

- plutus-core/cost-model/data/cekMachineCosts.json
- plutus-core/cost-model/test/TestCostModels.hs
- plutus-core/executables/Common.hs
- plutus-core/plutus-core/src/PlutusCore/Evaluation/Machine/ExBudget.hs
- plutus-core/plutus-core/test/CostModelInterface/Spec.hs
Remove some annoying underscores that we don't seem to need any more. Previously used for some lens-related thing?
- Branch
- PR
> Remove underscores from _exBudgetCPU and _exBudgetMemory

- plutus-tx/src/PlutusTx/AssocMap.hs
- plutus-use-cases/test/Spec/crowdfundingEmulatorTestOutput.txt
- plutus-use-cases/test/Spec/future.pir
- plutus-use-cases/test/Spec/governance.pir
- plutus-use-cases/test/Spec/multisigStateMachine.pir
- plutus-use-cases/test/Spec/renderCrowdfunding.txt
- plutus-use-cases/test/Spec/renderGuess.txt
- plutus-use-cases/test/Spec/renderVesting.txt
We have it, we might as well use it. In particular, this will give
`Value` a better encoding.
I am going to try and sneak this into the release.
- Branch
- PR
> Give PlutusTx.AssocMap IsData instances that use the map type in Data

- marlowe-playground-client/src/MainFrame/View.purs
The current implementation is broken and the plan is to integrate that functionality as a dynamic form in Marlowe Run/Marketplace instead of a Blockly interface in the playground. For now disabling, we can remove the code in a future PR (which will eliminate some libraries dependencies as well).
- Branch
- PR
> Marlowe Playground Client - Disable link to actus labs

- marlowe-dashboard-client/src/Template/View.purs
Does what it says on the tin. This turned out to be an easy fix - thanks for catching the bug @hrajchert.
> SCP-2555: Fixing contract setup confirmation on mobile

- plutus-contract/src/Plutus/Contract/Request.hs
instead of polling on every slot. 
This is already an improvement as is, but ideally this would block until the condition is met instead of poll on utxos changes alone
This was first encountered on #3526 where an endpoint should only be exposed after an address has been given funds, but given the original polling behavior of fundsAtAddressCondition that had to receive responses of the current slot in order to poll until the next one it ended preventing the other endpoint of funding the address from being exposed
- Branch
- PR
> fundsAtAddressCondition await on utxos updates 

- plutus-core/plutus-ir/src/PlutusIR/Compiler.hs
- plutus-core/plutus-ir/src/PlutusIR/Compiler/Types.hs
- plutus-core/plutus-ir/test/datatypes/listMatchEval.golden
- plutus-core/plutus-ir/test/datatypes/maybe.golden
- plutus-core/plutus-ir/test/recursion/even3Eval.golden
- plutus-tx-plugin/src/PlutusTx/Plugin.hs
- plutus-use-cases/test/Spec/crowdfundingEmulatorTestOutput.txt
- plutus-use-cases/test/Spec/renderCrowdfunding.txt
- plutus-use-cases/test/Spec/renderGuess.txt
- plutus-use-cases/test/Spec/renderVesting.txt
Profiling the pir compiler demonstrated that a lot of time is spent during deadcode optimisations. This PR reduces the multiple number of `removeDeadBindings` calls to only two:
1. before `simplifyTerm` in `compileToReadable`
2. before `simplifyTerm` in `compileReadableToPlc`
Before this change:
After this change:
---
- Branch
- PR
> Reduce the number of `removeDeadBindings` calls

- plutus-core/plutus-core/src/PlutusCore/Name.hs
- plutus-core/plutus-ir/src/PlutusIR/Transform/Inline.hs
The compilation of the auction contract was about ~6s before improvements.
1. By using a concrete monad instead of a polymorphic one the time reduced to ~4s.
2. By skipping an empty substitution the time reduced to ~1.5s
Before:
After two improvements:
---
- Branch
- PR
> Improve the performance of `PlutusIR.Transform.Inline.inline`

- nix/pkgs/haskell/materialized-darwin/.plan.nix/plutus-ledger.nix
- nix/pkgs/haskell/materialized-linux/.plan.nix/plutus-ledger.nix
- nix/pkgs/haskell/materialized-windows/.plan.nix/plutus-ledger.nix
- playground-common/src/PSGenerator/Common.hs
- plutus-chain-index/src/Plutus/ChainIndex/Server.hs
- plutus-chain-index/src/Plutus/ChainIndex/Tx.hs
- plutus-chain-index/test/Generators.hs
- plutus-contract/src/Plutus/Contract/Trace/RequestHandler.hs
- plutus-ledger/plutus-ledger.cabal
- plutus-ledger/src/Ledger/Generators.hs
- plutus-ledger/src/Ledger/Tx.hs
- plutus-ledger/test/Spec.hs
- plutus-pab/src/Plutus/PAB/Simulator.hs
Support for storing CardanoAPI transactions in chain index.
Biggest work of this PR was the `FromJSON/ToJSON` instances for the new datatype `SomeCardanoApiTx`.
- Branch
- PR
> SCP-2671: Support for storing CardanoAPI transactions in chain index

- plutus-playground-client/static/layout.scss
Fixes #3858 
by avoiding applying styles that were only meant to be used outside of
the monaco editor. This is due to the suggestions dropdown was also using
.main as a classname and this change only applies to the direct children 
element that manages the layout as originally intended.
- Branch
- PR
> plutus-playground: fix editor suggestions dropdown render

- plutus-pab/src/Cardano/ChainIndex/Types.hs
- plutus-pab/src/Cardano/Node/Types.hs
- plutus-pab/src/Cardano/Wallet/Types.hs
- plutus-pab/src/Plutus/PAB/Types.hs
- plutus-pab/src/Plutus/PAB/Webserver/Server.hs
This is a simple fix inspired by a comment from my colleague who observed that you can suggest a host preference to Warp to fix the issue it was having in resolving the hostname on macs.
Strange but true!
- Branch
- PR
> suggest to warp a host preference, resolves localhost issue

- plutus-core/plutus-core/src/PlutusCore/Default/Builtins.hs
I noticed the `trace` builtin was definitely very suboptimally. I'm not sure if there's any valid use case for `SomeConstantOf uni Some_type '[]`, but I can't think of any. `SomeConstant uni Some_type`  is a better way to spell that, but that also only makes sense when `Some_type` represents a Plutus type variable. So what should be used in `Trace` instead of `SomeConstantOf uni Text '[]` is simply `Text` and at that point inference works well and no type signatures are required.
Note that this is not just a nicer definition, it's also faster, since the `KnownType` instance of `SomeConstantOf` does quite a lot of bookkeeping.
> [Builtins] [Refac] Improve the meaning of 'Trace'

- marlowe/marlowe.cabal
- marlowe/test/Spec.hs
- marlowe/test/SpecLongRunning.hs
- nix/pkgs/haskell/haskell.nix
- nix/pkgs/haskell/materialized-darwin/.plan.nix/marlowe.nix
- nix/pkgs/haskell/materialized-darwin/.plan.nix/plutus-pab.nix
- nix/pkgs/haskell/materialized-darwin/default.nix
- nix/pkgs/haskell/materialized-linux/.plan.nix/marlowe.nix
- nix/pkgs/haskell/materialized-linux/.plan.nix/plutus-pab.nix
- nix/pkgs/haskell/materialized-linux/default.nix
- nix/pkgs/haskell/materialized-windows/.plan.nix/marlowe.nix
- nix/pkgs/haskell/materialized-windows/.plan.nix/plutus-pab.nix
- nix/pkgs/haskell/materialized-windows/default.nix
- plutus-pab/plutus-pab.cabal
- plutus-pab/test/full/Spec.hs
- plutus-pab/test/full/SpecLongRunning.hs
This follows the idea of @hamishmack to use the `platform` filter to prevent these long-running tests from running on the mac-mini.
Notably, it avoids the tests running _on macs_ in general. This is a bit of a shame, but I think it's one step better than _not running the tests at all_, which was the previous alternative.
Topics for discussion:
- Branch
- PR
> Constrain tests by platform

- plutus-core/plutus-core/src/PlutusCore/DeBruijn/Internal.hs
According to the Plutus Core specifications, names can only start with letters.
```
Name n ::= [a-zA-Z][a-zA-Z0-9_’]*
```
But currently `fakeNameDeBruijn` gives an empty `ndbnString`, which leads to "invalid" pretty-printed programs in this scenario:
- Call `mkTermToEvaluate` on a `Script`.
- The program is named with `fakeNameDeBruijn`.
- The `NamedDeBruijn`s are translated to `Name` through `unDeBruijnProgram`.
- `prettyPlcClassicDebug`ing the program/term leads to names like `_0`, `_1` because of the `PrettyBy` instance of `Name`:
```
instance HasPrettyConfigName config => PrettyBy config Name where
prettyBy config (Name txt (Unique uniq))
| showsUnique = pretty txt <> "_" <> pretty uniq
...
```
This leads to the `uplc` CLI itself failing to parse the program:
```
$ cat alwaystrue.uplc …
```
> Fix pretty printing `fakeNameDeBruijn`

- deployment/morph/machines/marlowe-dash.nix
- marlowe-dashboard-client/src/Capability/Contract.purs
- marlowe-dashboard-client/src/Capability/Marlowe.purs
- marlowe-dashboard-client/src/Capability/PlutusApps/MarloweApp.purs
- marlowe-dashboard-client/src/Capability/PlutusApps/MarloweApp/Lenses.purs
- marlowe-dashboard-client/src/Capability/PlutusApps/MarloweApp/Types.purs
- marlowe-dashboard-client/src/Dashboard/State.purs
- marlowe-dashboard-client/src/Dashboard/View.purs
- marlowe-dashboard-client/src/Env.purs
- marlowe-dashboard-client/src/Main.purs
- marlowe-dashboard-client/src/MainFrame/State.purs
- marlowe-dashboard-client/src/Marlowe/Client.purs
- marlowe/src/Language/Marlowe/Client.hs
- marlowe/test/Spec/Marlowe/Marlowe.hs
This PR is the third modification to improve the errors received from the BE. ([first modification](https://github.com/input-output-hk/plutus/pull/3835), [second modification](https://github.com/input-output-hk/plutus/pull/3883)) 
It adds the endpoint name to the MarloweApp contract so we can tie a response to an action (we should later expand for a requestId approach) and it adds a mutex logic to avoid calling unavailable endpoints.
- Branch
- PR
> SCP-2594: Handle errors from the Marlowe contract (version 3)

- plutus-chain-index/app/CommandLine.hs
- plutus-chain-index/app/Config.hs
- plutus-chain-index/app/Main.hs
- Further distinguish chain index & logging configs. 
- Support print default configs to file.
Previously there is an unhandled `DumpDefaultConfig` CLI command, with a few misdescriptions between the two config types.
- Branch
- [] Tests are provided (if possible)
- PR
> Improve ChainIndex config handling

- plutus-chain-index/src/Plutus/ChainIndex/TxIdState.hs
- plutus-chain-index/src/Plutus/ChainIndex/Types.hs
- plutus-chain-index/test/Generators.hs
- plutus-chain-index/test/Spec.hs
- plutus-pab/src/Plutus/PAB/Core/ContractInstance/BlockchainEnv.hs
- plutus-pab/src/Plutus/PAB/Core/ContractInstance/STM.hs
Fixes SCP-2735
Just adds an `Either` around the `transactionStatus` function.
The only questionable decision is [here](https://github.com/input-output-hk/plutus/compare/scp-2735-better-rollback-handling?expand=1#diff-cd4b79c0e47357f6c23774aab7a7428886411ce2d53405ef85f1bccbe8ae112eR431) where I've opted to retry on case of finding an error, instead of bumping the error up. I think this might be the thing you'd want, but it's debatable.
~Note that this doesn't address the other part of SCP-2735; making `updateTransactionState` return an error. I think in order to this properly things need to be shifted to use effects. Just want to clarify that idea first.~ ~Actually, I'm doing something here.)~
For discussion:
- Branch
- PR
> make transaction status return an either

- plutus-core/plutus-core/stdlib/PlutusCore/StdLib/Type.hs
- plutus-core/plutus-ir/src/PlutusIR/Compiler.hs
- plutus-core/plutus-ir/test/datatypes/listMatchEval.golden
- plutus-core/plutus-ir/test/recursion/even3Eval.golden
- plutus-core/plutus-ir/test/types/listMatch.golden
- plutus-core/plutus-ir/test/types/mutuallyRecursiveTypes.golden
This was coming up on the inlining branch, but it's independent (see https://github.com/input-output-hk/plutus/pull/3630#issuecomment-912915629).
The issue was that we were reusing a variable in two separate binders, which led to us using the wrong one in the body.
The error looks like this. The issue is that we were using the `a` from the outer type abstraction instead of the `a` from the inner type lambda, which makes it all go wrong.
```
Expected type
'(fun
(ifix
(lam
self
(fun (type) (type))
(lam a (type) (fun [ self (fun a b) ] (fun a b)))
)
(fun a b)
)
(fun a b)
)',
found type
'(fun
(ifix
(lam self (fun (type) (type)) (lam a (type) (fun [ self a ] a))) (fun a b)
)
(fun a b)
)'
```
When debugging this I had lots of other issues. Printing out the code, I found that most of the terms …
> Fix a shadowing bug in generating recursive types.

- marlowe/test/Spec/Marlowe/Marlowe.hs
- plutus-contract/src/Plutus/Contract/Test.hs
- plutus-contract/src/Plutus/Contract/Test/ContractModel.hs
- plutus-contract/test/Spec/Contract.hs
- plutus-core/plutus-core/src/PlutusCore/DeBruijn/Internal.hs
- plutus-use-cases/test/Spec/Crowdfunding.hs
We have found out that `Arbitrary` instance for `Actions state` generates a list of actions that does not exceed 125 slots of `initialState` as of here
https://github.com/input-output-hk/plutus/blob/d87e2eb1c37b995af2c56c5197a68dc02ced2633/quickcheck-dynamic/src/Test/QuickCheck/StateModel.hs#L113-L115
Meaning that even if we can still configure `initialState.lastSlot` in `propRunActionsWithOptions` to make the precondition be satisfied
https://github.com/input-output-hk/plutus/blob/d87e2eb1c37b995af2c56c5197a68dc02ced2633/plutus-contract/src/Plutus/Contract/Test/ContractModel.hs#L530-L531
We only strip list of actions that was already generated by the `Arbitrary` instance above. This PR removes the requirement of having the limitation of contract slots amount since the generator already …
> [#3843] Make arbitrary instance for actions in quickcheck-dynamic depend on their sizing

- plutus-chain-index/src/Plutus/ChainIndex/TxIdState.hs
- plutus-chain-index/src/Plutus/ChainIndex/Types.hs
- plutus-chain-index/test/Generators.hs
- plutus-chain-index/test/Spec.hs
Fixes SCP-2736
~I'm going to try and add a few more tests~, but @j-mueller it's of interest to note that I already caught one.
The issue was twofold:
- In the rollback, we were losing the old `txnsConfirmed`, so now it grabs the old state and adds it to the new one,
- In `transactionStatus` I just had the logic wrong for something being confirmed! `>=` vs `>` !
TODO:
- Branch
- PR
> Fix bug in transactionStatus, and TxIdState tracking when rolling-back

- plutus-core/plutus-core/src/PlutusCore/Data.hs
- plutus-tx/test/Spec.hs
Previously `fromIntegral :: Integer -> Word64` would silently
wrap integers which were out of range. Instead we now encode
out-of-range integers as big integers, which is more honest *and* will
fail to deserialise, making this a "soft" way of failing, rather than
calling error.
I'll backport this to `release/alonzo` afterwards also.
- Branch
- PR
> SCP-2758: Encode out-of-range integers as bigints

- plutus-tx/src/PlutusTx/List.hs
- Branch
- PR
The `take` function exported from PlutusTx.List doesn't work on-chain. Under the hood it uses `Prelude.<=` instead of `PlutusTx.<=`. 
Changed import to use function `PlutusTx.<=`
> [PlutusTx.List]: Fix take function

- nix/pkgs/haskell/materialized-darwin/.plan.nix/plutus-ledger-api.nix
- nix/pkgs/haskell/materialized-linux/.plan.nix/plutus-ledger-api.nix
- nix/pkgs/haskell/materialized-windows/.plan.nix/plutus-ledger-api.nix
- plutus-ledger-api/plutus-ledger-api.cabal
- plutus-ledger-api/src/Plutus/V1/Ledger/Scripts.hs
- plutus-ledger-api/src/Plutus/V2/Ledger/Api.hs
- plutus-ledger-api/src/Plutus/V2/Ledger/Contexts.hs
- plutus-tx/src/PlutusTx/AssocMap.hs
This is a first attempt at a V2 ledger interface.
- It re-exports almost everything from V1.
- It has new definitions of `TxInfo` and `ScriptContext` (which depends on `TxInfo`), as well as the functions that operate on `TxInfo`, and the envelope type.
- Changes to `TxInfo`:
- Use `Map` for the maps
- Add redeemer map
I have not changed anything to use it: in the future we'll want to do that, but probably the `plutus-ledger` stuff should happen after we split the repo.
- Branch
- PR
> SCP-2771: Plutus V2 interface

- plutus-contract/src/Plutus/Contract/Test/ContractModel.hs
- plutus-contract/src/Plutus/Trace/Effects/EmulatorControl.hs
- plutus-use-cases/test/Spec/Auction.hs
- plutus-use-cases/test/Spec/GameStateMachine.hs
- plutus-use-cases/test/Spec/Prism.hs
This PR adds the concept of a No-Locked-Funds proof to the contract model framework. A No-Locked-Funds proof consists of
- a strategy for recovering all funds from a contract (in any given state)
- for each wallet, a strategy to *unilaterally* recover their share of the funds without any actions from the other wallets
This prevents situations where there are strategies for recovering all funds from a contract, but they require the cooperation of wallets that have no incentives to do so.
- Branch
- ~~[ ] Relevant tickets are mentioned in commit messages~~
- PR
> No locked funds proofs

- cabal.project
- nix/pkgs/haskell/haskell.nix
- plutus-core/plutus-core/src/PlutusCore/Evaluation/Machine/ExBudget.hs
- plutus-ledger-api/src/Plutus/V1/Ledger/Api.hs
This enables the ledger to compute budgets while still setting an
overall limit, to guard against scripts that run for a very long time,
or loop.
I decided to roll this into `evaluateScriptRestricting` rather than
giving `evaluteScriptCounting` a bound, since having the bound-less
version of `evaluateScriptCounting` is still handy for casual usage.
Possibly it's actually just a trap and we should delete it, though.
- Branch
- PR
> SCP-2772: Teach evaluateScriptRestricting to return the used budget

- plutus-ledger-api/src/Plutus/V2/Ledger/Api.hs
We now use it in `TxInfo`, so we should export it so the ledger doesn't
need to import anything else.
- Branch
- PR
> Export AssocMap.Map from the V2 API

- nix/pkgs/haskell/materialized-darwin/.plan.nix/plutus-tx.nix
- nix/pkgs/haskell/materialized-linux/.plan.nix/plutus-tx.nix
- nix/pkgs/haskell/materialized-windows/.plan.nix/plutus-tx.nix
- plutus-ledger/plutus-ledger.cabal
- plutus-ledger/src/Ledger/Orphans.hs
- plutus-tx/plutus-tx.cabal
- plutus-tx/src/PlutusTx/AssocMap.hs
- plutus-tx/src/PlutusTx/Builtins/Internal.hs
Fix for extra dep merged in https://github.com/input-output-hk/plutus/pull/3807#issuecomment-925813317 ; it's now gone and instances are over in `Ledger.Oprhans`.
- Branch
- PR
> remove openapi3 dep from plutus-tx

- .gitattributes
Curious to see if this fixes the linguist language estimate:
If you click on HTML, it only shows 8 files, and though they are large, they don't seem to be larger than Haskell in total line count ... 😕 , so I added the docs folder as well?
- Branch
- PR
> linguist fixup

- marlowe-dashboard-client/src/Capability/Marlowe.purs
- marlowe-dashboard-client/src/Contacts/State.purs
- marlowe-dashboard-client/src/Contacts/Types.purs
- marlowe-dashboard-client/src/Contacts/View.purs
- marlowe-dashboard-client/src/Contract/State.purs
- marlowe-dashboard-client/src/Dashboard/State.purs
- marlowe-dashboard-client/src/Dashboard/Types.purs
- marlowe-dashboard-client/src/Dashboard/View.purs
- marlowe-dashboard-client/src/MainFrame/State.purs
- marlowe-dashboard-client/src/Welcome/State.purs
- marlowe-dashboard-client/src/Welcome/Types.purs
- marlowe-dashboard-client/src/Welcome/View.purs
This PR adds workflow comments throughout the code. They should be self-explanatory - start from the long comment at `MainFrame.State:47`.
While I was at it, I changed some of the "use wallet" terminology to "connect wallet".
> SCP-2766: Add workflow comments

- bitte/pab.nix
Keeping the state around isn't helpful (currently) because we can't
get pre-reset wallets.
This reverts commit e98ecd57bc7e1cd97fd9eb9bb0a0bfa47b1024c2.
> Revert "bitte: Test not clearing the PAB on restart"

- plutus-tx/src/PlutusTx/Ratio.hs
- Branch
- PR
Some exported functions do not have a pragma `INLINABLE`:
- `recip`
- `fromInteger`
- `toGHC`
-  `fromGHC`
As a result, they may not be possible to use in on-chain code.
For these `INLINABLE` pragma has been added.
> [PlutusTx.Ratio]: Added `INLINABLE` pragmas to `recip`, `fromInteger`, `toGHC`, `fromGHC`

- nix/pkgs/haskell/materialized-darwin/.plan.nix/plutus-tx-plugin.nix
- nix/pkgs/haskell/materialized-linux/.plan.nix/plutus-tx-plugin.nix
- nix/pkgs/haskell/materialized-windows/.plan.nix/plutus-tx-plugin.nix
- plutus-tx-plugin/plutus-tx-plugin.cabal
- plutus-tx-plugin/test/Budget/Lib.hs
- plutus-tx-plugin/test/Budget/Spec.hs
- plutus-tx-plugin/test/Budget/any.budget.golden
- plutus-tx-plugin/test/Budget/any.plc.golden
- plutus-tx-plugin/test/Budget/elem.budget.golden
- plutus-tx-plugin/test/Budget/elem.plc.golden
- plutus-tx-plugin/test/Budget/filter.budget.golden
- plutus-tx-plugin/test/Budget/filter.plc.golden
- plutus-tx-plugin/test/Budget/find.budget.golden
- plutus-tx-plugin/test/Budget/find.plc.golden
- plutus-tx-plugin/test/Budget/sum.budget.golden
- plutus-tx-plugin/test/Budget/sum.plc.golden
- plutus-tx-plugin/test/Spec.hs
Added a few tests in plutus-tx-plugin which record the budget of a few functions in plutus-tx.
That means that if we were to change the implementation of functions in PlutusTx, then the golden files would change as well and we could verify if the change is positive or not.
- Branch
- PR
> SCP-2799: Support for recording budgets in plutus-tx-plugin

- plutus-core/executables/Common.hs
- plutus-core/executables/uplc/Main.hs
- plutus-core/plutus-core/src/PlutusCore/Evaluation/Machine/ExBudgetingDefaults.hs
If you run `uplc` with the `-t -1` options it reports the number of times each AST constructor is evaluated, but used to ignore builtins. This extends it to report how often each built-in function is executed as well, using a unit-cost cost model for builtins.  This might make it a bit easier to diagnose inaccuracies in the costing functions for builtins. 
- Branch
- PR
> Add unit cost model for builtins (SCP-2815)

- plutus-core/cost-model/budgeting-bench/Benchmarks/Nops.hs
- plutus-core/generators/PlutusCore/Generators/Internal/Denotation.hs
- plutus-core/generators/PlutusCore/Generators/Internal/Entity.hs
- plutus-core/plutus-core/examples/PlutusCore/Examples/Builtins.hs
- plutus-core/plutus-core/src/PlutusCore/Constant/Debug.hs
- plutus-core/plutus-core/src/PlutusCore/Constant/Meaning.hs
- plutus-core/plutus-core/src/PlutusCore/Constant/Typed.hs
- plutus-core/plutus-core/src/PlutusCore/Default/Universe.hs
This drops the `term` argument from `KnownTypeIn` allowing us to
express more and require less. See the comments.
`KnownType term a` is recovered and user code is not affected
apart from `KnownTypeIn DefaultUni` instances being simpler and
some old testing code (that was already behaving weirdly) requiring
a few explicit type applications.
> [Builtin] Introduce 'AssociateType' in 'KnownTypeIn'

- prettyprinter-configurable/src/Text/Fixity/Internal.hs
A stupid typo. I checked, the code does the right thing and there's a [correct](https://github.com/input-output-hk/plutus/blob/78ebc12905a86df1f43b3f19a339d6d7dbc448b8/prettyprinter-configurable/src/Text/Fixity/Internal.hs#L217-L219) comment as well.
> [Typo] Fix a typo in a comment in 'prettyprinter-configurable'

- plutus-core/cost-model/budgeting-bench/Benchmarks/Nops.hs
- plutus-core/generators/PlutusCore/Generators/Internal/Denotation.hs
- plutus-core/generators/PlutusCore/Generators/Internal/Entity.hs
- plutus-core/plutus-core/examples/PlutusCore/Examples/Builtins.hs
- plutus-core/plutus-core/src/PlutusCore/Constant/Debug.hs
- plutus-core/plutus-core/src/PlutusCore/Constant/Meaning.hs
- plutus-core/plutus-core/src/PlutusCore/Constant/Typed.hs
- plutus-core/plutus-core/src/PlutusCore/Default/Universe.hs
Reverts input-output-hk/plutus#4172 due to performance [problems](https://github.com/input-output-hk/plutus/pull/4172#issuecomment-961809116) with it. I have an idea on how to fix them, so the war is not over.
> Revert "[Builtin] Introduce 'AssociateType' in 'KnownTypeIn'"

- plutus-core/plutus-core/examples/PlutusCore/Examples/Builtins.hs
- plutus-core/plutus-core/src/PlutusCore/Constant/Debug.hs
- plutus-core/plutus-core/src/PlutusCore/Constant/Meaning.hs
- plutus-core/plutus-core/src/PlutusCore/Constant/Typed.hs
- plutus-core/plutus-core/src/PlutusCore/Default/Builtins.hs
- plutus-core/plutus-core/src/PlutusCore/Evaluation/Result.hs
This drops all occurrences of `SomeConstantOf` from the definitions of builtins. Since we hardcode `DefaultUni` there anyway, we can just match on tags directly, which really should be at least somewhat more performant (if it's not, then I'm optimizing something that is not even close to being a bottleneck).
Not ready for review, just for benchmarking.
> [Builtin] Quit using 'SomeConstantOf'

- plutus-core/plutus-ir/src/PlutusIR/Compiler/Definitions.hs
- plutus-tx-plugin/src/PlutusTx/Compiler/Expr.hs
- plutus-tx-plugin/src/PlutusTx/Compiler/Type.hs
- plutus-tx-plugin/src/PlutusTx/Compiler/Types.hs
- plutus-tx-plugin/src/PlutusTx/Plugin.hs
- plutus-tx-plugin/test/IsData/deconstructData.plc.golden
- plutus-tx-plugin/test/IsData/unit.plc.golden
- plutus-tx-plugin/test/IsData/unitInterop.plc.golden
- plutus-tx-plugin/test/IsData/unsafeDeconstructData.plc.golden
- plutus-tx-plugin/test/Plugin/Primitives/trace.plc.golden
See `Note [Dependency tracking]` for the rationale.
I think overall this makes things simpler, and probably faster (since
we're not traversing things to get their free variables all the time).
It also fixes a long-standing hack whereby I made everything depend on
`Unit`, precisely because we would occasionally insert references to it
in a dynamic way. That goes away, which explains the test changes
(moving the `Unit` definition to a slightly more precise location).
This removes the need for the hack in
https://github.com/input-output-hk/plutus/issues/4148.
- Branch
- PR
> SCP-3058: PIR: track dependencies dynamically instead of statically

- plutus-core/plutus-core/examples/PlutusCore/Examples/Builtins.hs
- plutus-core/plutus-core/src/PlutusCore/Constant/Dynamic/Emit.hs
- plutus-core/plutus-core/src/PlutusCore/Constant/Typed.hs
- plutus-core/plutus-core/src/PlutusCore/Default/Builtins.hs
- plutus-core/plutus-core/src/PlutusCore/Default/Universe.hs
- plutus-core/plutus-core/src/PlutusCore/Evaluation/Machine/Ck.hs
- plutus-core/untyped-plutus-core/src/UntypedPlutusCore/Evaluation/HOAS.hs
- plutus-core/untyped-plutus-core/src/UntypedPlutusCore/Evaluation/Machine/Cek/Internal.hs
I was annoyed in #4229 that 'makeKnown' and 'readKnown' require different monads,
so I started thinking about ways to unify them and this PR implements such a way.
The idea is that for all intents and purposes 'makeKnown' always receives an
emitting function, for example we have
flip unWithEmitterT ?cekEmitter $ makeKnown (Just term) x
so we can just make it an explicit argument transforming the line above to
makeKnown ?cekEmitter (Just term) x
- Branch
- PR
> [Builtins] Simplify 'Emitter'

- .github/ISSUE_TEMPLATE/bug_report.md
- .github/ISSUE_TEMPLATE/feature_request.md
- .github/PULL_REQUEST_TEMPLATE.md
- CONTRIBUTING.adoc
This is an attempt to structure our interactions with external contributors a bit more clearly, mainly by asking that all changes come with an issue, and that the implementation approach has had signoff from someone one the Plutus team. The goal here isn't to put up more barriers, but rather to help external contributors make it easy for the Plutus team to review and assess their work, hopefully making things less time-consuming and frustrating all round.
Most of our good external contributors already do this (or nearly this), so hopefully it's not too controversial.
Also cc @silky @jhbertra @asutherlandus
> Add clearer guidelines for external contributors

- plutus-core/plutus-core/src/PlutusCore/Evaluation/Machine/BuiltinCostModel.hs
- plutus-tx-plugin/src/PlutusTx/Compiler/Expr.hs
- plutus-tx-plugin/test/Plugin/Profiling/Spec.hs
- plutus-tx-plugin/test/Plugin/Profiling/id.plc.golden
- plutus-tx-plugin/test/Plugin/Profiling/idCode.plc.golden
- plutus-tx-plugin/test/Plugin/Profiling/letInFun.plc.golden
- plutus-tx-plugin/test/Plugin/Profiling/letInFunMoreArg.plc.golden
- plutus-tx-plugin/test/Plugin/Profiling/letRecInFun.plc.golden
- plutus-tx-plugin/test/Plugin/Profiling/typeclass.plc.golden
1. Add a test confirming we profile typeclass methods
2. Add a test confirming we don't profile local functions
3. Fix the tracing of polymorphic functions, which wasn't working at all :scream: 
4. Add tracing of local functions
I think 3 is the killer here, that's going to have cut out lots of functions from normal Haskell code! Unfortunately the test was working by accident: we basically did this:
```
id = traceStuff (/\ a . \a -> a)
``` 
rather than
```
id = /\ a . \a -> traceStuff a
```
because we didn't go under the type abstractions. But the test called `id` once, so didn't notice this! I tweaked the test to call `id` twice, and lo we got the wrong answer (because the trace was happening when it was *defined* not when it was *called*).
Fixing that turned out to be a little involved …
> SCP-3109: Various profiling improvements

- plutus-tx-plugin/src/PlutusTx/Compiler/Expr.hs
- plutus-tx-plugin/test/Plugin/Profiling/Spec.hs
- plutus-tx-plugin/test/Plugin/Profiling/argMismatch1.plc.golden
- plutus-tx-plugin/test/Plugin/Profiling/argMismatch2.plc.golden
It seemed initially plausible that the term and type should match up
exactly when we're processing them, and thus it's okay to blow up if
they don't match.
But this is false: both at the term and the type level. I ran into it at
the type level (type lambdas from newtypes), but it's also false at the
term level.
- Branch
- PR
> Fix another bug in profiling

- plutus-core/executables/Common.hs
- plutus-core/executables/Parsers.hs
I was trying to use `uplc` to convert some files to flat format and got an error like this:
```
$ cabal exec uplc convert -- -i plutus-benchmark/validation/data/auction_1-1.flat -o /dev/null --if flat --of flat
uplc: De-Bruijn-named ASTs are not supported for typed Plutus Core
```
The code that should handle this just raised an error for some reason.  This one-line PR gets it to do what it should (I think).  I'm not sure why it was like that in the first place (maybe my fault?).
- Branch
- PR
> Fix flat output in uplc for deBruijn-indexed ASTs

- plutus-core/docs/Builtins.md
As is the docs seem to say that (1 == 2) should be True.
- Branch
- PR
> Correct type-o

- plutus-core/plutus-ir/src/PlutusIR/Analysis/Dependencies.hs
- plutus-core/plutus-ir/src/PlutusIR/Transform/DeadCode.hs
- plutus-core/plutus-ir/test/TransformSpec.hs
- plutus-core/plutus-ir/test/errors/mutuallyRecursiveTypes
- plutus-core/plutus-ir/test/errors/mutuallyRecursiveTypes.golden
- plutus-core/plutus-ir/test/transform/deadCode/datatypeLiveType.golden
- plutus-core/plutus-ir/test/transform/deadCode/nestedBindingsIndirect.golden
- plutus-core/plutus-ir/test/transform/deadCode/pruneDatatype
- plutus-core/plutus-ir/test/transform/deadCode/pruneDatatype.golden
- plutus-core/plutus-ir/test/transform/retainedSize/datatypeLiveConstr.golden
- plutus-core/plutus-ir/test/transform/retainedSize/datatypeLiveType.golden
- plutus-core/plutus-ir/test/transform/retainedSize/nestedBindingsIndirect.golden
- plutus-tx-plugin/test/Plugin/Data/Spec.hs
- plutus-tx-plugin/test/Plugin/Data/monomorphic/monoDataType.plc.golden
- plutus-tx-plugin/test/Plugin/Data/monomorphic/monoRecord.plc.golden
- plutus-tx-plugin/test/Plugin/Data/monomorphic/recordNewtype.plc.golden
- plutus-tx-plugin/test/Plugin/Data/newtypes/paramNewtype.plc.golden
- plutus-tx-plugin/test/Plugin/Data/polymorphic/polyDataType.plc.golden
- plutus-tx-plugin/test/Plugin/Data/recursive/ptreeMatch.plc.golden
I got annoyed with what I was doing and I wanted to polish off something where I knew what to do, so I did this. cc @kk-hainq also.
------------
1. Change dependency analysis to account for the fact that the
term-level parts can be removed (see note).
2. Simplify datatype bindings into trivial type bindings if all their
term-level parts are dead.
Had to do a bit of test rearrangement since a lot of the
`plutus-tx-plugin` tests for a type T just used a lambda with an unused
argument of type T... which gets simplified with this PR!
Fixes #4147.
Fixes #3702.
- Branch
- PR
> SCP-2638: simplify datatypes which are used only at the type-level

- plutus-core/plutus-core/src/PlutusCore/Constant/Typed.hs
- plutus-core/plutus-core/src/PlutusCore/Evaluation/Machine/Ck.hs
- plutus-core/untyped-plutus-core/src/UntypedPlutusCore/Evaluation/Machine/Cek/Internal.hs
> [Builtins] Monomorphize 'readKnown'

- nix/pkgs/haskell/materialized-darwin/.plan.nix/plutus-core.nix
- nix/pkgs/haskell/materialized-darwin/default.nix
- nix/pkgs/haskell/materialized-linux/.plan.nix/plutus-core.nix
- nix/pkgs/haskell/materialized-linux/default.nix
- nix/pkgs/haskell/materialized-windows/.plan.nix/plutus-core.nix
- nix/pkgs/haskell/materialized-windows/default.nix
- plutus-core/plutus-core.cabal
- plutus-core/plutus-core/examples/PlutusCore/Examples/Builtins.hs
- plutus-core/plutus-core/src/PlutusCore/Constant/Debug.hs
- plutus-core/plutus-core/src/PlutusCore/Constant/Meaning.hs
- plutus-core/plutus-core/src/PlutusCore/Constant/Typed.hs
- plutus-core/plutus-core/src/PlutusCore/Default/Builtins.hs
- plutus-core/plutus-core/test/TypeSynthesis/Golden/ConstrData.plc.golden
- plutus-core/plutus-core/test/TypeSynthesis/Golden/IdRank2.plc.golden
- plutus-core/plutus-core/test/TypeSynthesis/Golden/ListData.plc.golden
- plutus-core/plutus-core/test/TypeSynthesis/Golden/MapData.plc.golden
- plutus-core/plutus-core/test/TypeSynthesis/Golden/MkNilData.plc.golden
- plutus-core/plutus-core/test/TypeSynthesis/Golden/MkNilPairData.plc.golden
- plutus-core/plutus-core/test/TypeSynthesis/Golden/MkPairData.plc.golden
- plutus-core/plutus-core/test/TypeSynthesis/Golden/UnConstrData.plc.golden
- plutus-core/plutus-core/test/TypeSynthesis/Golden/UnListData.plc.golden
- plutus-core/plutus-core/test/TypeSynthesis/Golden/UnMapData.plc.golden
- plutus-core/plutus-core/test/TypeSynthesis/Golden/UnsafeCoerce.plc.golden
- plutus-core/plutus-core/test/TypeSynthesis/Golden/UnsafeCoerceEl.plc.golden
> [Builtins] Disentangle 'KnownTypeAst' from 'KnownTypeIn'

- plutus-tx-plugin/src/PlutusTx/Compiler/Expr.hs
Through clever use of `PartialTypeSignatures`, we can write some code
that will work with both the patched and unpatched GHC, rather than
having to explicitly discriminate.
I built the package with both our patched GHC and a vanilla 8.10.7 and it worked fine.
FYI @angerman @sevanspowell
> Use `PartialTypeSignatures` to deal with the `Tickish` mess

- README.adoc
According to Moritz this is bad advice and you should just leave the
default settings (no sandbox).
> Remove note about Nix sandbox on Macos

- plutus-core/plutus-core/src/PlutusCore/Constant/Debug.hs
- plutus-core/plutus-core/src/PlutusCore/Constant/Meaning.hs
- plutus-core/plutus-core/src/PlutusCore/Constant/Typed.hs
This adds another custom type error, the final one that I had in mind.
I've also polished the `PlutusCore.Constant.Debug` module a bit.
> [Builtins] Add detection of stuck 'ToHoles'

- nix/pkgs/haskell/materialized-darwin/.plan.nix/plutus-benchmark.nix
- nix/pkgs/haskell/materialized-darwin/default.nix
- nix/pkgs/haskell/materialized-linux/.plan.nix/plutus-benchmark.nix
- nix/pkgs/haskell/materialized-linux/default.nix
- nix/pkgs/haskell/materialized-windows/.plan.nix/plutus-benchmark.nix
- nix/pkgs/haskell/materialized-windows/default.nix
- plutus-benchmark/README.md
- plutus-benchmark/plutus-benchmark.cabal
- plutus-benchmark/validation/BenchCek.hs
- plutus-benchmark/validation/BenchFull.hs
- plutus-benchmark/validation/Common.hs
Clone benchmark:validation to validation-full that measures also unflatting , mapping to fakename and undebruijining.
I/O to `readFile` the scripts is  (hopefully) not measured.
- Branch
- PR
> SCP-3383: Added plutus-benchmark-validation-full

- plutus-core/plutus-core/src/PlutusCore/Builtin/Runtime.hs
- plutus-core/plutus-core/src/PlutusCore/Evaluation/Machine/Ck.hs
- plutus-core/untyped-plutus-core/src/UntypedPlutusCore/Evaluation/Machine/Cek/Internal.hs
This one introduces `RuntimeScheme` which is akin to `TypeScheme` except it doesn't
contain a bunch of irrelevant types stuff that we don't need during evaluation.
The `RuntimeScheme` introduced here is not optimal performance-wise, which is future work.
> [Builtins] Introduce 'RuntimeScheme'

- nix/pkgs/haskell/materialized-darwin/.plan.nix/plutus-core.nix
- nix/pkgs/haskell/materialized-darwin/.plan.nix/plutus-tx.nix
- nix/pkgs/haskell/materialized-linux/.plan.nix/plutus-core.nix
- nix/pkgs/haskell/materialized-linux/.plan.nix/plutus-tx.nix
- nix/pkgs/haskell/materialized-windows/.plan.nix/plutus-core.nix
- nix/pkgs/haskell/materialized-windows/.plan.nix/plutus-tx.nix
- plutus-core/plutus-core.cabal
- plutus-core/plutus-core/src/Data/Aeson/THReader.hs
- plutus-core/plutus-core/src/Data/SatInt.hs
- plutus-core/plutus-core/src/PlutusCore/Builtin/KnownKind.hs
- plutus-core/plutus-core/src/PlutusCore/Core/Type.hs
- plutus-core/plutus-core/src/PlutusCore/Error.hs
- plutus-core/plutus-core/src/Universe/Core.hs
- plutus-core/testlib/PlutusCore/Generators/NEAT/Term.hs
- plutus-ledger-api/src/Plutus/V1/Ledger/Contexts.hs
- plutus-ledger-api/src/Plutus/V1/Ledger/Credential.hs
- plutus-ledger-api/src/Plutus/V1/Ledger/Tx.hs
- plutus-ledger-api/src/Plutus/V1/Ledger/Value.hs
- plutus-tx/plutus-tx.cabal
- plutus-tx/src/PlutusTx/IsData/TH.hs
- plutus-tx/src/PlutusTx/Lift/Class.hs
- plutus-tx/src/PlutusTx/Lift/Instances.hs
- plutus-tx/src/PlutusTx/TH.hs
- Branch
- PR
This doesn't fix #4303 but it's a step in that direction.
Half of the changes are due to `Eq` being a superclass of `Hashable` now, the other half are TH related.
> plutus-core: Fix support for GHC 9.2.1 and hashable 1.4

- plutus-core/plutus-core/src/PlutusCore/Evaluation/Machine/ExMemory.hs
Looking at [this CIP](https://github.com/cardano-foundation/CIPs/pull/218), I noticed that a comment about `ExMemoryUsage` for `Data` contained some gibberish, probably due to some text being pasted in in error.  This just fixes the comment.
- Branch
- PR
> Fix typo in comment

- plutus-core/plutus-core/src/PlutusCore/Builtin/HasConstant.hs
I should've done that when I replaced the general `m` by `Either` in `readKnown`.
> [Builtins] Use 'Either' in 'asConstant'

- plutus-core/plutus-core/src/PlutusCore/Default/Universe.hs
- plutus-core/plutus-core/src/Universe/Core.hs
I realized that we check whether all types from the universe implement `KnownBuiltinTypeIn`, but don't check where each of them has a `Contains` instance. This PR fixes that.
> [Builtins] Add 'TestTypesFromTheUniverseAreAllContained'

- plutus-core/plutus-core/src/PlutusCore/Builtin/KnownType.hs
- plutus-core/plutus-core/src/PlutusCore/Evaluation/Machine/Ck.hs
- plutus-core/untyped-plutus-core/src/UntypedPlutusCore/Evaluation/Machine/Cek/Internal.hs
> [Builtins] Introduce 'ReadKnownError' to fully monomorphize 'readKnown'

- plutus-core/plutus-core/src/PlutusCore/Evaluation/Machine/ExMemory.hs
In commit https://github.com/input-output-hk/plutus/commit/9c75e5265ba346a7b389036ee9596a7c58d52ecc I tidied up the size function for the `bytestring` type but I introduced a bug because the memory usage of the empty bytestring increased from 0 to 1, causing some previously OK scripts to fail validation because the cost increased slightly (specifically, the cost of calling `equalsByteString`.  This should fix that.
Here's the change that caused the problem:
- Branch
- PR
> Fix ExMemoryUsage bug for bytestring

- plutus-core/plutus-core/src/PlutusCore/Builtin/HasConstant.hs
- plutus-core/plutus-core/src/PlutusCore/Builtin/Polymorphism.hs
- plutus-core/plutus-core/src/PlutusCore/Evaluation/Machine/Ck.hs
- plutus-core/plutus-core/src/PlutusCore/Evaluation/Machine/MachineParameters.hs
- plutus-core/plutus-ir/src/PlutusIR/Core/Type.hs
- plutus-core/untyped-plutus-core/src/UntypedPlutusCore/Core/Type.hs
- plutus-core/untyped-plutus-core/src/UntypedPlutusCore/Evaluation/Machine/Cek/Internal.hs
We had to have two classes because of the way costing was aligned,
but that has changed, so now we can unite these classes.
I also dropped `HasConstant`, because we don't need it.
> [Builtins] Fuse 'AsConstant' and 'FromConstant' into 'HasConstantIn'

- nix/pkgs/haskell/materialized-darwin/.plan.nix/plutus-core.nix
- nix/pkgs/haskell/materialized-darwin/default.nix
- nix/pkgs/haskell/materialized-linux/.plan.nix/plutus-core.nix
- nix/pkgs/haskell/materialized-linux/default.nix
- nix/pkgs/haskell/materialized-windows/.plan.nix/plutus-core.nix
- nix/pkgs/haskell/materialized-windows/default.nix
- plutus-core/plutus-core.cabal
- plutus-core/plutus-core/src/GHC/Natural/Extras.hs
- plutus-core/plutus-core/src/PlutusCore/Default/Universe.hs
- plutus-core/plutus-core/src/PlutusCore/Evaluation/Machine/ExMemory.hs
We have two problems:
1. 32-bit systems keep causing us trouble.
2. Specifying the denotation of builtins using `Int` is nonsense since
`Int` is generally platform-dependent.
This PR solves 1 by solving 2. The way we do that is to:
- Add `Int64` to the builtin universe unconditionally.
- Add `Int` to the builtin universe, but do so by delegating to `Int64`
and using `intCastEq` to convert between the two.
That amounts to a *static* assertion that `Int` is equivalent to
`Int64`, which means our semantics are stable, and incidentally breaks
32-bit builds, which is good.
There are a couple of different ways I could have put this together. I pointed out one in the comments, thoughts welcome.
- Branch
- PR
> SCP-3529: Allow Int in the universe only if it is Int64

- plutus-benchmark/validation/BenchFull.hs
- plutus-core/executables/Common.hs
- plutus-core/plutus-core/src/PlutusCore/DeBruijn.hs
- plutus-core/plutus-core/src/PlutusCore/DeBruijn/Internal.hs
- plutus-core/plutus-core/src/PlutusCore/Flat.hs
- plutus-core/untyped-plutus-core/src/UntypedPlutusCore/Core/Instance/Eq.hs
- plutus-core/untyped-plutus-core/src/UntypedPlutusCore/DeBruijn.hs
- plutus-ledger-api/src/Plutus/V1/Ledger/Api.hs
- plutus-ledger-api/src/Plutus/V1/Ledger/Scripts.hs
Adds a fakename newtype wrapper to fuse the `map fakeName` inside the flat-decoding that happens
exactly before script execution.
Note: plutus-ledger-api has been updated but not yet the validation benchmarks (separate PR).
- Branch
- PR
> SCP-3410: Fuse map (fakeNameDeBruijn) into the flat deserialization process

- nix/pkgs/haskell/materialized-darwin/.plan.nix/plutus-benchmark.nix
- nix/pkgs/haskell/materialized-linux/.plan.nix/plutus-benchmark.nix
- nix/pkgs/haskell/materialized-windows/.plan.nix/plutus-benchmark.nix
- plutus-benchmark/plutus-benchmark.cabal
- plutus-benchmark/validation/BenchCek.hs
- plutus-benchmark/validation/BenchDec.hs
- plutus-benchmark/validation/BenchFull.hs
- plutus-benchmark/validation/Common.hs
- plutus-core/plutus-core/test/CostModelInterface/Spec.hs
Changes the validation-full&decode from handcrafted code to Ledger.Api module calls.
I would also like to change the normal validation module to use the `Scripts.evaluateScript` but then it would incur a performance penaly since that function would have to account for (fakename pass + scope checking).
- Branch
- PR
> SCP-3493: change validation-full&decode to use the Ledger.Api

- plutus-benchmark/validation/BenchFull.hs
This brings us even closer to what actually happens, by peeling off the
`Data` arguments and re-applyign them. Importantly, this means that the
`Data` constants created from the arguments don't cause the size check
to fail.
> Make validation-full benchmark apply arguments

- nix/pkgs/haskell/materialized-darwin/.plan.nix/plutus-ledger-api.nix
- nix/pkgs/haskell/materialized-linux/.plan.nix/plutus-ledger-api.nix
- nix/pkgs/haskell/materialized-windows/.plan.nix/plutus-ledger-api.nix
- plutus-benchmark/validation/BenchDec.hs
- plutus-benchmark/validation/BenchFull.hs
- plutus-core/cost-model/budgeting-bench/Benchmarks/Nops.hs
- plutus-core/plutus-core/src/PlutusCore/Evaluation/Machine/ExBudgetingDefaults.hs
- plutus-core/plutus-core/src/PlutusCore/Evaluation/Machine/MachineParameters.hs
- plutus-core/untyped-plutus-core/test/Evaluation/Builtins/Definition.hs
- plutus-ledger-api/plutus-ledger-api.cabal
- plutus-ledger-api/src/Plutus/V1/Ledger/Api.hs
- plutus-ledger-api/src/Plutus/V1/Ledger/EvaluationContext.hs
- plutus-ledger-api/src/Plutus/V2/Ledger/Api.hs
- plutus-ledger-api/test/Spec.hs
- plutus-ledger-api/test/Spec/Eval.hs
We would like to cache the result of computing the plutus costmodel
as long as the ledger protocol parameters do not change.
This adds an extra abstract datatype `EvaluationContext` and a
constructor `mkEvaluationContext` to make the transition to using a cache easier.
It is the responsibility of the ledger/node software to
1) read the cached value and pass it to the `API.evaluateScript*`
2) when receiving new protocol parameters, update the cache with the value of `mkEvaluationContext(new_protocol_parameters)`
**note to plutus devs**: this caches the typed `CostModel` as well the `MachineParameters` derived from it.
- Branch
- PR
> SCP-3519: Added API.EvaluationContext to cache costmodel computation

- shell.nix
I made haskell.nix not set this, which was possibly a mistake. For the
time being, set it locally.
Not doing this may mean that tests fail for people.
> Set LOCALE_ARCHIVE in the shell

- plutus-core/plutus-core/src/PlutusCore/Data.hs
- plutus-ledger-api/src/Plutus/V1/Ledger/Value.hs
- plutus-tx/src/PlutusTx/AssocMap.hs
- plutus-tx/src/PlutusTx/Builtins/Internal.hs
These are the datatypes we need `Data` for to make things work on what will be a change to the version of plutus-apps that depends on `release/node-1.34`.
Fixes #4449 together with #4450.
- Branch
- PR
> Instances of Data for some datatypes

- plutus-core/index-envs/src/Data/RandomAccessList/SkewBinary.hs
- plutus-core/index-envs/test/TestRAList.hs
- plutus-core/plutus-core.cabal
The skewbinary's safeIndexOne and unsafeIndexOne function lacked a case when the passed index is equal to zero.
This is fine currently for the on-chain execution, since scopechecking makes sure that the AST does not contain (Var 0) and the discharge does behave correctly.
Offchain via plutus-tx cannot trigger this, because it will abort compilation upon freevariable (0). Handcrafted uplc off-chain execution can trigger this, however.
If we follow the plan and remove scopechecking in plutus-v2, then the problem will arise. Fix it for v2 (master) but backport it as well, since it does have negligible performance impact.
- Branch
- PR
> SCP-3591: Add case for undefined behavior indexOne(Zero)

- nix/pkgs/haskell/haskell.nix
Fix `enableHaskellProfiling`. Doesn't work since https://github.com/input-output-hk/haskell.nix/commit/0e2ae928e296a68ec16adbed5e7d4f7dca815b14
- Branch
- PR
> Change enableExecutableProfiling to enableProfiling

- nix/pkgs/haskell/materialized-darwin/.plan.nix/plutus-core.nix
- nix/pkgs/haskell/materialized-linux/.plan.nix/plutus-core.nix
- nix/pkgs/haskell/materialized-windows/.plan.nix/plutus-core.nix
- plutus-core/executables/Common.hs
- plutus-core/plutus-core.cabal
- plutus-core/plutus-core/src/PlutusCore.hs
- plutus-core/plutus-core/src/PlutusCore/Error.hs
- plutus-core/plutus-core/src/PlutusCore/Parser.hs
- plutus-core/plutus-core/src/PlutusCore/Parser/Builtin.hs
- plutus-core/plutus-core/src/PlutusCore/Parser/ParserCommon.hs
- plutus-core/plutus-core/src/PlutusCore/Parser/Type.hs
- plutus-core/plutus-core/test/Spec.hs
- plutus-core/plutus-ir/src/PlutusIR/Parser.hs
- plutus-core/untyped-plutus-core/src/UntypedPlutusCore/Parser.hs
- plutus-errors/src/Errors/TH/GenCodes.hs
- plutus-errors/src/Errors/TH/GenDocs.hs
- plutus-metatheory/src/Main.lagda
- plutus-metatheory/src/Raw.hs
> SCP-3527: Address remaining PR#4349 comments

- plutus-core/plutus-core/src/PlutusCore/Builtin/Runtime.hs
- plutus-core/plutus-core/src/PlutusCore/Default/Builtins.hs
- plutus-core/plutus-core/src/PlutusCore/Evaluation/Machine/MachineParameters.hs
- plutus-ledger-api/src/Plutus/V1/Ledger/EvaluationContext.hs
A minimal version of #4435, no `readKnown` inlining, no nothing.
> [Builtins] Inline 'mkMachineParameters' in its full glory

- plutus-core/cost-model/budgeting-bench/Benchmarks/Data.hs
- plutus-core/cost-model/data/builtinCostModel.json
- plutus-core/cost-model/data/models.R
Costing `serialiseData` and `equalsData` is a little tricky because we measure the size of `Data` objects using only a single number and execution times can be very different for objects of the same size.  For example, here's a plot of serialisation times:
The red line is a regression line obtained by standard linear regression, and it clearly underestimates the serialisation times for many inputs.  This PR attempts to fit a more conservative model.  We do this by discarding everything below the line and fitting another linear model to the remaining data, repeating until we get a line which lies above at least 90% of the original data (or until we've performed twenty iterations, but with the data here we only require two iterations).  We also go to some trouble to force the fitted model …
> SCP 3619: costing for serialiseData

- plutus-core/cost-model/data/builtinCostModel.json
A massive PR for the memory cost of `serialiseData`, which I forgot to do in #4480.  We have to account for the size of the serialized object as a function of the size of the input, so I've gone for a factor of 2 to account for any overhead.  A factor of 1 would probably be safe anyway though.
> Forgot the memory usage cost for serialiseData

- plutus-core/plutus-core/src/PlutusCore/Builtin/Runtime.hs
- plutus-core/plutus-core/src/PlutusCore/Evaluation/Machine/Ck.hs
Since the HOAS evaluator is gone, we don't need that laziness anymore.
> [Builtins] Update 'BuiltinRuntime' to store the costing function strictly

- plutus-core/plutus-core/src/PlutusCore/Evaluation/Result.hs
I was looking at Core and that popped up. Let's see.
> [Evaluation] Make 'EvaluationResult' strict

- plutus-core/plutus-ir/src/PlutusIR/Compiler.hs
- plutus-core/plutus-ir/src/PlutusIR/Transform/ThunkRecursions.hs
- plutus-core/plutus-ir/test/Spec.hs
- plutus-core/plutus-ir/test/TransformSpec.hs
- plutus-core/plutus-ir/test/recursion/errorBinding
- plutus-core/plutus-ir/test/recursion/errorBinding.golden
- plutus-core/plutus-ir/test/recursion/mutuallyRecursiveValues.golden
- plutus-core/plutus-ir/test/transform/thunkRecursions/errorBinding
- plutus-core/plutus-ir/test/transform/thunkRecursions/errorBinding.golden
Identified by Max from Quviq.
The issue is that we were turning strict bindings into non-strict
bindings, which obviously... changes their strictness properties. We can
fix this by forcing the value again immediately afterwards.
I decided to be a bit more conservative and only do this when the
binding RHS might be impure, so I expect this will not change
compilation output in the vast majority of cases.
- Branch
- PR
> SCP-3696: fix ThunkRecursions for impure RHSs

- scripts/ci-plutus-benchmark.sh
They take up lots of space in PR comment threads. You can embed HTML in
Markdown, `<details>` elements work (see referenced gist), so we can
hide the table by default and expand it when we want to look at it.
Example comment that I edited to show how it looks: https://github.com/input-output-hk/plutus/pull/4507#issuecomment-1080761548
> Hide the benchmarking results table by default

- plutus-benchmark/validation/Common.hs
- plutus-core/plutus-core/examples/PlutusCore/Examples/Builtins.hs
- plutus-core/plutus-core/src/PlutusCore/Builtin/HasConstant.hs
- plutus-core/plutus-core/src/PlutusCore/Builtin/KnownType.hs
- plutus-core/plutus-core/src/PlutusCore/Builtin/Meaning.hs
- plutus-core/plutus-core/src/PlutusCore/Builtin/Runtime.hs
- plutus-core/plutus-core/src/PlutusCore/Default/Universe.hs
- plutus-core/plutus-core/src/PlutusCore/Evaluation/Machine/Ck.hs
- plutus-core/plutus-core/src/PlutusCore/Evaluation/Machine/Exception.hs
- plutus-core/plutus-ir/src/PlutusIR/Core/Type.hs
- plutus-core/untyped-plutus-core/src/UntypedPlutusCore/Core/Type.hs
- plutus-core/untyped-plutus-core/src/UntypedPlutusCore/Evaluation/Machine/Cek/Internal.hs
Returning an `ErrorWithCause` from the builtins machinery was a mistake from day 1.
This PR fixes that by attaching the cause of an actual failure (not a potential one
like before) to the error message at the call site.
> [Builtins] Factor causes out of the builtins machinery

- nix/pkgs/haskell/materialized-darwin/.plan.nix/plutus-core.nix
- nix/pkgs/haskell/materialized-linux/.plan.nix/plutus-core.nix
- nix/pkgs/haskell/materialized-windows/.plan.nix/plutus-core.nix
- plutus-core/index-envs/src/Data/RandomAccessList/Class.hs
- plutus-core/index-envs/test/RAList/Spec.hs
- plutus-core/plutus-core.cabal
It was appending things in the wrong order! In practice, this meant that
the `consSlab` property should have been failing, since it relied on the
default implementation for `List`, which should have been different.
Eventually I realised that it wasn't because for some reason I was doing
all the tests with lists of `()`, so order didn't matter! Changing it to
`Integer` caused the test to fail (and only that one, phew), and the fix
fixes it.
> Fix the default implementation of consSlab

- plutus-core/plutus-core/src/PlutusCore/Parser/Builtin.hs
As mentioned in #4368. It's similar to before the megaparsec merge, but now it parses to `DefaultFun`. 
- Branch
- PR
> Parse all DefaultFun builtin functions.

- shell.nix
Fixed since Nix version 2.6, which is widely used now.
> Remove fix for CPU affinity

- plutus-core/plutus-core/src/PlutusCore/Error.hs
- plutus-core/plutus-core/src/PlutusCore/Parser/Builtin.hs
Follow up on #4546. More proper error reporting for the builtin function parser. The parser can only deal with `DefaultFun` atm anyway so adding a `DefaultFun` specific type parameter to `UnknownBuiltinFunction` shouldn't be a problem? As we make the parser work on more functions we'll need to have `ParserError` take a `fun` argument though.
- Branch
- PR
> Improve error reporting of the builtin function parser.

- plutus-core/plutus-core/examples/PlutusCore/Examples/Builtins.hs
- plutus-core/plutus-core/src/PlutusCore/Builtin/KnownTypeAst.hs
- plutus-core/plutus-core/src/PlutusCore/Builtin/Meaning.hs
To make sure we don't unknowingly end up with another `MkNilData` and `MkNilPairData`.
> [Builtins] Throw on nullary builtins

- plutus-ledger-api/src/Plutus/V1/Ledger/EvaluationContext.hs
It seems like the worker-wrapper transformation may do more harm than good for builtins.
> [Builtins] Stop doing the worker-wrapper transformation for the denotations

- plutus-core/cost-model/budgeting-bench/Benchmarks/Nops.hs
- plutus-core/plutus-core/examples/PlutusCore/Examples/Builtins.hs
- plutus-core/plutus-core/src/PlutusCore/Builtin/HasConstant.hs
- plutus-core/plutus-core/src/PlutusCore/Builtin/Meaning.hs
- plutus-core/plutus-core/src/PlutusCore/Builtin/TestKnown.hs
- plutus-core/plutus-core/src/PlutusCore/Default/Builtins.hs
- plutus-core/plutus-core/src/PlutusCore/Evaluation/Machine/ExBudgetingDefaults.hs
- plutus-core/plutus-core/src/PlutusCore/Evaluation/Machine/MachineParameters.hs
- plutus-core/testlib/PlutusCore/Generators/Internal/Entity.hs
This polishes constraints a little separating `HasConstantIn` from a newly added `HasMeaningIn`. Not ready for review yet.
> [Builtins] Add 'HasMeaningIn'

- plutus-core/cost-model/create-cost-model/CreateBuiltinCostModel.hs
This fixes a stupid mistake.  When I added the costing function for `serialiseData` I forgot about the memory usage component (I think maybe @bezirg  pointed this out).  I "fixed" it in #4486 by modifying `builtinCostModel.json`, which is where the cost model gets read in from.  However, I failed to modify the code that produces the JSON file, so regenerating the JSON sets the memory costing function back to zero.  We haven't actually regenerated the cost model since then, so there shouldn't be a model in use anywhere that has the wrong costing function.  This PR ensures that a sensible memory cost function should be generated in future.
- Branch
- PR
> Forgot to update memory usage for serialiseData

- plutus-core/plutus-core/test/Evaluation/Spec.hs
- plutus-core/testlib/PlutusCore/Generators/Internal/Builtin.hs
The existing `genConstant :: forall a. TypeRep a -> Gen a` does not generate terms/constants of the correct type in the `Opaque` and `SomeConstant` cases - it generates arbitrary terms and Integer constants, respectively. I don't seen an easy way to correct this given the type of `genConstant`, so I reverted it back to `genConstant :: forall k (a :: k). TypeRep a -> Gen (Some (ValueOf DefaultUni))`.
> Make `genConstant` return `SomeGen`

- plutus-core/plutus-core/test/Check/Spec.hs
- plutus-core/plutus-core/test/Evaluation/Spec.hs
- plutus-core/plutus-core/test/Names/Spec.hs
- plutus-core/plutus-core/test/Normalization/Type.hs
- plutus-core/plutus-core/test/Spec.hs
- plutus-core/testlib/PlutusCore/Generators/AST.hs
so that we can test another set of function to verify that exceptions cause the test to fail.
> Make `prop_builtinsDon'tThrow` polymorphic wrt `fun`

- plutus-core/untyped-plutus-core/src/UntypedPlutusCore/Evaluation/Machine/Cek/Internal.hs
Theorem: `dischargeCekValue` is safe without `VBuiltin` storing an environment.
Proof by induction: `CekValue` has fours constructors:
1. `VCon`: doesn't require an environment for discharging
2. `VDelay`: requires an environment, but keeps one for itself
3. `VLamAbs`: requires an environment, but keeps one for itself
4. `VBuiltin`:
4.1 when initially constructed, doesn't require an environment, because it's only a `Builtin () fun` inside
4.2 within `forceEvaluate` the term inside is grown with `Force ()` which preserves the lack of need for an environment
4.3 within `applyEvaluate` the term inside is grown with `flip (Apply ()) (dischargeCekValue arg)` which preserves the lack of need for an environment as long as `dischargeCekValue arg` does, which is indeed the case by the induction …
> [Builtins] Drop 'CekValEnv' from 'VBuiltin'

- plutus-core/plutus-core/src/PlutusCore/Parser/Builtin.hs
- plutus-core/testlib/PlutusCore/Generators/AST.hs
Make `(con unit ( <spaces> ))` legal.
> Allow spaces in unit constants

- plutus-tx-plugin/src/PlutusTx/Compiler/Binders.hs
- plutus-tx-plugin/src/PlutusTx/Compiler/Builtins.hs
- plutus-tx-plugin/src/PlutusTx/Compiler/Error.hs
- plutus-tx-plugin/src/PlutusTx/Compiler/Expr.hs
- plutus-tx-plugin/src/PlutusTx/Compiler/Kind.hs
- plutus-tx-plugin/src/PlutusTx/Compiler/Laziness.hs
- plutus-tx-plugin/src/PlutusTx/Compiler/Names.hs
- plutus-tx-plugin/src/PlutusTx/Compiler/Type.hs
- plutus-tx-plugin/src/PlutusTx/Compiler/Type.hs-boot
- plutus-tx-plugin/src/PlutusTx/Compiler/Types.hs
- plutus-tx-plugin/src/PlutusTx/Compiler/Utils.hs
- plutus-tx-plugin/src/PlutusTx/Plugin.hs
This makes it possible to compile with non-unit annotations.
> Make `CompileError` annotation-polymorphic

- plutus-core/executables/Common.hs
- plutus-core/executables/plc/Main.hs
- plutus-core/plutus-core/src/PlutusCore.hs
- plutus-core/plutus-core/src/PlutusCore/Parser.hs
- plutus-core/plutus-core/src/PlutusCore/Parser/ParserCommon.hs
- plutus-core/plutus-core/test/Spec.hs
- plutus-core/plutus-ir/src/PlutusIR/Parser.hs
- plutus-core/testlib/Test/Tasty/Extras.hs
- plutus-tx-plugin/src/PlutusTx/Plugin.hs
Contributing my two cents against the global entropy.
This just moves stuff around and drops `typecheckPipeline`. No attempt to improve the moved stuff is performed.
> [Refactoring] Move junk out of 'PlutusCore'

- plutus-core/plutus-core/src/PlutusCore/Evaluation/Machine/CostModelInterface.hs
- plutus-ledger-api/plutus-ledger-api.cabal
- plutus-ledger-api/src/Plutus/ApiCommon.hs
- plutus-ledger-api/src/Plutus/V1/Ledger/EvaluationContext.hs
- plutus-ledger-api/src/Plutus/V2/Ledger/Api.hs
- plutus-ledger-api/src/Plutus/V2/Ledger/EvaluationContext.hs
- plutus-ledger-api/test/Spec.hs
- plutus-ledger-api/test/Spec/Builtins.hs
- plutus-ledger-api/test/Spec/CostModelParams.hs
- plutus-ledger-api/testlib/Plutus/Ledger/Test/EvaluationContext.hs
For each api version, we create an enumeration datatype that attaches a "tag/label" to the otherwise
untyped array of costmodel params coming from the ledger , i.e. `[Integer]`.
Each tag/label is a nullary constructor in the enumeration datatype and the order of its appearance matters.
Also some "dt-generic" code to derive a human-readable/JSON key name for such nullary constructors (tags).
This will hopefully allow us to be more flexible in future versions (V3) , so that we can define our own costmodel param ordering and not rely/assume/expect an alphabetical order of cost model parameter names.
- Branch
- PR
> PLT-110: Expose V1/V2 cost model param names as fixed enumeration

- plutus-tx-plugin/src/PlutusTx/Plugin.hs
- plutus-tx/src/PlutusTx/Foldable.hs
See the added note for the reason.
This will need to be cherry-picked to `release/node-1.34`
> Avoid newtype field accessors in `base`

- plutus-core/plutus-core/src/PlutusCore/Builtin/Debug.hs
- plutus-core/plutus-core/src/PlutusCore/Builtin/Elaborate.hs
- plutus-core/plutus-core/src/PlutusCore/Builtin/Meaning.hs
- plutus-core/plutus-core/src/PlutusCore/Builtin/Polymorphism.hs
This polishes the `PlutusCore.Builtin.Meaning` module and adds another tool to `PlutusCore.Builtin.Debug` allowing us to debug the whole `BuiltinMeaning` inference pipeline.
> [Builtins] Add 'MakeBuiltinMeaning' and type errors doctests

- scripts/ci-plutus-benchmark.sh
We have [some reasons](https://github.com/input-output-hk/plutus/pull/4650#issuecomment-1139545881) to believe that this may make the benchmark more accurate.
- Branch
- PR
> Add cabal clean before running benchmark.

- plutus-core/plutus-ir/src/PlutusIR/TypeCheck/Internal.hs
- plutus-core/plutus-ir/test/types/listMatch.golden
- plutus-core/plutus-ir/test/types/maybe.golden
- plutus-core/plutus-ir/test/types/mutuallyRecursiveTypes.golden
This removes all calls to `rename` (1 of them) from the PIR type checker.
> [TypeCheck] Remove all calls to 'rename' from the PIR type checker

- .github/workflows/test.yml
We just bumped to the latest install-nix-action which has version 2.8
which hopefully doesn't have the problem.
> Remove a nix version workaround

- plutus-core/untyped-plutus-core/src/UntypedPlutusCore/Evaluation/Machine/Cek/Internal.hs
- plutus-core/untyped-plutus-core/test/Evaluation/Golden/diFullyApplied.uplc.golden
- plutus-core/untyped-plutus-core/test/Evaluation/Golden/polyErrorInst.uplc.golden
In particular, try to make it obvious that the overspent budget error
arises in the middle of execution, and that the budget state printed
just represents the immediate overspent budget, and not the amount
needed to run the script to completion.
> Improve the error messages from the CEK machine

- plutus-core/cost-model/budgeting-bench/Benchmarks/Nops.hs
- plutus-core/cost-model/create-cost-model/CreateBuiltinCostModel.hs
- plutus-core/plutus-core/examples/PlutusCore/Examples/Builtins.hs
- plutus-core/plutus-core/src/PlutusCore/Builtin/HasConstant.hs
- plutus-core/plutus-core/src/PlutusCore/Builtin/KnownType.hs
- plutus-core/plutus-core/src/PlutusCore/Builtin/Polymorphism.hs
- plutus-core/plutus-core/src/PlutusCore/Default/Builtins.hs
- plutus-core/prelude/PlutusPrelude.hs
I've been annoyed by this since forever and I just finally realized that we can make a single function work for both `SomeConstant` and `Opaque`, hence this tiny refactoring.
> [Builtins] Add 'fromValue' and 'fromValueOf'

- shell.nix
so that in the nix shell we have nix's pre-commit, not the one in your `.local/bin` installed from pip, which for some reason doesn't work in the nix shell.
> Add pre-commit to shell.nix

- plutus-tx-plugin/src/PlutusTx/Annotation.hs
- plutus-tx-plugin/src/PlutusTx/Compiler/Binders.hs
- plutus-tx-plugin/src/PlutusTx/Compiler/Builtins.hs
- plutus-tx-plugin/src/PlutusTx/Compiler/Expr.hs
- plutus-tx-plugin/src/PlutusTx/Compiler/Names.hs
`compileVarFresh` should not assume that the `VarDecl` it creates should be annotated `AnnOther`. The caller should decide that.
This PR also makes sure all calls to `TermBind` constructor uses the correct annotation, since that's what the inliner looks at. This doesn't affect any existing test because we aren't inlining many things, but it's the right thing to do.
> PLT-279: Make compileVarFresh take an annotation

- plutus-core/plutus-core/src/PlutusCore/Normalize.hs
- plutus-core/plutus-core/src/PlutusCore/Normalize/Internal.hs
- plutus-core/plutus-core/src/PlutusCore/TypeCheck.hs
- plutus-core/plutus-core/src/PlutusCore/TypeCheck/Internal.hs
- plutus-core/plutus-ir/src/PlutusIR/TypeCheck.hs
- plutus-core/plutus-ir/src/PlutusIR/TypeCheck/Internal.hs
I wanted to remove the unnecessary `MonadQuote` from the kind checker, but ended up refactoring the type checker constraints in general.
> [TypeCheck] Clean up constraints

- plutus-ledger-api/testlib/PlutusLedgerApi/Test/EvaluationEvent.hs
This means the evaluation context only needs to be created once per multiple events, which leads to significant speedup.
> PLT-108: Share cost parameters among multiple script evaluation events

- scripts/s3-sync-unzip.sh
- shell.nix
Based on comment https://github.com/input-output-hk/plutus/pull/4692/files#r896901361, separating the downloader out. 
This downloads s3 objects with the given prefix and suffix to a local dir (skipping objects that exist locally), and unzips all bz2 files in the local dir.
> PLT-108: Script for downloading Plutus script dump from S3

- plutus-core/untyped-plutus-core/src/UntypedPlutusCore/Evaluation/Machine/Cek/Internal.hs
- plutus-core/untyped-plutus-core/test/Evaluation/Golden/diFullyApplied.uplc.golden
- plutus-core/untyped-plutus-core/test/Evaluation/Golden/polyErrorInst.uplc.golden
In particular, try to make it obvious that the overspent budget error
arises in the middle of execution, and that the budget state printed
just represents the immediate overspent budget, and not the amount
needed to run the script to completion.
- Branch
- PR
> Improve the error messages from the CEK machine (#4667)

- nix/pkgs/haskell/materialized-darwin/.plan.nix/plutus-core.nix
- nix/pkgs/haskell/materialized-linux/.plan.nix/plutus-core.nix
- nix/pkgs/haskell/materialized-windows/.plan.nix/plutus-core.nix
- plutus-core/plutus-core.cabal
- plutus-core/untyped-plutus-core/src/UntypedPlutusCore/Core/Instance/Flat.hs
- plutus-core/untyped-plutus-core/test/Spec.hs
- plutus-ledger-api/src/Plutus/ApiCommon.hs
- plutus-ledger-api/src/Plutus/V1/Ledger/Scripts.hs
- plutus-ledger-api/test/Spec/Builtins.hs
The way flat encodes bytestrings _already_ effects a size limit because
it serializes them in chunks. This is
good enough for our purposes, and we can just remove the additional size
check that we do, after all that!
> Backport: Remove the V2 size limit

- plutus-core/plutus-core.cabal
- plutus-core/plutus-core/src/PlutusCore/Data.hs
The ByteString can have arbitrary bytes, and printing via `Show` isn't very pretty.
> Base64-encode ByteString in `Pretty Data`

- plutus-core/plutus-core.cabal
- plutus-core/untyped-plutus-core/src/UntypedPlutusCore/Core/Instance/Flat.hs
- plutus-core/untyped-plutus-core/test/Spec.hs
- plutus-ledger-api/src/PlutusLedgerApi/Common/SerialisedScript.hs
- plutus-ledger-api/src/PlutusLedgerApi/V1/Scripts.hs
- plutus-ledger-api/test/Spec/Builtins.hs
The way flat encodes bytestrings _already_ effects a size limit. This is good enough for our purposes, so we can just remove the size limit entirely.
> Remove the V2 size limit

- plutus-conformance/add-test-output/Spec.hs
I've checked locally that this looks a lot better than before even though we now don't have word-wrapping. 
- Branch
- PR
> Fix add-test-output's help text formatting.

- plutus-core/plutus-core/src/PlutusCore/Builtin/Meaning.hs
- plutus-ledger-api/src/PlutusLedgerApi/Common/Eval.hs
Doesn't really make much of a difference in terms of performance as shown by benchmarking, but this makes it so that there's fewer thunks in `EvaluationContext`, which makes writing `NoThunks` instance easier.
> PLT-370: Make EvaluationContext more strict

- plutus-core/untyped-plutus-core/src/UntypedPlutusCore/Core/Instance/Flat.hs
- plutus-ledger-api/src/PlutusLedgerApi/Common/SerialisedScript.hs
- plutus-ledger-api/src/PlutusLedgerApi/Common/Versions.hs
- plutus-tx-plugin/test/Lib.hs
- plutus-tx/src/PlutusTx/Code.hs
- plutus-tx/testlib/PlutusTx/Test.hs
Make the predicate an error-producing function so we can give an error
with more context.
> PLT-272: Give a better error when builtins aren't available

- plutus-core/plutus-core.cabal
- plutus-core/plutus-core/src/Crypto.hs
- plutus-core/plutus-core/src/PlutusCore/Default/Builtins.hs
- plutus-core/untyped-plutus-core/test/Evaluation/Builtins/Definition.hs
- plutus-core/untyped-plutus-core/test/Evaluation/Builtins/SignatureVerification.hs
- plutus-metatheory/src/Builtin.lagda.md
- plutus-tx/src/PlutusTx/Builtins/Internal.hs
This is PLT-586 (wrong issue number in the branch name).  It changes the return type of the current version of `verifyEd25519Signature` from `Maybe Bool` to `Emitter (EvaluationResult Bool)`.  This (a) makes it compatible with the `Secp256k1` verification signature verification functions (which log details if something goes wrong, like encountering a malformed signature or a public key of the wrong size (hence the `Emitter` type)), and (b) will make it easier to update to a different implementation using `libsodium` (PLT-162), since both versions will have the same type. 
When/if we merge this I'll close #4606 and replace it with a PR with a much smaller diff.
> Kwxm/plt 585/update verify ed25519 signature return type

- plutus-ledger-api/src/PlutusLedgerApi/V1/Value.hs
In #2880, the standard `Show` instance for `Value` was replaced with a normalizing one.
Recently, it was discovered that it might be confusing to deal with values:
```
> A.singleton "0abc" "0abc" 1
Value (Map [(0abc,Map [("0abc",1)])])
> lovelaceValueOf 0 <> A.singleton "0abc" "0abc" 1
Value (Map [(0abc,Map [("0abc",1)])])
> getValue $ lovelaceValueOf 0 <> A.singleton "0abc" "0abc" 1
Map {unMap = [(,Map {unMap = [("",0)]}),(0abc,Map {unMap = [("0abc",1)]})]}
> getValue $ A.singleton "0abc" "0abc" 1
Map {unMap = [(0abc,Map {unMap = [("0abc",1)]})]}
```
it hides the evidence about zero tokens (with any symbol, not only ada) and contradicts the usual expectation of `Show`'s behaviour to be able to see the whole structure as is.
---
**Before:**
```
> singleton adaSymbol adaToken 0
Value (Map …
```
> Use the standard deriving Show instance for Value

- plutus-core/cost-model/budgeting-bench/CriterionExtensions.hs
- plutus-core/cost-model/budgeting-bench/Main.hs
This fixes a problem where the CSV output from the cost model benchmarking process was being split into two files. This is a quick fix: PLT-202 should provide a better solution when we get round to it.
> Fix CSV file output problem in cost model benchmarking

- plutus-conformance/agda/Spec.hs
- plutus-conformance/haskell/Spec.hs
- plutus-conformance/plutus-conformance.cabal
- plutus-conformance/src/PlutusConformance/Common.hs
- refactored into using the golden test function instead of a custom `IsTest` instance. This is cleaner especially when we add more types of tests down the road.
- the expected to fail tests are now marked with their filepath, not their names.
- the UPLC evaluation tests now test alpha-equivalence of programs instead of comparing them textually. This **hasn't** fixed the failing Agda `churchZero` test yet because the Agda evaluator is actually returning a not alpha-equivalent program to the expected one. It seems the Agda evaluator has a bug relating to the off-by-one debruijn discrepancy we have in plutus-core.
- with this merged once we fix the bug `churchZero` should be fixed. If not, there's a bug in checking the alpha-equivalence and we should fix it.
- Branch
- …
> PLT-572 Check alpha-equivalence of programs in conformance tests

- plutus-conformance/README.md
- plutus-conformance/agda/Spec.hs
- plutus-core/testlib/PlutusCore/Generators/NEAT/Spec.hs
- plutus-core/testlib/PlutusCore/Generators/NEAT/Term.hs
- plutus-metatheory/src/Main.lagda
- plutus-metatheory/test/TestNEAT.hs
As discussed(see the updated readme), I'm changing the agda implementation to throw an error instead of returning the `error` term.
- changed the agda implementation to throw an error instead of returning the `error` term.
- removed the fixed tests from the expected failure list.
- updated readme.
- fixed NEAT term level test that was failing because it's now throwing an error instead of returning the `error` term.  The fix is to catch the error and return the `error` term for those tests. It's a bit hacky but it's inline with what those tests do elsewhere. (Thanks @effectfully)
- Branch
- PR
> PLT-571 Fix failing agda conformance tests regarding returning error terms.

- plutus-core/plutus-core/src/PlutusCore/Evaluation/Machine/CostModelInterface.hs
- plutus-ledger-api/plutus-ledger-api.cabal
- plutus-ledger-api/src/PlutusLedgerApi/Common/ParamName.hs
- plutus-ledger-api/src/PlutusLedgerApi/V1/EvaluationContext.hs
- plutus-ledger-api/src/PlutusLedgerApi/V1/ParamName.hs
- plutus-ledger-api/src/PlutusLedgerApi/V2/EvaluationContext.hs
- plutus-ledger-api/src/PlutusLedgerApi/V2/ParamName.hs
- plutus-ledger-api/src/PlutusLedgerApi/V3/EvaluationContext.hs
- plutus-ledger-api/src/PlutusLedgerApi/V3/ParamName.hs
- plutus-ledger-api/test-onchain-evaluation/Main.hs
- plutus-ledger-api/test/Spec/CostModelParams.hs
- plutus-ledger-api/test/Spec/NoThunks.hs
This PR changes the logic of receiving costmodel parameters to the ledger. We need this if we are planning to introduce new builtins in an existing plutus language.
Before:
```
received_from_ledger == expected = success
otherwise = error
```
After:
```
received_from_ledger == expected = success
received_from_ledger > expected = warning
received_from_ledger < expected = error
```
- Branch
- PR
> PLT-576: Be permissive when receiving too many cm params from the ledger

- plutus-core/plutus-core/src/PlutusCore/Default/Builtins.hs
- plutus-core/untyped-plutus-core/test/Evaluation/Builtins/Definition.hs
- plutus-core/untyped-plutus-core/test/Evaluation/Builtins/SignatureVerification.hs
This is PLT-585.  Previously PLT-167 (#4771) added an alternative implementation for `verifyEd25519Signature` which uses `caradno-base` instead of `cardano-crypto`; this just hooks it up to Nikos' versioned builtins PR, so it's pretty straightforward. See PLT-728 for a path towards getting rid of the old version completely. 
The most complicated part was updating the tests to test both versions.  The tests are based on those provided by Koz Ross for the SCP functions and are quite extensive (they take about 40 seconds per function on my laptop).  I've added a separate test for each version of `verifyEd255519Signature`. Having two lots of tests might add some maintenance burden since we'll need to make sure that they stay synchronised with the various `DefaultFun` versions.  @effectfully …
> Kwxm/ed25519-v1-v2 (PLT-585)

- plutus-tx/src/PlutusTx/List.hs
- plutus-tx/test/Spec.hs
The plugin can't compile list range syntax, so adding a helper function.
> PLT-760: Add PlutusTx.List.fromRange

- plutus-ledger-api/src/PlutusLedgerApi/V1/Scripts.hs
- plutus-ledger-api/test/Spec/Eval.hs
as well as functions that use it.
`evaluateScript` uses default parameters, and assumes a particular BuiltinVersion, Plutus Version and Protocol Version. It definitely shouldn't be used in non-test code, and even in test code it's not that useful. One should instead use `evaluateScriptCounting` or `evaluateScriptRestricting`.
> PLT-557: Remove `evaluateScript` from ledger api

- doc/reference/cardano/language-changes.rst
This is my cleaned-up "take 2" version of this PR. The only change is to this file: 
language-changes.rst
in order to remove the two references to the secp256k1 builtins.
> removed references to the two secp256k1 builtins

- plutus-ledger-api/src/PlutusLedgerApi/V1/Bytes.hs
- plutus-ledger-api/src/PlutusLedgerApi/V1/Contexts.hs
- plutus-ledger-api/src/PlutusLedgerApi/V1/Credential.hs
- plutus-ledger-api/src/PlutusLedgerApi/V1/Crypto.hs
- plutus-ledger-api/src/PlutusLedgerApi/V1/DCert.hs
- plutus-ledger-api/src/PlutusLedgerApi/V1/Scripts.hs
- plutus-ledger-api/src/PlutusLedgerApi/V1/Time.hs
- plutus-ledger-api/src/PlutusLedgerApi/V1/Tx.hs
- plutus-ledger-api/src/PlutusLedgerApi/V1/Value.hs
- plutus-tx/src/PlutusTx/IsData/Class.hs
The purpose of this is to add/update the Haddock of some functions in the plutus-ledger-api. Closes #4476, closes #4801.
Haddock is added to types mentioned in the issues roughly following this format:
- What is it?
- Its hash algorithm, if any
- No. of bytes, if applicable
- Add warning that these types are simple types without any validation.
- Links to relevant info/spec
I've tried to verify the added info against the spec/code but @michaelpj and @JaredCorduan could you please confirm all the info are accurate. 
@JaredCorduan regarding [your comment](https://github.com/input-output-hk/plutus/issues/4476#issuecomment-1209294094), could you please let us know when the appendix is added so we can add links to the Haddock? Thanks.
I've included most types mentioned in #4476 and #4801. More …
> PLT-712: Update and add Haddock to some functions in `plutus-ledger-api`.

- plutus-core/plutus-core.cabal
This change rules out cabal build plans that pick up `hashable < 1.4` (which won't compile anyway).
- Branch
- PR
Closes #4855
> Hashable extends Eq starting from hashable 1.4

- plutus-conformance/agda/Spec.hs
- plutus-metatheory/src/Untyped.hs
Fixed all the failing tests relating to Debruijn indices. There's a separate ticket for the other failing tests - they are failing with the evaluator throwing an error, so that requires another fix.
Added some comments and removed some seemingly dead code.
- Branch
- PR
> PLT-579 Fix some tests that are failing on `agda-conformance`

- plutus-conformance/README.md
- plutus-conformance/agda/Spec.hs
- plutus-conformance/executables/add-test-output/Spec.hs
- plutus-conformance/executables/test-utils/Spec.hs
- plutus-conformance/plutus-conformance.cabal
- plutus-conformance/src/PlutusConformance/Common.hs
Added a debugging mode to investigate some failed tests.
I removed the "all or missing" option for adding tests - it doesn't fit with the debugging mode and it adds minimum value because we all use git so we know which files are changed anyway.  
- Branch
- PR
> Add debugging mode to conformance test suite executable.

- plutus-conformance/agda/Spec.hs
- plutus-metatheory/src/Untyped/CEK.lagda.md
This adds support for `chooseUnit` to the metatheory and a template for adding support for all other missing builtins. I've restructured `BUILTIN` to make it exhaustively match on builtins, so that we it's clear which builtins are handled and which are not.
> [Metatheory] [Builtins] Add support for 'chooseUnit'

- plutus-core/cost-model/test/TestCostModels.hs
- plutus-core/plutus-core/src/PlutusCore/Evaluation/Machine/ExMemory.hs
Looking at PLT-953 (moving the cost model code into a separate Cabal component/package), I noticed that the cost model tests (which aren’t run in CI because of sporadic failures) were failing most of the time.  These tests run the Haskell costing functions for builtins and compare the results with predictions obtained directly from the R models, checking that they agree to within a small margin of error.  
The reason that they were failing is because #4778 changed the costing code to take objects as arguments where they’d previously taken sizes: the new version calculates the sizes itself.  Unfortunately there was an existing `ExMemoryUsage` instance for `ExMemory` which meant that the testing code continued to compile, but the Haskell costing functions were being fed the sizes of sizes, …
> PLT-956: Fix cost model tests

- plutus-ledger-api/test-onchain-evaluation/README.md
A brief description of how to generate event dumps and run the tests.
> README on mainnet script evaluation tests

- plutus-errors/src/Errors.hs
- plutus-tx/plutus-tx.cabal
- plutus-tx/src/PlutusTx/Lift.hs
- plutus-tx/src/PlutusTx/Lift/Class.hs
- plutus-tx/src/PlutusTx/Lift/Instances.hs
- plutus-tx/src/PlutusTx/Lift/TH.hs
This matches the other classes, so the `Class` file just has the classes and the straightforward instances.
> Lift: move TH to its own file

- plutus-core/executables/Common.hs
- plutus-core/executables/Parsers.hs
- plutus-core/executables/pir/Main.hs
- plutus-core/executables/plc/Main.hs
- plutus-core/executables/uplc/Main.hs
- plutus-core/plutus-ir/src/PlutusIR/Core/Type.hs
- plutus-core/plutus-ir/src/PlutusIR/TypeCheck/Internal.hs
- fix line lengths of the files I touched. I apologize that it's making the diff harder to read. I will separate out these commits to another PR next time.
- tidy PIR executable:
- add a type that specifies the input and output paths and and use it in the print function and other places. The print function now lets you specify the output path also in all three executables (PLC, UPLC, and PIR).
- add a `PirProg` instance to the `Executable` typeclass.
- use the `Common` functions in PIR.
- add convert option to PIR executable.
- the `DumpModel` function can be easily added in one line but I'm not sure if we want that function in PIR.
- update the program description.
- rename `Executable` typeclass to `PlutusProgram` because these don't need to just apply to the executables. We can decide …
> PLT-122 Tidy up PIR executable

- notes/fomega/cek-cps-experiments/run-all
- notes/fomega/lazy-machine/benchmarking/run-fac
- notes/fomega/lazy-machine/benchmarking/run-fib
- notes/fomega/lazy-machine/benchmarking/run-loop
- notes/fomega/lazy-machine/benchmarking/run-max
- notes/fomega/lazy-machine/benchmarking/run-tri
Running `pre-commit run --all-files` fails.
There are 2 PNGs that are 0 bytes (deleted by this diff).
And most shell files don't pass shellcheck (I suppose we don't care to fix them up, so I've added the ignore pragma to each).
I suspect that these files either were committed before pre-commit was put in place, or they were committed in spite of the pre-commit failure.
> Remove zero-byte PNGs and add shellcheck ignore pragma where appropriate

- CONTRIBUTING.adoc
- __std__/cells/plutus/library/plutus-project.nix
- cabal.project
- flake.lock
- flake.nix
- nix/pkgs/haskell/default.nix
- nix/pkgs/haskell/haskell.nix
- nix/sources.nix
- plutus-core/plutus-core.cabal
This switches us to getting our packages from CHaP, rather than using `source-repository-package`s, which should be much easier in the long run.
@zliu41 I didn't mention anything about releasing _to_ CHaP, which I think could just go into https://github.com/input-output-hk/plutus/pull/4885. It's pretty easy, we can just link to https://github.com/input-output-hk/cardano-haskell-packages#-from-github
> Switch plutus to use CHaP

- __std__/cells/plutus/devshells/plutus-shell.nix
After integrating CHaP, `nix develop` stopped working on Darwin. 
That is, running `cabal build all` would yield:
```
Error: cabal: Could not resolve dependencies:
[__0] trying: plutus-core-1.0.0.0 (user goal)
[__1] next goal: inline-r (dependency of plutus-core)
[__1] rejecting: inline-r-0.10.5, inline-r-0.10.4, inline-r-0.10.3,
inline-r-0.10.2, inline-r-0.10.1, inline-r-0.10, inline-r-0.9.2,
inline-r-0.9.1, inline-r-0.9.0.2, inline-r-0.9.0.1, inline-r-0.9.0.0,
inline-r-0.8.0.1, inline-r-0.8.0.0, inline-r-0.7.3.0, inline-r-0.7.2.0,
inline-r-0.7.1.2, inline-r-0.7.1.1, inline-r-0.7.1.0, inline-r-0.7.0.0
(conflict: pkg-config package libR>=3.0, not found in the pkg-config database)
[__1] fail (backjumping, conflict set: inline-r, plutus-core)
After searching the rest of the dependency tree …
```
> Add pkg-config to the shell

- __std__/cells/plutus/library/make-plutus-shell.nix
- doc/RELEASE.adoc
- scripts/update-versions.sh
- shell.nix
Usage: `./scripts/update-versions.sh x.y.z.w`. This updates versions in selected cabal files to `x.y.z.w`, and version bounds in all cabal files to `^>=x.y`.
> PLT-1061: Script for updating versions and version bounds in cabal files

- cabal.project
- flake.lock
Index state 2022-10-15T00:00:00Z does not exist in CHaP anymore.
> Bump CHaP after reset

- flake.lock
For https://github.com/input-output-hk/haskell.nix/pull/1766, which will hopefully deal with the corruption issue that's causing random failures.
- Branch
- PR
> Bump haskell.nix

- plutus-core/cost-model/CostModelGeneration.md
- plutus-core/cost-model/test/TestCostModels.hs
PLT-603 is an issue to check that the order of [steps 8 and 9 ](https://github.com/input-output-hk/plutus/blob/master/plutus-core/cost-model/CostModelGeneration.md#step-8-test-the-haskell-versions-of-the-costing-functions) in `CostModelGeneration.md` is correct.  I think that this issue was prompted by a question (some time ago) from @zliu41.
I believe that the order is correct (run the tests _before_ updating the cost model file), but I got a bit confused myself so I've expanded a comment a bit to clarify what's going on, and I'm also appending a detailed comment from PLT-603 below.  I've also added a new issue at PLT-1250 to add  test that cost model serialisation/deserialisation is correct, which would fill in the gap in the testing mentioned below.  
> As explained …
> Update comment on cost model tests

- nix/cells/automation/library/plutus-benchmark-runner.nix
- nix/cells/automation/pipelines.nix
Some invocations have been failing because of the benchmark name having newlines ex: https://cicero.ci.iog.io/invocation/c8c2aaba-83f6-4e7b-ac0b-215c08bef970
- Branch
- PR
> fix(ci/benchmark): export script config

- plutus-core/plutus-core.cabal
`brick` does not build there. Otherwise CI fails because it can't
resolve dependencies for the cross build.
- Branch
- PR
> Make the debugger not buildable on windows

- doc/read-the-docs-site/reference/writing-scripts/compiler-options-table.rst
- plutus-tx-plugin/app/GeneratePluginOptionsDoc.hs
- plutus-tx-plugin/src/PlutusTx/Compiler/Types.hs
- plutus-tx-plugin/src/PlutusTx/Options.hs
- plutus-tx-plugin/src/PlutusTx/Plugin.hs
Once we have the debugger, the `debug` option will be confusing - it could be thought of as the option for producing Plutus Core with SrcSpan annotations.
> PLT-456: Combine `verbose` and `debug` compiler options into `verbosity`

- plutus-metatheory/src/Algorithmic/Evaluation.lagda
- plutus-metatheory/src/Main.lagda
- plutus-metatheory/test/TestSimple.hs
The `TestSimple.hs` file should test succeeding  and non-succeeding examples.
The current tests fails to do that:
The first failing test should have failed, because `plc-agda` terminated successfully, but succeeded and finished test execution.
This PR:
* Fixes the agda code to actually fail.
* Corrects the tests to actually tests all the evaluation modes.
* Typechecking tests now working.  
- Branch
- PR
> PLT-1319 Fix TestSimple to actually work

- CONTRIBUTING.adoc
- cabal.project
- doc/read-the-docs-site/plutus-doc.cabal
- flake.lock
- nix/cells/plutus/library/r-overlay.nix
- plutus-benchmark/plutus-benchmark.cabal
- plutus-core/plutus-core.cabal
- plutus-ledger-api/plutus-ledger-api.cabal
- plutus-tx-plugin/plutus-tx-plugin.cabal
- plutus-tx/plutus-tx.cabal
Tested with&without nix, with ghc9.2 & ghc 8.10 and R 4.2, R 4.1.
I did not test on Mac and Win. Perhaps it does not work in Win.
Bumping hackage-nix was not required, but I left it there.
- Branch
- PR
> PLT-1057: update R and inline-r. Bump hackage-nix haskell-nix

- .github/workflows/add-triage-label.yml
This does what it says.  The YAML code is based on the example [here](https://docs.github.com/en/actions/managing-issues-and-pull-requests/adding-labels-to-issues).
> GitHub action to add "status: needs triage" label to new issues

- cabal.project
The second index-state stanza completely ovverides the first, resetting hackage index state to HEAD. See haskell/cabal#8568
- Branch
- PR
> Fix index-state syntax

- plutus-core/cost-model/budgeting-bench/Benchmarks/Nops.hs
- plutus-core/cost-model/budgeting-bench/Common.hs
- plutus-core/plutus-core/src/PlutusCore/Evaluation/Machine/ExBudgetingDefaults.hs
- plutus-core/plutus-core/src/PlutusCore/Evaluation/Machine/MachineParameters.hs
- plutus-core/plutus-core/src/PlutusCore/Evaluation/Machine/MachineParameters/Default.hs
- plutus-core/untyped-plutus-core/src/UntypedPlutusCore/Evaluation/Machine/Cek.hs
- plutus-core/untyped-plutus-core/src/UntypedPlutusCore/Evaluation/Machine/Cek/Internal.hs
- plutus-core/untyped-plutus-core/test/Evaluation/Builtins/Common.hs
- plutus-core/untyped-plutus-core/test/Evaluation/Machines.hs
I would like to have `ann` available in CEK's Term, because then I can share more between the canonical cek and the debuggable-steppable cek.
Originally, I put `ann` everywhere both in the `Term`s that come in the CEK and the `Term`s that come out of the CEK.
@effectfully pointed to me that the out-Terms should remain as-is, i.e. with `ann`==`()` . This implies that the dischargeCekValue/Env functions have to be constrained to `()` and that had me put some `void`s over there. I don't like these `void`s there but discharge should suppose to be lazy anyway.
- Branch
- PR
> Generalize CEK input-term annotations

- plutus-core/cost-model/budgeting-bench/Common.hs
- plutus-core/plutus-core/src/PlutusCore/Builtin/Meaning.hs
- plutus-core/plutus-core/src/PlutusCore/Builtin/Runtime.hs
- plutus-core/plutus-core/src/PlutusCore/Evaluation/Machine/Ck.hs
- plutus-core/plutus-core/src/PlutusCore/Evaluation/Machine/MachineParameters/Default.hs
- plutus-core/untyped-plutus-core/src/UntypedPlutusCore/Evaluation/Machine/Cek.hs
- plutus-core/untyped-plutus-core/src/UntypedPlutusCore/Evaluation/Machine/Cek/Internal.hs
> [Builtins] [Evaluation] Drop lookups

- plutus-conformance/README.md
In all files the actual term is "evaluation failure" and not error. It is unclear which part is incorrect but its at least not consistent in the current state.
- Branch
- PR
> Fix typo (?) in README

- plutus-core/plutus-ir/src/PlutusIR/Transform/Beta.hs
- plutus-core/plutus-ir/src/PlutusIR/Transform/Inline/UnconditionalInline.hs
The comments that are removed mentioned SCP-2570, which became [PLT-126](https://input-output.atlassian.net/browse/PLT-126) and it was done in PR #4592.
Because of that work, it is no longer necessary to do a pattern match for `TyInst` in the inliner, because it would have turned into a type let binding and be caught in the earlier pattern for let bindings.
I also re-organize the comments a bit because there were some mis-placements. I also fixed the line lengths of `Beta.hs` in a separate commit.
- Branch
- PR
[PLT-126]: https://input-output.atlassian.net/browse/PLT-126?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Remove redundant type beta reduction in inliner.

- nix/cells/plutus/library/make-plutus-project.nix
Building plutus core fails on mac, because it doesn't find the R library.
```
Error: cabal: Could not resolve dependencies:
[__0] trying: plutus-core-1.1.1.0 (user goal)
[__1] rejecting: plutus-core:-with-inline-r (constraint from config file,
command line flag, or user target requires opposite flag selection)
[__1] trying: plutus-core:+with-inline-r
[__2] next goal: inline-r (dependency of plutus-core +with-inline-r)
[__2] rejecting: inline-r-1.0.0.0.0.0.0.1 (conflict: pkg-config package
libR>=3.0, not found in the pkg-config database)
[__2] rejecting: inline-r-1.0.0, inline-r-0.10.5, inline-r-0.10.4,
inline-r-0.10.3, inline-r-0.10.2, inline-r-0.10.1, inline-r-0.10,
inline-r-0.9.2, inline-r-0.9.1, inline-r-0.9.0.2, inline-r-0.9.0.1,
inline-r-0.9.0.0, inline-r-0.8.0.1, inline-r-0.8.0.0, …
```
> Fix nix to build on mac

- plutus-core/common/Annotation.hs
- plutus-core/common/PlutusCore/InlineUtils.hs
- plutus-core/executables/debugger/Event.hs
- plutus-core/executables/debugger/Main.hs
- plutus-core/executables/uplc/Main.hs
- plutus-core/plutus-core.cabal
- plutus-core/plutus-core/src/PlutusCore/DeBruijn/Internal.hs
- plutus-core/plutus-ir/src/PlutusIR/Compiler/Provenance.hs
- plutus-core/plutus-ir/src/PlutusIR/Compiler/Types.hs
- plutus-core/plutus-ir/src/PlutusIR/Transform/Inline/UnconditionalInline.hs
- plutus-core/plutus-ir/src/PlutusIR/Transform/Inline/Utils.hs
- plutus-core/untyped-plutus-core/src/UntypedPlutusCore/Evaluation/Machine/Cek/Debug/Driver.hs
- plutus-core/untyped-plutus-core/src/UntypedPlutusCore/Evaluation/Machine/Cek/Debug/Internal.hs
- plutus-core/untyped-plutus-core/src/UntypedPlutusCore/Transform/Inline.hs
- plutus-core/untyped-plutus-core/test/Evaluation/Debug.hs
- plutus-core/untyped-plutus-core/test/Evaluation/Debug/ex1.golden
- plutus-core/untyped-plutus-core/test/Evaluation/Debug/ex2.golden
- plutus-core/untyped-plutus-core/test/Spec.hs
- plutus-tx-plugin/plutus-tx-plugin.cabal
- plutus-tx-plugin/src/PlutusTx/Compiler/Expr.hs
- plutus-tx-plugin/src/PlutusTx/Compiler/Types.hs
- plutus-tx-plugin/src/PlutusTx/PIRTypes.hs
- plutus-tx-plugin/src/PlutusTx/PLCTypes.hs
- plutus-tx/src/PlutusTx/Code.hs
Prototype of the debugger backend. 
1) the `CEK.Internal` is duplicated  to `Cek.Debug.Internal` and the recursive step functions are modified to immediately stop and return a `CekState`.
2) An adapter/driver (written as free-monad) wraps the `Cek.Debug.Internal` : the adapter receives `Command`s from the debug-client and steps the CEK forward (one or more times).
3) A client feeds commands to the adapter and interprets the adapter's free monad actions.
Three different debug-clients are written:  MOCK for testing,  CLI connected to uplc executable, and BRICK for curses style debugging.
The input terms of the `Cek.Internal` and `Cek.Debug.Internal` remain agnostic of the input's `ann`otations.
The adapter that sits on top of `Cek.Debug.Internal` constrains this `ann` by `Breakpointable ann …
> PLT-458: Prototype of the debugger "backend"

- plutus-core/cost-model/budgeting-bench/Benchmarks/Nops.hs
- plutus-core/cost-model/budgeting-bench/Common.hs
- plutus-core/plutus-core/src/PlutusCore/Evaluation/Machine/ExBudgetingDefaults.hs
- plutus-core/plutus-core/src/PlutusCore/Evaluation/Machine/MachineParameters.hs
- plutus-core/plutus-core/src/PlutusCore/Evaluation/Machine/MachineParameters/Default.hs
- plutus-core/untyped-plutus-core/src/UntypedPlutusCore/Evaluation/Machine/Cek.hs
- plutus-core/untyped-plutus-core/src/UntypedPlutusCore/Evaluation/Machine/Cek/Internal.hs
- plutus-core/untyped-plutus-core/test/Evaluation/Builtins/Common.hs
Just a tiny one. Now that `CkValue` and `CekValue` take a different number of arguments, it's even more pronounced that we shouldn't insist a particular kind on the type of values. Which is something we only do in `MachineParameters` as far as I'm aware, hence this PR fixing that.
> [Costing] Drop 'uni' and 'ann' from 'MachineParameters

- plutus-core/executables/debugger/Draw.hs
- plutus-core/executables/debugger/Event.hs
- plutus-core/executables/debugger/Main.hs
- plutus-core/executables/debugger/Types.hs
- plutus-core/plutus-core.cabal
- plutus-core/untyped-plutus-core/src/UntypedPlutusCore/Evaluation/Machine/Cek/Debug/Internal.hs
This is the integration. Now one can launch the debugger with a UPLC program (in a `flat` file) and a source program, and press 's' to step through the program. Currently UPLC has highlighting, source doesn't.
e.g.
```
cabal run plutus-core:debugger -- ~/demo/DebuggerDemo.flat ~/demo/DebuggerDemo.hs
```
> PLT-828: integrate debug CEK machine with brick

- plutus-core/executables/debugger/Event.hs
- plutus-core/executables/debugger/Main.hs
- plutus-core/executables/debugger/Types.hs
Previously `mkUplcSpan` wasn't doing the right thing in the `Returning` case. It used the returned value to determine the length of the highlight. If, for example, the return value is a `lam`, and the original term that evaluated to that value is a `force`, it'd only highlight the first 3 letters of `force` (because `length "lam" == 3`).
This PR fixes it by using `SrcSpan` instead of `SourcePos` in `DAnn`. This is what we need to do anyway, once we make the UPLC parser return `SrcSpan`-annotated terms instead of `SourcePos`-annotated ones.
> Use `SrcSpan` instead of `SourcePos` for UPLC in debugger

- .github/workflows/haddock.yml
- nix/cells/plutus/packages/combined-plutus-haddock.nix
- Branch
- PR
This PR adds a Github Action to build a static site out of haddock docs. It requires a Github Environment (under Settings) named `github-pages` with `gh-pages` as the allowed branch. This currently does not use any versioning strategy and has no deploy previews. It is worth noting the artifacts created from `nix-build` are ~1GB and the retention periods are 1 day which may need more tuning.
A demo of this in practice will look like: https://sfoo-iohk.github.io/plutus/
> Deploy haddock to github pages

- plutus-ledger-api/changelog.d/20230215_170512_effectfully_expose_mkTermToEvaluate.md
- plutus-ledger-api/src/PlutusLedgerApi/Common.hs
- plutus-ledger-api/src/PlutusLedgerApi/Common/Eval.hs
People find this helper useful, hence we should expose it.
Fixes #5133.
> [Ledger API] Expose 'mkTermToEvaluate'

- plutus-core/changelog.d/20230215_190332_effectfully_inlinable_geq.md
- plutus-core/plutus-core/src/PlutusCore/Default/Universe.hs
@michaelpj made me learn about loop-breakers, hence this PR achieving more or less the same as #4462 and #4463 except without as much burden.
My quick-and-dirty benchmarking suggests that this does give us a speedup, plus the Core definitely looks better.
Manual benchmarking is a pain in the ass, so let's wait for automated benchmarking to arise from the ashes, hopefully that'll happen soonish. Unless of course somebody wants to volunteer.
> PLT-1432: [Builtins] Make 'geq' inlinable

- plutus-core/changelog.d/20230215_151615_bezirg_tx_highlight.md
- plutus-core/executables/debugger/Draw.hs
- plutus-core/executables/debugger/Event.hs
- plutus-core/executables/debugger/Main.hs
- plutus-core/executables/debugger/Types.hs
- plutus-core/executables/src/PlutusCore/Executable/Common.hs
- plutus-core/plutus-core.cabal
- plutus-core/plutus-core/src/PlutusCore.hs
- plutus-core/untyped-plutus-core/src/UntypedPlutusCore/Core/Zip.hs
This allows highlighting of the source Tx file using the SourceSpans annotations.
Also it allows a bit more input choices for the debugger executable. I tried to reuse parts of the execlib where possible;
and for that i did a small change to execlib that should not break the other executables.
- Branch
- PR
> PLT-1375: Highlight source code while tracing through Plutus Core

- .github/workflows/haddock.yml
Currently the haddock is published at https://input-output-hk.github.io/plutus/
Once this PR is merged, the haddock for master will be at https://input-output-hk.github.io/plutus/master, and the haddock for the releases will be at `https://input-output-hk.github.io/plutus/<version>`, e.g., https://input-output-hk.github.io/plutus/1.2.0.0.
This is done by triggering the GH action on tags of the form `a.b.c.d`, and specifying the `target-folder`.
I've tested this on a fork.
> Publish Haddock for each release

- doc/read-the-docs-site/plutus-doc.cabal
- plutus-benchmark/plutus-benchmark.cabal
- plutus-conformance/plutus-conformance.cabal
- plutus-core/CHANGELOG.md
- plutus-core/changelog.d/20221130_100833_michael.peyton-jones_nothunks_data.md
- plutus-core/changelog.d/20230105_135411_unsafeFixIO_floatin.md
- plutus-core/changelog.d/20230206_074313_thealmartyblog_fix_goldenPIR_parser_err_show.md
- plutus-core/changelog.d/20230207_100654_thealmartyblog_fix_term_parser.md
- plutus-core/changelog.d/20230213_073414_thealmartyblog_plt_1445_add_inliner_tests.md
- plutus-core/changelog.d/20230213_133329_unsafeFixIO_parser.md
- plutus-core/changelog.d/20230213_205047_unsafeFixIO_datatype.md
- plutus-core/changelog.d/20230214_171339_unsafeFixIO_relax.md
- plutus-core/changelog.d/20230215_110959_michael.peyton-jones_split_out_pir.md
- plutus-core/changelog.d/20230215_132227_michael.peyton-jones_no_ann_version.md
- plutus-core/changelog.d/20230215_151615_bezirg_tx_highlight.md
- plutus-core/changelog.d/20230215_190332_effectfully_inlinable_geq.md
- plutus-core/changelog.d/20230216_194718_bezirg_tx_optional.md
- plutus-core/changelog.d/20230220_195818_bezirg_dbgr_errors.md
- plutus-core/changelog.d/20230222_090552_thealmartyblog_plt_1446_add_lam_tracking.md
- plutus-core/plutus-core.cabal
- plutus-ledger-api/CHANGELOG.md
- plutus-ledger-api/changelog.d/20230215_170512_effectfully_expose_mkTermToEvaluate.md
- plutus-ledger-api/plutus-ledger-api.cabal
- plutus-metatheory/plutus-metatheory.cabal
- plutus-tx-plugin/plutus-tx-plugin.cabal
- plutus-tx/plutus-tx.cabal
- scripts/update-version.sh
I considered tagging 1.2.0.0 from the commit where we started enforcing changelogs.
However, it would be inconvenient because I'd have to add a few commits on top of that, and backport them to master.
Also, by then we had already had a few changelog entries anyway.
So I'm tagging 1.2.0.0 from master. The changelog won't be exhaustive for this release, but will be for future releases.
> Version 1.2.0.0

- plutus-core/plutus-ir/src/PlutusIR/Core/Instance/Pretty/Readable.hs
- plutus-tx-plugin/test/Budget/Spec.hs
- plutus-tx-plugin/test/Budget/allCheap.plc.golden
- plutus-tx-plugin/test/Budget/allEmptyList.plc.golden
- plutus-tx-plugin/test/Budget/allExpensive.plc.golden
- plutus-tx-plugin/test/Budget/anyCheap.plc.golden
- plutus-tx-plugin/test/Budget/anyEmptyList.plc.golden
- plutus-tx-plugin/test/Budget/anyExpensive.plc.golden
- plutus-tx-plugin/test/Budget/applicative.plc.golden
- plutus-tx-plugin/test/Budget/elem.plc.golden
- plutus-tx-plugin/test/Budget/filter.plc.golden
- plutus-tx-plugin/test/Budget/findCheap.plc.golden
- plutus-tx-plugin/test/Budget/findEmptyList.plc.golden
- plutus-tx-plugin/test/Budget/findExpensive.plc.golden
- plutus-tx-plugin/test/Budget/ifThenElse1.plc.golden
- plutus-tx-plugin/test/Budget/ifThenElse2.plc.golden
- plutus-tx-plugin/test/Budget/monadicDo.plc.golden
- plutus-tx-plugin/test/Budget/patternMatch.plc.golden
- plutus-tx-plugin/test/Budget/show.plc.golden
- plutus-tx-plugin/test/Budget/sum.plc.golden
- plutus-tx-plugin/test/Budget/toFromData.plc.golden
- plutus-tx/plutus-tx.cabal
- plutus-tx/testlib/PlutusTx/Test.hs
The golden PIR files for `Budget.Spec` often need to be inspected to understand why a change to the compiler leads to different costs. Using the readable version makes this much easier.
Adding the uniques would be helpful for disambiguation (although it can also be distracting), but it makes it harder to diff two PIRs since the uniques can be totally different. So it doesn't print the uniques.
> Use unique-less readable PIR for Budget.Spec

- plutus-core/changelog.d/20230228_215517_bezirg_dbg_budget.md
- plutus-core/executables/debugger/Draw.hs
- plutus-core/executables/debugger/Event.hs
- plutus-core/executables/debugger/Main.hs
- plutus-core/executables/debugger/Types.hs
- plutus-core/plutus-core/src/PlutusCore/Evaluation/Machine/ExBudget.hs
- plutus-core/plutus-core/src/PlutusCore/Evaluation/Machine/ExMemory.hs
This adds a "footer" text of `Spent:({cpu: i | mem: j })Remaining:({cpu: N | mem: M})`                                                                                                                                                                                                                                                                                                            
and an optional cli argument `--budget=cpu,mem` to limit resources. If limit not passed, `Remaining:` is not shown.
- Branch
- PR
> PLT-1458: Propagate budget from debug driver to client

- plutus-ledger-api/changelog.d/20230302_163021_michael.peyton-jones_fix_interval.md
- plutus-ledger-api/plutus-ledger-api.cabal
- plutus-ledger-api/src/PlutusLedgerApi/V1/Interval.hs
- plutus-ledger-api/test/Spec/Interval.hs
- plutus-tx/plutus-tx.cabal
- plutus-tx/src/PlutusTx/Enum.hs
- plutus-tx/testlib/Hedgehog/Laws/Common.hs
- plutus-tx/testlib/Hedgehog/Laws/Eq.hs
- plutus-tx/testlib/Hedgehog/Laws/Lattice.hs
- plutus-tx/testlib/Hedgehog/Laws/Ord.hs
`Interval` was not in a good place. It violated a bunch of laws. The first thing this PR does is add a bunch more tests:
- Generic tests for the typeclasses that `Interval` has instances of.
- Some specific tests that test that finite intervals behave the same as sets of consecutive numbers.
The latter gives us a "semantic" test that lets us check whether our operations on intervals are doing the right thing with respect to a model - in this case the model is the set of values that fall into the inteval.
Then we need to actually fix `Interval`. The most straightforward solution I could see is just to restrict most of its operations to intervals on enumerable types. That lets us turn non-inclusive bounds into inclusive bounds, which simplifies things a lot. Without that information, we …
> PLT-1611: Fix Interval for discrete intervals

- plutus-benchmark/ed25519-throughput/Main.hs
- plutus-benchmark/nofib/exe/Main.hs
- plutus-tx/changelog.d/20230307_151002_unsafeFixIO_haskell_monad.md
- plutus-tx/src/PlutusTx/Foldable.hs
I'm fine with removing these to make things look less weird (especially `sequence_` and `mapM_`, which shouldn't be used anyway).
However, I still don't think we need our own `Monad` class. Rather, I'm in favor of removing our `Applicative` and `Functor` classes (and perhaps more) and use the Haskell ones, because.. why not? We don't have any instance of those classes whose definitions differ from the respective Haskell instances.
Some other classes, like `PlutusTx.AdditiveSemigroup`, exist for a good reason (for now): `Integer`'s `PlutusTx.+` differ from its `GHC.Num.+`, and the latter cannot be used ("for now" because they can be made to work in the future). I don't think this applies to `Monad`, `Applicative` and `Functor`.
> PLT-1539: Remove Plutus Tx functions with Haskell.Monad constraint

- plutus-benchmark/changelog.d/20230310_185153_effectfully_stop_the_irrelevance.rst
- plutus-benchmark/plutus-benchmark.cabal
- plutus-benchmark/validation/BenchCek.hs
- plutus-benchmark/validation/Common.hs
- plutus-ledger-api/src/PlutusLedgerApi/Common.hs
- plutus-ledger-api/src/PlutusLedgerApi/Common/Eval.hs
Hopefully fixes the issue described [here](https://github.com/input-output-hk/plutus/pull/4914#issuecomment-1387710846)
> Benchmark the production code rather than some arbitrary thing

- nix/cells/plutus/packages/combined-plutus-haddock.nix
Opened PLT-4590 for making Haddock work for sublibraries.
> Remove PlutusIR link from Haddock

- plutus-metatheory/plutus-metatheory.cabal
- plutus-metatheory/src/Algorithmic.lagda
- plutus-metatheory/src/Algorithmic/BehaviouralEquivalence/ReductionvsCC.lagda.md
- plutus-metatheory/src/Algorithmic/CC.lagda.md
- plutus-metatheory/src/Algorithmic/CEK.lagda.md
- plutus-metatheory/src/Algorithmic/CK.lagda.md
- plutus-metatheory/src/Algorithmic/Completeness.lagda
- plutus-metatheory/src/Algorithmic/Erasure/RenamingSubstitution.lagda
- plutus-metatheory/src/Algorithmic/Reduction.lagda
- plutus-metatheory/src/Algorithmic/ReductionEC.lagda.md
- plutus-metatheory/src/Algorithmic/ReductionEC/Determinism.lagda.md
- plutus-metatheory/src/Algorithmic/ReductionEC/Progress.lagda.md
- plutus-metatheory/src/Algorithmic/RenamingSubstitution.lagda
- plutus-metatheory/src/Algorithmic/Signature.lagda.md
- plutus-metatheory/src/Algorithmic/Soundness.lagda
- plutus-metatheory/src/Builtin.lagda.md
- plutus-metatheory/src/Builtin/Signature.lagda.md
- plutus-metatheory/src/Check.lagda.md
- plutus-metatheory/src/Type/BetaNBE/Completeness.lagda
- plutus-metatheory/src/Type/RenamingSubstitution.lagda.md
- plutus-metatheory/src/Untyped.lagda.md
- plutus-metatheory/src/Untyped/CEK.lagda.md
- plutus-metatheory/src/Utils.lagda
- plutus-metatheory/src/index.lagda.md
This PR describes the changes to the partial application of builtins, which allows us to avoid pattern matching on the builtins in functions that do not actually need it (that is most functions that did it).
It includes the addition of a predicate classifying types generated by a signature (`SigTy`) and a new design of the type of partially applied builtins (`BApp`).
Because of the changes, there are four proofs that need to be updated (and are not done yet)
1. Determinism of reduction semantics.
2. Behavioural equivalence between reduction and CC.
3. Behavioural equivalence between CC and CK.
4. Behavioural equivalence between CK and CEK.
The relevant files have been commented out in index.lagda.md so that documentation can be generated anyway if it is merged.
> PLT-1345 Simplify bappTerm / bappType

- doc/read-the-docs-site/simple-example.rst
The ImperatorLang framework was recently renamed OpShin. The language "imperator" itself was deprecated and replaced by the imperative language OpShin and the functional language Hebi. This changes adds both to the list and removes the deprecated language.
> Imperator is outdated, replace with Hebi and OpShin

- plutus-metatheory/plutus-metatheory.cabal
- plutus-metatheory/src/Algorithmic/Erasure.lagda
- plutus-metatheory/src/Builtin.lagda.md
- plutus-metatheory/src/Builtin/Constant/AtomicType.lagda.md
- plutus-metatheory/src/Builtin/Constant/Type.lagda.md
- plutus-metatheory/src/Check.lagda.md
- plutus-metatheory/src/Declarative/Erasure.lagda.md
- plutus-metatheory/src/Raw.lagda
- plutus-metatheory/src/RawU.lagda.md
- plutus-metatheory/src/Scoped.lagda
- plutus-metatheory/src/Scoped/Extrication.lagda
- plutus-metatheory/src/Untyped.lagda.md
- plutus-metatheory/src/Untyped/CEK.lagda.md
- plutus-metatheory/src/Utils/Decidable.lagda.md
- plutus-metatheory/src/Utils/Reflection.lagda.md
Rewrote some decidability predicate to avoid pattern-matching on too many constructors.
In order to do this I defined some helpers that work via reflection, and some helpers specific to `Dec` predicates (inspired by @effectfully 's Generic library).
In order to avoid defining separate decidability predicates for `TyTag`s and for `TyCon`s one was defined in terms of the other.
There is more work to do to automate definitions of decidability predicates, but the changes in this PR solve the more annoying definitions.
> PLT-5279 Rewrite Decidable predicates to avoid PM on many constructors.

- plutus-tx-plugin/test/Lift/Spec.hs
- plutus-tx-plugin/test/Plugin/Primitives/Spec.hs
- plutus-tx-plugin/test/StdLib/Spec.hs
- plutus-tx/changelog.d/20230504_121943_unsafeFixIO_lift_pir.md
- plutus-tx/src/PlutusTx/Lift.hs
This enables us to see the PIR of many test cases, which is useful for debugging.
> Make PIR available in the result of liftCode

- plutus-core/plutus-core/src/PlutusCore/Evaluation/Machine/CostModelInterface.hs
- Branch
- PR
This is a prerequisite for https://github.com/input-output-hk/cardano-node/pull/5197 , where infectious `Eq` got in the way.
> Add Eq for CostModelApplyError

- plutus-core/plutus-ir/src/PlutusIR/Compiler/Datatype.hs
- plutus-core/plutus-ir/test/datatypes/listMatch.golden
- plutus-core/plutus-ir/test/datatypes/maybe.golden
- plutus-core/plutus-ir/test/recursion/even3.golden
- plutus-core/plutus-ir/test/recursion/stupidZero.golden
- plutus-tx-plugin/test/Plugin/Data/recursive/interListConstruct.tplc.golden
This should probably alleviate at least some of the confusion. @michaelpj what you were doing there with creating a lambda and immediately applying it is in fact a pretty common thing in the Plutus IR compiler. So common we've named a paper after it! It's just unveiling. You can even see how the same thing is done for Scott-encoding as well, albeit for a slightly different reason (with Scott-encoding we need unveiling for the types of arguments, with SOPs we need it for the type of the result).
Here's a comparison of compilation output for the `InterList` example:
```
SOP    Unveil SOP    Scott
lines of S-exps       749    764           817
occurrences of ifix   6      6             5
```
With unveiling we get slightly larger output, but we're also being consistent and making the dreaded …
> [PlutusIR] [Compile] Replace a lambda with 'unveilDatatype'

- .github/workflows/haddock.yml
We've been publishing Haddock for each release, but each one has a whopping 1.4GB in size and it has exceeded the 10GB limit. Removing the Haddock for releases, and only keeping the master Haddock, until we find a better solution.
> Stop publishing haddock for releases

- plutus-core/executables/pir/Main.hs
- plutus-core/executables/src/PlutusCore/Executable/Common.hs
- plutus-core/executables/src/PlutusCore/Executable/Parsers.hs
- plutus-core/executables/src/PlutusCore/Executable/Types.hs
The plc excutables usually print the output of a program after execution has finished, but that can take a long time or be distracting if you just want to see the execution costs, for example.  This (very small)  PR adds a `-s`/`--silent` option that stops the executables from outputting the result.  That may not make a lot of sense in some cases (eg for `convert`) but to deal with that properly would require adding new option types and option parsers.  Let's just trust the user not to be silly.
> Add --silent option to plc/pir/uplc commands

- plutus-core/plutus-core/test/Evaluation/Spec.hs
I was trying to test that `BuiltinRuntime`s are always in WHNF at runtime and needed these changes to make progress. The testing endeavor failed miserably, but I thought it was worth keeping some changes anyway, because I think they make the code slightly cleaner and you're-holding-it-righter.
> [Test] [Builtins] Use 'BuiltinsRuntime' in no-exceptions tests

- nix/cells/automation/ciJobs.nix
We're low on Mac builder capacity. It's plausible that if our code
builds on `x86_64-darwin` then it builds on `aarch64-darwin`. So we just
skip building most things on `aarch64-darwin`. We _do_ want to build the
shell and the package roots, though, so anyone who is developing on
`aarch64-darwin` will get a shell and have things cached properly.
- Branch
- PR
> Don't build much on aarch64-darwin

- scripts/s3-sync-unzip.sh
In an attempt to fix an 'out of disk space' error in script-evaluation-test
See: https://github.com/input-output-hk/plutus/actions/runs/5067207532/jobs/9097996057
> Remove zipped event dump right after unzipping in s3-sync-unzip.hs

- plutus-core/plutus-core/src/PlutusCore/Builtin/Meaning.hs
Our current approach to creating thunks for individual `BuiltinRuntime`s and sharing them during evaluation turned out to have a flaw: it randomly duplicates `BuiltinRuntime`s for a few builtins (while doing the right thing for the majority of them).
For example, in the current Core we have this for `AddInteger` :
```
AddInteger -> lvl366_sbwr4;
```
as well as this:
```
AddInteger ->
let! { __DEFAULT ~ <- lvl366_sbwr4 } in jump go5_i86oX ys_i86p3;
```
and both point to the same thunk, `lvl366_sbwr4`.
But for `IndexByteString` the two thunks are different, it's 
```
IndexByteString -> lvl370_sbwBp;
```
vs
```
IndexByteString ->
let! { __DEFAULT ~ <- lvl367_sbx56 } in jump go5_i86oX ys_i86p3;
```
i.e. `lvl370_sbwBp` vs `lvl367_sbx56`. Both bindings have to point to the same implementation, …
> [Builtins] [Evaluation] Retain 'cost' in a different way

- plutus-benchmark/bls-benchmarks/src/PlutusBenchmark/BLS12_381/Common.hs
- plutus-core/plutus-core/src/PlutusCore/Evaluation/Machine/ExMemoryUsage.hs
This is just responding to a couple of small things raised in the PR comments; the main branch got merged while I was fixing these.
> Kwxm/bls12 381/minor fixes

- plutus-core/changelog.d/20230525_104559_marty.stumpf_plt_1187_commuteEquals.md
- plutus-core/plutus-core.cabal
- plutus-core/plutus-ir/src/PlutusIR/Compiler.hs
- plutus-core/plutus-ir/src/PlutusIR/Compiler/Types.hs
- plutus-core/plutus-ir/src/PlutusIR/Transform/CommuteConst.hs
- plutus-core/plutus-ir/src/PlutusIR/Transform/CommuteFnWithConst.hs
- plutus-core/plutus-ir/test/TransformSpec.hs
- plutus-core/plutus-ir/test/recursion/factorial.golden
- plutus-core/plutus-ir/test/transform/commuteDefaultFun/divideInt
- plutus-core/plutus-ir/test/transform/commuteDefaultFun/divideInt.golden
- plutus-core/plutus-ir/test/transform/commuteDefaultFun/equalsInt
- plutus-core/plutus-ir/test/transform/commuteDefaultFun/equalsInt.golden
- plutus-core/plutus-ir/test/transform/commuteDefaultFun/let
- plutus-core/plutus-ir/test/transform/commuteDefaultFun/let.golden
- plutus-core/plutus-ir/test/transform/commuteDefaultFun/multiplyInt
- plutus-core/plutus-ir/test/transform/commuteDefaultFun/multiplyInt.golden
Doing this in PIR in case we want to do CSE in PIR.
- Branch
- PR
> Add `commuteConst` to simplifier pass.

- doc/read-the-docs-site/requirements.txt
For security reasons:
https://github.com/input-output-hk/plutus/security/dependabot/3
> Bump requests to 2.31.0 in doc/requirements.txt

- plutus-benchmark/plutus-benchmark.cabal
`cabal bench ed25519-costs` was printing a warning
```
<no location info>: warning: [-Wunused-packages]
The following packages were specified via -package or -package-id flags,
but were not needed for compilation:
- plutus-tx-plugin-1.7.0.0-inplace
```
There's a danger that this may cause a CI failure (although it appears that there was another problem that may have prevented this from being triggered: see #5375-#5379), so this adds `-Wno-unused-pacakges` to stop that.
I don't think this requires review.
> Add -Wno-unused-packages to plutus-benchmark.cabal in a couple of places (PLT-5947 again).

- plutus-benchmark/plutus-benchmark.cabal
- plutus-benchmark/validation/BenchCek.hs
- plutus-benchmark/validation/BenchFull.hs
This is a continuation of #5200, which updated `BenchCek.hs` to use the correct evaluation context. This one updates `BenchFull.hs`.
> Benchmark the production code fully rather than some arbitrary thing

- plutus-tx/src/PlutusTx/IsData/Class.hs
- plutus-tx/src/PlutusTx/Lift/Class.hs
@james-iohk ran into problems when trying to use the BLS functions in some of his end-to-end tests (#5383) because I'd failed to add some instances in `plutus-tx`.  This should fix that.
> Add Typeable and IsData instances for BLS12-381 types (PLT-6512)

- doc/plutus-core-spec/builtins-future.tex
- doc/plutus-core-spec/header.tex
This fixes some typos in the specification of the BLS12-381 builtins.  I don't think it needs to be reviewed.
> Fix some typos

- plutus-core/plutus-core.cabal
This is the version that actually added the BLST support.
> Bump lower bound on cardano-crypto-class

- cabal.project
- flake.lock
- plutus-core/plutus-core.cabal
- plutus-metatheory/plutus-metatheory.cabal
Somewhat non-obvious, ultimately caused by recent revisions to `turtle`. I had to put some `constraints` in the project file, but nothing that affects our publishing to CHaP, fortunately.
> Bump hackage and fix some issues

- plutus-benchmark/common/PlutusBenchmark/Common.hs
- plutus-benchmark/plutus-benchmark.cabal
- plutus-benchmark/script-contexts/test/Spec.hs
When a test fails, rather than `"evaluation failed"`, it now prints the actual error message and Cek logs.
> Improve error messages in ScriptContext benchmarks

- plutus-ledger-api/changelog.d/20230808_144833_bezirg_cborfailureinterp.md
- plutus-ledger-api/plutus-ledger-api.cabal
- plutus-ledger-api/src/Codec/CBOR/Extras.hs
- plutus-ledger-api/src/PlutusLedgerApi/Common/SerialisedScript.hs
- plutus-ledger-api/test/Spec.hs
- plutus-ledger-api/test/Spec/CBOR/DeserialiseFailureInfo.hs
The ledger team has requested long time ago,  to have more descriptive errors when a script fails to deserialize because of some CBOR problem.
The `cborg` library returns plain messages (strings) as deserialization failure reasons, and this PR maps only those that can occur during a plutus script deserialisation to some datatypes.
- Branch
- PR
> PLT-894: Improve the error reporting of 'CBOR.DeserialiseFailure'

- plutus-core/plutus-core/src/PlutusCore/Check/Scoping.hs
- plutus-core/plutus-core/test/Names/Spec.hs
- plutus-core/plutus-ir/test/NamesSpec.hs
- plutus-core/testlib/PlutusCore/Test.hs
This utilizes scoping tests for all PIR transformations that we have (previously it was only renaming).
> [Test] [Names] Add more scoping tests

- plutus-ledger-api/test/Spec/CostModelParams.hs
This is just to fix an error message that mentions the wrong function name.
> Fix slightly worng error message

- doc/read-the-docs-site/reference/writing-scripts/compiler-options-table.rst
- plutus-tx-plugin/changelog.d/20230818_143912_unsafeFixIO_debug_trace.md
- plutus-tx-plugin/plutus-tx-plugin.cabal
- plutus-tx-plugin/src/PlutusTx/Compiler/Expr.hs
- plutus-tx-plugin/src/PlutusTx/Compiler/Kind.hs
- plutus-tx-plugin/src/PlutusTx/Compiler/Trace.hs
- plutus-tx-plugin/src/PlutusTx/Compiler/Type.hs
- plutus-tx-plugin/src/PlutusTx/Compiler/Types.hs
- plutus-tx-plugin/src/PlutusTx/Compiler/Utils.hs
- plutus-tx-plugin/src/PlutusTx/Options.hs
- plutus-tx-plugin/src/PlutusTx/Plugin.hs
When the compilation fails it can dump a stack of things leading to the failure point. This is not sufficient for two reasons:
1. In most of my debugging sessions I find myself wanting to look at the traces of both the failed compilation and a succeeded compilation, and compare the two to figure out where it went wrong. Looking at the trace of the failed compilation alone is insufficient.
2. The stack can't be printed if the compiler loops infinitely.
This PR adds a compiler flag for dumping the full trace, that is, every step taken by `compileExpr`, `hoistExpr`, `compileType` and so on, as the compilation proceeds. To make it easier to figure out how the compilation got to a certain point, every step is annotated by an ID along with the ID of the parent step.
An example trace dump:
``` …
```
> Dump full compilation trace for the plugin (PLT-269)

- .github/workflows/haddock.yml
The git history for the gh-pages branch makes the repo quite heavy.
This PR sets the `single-commit` flag of the github-pages-deploy action to true:
See here: https://github.com/JamesIves/github-pages-deploy-action#optional-choices
> This option can be toggled to true if you'd prefer to have a single commit on the deployment branch instead of maintaining the full history. Using this option will also cause any existing history to be wiped from the deployment branch.
> Reduce gh-pages size when uploading Haddock

- plutus-tx-plugin/test/StdLib/Spec.hs
- plutus-tx/src/PlutusTx/IsData/Instances.hs
It fails if ratio denominator is 0: https://github.com/input-output-hk/plutus/runs/16359392302
> Fix `testOrd`

- doc/plutus-core-spec/Makefile
- doc/plutus-core-spec/README.md
- doc/plutus-core-spec/plutus-core-specification.tex
The README file in the directory containing the PLC specification had a broken link to the PDF (we don't have a checked-in PDF any more) and this is supposed to fix it.  I also changed the date on the PDF because it's not 2024 yet.
> Update the download link and the date on the specification

- plutus-benchmark/validation/Common.hs
This was broken by https://github.com/input-output-hk/plutus/pull/5371
"The function that receives the environment must use lazy pattern matching": https://hackage.haskell.org/package/criterion-1.6.3.0/docs/Criterion.html#v:env
Otherwise
```
validation: Criterion atttempted to retrieve a non-existent environment!
Perhaps you forgot to use lazy pattern matching in a function which
constructs benchmarks from an environment?
(see the documentation for `env` for details)
```
> Fix longitudinal benchmark

- plutus-tx-plugin/changelog.d/20230901_163607_michael.peyton-jones_plugin_pattern_synonyms.md
- plutus-tx-plugin/plutus-tx-plugin.cabal
- plutus-tx-plugin/src/PlutusTx/Compiler/Expr.hs
- plutus-tx-plugin/src/PlutusTx/Compiler/Kind.hs
- plutus-tx-plugin/src/PlutusTx/Compiler/Type.hs
- plutus-tx-plugin/test/Plugin/Patterns/9.2/psym1.pir-readable.golden
- plutus-tx-plugin/test/Plugin/Patterns/9.2/psymRec.pir-readable.golden
- plutus-tx-plugin/test/Plugin/Patterns/9.6/psym1.pir-readable.golden
- plutus-tx-plugin/test/Plugin/Patterns/9.6/psymRec.pir-readable.golden
- plutus-tx-plugin/test/Plugin/Patterns/Spec.hs
- plutus-tx-plugin/test/Plugin/Spec.hs
This requires very little from us (thanks GHC!). GHC generates matching/building functions for the pattern synonyms, we can just compile those as they are.
The only wrinkle is that the functions it generates are runtime-rep polymorphic in a way we haven't dealt with before, so we need to touch up our support for that a little.
- Branch
- PR
> Support pattern synonyms

- plutus-metatheory/src/Builtin.lagda.md
`Builtin.lagda.md` contains several lines like this:
```
{-# COMPILE GHC SHA2-256 = B.convert . Hash.sha2_256 #-}
```
This is using `Data.ByteArray.convert`, which I think is the identity in this case.  Everything still works without it, so I've removed it.
> Remove use of Data.ByteArray.convert

- doc/read-the-docs-site/extensions-flags-pragmas.rst
- doc/read-the-docs-site/index.rst
The `Strict` extension section can potentially be extended and probably deserves its own page. That is future work.
> Add Documentation on GHC Extensions, Flags and Pragmas

- plutus-core/changelog.d/20230901_114457_kenneth.mackenzie_builtin_semantics_option.md
- plutus-core/executables/plc/Main.hs
- plutus-core/executables/src/PlutusCore/Executable/Parsers.hs
- plutus-core/executables/uplc/Main.hs
- plutus-core/plutus-core/src/PlutusCore/Evaluation/Machine/ExBudgetingDefaults.hs
This adds an option to the `plc` and `uplc` commands so that we can say which variant of the builtin semantics we want to use.
This is a step towards PLT-372, but we may want to make it take the ledger language version and/or the PLC language version configurable too.  That would probably require us to move the executables elsewhere though, maybe into a package of their own.
```
$ cat cons.plc
(program 1.0.0
[(builtin consByteString) (con integer 400) (con bytestring #213123213421)]
)
$ cabal run uplc evaluate -- -i cons.uplc -B1
(con bytestring #90213123213421)
$ cabal run uplc evaluate -- -i cons.uplc -B2
An error has occurred:  User error:
The machine terminated because of an error, either from a built-in function or from an explicit use of 'error'.
Caused by: (consByteString 400 …
```
> Add --builtin-semantics-version option to plc and uplc commands

- scripts/ci-plutus-benchmark.sh
The `benchmark.yml` workflow is used to compare benchmark results between two commits.
The two commits user are:
- The latest commit in the PR that triggers the workflow
- The current `master`.
Instead of using `master` we now want to use the commit before the first commit in the PR.
> Change commit used when running benchmarks

- .github/workflows/benchmark.yml
When specifying a regex as a string, backslashes need to be double-escaped, so the `\s`s were not working. We could double-escape them, but it's simpler to use the JS regex literal syntax.
> Fix JS regex syntax

- .github/workflows/benchmark.yml
This attempts to fix the error in `scripts/ci-plutus-benchmark.sh`, where the line:
```
git checkout "$(git merge-base HEAD origin/master)"
```
Fails with:
```
fatal: empty string is not a valid pathspec. please use . instead if you meant to match all paths
```
Because `git merge-base HEAD origin/master` returns the empty string
> Increase fetch-depth in workflows/benchmark.yml

- cabal.project
Otherwise you can't actually disable the `with-cert` flag, which somewhat defeats the point.
> Switch up cabal flag setup to avoid cabal bug

- plutus-metatheory/src/Algorithmic.lagda
- plutus-metatheory/src/Algorithmic/CC.lagda.md
- plutus-metatheory/src/Algorithmic/Evaluation.lagda
- plutus-metatheory/src/Algorithmic/ReductionEC.lagda.md
- plutus-metatheory/src/Algorithmic/ReductionEC/Progress.lagda.md
- plutus-metatheory/src/Utils/List.lagda.md
This PR removes a duplication of representation in the Progress proofs.
Errors could be represented in two ways: with the error constructor, or as an error step in the empty context.
The duplication is solved by removing the error constructor. 
Not only this simplifies proofs, but also will enable the simplification of the determinism proof by reusing the progress proof.
Also, other simplifications to the progress proof were done.
- Branch
- PR
> PLT-7799 Simplify progress proofs

- plutus-core/cost-model/data/models.R
This involves a small refactoring of the R cost modelling code, prompted by PLT-881.  It's possible that we generate a modelling function that has negative slope (eg, if the time is more or less constant) or negative intercept (eg, if the time is linear in x but the regression line happens to cross the t-axis below the origin).  There's a function called `adjustModel` that checks the coefficients of the generated models and replaces any non-positive values with a small positive value in order to avoid the possibility of negative costs.  That was previously called at the end of the functions that generate the individual models, but in this PR I've changed the code so that it's mapped over the full set of models before they're returned to the outside world (which is a bit tricky to do …
> Just call adjustModel once

- plutus-core/plutus-core/src/PlutusCore/Default/Builtins.hs
This is very minor: I'll auto-merge it.
> Fix a misleading typo in a comment

- scripts/update-version.sh
Running `./scripts/prepare-release.sh 1.15.0`, I got messages like 
```
Updating versions ...
Updating version of plutus-core to 1.15.0
Updating version bounds on plutus-core to '^>=1.15'
sed: couldn't edit ./pkgs/.cabal: not a regular file
Updating version of plutus-ledger-api to 1.15.0
Updating version bounds on plutus-ledger-api to '^>=1.15'
sed: couldn't edit ./pkgs/.cabal: not a regular file
...
```
including alarming but harmless warnings about not being able to edit `./pkgs/.cabal`.  This was because there's a line in `update-version.sh` saying
```
find . -name "*.cabal" -exec sed -i ...
```
The  asterisk in `*.cabal` matches the empty string, so it's finding the  `.cabal`  directory.  Changing it to `?*.cabal` prevents this by ensuring that `find` only finds `.cabal` files whose …
> We don't want 'find' to find .cabal

- plutus-core/plutus-core.cabal
- plutus-ledger-api/plutus-ledger-api.cabal
- plutus-tx-plugin/plutus-tx-plugin.cabal
- plutus-tx/plutus-tx.cabal
- prettyprinter-configurable/prettyprinter-configurable.cabal
I messed up in the earlier attempt by typing `1.15.0` instead of `1.15.0.0` in the very first step and that led to a [bad version number](https://github.com/input-output-hk/cardano-haskell-packages/pull/536) in CHaP. This fixes that by starting from scratch, but in the meantime the previous attempt got merged.  I'm not sure how that'll affect the changelogs, since they got updated in the previous attempt.
> Release 1.15.0.0

- .github/workflows/benchmark.yml
- scripts/ci-plutus-benchmark.sh
It's possible that one has to `git pull --rebase origin master` first in order for the `ci-plutus-benchmark.sh` to work in one's PR.
This PR adds a check that `git merge-base HEAD origin/master` does not return the empty string at the top of the `ci-plutus-benchmark.sh` file.
> Add empty string check for git command in ci-plutus-benchmark.sh

- doc/read-the-docs-site/requirements.txt
This is to address a security issue as per https://github.com/input-output-hk/plutus/security/dependabot/7
Also `PyYAML` has been updated to fix this build error: https://readthedocs.org/projects/plutus/builds/22350594/
> Bump urllib version in read-the-docs-site/requirements.txt

- plutus-core/changelog.d/20231103_205517_effectfully_remove_dependent_sum_template.md
- plutus-core/plutus-core.cabal
- plutus-core/plutus-core/src/PlutusCore.hs
- plutus-core/plutus-core/src/PlutusCore/Default/Universe.hs
- plutus-core/plutus-core/src/Universe/Core.hs
This removes the `dependent-sum-template` package from dependencies, so that it doesn't complicate supporting GHC 9.8. We don't need the package for anything, however it was requested that we add a `GCompare` instance for `DefaultUni` in #4178. We could implement the instance manually, but given that we don't need it my inclination is to say that if somebody needs the instance, they can either implement it themselves or indeed just depend on `dependent-sum-template` as we used to (unless they need it for GHC 9.8 and support for that version is never added to the package).
> [Build] Remove 'dependent-sum-template'

- cabal.project
I'm learning about Plutus and was reading `cabal.project` in the root and found some typos. I did read the CONTRIBUTING guide but don't feel this change merits an issue.
- PR
> Minor typos in cabal.project

- doc/plutus-core-spec/cardano/builtins1.tex
- plutus-core/plutus-core/src/PlutusCore/Parser/Builtin.hs
The PLC parser uses `Data.Text.pack` when parsing Unicode strings, which replaces surrogate character codes with U+FFFE.  This adds a comment and a remark in the specification to explain that.
> Remarks about replacement of Unicode surrogates

- cabal.project
- flake.lock
- plutus-core/executables/debugger/Main.hs
- plutus-core/plutus-core.cabal
- plutus-ledger-api/src/PlutusLedgerApi/Common/Eval.hs
`ouroboros-network-framework` now has a lower bound on this, so we need to be compatible with it. It adds a conflicting instance, so we need to remove that and also update our lower bound too.
> Update to new nothunks

- plutus-ledger-api/changelog.d/20231109_213954_effectfully_expose_fromSatInt_and_add_some_instances.md
- plutus-ledger-api/src/PlutusLedgerApi/V2.hs
- plutus-ledger-api/src/PlutusLedgerApi/V3.hs
#5618 wasn't ready for merging, this one does for V2 and V3 the same as the previous one did for V1 and adds a changelog entry.
> Expose 'unSatInt' and 'fromSatInt' from V2 and V3 as well

- CONTRIBUTING.adoc
- RELEASE.adoc
- doc/plutus-core-spec/Makefile
- doc/read-the-docs-site/README.md
- flake.lock
Instructions on how to install & upgrade nix and how to setup the binary caches are now included in the [relevant section](https://github.com/input-output-hk/iogx/blob/main/doc/api.md#flakenix) of the IOGX manual. 
This PR affects the CONTRIBUTING.adoc and RELEASE.adoc making those documents up-to-date.
> Update nix documentation in CONTRIBUTING and RELEASE

- plutus-tx-plugin/test/AsData/Budget/Spec.hs
- plutus-tx-plugin/test/Budget/Spec.hs
- plutus-tx-plugin/test/IntegerLiterals/NoStrict/NegativeLiterals/Spec.hs
- plutus-tx-plugin/test/IntegerLiterals/NoStrict/NoNegativeLiterals/Spec.hs
- plutus-tx-plugin/test/IntegerLiterals/Strict/NegativeLiterals/Spec.hs
- plutus-tx-plugin/test/IntegerLiterals/Strict/NoNegativeLiterals/Spec.hs
- plutus-tx-plugin/test/Strictness/Spec.hs
- plutus-tx-plugin/test/TH/Spec.hs
A number of files in `plutus-tx-plugin/test` contain
```
{-# OPTIONS_GHC -fplugin PlutusTx.Plugin #-}
```
where it isn't needed.  This confused me a bit, so I've removed them.
I found some other unnecessary pragmas in these files, so I removed them too.  There are probably similar things in other tests in this package, but I didn't go through them all.
> Remove some redundant pragmas

- doc/plutus-core-spec/cardano/builtins1.tex
Just fixing a tiny typo in the PLC specification. I'll auto-merge this.
> Typo: the -> that

- plutus-ledger-api/exe/analyse-script-events/Main.hs
Fixing a small mistake: the `Data` analysis for  datums was analysing redeemers instead for V2 script events.  I'll re-run the analysis, but I think it probably won't make much difference.
> Oops: analysing redeemer instead of datum for V2

- plutus-tx/src/PlutusTx/Builtins/Class.hs
- plutus-tx/src/PlutusTx/Lift/Class.hs
- plutus-tx/src/PlutusTx/Lift/Instances.hs
> Add some comments on FromBuiltin/ToBuiltin/Lift

- plutus-conformance/test-cases/uplc/evaluation/builtin/semantics/chooseList/chooseList3/chooseList3.uplc
- plutus-conformance/test-cases/uplc/evaluation/builtin/semantics/chooseList/chooseList3/chooseList3.uplc.expected
- plutus-conformance/test-cases/uplc/evaluation/builtin/semantics/chooseList/chooseList4/chooseList4.uplc
- plutus-conformance/test-cases/uplc/evaluation/builtin/semantics/chooseList/chooseList4/chooseList4.uplc.expected
- plutus-conformance/test-cases/uplc/evaluation/builtin/semantics/chooseUnit2/chooseUnit2.uplc
- plutus-conformance/test-cases/uplc/evaluation/builtin/semantics/chooseUnit2/chooseUnit2.uplc.expected
`chooseList` is *-polymorphic in its second and third arguments and we weren't checking this.  We should do this for all *-polymorphic arguments and check that builtins with #-polymorphic arguments fail when given non-constant terms (but later).
The present PR adds tests for the problem that got fixed in #5657.
> Extra conformance tests for chooseList

- doc/read-the-docs-site/quick-start.rst
The other tutorials don't have this since they set it globally at the top. We don't want that here since we have some non-Haskell code blocks too.
> Fix haskell syntax highlighting in quickstart

- plutus-metatheory/plutus-metatheory.cabal
- plutus-metatheory/src/Builtin.lagda.md
- plutus-metatheory/src/Cost.lagda.md
- plutus-metatheory/src/Cost/Base.lagda.md
- plutus-metatheory/src/Untyped/CEK.lagda.md
- plutus-metatheory/src/Untyped/CEKWithCost.lagda.md
Cost semantics in the metatheory for the following builtin functions, and their corresponding costing models.
```
addInteger
subtractInteger
multiplyInteger
divideInteger
quotientInteger
remainderInteger
modInteger
equalsInteger
lessThanInteger
lessThanEqualsInteger
ifThenElse
```
> PLT-1566 Add cost semantics for basic builtins

- plutus-ledger-api/changelog.d/20231218_154908_unsafeFixIO_helper.md
- plutus-ledger-api/src/PlutusLedgerApi/V3/Contexts.hs
They mirror the ones for Plutus V2.
> Add some helper functions for Plutus V3 ScriptContext

- plutus-core/plutus-core/src/PlutusCore/Builtin/Convert.hs
- plutus-core/untyped-plutus-core/test/Evaluation/Builtins/Conversion.hs
- plutus-core/untyped-plutus-core/test/Evaluation/Builtins/Definition.hs
- plutus-ledger-api/test-plugin/Spec/Value.hs
- plutus-tx-plugin/src/PlutusTx/Compiler/Builtins.hs
- plutus-tx-plugin/test/AsData/Budget/9.6/patternMatching.uplc.golden
- plutus-tx/src/PlutusTx/Builtins.hs
- plutus-tx/src/PlutusTx/Builtins/Internal.hs
This makes it so that an unhandled built-in function in the plugin causes a compile-time warning. 
In particular, it gives me
```
warning: [GHC-62161] [-Wincomplete-patterns]
Pattern match(es) are non-exhaustive
In a case alternative:
Patterns of type ‘PLC.DefaultFun’ not matched:
PLC.IntegerToByteString
PLC.ByteStringToInteger
```
> [Plugin] Warn about missing builtins

- plutus-tx/changelog.d/20240112_125800_kenneth.mackenzie.md
- plutus-tx/src/PlutusTx/Builtins.hs
The implementation of `blake2b_224` in the plugin was actually calling `blake2b_256`.  This fixes that.  The problem only affects the plugin: the Plutus Core implementation is correct.
> Fix blake2b_224 in plutus-tx

- plutus-benchmark/bench-compare-markdown
- plutus-benchmark/nofib-compare
The `bench-compare` scripts use `paste`, which by default uses tabs as separators in the output.  This can confuse the formatting `awk` does later in the scripts, so this PR makes `paste` use spaces as delimiters instead.
I'm going to take the opportunity to run the benchmarks multiple times (nothing to do with the PR really, just checking consistency).
> Make 'paste' use spaces as delimiters: tabs confuse awk formatting

- plutus-core/changelog.d/20240117_230746_effectfully_expose_BuiltinResult.md
- plutus-core/plutus-core.cabal
- plutus-core/plutus-core/examples/PlutusCore/Examples/Builtins.hs
- plutus-core/plutus-core/src/PlutusCore/Builtin.hs
- plutus-core/plutus-core/src/PlutusCore/Builtin/Convert.hs
- plutus-core/plutus-core/src/PlutusCore/Builtin/Emitter.hs
- plutus-core/plutus-core/src/PlutusCore/Builtin/HasConstant.hs
- plutus-core/plutus-core/src/PlutusCore/Builtin/KnownType.hs
- plutus-core/plutus-core/src/PlutusCore/Builtin/KnownTypeAst.hs
- plutus-core/plutus-core/src/PlutusCore/Builtin/Meaning.hs
- plutus-core/plutus-core/src/PlutusCore/Builtin/Result.hs
- plutus-core/plutus-core/src/PlutusCore/Builtin/Runtime.hs
- plutus-core/plutus-core/src/PlutusCore/Crypto/Ed25519.hs
- plutus-core/plutus-core/src/PlutusCore/Crypto/Secp256k1.hs
- plutus-core/plutus-core/src/PlutusCore/Crypto/Utils.hs
- plutus-core/plutus-core/src/PlutusCore/Default/Builtins.hs
- plutus-core/plutus-core/src/PlutusCore/Default/Universe.hs
- plutus-core/plutus-core/src/PlutusCore/Evaluation/ErrorWithCause.hs
- plutus-core/plutus-core/src/PlutusCore/Evaluation/Machine/Ck.hs
- plutus-core/plutus-core/src/PlutusCore/Evaluation/Machine/Exception.hs
- plutus-core/plutus-core/src/PlutusCore/Evaluation/Result.hs
- plutus-core/plutus-core/src/PlutusCore/TypeCheck/Internal.hs
- plutus-core/plutus-core/test/Evaluation/Spec.hs
- plutus-core/plutus-ir/src/PlutusIR/Transform/EvaluateBuiltins.hs
- plutus-core/untyped-plutus-core/src/UntypedPlutusCore/Evaluation/Machine/Cek/Internal.hs
- plutus-core/untyped-plutus-core/src/UntypedPlutusCore/Evaluation/Machine/SteppableCek/Internal.hs
- plutus-metatheory/src/Builtin.lagda.md
- plutus-tx/plutus-tx.cabal
- plutus-tx/src/PlutusTx/Builtins/Internal.hs
This renames `MakeKnownM` to `BuiltinResult`, exposes it to the user and updates a bunch of crypto primitives to use it instead of `Emitter (EvaluationResult Smth)`. The latter was very error-prone: an `EvaluationFailure` is supposed to terminate evaluation, but not when it's wrapper in `Emitter`, meaning code like
```haskell
do
guard condition
rest
```
wouldn't terminate on `condition` being `False`, which could easily lead to a security issue if we weren't extra careful with the crypto builtins. This PR fixes the problem.
Plus `BuiltinResult` is designed do be fast, unlike `Emitter (EvaluationResult Smth)`, although the difference for our specific use cases is likely negligible.
I also had to move a bunch of stuff around, 'cause I was getting pretty annoying import cycle errors.
> [Builtins] Expose 'BuiltinResult'

- plutus-benchmark/common/PlutusBenchmark/Common.hs
This is just fixing an import that became outdated after merging #5730: see the comments there for more details.  I'll auto-merge it to get `master` working again.
> Fix missing Agda import

- plutus-core/executables/pir/README.md
- plutus-ledger-api/plutus-ledger-api.cabal
- plutus-ledger-api/src/Codec/CBOR/Extras.hs
- plutus-ledger-api/src/PlutusLedgerApi/Common/Eval.hs
- plutus-ledger-api/src/PlutusLedgerApi/Common/SerialisedScript.hs
- plutus-ledger-api/test/Spec.hs
- plutus-ledger-api/test/Spec/CBOR/DeserialiseFailureInfo.hs
- plutus-ledger-api/test/Spec/ScriptDecodeError.hs
- plutus-ledger-api/testlib/PlutusLedgerApi/Test/EvaluationEvent.hs
This PR adds `instance Pretty ScriptDecodeError` to be used instead of the `Show` instance.
(Hint: its probably easier to review it commit-by-commit).
- Branch
> [PLT-9056] Pretty instance for ScriptDecodeError

- plutus-conformance/agda/Spec.hs
This PR adds an agda evaluator which return costing. 
It currently doesn't use the provided `CostModelParams`, but rather default ones. Since default parameters are the ones used for creating the `upc.budget.expected` files this is not a problem right now, and all test pass. 
A final implementation should really get the parameters from the provided `CostModelParams`, by correctly implementing the function
```haskell
processModelParams  :: CostModelParams -> (CekMachineCosts ,  BuiltinCostMap)
```
to actually use its argument. 
- Branch
- PR
> Adding a Costing Evaluator to agda-conformance

- plutus-conformance/agda/Spec.hs
- plutus-conformance/haskell/Spec.hs
- plutus-conformance/plutus-conformance.cabal
- plutus-conformance/src/PlutusConformance/Common.hs
- plutus-core/plutus-core/src/PlutusCore/Default/Builtins.hs
- plutus-core/plutus-core/src/PlutusCore/Evaluation/Machine/SimpleBuiltinCostModel.hs
#5758 ("Add a costing evaluator to agda-conformance") contained a comment saying
```
TODO: In processModelParams construct the pair in the result from the argument.
Here, we ignore the argument and just return a default set.
```
This PR fixes that. The problem is that the Agda evualator uses a simplified cost model representation and we have to convert a set of `CostModelParams` in to that format.  We have [multiple cost model representations](https://github.com/IntersectMBO/plutus/tree/master/doc/notes/cost-model-representations) and it was a little difficult to find the best way of doing the conversion.  There's a comment explaining what I eventually did, and why.
> Kwxm/agda conformance/better cost model (PLT-9449)

- plutus-tx/plutus-tx.cabal
This tiny PR fixes the following warning
```
Warning: 'ghc-options: -rtsopts' has no effect for libraries. It should only be used for executables.
```
by removing the `ghc-option` from the plutus-tx-testlib
> Remove unnecessary for a library ghc options

- plutus-core/untyped-plutus-core/src/UntypedPlutusCore/Transform/Inline.hs
Fixes  the following error (GHC 8.10.7)
```
untyped-plutus-core/src/UntypedPlutusCore/Transform/Inline.hs:175:3: error:
parse error on input '-- ^ inline constants'
|
175 |   -- ^ inline constants
|   ^^^^^^^^^^^^^^^^^^^^^
Warning: Failed to build documentation for plutus-core-1.22.0.0.
```
> fix: haddock parse error in GHC 8.10

- plutus-core/testlib/PlutusIR/Generators/QuickCheck/ShrinkTerms.hs
Before this PR running
```
cabal test plutus-ir-test --test-options "--pattern shrinkTermSound --quickcheck-replay=21373"
```
produces
```
plutus-ir/test/Driver.hs
PlutusIR
Generators.QuickCheck.Tests
shrinkTermSound: FAIL (0.23s)
*** Failed! Falsified (after 6 tests and 7 shrinks):
ty,tm = ( all a5_17. a5_17 -> (all a4_19. a5_17)
, let
data (d8_8 :: * -> *) a10_10 | m6_6 where
in
/\a5_8 -> \(x13_13 : a5_8) -> /\a4_11 -> x13_13 )
[ ( ( a5_8 -> (all a4_19. unit)
, let
data (d8_8 :: * -> *) a10_10 | m6_6 where
in
\(x13_13 : a5_8) -> error {all a4_19. unit} )
, Error during PIR typechecking:
Type-level name mismatch at (): d8 is in scope, but a5 having the same Unique 20 is attempted to be referenced ) ]
Use --quickcheck-replay=21373 to reproduce.
```
After:
```
plutus-ir/test/Driver.hs …
```
> [Generators] Fix 'LamAbs' handling in 'fixupTerm_'

- plutus-ledger-api/src/PlutusLedgerApi/V3.hs
- plutus-ledger-api/src/PlutusLedgerApi/V3/Contexts.hs
Switching from `V2.TxId` to `V3.TxId` also requires switching from `V2.TxInInfo` to `V3.TxInInfo` as it contains `TxId`
> PlutusLedgerApi.V3.TxInInfo

- plutus-core/plutus-core/src/PlutusCore/Evaluation/Machine/ExMemoryUsage.hs
This just clarifies the comment about the `ExMemoryUsage` of `ByteString`, where a number of contradictory comments had accumulated.  See issue #5775.
> Sort out the comments on the ExMemoryUsage instance for ByteString

- plutus-core/plutus-core/src/PlutusCore/Evaluation/Machine/CostModelInterface.hs
The interface between the ledger and the Plutus Core cost model is quite complicated (see [this Note)](https://github.com/IntersectMBO/plutus/blob/ce4bcc4c709681c1ec085ad1f132b5fb9f5a4c5a/plutus-core/plutus-core/src/PlutusCore/Evaluation/Machine/CostModelInterface.hs#L86).  This adds a link to the issue where the current form of the interface was decided.
> Add pointer to issue on the ledger's cost model interface

- plutus-tx-plugin/test/Blueprint/Tests.hs
- plutus-tx-plugin/test/Blueprint/Tests/Lib.hs
- plutus-tx/src/PlutusTx/Blueprint/Contract.hs
- plutus-tx/src/PlutusTx/Blueprint/Definition.hs
- plutus-tx/src/PlutusTx/Blueprint/Validator.hs
- plutus-tx/src/PlutusTx/Blueprint/Write.hs
- plutus-tx/test/Blueprint/Definition/Fixture.hs
- plutus-tx/test/Blueprint/Definition/Spec.hs
- plutus-tx/test/Blueprint/Spec.hs
This PR implements @michaelpj 's [suggestion](https://github.com/IntersectMBO/plutus/pull/5824#discussion_r1524647268) to derive schema definitions "bottom-up" in contrast with the "top-down" derivation approach from [this PR](https://github.com/IntersectMBO/plutus/pull/5824#):
1. User lists top-level contract types, e.g.:
`[Params, Redeemer, Datum]`.
2. User uses this list to derive schema definitions:
`deriveDefinitions @[Params, Redeemer, Datum]`:
- before deriving, top-level types are un-rolled to include all nested types, e.g.:    
`@[Params, Bool, Integer, Redeemer, Datum, (), ...]`.
4. Schema references checked against the un-rolled list, e.g.:  
- `definitionRef @Datum`
- `definitionRef @Bool`
5. The `referencedTypes` type variable in the `ContractBlueprint referencedTypes` which …
> CIP-0057: Alternative approach to deriving and referencing schema definitons.

- plutus-tx-plugin/test/Blueprint/Acme.golden.json
- plutus-tx-plugin/test/Blueprint/Tests.hs
- plutus-tx-plugin/test/Blueprint/Tests/Lib.hs
- plutus-tx/plutus-tx.cabal
- plutus-tx/src/PlutusTx/Blueprint/Argument.hs
- plutus-tx/src/PlutusTx/Blueprint/Contract.hs
- plutus-tx/src/PlutusTx/Blueprint/Definition.hs
- plutus-tx/src/PlutusTx/Blueprint/Definition/Id.hs
- plutus-tx/src/PlutusTx/Blueprint/Parameter.hs
- plutus-tx/src/PlutusTx/Blueprint/Purpose.hs
- plutus-tx/src/PlutusTx/Blueprint/Schema.hs
- plutus-tx/src/PlutusTx/Blueprint/Schema/Annotation.hs
- plutus-tx/src/PlutusTx/Blueprint/TH.hs
- plutus-tx/src/PlutusTx/Blueprint/Validator.hs
- plutus-tx/src/PlutusTx/Blueprint/Write.hs
- plutus-tx/src/PlutusTx/Builtins/Internal.hs
- plutus-tx/test/Blueprint/Definition/Fixture.hs
- plutus-tx/test/Blueprint/Definition/Spec.hs
- plutus-tx/test/Blueprint/Spec.hs
The idea is that user specifies at most 3 types: Param, Datum, Redeemer and all the types nested withing them are extracted automatically (un-rolled).
> CIP-0057: ContractBlueprint with derived schema definitions and safe schema refs

- plutus-benchmark/marlowe/src/PlutusBenchmark/Marlowe/Core/V1/Semantics.hs
- plutus-ledger-api/src/PlutusLedgerApi/V1/Value.hs
- plutus-ledger-api/src/PlutusLedgerApi/V2.hs
- plutus-ledger-api/src/PlutusLedgerApi/V3.hs
- plutus-ledger-api/test-plugin/Spec/Budget.hs
- plutus-ledger-api/test-plugin/Spec/Value.hs
- plutus-ledger-api/testlib/PlutusLedgerApi/Test/V1/Value.hs
- plutus-tx/changelog.d/20240315_151519_ana.pantilie95_plt_9511_audit_assocmap.md
- plutus-tx/src/PlutusTx/AssocMap.hs
> Document unsafe operations of `AssocMap`

- plutus-core/plutus-ir/src/PlutusIR/Contexts.hs
- plutus-core/plutus-ir/src/PlutusIR/Purity.hs
- plutus-core/untyped-plutus-core/src/UntypedPlutusCore/Purity.hs
Housekeeping chore: format a few modules (`Purity`) before changing them.
> Chore: formatting, explicit imports.

- plutus-benchmark/bench-compare-markdown
Print out total times in benchmark comparisons.  This should make it a bit easier to see if there's a real change or just noise.
> Get the benchmark comparison script to print out total times

- flake.lock
- nix/shell.nix
Recent versions of iogx use HSL v2.7 for ghc94 and ghc98. 
This PR addresses this issue in iogx https://github.com/input-output-hk/iogx/issues/25 and makes the conditionals in `shell.nix` obsolete 
```
> nix develop .#ghc96
> ghc --version
The Glorious Glasgow Haskell Compilation System, version 9.6.4
> haskell-language-server --version
haskell-language-server version: 2.7.0.0 (GHC: 9.6.4)
```
And 
```
> nix develop .#ghc98
> ghc --version
The Glorious Glasgow Haskell Compilation System, version 9.8.1
> haskell-language-server --version
haskell-language-server version: 2.7.0.0 (GHC: 9.8.1)
> Remove obsolete edge case for GHC98/HSL from shell.nix

- flake.lock
`nix flake update iogx --override-input iogx github:input-output-hk/iogx/b8d2456daf9d85a55a62cc59744105d5bfcbf82e`
(I tried `nix flake update iogx` first,  but it updates to the latest commit which breaks the nix shell in a way I don't know how to fix).
> nix flake update iogx

- plutus-core/changelog.d/20240405_015609_kenneth.mackenzie_canonincal_data_encoding.md
- plutus-core/plutus-core/src/PlutusCore/Flat.hs
- plutus-core/untyped-plutus-core/test/Flat/Spec.hs
As described in https://github.com/IntersectMBO/plutus/issues/5852, the `flat` encoding of `Data` objects did not always have the canonical format described in the Plutus Core specification, which is arguably a bug. This should fix the problem.  See the code comments for details.  The actual fix only requires one extra word, but I've added some tests too.
> Kwxm/flat/canonincal data encoding (PLT-9705)

- RELEASE.adoc
I had some difficulty making the 1.25.0.0 release because other people's CHaP PRs kept getting merged before mine.  I've added a warning about that and some links to the CHaP documentation in case it happens to anyone else. Thanks to @michaelpj for the pointers.
> Add some text about how to deal with bad CHaP timestamps in RELEASE.adoc

- plutus-tx-plugin/src/PlutusTx/Compiler/Expr.hs
- plutus-tx-plugin/src/PlutusTx/Plugin.hs
- plutus-tx-plugin/test/Plugin/Coverage/9.6/coverageCode.pir.golden
- plutus-tx/src/PlutusTx/Bool.hs
Follow-up to [this thread](https://github.com/IntersectMBO/plutus/pull/5863#pullrequestreview-1975184625).
> Refer to && and || by their qualified TH names.

- plutus-benchmark/agda-common/PlutusBenchmark/Agda/Common.hs
- plutus-benchmark/bls12-381-costs/src/PlutusBenchmark/BLS12_381/Scripts.hs
- plutus-benchmark/cek-calibration/Main.hs
- plutus-benchmark/common/PlutusBenchmark/Common.hs
- plutus-benchmark/ed25519-costs/src/PlutusBenchmark/Ed25519/Common.hs
- plutus-benchmark/lists/src/PlutusBenchmark/Lists/Lookup/Compiled.hs
- plutus-benchmark/lists/src/PlutusBenchmark/Lists/Sort/GhcSort.hs
- plutus-benchmark/lists/src/PlutusBenchmark/Lists/Sort/InsertionSort.hs
- plutus-benchmark/lists/src/PlutusBenchmark/Lists/Sort/MergeSort.hs
- plutus-benchmark/lists/src/PlutusBenchmark/Lists/Sort/QuickSort.hs
- plutus-benchmark/lists/src/PlutusBenchmark/Lists/Sum/Compiled.hs
- plutus-benchmark/marlowe/bench/BenchAgdaCek.hs
- plutus-benchmark/nofib/bench/BenchAgdaCek.hs
- plutus-benchmark/nofib/src/PlutusBenchmark/NoFib/Clausify.hs
- plutus-benchmark/nofib/src/PlutusBenchmark/NoFib/Knights.hs
- plutus-benchmark/nofib/src/PlutusBenchmark/NoFib/LastPiece.hs
- plutus-benchmark/nofib/src/PlutusBenchmark/NoFib/Prime.hs
- plutus-benchmark/nofib/src/PlutusBenchmark/NoFib/Queens.hs
- plutus-benchmark/plutus-benchmark.cabal
- plutus-benchmark/script-contexts/src/PlutusBenchmark/ScriptContexts.hs
- plutus-benchmark/validation/bench/BenchAgdaCek.hs
`plutus-benchmarks` contains a library called `plutus-benchmark-common` that contains some shared code.  Some of the benchmarks are for the Agda evaluator in `plutus-metatheory`, so `plutus-benchmark-common` depended on that.  This sometimes caused `plutus-metatheory` to be built for things like the validation benchmarks, which don't care about the benchmarks: this takes a long time and is very annoying.  This PR removes the `plutus-metatheory` dependency and puts the relevant code into a library of its own, so the lengthy Agda build only happens when you really need it.
> Remove plutus-metatheory from plutus-benchmark-common

- plutus-core/plutus-core.cabal
- plutus-core/untyped-plutus-core/test/Flat/Spec.hs
(PLT-9705 continued)
The Plutus Core specification recommends that bytestrings should be serialised in a certain canonical way, and #5879  made sure that our flat serialisation for Data  obeyed this recommendation.  However, when we're deserialising from flat we also accept _non-canonical_ encodings of bytestrings and Data, and this PR adds some tests to make sure that we really do accept those.
> Add some tests that non-canonically encoded bytestrings decode correctly

- doc/read-the-docs-site/troubleshooting.rst
- plutus-tx/changelog.d/20240405_144845_Yuriy.Lazaryev_error_codes.md
- plutus-tx/src/PlutusTx/ErrorCodes.hs
- plutus-tx/src/PlutusTx/Ratio.hs
> PT20: reciprocalOfZeroError

- plutus-tx/src/PlutusTx/Builtins/Internal.hs
- plutus-tx/src/PlutusTx/Utils.hs
It makes no sense to say "placeholder must have been replaced by the core-to-plc plugin during compilation", when calling `PlutusTx.Builtins.Internal.error`. There's no placeholder - it's just an innocent use of `error`, and nothing needs to be replaced.
I was quite confused by this message when testing the constitution script.
> Don't call `mustBeReplaced` in PlutusTx.Builtins.Internal

- plutus-tx-plugin/plutus-tx-plugin.cabal
- plutus-tx-plugin/test/Plugin/NoTrace/Lib.hs
- plutus-tx-plugin/test/Plugin/NoTrace/Spec.hs
- plutus-tx-plugin/test/Plugin/NoTrace/WithTraces.hs
- plutus-tx-plugin/test/Plugin/NoTrace/WithoutTraces.hs
> Add some more complex test cases for the remove-trace plugin option

- doc/read-the-docs-site/plutus-doc.cabal
- plutus-benchmark/plutus-benchmark.cabal
- plutus-conformance/plutus-conformance.cabal
- plutus-core/CHANGELOG.md
- plutus-core/changelog.d/20240326_184114_kenneth.mackenzie_read_model_type_from_R_2.md
- plutus-core/changelog.d/20240402_173125_michael.peyton-jones_vector_cases.md
- plutus-core/changelog.d/20240405_015609_kenneth.mackenzie_canonincal_data_encoding.md
- plutus-core/plutus-core.cabal
- plutus-ledger-api/plutus-ledger-api.cabal
- plutus-metatheory/plutus-metatheory.cabal
- plutus-tx-plugin/CHANGELOG.md
- plutus-tx-plugin/changelog.d/20240325_114310_unsafeFixIO_options.md
- plutus-tx-plugin/changelog.d/20240412_150720_Yuriy.Lazaryev_fix_remove_dead_bindings_flag.md
- plutus-tx-plugin/plutus-tx-plugin.cabal
- plutus-tx/CHANGELOG.md
- plutus-tx/changelog.d/20240325_114314_Yuriy.Lazaryev_cip57_howto.md
- plutus-tx/changelog.d/20240405_144845_Yuriy.Lazaryev_error_codes.md
- plutus-tx/changelog.d/20240412_060219_unsafeFixIO_indexBuiltinList.md
- plutus-tx/plutus-tx.cabal
- prettyprinter-configurable/prettyprinter-configurable.cabal
> [Release] 1.26.0.0

- doc/plutus-core-spec/builtins.tex
- doc/plutus-core-spec/cardano/builtins4.tex
- doc/plutus-core-spec/plutus-core-specification.tex
[PLT-8189]  This adds the two new integer/bytestring conversions to the specification. See p35-36 of the attached PDF for a readable version.
[plutus-core-specification.pdf](https://github.com/IntersectMBO/plutus/files/15024318/plutus-core-specification.pdf)
> Kwxm/plc spec/bitwise conversions

- plutus-core/plutus-core.cabal
- plutus-core/plutus-ir/src/PlutusIR/Contexts.hs
- plutus-core/plutus-ir/test/PlutusIR/Contexts/Tests.hs
- plutus-core/plutus-ir/test/PlutusIR/Transform/CaseOfCase/Tests.hs
- plutus-core/plutus-ir/test/PlutusIR/Transform/CaseOfCase/twoTyArgs
- plutus-core/plutus-ir/test/PlutusIR/Transform/CaseOfCase/twoTyArgs.golden
Closes #5922 by fixing order of type arguments as they are extracted.
> CaseOfCase kind mismatch error fix

- plutus-tx-plugin/test/Plugin/NoTrace/Spec.hs
- plutus-tx/src/PlutusTx/Blueprint/Contract.hs
- plutus-tx/src/PlutusTx/Blueprint/Definition/Unroll.hs
- scripts/check-Notes.awk
I ran the `scripts/check-Notes.sh` script and found a few references that said "note" instead of "Note" (see the rules [here](https://github.com/IntersectMBO/plutus/blob/0567ef7fc1efb4ec415fe882df9b313d8c3dd0df/scripts/check-Notes.awk#L3), which are supposed to make it easier to find Notes and references to them).  This fixes that.
(Also, see `find-Notes.sh` for a script to list/search the Notes.)
> Fix some Notes so they pass the check

- plutus-core/plutus-core/src/PlutusCore/Evaluation/Machine/CostingFun/SimpleJSON.hs
Just tidying up some code after #5932.
> Tidy up SimpleJSON.hs

- plutus-core/plutus-core.cabal
- plutus-core/plutus-core/src/PlutusCore/Evaluation/Machine/CostingFun/Core.hs
It doesn't build with 9.2: https://github.com/IntersectMBO/cardano-haskell-packages/actions/runs/8902018953/job/24447188265
> Do not build the plutus executable if GHC <9.6

- plutus-core/plutus-core/src/PlutusCore/Evaluation/Machine/CostModelInterface.hs
> Add 'Note [Table of all possible ledger's states w.r.t. cost model parameters update]'

- plutus-core/cost-model/budgeting-bench/Benchmarks/Strings.hs
- plutus-core/cost-model/budgeting-bench/CriterionExtensions.hs
- plutus-core/cost-model/budgeting-bench/Main.hs
The `cost-model-budgeting-bench` executable runs benchmarks for the builtins but also runs some no-op benchmarks to give us an idea of the overhead involved in calling a builtin.  To get accurate results for the no-op benchmarks we run them with a bigger time limit, which involves calling Criterion twice.  If you asked it to benchmark some subset of the builtins (eg, by passing `EqualsString` on the command line) then there would be an error with the message  "none of the specified names matches a benchmark" when it ran the no-op benchmarks (because none of them do match).   This was annoying and also meant that you couldn't run a subset of the benchmarks on the benchmarking machine and get the results back.  This PR removes the error mesage.  Now it's less annoying, but if you ask it to …
> Remove annoying error message

- plutus-core/plutus-core/test/Names/Spec.hs
before adding more tests I want to fix indentation and make imports explicit. 
This allows me to use `fourmolu` when adding new code without mixing up diffs.
> Chore: formatting, imports, pragmas.

- doc/read-the-docs-site/plutus-doc.cabal
- plutus-benchmark/plutus-benchmark.cabal
- plutus-conformance/plutus-conformance.cabal
- plutus-core/CHANGELOG.md
- plutus-core/changelog.d/20240503_135941_Yuriy.Lazaryev_strictify_fix.md
- plutus-core/plutus-core.cabal
- plutus-ledger-api/plutus-ledger-api.cabal
- plutus-metatheory/plutus-metatheory.cabal
- plutus-tx-plugin/plutus-tx-plugin.cabal
- plutus-tx/CHANGELOG.md
- plutus-tx/changelog.d/20240509_114920_unsafeFixIO_index_budget.md
- plutus-tx/plutus-tx.cabal
- prettyprinter-configurable/prettyprinter-configurable.cabal
> Release 1.28.0.0

- RELEASE.adoc
- scripts/prepare-bins.sh
> Script to prepare binary executables for uploading to the github release page.

- .github/workflows/add-triage-label.yml
Add triage label only when the issue does not have any of the 'Internal' labels.
> Conditionally add 'triage' label to new issues

- plutus-ledger-api/src/PlutusLedgerApi/V2/ParamName.hs
- plutus-ledger-api/test/Spec/CostModelParams.hs
- plutus-ledger-api/testlib/PlutusLedgerApi/Test/V2/EvaluationContext.hs
- plutus-ledger-api/testlib/PlutusLedgerApi/Test/V3/EvaluationContext.hs
Should have been done in https://github.com/IntersectMBO/plutus/pull/6056 but I overlooked it.
> Add integerToByteString and byteStringToInteger to V2.ParamName

- .github/workflows/nightly.yml
The nightly.yml workflow will now run 50k test cases by default instead of 10k.
In addition, the nightly.yml workflow will now accept the number of test cases as a workflow_dispatch input.
> Let nightly.yml accept hedgehog-tests input

- .github/workflows/nightly.yml
- nix/project.nix
The nightly tests now run 100k test cases by default and will run on the self-hosted plutus-benchmark instance.
> Run nightly tests on plutus-benchmark

- plutus-core/executables/plutus/AnyProgram/IO.hs
- plutus-core/executables/plutus/AnyProgram/With.hs
This adds a function encompassing all of `withFlatL`, `withShowL` and `withPrettyPlcL`. I'm not even sure that it's worth it at this point, but given that @bezirg asked for it and I liked the challenge, here we go.
> [Exe] Generalize 'withL' to 'withLangGeneral'

- plutus-conformance/plutus-conformance.cabal
- plutus-core/plutus-core.cabal
There was a reference to `benching.csv` in `plutus-core.cabal`.  That file has now been replaced by `benching-vasil.csv` and `benching-conway.csv`, but I don't think either of these is needed in a distribution so I've just removed the entry for the original file.
I'll set this to auto-merge since it's not a big change.
> Remove reference to benching.csv in plutus-core.cabal

- plutus-core/changelog.d/20240530_123928_kenneth.mackenzie_reduce_cek_cpu_step_costs_B.md
- plutus-core/cost-model/data/cekMachineCostsB.json
This adjusts the CPU costs for machine steps in `cekMachineCostsB.json` to match those in `cekMachineCostsC.json`.  This means that after the Chang HF script costs should be approximately the same for PlutusV1, PlutusV2, and PlutusV3, and all should be cheaper than at present.
> Kwxm/costing/reduce CEK CPU step costs B

- plutus-benchmark/bls12-381-costs/bench/Bench.hs
- plutus-benchmark/cek-calibration/Main.hs
- plutus-benchmark/common/PlutusBenchmark/Common.hs
- plutus-benchmark/lists/bench/Bench.hs
- plutus-benchmark/marlowe/bench/BenchCek.hs
- plutus-benchmark/nofib/bench/BenchCek.hs
- plutus-benchmark/nofib/bench/Shared.hs
- plutus-benchmark/plutus-benchmark.cabal
- plutus-benchmark/validation/bench/BenchCek.hs
- plutus-benchmark/validation/bench/BenchFull.hs
I had some trouble doing some benchmarking yesterday and discovered that it was because `mkEvalCtx` was [using the most recent cost model parameters](https://github.com/IntersectMBO/plutus/blob/e675e654c5f8847bd9cf1c25aa6fa0985c8a5e8f/plutus-benchmark/common/PlutusBenchmark/Common.hs#L92) with PlutusV1 and my branch had added some parameters that weren't compatible with the old cost model.  This probably crept in when I was merging [the PR that added the Conway cost model](https://github.com/IntersectMBO/plutus/pull/6087).    I'm not entirely sure what we want to do (cf #6088) but this PR adds a `mkMostRecentEvalCtx` function that creates an evaluation context for the most recent ledger language and semantics variant, and that gets used for all of the benchmarks except for the validation …
> Use the most recent evaluation context for most of the benchmarks

- plutus-core/plutus-ir/src/PlutusIR/Transform/EvaluateBuiltins.hs
- plutus-tx-plugin/plutus-tx-plugin.cabal
- plutus-tx-plugin/test/Plugin/NoTrace/Spec.hs
- plutus-tx-plugin/test/Plugin/NoTrace/WithPreservedLogging.hs
A [user has reported](https://github.com/IntersectMBO/plutus/issues/5949#issuecomment-2141488071) that `preserve-logging` flag is not recognized, so I decided to verify it by adding it to the spec which verifies behavior of the `remove-trace` flag (very related).
(I wasn't able to reproduce the misbehaviour, tests show that in a presence of this flag logs are preserved.)
> Tests for the `preserve-logging` flag.

- plutus-core/plutus-core/src/PlutusCore/Evaluation/Machine/ExBudgetingDefaults.hs
- plutus-ledger-api/test/Spec.hs
- plutus-ledger-api/testlib/PlutusLedgerApi/Test/V2/EvaluationContext.hs
V2 and V3 use different parameter names for `divideInteger` etc.
> Fix V2's costModelParamsForTesting

- scripts/update-version.sh
I had a problem in #6170 because `update-versions.sh` was adding a version bound for the recently-added `plutus-tx-test-utils` package, and this was causing problems for our nix setup  This was because there was a `sed` command which was matching `plutus-tx-test-util` when updating the bounds for `plutus-tx`.  This PR should make the `sed` command match the package name exactly, so it won't matter if one package name is a prefix of another.  In fact the previous version would modify entries for `plutus-tx-plugin` twice, once for `plutus-tx` and once for `plutus-tx-plugin`.  This didn't actually matter because both of those packages are versioned, but `plutus-tx-test-utils` introduced an unversioned package whose name contained the name of a versioned package as a prefix.
> Update update-version.sh to match package names less greedily

- scripts/update-version.sh
`update-version.sh` gave a cryptic error if you gave it a version number without any dots.  This is just a small fix to make it say something more sensible if that happens.  I don't think this needs to be reviewed.
> More error checking for update-vesion.sh

- .github/workflows/combined-haddock.yml
New workflow files must be committed to master before they become available in the GH Actions tab.
This PR introduces the new `combined-haddock.yml` which will be implemented in a separate PR.
By committing this file to master, we can test it immediately.
> Initial version of new combined-haddock.yml workflow

- plutus-ledger-api/changelog.d/20240606_160839_effectfully_polish_imports_and_exports.md
- plutus-ledger-api/exe/analyse-script-events/Main.hs
- plutus-ledger-api/src/PlutusLedgerApi/Common.hs
- plutus-ledger-api/src/PlutusLedgerApi/V1.hs
- plutus-ledger-api/src/PlutusLedgerApi/V1/EvaluationContext.hs
- plutus-ledger-api/src/PlutusLedgerApi/V2.hs
- plutus-ledger-api/src/PlutusLedgerApi/V2/EvaluationContext.hs
- plutus-ledger-api/src/PlutusLedgerApi/V3.hs
- plutus-ledger-api/src/PlutusLedgerApi/V3/EvaluationContext.hs
- plutus-ledger-api/testlib/PlutusLedgerApi/Test/Scripts.hs
- plutus-tx/src/PlutusTx/IsData/Class.hs
This
- resolves #6098
- moves a bunch of stuff shared among `V1`/`V2`/`V3` into `Common` (see the PR review)
- makes all imports in the `Common`/`V1`/`V2`/`V3` modules qualified so that it's clear where definitions come from and whether they are inherited from `Common` or an earlier ledger language
- fixes some formatting, adds a definition for consistency etc
>  [PlutusLedgerApi] [Refactoring] Polish imports and exports

- docusaurus/docs/index.md
This change adds a link to the combined documentation for all the public Plutus code libraries under the heading for "The Plutus repository."
> Adding link to Haddock documentation to index.md

- docusaurus/docs/essential-concepts/plutus-platform.mdx
This PR removes one section from the Plutus platform page -- just the content starting with the heading "Why we call it a platform" including the diagram. This content is badly outdated and is incorrect. Simply removing it will be an important update so that we don't communicate badly outdated information. For example, we no longer support the PAB and there is no longer a Plutus Playground.
> removing outdated and incorrect content from the Plutus platform page

- plutus-core/changelog.d/20240528_112406_bezirg.md
- plutus-core/executables/plutus/AnyProgram/IO.hs
- plutus-core/plutus-core.cabal
- plutus-core/plutus-core/src/Codec/Extras/FlatViaSerialise.hs
- plutus-core/plutus-core/src/Codec/Extras/SerialiseViaFlat.hs
- plutus-core/plutus-core/src/PlutusCore/Flat.hs
- plutus-core/untyped-plutus-core/src/UntypedPlutusCore/Core/Instance/Flat.hs
- plutus-ledger-api/src/PlutusLedgerApi/Common/SerialisedScript.hs
- plutus-ledger-api/test/Spec/CBOR/DeserialiseFailureInfo.hs
- plutus-ledger-api/test/Spec/ScriptDecodeError.hs
- plutus-tx/src/PlutusTx/Coverage.hs
Some refactoring to make SerialiseViaFlat and FlatViaSerialise uniform.
Also removed some code not needed anymore.
> Refactored Serialise/Flat-Via. Fixes #6083

- plutus-core/plutus-core/src/PlutusCore/Builtin/HasConstant.hs
- plutus-core/untyped-plutus-core/test/Evaluation/Builtins/Definition.hs
- plutus-core/untyped-plutus-core/test/Evaluation/Builtins/Golden/List/headList-empty.err.golden
- plutus-core/untyped-plutus-core/test/Evaluation/Builtins/Golden/List/tailList-empty.err.golden
- plutus-core/untyped-plutus-core/test/Evaluation/Builtins/Golden/String/consByteString-out-of-range.err.golden
- plutus-core/untyped-plutus-core/test/Evaluation/Builtins/Golden/String/indexByteString-out-of-bounds-empty.err.golden
- plutus-core/untyped-plutus-core/test/Evaluation/Builtins/Golden/String/indexByteString-out-of-bounds-non-empty.err.golden
This refactors a file with tests so that unit tests that are supposed to result in evaluation failure also become golden tests with the error message printed to a golden file. Need it to demonstrate that #6181 does indeed allow us to preserve operational unlifting errors.
> [Test] [Builtins] Add golden tests with unlifting errors

- plutus-core/untyped-plutus-core/test/Evaluation/Builtins/MakeRead.hs
This is a quick refactoring of one test file. Removes some redundant stuff, changes some wording. Not important in any way. I wanted to replace `hedgehog` with `QuickCheck` here, but then realized that the tests are too unimportant to bother further with them.
> [Test] [Builtin] Polish 'MakeRead' tests

- plutus-ledger-api/plutus-ledger-api.cabal
- plutus-ledger-api/testlib/PlutusLedgerApi/Test/EvaluationEvent.hs
Example of the dependency conflict caused by the `PyF`:
```
last 25 log lines:
> [__6] trying: base-4.18.2.0/installed-4.18.2.0 (dependency of
> byron-spec-chain)
> [__7] trying: cardano-api-8.47.0.0 (user goal)
> [__8] trying: plutus-ledger-api-1.29.0.0 (dependency of cardano-api)
> [__9] trying: PyF-0.11.3.0 (dependency of plutus-ledger-api)
> [_10] trying: ghc-9.6.4/installed-9.6.4 (dependency of PyF)
> [_11] trying: ouroboros-network-framework-0.13.2.0 (dependency of cardano-api)
> [_12] trying: io-classes-1.5.0.0 (dependency of ouroboros-network-framework)
> [_13] next goal: Win32-network (dependency of ouroboros-network-framework)
> [_13] rejecting: Win32-network-0.2.0.0 (conflict: time =>
> Win32==2.13.3.0/installed-2.13.3.0, Win32-network => Win32^>=2.14)
> [_13] rejecting: …
```
> Remove PyF as it depends on GHC and causes depenecy conflicts downstream

- plutus-core/untyped-plutus-core/test/Evaluation/Builtins/SignatureVerification.hs
The number of test cases in the signature verification tests was reduced in #6909, but that makes it more difficult to satisfy the coverage requirements.  This reduces the limits a bit to make the tests more likely to succeed.
> Reduce coverage limits for signature verification tests

- docusaurus/docs/getting-started-plutus-tx.md
For higher visibility, moved the Getting Started page to immediately follow the Introduction page.
> Moved the Getting Started page for higher visibility

- plutus-core/plutus-core/src/PlutusCore/Bitwise.hs
This is just fixing a reference to a Note in the bitwise code whose name has been changed.  I don't think it needs to be reviewed.
> Fix incorrect Note reference

- .github/workflows/plublish-metatheory-site.yml
- nix/plutus-metatheory-site.nix
- plutus-metatheory/src/Type/RenamingSubstitution.lagda.md
- plutus-metatheory/src/index.lagda.md
This PR improves the build script of the plutus metatheory site and adds a new workflow for manually deploying the site to our GitHub Pages
> Add workflow for publishing Agda Metatheory site

- .github/workflows/metatheory-site.yml
- RELEASE.adoc
The workflow can now publish the metatheory site successfully.
The RELEASE.adoc has been updated
> Final changes to `metatheory-site.yml` workflow

- plutus-core/plutus-ir/src/PlutusIR/Compiler/Datatype.hs
Here's a small fix for the comment:
- use one variable for the type everywhere
- fix ordering of `constr` arguments
Additionally,
- align the corresponding parts in the text
- Branch
- PR
> Fix & simplify SOP encoding example comment

- cabal.project
- doc/docusaurus/LICENSE
- doc/docusaurus/docs/using-plutus-tx/producing-a-blueprint.md
- doc/docusaurus/docusaurus-examples.cabal
- doc/docusaurus/plutus.json
- doc/docusaurus/static/code/Example/Cip57/Blueprint/Main.hs
- nix/project.nix
**Before this PR:**
- docusaurus project contains Haskell source files that aren't typechecked and might contain compilation errors.
- A change in the Plutus plug-in or API might break examples without any CI failure.
-  CIP-57 Example validator script isn't compatible with the CIP-69 and CIP-117.
**After this PR:**
- Cabal package `docusaurus-examples` exists to build a single executable `example-cip57` (for now) which compiles a corresponding CIP-57 Blueprint example.
- A change in the Plutus plug-in or API that breaks examples will cause the whole project build to fail CI.
-  CIP-57 Example validator script is compatible with the CIP-69 and CIP-117.
> Cabal project to compile docusaurus examples.

- plutus-ledger-api/plutus-ledger-api.cabal
- plutus-ledger-api/test-plugin/Spec.hs
- plutus-ledger-api/test-plugin/Spec/ScriptSize.hs
Closes #6242 
A spec to demonstrate V3 script size increase when un-marshalling `ScriptContext` as a whole.
This spec also demonstrates alternative (lazy) approach to getting redeemer and datum from a script context without un-marshalling it all.
> Spec that verifies various script sizes, also demostrates a lazy script context un-marshalling

- plutus-tx/src/PlutusTx/Blueprint/Definition/Unroll.hs
- plutus-tx/test/Blueprint/Spec.hs
This fix closes #6163 by adding a type family clause, instead of relying on the generic rep of `[]`
> Fix "un-rolling" a list type.

- doc/docusaurus/docusaurus.config.ts
This reflects the recent addition of the custom `plutus.cardano.intersectmbo.org` CNAME to GitHub Pages
> Update baseUrl in docusaurus.config.ts

- plutus-core/changelog.d/20240701_104059_effectfully_fix_isNormalType.md
- plutus-core/plutus-core/src/PlutusCore/Check/Normal.hs
- plutus-core/plutus-core/src/PlutusCore/Core/Instance/Eq.hs
- plutus-core/plutus-core/src/PlutusCore/Core/Instance/Pretty/Classic.hs
- plutus-core/plutus-core/src/PlutusCore/Core/Instance/Pretty/Readable.hs
- plutus-core/plutus-core/src/PlutusCore/Core/Instance/Scoping.hs
- plutus-core/plutus-core/src/PlutusCore/DeBruijn.hs
- plutus-core/plutus-core/src/PlutusCore/Normalize/Internal.hs
- plutus-core/plutus-core/test/Check/Spec.hs
- plutus-core/plutus-core/test/Normalization/Check.hs
- plutus-core/plutus-ir/test/PlutusCore/Generators/QuickCheck/TypesTests.hs
- plutus-core/testlib/PlutusCore/Generators/NEAT/Type.hs
- plutus-core/testlib/PlutusCore/Generators/QuickCheck/ShrinkTypes.hs
- plutus-core/testlib/PlutusIR/Generators/QuickCheck/GenerateTerms.hs
- plutus-core/testlib/PlutusIR/Generators/QuickCheck/ShrinkTerms.hs
- plutus-metatheory/src/Raw.hs
This fixes a bug in `isNormalType` and adds a test. Without the bug fixed the test fails with
```
PlutusCore.Generators.QuickCheck
TypesTests
normalizedTypeIsNormal: FAIL
*** Failed! 'normalizeType' returned a non-normal type (after 8 tests and 1 shrink):
k,ty = (*, list unit)
```
as expected.
Resolves #6033.
> [Bug] Fix 'isNormalType' and add 'prop_normalizedTypeIsNormal'

- plutus-ledger-api/exe/analyse-script-events/Main.hs
- plutus-ledger-api/exe/common/LoadScriptEvents.hs
- plutus-ledger-api/exe/test-onchain-evaluation/Main.hs
- plutus-ledger-api/src/PlutusLedgerApi/Common/ProtocolVersions.hs
- plutus-ledger-api/src/PlutusLedgerApi/Common/Versions.hs
- plutus-ledger-api/testlib/PlutusLedgerApi/Test/EvaluationEvent.hs
> Analyse script events supports PlutusLedgerLanguage V3

- plutus-core/plutus-core/src/PlutusCore/Bitwise.hs
- plutus-core/plutus-core/src/PlutusCore/Default/Builtins.hs
- plutus-core/untyped-plutus-core/test/Evaluation/Builtins/Bitwise.hs
- plutus-core/untyped-plutus-core/test/Evaluation/Builtins/Definition.hs
- plutus-tx/src/PlutusTx/Builtins/Internal.hs
This repairs an issue spotted by @effectfully and @kwxm in both `shiftByteString` and `rotateByteString`. Specifically, this happened due to `abs minBound = minBound` for `Int`, which would lead to incorrect behaviour if `shiftByteString` or `rotateByteString` was given that value as a shift or rotation argument. More specifically, we added the following:
1. An additional check in `shiftByteString`, via `Integer`, to ensure that this case gets properly trapped;
2. An additional check in `rotateByteString`, via `Integer`, to do the same thing;
3. Test that verifies that any such shift or rotation does not crash, instead giving a sensible result.
> Fix overflow bug in shiftByteString, rotateByteString, add tests to ensure it stays fixed

- cardano-constitution/cardano-constitution.cabal
- doc/docusaurus/docusaurus-examples.cabal
- plutus-benchmark/plutus-benchmark.cabal
- plutus-conformance/plutus-conformance.cabal
- plutus-core/CHANGELOG.md
- plutus-core/changelog.d/20240510_200705_Yuriy.Lazaryev_4808_unique_names_roundtrip_tests.md
- plutus-core/changelog.d/20240618_023306_effectfully_replace_EvaluationResult_with_BuiltinResult.md
- plutus-core/changelog.d/20240620_025344_effectfully_remove_Emitter_and_MonadEmitter.md
- plutus-core/changelog.d/20240626_184002_effectfully_remove_case_of_case.md
- plutus-core/changelog.d/20240701_104059_effectfully_fix_isNormalType.md
- plutus-core/plutus-core.cabal
- plutus-ledger-api/plutus-ledger-api.cabal
- plutus-metatheory/plutus-metatheory.cabal
- plutus-tx-plugin/plutus-tx-plugin.cabal
- plutus-tx-test-util/plutus-tx-test-util.cabal
- plutus-tx/plutus-tx.cabal
- prettyprinter-configurable/prettyprinter-configurable.cabal
Result of `./scripts/prepare-release.sh "1.31.0.0"`
* I had to remove the `create-json-envelope` executable as it depends on the `cardano-api` which in turn depends on the `plutus` making it a circular dependency hindering the plutus version upgrade.
> Release 1.31.0.0

- plutus-tx/src/PlutusTx/Prelude.hs
This re-exports CIP-121, CIP-122 and CIP-123 operations from `PlutusTx.Prelude`.
> Re-export bitwise builtins from PlutusTx.Prelude

- plutus-core/plutus-core/src/PlutusCore/Default/Builtins.hs
- plutus-core/plutus-core/src/PlutusCore/Evaluation/Machine/ExMemoryUsage.hs
- plutus-core/untyped-plutus-core/test/Evaluation/Builtins/Costing.hs
This increases the cost for the `[]` and `(:)` constructors of the `[]` data type. It shouldn't really affect anything since all relevant builtins are constant-time anyway, but making individual pieces of the costing machinery more accurate is always good.
> [Costing] Increase the cost of constructors of '[]'

- plutus-core/plutus-core/src/PlutusCore/Evaluation/Machine/ExMemoryUsage.hs
The instance seems to be unused and it's wrong, so I'm removing it.
> [Costing] Remove the 'ExMemoryUsage' instance for 'SomeTypeIn'

- plutus-ledger-api/testlib/PlutusLedgerApi/Test/EvaluationEvent.hs
An attempt to fix [this error](https://github.com/IntersectMBO/cardano-haskell-packages/actions/runs/10040965058/job/27748192859?pr=840) in CHaP.
> fix: haddock error

- plutus-tx-plugin/src/PlutusTx/Compiler/Expr.hs
- plutus-tx-plugin/src/PlutusTx/Plugin.hs
- plutus-tx-plugin/test/Plugin/Errors/9.6/fromBuiltinUsed.uplc.golden
- plutus-tx-plugin/test/Plugin/Errors/9.6/toBuiltinUsed.uplc.golden
- plutus-tx-plugin/test/Plugin/Errors/Spec.hs
- plutus-tx/src/PlutusTx/Builtins.hs
- plutus-tx/src/PlutusTx/Builtins/HasBuiltin.hs
- plutus-tx/src/PlutusTx/IsData/Class.hs
It used to be possible to use `toBuiltin`/`fromBuiltin` within a smart contract, but this is no longer the case, but this isn't obvious to the users as they already have code with `toBuiltin`/`fromBuiltin` that now just misbehaves instead of throwing a type error or breaking compilation some other way. This fixes the problem by throwing on any usage of `toBuiltin`/`fromBuiltin` with a suggestion to use `toOpaque`/`fromOpaque` instead.
> [Plinth] Ban using 'toBuiltin' and 'fromBuiltin'

- plutus-core/changelog.d/20240726_102834_bezirg_ratinteger.md
- plutus-core/plutus-core/src/PlutusCore/Default/Universe.hs
Prerequisite for introducing #6333 
One argument and the result type is going to be `Natural`
See https://hackage.haskell.org/package/ghc-bignum-1.3/docs/GHC-Num-Integer.html#v:integerPowMod-35-
This is not optimised and left as TODO.
Should work on GHC8.10 onwards. However, Idk yet if the actual builtin will work for GHC8.10.
- Branch
- PR
> [plc] Support for `Natural` numbers in the universe, backed by Integer

- cabal.project
- plutus-core/changelog.d/20240726_165736_Yuriy.Lazaryev_nothunks_0_2.md
- plutus-core/plutus-core.cabal
- plutus-core/plutus-core/src/PlutusCore/Builtin/Runtime.hs
- plutus-ledger-api/test/Spec/Eval.hs
Update `nothunks` version removing `cabal.project` workarounds.
> nothunks ^>= 0.2

- plutus-core/cost-model/budgeting-bench/Benchmarks/Bitwise.hs
- plutus-core/plutus-core/src/PlutusCore/Bitwise.hs
- plutus-core/plutus-core/src/PlutusCore/Default/Builtins.hs
- plutus-core/plutus-core/src/PlutusCore/Evaluation/Machine/ExMemoryUsage.hs
- plutus-core/untyped-plutus-core/test/Evaluation/Builtins/Conversion.hs
- plutus-tx/src/PlutusTx/Builtins/Internal.hs
The `NumBytesCostedAsNumWords` wrapper contained an `Int`, but this changes it to `Integer` for consistency with the other wrappers.  This change also affects the type of `Bitwise.replicateByte`. 
@effectfully There were some conflicts between the recently-committed code for bitwise costing and your PR #6315.  I hope that this will make it easier to reconcile the two.
> Make NumBytesCostedAsNumWords use Integer instead of Int

- plutus-benchmark/lists/bench/Bench.hs
- plutus-benchmark/nofib/bench/Shared.hs
Since we advise to run benchmarks multiple times anyway, there's no need in making them long-running, hence let's run less stuff. Plus, let's not run something that finishes way too quickly, since it's likely that those results are noise.
> [Benchmark] Reduce the number of benchmarks

- plutus-core/plutus-core/src/PlutusCore/Default/Universe.hs
- plutus-core/plutus-ir/test/PlutusCore/Generators/QuickCheck/TypesTests.hs
- plutus-core/untyped-plutus-core/test/Evaluation/Builtins/Definition.hs
This replaces `HasConstantIn` constraints with `KnownBuiltinTypeIn` ones as we use the latter everywhere else. Just a quick refactoring for consistency. I've also downscaled a few slow tests.
> [Refactoring] Use 'KnownBuiltinTypeIn' instead of 'HasConstant' consistently

- plutus-conformance/agda/Spec.hs
- plutus-conformance/haskell-steppable/Spec.hs
- plutus-conformance/haskell/Spec.hs
- plutus-conformance/src/PlutusConformance/Common.hs
- plutus-core/plutus-core/src/PlutusCore/Default/Builtins.hs
- plutus-metatheory/src/Algorithmic/CEK.lagda.md
- plutus-metatheory/src/Builtin.lagda.md
- plutus-metatheory/src/Cost/Model.lagda.md
- plutus-metatheory/src/Cost/Raw.lagda.md
- plutus-metatheory/src/Cost/Size.lagda.md
- plutus-metatheory/src/Untyped/CEK.lagda.md
This adds the bitwise builtins specified in [CIP-0121](https://github.com/cardano-foundation/CIPs/tree/master/CIP-0121) and [CIP-0122](https://github.com/cardano-foundation/CIPs/tree/master/CIP-0122) to the Agda code in `plutus-meatatheory`.  Adding these has exposed a deficiency in the Agda code.  Types in UPLC can have multiple size measures but the metatheory currently only knows about the standard ones:  see issue #6367.  We're expecting conformance tests for the bitwise operations shortly, but the costing problem means that the buudget tests will fail for some of these when `agda-conformance` is run.  To make this a bit more manageable I've modified the conformance tests so that you can separately specify a list of budget tests that are expected to fail.  We can use this to turn off …
> Add the bitwise builtins to the metatheory

- plutus-metatheory/src/Builtin.lagda.md
The Agda interface to `shiftByteString` and `rotateByteString` was bypassing the wrappers, which led to `rotateByteString` handling negative rotations incorrectly: this should fix that  problem.
> Fix Agda interface to `shiftByteString` and `rotateByteString`

- flake.lock
We forgot to update this for a while. I don't think it matters for projects that depend on plutus, since they would use cabal&chap instead. It only matters for local plutus nix dev and creating executables , I think?
> Update chap&hackage nix flake sha

- doc/adr/README.md
- doc/adr/adr1.md
- doc/adr/adr2.md
- doc/adr/adr3.md
- doc/adr/adr4.md
- doc/docusaurus/docs/adr/_category_.json
I haven't come across any programming language user documentation that contains an ADR section. Plus these ADRs are of little interest to users.
> Remove ADRs from user documentation

- cabal.project
- doc/docusaurus/docusaurus-examples.cabal
- nix/project.nix
- plutus-benchmark/plutus-benchmark.cabal
- plutus-conformance/plutus-conformance.cabal
- plutus-core/plutus-core.cabal
- plutus-ledger-api/plutus-ledger-api.cabal
- plutus-metatheory/plutus-metatheory.cabal
- plutus-tx-plugin/plutus-tx-plugin.cabal
In Plutus, several packages cannot be built on Windows (e.g., plutus-benchmark, plutus-tx-plugin, plutus-conformance). Currently, we mark these packages as not buildable in nix/project.nix using haskell.nix. However, this creates two inconsistent sources of truth: cabal.project and nix/project.nix. This PR addresses the issue by moving the relevant logic from nix/project.nix to the corresponding .cabal files.
> Move  cross-compiling logic from project.nix to cabal

- .github/workflows/haddock-site.yml
- .github/workflows/metatheory-site.yml
- README.adoc
- plutus-metatheory/README.md
This PR changes the deployment workflow for the metatheory site.
It used to be deployed only to 
`https://plutus.cardano.intersectmbo.org/metatheory`
But now it will be deployed to:
`https://plutus.cardano.intersectmbo.org/metatheory/{$version,latest,master}`
> Support Versioned Metatheory Site

- .github/workflows/sprint-issues-rollover.yml
The sprint-issues-rollover.yml has been tested on a private project and seems to work well.
The workflow will no longer run automatically to avoid unpleasant surprises.
It will be sufficient to run the workflow manually at any point *after* the new sprint has begun, once every two weeks.
To do so, click the `Run workflow (Branch: master)` button at [this link](https://github.com/IntersectMBO/plutus/actions/workflows/sprint-issues-rollover.yml).
> Test Sprint Issues Rollover Workflow On Private Project

- doc/docusaurus/docs/working-with-scripts/script-purposes.md
The documentation incorrectly asserted that a script can be used to require that certain transactions are provided for registration of the associated staking credential. That will be the case in the next era after Conway when `staking_registration` is deprecated, but as it stands currently, any staking credential (even those that contain a script hash) can be registered without any witness and thus it is not currently possible to enforce that a script must be executed in the transaction for registration to succeed.
- Branch
- PR
> Fix incorrect documentation regarding registration certifications

- plutus-core/changelog.d/20240903_180833_effectfully_swap_structural_and_operational_errors.md
- plutus-core/plutus-core/src/PlutusCore/Builtin/Result.hs
- plutus-core/plutus-core/src/PlutusCore/Evaluation/Error.hs
- plutus-core/plutus-core/src/PlutusCore/Evaluation/Machine/Ck.hs
- plutus-core/plutus-core/src/PlutusCore/Evaluation/Machine/Exception.hs
- plutus-core/plutus-core/test/Evaluation/Machines.hs
- plutus-core/testlib/PlutusCore/Generators/Hedgehog/Test.hs
- plutus-core/testlib/PlutusCore/Generators/Hedgehog/TypeEvalCheck.hs
- plutus-core/testlib/PlutusCore/Generators/NEAT/Spec.hs
- plutus-core/untyped-plutus-core/src/UntypedPlutusCore/Evaluation/Machine/Cek/Internal.hs
- plutus-core/untyped-plutus-core/src/UntypedPlutusCore/Evaluation/Machine/SteppableCek/Internal.hs
- plutus-core/untyped-plutus-core/test/Evaluation/Machines.hs
This simply swaps around two type variables and two constructors, affecting `EvaluationError` and `EvaluationException`. Structural errors correspond to type errors and operational errors correspond to runtime errors, hence the former "precede" the latter. This PR finally reflects that perceived ordering. It's not really important, but I've got things mixed up before due to the previously counter-intuitive ordering, so I thought it'd be worth fixing it, given how easy that is.
> [Errors] Swap operational and structural errors

- doc/docusaurus/docs/delve-deeper/plutus-tx-compiler-options.md
- plutus-tx-plugin/changelog.d/20240906_143413_unsafeFixIO_evaluate_builtins.md
- plutus-tx-plugin/src/PlutusTx/Options.hs
This flag is currently missing, `_posDoSimplifierEvaluateBuiltins` is always true and cannot be turned off.
> Add a compiler flag for the evaluateBuiltins pass

- plutus-conformance/agda/Spec.hs
- plutus-conformance/haskell-steppable/Spec.hs
- plutus-conformance/haskell/Spec.hs
- plutus-core/plutus-core/src/PlutusCore/Bitwise.hs
- plutus-core/untyped-plutus-core/test/Evaluation/Builtins/Bitwise.hs
- plutus-core/untyped-plutus-core/test/Evaluation/Builtins/Definition.hs
Supercedes #6459, with a cleaner history. Additionally, instead of unit tests for the regression cases, there's now a property test instead.
> Fix regression, ensure it doesn't come back with a property test

- plutus-core/executables/src/PlutusCore/Executable/Common.hs
`uplc print-builtin-signatures` prints out a table of all of the builtins and their signatures.  After some changes in the prettyprinter a while ago this was printing out things like
```
ifThenElse                         : [ forall a, bool, a-0, a-0 ] -> a-0
```
This PR jsut makes it use a vesion of the prettyprinter that gives
```
ifThenElse                         : [ forall a, bool, a, a ] -> a
```
instead.
> Fix printing of type variables in print-builtin-signatures

- doc/docusaurus/package.json
- doc/docusaurus/yarn.lock
Upgrade yarn packages as suggested by dependabot, to address vulnerability issues.
See https://github.com/IntersectMBO/plutus/pull/6475
> Address Dependabot Alerts for Docusaurus

- plutus-core/changelog.d/20240913_101059_kenneth.mackenzie.md
We failed to add a changelog entry for the `findFirstSetBit` builtin bugfix in #6459/#6461, but it should probably be mentioned.
> Add forgotten changelong entry

- plutus-benchmark/nofib/exe/Main.hs
- plutus-core/executables/plutus/AnyProgram/Compile.hs
- plutus-core/plutus-core.cabal
- plutus-core/plutus-core/src/PlutusCore/Builtin/Result.hs
- plutus-core/plutus-core/src/PlutusCore/Default/Builtins.hs
- plutus-core/plutus-core/src/PlutusCore/Evaluation/Machine/Ck.hs
- plutus-core/plutus-core/src/PlutusCore/Evaluation/Machine/Exception.hs
- plutus-core/plutus-ir/test/PlutusIR/Generators/QuickCheck/Tests.hs
- plutus-core/plutus-ir/test/PlutusIR/Transform/StrictLetRec/Tests/Lib.hs
- plutus-core/prelude/PlutusPrelude.hs
- plutus-core/testlib/PlutusCore/Generators/Hedgehog/TypeEvalCheck.hs
- plutus-core/testlib/PlutusCore/Test.hs
- plutus-core/untyped-plutus-core/src/UntypedPlutusCore/Evaluation/Machine/Cek.hs
- plutus-core/untyped-plutus-core/src/UntypedPlutusCore/Evaluation/Machine/Cek/Internal.hs
- plutus-core/untyped-plutus-core/src/UntypedPlutusCore/Evaluation/Machine/CommonAPI.hs
- plutus-core/untyped-plutus-core/src/UntypedPlutusCore/Evaluation/Machine/SteppableCek.hs
- plutus-core/untyped-plutus-core/test/Evaluation/Builtins/Common.hs
- plutus-core/untyped-plutus-core/test/Evaluation/Builtins/Definition.hs
- plutus-core/untyped-plutus-core/test/Evaluation/Builtins/MakeRead.hs
- plutus-core/untyped-plutus-core/test/Evaluation/Machines.hs
- plutus-core/untyped-plutus-core/test/Transform/CaseOfCase/Test.hs
- plutus-tx-test-util/testlib/PlutusTx/Test/Util/Compiled.hs
What the title says.
In theory, this is supposed to conclude the investigation on the "runtime type system" for UPLC. In practice unfortunately, PIR generators aren't very helpful here as per the recent Slack discussion (I'll reflect that in some GitHub issue later), plus the compiler being too slow doesn't help either. So this PR is more of a proof of concept than an actually helpful test, but better than nothing I suppose.
Resolves #6150.
> [Errors] Test that evaluation of a well-typed term doesn't fail with a structural error

- plutus-tx/src/PlutusTx/Data/AssocMap.hs
I was looking into what relies upon these instances
```haskell
instance ToData BuiltinData where
{-# INLINABLE toBuiltinData #-}
toBuiltinData = id
instance FromData BuiltinData where
{-# INLINABLE fromBuiltinData #-}
fromBuiltinData d = Just d
instance UnsafeFromData BuiltinData where
{-# INLINABLE unsafeFromBuiltinData #-}
unsafeFromBuiltinData d = d
```
existing and a few things in `PlutusTx.Data.AssocMap` popped up, but none of them actually needs to rely on the instance, so I tweaked the code a bit.
> [Refactoring] Tweak 'PlutusTx.Data.AssocMap'

- doc/adr/adr3.md
- plutus-benchmark/bls12-381-costs/src/PlutusBenchmark/BLS12_381/Scripts.hs
- plutus-benchmark/ed25519-costs/src/PlutusBenchmark/Ed25519/Common.hs
- plutus-core/cost-model/budgeting-bench/Common.hs
- plutus-core/plutus-core/src/PlutusCore/Builtin/Meaning.hs
- plutus-core/plutus-core/src/PlutusCore/Default/Universe.hs
- plutus-core/plutus-core/src/PlutusCore/Evaluation/Machine/CostingFun/Core.hs
- plutus-core/plutus-core/src/PlutusCore/Evaluation/Machine/ExBudgetingDefaults.hs
- plutus-core/plutus-core/src/PlutusCore/Evaluation/Machine/ExMemoryUsage.hs
- plutus-core/untyped-plutus-core/src/UntypedPlutusCore/Evaluation/Machine/Cek/Internal.hs
- plutus-metatheory/Setup.hs
- plutus-tx-plugin/src/PlutusTx/Plugin.hs
- plutus-tx-plugin/test/Plugin/Data/Spec.hs
- plutus-tx-plugin/test/Plugin/Laziness/Spec.hs
- plutus-tx-plugin/test/Plugin/Typeclasses/Spec.hs
- plutus-tx/src/PlutusTx/Builtins/Internal.hs
- plutus-tx/src/PlutusTx/Plugin/Utils.hs
This replaces all occurrences of `NOINLINE` with the more reliable `OPAQUE`. However unlike `NOINLINE` `OPAQUE` prevents specialization, so let's benchmark this to make sure there's no unexpected slowdown. 
Resolves #6269.
> [Refactoring] Replace 'NOINLINE' with 'OPAQUE'

- plutus-metatheory/src/VerifiedCompilation/Purity.lagda.md
- plutus-metatheory/src/VerifiedCompilation/UCaseOfCase.lagda.md
- plutus-metatheory/src/VerifiedCompilation/UFloatDelay.lagda.md
- plutus-metatheory/src/VerifiedCompilation/UForceDelay.lagda.md
- plutus-metatheory/src/VerifiedCompilation/UntypedTranslation.lagda.md
- plutus-metatheory/src/VerifiedCompilation/UntypedViews.lagda.md
Translation relation and decision procedure for the Float-Delay phase of the UPLC certifying compiler.
This typechecks and follows the description of the phase, but it hasn't been tested against many real examples. 
Fixes #6371
> Translation relation and decision procedure for the Float-Delay

- plutus-ledger-api/src/PlutusLedgerApi/Common/Versions.hs
- plutus-ledger-api/src/PlutusLedgerApi/V3/ParamName.hs
- plutus-ledger-api/test/Spec/CostModelParams.hs
- plutus-ledger-api/test/Spec/Data/CostModelParams.hs
- plutus-ledger-api/testlib/PlutusLedgerApi/Test/V3/Data/EvaluationContext.hs
- plutus-ledger-api/testlib/PlutusLedgerApi/Test/V3/EvaluationContext.hs
This disables `writeBits` for chang+1, so that we have more time to fix it as per #6528.
I've checked that the neither `plutus-core` nor `plutus-ledger-api` mention `writeBits` in their changelogs.
> [Builtins] Disable 'writeBits' for chang+1

- doc/plutus-core-spec-old/figures/TypedCkMachine.tex
- doc/plutus-core-spec-old/figures/UntypedCekMachine.tex
- doc/plutus-core-spec-old/figures/UntypedCkMachine.tex
- doc/plutus-core-spec/README.md
- nix/latex-documents.nix
A change in some package caused `\captionof` to stop working inside subfigures (I think) in the old version of the specification.  This replaces the problematic uses with `\caption`:  it doesn't seem to make any significant difference to the PDF apart from maybe some changes in spacing.  I also restored a link to the PDF of the new specification in a README file.
> Fix latex errors in old specification

- doc/plutus-core-spec/cardano/builtins3.tex
- doc/plutus-core-spec/plutus-core-specification.tex
When I was looking at the conformance tests for `verifySchnorrSecp256k1Signature` and `verifyEcdsa256k1Signature` I noticed that the specification wasn't too precise about when the functions should fail and when they should return `False`.  This makes it a bit more precise, although maybe not quite as precise as it might be (there are a lot of edge cases that need to be rejected).  I may come back to this later.
> Improve specification of the Secp256k1 signature verification functions

- plutus-tx/src/PlutusTx/ErrorCodes.hs
The keys in the list are not in ascending order, and there's no reason to use this unsafe function anyway.
> Fix incorrect `fromDistinctAscList` in PlutusTx.ErrorCodes

- plutus-executables/plutus-executables.cabal
This file does not exist and causes `cabal haddock` to fail.
> Remove extra-doc-files:README.md from plutus-executables.cabal

- .hlint.yaml
- plutus-ledger-api/changelog.d/20241107_164059_Yuriy.Lazaryev_with_currency_symbol.md
- plutus-ledger-api/plutus-ledger-api.cabal
- plutus-ledger-api/src/PlutusLedgerApi/V1/Data/Value.hs
- plutus-ledger-api/src/PlutusLedgerApi/V1/Value.hs
- plutus-ledger-api/test-plugin/Spec.hs
- plutus-ledger-api/test-plugin/Spec/Budget/9.6/currencySymbolValueOf.pir.golden
- plutus-ledger-api/test-plugin/Spec/Data/Budget/9.6/currencySymbolValueOf.pir.golden
- plutus-ledger-api/test-plugin/Spec/Value/WithCurrencySymbol.hs
- plutus-ledger-api/test/Spec/V1/Data/Value.hs
Closes https://github.com/IntersectMBO/plutus/issues/5992
> `PlutusLedgerApi.V1.withCurrencySymbol`

- nix/shell.nix
- scripts/ci-plutus-benchmark.sh
You can now run 
`/benchmark BENCH_NAME cap=CAPABILITY_NUM` 
In addition to 
`/benchmark BENCH_NAME`  
The former will run BENCH_NAME on the given CPU core
> Use taskset in ci-plutu-benchmark.sh

- scripts/ci-plutus-benchmark.sh
I think the cases for what to do when `taskset` is/isn't available were the wrong way round in #6646.  This swaps them around.
> Swap cases for availability of taskset

- plutus-ledger-api/changelog.d/20241111_125402_Yuriy.Lazaryev_plutus_ledger_api_v1.md
- plutus-ledger-api/src/PlutusLedgerApi/V1.hs
- plutus-ledger-api/src/PlutusLedgerApi/V1/Address.hs
- plutus-ledger-api/test/Spec/V1/Value.hs
> refactor: PlutusLedgerApi.V1

- plutus-benchmark/bench-compare-markdown
This is just a small fix to avoid a division by zero error in the benchmark comparison script.  This would happen when calculating the change in total execution time if the benchmarks failed to run for some reason because then the total time would be zero..
> Avoid division by zero in benchmark comparisons

- plutus-core/plutus-core/src/PlutusCore/Crypto/BLS12_381/G1.hs
- plutus-core/plutus-core/src/PlutusCore/Crypto/BLS12_381/G2.hs
Hi team,
This simple PR makes the type applications for functions involving G1 and G2 explicit. The change is necessary due to a recent update in cardano-base ([PR #509](https://github.com/IntersectMBO/cardano-base/pull/509)), where internal constructors were exposed. Without this adjustment, plutus-core encounters issues when interacting with these updated types. More explicitly, it will throw for example
```bash
plutus-core/src/PlutusCore/Crypto/BLS12_381/G1.hs:162:42: error: [GHC-39999]
• Ambiguous type variable ‘curve4’ arising from a use of ‘BlstBindings.Internal.blsGenerator’
prevents the constraint ‘(BlstBindings.Internal.BLS
curve4)’ from being solved.
Probable fix: use a type annotation to specify what ‘curve4’ should be.
Potentially matching instances:
instance …
```
> add explicit type application on bls operations for G1/G2

- plutus-tx-plugin/src/PlutusTx/Compiler/Builtins.hs
- plutus-tx-plugin/src/PlutusTx/Compiler/Expr.hs
- plutus-tx-plugin/src/PlutusTx/Compiler/Utils.hs
- plutus-tx/src/PlutusTx/Builtins/HasOpaque.hs
Some chores before adding new functionality:
Extracted 3 utility lookup functions:
1. `lookupGhcId :: Compiling uni fun m ann => TH.Name -> m GHC.Id`
2. `lookupGhcName :: Compiling uni fun m ann => TH.Name -> m GHC.Name`
3. `lookupGhcTyCon :: Compiling uni fun m ann => TH.Name -> m GHC.TyCon`
and used them uniformly where appropriate. This allowed to reduce some code duplication in `compileExpr`
> Refactor: reduce code duplication and make more uniform how plugin looks up GHC things (Names, Ids, etc.)

- plutus-core/plutus-core.cabal
- Branch
- PR
exposes `index-envs` to public
Resolves #6675
> Expose `index-envs` library to public

- doc/docusaurus/package.json
- doc/docusaurus/yarn.lock
This is needed to fix Dependabot Security Alerts, but the build currently fails with:
```
[ERROR] Error: Unable to build website for locale en.
at tryToBuildLocale (/Volumes/Repos/plutus/doc/docusaurus/node_modules/@docusaurus/core/lib/commands/build/build.js:78:15)
at async /Volumes/Repos/plutus/doc/docusaurus/node_modules/@docusaurus/core/lib/commands/build/build.js:34:9
at async mapAsyncSequential (/Volumes/Repos/plutus/doc/docusaurus/node_modules/@docusaurus/utils/lib/jsUtils.js:21:24)
at async Command.build (/Volumes/Repos/plutus/doc/docusaurus/node_modules/@docusaurus/core/lib/commands/build/build.js:33:5) {
[cause]: TypeError: Cannot read properties of undefined (reading 'load')
at html2text (/Volumes/Repos/plutus/doc/docusaurus/node_modules/@cmfcmf/docusaurus-search-local/lib/serve …
```
> Upgrade Docusaurus to 3.6.0

- plutus-core/changelog.d/20241126_024818_effectfully_strictify_spend.md
- plutus-core/untyped-plutus-core/src/UntypedPlutusCore/Evaluation/Machine/Cek/ExBudgetMode.hs
I used to see this:
```haskell
$j_sXeb (x#_aWMv :: Int#) (wild1_aWMu :: Int)
= let! { I# ipv6_sXec ~ wild3_X8 <- wild1_aWMu } in
```
and now I see this:
```haskell
$w$j_sum7 :: Int# -> Int# -> (# State# s_sumh, () #)
$w$j_sum7 (x#_sum1 :: Int#) (ww2_sum4 :: Int#)
```
in the GHC Core of the `spend` local function in `UntypedPlutusCore.Evaluation.Machine.Cek.ExBudgetMode`. It's a tiny but welcome improvement.
> [Evaluation] [Performance] Strictify 'spend'

- .github/workflows/manual-benchmark.yml
- scripts/ci-plutus-benchmark.sh
The benchmarking machine has been configured to use the "performance" frequency governor on all cores.
This means that we no longer need to specify which core to run on, nor do we need to set the governor each time we run the benchmarks.
> Remove taskset usage from ci-plutus-benchmarks.sh

- doc/docusaurus/docusaurus.config.ts
Add config for trailing slashes to docs site for scraping/seo purposes - removing automatic redirect happening where it was adding a trailing slash
> filip(fix): add config for trailing slashes

- plutus-core/changelog.d/20241211_095642_1009751+Unisay_relax_crypto_upper_bound.md
- plutus-core/plutus-core.cabal
I can confirm that plutus builds just fine with the version of `cardano-crypto-class-2.2` that we are getting to release on CHaP.
- Branch
- PR
> Relax upper bound on `cardano-crypto-class`

- flake.lock
- flake.nix
- nix/agda.nix
- nix/build-latex-doc.nix
- nix/build-latex.nix
- nix/latex-documents.nix
- nix/outputs.nix
- nix/plutus-metatheory-site.nix
- nix/project.nix
- nix/shell.nix
- nix/unraveling-recursion-paper.nix
2nd attempt to update nix flake
> nix flake update

- plutus-benchmark/nofib/src/PlutusBenchmark/NoFib/Queens.hs
- plutus-tx/src/PlutusTx/Ord.hs
addresses #6270 
`git grep -e "^class .* where" -- **/*.hs`
[`Ord`](https://hackage.haskell.org/package/base-4.20.0.1/docs/Data-Ord.html) is a type class that defines a total ordering for types. 
A pragma is a special instruction or directive that provides additional information to the compiler, allowing for optimizations or modifications in how the code is processed. Pragmas are denoted by the syntax `{-# ... #-}`, and they do not generally affect the semantic meaning of the program, but they can influence performance and behavior during compilation.
the `MINIMAL` pragma is used to specify the minimal complete definition of a type class, indicating which methods must be implemented for an instance of that class. This is particularly useful for classes that have methods with circular …
> add `MINIMAL` pragma to ord

- doc/plutus-core-spec/cardano/builtins5.tex
The plutus core spec Builtins Batch 5 Note 1 mentions that for the extending case of and/xor/orByteString, the bytestrings are extended with 0/1/1 respectively. This contradicts conformance test andByteString/case-06 and the statement a few sentences later that "In both cases, the otuput is the same as the input when 𝑘 = 0". Moreover the formular later also contradicts this. I assume this is a simple case of flipped bit in the first mention.
Further:
- fix typo otuput -> output
- fix typo in return type of readBit: bytestring -> bool
> Fix typos in Plutus Core Spec of Batch 5 builtins

- doc/docusaurus/static/code/generate-keys.mjs
- doc/docusaurus/static/code/mint-token-for-auction.mjs
In the latest version of mesh, `getUnusedAddresses` and `getUsedAddresses` return `Promise`, necessitating `await`.
> Fix an error related to mesh wallet

- plutus-conformance/src/PlutusConformance/Common.hs
This works around the problem described in #6714.
> Use ignoreTest instead of expectFail in conformance tests

- doc/docusaurus/docs/working-with-scripts/optimizing-scripts-with-asData.md
Fixes https://github.com/IntersectMBO/plutus-private/issues/1213
> Add docs on data-backed ScriptContext

- plutus-core/changelog.d/20241126_025636_effectfully_statically_unroll_itraverseCounter_.md
- plutus-core/untyped-plutus-core/src/UntypedPlutusCore/Evaluation/Machine/Cek/StepCounter.hs
Results in a statically unrolled loop:
```haskell
let! { (# ipv10_X1x, ipv11_X1y #) ~ <- $wf_svLt 0# (ipv8_itGb `cast` <Co:8>) } in
let! { (# ipv12_X1B, ipv13_X1C #) ~ <- $wf_svLt 1# ipv10_X1x } in
let! { (# ipv14_X1F, ipv15_X1G #) ~ <- $wf_svLt 2# ipv12_X1B } in
let! { (# ipv16_X1U, ipv17_X1V #) ~ <- $wf_svLt 3# ipv14_X1F } in
let! { (# ipv18_X1X, ipv19_X1Y #) ~ <- $wf_svLt 4# ipv16_X1U } in
let! { (# ipv20_X20, ipv21_X21 #) ~ <- $wf_svLt 5# ipv18_X1X } in
let! { (# ipv22_X23, ipv23_X24 #) ~ <- $wf_svLt 6# ipv20_X20 } in
let! { (# ipv24_X29, ipv25_X2a #) ~ <- $wf_svLt 7# ipv22_X23 } in
let! { (# ipv26_X2f, ipv27_X2g #) ~ <- $wf_svLt 8# ipv24_X29 } in
let! { (# ipv28_X2l, ipv29_X2m #) ~ <- $wf_svLt 9# ipv26_X2f } in
let! { UnsafeRefl v4_itGA ~ <- unsafeEqualityProof } in
let! { UnsafeRefl …
```
> [Evaluation] Statically unroll 'itraverseCounter_'

- doc/docusaurus/package.json
This fixes incorrect rendering of mjs files in the docusaurus build.
This will be reverted once [this PR](https://github.com/IntersectMBO/plutus/pull/6780) is merged
> Disable .js file minification in docusaurus build

- plutus-core/changelog.d/20250114_110640_bezirg_steppable_sop_fix.md
- plutus-core/untyped-plutus-core/src/UntypedPlutusCore/Evaluation/Machine/SteppableCek/Internal.hs
> Fix the Steppable CEK machine to correctly "pause/step" in case of SOPs.

- plutus-core/plutus-core.cabal
- plutus-core/plutus-core/src/PlutusCore/Check/Scoping.hs
- plutus-core/plutus-core/src/PlutusCore/Core/Instance/Scoping.hs
- plutus-core/plutus-ir/src/PlutusIR/Core/Instance/Scoping.hs
- plutus-core/plutus-ir/test/PlutusIR/Scoping/Tests.hs
- plutus-core/prelude/PlutusPrelude.hs
- plutus-core/testlib/PlutusCore/Test.hs
- plutus-core/untyped-plutus-core/src/UntypedPlutusCore/Core/Instance.hs
- plutus-core/untyped-plutus-core/src/UntypedPlutusCore/Core/Instance/Scoping.hs
- plutus-core/untyped-plutus-core/src/UntypedPlutusCore/Rename/Internal.hs
- plutus-core/untyped-plutus-core/test/Generators.hs
- plutus-core/untyped-plutus-core/test/Scoping/Spec.hs
- plutus-core/untyped-plutus-core/test/Spec.hs
This adds scoping tests for UPLC the same way we have them for PIR. It also tweaks the way the scoping machinery handles case-expressions for PIR.
I didn't stumble upon any unexpected behavior.
> [UPLC] [Test] Add scoping tests

- plutus-conformance/haskell-steppable/Spec.hs
- plutus-conformance/plutus-conformance.cabal
> conformance: Add budgeting for haskell steppable

- plutus-core/changelog.d/20250128_170723_unsafeFixIO_circuit.md
- plutus-core/plutus-ir/src/PlutusIR/Analysis/Dependencies.hs
- plutus-core/plutus-ir/test/PlutusIR/Analysis/RetainedSize/datatypeLiveConstr.golden
- plutus-core/plutus-ir/test/PlutusIR/Analysis/RetainedSize/datatypeLiveDestr.golden
- plutus-tx-plugin/test/Plugin/Data/9.6/monomorphic/stakingCredential.pir.golden
- plutus-tx-plugin/test/Plugin/Data/Spec.hs
`clique` apparently treats the graph as undirected, as its Haddock says:
> clique [x,y]      == edge x y
> clique [x,y,z]    == edges [(x,y), (x,z), (y,z)]
This is not what we want - we want all pairs of nodes to be mutually reachable. So what we should use is `circuit`.
> Replace `clique` with `circuit` in dead code elimination

- doc/docusaurus/docs/auction-smart-contract/end-to-end/mint.md
- doc/docusaurus/docs/auction-smart-contract/on-chain-code.md
- doc/docusaurus/docusaurus-examples.cabal
- doc/docusaurus/static/code/AuctionValidator.hs
- doc/docusaurus/static/code/QuickStart.hs
Closed https://github.com/IntersectMBO/plutus/issues/6519
I've also added existing `QuickStart.hs` module as an `executable` to cabal project. 
It allowed me to `cabal run quickstart`  generating `validator.uplc` from `AuctionValidator.hs`.
> Update the auction example in the user guide to Plutus V3

- .github/workflows/cabal-build-all.yml
- doc/docusaurus/docusaurus-examples.cabal
- plutus-benchmark/plutus-benchmark.cabal
- plutus-core/plutus-core.cabal
- scripts/combined-haddock.sh
These changes are needed to account for the exceptional steps needed to publish release 1.40.0.0, which left master in an inconsistent state.
> Fix combined-haddock.sh, remove release-1.30.0.0 folder, restore cardano-crypto-class ^>=2.2

- plutus-core/plutus-core/src/PlutusCore/Evaluation/Machine/ExBudget.hs
- plutus-core/plutus-ir/test/PlutusIR/Generators/QuickCheck/Tests.hs
- plutus-core/untyped-plutus-core/src/UntypedPlutusCore/Evaluation/Machine/Cek.hs
- plutus-core/untyped-plutus-core/src/UntypedPlutusCore/Evaluation/Machine/Cek/ExBudgetMode.hs
- plutus-core/untyped-plutus-core/test/Evaluation/Builtins/Definition.hs
We have a test ensuring that running a builtin call forever gonna drain the budget, but we don't have a test that running regular function calls forever will. This adds such a test. It'll also be useful to test #6793.
> [Test] Add 'fix id'

- scripts/interactive-release.sh
Instead of listing the commits between since the last release, the `interactive-release.sh` script will now collect the changes from the CHANGELOG.md files and use them as release notes.
> Add nicer changelog to plutus release notes

- plutus-executables/executables/uplc/Main.hs
- plutus-executables/plutus-executables.cabal
On the chain scripts are encoded using `flat` but `data` objects (in redeemers etc) are encoded using CBOR.  This PR adds an `apply-to-cbor-data` option to the `uplc` command that lets you apply a script to a list of such CBOR-encoded `data` objects.
We should really be using the unified `plutus` command instead, but it was a lot quicker for me to add this to `uplc`.
> Add apply-to-cbor-data option to uplc

- plutus-tx/changelog.d/20250211_170605_unsafeFixIO_null.md
- plutus-tx/src/PlutusTx/Data/List.hs
Adding `null` so that we can migrate the [ledger scripts](https://github.com/IntersectMBO/cardano-ledger/blob/47b7cc06790814fa9bb8584f14d38f9dbcf59f65/libs/plutus-preprocessor/src/Cardano/Ledger/Plutus/Preprocessor/Binary/V3.hs#L42-L177).
> Add PlutusTx.Data.List.null

- doc/notes/model/UTxO.hsproj/Examples/Keys.hs
- doc/notes/model/UTxO.hsproj/Types.hs
- doc/notes/model/UTxO.hsproj/UTxO.cabal
- doc/notes/model/UTxO.hsproj/Witness.hs
- plutus-core/plutus-core.cabal
- plutus-core/plutus-core/src/PlutusCore/Crypto/Ed25519.hs
- plutus-core/plutus-core/src/PlutusCore/Default/Builtins.hs
- plutus-metatheory/plutus-metatheory.cabal
- plutus-metatheory/src/Builtin.lagda.md
- plutus-tx/src/PlutusTx/Builtins/Internal.hs
This removes the `verifyEd25519Signature_V1` builtin variant, which in turn removes our dependency on the `crypton`/`cryptonite` library and the deprecated `cardano-crypto` package.
> Kwxm/crypto/remove ed25519-donna

- plutus-core/cost-model/create-cost-model/BuiltinMemoryModels.hs
- plutus-core/cost-model/data/builtinCostModelA.json
- plutus-core/cost-model/data/builtinCostModelB.json
- plutus-core/cost-model/data/builtinCostModelC.json
- plutus-core/plutus-core/src/PlutusCore/Default/Builtins.hs
- plutus-core/plutus-core/test/TypeSynthesis/Golden/Signatures/DefaultFun/DropList.sig.golden
- plutus-core/plutus-core/test/TypeSynthesis/Golden/Signatures/DefaultFun/LengthOfArray.sig.golden
This PR
- fixes the bug with the denotation of `dropList` taking an `Integer` rather than an `IntegerCostedLiterally`
- makes the cost model `constant_cost`
- adds some comments
- adds the missing golden files
> [Builtins] [Bug] Tweak 'dropList' costing and else

- doc/docusaurus/docs/working-with-scripts/ledger-language-version.md
Fixed 3 broken links :
a) CIP-69  from  `https://developers.cardano.org/docs/governance/cardano-improvement-proposals/cip-0069/` to `https://cips.cardano.org/cip/CIP-69`
b) CIP-117 from  `https://developers.cardano.org/docs/governance/cardano-improvement-proposals/cip-0117/` to `https://cips.cardano.org/cip/CIP-0117`
c) UnsafeFromData class from `http://localhost:3000/docs/working-with-scripts/ledger-language-version` to `https://plutus.cardano.intersectmbo.org/haddock/master/plutus-ledger-api/PlutusLedgerApi-V1.html#t:UnsafeFromData`
> Fixed 3 broken links  CIP-69,  CIP-117 and UnsafeFromData

- plutus-benchmark/.gitignore
The .gitignore paths had to be adjusted.
> Fix .gitignore pattern for flat files generated by exe:marlowe-validators

- plutus-benchmark/marlowe/exe/Main.hs
- plutus-benchmark/marlowe/exe/PlutusBenchmark/Marlowe/RolePayout.hs
- plutus-benchmark/marlowe/exe/PlutusBenchmark/Marlowe/Semantics.hs
- plutus-benchmark/marlowe/exe/PlutusBenchmark/Marlowe/Util.hs
- plutus-benchmark/marlowe/test/Spec.hs
- plutus-benchmark/plutus-benchmark.cabal
Applied `fourmolu` to a few marlowe-related modules under the `plutus-benchmark` package.
Also added several manual improvements, e.g. moved language extensions to the cabal file.
TLDR: this PR is a refactoring, contains no semantic changes.
> chore: fourmolize PlutusBenchmark/Marlowe

- cabal.project
- plutus-core/plutus-core.cabal
- plutus-ledger-api/changelog.d/20250130_1148_erikd_typeable.md
- plutus-ledger-api/src/PlutusLedgerApi/V1/Address.hs
- plutus-ledger-api/src/PlutusLedgerApi/V1/Bytes.hs
- plutus-ledger-api/src/PlutusLedgerApi/V1/Credential.hs
- plutus-ledger-api/src/PlutusLedgerApi/V1/Crypto.hs
- plutus-ledger-api/src/PlutusLedgerApi/V1/DCert.hs
- plutus-ledger-api/src/PlutusLedgerApi/V1/Data/Address.hs
- plutus-ledger-api/src/PlutusLedgerApi/V1/Data/Credential.hs
- plutus-ledger-api/src/PlutusLedgerApi/V1/Data/DCert.hs
- plutus-ledger-api/src/PlutusLedgerApi/V1/Data/Time.hs
- plutus-ledger-api/src/PlutusLedgerApi/V1/Data/Value.hs
- plutus-ledger-api/src/PlutusLedgerApi/V1/Scripts.hs
- plutus-ledger-api/src/PlutusLedgerApi/V1/Time.hs
- plutus-ledger-api/src/PlutusLedgerApi/V1/Tx.hs
- plutus-ledger-api/src/PlutusLedgerApi/V1/Value.hs
- plutus-ledger-api/src/PlutusLedgerApi/V3/MintValue.hs
- plutus-tx/changelog.d/20250130_1148_erikd_typeable.md
- plutus-tx/src/PlutusTx/Blueprint/Schema/Annotation.hs
> Support ghc 9.12

- doc/papers/system-f-in-agda/paper.lagda
- doc/plutus-core-spec/flat-serialisation.tex
remove redundant words in comment
- Branch
- PR
> chore: remove redundant words in comment

- plutus-core/plutus-ir/src/PlutusIR/Transform/Inline/Inline.hs
- plutus-tx-plugin/changelog.d/20250228_083744_unsafeFixIO_inline_pragma_local.md
- plutus-tx-plugin/src/PlutusTx/Compiler/Binders.hs
- plutus-tx-plugin/src/PlutusTx/Compiler/Expr.hs
- plutus-tx-plugin/test/AsData/Budget/9.6/always-inline-local.pir.golden
- plutus-tx-plugin/test/AsData/Budget/9.6/always-inline-local.uplc.golden
- plutus-tx-plugin/test/Inline/Spec.hs
In https://github.com/IntersectMBO/plutus/pull/5183, the Plinth inliner was made to inline bindings with `INLINE` pragmas. However it only works for top-level bindings, not local bindings (at least not strict local bindings, which are compiled to `case` binders). This PR fixes it.
It basically comes down to setting and propagating the correct `binderAnn` in `compileCase`.
Also fixed a bug in the PIR inliner (PlutusIR.Transform.Inline.Inline): it was using the wrong `ann` for inline hints.
> Propagate INLINE pragmas for local bindings

- scripts/interactive-release.sh
We are not going to publish these.
> Remove cardano-constitution and plutus-executables from CHaP release

- plutus-ledger-api/plutus-ledger-api.cabal
- plutus-tx-plugin/src/PlutusTx/Compiler/Expr.hs
- plutus-tx-plugin/src/PlutusTx/Compiler/Kind.hs
- plutus-tx-plugin/src/PlutusTx/Compiler/Type.hs
- plutus-tx-plugin/src/PlutusTx/Plugin.hs
[CONTRIBUTING.adoc](https://github.com/IntersectMBO/plutus/blob/master/CONTRIBUTING.adoc#plugin-support) says
> We currently support the plugin on: - 9.6
This PR removes support for GHC versions < 9.6.
> Remove plugin support for GHC < 9.6

- doc/plutus-core-spec/flat-serialisation.tex
Fixes typo on the spec, current spec doesn't wrap `b` with `\Builtin{}` from term flat decoder
> Fix typo on term flat decoder for builtin term

- plutus-core/cost-model/CostModelGeneration.md
The instructions in `CostModelGeneration.md` were a bit otudated so this updates them.  I also had some problems because some incomplete costing code was checked in and that caused the cost model generation process to fail with mysterious errors that I only tracked down after spending some time bisecting the git history.  I've added a prominent warning not to do that!
> Update costing instructions

- plutus-ledger-api/CostModel/Data/Params/CostModelParams/costModelParamNames.txt.golden
- plutus-ledger-api/src/PlutusLedgerApi/Common/Versions.hs
- plutus-ledger-api/src/PlutusLedgerApi/V1/ParamName.hs
- plutus-ledger-api/src/PlutusLedgerApi/V2/ParamName.hs
- plutus-ledger-api/src/PlutusLedgerApi/V3/ParamName.hs
- plutus-ledger-api/test/Spec/CostModelParams.hs
- plutus-ledger-api/test/Spec/Data/CostModelParams.hs
- plutus-ledger-api/testlib/PlutusLedgerApi/Test/V3/Data/EvaluationContext.hs
- plutus-ledger-api/testlib/PlutusLedgerApi/Test/V3/EvaluationContext.hs
As per the specification:
> Currently, once we add a feature for any given protocol version/ledger language, we also make it
available for all subsequent protocol versions/ledger languages. For example, Batch 2 of builtins was
introduced in PlutusV2 at protocol version 7.0, so it is also available in PlutusV2 at protocol versions
after 7.0, and PlutusV3 at protocol versions after 9.0 (when PlutusV3 itself was first introduced).
> Remove parameter names for array-related builtin functions

- plutus-ledger-api/src/PlutusLedgerApi/Data/V2.hs
- plutus-tx/changelog.d/20250320_234602_ana.pantilie95_remove_toDataList.md
- plutus-tx/src/PlutusTx/Data/AssocMap.hs
It does not compile because of https://github.com/IntersectMBO/plutus/issues/6085. I have recorded this in https://github.com/IntersectMBO/plutus/issues/6904 so that we do not forget to bring it back once the bug is fixed.
> Remove Data.AssocMap.toDataList

- doc/docusaurus/docs/auction-smart-contract/end-to-end/generating-keys.md
off-chain project fails to build as it is missing a dependency.
Follow the instruction in **[Generating Keys and Addresses](https://plutus.cardano.intersectmbo.org/docs/auction-smart-contract/end-to-end/generating-keys)**
This will give an error that you're missing the `@harmoniclabs/pair` dependency
Follow the same instruction from the patch branch
> Doc-fix, Add required dependency for the off-chain example code 

- doc/docusaurus/package.json
- doc/docusaurus/yarn.lock
Fixes https://github.com/IntersectMBO/plutus/security/dependabot/45
> Bump estree-util-value-to-estree to 3.3.3 for docusaurus site

- plutus-core/untyped-plutus-core/src/UntypedPlutusCore/Transform/Inline.hs
Before I make changes in the `UntypedPlutusCore.Transform.Inline` module I decided to groom its code:
- Apply fourmolu.
- Wrap long lines (> 80 chars, mainly comments, some type sigs)
- Replace wildcard imports with explicit ones.
> Code Formatting: UPLC's Inline module.

- plutus-executables/src/AgdaUnparse.hs
- plutus-executables/test/certifier/Golden/AA2-CSE.golden
- plutus-executables/test/certifier/Spec.hs
- plutus-metatheory/changelog.d/20250411_131306_ana.pantilie95_fix_certifier_builtin_deceq.rst
- plutus-metatheory/src/Utils.lagda.md
- plutus-metatheory/src/VerifiedCompilation/Equality.lagda.md
Fixes https://github.com/IntersectMBO/plutus-private/issues/1505
> Fix bug in builtin decidable equality

- plutus-conformance/agda/Spec.hs
- plutus-conformance/haskell-steppable/Spec.hs
- plutus-conformance/haskell/Spec.hs
- plutus-conformance/src/PlutusConformance/Common.hs
> refactor: apply fourmolu to plutus-conformance

- doc/docusaurus/static/code/mint-token-for-auction.mjs
Fix missing await in <b>Minting the Token to be Auctioned</b> example doc.
`wallet.signTx` return a Promise, getting `{"code":"ERR_INVALID_ARG_TYPE"}` when calling `wallet.submitTx`
> doc: fix missing await on wallet.signTx

- plutus-core/plutus-core/src/PlutusCore/Crypto/ExpMod.hs
- plutus-core/untyped-plutus-core/test/Evaluation/Builtins/Golden/Integer/ExpMod/exp-neg-non-inverse1.err.golden
- plutus-core/untyped-plutus-core/test/Evaluation/Builtins/Golden/Integer/ExpMod/exp-neg-non-inverse2.err.golden
- plutus-core/untyped-plutus-core/test/Evaluation/Builtins/Golden/Integer/ExpMod/mod-zero.err.golden
This fixes #7061 (see that for details).  I'll add the property tests that discovered the problem in a later PR.
> Fix `expModInteger` bug

- plutus-tx-plugin/changelog.d/20250502_105910_Yuriy.Lazaryev_from_string_inscruitable.md
- plutus-tx-plugin/plutus-tx-plugin.cabal
- plutus-tx-plugin/src/PlutusTx/Compiler/Expr.hs
- plutus-tx-plugin/test/ByteStringLiterals/Lib.hs
- plutus-tx-plugin/test/ByteStringLiterals/Spec.hs
Closes https://github.com/IntersectMBO/plutus-private/issues/1496
> Fix: `Use of fromString @BuiltinByteStringHex with inscrutable content`

- plutus-core/plutus-core/src/PlutusCore.hs
- plutus-metatheory/changelog.d/20250507_213709_ana.pantilie95_fix_some_agda_unparsing.rst
- plutus-metatheory/src/FFI/AgdaUnparse.hs
I've been manually testing the plugin with certification turned on. These changes fix some minor bugs in the generated certificates.
> Fix some Agda unparsing

- doc/docusaurus/docusaurus-examples.cabal
AuctionMintingPolicy was not included in the cabal file therefore wasn't being built when running `cabal build docusaurus-examples`
> Add missing example to docusaurus cabal file

- plutus-executables/executables/uplc/Main.hs
- plutus-executables/plutus-executables.cabal
- plutus-executables/test/certifier/Test/Certifier/Executable.hs
- plutus-metatheory/changelog.d/20250512_141822_ana.pantilie95_split_certificates_2.rst
- plutus-metatheory/plutus-metatheory.cabal
- plutus-metatheory/src/Certifier.hs
- plutus-metatheory/src/FFI/AgdaUnparse.hs
- plutus-metatheory/src/FFI/Untyped.hs
Fixes https://github.com/IntersectMBO/plutus-private/issues/1346
Fixes https://github.com/IntersectMBO/plutus-private/issues/1546
If you run:
```
cabal exec uplc -- example -s fibonacci | cabal exec uplc -- optimise --certify FibCert
```
you get the following output:
```
................
]
)
]
(con integer 5)
]
)
The compilation was successfully certified.
Agda certificate project written to FibCert-911718221
```
The certifier creates a new directory called `FibCert-911718221`, which is the name the user provides followed by system time in nanoseconds. I decided to append this because we have multiple `Plinth` files which contain multiple `compile` evaluations, each of which representing one program with its own certificate. Until we modify `compile` to allow the user to provide a name …
> Certifier produces certificate as Agda project; optimise certificate

- .github/workflows/code-coverage-report.yml
- .github/workflows/slack-message-broker.yml
- nix/outputs.nix
- nix/project.nix
- plutus-core/plutus-core.cabal
- plutus-core/testlib/Test/Tasty/Extras.hs
- plutus-core/untyped-plutus-core/testlib/Evaluation/Builtins/Definition.hs
- plutus-ledger-api/test/Spec/Data/Eval.hs
- plutus-ledger-api/test/Spec/Eval.hs
This PR enables the build of the project coverage report.
A report is built on each PR, but only published on push to master.
The report will be available [here](https://plutus.cardano.intersectmbo.org/dev/coverage) 
The report currently is only available for the `plutus-core` package, this is because enabling HPC (haskell program coverage) on other packages breaks several tests in their test-suites, see [this PR](https://github.com/IntersectMBO/plutus/pull/6979) for an effort to address this.
There is one test that also fails in plutus-core, when HPC is enabled:
```
TrackCosts: retaining:                                                             FAIL (0.43s)
untyped-plutus-core/testlib/Evaluation/Builtins/Definition.hs:526:
Too many elements picked up by GC
Expected at most: 5
But got: …
```
> Enable & Publish Project Coverage Reports For plutus-core

- plutus-tx/src/PlutusTx/Builtins/Internal.hs
> Add haddock in `PlutusTx.Builtins.Internal`

- plutus-core/changelog.d/20250520_160112_effectfully_make__OperationalEvaluationError_work_in_the_machines.md
- plutus-core/plutus-core/src/PlutusCore/Evaluation/ErrorWithCause.hs
- plutus-core/plutus-core/src/PlutusCore/Evaluation/Machine/Ck.hs
- plutus-core/plutus-ir/test/PlutusIR/Compiler/Recursion/errorBinding.golden
- plutus-core/untyped-plutus-core/src/UntypedPlutusCore/Evaluation/Machine/Cek/ExBudgetMode.hs
- plutus-core/untyped-plutus-core/src/UntypedPlutusCore/Evaluation/Machine/Cek/Internal.hs
- plutus-core/untyped-plutus-core/src/UntypedPlutusCore/Evaluation/Machine/SteppableCek/Internal.hs
- plutus-core/untyped-plutus-core/test/Evaluation/Debug/ex3.golden
- plutus-core/untyped-plutus-core/test/Evaluation/Debug/ex4.golden
- plutus-core/untyped-plutus-core/test/Evaluation/Golden/polyErrorInst.plc.golden
- plutus-core/untyped-plutus-core/test/Evaluation/Golden/polyErrorInst.uplc.golden
- plutus-tx-plugin/test/Strictness/9.6/lambda-default.eval.golden
- plutus-tx-plugin/test/Strictness/9.6/lambda-nonstrict.eval.golden
- plutus-tx-plugin/test/Strictness/9.6/lambda-strict.eval.golden
This replaces
```haskell
instance AsEvaluationFailure err => AsEvaluationFailure (ErrorWithCause err cause) 
```
with
```haskell
instance AsEvaluationError err structural operational =>
AsEvaluationError (ErrorWithCause err cause) structural operational where
```
making error throwing more uniform in the machines (plus it adds functionality that I need in #7029).
Also makes `throwingWithCause` accept a `term` rather than a `Maybe term`, as the name indicates there really should be a cause.
Also replaces 
```haskell
throwing_ _EvaluationFailure
```
with
```haskell
throwingWithCause _OperationalEvaluationError CekEvaluationFailure $ Error ()
```
in the machines, so that the logs clearly indicate that it was `error` that caused an evaluation failure -- not a builtin.
> [Errors] Make '_OperationalEvaluationError' work in the machines

- doc/notes/plutus-core/cek-budgeting-profiling/CostingDetails.md
- plutus-core/changelog.d/20250521_140320_effectfully_cut_Evaluation_from_Structural_and_Operational.md
- plutus-core/plutus-core/src/PlutusCore/Builtin/KnownType.hs
- plutus-core/plutus-core/src/PlutusCore/Builtin/Result.hs
- plutus-core/plutus-core/src/PlutusCore/Evaluation/Error.hs
- plutus-core/plutus-core/src/PlutusCore/Evaluation/Machine/Ck.hs
- plutus-core/plutus-core/src/PlutusCore/Evaluation/Machine/Exception.hs
- plutus-core/testlib/PlutusCore/Generators/NEAT/Spec.hs
- plutus-core/untyped-plutus-core/src/UntypedPlutusCore/Evaluation/Machine/Cek/ExBudgetMode.hs
- plutus-core/untyped-plutus-core/src/UntypedPlutusCore/Evaluation/Machine/Cek/Internal.hs
- plutus-core/untyped-plutus-core/src/UntypedPlutusCore/Evaluation/Machine/SteppableCek/Internal.hs
- plutus-core/untyped-plutus-core/testlib/Evaluation/Builtins/Definition.hs
Makes names shorter and replaces `_MachineError` with `_StructuralError` for consistency with `_OperationalError`.
> [Refactoring] Cut 'Evaluation' from 'Structural' and 'Operational'

- plutus-tx-plugin/changelog.d/20250523_172915_seungheon.ooh_7065_2.md
- plutus-tx-plugin/src/PlutusTx/Compiler/Expr.hs
- plutus-tx-plugin/src/PlutusTx/Plugin.hs
- plutus-tx-plugin/test/Plugin/Basic/9.6/integerCase.pir.golden
- plutus-tx-plugin/test/Plugin/Basic/9.6/integerPatternMatch.pir.golden
- plutus-tx-plugin/test/Plugin/Basic/Spec.hs
- plutus-tx-plugin/test/Plugin/Errors/9.6/literalCaseInt.uplc.golden
- plutus-tx-plugin/test/Plugin/Errors/Spec.hs
- plutus-tx-plugin/test/TH/Spec.hs
Add support for base integer equality, thus integer pattern matching. This is accomplished by injecting `(PlutusTx.==) @Integer` into the code given to `compile` and converting all `GHC.Num.Integer.integerEq` into `PlutusTx.Builtins.equalsInteger` on the plugin side. This does bloat the PIR a little bit because it will include binding for `equalsInteger` even when it's not used, but this won't effect uplc at the end as we expect unused bindings from PIR to be correctly erased trivially. 
This feels like a rather sloppy method. In fact, I had other approach in mind, which is to precompile `(PlutusTx.==) @Integer` and load precompiled PIR from the plugin side, but I wasn't able to figure out a way to get this working with `Bool` being defined twice both from imported snippet and the code …
> Add support for base integer `==`  (#7065)

- plutus-tx-plugin/test/BuiltinList/Budget/9.6/index-out-of-bounds.pir.golden
- plutus-tx-plugin/test/BuiltinList/Budget/9.6/index-out-of-bounds.uplc.golden
- plutus-tx-plugin/test/BuiltinList/Budget/9.6/index.eval.golden
- plutus-tx-plugin/test/BuiltinList/Budget/9.6/index.pir.golden
- plutus-tx-plugin/test/BuiltinList/Budget/9.6/index.uplc.golden
- plutus-tx/changelog.d/20250526_182207_Yuriy.Lazaryev_lookup_builtin_list_cheaper.md
- plutus-tx/src/PlutusTx/BuiltinList.hs
`BuiltinList` lookup made many times cheaper by using the new `dropList` builtin instead of recursion.
Note: this PR is built on top of another PR as suggested by @zliu41 in order to separate concerns and make code review easier.
Closes: https://github.com/IntersectMBO/plutus-private/issues/1589
> BuiltinList lookup uses `dropList` builtin to improve performance.

- doc/plutus-core-spec/cardano/builtins6.tex
- doc/plutus-core-spec/flat-serialisation.tex
- doc/plutus-core-spec/plutus-core-specification.tex
- plutus-core/changelog.d/20250530_195904_kenneth.mackenzie_deprecate_caseList_caseData.md
- plutus-core/plutus-core/src/PlutusCore/Default/Builtins.hs
Fixes https://github.com/IntersectMBO/plutus-private/issues/1613.
It seems that we may decide not to release the `caseList` and `caseData` builtins.  This PR moves them to the very end of the flat encoding (tags 126 and 127) and adjusts the tags for `dropList` and the array builtins (which we're definitely going to release) to fill the gap.  The point of this is to make the changes as early as possible to stabilise the encoding before anything gets released and to make it easier to remove `caseList` and `caseData` if we decide to do  so (which will involve further changes to the implementation and specification).
> Move `caseList` and `caseData` to the end of the flat encoding

- plutus-core/cost-model/budgeting-bench/Benchmarks/Nops.hs
- plutus-core/docs/BuiltinsOverview.md
- plutus-core/plutus-core/examples/PlutusCore/Examples/Builtins.hs
- plutus-core/plutus-core/src/PlutusCore/Bitwise.hs
- plutus-core/plutus-core/src/PlutusCore/Builtin/HasConstant.hs
- plutus-core/plutus-core/src/PlutusCore/Builtin/KnownType.hs
- plutus-core/plutus-core/src/PlutusCore/Builtin/Result.hs
- plutus-core/plutus-core/src/PlutusCore/Crypto/Utils.hs
- plutus-core/plutus-core/src/PlutusCore/Default/Builtins.hs
- plutus-core/plutus-core/src/PlutusCore/Default/Universe.hs
- plutus-core/plutus-core/src/PlutusCore/Evaluation/Error.hs
- plutus-core/plutus-core/src/PlutusCore/Evaluation/ErrorWithCause.hs
- plutus-core/plutus-core/src/PlutusCore/Evaluation/Machine/Ck.hs
- plutus-core/plutus-core/src/PlutusCore/Evaluation/Machine/Exception.hs
- plutus-core/plutus-core/src/PlutusCore/Evaluation/Result.hs
- plutus-core/plutus-core/test/TypeSynthesis/Spec.hs
- plutus-core/plutus-ir/src/PlutusIR/Core/Type.hs
- plutus-core/testlib/PlutusCore/Generators/Hedgehog/Interesting.hs
- plutus-core/untyped-plutus-core/src/UntypedPlutusCore/Core/Type.hs
- plutus-core/untyped-plutus-core/src/UntypedPlutusCore/Evaluation/Machine/Cek/ExBudgetMode.hs
- plutus-core/untyped-plutus-core/src/UntypedPlutusCore/Evaluation/Machine/Cek/Internal.hs
- plutus-core/untyped-plutus-core/src/UntypedPlutusCore/Evaluation/Machine/SteppableCek/Internal.hs
- plutus-ledger-api/test-plugin/Spec/Data/Value.hs
- plutus-ledger-api/test-plugin/Spec/Value.hs
- plutus-tx/src/PlutusTx/Lift.hs
Closes #6160 
Removes prismatic error handling from Ck/Cek machine implementations.
There is a very minor performance degradation, and I don't know where it's coming from. I'll see if I can dig into ghc core tomorrow
> [Refactoring] Remove prismatic error handling from Ck/Cek machines

- plutus-tx/src/PlutusTx/Builtins/Internal.hs
Adds more notes in Builtins.Internal:
1. notes about execution budget and script failure due to that
2. Invariants on `replicateByte` and `integerToByteString`
~~I will add notes on which function have dynamic costing and which doesn't later today~~
> Amend documentation in Builtins.Internal about budgeting and invariants on Bytestring builtins

- scripts/interactive-release.sh
The release script calls `git add .` which is a security risk. This PR changes what files are added
> Narrow down files added by the release script

- plutus-benchmark/linear-vesting/exe/Main.hs
- plutus-benchmark/linear-vesting/src/LinearVesting.hs
- plutus-benchmark/linear-vesting/src/LinearVesting/Test.hs
- plutus-benchmark/linear-vesting/src/LinearVesting/Validator.hs
- plutus-benchmark/plutus-benchmark.cabal
Closes https://github.com/IntersectMBO/plutus-private/issues/1617
```
Evaluation was SUCCESSFUL, result is:
()
Execution budget spent:
CPU 101,442,633
MEM 474,786
Evaluation traces:
1. Parsing ScriptContext...
2. Parsed ScriptContext
3. Parsed Redeemer
4. Full unlock requested
5. Validation completed
```
After switching to the `Data`-backed `ScriptContext`:
```
Execution budget spent:
CPU 39,768,848
MEM 155,049  
```
> Benchmark: Linear Vesting

- plutus-ledger-api/exe/dump-cost-model-parameters/Main.hs
- plutus-ledger-api/exe/dump-cost-model-parameters/Parsers.hs
- plutus-ledger-api/plutus-ledger-api.cabal
Fixes https://github.com/IntersectMBO/plutus-private/issues/1650.
The ledger and the procol parameters view the cost model parameters as a list of integers with no other information.  This makes them quite difficult to deal with (in particular to check that they're in the right order).  This PR adds a simple tool to dump the cost model parameters in the expected order, in various formats including the JSON format used by `cardano-cli`.  See the attached files for examples of the output.
[cost-model-parameters-untagged.txt](https://github.com/user-attachments/files/20984174/cost-model-parameters-untagged.txt)
[cost-model-parameters-tagged.txt](https://github.com/user-attachments/files/20984176/cost-model-parameters-tagged.txt)
[cost-model-parameters-json.txt](https://github.com/user-attachm …
> Tool to dump cost model parameters in order expected by ledger

- plutus-ledger-api/src/PlutusLedgerApi/V1/Value.hs
To note that order of entries in the result of `flattenValue` will be reversed order of entries in underlying data of original `Value`.
closes #7173
> Add a note for `flattenValue`

- cabal.project
- plutus-core/changelog.d/20250703_123351_erikd_drop_hex_text.md
- plutus-core/plutus-core.cabal
- plutus-core/plutus-core/test/CBOR/DataStability.hs
* Drop poorly maintained package `hex-text` in favor of `base16-bytestring` which is more widely used and better maintained.
- Branch
- PR
> Replace `hex-text` with `base16-bytestring` package

- plutus-core/cost-model/create-cost-model/BuiltinMemoryModels.hs
- plutus-core/cost-model/create-cost-model/CreateBuiltinCostModel.hs
- plutus-core/plutus-core/src/PlutusCore/Evaluation/Machine/BuiltinCostModel.hs
- plutus-core/plutus-core/src/PlutusCore/Evaluation/Machine/ExBudgetingDefaults.hs
This just removes some comments that were placeholders for `caseList` and `caseData` costing stuff that we're not going to need any more.
> Remove some placeholder comments

- cabal.project
- plutus-core/changelog.d/20250707_193702_pablo.lamela_disable_exec_for_wasm.md
This PR disables compilation of Plutus executable for `wasm32`, because it doesn't compile. This removes the requirement for dependencies of `plutus-core` that must compile to `wasm32` to add this flag for compilation to succeed.
- Branch
- PR
> Disable Plutus executable build for wasm

- plutus-core/plutus-core/src/PlutusCore/Builtin/KnownType.hs
- plutus-core/plutus-core/src/PlutusCore/Builtin/Runtime.hs
- plutus-core/plutus-core/src/PlutusCore/Default/Builtins.hs
- plutus-core/plutus-core/src/PlutusCore/Evaluation/Machine/Ck.hs
- plutus-core/plutus-core/stdlib/PlutusCore/StdLib/Data/List.hs
- plutus-core/plutus-core/test/Evaluation/Spec.hs
- plutus-core/plutus-ir/src/PlutusIR/Transform/EvaluateBuiltins.hs
- plutus-core/testlib/PlutusCore/Generators/Hedgehog/Test.hs
- plutus-core/testlib/PlutusCore/Generators/Hedgehog/TypeEvalCheck.hs
- plutus-core/testlib/PlutusCore/Generators/Hedgehog/TypedBuiltinGen.hs
- plutus-core/untyped-plutus-core/src/UntypedPlutusCore/Evaluation/Machine/Cek/Internal.hs
- plutus-core/untyped-plutus-core/src/UntypedPlutusCore/Evaluation/Machine/SteppableCek/Internal.hs
- plutus-core/untyped-plutus-core/testlib/Evaluation/Builtins/MakeRead.hs
- plutus-core/untyped-plutus-core/testlib/Evaluation/Machines.hs
This removes `HeadSpine` from `BuiltinRuntime` now that we don't need it for pattern matching builtins (because they're removed).
> [Builtins] Remove 'HeadSpine' from 'BuiltinRuntime'

- .github/workflows/haddock-site.yml
Each haddock build weighs ~500MB.
Every 2 weeks a new version of plutus is released, and with it, a new version of the haddock. 
This PR deletes the oldest haddock build before deploying a new one. 
We keep the last 10 builds.
> Autodelete latest haddock build on new deployments

- cabal.project
The `cabal.project.freeze` file generated by `cabal freeze` contains packages pinned to multiple versions eg:
```
any.foldl ==1.4.17 || ==1.4.18,
any.optparse-applicative ==0.18.1.0 || ==0.19.0.0,
```
The `/scripts/combined-haddock.sh` then reads the freeze file to extract version information and replace `/nix/store` paths with `https://` hrefs in the generated html files. But the new `||` syntax causes the [haddock build to fail](https://github.com/IntersectMBO/plutus/actions/runs/16352594468/job/46202949272) with:
```
sed: file dist-newstyle/sedscript.txt line 123: unknown option to `s'
```
This presence of offending packages in the `cabal.project.freeze` file is confirmed by `dist-newstyle/cache/plan.json`: 
```
{
"type": "pre-existing",
"id": …
```
> Allow 'turtle' package to use a new version of 'optparse-applicative'

- plutus-ledger-api/test/Spec/Versions.hs
When you have `assertBool <error message> <condition>` the error message should report what is expected, not what went wrong.  I got that the wrong way round in a couple of the `plutus-ledger-api` tests in #7223.
> Invert some error messages in plutus-ledger-api tests

- cardano-constitution/test/Cardano/Constitution/Validator/Data/GoldenTests.hs
- cardano-constitution/test/Cardano/Constitution/Validator/Data/TestsCommon.hs
- cardano-constitution/test/Cardano/Constitution/Validator/GoldenTests.hs
- cardano-constitution/test/Cardano/Constitution/Validator/TestsCommon.hs
- plutus-benchmark/common/PlutusBenchmark/Common.hs
- plutus-benchmark/lists/exe/Main.hs
- plutus-benchmark/nofib/exe/Main.hs
- plutus-core/changelog.d/20250813_155837_effectfully_add_CekResult.md
- plutus-core/executables/plutus/AnyProgram/Run.hs
- plutus-core/plutus-core/src/PlutusCore/Builtin/KnownType.hs
- plutus-core/plutus-core/src/PlutusCore/Evaluation/Result.hs
- plutus-core/testlib/PlutusCore/Test.hs
- plutus-core/untyped-plutus-core/src/UntypedPlutusCore/Evaluation/Machine/Cek.hs
- plutus-core/untyped-plutus-core/src/UntypedPlutusCore/Evaluation/Machine/Cek/Internal.hs
- plutus-core/untyped-plutus-core/src/UntypedPlutusCore/Evaluation/Machine/CommonAPI.hs
- plutus-core/untyped-plutus-core/src/UntypedPlutusCore/Evaluation/Machine/SteppableCek.hs
- plutus-core/untyped-plutus-core/src/UntypedPlutusCore/Evaluation/Machine/SteppableCek/Internal.hs
- plutus-core/untyped-plutus-core/testlib/Evaluation/Builtins/BLS12_381.hs
- plutus-core/untyped-plutus-core/testlib/Evaluation/Builtins/Common.hs
- plutus-core/untyped-plutus-core/testlib/Evaluation/FreeVars.hs
- plutus-executables/executables/uplc/Main.hs
- plutus-ledger-api/src/PlutusLedgerApi/Common/Eval.hs
- plutus-ledger-api/test-plugin/Spec/ScriptSize.hs
- plutus-tx-plugin/test/CallTrace/Lib.hs
- plutus-tx/src/PlutusTx/Eval.hs
- plutus-tx/testlib/PlutusTx/Test/Run/Uplc.hs
- plutus-tx/testlib/PlutusTx/Test/Util/Compiled.hs
This is something I've been meaning to do for a long time. It adds `CekResult` and `CekReport` so that we never run into very confusing issues with excessive laziness invalidating benchmarking results like it happened in #3876. Plus, 3-tuples are an anti-pattern anyway, so it's good to move from them.
I also fixed a bug in `dischargeCekValue` where it previously wouldn't discharge under `Constr` or `Case` due to a catch-all clause that we forgot to update when introducing SOPs. It doesn't matter on-chain (we only care there if something is a `()` or success in general, not whether `Constr` was discharges correctly), but since we use the CEK machine as a sorta normalizer in tests, we still want it to return the correct answer.
Catch-all clauses are cancer, this is not the first time …
> [Evaluation] Add 'CekResult' and improve 'dischargeCekValue'

- plutus-tx-plugin/changelog.d/20250831_170659_unsafeFixIO_var_srcspan.md
- plutus-tx-plugin/src/PlutusTx/Compiler/Expr.hs
The effect can be seen both in the full compilation trace (via `dump-compilation-trace`), or in the error message when the compilation fails.
Unfortunately most `Var`s don't have `SrcSpan`, but this is better than nothing.
> Add SrcSpans of Vars in the compilation trace

- cabal.project
- flake.lock
- nix/pkgs.nix
- plutus-core/plutus-core.cabal
- plutus-core/testlib/PlutusCore/Generators/QuickCheck/Builtin.hs
- plutus-core/untyped-plutus-core/testlib/Evaluation/Builtins/BLS12_381.hs
- plutus-core/untyped-plutus-core/testlib/Evaluation/Builtins/Costing.hs
Fixes https://github.com/IntersectMBO/plutus-private/issues/1780
> Remove dependency on QuickCheck 2.16 + remove allow-newer QuickCheck

- cabal.project
It's better to use `-Wall` and `-Wwarn` for development. When developing using ghci, it's very inconvenient if as soon as there's a warning, you can't proceed until it is fixed.
> Revert "Build with -Werror by default (#7298)"

- doc/plutus-core-spec/cardano/builtins1.tex
- doc/plutus-core-spec/cardano/builtins6.tex
- doc/plutus-core-spec/flat-serialisation.tex
- doc/plutus-core-spec/plutus-core-specification.tex
This updates the specification to reflect the change to array (de)serialisation in #7296.  I tidied up and clarified a few other things while I was at it. 
Edit: here's a copy of the rendered PDF:
[plutus-core-specification.pdf](https://github.com/user-attachments/files/22282536/plutus-core-specification.pdf)
> Spec: serialise arrays as lists; miscellaneous updates

- plutus-core/plutus-core/src/PlutusCore/Builtin/KnownType.hs
- plutus-core/plutus-core/src/PlutusCore/Builtin/KnownTypeAst.hs
- plutus-core/plutus-core/src/PlutusCore/Default/Universe.hs
- plutus-core/prelude/PlutusPrelude.hs
This removes all `readKnown` and `makeKnown` calls from the GHC Core of builtins (I did check).
> [Builtins] Implement 'ReadKnownIn' and 'MakeKnownIn' instances manually

- plutus-core/plutus-core/src/PlutusCore/Evaluation/Machine/ExMemoryUsage.hs
- plutus-core/plutus-core/src/PlutusCore/Value.hs
- plutus-core/plutus-core/test/Value/Spec.hs
@Unisay noted that currency symbols and token names are capped at 32 bytes, which means we don't need to take map key length into account when costing, hence reverting the PR for keeping track of the lengths.
> Revert "Keep track of currency/token lengths in builtin Value (#7349)"

- plutus-conformance/agda/Spec.hs
- plutus-core/plutus-core/src/PlutusCore/Default/Builtins.hs
Some of the Agda conformance tests for the array builtins were disabled until the metatheory for the array builtins was completed.   That was in fact done in #7127, so it's now safe to enable the tests. 
Closes https://github.com/IntersectMBO/plutus-private/issues/1863
> Enable the Agda conformance tests for the array builtins.

- plutus-ledger-api/changelog.d/20251002_130633_kenneth.mackenzie_enable_bls_msm.md
- plutus-ledger-api/src/PlutusLedgerApi/Common/Versions.hs
- plutus-ledger-api/testlib/PlutusLedgerApi/Test/V3/Data/EvaluationContext.hs
- plutus-ledger-api/testlib/PlutusLedgerApi/Test/V3/EvaluationContext.hs
Closes #7330.
Closes https://github.com/IntersectMBO/plutus-private/issues/1812
This enables the two BLS12-381 MSM buitins at PV11 by adding them to `batch6` of the builtins, which makes them visible to the `builtinsAvailableIn` check that gets performed during deserialisation.  The cost model parameter names were added in an earlier PR, so there's no need to do anything for them here.
> Enable BLS12-381 MSM builtins at PV11
