- plutus-pab/src/Plutus/PAB/ContractCLI.hs
- plutus-pab/src/Plutus/PAB/Core.hs
- plutus-pab/src/Plutus/PAB/Effects/Contract/ContractExe.hs
- plutus-pab/src/Plutus/PAB/Monitoring/PABLogMsg.hs
- plutus-pab/test/full/Plutus/PAB/Events/ContractSpec.hs
The contract CLI was returning a `PartiallyDecodedResponse` but the PAB was expecting a `ContractResponse`. 
- Branch
- PR
> Fix wrong json encoding in contract CLI

- plutus-core/plutus-core/src/PlutusCore/Constant/Typed.hs
- plutus-core/plutus-core/src/PlutusCore/Evaluation/Machine/Ck.hs
- plutus-core/plutus-core/src/PlutusCore/Evaluation/Machine/ExBudget.hs
- plutus-core/plutus-ir/src/PlutusIR/Core/Type.hs
- plutus-core/untyped-plutus-core/src/UntypedPlutusCore/Core/Type.hs
- plutus-core/untyped-plutus-core/src/UntypedPlutusCore/Evaluation/HOAS.hs
- plutus-core/untyped-plutus-core/src/UntypedPlutusCore/Evaluation/Machine/Cek/Internal.hs
Some simplification, no benchmarking yet.
> [Evaluation] Tweaked some budgeting-related stuff a bit

- nix/pkgs/haskell/materialized-unix/.plan.nix/plutus-core.nix
- plutus-core/plutus-core.cabal
> Removed mono-traversable dead dependency

- plutus-contract/src/Plutus/Contract/Effects/WatchAddress.hs
> Add fundsAtAddressLt, fundsAtAddressLeq and export fundsAtAddressCondition (fix #3130)

- plutus-contract/src/Wallet/Emulator/Folds.hs
> Return blockchain in newest -> oldest order instead of reversed (fix #3165).

- doc/marlowe/tutorials/marlowe-model.rst
> Fix typo in marlowe-model.rst

- plutus-pab/app/PSGenerator.hs
Export `pabBridge` and `pabTypes` to fix #3325.
---
- Branch
- PR
> Export pabBridge and pabTypes (fix #3325).

- plutus-contract/src/Plutus/Contract/Wallet.hs
This PR removes empty outputs mentioned in #3251
---
- Branch
- PR
> Filter out empty outputs (fix #3251)

- nix/pkgs/haskell/materialized-unix/.plan.nix/plutus-core.nix
- plutus-core/plutus-core.cabal
- plutus-core/plutus-core/src/PlutusCore/ParserCommon.hs
- plutus-core/plutus-core/test/Spec.hs
- plutus-core/plutus-ir/src/PlutusIR/Parser.hs
- plutus-core/untyped-plutus-core/src/NewUntypedPlutusCore.hs
- plutus-core/untyped-plutus-core/src/UntypedPlutusCore.hs
- plutus-core/untyped-plutus-core/src/UntypedPlutusCore/Core/Type.hs
- plutus-core/untyped-plutus-core/src/UntypedPlutusCore/Evaluation/HOAS.hs
- plutus-core/untyped-plutus-core/src/UntypedPlutusCore/Evaluation/Machine/Cek/Internal.hs
- plutus-core/untyped-plutus-core/src/UntypedPlutusCore/NewParser.hs
- plutus-core/untyped-plutus-core/src/UntypedPlutusCore/Subst.hs
- plutus-core/untyped-plutus-core/test/Evaluation/Builtins/MakeRead.hs
- replacement parser for UPLC, for now it'll coexist with the current parser.
- some changes are suggestions from linter
- tests to be written in this PR but feel free to let me know anything you spot now.
- [Update 8 June]: tests will be in another PR
- Branch
- PR
> SCP-2319 New UPLC parser

- nix/pkgs/haskell/materialized-unix/.plan.nix/plutus-core.nix
- plutus-core/plutus-core.cabal
- plutus-core/plutus-ir/src/PlutusIR/Compiler.hs
- plutus-core/plutus-ir/src/PlutusIR/Transform/Unwrap.hs
- plutus-core/plutus-ir/test/TransformSpec.hs
- plutus-core/plutus-ir/test/transform/unwrapCancel/unwrapWrap
- plutus-core/plutus-ir/test/transform/unwrapCancel/unwrapWrap.golden
- plutus-core/plutus-ir/test/transform/unwrapCancel/wrapUnwrap
- plutus-core/plutus-ir/test/transform/unwrapCancel/wrapUnwrap.golden
I noticed that this might come up in a test case. I think it'll be rare
(see the module doc), but it's so simple we might as well have it in
case.
- Branch
- PR
> Extremely simple wrap/unwrap cancellation pass for PIR

- playground-common/src/Schema.hs
- plutus-tx/src/PlutusTx/Prelude.hs
Add `ToSchema` instance for `Rational` to fix #3277.
---
- Branch
- PR
> Add ToSchema instance for Rational (fix #3277).

- marlowe-playground-server/app/Webserver.hs
- plutus-playground-server/app/Webserver.hs
My fault, I was being too quick. Maybe not the right thing but I'll let @gilligan worry about that later.
- Branch
- PR
> Quick fix for plutus-playground-server

- cabal.project
- nix/pkgs/haskell/haskell.nix
- nix/pkgs/haskell/materialized-unix/.plan.nix/iohk-monitoring.nix
- stack.yaml
Hey @raduom ; still builds with the updated revision; so it should be fine :)
- Branch
- PR
> revert back to the upgraded logging-version of iohk-monitoring

- plutus-contract/src/Wallet/Rollup/Render.hs
- plutus-ledger-api/src/Plutus/V1/Ledger/Tx.hs
- plutus-ledger/src/Ledger/Index.hs
- plutus-ledger/src/Ledger/Typed/Tx.hs
> Make TxInType optional to be able to convert from cardano-api tx's.

- nix/pkgs/default.nix
- nix/pkgs/haskell/cardano-repo-tool.sha
- nix/pkgs/haskell/extra.nix
- nix/sources.json
- shell.nix
The tool `cardano-repo-tool` is now available when entering a dev environment.
- Branch
- PR
> Integrated cardano-repo-tool in the nix-shell dev environment

- plutus-core/plutus-core/src/PlutusCore/Constant/Meaning.hs
- plutus-core/untyped-plutus-core/src/UntypedPlutusCore/Evaluation/Machine/Cek/Internal.hs
My latest investigations. Mostly negative results, but one is positive. I double- and triple-checked, but I encourage somebody to recheck themselves.
> [Evaluation] Made the 'VCon' constructor strict in the CEK machine

- marlowe-playground-client/src/SimulationPage/State.purs
- marlowe-playground-client/src/Simulator/State.purs
- marlowe-playground-client/test/Marlowe/ContractTests.purs
This PR makes some refactors around the Simulator so that it provides a nicer API and hides away some implementation details.
- Branch
- PR
> Marlowe Playground: Improve simulator encapsulation

- marlowe-website/src/index.njk
Russ wants to be able to link through to the latest version of Marlowe Run from the website in his internal user tests. So this changes the links - and adds some FIXMEs so we don't forget to change them back before we go live.
> Changing play/run links to staging.

- plutus-benchmark/bench-compare
So we can use it in a buildkite job.
FYI @kwxm . We should probably try and use it from the repository on the benchmarking machine so it doesn't get out of sync.
- Branch
- PR
> Commit the bench-compare script into the repo

- marlowe-dashboard-client/src/Contract/View.purs
> Centering contract step cards vertically.

- marlowe-dashboard-client/src/Contract/View.purs
> Adding explanatory text if a step has no possible actions.

- doc/plutus/howtos/getting-started.rst
- doc/reference/examples.rst
- doc/reference/index.rst
- plutus-use-cases/README.md
> A few doc tweaks

- doc/plutus/howtos/exporting-a-script.rst
- doc/plutus/tutorials/BasicValidators.hs
- plutus-ledger-api/src/Plutus/V1/Ledger/Api.hs
- plutus-ledger/src/Ledger/Scripts.hs
Support for exporting Datums and Redeemers to Cardano API envelopes
- Branch
- PR
> SCP-1880: Datums and Redeemers Cardano API envelopes

- marlowe-playground-client/src/Marlowe/Gen.purs
- marlowe-playground-client/src/Simulator/Lenses.purs
- marlowe-playground-client/src/Simulator/State.purs
- marlowe-playground-client/test/Marlowe/ContractTests.purs
what the title says 
- Branch
- PR
> SCP-2342: Add property based test to check that the provided examples dont have errors

- plutus-ledger-api/src/Plutus/V1/Ledger/Interval.hs
> Fix interval function doc

- marlowe-dashboard-client/src/Capability/Marlowe.purs
- marlowe-dashboard-client/src/Contract/State.purs
- marlowe-dashboard-client/src/ContractHome/View.purs
- marlowe-dashboard-client/src/MainFrame/State.purs
- marlowe-dashboard-client/src/Play/State.purs
- marlowe-dashboard-client/src/Play/Types.purs
- marlowe-dashboard-client/src/Template/View.purs
#3365 introduced a bug with the `LocalStorage` dataProvider. (It was intended to improve things for when we use the PAB as the dataProvider, and I failed to consider properly how the changes would affect the `LocalStorage` case.) This PR is mainly about fixing that bug, but while I was debugging I found that I could no longer understand some of what I'd done previously, so I refactored a bit and added some more comments - I hope it will be more intelligible now.
> Fix contract placeholders to work with LocalStorage.

- plutus-tx/src/PlutusTx/AssocMap.hs
Adds more standard functions to AssocMap: elems, filter, mapWithKeys, mapMaybe, mapMaybeWithKeys.
Exports unionWith.
> Add new functions to AssocMap

- stack.yaml
Make stack compile again.
- Branch
- PR
> Make stack compile again.

- nix/pkgs/haskell/materialized-darwin/.plan.nix/plutus-pab.nix
- nix/pkgs/haskell/materialized-linux/.plan.nix/plutus-pab.nix
- plutus-pab/plutus-pab.cabal
- plutus-pab/test-node/start-node-01.sh
- plutus-pab/test-node/start-node-02.sh
Make the node and cli binaries available using cabal.
- Branch
- PR
> Make the node binaries available using cabal

- playground-common/src/PSGenerator/Common.hs
- plutus-contract/src/Wallet/Emulator/MultiAgent.hs
- plutus-ledger-api/src/Plutus/V1/Ledger/Tx.hs
- plutus-ledger/src/Ledger/Constraints/OffChain.hs
- plutus-ledger/src/Ledger/Constraints/OnChain.hs
- plutus-ledger/src/Ledger/Constraints/TxConstraints.hs
- plutus-ledger/src/Ledger/Index.hs
- plutus-ledger/src/Ledger/Typed/Scripts/MonetaryPolicies.hs
- plutus-pab/src/Plutus/PAB/Arbitrary.hs
- plutus-use-cases/src/Plutus/Contracts/Prism/Credential.hs
- plutus-use-cases/src/Plutus/Contracts/Uniswap/OffChain.hs
- plutus-use-cases/test/Spec/future.pir
- plutus-use-cases/test/Spec/gameStateMachine.pir
- plutus-use-cases/test/Spec/governance.pir
- plutus-use-cases/test/Spec/multisigStateMachine.pir
- plutus-use-cases/test/Spec/renderGuess.txt
> Add redeemers for minting policies

- CONTRIBUTING.adoc
> Add some more instructions about profiling

- plutus-core/untyped-plutus-core/src/UntypedPlutusCore/Core/Type.hs
Seems to be noise but I guess it's worth having made an explicit decision :shrug: 
- Branch
- PR
> SCP-2436: reorder constructors according to frequency

- nix/sources.json
Fix upstream making shell.nix evaluation much faster, which is good.
- Branch
- PR
> Bump haskell.nix again

- .github/workflows/benchmark.yml
> Checkout repo in benchmark action

- scripts/trigger-buildkite-pipeline.sh
> Fix missing quotes

- marlowe-playground-client/src/SimulationPage/State.purs
Small PR to fix the decorations of the simulator when doing a reset. 
- Branch
- PR
> Fix invalid decorators when doing a simulation reset

- scripts/ci-plutus-benchmark.sh
Include git refs for base and PR branches in the comment added to PRs
as response to `/benchmark`
----------
- Branch
- PR
> ci-plutus-benchmark: add git ref info

- plutus-use-cases/scripts/Main.hs
- plutus-use-cases/test/Spec/Auction.hs
- plutus-use-cases/test/Spec/Future.hs
There was another PR solving this issue which was merged in master (#3446 ). However, it was pointed out that the `Future` contract would only partially work. Therefore, this PR addresses the issue.
- Branch
- PR
> SCP-2380: Fixing scripts in plutus-use-cases-scripts

- marlowe/src/Language/Marlowe/Client.hs
- marlowe/src/Language/Marlowe/Semantics.hs
- marlowe/test/Spec/Marlowe/Marlowe.hs
> SCP-2335 Simple Marlowe Plutus Error handling

- plutus-benchmark/bench-compare-markdown
- scripts/ci-plutus-benchmark.sh
Minor improvements to the benchmark comparison script, extracted from #3471.  This one doesn't touch the CI scripts.
- Branch
- PR
> Update bench comparison script

- nix/pkgs/haskell/materialized-darwin/.plan.nix/plutus-tx.nix
- nix/pkgs/haskell/materialized-linux/.plan.nix/plutus-tx.nix
- nix/pkgs/haskell/materialized-unix/.plan.nix/plutus-tx.nix
- plutus-benchmark/nofib/src/Plutus/Benchmark/Queens.hs
- plutus-ledger-api/src/Plutus/V1/Ledger/Interval.hs
- plutus-ledger-api/src/Plutus/V1/Ledger/Slot.hs
- plutus-ledger-api/src/Plutus/V1/Ledger/Time.hs
- plutus-ledger-api/test/Spec/Interval.hs
- plutus-tx/plutus-tx.cabal
- plutus-tx/src/PlutusTx/Enum.hs
- plutus-tx/src/PlutusTx/Eq.hs
- plutus-tx/src/PlutusTx/Prelude.hs
Introduce `Enum` typeclass for Plutus to fix the problem with open intervals (fix #3467).
---
- Branch
- PR
> Fix isEmpty for some open intervals (#3467).

- nix/pkgs/haskell/materialized-darwin/.plan.nix/plutus-pab.nix
- nix/pkgs/haskell/materialized-linux/.plan.nix/plutus-pab.nix
- plutus-pab/examples/wait-for-tx/Main.hs
- plutus-pab/plutus-pab.cabal
> SCP-2405: Example app that waits for a blockchain event

- marlowe/src/Language/Marlowe/Semantics.hs
- marlowe/test/Spec/Marlowe/AutoExecute.hs
- marlowe/test/Spec/Marlowe/Marlowe.hs
- playground-common/src/Playground/TH.hs
- playground-common/src/Schema.hs
- plutus-ledger-api/src/Plutus/V1/Ledger/Slot.hs
- plutus-playground-server/src/Playground/Interpreter.hs
- plutus-tx-plugin/test/Plugin/Errors/Spec.hs
- plutus-tx-plugin/test/TH/TestTH.hs
- plutus-tx/src/PlutusTx/Applicative.hs
- plutus-tx/src/PlutusTx/AssocMap.hs
- plutus-tx/src/PlutusTx/Bool.hs
- plutus-tx/src/PlutusTx/Either.hs
- plutus-tx/src/PlutusTx/Eq.hs
- plutus-tx/src/PlutusTx/Functor.hs
- plutus-tx/src/PlutusTx/IsData/Class.hs
- plutus-tx/src/PlutusTx/List.hs
- plutus-tx/src/PlutusTx/Maybe.hs
- plutus-tx/src/PlutusTx/Monoid.hs
- plutus-tx/src/PlutusTx/Ord.hs
- plutus-tx/src/PlutusTx/Prelude.hs
- plutus-tx/src/PlutusTx/Ratio.hs
- plutus-tx/src/PlutusTx/Semigroup.hs
- plutus-use-cases/bench/Opt.hs
- plutus-use-cases/bench/Scott.hs
- plutus-use-cases/src/Plutus/Contracts/Currency.hs
ANN will trigger TemplateHaskell, use {- HLINT ... -} instead.
See https://github.com/ndmitchell/hlint#ignoring-hints
> Don't use ANN for HLINT

- doc/plutus/explanations/plutus-foundation.rst
removed an "a" that was wrongly placed be4 a "the"
- Branch
- PR
> Grammar check

- plutus-pab/src/Cardano/Protocol/Socket/Client.hs
- plutus-pab/src/Cardano/Protocol/Socket/Server.hs
- plutus-pab/src/Cardano/Protocol/Socket/Type.hs
- plutus-pab/tx-inject/config.yaml
Added versioning information to the node client and mock server. This was required by the real node and it was the reason why the handshake failed.
- Branch
- PR
> Add protocol versioning to the node client.

- plutus-core/executables/Common.hs
- plutus-core/executables/Parsers.hs
- plutus-core/executables/plc/Main.hs
- plutus-core/executables/uplc/Main.hs
I found a few more CBOR things.
- Branch
- PR
> Remove CBOR.

- cabal.project
- nix/pkgs/haskell/haskell.nix
- nix/pkgs/haskell/materialized-darwin/.plan.nix/plutus-contract.nix
- nix/pkgs/haskell/materialized-linux/.plan.nix/plutus-contract.nix
- plutus-contract/plutus-contract.cabal
- plutus-contract/src/Plutus/Contract/CardanoAPI.hs
Depends on #3335 being merged first.
- Branch
- PR
> SCP-2317 Convert cardano-api Tx types from/to our Tx types.

- marlowe-dashboard-client/src/Bridge.purs
This PR is explained in the comment in the code.
> Fixing slot conversion to work with new PAB.

- marlowe-dashboard-client/src/API/Wallet.purs
- marlowe-dashboard-client/src/Bridge.purs
- marlowe-dashboard-client/src/Capability/Wallet.purs
- playground-common/src/PSGenerator/Common.hs
- plutus-contract/src/Plutus/Contract/Effects.hs
- plutus-contract/src/Plutus/Contract/Request.hs
- plutus-contract/src/Wallet/API.hs
- plutus-contract/src/Wallet/Effects.hs
- plutus-contract/src/Wallet/Types.hs
- plutus-pab-client/src/View/Pretty.purs
> SCP-2453: Remove SendNotification and Wallet.Types.Payment code.

- plutus-playground-client/default.nix
- plutus-playground-server/app/Main.hs
- plutus-playground-server/app/Webserver.hs
- plutus-playground-server/src/Playground/Interpreter.hs
- plutus-playground-server/src/Playground/Server.hs
Add plutus-playground-server maxInterpretation timeout cli option. (fix #3216, fix #3509)
---
- Branch
- PR
> Fix playground timeout (fix #3216, #3509).

- plutus-pab-client/config.nix
Fixes https://github.com/input-output-hk/plutus/issues/3551
CORS config is required since https://github.com/input-output-hk/plutus/pull/3507
- Branch
- PR
> Add missing pab cors config

- nix/pkgs/haskell/materialized-darwin/.plan.nix/plutus-pab.nix
- nix/pkgs/haskell/materialized-linux/.plan.nix/plutus-pab.nix
- plutus-pab/plutus-pab.cabal
- plutus-pab/src/Cardano/ChainIndex/Server.hs
- plutus-pab/src/Cardano/Node/Client.hs
- plutus-pab/src/Cardano/Node/Mock.hs
- plutus-pab/src/Cardano/Node/Server.hs
- plutus-pab/src/Cardano/Node/Types.hs
- plutus-pab/src/Cardano/Protocol/Socket/Client.hs
- plutus-pab/src/Cardano/Protocol/Socket/Mock/Client.hs
- plutus-pab/src/Cardano/Protocol/Socket/Mock/Server.hs
- plutus-pab/src/Cardano/Protocol/Socket/Type.hs
- plutus-pab/src/Cardano/Wallet/Mock.hs
- plutus-pab/src/Cardano/Wallet/Server.hs
- plutus-pab/src/Plutus/PAB/App.hs
- plutus-pab/src/Plutus/PAB/Core/ContractInstance/BlockchainEnv.hs
- plutus-pab/sync-client/Main.hs
- plutus-pab/test-node/configuration.yaml
- plutus-pab/test-node/start-testnet-node.sh
- plutus-pab/test-node/testnet/testnet-alonzo-genesis.json
- plutus-pab/test-node/testnet/testnet-byron-genesis.json
- plutus-pab/test-node/testnet/testnet-config.json
- plutus-pab/test-node/testnet/testnet-shelley-genesis.json
- plutus-pab/test-node/testnet/testnet-topology.json
- plutus-pab/tx-inject/Main.hs
I moved the current mocked server and client to a `Mock` package, and I removed the Server from the main package.
Switched to monomorphic types, but will think if it makes sense to parameterise more on the next refactoring rounds.
To test it, you need to start the testnet client and then connect to it using ```cabal exec sync-client -- <path-to-socket>```.
- Branch
- PR
> Create a client that can work with the cardano node.

- nix/modules/pab.nix
- nix/pkgs/haskell/materialized-darwin/.plan.nix/plutus-pab.nix
- nix/pkgs/haskell/materialized-linux/.plan.nix/plutus-pab.nix
- plutus-contract/src/Plutus/Contract/CardanoAPI.hs
- plutus-ledger-api/test/Spec/Time.hs
- plutus-pab-client/config.nix
- plutus-pab/plutus-pab.cabal
- plutus-pab/src/Cardano/Api/NetworkId/Extra.hs
- plutus-pab/src/Cardano/Node/Types.hs
- plutus-pab/test/light/Cardano/Api/NetworkId/ExtraSpec.hs
- plutus-pab/test/light/Spec.hs
Added NetworkId parameter to PAB and threaded to Plutus.Contract.CardanoAPI.
Need your thoughts on the ToJSON/FromJSON of NetworkId. They make sense?
- Branch
- PR
> SCP-2402: Added NetworkId parameter to PAB

- cabal.project
- nix/pkgs/haskell/haskell.nix
- nix/pkgs/haskell/materialized-darwin/.plan.nix/shelley-spec-ledger-test.nix
- nix/pkgs/haskell/materialized-linux/.plan.nix/shelley-spec-ledger-test.nix
This once more puts us to tracking `cardano-ledger-specs:master`, with our recent changes merged in.
- Branch
- PR
> Bump the ledger to master

- plutus-pab/src/Plutus/PAB/Effects/Contract.hs
> Fix type parameter name in PABContract haddock

- nix/pkgs/haskell/materialized-darwin/.plan.nix/plutus-pab.nix
- nix/pkgs/haskell/materialized-linux/.plan.nix/plutus-pab.nix
- plutus-pab/plutus-pab.cabal
- plutus-pab/src/Cardano/Protocol/Socket/Client.hs
- plutus-pab/src/Cardano/Protocol/Socket/Type.hs
- plutus-pab/sync-client/Main.hs
Switch from the ouroboros apis for controlling the node to the ones from `cardano-api` which is meant as a portable, generic way of abstracting over the different specificities of different blockchain versions.
- Branch
- PR
> Use cardano-api rather than the ouroboros one.

- README.adoc
> README: add note about cabal update

- plutus-ledger-api/src/Plutus/V1/Ledger/Contexts.hs
Example:
```
Purpose: Minting 0000
TxInfo:
TxId: 61666166
Inputs: []
Outputs: []
Fee: Value (Map [])
Value minted: Value (Map [])
DCerts: []
Wdrl: []
Valid range: (-∞ , +∞)
Signatories: []
Datums: []
```
- Branch
- PR
> Add some Show and Pretty instances

- plutus-ledger/src/Ledger/Index.hs
Fixes #3573 as suggested in the issue
- Branch
- PR
> Validate script inputs exist in phase 1

- plutus-use-cases/scripts/Main.hs
> SCP-2509: Encode partial tx as JSON

- nix/pkgs/haskell/materialized-darwin/.plan.nix/plutus-pab.nix
- nix/pkgs/haskell/materialized-linux/.plan.nix/plutus-pab.nix
- plutus-pab/plutus-pab.cabal
- plutus-pab/src/Cardano/Protocol/Socket/Client.hs
- plutus-pab/sync-client/Main.hs
Support resume for chain sync.
- Branch
- PR
> Add support for resuming chain sync.

- plutus-pab/src/Cardano/Protocol/Socket/Client.hs
- plutus-pab/sync-client/Main.hs
Support rollbacks.
- Branch
- PR
> Add rollback support.

- plutus-use-cases/scripts/Main.hs
Added a help menu for the command `transactions` in the `plutus-use-cases-scripts` executable.
- Branch
- PR
> Added a help menu for the command `transactions` in the plutus-use-cases-scripts exe

- notes/fomega/cek-cps-experiments/run-all
- plutus-core/README.md
- plutus-core/executables/Parsers.hs
- plutus-core/executables/plc/Main.hs
- plutus-core/executables/uplc/Main.hs
- plutus-core/plutus-ir/src/PlutusIR/Compiler/Types.hs
Fixed some typos and updated documentation.
- Branch
- PR
> SCP 2536 Update documentation for plutus core executables

- plutus-playground-client/README.md
This is an updated version of #3485. Fixes #3484.
---
- Branch
- PR
> Add note on webpack https config to getting started in Plutus Playground

- nix/pkgs/haskell/materialized-darwin/.plan.nix/plutus-tx.nix
- nix/pkgs/haskell/materialized-linux/.plan.nix/plutus-tx.nix
- plutus-contract/src/Plutus/Contract/StateMachine/OnChain.hs
- plutus-ledger-api/src/Plutus/V1/Ledger/Contexts.hs
- plutus-tx/plutus-tx.cabal
- plutus-tx/src/PlutusTx/Enum.hs
- plutus-tx/src/PlutusTx/IsData/Class.hs
- plutus-tx/src/PlutusTx/List.hs
- plutus-tx/src/PlutusTx/Ord.hs
- plutus-tx/src/PlutusTx/Prelude.hs
- plutus-tx/src/PlutusTx/Ratio.hs
- plutus-tx/src/PlutusTx/Semigroup.hs
- plutus-tx/src/PlutusTx/Trace.hs
- plutus-use-cases/src/Plutus/Contracts/Swap.hs
- plutus-use-cases/test/Spec/crowdfundingEmulatorTestOutput.txt
- plutus-use-cases/test/Spec/gameStateMachine.pir
- plutus-use-cases/test/Spec/governance.pir
- plutus-use-cases/test/Spec/multisigStateMachine.pir
- plutus-use-cases/test/Spec/renderCrowdfunding.txt
- plutus-use-cases/test/Spec/renderGuess.txt
- plutus-use-cases/test/Spec/renderVesting.txt
- plutus-use-cases/test/Spec/vesting.pir
This PR replaces `error ()` with `traceError` providing error messages for better debugging. (fix #3608).
---
- Branch
- PR
> Use traceError instead of error for better error messages (fix #3608).

- marlowe-dashboard-client/src/Contract/Types.purs
- marlowe-dashboard-client/src/Contract/View.purs
- marlowe-dashboard-client/src/Dashboard/State.purs
- marlowe-dashboard-client/src/Dashboard/Types.purs
- marlowe-dashboard-client/src/Dashboard/View.purs
- marlowe-dashboard-client/src/Humanize.purs
- marlowe-dashboard-client/src/MainFrame/Lenses.purs
- marlowe-dashboard-client/src/MainFrame/State.purs
- marlowe-dashboard-client/src/MainFrame/Types.purs
- marlowe-dashboard-client/src/MainFrame/View.purs
- marlowe-dashboard-client/src/Marlowe/Execution/State.purs
This PR solves two issues around time:
* It displays the times with the offset of the browser 
* It correctly uses the contract timeout (before it was using the current slot at the moment of calculation)
the PR is marked as a draft until [this PR](https://github.com/input-output-hk/plutus/pull/3607) gets merged, then I'll rebase this.
- Branch
- PR
> SCP-2162 - Marlowe Dashboard Client - Fix timezone and timeout

- marlowe-dashboard-client/src/Contract/State.purs
- marlowe-dashboard-client/src/Contract/Types.purs
- marlowe-dashboard-client/src/Contract/View.purs
- marlowe-dashboard-client/src/Dashboard/View.purs
- marlowe-dashboard-client/src/Marlowe/Execution/Lenses.purs
- marlowe-dashboard-client/src/Marlowe/Execution/State.purs
- marlowe-dashboard-client/src/Marlowe/Execution/Types.purs
- marlowe-dashboard-client/tailwind.config.js
- web-common/src/Material/Icons.purs
- web-common/static/icons.css
This PR implements the new design for the balances, including information on the balance start and end (if available).
- Branch
- PR
> SCP-2547 - Marlowe Run Client - Re-implemented Balance tab

- .github/PULL_REQUEST_TEMPLATE.md
Nobody ever uses this (including me), it's in the wrong place.
- Branch
- PR
> Delete pre-merge checklist

- cabal.project
- nix/pkgs/haskell/haskell.nix
- plutus-pab/README.md
- stack.yaml
Eventful was replaced with beam and no longer being used since #3294
- Branch
- PR
> Remove stray eventful references

- nix/modules/pab.nix
- plutus-pab/src/Cardano/Node/Types.hs
> PAB: Delete unused type

- scripts/ci-plutus-benchmark.sh
GitHub will turn short revisions into clickable links to the respective
commit.
- Branch
- PR
> ci-benchmark: use rev-parse --short

- plutus-pab/src/Plutus/PAB/Webserver/Server.hs
- Branch
- PR
`Middleware` turns out not to be a `Monoid`. It would be useful to be able to utilize multiple `Middleware`s e.g cors, logging, etc and therefore I modified `startServer'` to take a `[Middleware]` argument.
> Add support for multiple Middlewares in the PAB server

- plutus-pab/src/Plutus/PAB/Webserver/Server.hs
Use `Endo` for fusing the middlewares.
- Branch
- PR
> PAB: Fix applyMiddlewares

- cabal.project
Empirically this makes a fairly big difference (~50%) in compiling these packages.
- Branch
- PR
> Turn off optimization for cardano projects on our critical path

- deployment/terraform/locals.tf
Add pablo key to staging environment
> Add pablo to staging

- marlowe/src/Language/Marlowe/Client.hs
> SCP-2576 Repack CurrencyError to MarloweError

- flake.nix
Enables the bitte deployment to use master.
- Branch
- PR
> Expose plutus-enabled GHC from the flake.

- deployment/terraform/locals.tf
Part of SCP-2396
- Branch
- PR
> Give Shea access to deployments.

- deployment/terraform/locals.tf
> Syntax error fixup

- doc/plutus/troubleshooting.rst
> Document error codes

- .github/workflows/test.yml
- ci.nix
- release.nix
This will allow hydra eval to move much faster.
- Branch
- PR
> Only checkMaterialization in the instantiation test.

- deployment/README.md
> Fix automatic deployment docs

- deployment/envs.nix
- deployment/terraform/locals.tf
This PR updates the credentials to remove Tobias, and add Pablo to the environments that are public
> Remove tobias from envs and add pablo

- deployment/terraform/variables.tf
We deployed a new route53 zone...
- Branch
- PR
> Fix production deploy.

- plutus-pab/test/full/Plutus/PAB/CliSpec.hs
- plutus-pab/test/full/Spec.hs
- remove the final test that spins up two more PABs; this makes
everything too slow.
- add some comments
- Branch
- PR
> hotfix comment out a test that takes too long

- plutus-core/plutus-ir/src/PlutusIR/Transform/NonStrict.hs
> Fix a few small comments on NonStrict

- deployment/morph/machines/playground.nix
> Set the marlowe-playground frontend URL correctly in production.

- plutus-pab/src/Plutus/PAB/Core/ContractInstance.hs
- plutus-pab/src/Plutus/PAB/Core/ContractInstance/STM.hs
> Add time actions to PAB Simulator

- marlowe-dashboard-client/src/API/Contract.purs
- plutus-pab-client/src/MonadApp.purs
- plutus-pab/ARCHITECTURE.adoc
- plutus-pab/src/Cardano/ChainIndex/API.hs
- plutus-pab/src/Cardano/Metadata/API.hs
- plutus-pab/src/Cardano/Node/API.hs
- plutus-pab/src/Plutus/PAB/Run/PSGenerator.hs
- plutus-pab/src/Plutus/PAB/Webserver/API.hs
- plutus-pab/src/Plutus/PAB/Webserver/Handler.hs
- plutus-pab/src/Plutus/PAB/Webserver/Server.hs
- plutus-pab/test/full/Plutus/PAB/CliSpec.hs
Fixes SCP-2599
- Merge API and NewAPI
- Some minor cleanup
- Branch
- PR
> SCP-2599 - Merge API and NewAPI; now simply API.

- plutus-contract/plutus-contract.cabal
> Fix plutus-contract plugin errors when loading into a repl

- CONTRIBUTING.adoc
> Document plutus-staging workflow

- nix/pkgs/haskell/materialized-darwin/.plan.nix/plutus-ledger.nix
- nix/pkgs/haskell/materialized-linux/.plan.nix/plutus-ledger.nix
- playground-common/src/PSGenerator/Common.hs
- plutus-chain-index/src/Plutus/ChainIndex/Effects.hs
- plutus-chain-index/src/Plutus/ChainIndex/Emulator/DiskState.hs
- plutus-chain-index/src/Plutus/ChainIndex/Emulator/Handlers.hs
- plutus-chain-index/src/Plutus/ChainIndex/Tx.hs
- plutus-chain-index/test/Generators.hs
- plutus-ledger-api/src/Plutus/V1/Ledger/Api.hs
- plutus-ledger-api/src/Plutus/V1/Ledger/Scripts.hs
- plutus-ledger/plutus-ledger.cabal
- plutus-ledger/src/Ledger/Scripts.hs
- plutus-ledger/src/Ledger/Typed/Scripts.hs
- plutus-ledger/src/Ledger/Typed/Scripts/StakeValidators.hs
Stake validators, to be used for both withdrawals and certificates for stake addresses.
- Branch
- PR
> SCP-2428, SCP-2429: Stake validators

- plutus-core/plutus-core/src/PlutusCore/Data.hs
> Document and validate that constructor tags are non-negative

- flake.nix
> Export marlowe-run packages for bitte

- default.nix
- deployment/morph/machines/marlowe-dash.nix
- deployment/morph/mk-machine.nix
- flake.nix
- nix/modules/pab.nix
- nix/tests/default.nix
- nix/tests/vm-tests/all.nix
- nix/tests/vm-tests/pab.nix
- nix/tests/vm.nix
> Use marlowe-pab for marlowe-run

- plutus-core/generators/PlutusCore/Generators/NEAT/Term.hs
- plutus-core/plutus-core/src/PlutusCore/Default/Builtins.hs
- plutus-core/plutus-core/test/TypeSynthesis/Golden/Trace.plc.golden
- plutus-core/untyped-plutus-core/test/Evaluation/Builtins/MakeRead.hs
- plutus-tx-plugin/test/Plugin/Primitives/trace.plc.golden
- plutus-tx-plugin/test/Plugin/Primitives/traceComplex.plc.golden
- plutus-tx-plugin/test/StdLib/errorTrace.plc.golden
- plutus-tx-plugin/test/TH/traceRepeatedly.plc.golden
- plutus-tx/src/PlutusTx/Builtins.hs
- plutus-tx/src/PlutusTx/Builtins/Internal.hs
- plutus-use-cases/test/Spec/crowdfundingEmulatorTestOutput.txt
- plutus-use-cases/test/Spec/future.pir
- plutus-use-cases/test/Spec/gameStateMachine.pir
- plutus-use-cases/test/Spec/governance.pir
- plutus-use-cases/test/Spec/multisigStateMachine.pir
- plutus-use-cases/test/Spec/renderCrowdfunding.txt
- plutus-use-cases/test/Spec/renderGuess.txt
- plutus-use-cases/test/Spec/renderVesting.txt
- plutus-use-cases/test/Spec/vesting.pir
This simplifies the use of it and saves us a little bit of space and
time.
Easy to do, and every little helps.
- Branch
- PR
> SCP-1220: make trace polymorphic

- deployment/morph/machines/playground.nix
- flake.nix
- marlowe-playground-client/src/HaskellEditor/State.purs
- marlowe-playground-server/app/Main.hs
- marlowe-playground-server/app/Webserver.hs
- marlowe-playground-server/marlowe-playground-server.cabal
- marlowe-playground-server/src/API.hs
- marlowe-playground-server/src/Server.hs
- nix/modules/marlowe-playground.nix
- nix/pkgs/haskell/materialized-darwin/.plan.nix/marlowe-playground-server.nix
- nix/pkgs/haskell/materialized-darwin/.plan.nix/web-ghc.nix
- nix/pkgs/haskell/materialized-linux/.plan.nix/marlowe-playground-server.nix
- nix/pkgs/haskell/materialized-linux/.plan.nix/web-ghc.nix
- nix/pkgs/web-ghc/default.nix
- nix/tests/vm-tests/marlowe-playground.nix
- plutus-playground-server/src/Playground/Interpreter.hs
- web-ghc/src/Webghc/Client.hs
- web-ghc/web-ghc.cabal
> Use web-ghc for Marlowe.

- plutus-core/untyped-plutus-core/test/Evaluation/Builtins/Definition.hs
> Added missing regression tests for builtins

- marlowe-dashboard-client/plutus-pab.yaml
- nix/modules/pab.nix
- nix/pkgs/haskell/materialized-darwin/.plan.nix/plutus-pab.nix
- nix/pkgs/haskell/materialized-linux/.plan.nix/plutus-pab.nix
- plutus-pab-client/config.nix
- plutus-pab/plutus-pab.cabal
- plutus-pab/plutus-pab.yaml.sample
- plutus-pab/src/Cardano/Node/API.hs
- plutus-pab/src/Cardano/Node/Client.hs
- plutus-pab/src/Cardano/Node/Mock.hs
- plutus-pab/src/Cardano/Node/Server.hs
- plutus-pab/src/Cardano/Node/Types.hs
- plutus-pab/tx-inject/Main.hs
- plutus-pab/tx-inject/TxInject/RandomTx.hs
We don't need it in the mock node, it's enough to have it in `tx-inject`
- Branch
- PR
> Delete random tx effect from mock node

- plutus-tx/src/PlutusTx/Prelude.hs
We've been expanding HLint to support Plutus and found the lack of these functions. Hope this addition will be useful in general.
- Branch
- PR
> Add curry & uncurry to PlutusTx Prelude

- nix/pkgs/haskell/materialized-darwin/.plan.nix/plutus-chain-index.nix
- nix/pkgs/haskell/materialized-darwin/default.nix
- nix/pkgs/haskell/materialized-linux/.plan.nix/plutus-chain-index.nix
- nix/pkgs/haskell/materialized-linux/default.nix
- plutus-chain-index/app/CommandLine.hs
- plutus-chain-index/app/Config.hs
- plutus-chain-index/app/Logging.hs
- plutus-chain-index/app/Main.hs
- plutus-chain-index/plutus-chain-index.cabal
> Support command line arguments.

- .editorconfig
- shell.nix
Had this lying around, forgot to push it earlier. Not much too see here.
- Branch
- PR
> Editorconfig tweaks

- plutus-tx/src/PlutusTx/List.hs
- plutus-tx/test/Spec.hs
Fixes the implementation of `nubBy`.
---
- Branch
- PR
> Fix the implementation of `nubBy`.

- .github/PULL_REQUEST_TEMPLATE.md
This PR extends the usual PR's checklist with a new line reminding to add tests. Please take a look and share your opinion / propose a different line.
---
- Branch
- PR
> Add step about tests to the PR's checklist

- marlowe-website/src/index.js
- marlowe-website/src/index.njk
> marlowe-web: Have cross-links follow the environment.

- nix/pkgs/haskell/materialized-darwin/.plan.nix/plutus-core.nix
- nix/pkgs/haskell/materialized-linux/.plan.nix/plutus-core.nix
- plutus-core/executables/uplc/Main.hs
- plutus-core/plutus-core.cabal
> Add a simple command to uplc to dump the cost model params

- flake.nix
> Export plutus-docs for the bitte deployment.

- marlowe/marlowe.cabal
- marlowe/pab/Main.hs
- marlowe/test/Spec.hs
- marlowe/test/Spec/PAB/Workflow.hs
- nix/pkgs/haskell/materialized-darwin/.plan.nix/marlowe.nix
- nix/pkgs/haskell/materialized-linux/.plan.nix/marlowe.nix
- plutus-pab/src/Cardano/ChainIndex/Types.hs
- plutus-pab/src/Cardano/Node/Types.hs
- plutus-pab/src/Cardano/Wallet/Types.hs
- plutus-pab/src/Plutus/PAB/Monitoring/Config.hs
- plutus-pab/src/Plutus/PAB/Run.hs
- plutus-pab/src/Plutus/PAB/Run/Command.hs
- plutus-pab/src/Plutus/PAB/Types.hs
- plutus-pab/src/Plutus/PAB/Webserver/Client.hs
- plutus-pab/test/full/Plutus/PAB/CliSpec.hs
- plutus-pab/test/full/Spec.hs
This perhaps needs a little bit more work from me but is in a good enough state to review @j-mueller . The thing that took me the most time was thinking about the client for the websocket, and deciding where to place the code I wanted to share with CliSpec and this test.
TODO:
Fixes SCP-2595
- Branch
- PR
> SCP-2595 marlowe workflow tests

- nix/pkgs/haskell/materialized-darwin/.plan.nix/plutus-chain-index.nix
- nix/pkgs/haskell/materialized-linux/.plan.nix/plutus-chain-index.nix
- plutus-chain-index/app/CommandLine.hs
- plutus-chain-index/app/Config.hs
- plutus-chain-index/app/Main.hs
- plutus-chain-index/plutus-chain-index.cabal
- plutus-chain-index/src/Plutus/ChainIndex/Api.hs
- plutus-chain-index/src/Plutus/ChainIndex/Client.hs
- plutus-chain-index/src/Plutus/ChainIndex/Emulator/Handlers.hs
- plutus-chain-index/src/Plutus/ChainIndex/Server.hs
* Add HTTP API and server to chain index
* Lookups returning `Nothing` are converted to 404 errors (not found)
- Branch
- PR
> SCP-2635: Chain index HTTP API

- plutus-contract/src/Plutus/Contract/Test.hs
- plutus-use-cases/test/Spec/Governance.hs
> Make dataAtAddress take multiple datums (fix #3163).

- nix/devcontainer/devcontainer.nix
so we can see into infinity ... (render richer symbols when printing to the console.)
- Branch
- PR
> set LANG=C.UTF-8 on devcontainer ... 

- doc/README.md
- doc/_static/theme_overrides.css
- doc/conf.py
- doc/default.nix
- doc/reference/builtin-parameters.csv
- doc/reference/cost-model-parameters.rst
- doc/reference/index.rst
- doc/reference/machine-parameters.csv
Kenneth, there were a few where I didn't know what to say (marked `???`), help me out!
- Branch
- PR
> SCP-2692: add reference page on the cost model paramteters

- marlowe-dashboard-client/src/Contract/State.purs
- marlowe-dashboard-client/src/Contract/Types.purs
- marlowe-dashboard-client/src/Contract/View.purs
- marlowe-dashboard-client/src/Marlowe/Execution/Lenses.purs
- marlowe-dashboard-client/src/Marlowe/Execution/State.purs
- marlowe-dashboard-client/src/Marlowe/Execution/Types.purs
- marlowe-dashboard-client/tailwind.config.js
This PR implements the new design of the timeout step which includes the actions that were missed to do
- Branch
- PR
> SCP-2549 - Marlowe Run Client - Re-implemented timeout step card

- plutus-ledger-api/src/Plutus/V1/Ledger/Address.hs
- plutus-ledger-api/src/Plutus/V1/Ledger/Contexts.hs
- plutus-ledger-api/src/Plutus/V1/Ledger/Credential.hs
- plutus-ledger-api/src/Plutus/V1/Ledger/DCert.hs
- plutus-ledger-api/src/Plutus/V1/Ledger/Tx.hs
I'll backport this to `release/alonzo` after merging.
- Branch
- PR
> Add Eq instances for ScriptContext and components

- plutus-ledger-api/src/Plutus/V1/Ledger/DCert.hs
I tested this but evidently not well enough. I'll write a permanent test later today.
- Branch
- PR
> Fix accidental use of Haskell Eq

- plutus-contract/src/Plutus/Contract/StateMachine/ThreadToken.hs
> Add IsData ThreadToken (fix #3798).

- plutus-pab/src/Plutus/PAB/Core.hs
- plutus-pab/src/Plutus/PAB/Core/ContractInstance.hs
- plutus-pab/src/Plutus/PAB/Monitoring/PABLogMsg.hs
- plutus-pab/src/Plutus/PAB/Run/Cli.hs
Don't show full logs when restoring contracts, but display a summary message.
- Branch
- PR
> SCP-2608: Don't show full logs when restoring contracts, but display a summary message.

- plutus-pab-client/src/MainFrame.purs
- plutus-pab-client/src/MonadApp.purs
- plutus-pab-client/src/Types.purs
- plutus-pab-client/src/View.purs
- plutus-pab-client/src/View/Contracts.purs
- plutus-pab-client/src/View/Events.purs
- plutus-pab-client/src/View/Pretty.purs
- plutus-pab-client/test/MainFrameTests.purs
https://user-images.githubusercontent.com/817138/127330300-1dcb9270-54ab-49b0-ad7c-f271cdec6fca.mp4
- Branch
- PR
> pab client reinstate contract pane

- marlowe-dashboard-client/package-lock.json
- marlowe-dashboard-client/package.json
- marlowe-dashboard-client/src/Contract/View.purs
- marlowe-dashboard-client/static/css/main.css
- marlowe-dashboard-client/static/css/utilities.css
- marlowe-dashboard-client/tailwind.config.js
This PR implements the no possible actionst step card as shown in this gif 
- Branch
- PR
> SCP-2591 - Marlowe Run Client - implement no actions card

- plutus-pab/src/Plutus/PAB/Arbitrary.hs
> Add Arbitrary instance for ThreadToken (fix #3824).

- nix/pkgs/haskell/materialized-darwin/.plan.nix/plutus-contract.nix
- nix/pkgs/haskell/materialized-linux/.plan.nix/plutus-contract.nix
- nix/pkgs/haskell/materialized-windows/.plan.nix/plutus-contract.nix
- plutus-contract/plutus-contract.cabal
- plutus-contract/src/Plutus/Contract/Wallet.hs
- plutus-contract/src/Plutus/Trace.hs
- plutus-contract/src/Plutus/Trace/Emulator/Extract.hs
- plutus-ledger/src/Ledger/Index.hs
- plutus-use-cases/scripts/Main.hs
> SCP-2610: Move ExportTx to Plutus.Contract.Wallet

- plutus-ledger/src/Ledger/Oracle.hs
> Add Eq instance for SignedMessage (fix #3825).

- marlowe-dashboard-client/src/Capability/Marlowe.purs
- marlowe-dashboard-client/src/Marlowe/Client.purs
- web-common-marlowe/src/Marlowe/Semantics.purs
This doesn't (yet) fix the bug, but I'm pretty sure it's a necessary first step...
UPDATE: with the second commit it is now fixed. 🎉
> SCP-2717 - Fix decoding of wallet companion contract state.

- plutus-chain-index/src/Plutus/ChainIndex/Api.hs
- plutus-chain-index/src/Plutus/ChainIndex/Client.hs
- plutus-chain-index/src/Plutus/ChainIndex/Effects.hs
- plutus-chain-index/src/Plutus/ChainIndex/Emulator/DiskState.hs
- plutus-chain-index/src/Plutus/ChainIndex/Emulator/Handlers.hs
- plutus-chain-index/src/Plutus/ChainIndex/Server.hs
- plutus-contract/src/Plutus/Contract/Effects.hs
- plutus-contract/src/Plutus/Contract/Request.hs
- plutus-contract/src/Plutus/Contract/Trace/RequestHandler.hs
- plutus-pab/src/Plutus/PAB/Simulator.hs
Add a missing lookup to chain index
- Branch
- PR
> SCP-2713: Redeemer hash lookup in chain index

- plutus-ledger/src/Ledger/Blockchain.hs
> Fix BlockId Pretty instance

- cabal.project
- nix/pkgs/haskell/haskell.nix
> Point flat back to main repo now PR is merged

- marlowe/src/Language/Marlowe/Client.hs
- marlowe/test/Spec/Marlowe/Marlowe.hs
> Fix transfers between accounts

- nix/pkgs/haskell/materialized-darwin/.plan.nix/plutus-pab.nix
- nix/pkgs/haskell/materialized-darwin/default.nix
- nix/pkgs/haskell/materialized-linux/.plan.nix/plutus-pab.nix
- nix/pkgs/haskell/materialized-linux/default.nix
- nix/pkgs/haskell/materialized-windows/.plan.nix/plutus-pab.nix
- nix/pkgs/haskell/materialized-windows/default.nix
- plutus-pab/plutus-pab.cabal
- plutus-pab/src/Plutus/PAB/Webserver/Server.hs
> Add CORS middleware for preflight OPTIONS browser requests and allow content-type header

- doc/plutus/howtos/writing-a-scalable-app.rst
> minor edit

- playground-common/src/Schema.hs
> Add TxOutRef and ThreadToken Schema instances (fix #3867).

- cabal.project
- nix/pkgs/haskell/haskell.nix
- nix/pkgs/haskell/materialized-darwin/.plan.nix/iohk-monitoring.nix
- nix/pkgs/haskell/materialized-linux/.plan.nix/iohk-monitoring.nix
- nix/pkgs/haskell/materialized-windows/.plan.nix/iohk-monitoring.nix
- stack.yaml
> bring back latest develop commit; note about changing.

- marlowe-dashboard-client/plutus-pab.yaml
- marlowe-dashboard-client/src/Capability/Marlowe.purs
- marlowe-dashboard-client/src/Marlowe/PAB.purs
This PR fixes a serialization issue and a configuration issue around redeem and fees. 
- Branch
- PR
> Marlowe Run - fix redeem

- plutus-contract/src/Plutus/Contract/Types.hs
- plutus-contract/test/Spec/Contract.hs
- plutus-use-cases/src/Plutus/Contracts/Auction.hs
- plutus-use-cases/test/Spec/Auction.hs
Remove unnecessary loop in Auction contract. Also, added comments explaining how `select` and `selectList` work.
- Branch
- PR
> SCP-2728: Remove unecessary loop in Auction contract.

- doc/plutus/explanations/index.rst
- doc/plutus/explanations/order-book-pattern.rst
- doc/plutus/howtos/writing-a-scalable-app.rst
- doc/reference/glossary.rst
> docs: Explain order book pattern

- plutus-chain-index/app/CommandLine.hs
- plutus-chain-index/app/Config.hs
- plutus-chain-index/app/Main.hs
Add options for overriding / setting some config values on the CLI. That way you don't always need a custom config file.
- Branch
- PR
> chain-index: CLI overrides for some config values

- plutus-chain-index/src/Plutus/ChainIndex/Api.hs
- plutus-chain-index/src/Plutus/ChainIndex/Client.hs
- plutus-chain-index/src/Plutus/ChainIndex/Server.hs
Add an HTTP route to trigger garbage collection on the disk state (which is currently kept in memory)
- Branch
- PR
> chain-index: Add collect-garbage endpoint

- doc/plutus-doc.cabal
- doc/plutus/howtos/WriteScriptsTo.hs
- doc/plutus/howtos/analysing-scripts.rst
- doc/plutus/howtos/index.rst
- doc/reference/glossary.rst
- nix/pkgs/haskell/materialized-darwin/.plan.nix/plutus-doc.nix
- nix/pkgs/haskell/materialized-linux/.plan.nix/plutus-doc.nix
- nix/pkgs/haskell/materialized-windows/.plan.nix/plutus-doc.nix
- plutus-contract/src/Plutus/Trace/Emulator/Extract.hs
> docs: How to analyse the cost and size of Plutus scripts

- marlowe-dashboard-client/src/InputField/View.purs
- marlowe-dashboard-client/src/Template/State.purs
- marlowe-dashboard-client/src/Template/Types.purs
- nix/pkgs/purty-pre-commit/default.nix
> [SCP-2556] Fix focus on contract templates

- plutus-chain-index/src/Plutus/ChainIndex/Api.hs
- plutus-chain-index/src/Plutus/ChainIndex/Client.hs
- plutus-chain-index/src/Plutus/ChainIndex/Compatibility.hs
- plutus-chain-index/src/Plutus/ChainIndex/Effects.hs
- plutus-chain-index/src/Plutus/ChainIndex/Emulator/DiskState.hs
- plutus-chain-index/src/Plutus/ChainIndex/Emulator/Handlers.hs
- plutus-chain-index/src/Plutus/ChainIndex/Server.hs
- plutus-chain-index/src/Plutus/ChainIndex/Tx.hs
- plutus-chain-index/src/Plutus/ChainIndex/Types.hs
- plutus-chain-index/src/Plutus/Contract/CardanoAPI.hs
- plutus-contract/src/Wallet/Rollup/Render.hs
- plutus-ledger-api/src/Plutus/V1/Ledger/Tx.hs
* Fix conversion from cardano addresses / script types
* Add diagnostics endpoint
* Convert directly to chain index tx
- Branch
- PR
> Chain index: Some fixes

- plutus-ledger-api/src/Plutus/V1/Ledger/TxId.hs
> Derive TxId's IsString instance via LedgerBytes (fix #3888).

- nix/pkgs/haskell/materialized-darwin/.plan.nix/plutus-playground-server.nix
- nix/pkgs/haskell/materialized-linux/.plan.nix/plutus-playground-server.nix
- nix/pkgs/haskell/materialized-windows/.plan.nix/plutus-playground-server.nix
- plutus-ledger/src/Ledger/Scripts.hs
- plutus-playground-server/plutus-playground-server.cabal
- plutus-use-cases/test/Spec/crowdfundingEmulatorTestOutput.txt
- plutus-use-cases/test/Spec/renderCrowdfunding.txt
- plutus-use-cases/test/Spec/renderGuess.txt
- plutus-use-cases/test/Spec/renderVesting.txt
Change our script hash functions to use `cardano-api`.
- Branch
- PR
> plutus-ledger: Fix scriptHash function

- nix/pkgs/default.nix
- shell.nix
Adds a dumb `haskell-language-server-wrapper` for easier editor integration.
Not sure how this will behave on Windows though...
- Branch
- PR
> SCP-2741:  Add haskell-language-server-wrapper

- plutus-ledger/src/Ledger/Generators.hs
- plutus-ledger/src/Ledger/Index.hs
This is quite minimal, as I feel it works better to write generators by need, together with the actual tests.
- Branch
- PR
> SCP-2647: Add a ScriptContext generator

- marlowe-dashboard-client/src/Dashboard/View.purs
Very simple visual update here - refactoring to follow in separate PR
- Branch
- PR
> [SCP-2703] Implement redesign of wallet card

- marlowe-dashboard-client/src/Contract/View.purs
- marlowe-dashboard-client/tailwind.config.js
@jhbertra is working on implementing the new design for the confirmation card properly. This is intended as a quick fix to make it look a bit more like the new design (but not implement that design fully), in time for the video recording this afternoon.
> Make confirmation card closer to new design

- plutus-pab/src/Plutus/PAB/Core/ContractInstance.hs
- plutus-pab/src/Plutus/PAB/Core/ContractInstance/STM.hs
> SCP-2668: Delete unused fields

- plutus-tx/src/PlutusTx/Prelude.hs
> [PlutusTx.Prelude]: fix even (#3930).

- plutus-tx/src/PlutusTx/Ratio.hs
- plutus-tx/test/Spec.hs
> [PlutuxTx.Ratio]: Use reduce in recip (fix #3897).

- marlowe-dashboard-client/src/InputField/View.purs
- Fixes https://input-output.atlassian.net/browse/SCP-2791
- Branch
- PR
> [SCP-2891] Fix pristine flag behaviour on inputs

- marlowe-dashboard-client/src/Contract/View.purs
- marlowe-dashboard-client/src/Marlowe/PAB.purs
- marlowe-dashboard-client/src/Welcome/View.purs
- marlowe-website/src/index.njk
Each fix is in its own commit. Basically:
* Fix a typo in the main screen of marlowe run 
* Fix the contract name to be consistent with the template name (Loan instead of Zero coupon bond, etc)
* Updated terms and conditions and some wording on the website 
* Updated the transaction fee for creating a contract to 10 lovelaces
- Branch
- PR
> Small fixes on Marlowe Run Dist demo

- doc/marlowe/tutorials/marlowe-data.rst
- marlowe-actus/src/Language/Marlowe/ACTUS/Ops.hs
- marlowe-playground-client/grammar.ne
- marlowe-playground-client/src/JavascriptEditor/State.purs
- marlowe-playground-client/src/Language/Javascript/MarloweJS.ts
- marlowe-playground-client/src/Marlowe/Blockly.purs
- marlowe-playground-client/src/Marlowe/Gen.purs
- marlowe-playground-client/src/Marlowe/Holes.purs
- marlowe-playground-client/src/Marlowe/Linter.purs
- marlowe-playground-client/src/Marlowe/Monaco.ts
- marlowe-playground-client/src/Marlowe/Parser.purs
- marlowe-playground-client/test/BridgeTests.purs
- marlowe-playground-client/test/Marlowe/LintTests.purs
- marlowe-playground-client/test/contract.json
- marlowe-playground-server/app/PSGenerator.hs
- marlowe-playground-server/src/Marlowe/Mermaid.hs
- marlowe/src/Language/Marlowe/Analysis/FSSemantics.hs
- marlowe/src/Language/Marlowe/Extended.hs
- marlowe/src/Language/Marlowe/Semantics.hs
- marlowe/src/Language/Marlowe/Util.hs
- marlowe/test/Spec/Marlowe/Common.hs
- marlowe/test/Spec/Marlowe/Marlowe.hs
- marlowe/test/Spec/PAB/Workflow.hs
- marlowe/test/contract.json
- web-common-marlowe/src/Marlowe/Extended.purs
- web-common-marlowe/src/Marlowe/HasParties.purs
- web-common-marlowe/src/Marlowe/Semantics.purs
> Add Marlowe DivValue (division)

- plutus-chain-index/notes/ConnectingToTheTestnet.md
Add a short documentation about how to configure the node to connect to any testnet, and also include a troubleshooting section since people have been having issues connecting to the testnets and it may be worth to have some sort of a knowledge base somewhere.
- Branch
- PR
> Document how to connect to the testnet

- marlowe-dashboard-client/src/Welcome/View.purs
> Marlowe distributed coming soon

- doc/plutus/troubleshooting.rst
> Fix troubleshooting doc

- plutus-core/plutus-core/src/PlutusCore.hs
- plutus-core/plutus-ir/src/PlutusIR.hs
- plutus-core/plutus-ir/src/PlutusIR/Core/Type.hs
- plutus-core/untyped-plutus-core/src/UntypedPlutusCore.hs
- plutus-tx/src/PlutusTx/Code.hs
It'll be somewhat transformed, but not totally inaccurate, so worth
keeping.
- Branch
- PR
> Make applyCode preserve PIR if possible

- plutus-core/untyped-plutus-core/src/UntypedPlutusCore/Evaluation/Machine/Cek.hs
- plutus-core/untyped-plutus-core/test/Evaluation/Builtins/Definition.hs
This shows how to trigger the issue described in #3876.
> [Test] [Evaluaton] Update tests to trigger the strictness issue with 'unsafeEvaluateCek'

- cabal.project
- nix/pkgs/haskell/haskell.nix
- nix/pkgs/haskell/materialized-darwin/.plan.nix/cardano-cli.nix
- nix/pkgs/haskell/materialized-linux/.plan.nix/cardano-cli.nix
- nix/pkgs/haskell/materialized-windows/.plan.nix/cardano-cli.nix
- plutus-ledger/src/Ledger/Tx.hs
Removed types and functions in Ledger.Tx that were integrated in cardano-api instead. Updated cardano-node commit hash.
- Branch
- PR
> SCP-2750: Removed types and functions in Ledger.Tx integrated in cardano-api

- plutus-core/plutus-ir/src/PlutusIR/Core/Plated.hs
- plutus-core/plutus-ir/src/PlutusIR/Transform/LetFloat.hs
> Add annotation joining for PIR/LetFloat

- CONTRIBUTING.adoc
- flake.lock
- flake.nix
After chatting with @shlevy this seems like the way to go.
- Branch
- PR
> Switch to not pinning revs in flake.nix

- plutus-core/plutus-ir/test/TransformSpec.hs
- plutus-core/plutus-ir/test/transform/letFloat/rhsSqueezeVsNest
- plutus-core/plutus-ir/test/transform/letFloat/rhsSqueezeVsNest.golden
> Typecheck the results of let-float tests.

- nix/pkgs/haskell/extra.nix
- nix/pkgs/haskell/hlint.sha
- nix/pkgs/haskell/stylish-haskell.sha
See the note in `extra.nix` for the reasoning. Also will make
`updateMaterialized` a bit faster since there's fewer things to check.
- Branch
- PR
> Get stylish-haskell and hlint from the HLS project

- plutus-chain-index/app/Main.hs
- plutus-chain-index/src/Plutus/ChainIndex/DbStore.hs
- plutus-chain-index/src/Plutus/ChainIndex/Handlers.hs
> Split utxo table into outputs and inputs tables

- plutus-pab/README.md
Just a readme update. Added note for if plutus-pab.yaml.sample is updated, and refined running steps.
> Update plutus-pab readme

- plutus-core/plutus-core/src/PlutusCore/Default/Universe.hs
- plutus-core/plutus-core/src/Universe/Core.hs
> [Builtin] Add 'GCompare' instances for universes stuff

- plutus-ledger-api/src/Plutus/V2/Ledger/Contexts.hs
- plutus-tx/src/PlutusTx/IsData/TH.hs
> A few small Haddock fixes

- plutus-core-spec/plutus-core-specification.tex
occurences ->occurrences
- Branch
- PR
> Fix typo in plutus-core-specification.tex

- nix/pkgs/haskell/materialized-darwin/.plan.nix/plutus-tx-plugin.nix
- nix/pkgs/haskell/materialized-darwin/.plan.nix/plutus-tx.nix
- nix/pkgs/haskell/materialized-linux/.plan.nix/plutus-tx-plugin.nix
- nix/pkgs/haskell/materialized-linux/.plan.nix/plutus-tx.nix
- nix/pkgs/haskell/materialized-windows/.plan.nix/plutus-tx-plugin.nix
- nix/pkgs/haskell/materialized-windows/.plan.nix/plutus-tx.nix
- plutus-core/plutus-core/src/PlutusCore/Quote.hs
- plutus-core/plutus-ir/src/PlutusIR/Compiler/Definitions.hs
- plutus-tx-plugin/plutus-tx-plugin.cabal
- plutus-tx-plugin/src/PlutusTx/Compiler/Builtins.hs
- plutus-tx-plugin/src/PlutusTx/Compiler/Expr.hs
- plutus-tx-plugin/src/PlutusTx/Compiler/Types.hs
- plutus-tx-plugin/src/PlutusTx/Compiler/Utils.hs
- plutus-tx-plugin/src/PlutusTx/Plugin.hs
- plutus-tx-plugin/test/Budget/find.budget.golden
- plutus-tx-plugin/test/Budget/find.plc.golden
- plutus-tx-plugin/test/Plugin/Coverage/Spec.hs
- plutus-tx-plugin/test/Plugin/Coverage/coverageCode.plc.golden
- plutus-tx-plugin/test/Plugin/Spec.hs
- plutus-tx-plugin/test/Plugin/Typeclasses/concatTest.plc.golden
- plutus-tx/plutus-tx.cabal
- plutus-tx/src/PlutusTx/Code.hs
- plutus-tx/src/PlutusTx/Coverage.hs
- plutus-tx/src/PlutusTx/Lift.hs
- plutus-tx/src/PlutusTx/Plugin/Utils.hs
- plutus-tx/src/PlutusTx/TH.hs
- plutus-tx/src/PlutusTx/Trace.hs
> Coverage checking primitives

- doc/plutus/troubleshooting.rst
> Update PlutusTx error codes and messages in troubleshooting.

- plutus-tx-plugin/src/PlutusTx/Compiler/Binders.hs
- plutus-tx-plugin/src/PlutusTx/Compiler/Builtins.hs
- plutus-tx-plugin/src/PlutusTx/Compiler/Expr.hs
- plutus-tx-plugin/src/PlutusTx/Compiler/Names.hs
- plutus-tx-plugin/src/PlutusTx/Compiler/Type.hs
- plutus-tx-plugin/src/PlutusTx/Compiler/Type.hs-boot
- plutus-tx-plugin/test/Plugin/Coverage/coverageCode.plc.golden
- plutus-tx-plugin/test/Plugin/Primitives/void.plc.golden
Proof-of-concept improvement for what David's sharp eyes pointed out in #4212.
- Branch
- PR
> Compile void# to unit instead of wrapped error

- nix/pkgs/haskell/materialized-darwin/.plan.nix/plutus-core.nix
- nix/pkgs/haskell/materialized-darwin/default.nix
- nix/pkgs/haskell/materialized-linux/.plan.nix/plutus-core.nix
- nix/pkgs/haskell/materialized-linux/default.nix
- nix/pkgs/haskell/materialized-windows/.plan.nix/plutus-core.nix
- nix/pkgs/haskell/materialized-windows/default.nix
- plutus-core/executables/traceToStacks/Common.hs
- plutus-core/executables/traceToStacks/Main.hs
- plutus-core/executables/traceToStacks/TestGetStacks.hs
- plutus-core/plutus-core.cabal
- plutus-core/untyped-plutus-core/src/UntypedPlutusCore/Evaluation/Machine/Cek/EmitterMode.hs
- added tests to `getStacks`. Should I assert that the correct exception is raised? For example when something didn't exit? There's no builtin function for that in tasty but I can write one by hand. I did test it by hand in that case already.
- Branch
- PR
> SCP-2923 Add tests to functions called by `traceToStacks`

- plutus-tx-plugin/test/Plugin/Basic/Spec.hs
- plutus-tx-plugin/test/Plugin/Basic/nonstrictLet.plc.golden
- plutus-tx-plugin/test/Plugin/Basic/strictLet.plc.golden
- plutus-tx-plugin/test/Plugin/Basic/strictLetRec.plc.golden
- plutus-tx-plugin/test/Plugin/Basic/strictMultiLet.plc.golden
- plutus-tx-plugin/test/Plugin/Data/Spec.hs
- plutus-tx-plugin/test/Plugin/Data/monomorphic/monoCaseStrict.plc.golden
- plutus-tx-plugin/test/Plugin/Data/monomorphic/strictDataMatch.plc.golden
Strict let-bindings work already, but we had no tests for them; strict
patterns do nothing.
- Branch
- PR
> Add some tests for strict let-bindings and case patterns

- flake.lock
- flake.nix
- nix/pkgs/haskell/hls-darwin.sha
- nix/pkgs/haskell/hls-linux.sha
> Bump HLS to 1.5.1

- plutus-core/plutus-core/src/PlutusCore/Core/Instance/Eq.hs
- plutus-core/plutus-core/src/PlutusCore/Core/Type.hs
- plutus-core/plutus-core/src/PlutusCore/Error.hs
- plutus-core/plutus-ir/src/PlutusIR/TypeCheck/Internal.hs
- plutus-core/untyped-plutus-core/src/UntypedPlutusCore/Core/Instance/Eq.hs
> SCP-3125: Don't ignore annotations on (U)PLC Term/Type equality

- plutus-tx-plugin/test/Budget/Spec.hs
- plutus-tx-plugin/test/Budget/any.budget.golden
- plutus-tx-plugin/test/Budget/any.plc.golden
- plutus-tx-plugin/test/Budget/elem.budget.golden
- plutus-tx-plugin/test/Budget/elem.plc.golden
- plutus-tx-plugin/test/Budget/filter.budget.golden
- plutus-tx-plugin/test/Budget/filter.plc.golden
- plutus-tx-plugin/test/Budget/find.budget.golden
- plutus-tx-plugin/test/Budget/find.plc.golden
- plutus-tx-plugin/test/Budget/sum.budget.golden
- plutus-tx-plugin/test/Budget/sum.plc.golden
This is testing how expensive they are, so I think that optimizing them
makes sense.
- Branch
- PR
> Turn on optimization for budget tests

- .github/ISSUE_TEMPLATE/security_report.yml
- .github/SECURITY.md
> Add a security policy

- plutus-benchmark/lists/src/PlutusBenchmark/Lists/Sort/InsertionSort.hs
- plutus-benchmark/nofib/src/PlutusBenchmark/NoFib/Queens.hs
- plutus-ledger-api/src/Plutus/V1/Ledger/Value.hs
- plutus-tx/src/PlutusTx/List.hs
- plutus-tx/test/Spec.hs
> Add sortBy and partition (fix #4274)

- nix/pkgs/haskell/materialized-darwin/.plan.nix/plutus-ledger-api.nix
- nix/pkgs/haskell/materialized-linux/.plan.nix/plutus-ledger-api.nix
- nix/pkgs/haskell/materialized-windows/.plan.nix/plutus-ledger-api.nix
- plutus-ledger-api/plutus-ledger-api.cabal
- plutus-ledger-api/test/Spec.hs
- plutus-ledger-api/test/Spec/Eval.hs
People may bypass our plutus toolchain (for any reasons),and create uplc themselves. Test what happens when we try to execute with CEK such "hand-crafted" uplc that contains ill-scoped and ill-typed programs
- Branch
- PR
> SCP-3163: Test offline/online handling of "handcrafted" uplc 

- plutus-core/plutus-core/src/PlutusCore/ParserCommon.hs
- plutus-core/plutus-ir/test/TestLib.hs
This was annoying me, so I fixed it. Then I realised we already had an
issue, even.
Fixes #4197.
- Branch
- PR
> Better printing of megaparsec parse errors

- plutus-core/plutus-core/src/PlutusCore/Constant/Debug.hs
possibe -> possible
- Branch
- PR
> Fix typo in Debug.hs

- plutus-tx-plugin/src/PlutusTx/Compiler/Builtins.hs
This PR enables the builtin `blake2b_256`.
---
- Branch
- PR
> Enable blake2b_256 builtin in the plugin.

- plutus-core/plutus-core/src/PlutusCore/Constant/Typed.hs
- plutus-core/plutus-core/src/PlutusCore/Default/Builtins.hs
- plutus-core/plutus-core/src/PlutusCore/Default/Universe.hs
- plutus-core/plutus-core/test/Names/Spec.hs
I looked at Core and found some opportunities for optimization. The Core now looks better, but let's see what benchmarks say. If things are not slower, I'll add some docs and merge that.
> [Builtins] Optimize 'Typed' via 'INLINE' pragmas

- plutus-ledger-api/src/Plutus/V1/Ledger/Value.hs
This is the sole function in our codebase that was using do-notation
on-chain. It's surprising that that worked at all, but also it results
in a lot of calls to `foldr` as that's what do-notation over lists
eventually turns into.
Apart from being faster, this will help if we try and ban do-notation
entirely...
- Branch
- PR
> Optimize flattenValue

- plutus-tx-plugin/src/PlutusTx/Compiler/Expr.hs
Proof-of-concept workaround for #4298.
- Branch
- PR
> Support non-patched GHC outside of haskell.nix

- plutus-core/plutus-ir/src/PlutusIR/Transform/Inline.hs
- plutus-core/plutus-ir/test/transform/inline/single
- plutus-core/plutus-ir/test/transform/inline/single.golden
- plutus-tx-plugin/src/PlutusTx/Plugin.hs
- plutus-tx-plugin/test/Plugin/NoTrace/traceComplex.plc.golden
https://github.com/input-output-hk/plutus/pull/4304 with some more comments, also I turned off inlining constants because it's suspicious.
> Inline lambdas with trivial bodies 

- plutus-metatheory/src/index.lagda.md
> plutus-metatheory: Fix typos

- plutus-core/executables/Common.hs
- plutus-core/generators/PlutusCore/Generators/Internal/Denotation.hs
- plutus-core/generators/PlutusCore/Generators/Internal/Entity.hs
- plutus-core/plutus-core/src/PlutusCore/Constant/Function.hs
- plutus-core/plutus-core/src/PlutusCore/Constant/Meaning.hs
- plutus-core/plutus-core/src/PlutusCore/Constant/Typed.hs
- plutus-core/plutus-core/src/PlutusCore/Evaluation/Machine/Ck.hs
- plutus-core/plutus-ir/src/PlutusIR/Purity.hs
- plutus-core/untyped-plutus-core/src/UntypedPlutusCore/Evaluation/Machine/Cek/Internal.hs
> [Builtins] Drop 'Proxy' from 'TypeSchemeAll'

- plutus-metatheory/plutus-metatheory.cabal
> Fix cabal sdist plutus-metatheory error #4324

- plutus-core/plutus-core/src/PlutusCore/Constant/Typed.hs
- plutus-core/plutus-core/src/PlutusCore/Default/Builtins.hs
I ran out of time, so this is like half-written (I mean, the single topic of adding a built-in function). It's probably good to have these docs reviewed in batches anyway, given how much stuff there's to digest.
> Add Note [How to add a built-in function: simple cases]

- .github/workflows/benchmark.yml
- scripts/ci-plutus-benchmark.sh
- scripts/trigger-buildkite-pipeline.sh
> Teach /benchmark to take a benchmark name

- .github/workflows/benchmark.yml
> Fix string syntax

- .github/workflows/benchmark.yml
> Fix workflow syntax

- .github/workflows/benchmark.yml
> Get the comment body another way

- scripts/trigger-buildkite-pipeline.sh
> Fix arg number

- nix/pkgs/haskell/materialized-darwin/.plan.nix/plutus-benchmark.nix
- nix/pkgs/haskell/materialized-darwin/default.nix
- nix/pkgs/haskell/materialized-linux/.plan.nix/plutus-benchmark.nix
- nix/pkgs/haskell/materialized-linux/default.nix
- nix/pkgs/haskell/materialized-windows/.plan.nix/plutus-benchmark.nix
- nix/pkgs/haskell/materialized-windows/default.nix
- plutus-benchmark/README.md
- plutus-benchmark/plutus-benchmark.cabal
- plutus-benchmark/validation/BenchCek.hs
- plutus-benchmark/validation/BenchDec.hs
- plutus-benchmark/validation/BenchFull.hs
- plutus-benchmark/validation/Common.hs
Yet another validation benchmark that measures *only* the flat script deserialization time
- Branch
- PR
> Added plutus-benchmark:validation-decode

- scripts/ci-plutus-benchmark.sh
Useful if you've got more than one running on the same PR.
> Add the benchmark name to the summary comment

- plutus-core/plutus-core/src/PlutusCore/Default/Builtins.hs
Another small piece of docs. For some reason it took me a ridiculous amount of time to write it down.
> [Builtins] [Docs] Elaborate on 'Opaque'

- plutus-core/executables/pir/Main.hs
Useful for turning the flat PIR that comes out of the plugin into something you can look at.
- Branch
- PR
> Add a simple pir command to print the loaded PIR textually

- plutus-core/plutus-core/src/PlutusCore/Flat.hs
- plutus-core/plutus-core/test/Spec.hs
Quick fix to make sure we don't overflow when decoding via natural. I added an ad-hoc test but that can probably be folded into the stuff Nikos is doing later.
I expect the performance of `naturalToWord64Maybe` to be garbage, but we need safety more than we need it to be fast.
> Make sure we can't overflow when decoding via Natural

- nix/pkgs/haskell/materialized-darwin/.plan.nix/plutus-core.nix
- nix/pkgs/haskell/materialized-linux/.plan.nix/plutus-core.nix
- nix/pkgs/haskell/materialized-windows/.plan.nix/plutus-core.nix
- plutus-core/plutus-core.cabal
- plutus-core/plutus-core/src/GHC/Natural/Extras.hs
- plutus-core/plutus-core/src/PlutusCore/Flat.hs
> Optimize flat-decode Index instance for 64-bit machines

- plutus-core/index-envs/src/Data/DeBruijnEnv.hs
- plutus-core/index-envs/test/TestRAList.hs
> Switched DeBruijnEnv to BRAL.indexone impl.

- plutus-core/plutus-core/src/PlutusCore/Builtin/KnownType.hs
- plutus-core/plutus-core/src/PlutusCore/Default/Universe.hs
> [Builtins] Inline 'KnownBuiltinTypeIn' constraints

- plutus-core/plutus-core/src/PlutusCore/Parser/ParserCommon.hs
As @michaelpj suggested. And @effectfully also pointed out this *may* fix this https://hydra.iohk.io/build/12938326/nixlog/68.
- Branch
- PR
> Fix pType parser.

- plutus-metatheory/plutus-metatheory.cabal
> Add missing autogen-module

- plutus-tx/src/PlutusTx/Code.hs
> Add role annotations for CompiledCodeIn

- plutus-core/cost-model/CostModelGeneration.md
Just expanding the explanation of how to generate a new cost model.
- Branch
- PR
> Expand remarks on cost model generation

- plutus-core/plutus-core/src/PlutusCore/Data.hs
- plutus-ledger-api/src/Plutus/V1/Ledger/Slot.hs
- plutus-ledger-api/src/Plutus/V1/Ledger/Value.hs
- plutus-tx/src/PlutusTx/AssocMap.hs
- plutus-tx/src/PlutusTx/Builtins/Internal.hs
C.f. #4448.
Fixes #4449 together with #4448.
- Branch
- PR
> Instances of Data for some datatypes on release/node-1.34

- plutus-core/plutus-core/examples/PlutusCore/Examples/Builtins.hs
- plutus-core/plutus-core/src/PlutusCore/Builtin/KnownType.hs
- plutus-core/plutus-core/src/PlutusCore/Builtin/Polymorphism.hs
- plutus-core/plutus-core/src/PlutusCore/Default/Builtins.hs
- plutus-core/plutus-core/test/TypeSynthesis/Golden/IdAssumeBool.plc.golden
- plutus-core/plutus-core/test/TypeSynthesis/Golden/IdAssumeCheckBool.plc.golden
- plutus-core/plutus-core/test/TypeSynthesis/Golden/IdSomeConstantBool.plc.golden
- plutus-core/plutus-core/test/TypeSynthesis/Golden/SumInteger.plc.golden
Another piece of docs. Some stuff still remains to be written, that's for another time.
> [Docs] Add Note [How to add a built-in function: complicated cases]

- nix/pkgs/haskell/materialized-darwin/.plan.nix/plutus-metatheory.nix
- nix/pkgs/haskell/materialized-linux/.plan.nix/plutus-metatheory.nix
- nix/pkgs/haskell/materialized-windows/.plan.nix/plutus-metatheory.nix
- plutus-metatheory/plutus-metatheory.cabal
- plutus-metatheory/test/TestDetailed.hs
- plutus-metatheory/test/TestSimple.hs
> A small fix to avoid a "tmp" file lying around in metatheory

- plutus-ledger-api/src/Plutus/V1/Ledger/Api.hs
- plutus-ledger-api/src/Plutus/V1/Ledger/EvaluationContext.hs
- plutus-ledger-api/src/Plutus/V2/Ledger/Api.hs
> SCP-3630: Export more costmodel info in the api's EvaluationContext

- plutus-benchmark/validation/BenchDec.hs
- plutus-benchmark/validation/BenchFull.hs
- plutus-benchmark/validation/Common.hs
- plutus-ledger-api/src/Plutus/V1/Ledger/Api.hs
> Small fixes after SCP-3509: add runtime checks for allowed builtins

- plutus-core/plutus-core/src/PlutusCore/Builtin/Runtime.hs
- plutus-core/plutus-core/src/PlutusCore/Evaluation/Machine/MachineParameters.hs
- plutus-core/untyped-plutus-core/src/UntypedPlutusCore/Evaluation/Machine/Cek/CekMachineCosts.hs
- plutus-ledger-api/plutus-ledger-api.cabal
- plutus-ledger-api/src/Plutus/V1/Ledger/EvaluationContext.hs
> Added instance NFData EvaluationContext

- plutus-core/plutus-core/src/PlutusCore/Builtin/Runtime.hs
- plutus-core/plutus-core/src/PlutusCore/Evaluation/Machine/MachineParameters.hs
- plutus-core/untyped-plutus-core/src/UntypedPlutusCore/Evaluation/Machine/Cek/CekMachineCosts.hs
- plutus-ledger-api/plutus-ledger-api.cabal
- plutus-ledger-api/src/Plutus/V1/Ledger/EvaluationContext.hs
> backport: Added instance NFData EvaluationContext

- plutus-core/index-envs/src/Data/RandomAccessList/SkewBinary.hs
- plutus-core/index-envs/test/TestRAList.hs
- plutus-core/plutus-core.cabal
> Backport: SCP-3591: Add case for undefined behavior indexOne(Zero)

- plutus-core/untyped-plutus-core/src/UntypedPlutusCore/Check/Scope.hs
This was figured out by @effectfully and makes the pass of check-scope minimal.
Co-authored-by: effectfully <effectfully@gmail.com>
- Branch
- PR
> Effectfully's changes for scopecheck

- nix/pkgs/haskell/materialized-darwin/.plan.nix/plutus-benchmark.nix
- nix/pkgs/haskell/materialized-linux/.plan.nix/plutus-benchmark.nix
- nix/pkgs/haskell/materialized-windows/.plan.nix/plutus-benchmark.nix
- plutus-benchmark/plutus-benchmark.cabal
- plutus-benchmark/validation/BenchCek.hs
- plutus-benchmark/validation/Common.hs
> Don't do scopechecking for validation

- plutus-core/untyped-plutus-core/src/UntypedPlutusCore/Check/Scope.hs
Co-authored-by: effectfully <effectfully@gmail.com>
Co-authored-by: Nikolaos Bezirgiannis <bezirg@users.noreply.github.com>
Co-authored-by: effectfully <effectfully@gmail.com>
- Branch
- PR
> backport: SCP-3669: Inline scopecheck (#4483)

- plutus-tx/src/PlutusTx/Prelude.hs
Adding an odd function from the definition of even in the PlutusTx Prelude.
> Add odd function to the PlutusTx Prelude

- nix/pkgs/haskell/materialized-darwin/.plan.nix/plutus-core.nix
- nix/pkgs/haskell/materialized-linux/.plan.nix/plutus-core.nix
- nix/pkgs/haskell/materialized-windows/.plan.nix/plutus-core.nix
- plutus-core/plutus-core.cabal
- plutus-core/plutus-core/examples/PlutusCore/Examples/Builtins.hs
- plutus-core/plutus-core/src/PlutusCore/Builtin.hs
- plutus-core/plutus-core/src/PlutusCore/Builtin/KnownType.hs
- plutus-core/plutus-core/src/PlutusCore/Builtin/Meaning.hs
- plutus-core/plutus-core/src/PlutusCore/Builtin/Runtime.hs
- plutus-core/plutus-core/src/PlutusCore/Builtin/TestKnown.hs
- plutus-core/plutus-core/src/PlutusCore/Builtin/TypeScheme.hs
- plutus-core/plutus-core/src/PlutusCore/Default/Universe.hs
- plutus-core/plutus-core/src/PlutusCore/Evaluation/Machine/Ck.hs
- plutus-core/testlib/PlutusCore/Generators/Internal/Dependent.hs
- plutus-core/testlib/PlutusCore/Generators/Internal/TypeEvalCheck.hs
- plutus-core/testlib/PlutusCore/Generators/Test.hs
- plutus-core/untyped-plutus-core/src/UntypedPlutusCore/Evaluation/Machine/Cek.hs
- plutus-core/untyped-plutus-core/test/Evaluation/Builtins/Common.hs
- plutus-core/untyped-plutus-core/test/Evaluation/Builtins/MakeRead.hs
> [Builtins] Split 'KnownTypeIn' into two classes

- .github/workflows/benchmark.yml
Broken by
https://github.com/Khan/pull-request-comment-trigger/issues/22.
It was risky for us to be pulling the master version anyway.
- Branch
- PR
> Fix the benchmarking workflow

- plutus-core/plutus-core/src/PlutusCore/Builtin/KnownType.hs
- plutus-core/plutus-core/src/PlutusCore/Builtin/Meaning.hs
> [Refac] [Builtins] Remove a bit of noise

- nix/pkgs/haskell/materialized-darwin/.plan.nix/plutus-core.nix
- nix/pkgs/haskell/materialized-linux/.plan.nix/plutus-core.nix
- nix/pkgs/haskell/materialized-windows/.plan.nix/plutus-core.nix
- plutus-core/executables/Common.hs
- plutus-core/plutus-core.cabal
- plutus-core/plutus-core/src/PlutusCore.hs
- plutus-core/plutus-core/src/PlutusCore/Error.hs
- plutus-core/plutus-core/src/PlutusCore/Parser.hs
- plutus-core/plutus-core/src/PlutusCore/Parser/ParserCommon.hs
- plutus-core/plutus-core/test/Spec.hs
- plutus-core/plutus-core/test/scopes/apply.plc.golden
- plutus-core/plutus-core/test/scopes/lambda.plc.golden
- plutus-core/plutus-core/test/scopes/lambda2.plc.golden
- plutus-core/plutus-core/test/scopes/negation.plc.golden
- plutus-core/plutus-ir/src/PlutusIR/Parser.hs
- plutus-core/plutus-ir/test/NamesSpec.hs
- plutus-core/plutus-ir/test/ParserSpec.hs
- plutus-core/testlib/PlutusIR/Test.hs
- plutus-core/untyped-plutus-core/src/UntypedPlutusCore/Parser.hs
- plutus-errors/src/Errors.hs
- plutus-metatheory/src/Main.lagda
- plutus-metatheory/src/Raw.hs
> SCP-3527: Switch Error to carrying ParseErrorBundle instead of ParserError

- doc/reference/common-weaknesses/hard-limits.rst
- doc/reference/common-weaknesses/index.rst
This is a general class of weakness that can come up in a number of
forms.
> SCP-3413: Common weaknesses: add a short doc on hitting hard limits

- plutus-core/cost-model/create-cost-model/CreateBuiltinCostModel.hs
- plutus-core/cost-model/test/TestCostModels.hs
- plutus-core/plutus-core/src/PlutusCore/Evaluation/Machine/ExBudget.hs
Just fixing a function that had the wrong name (I think I changed the units at some point and forgot to change the name).  I took the opportunity to make some imports more explicit while I was at it because I'm trying to properly understand how the interface between Haskell and R works.
- Branch
- PR
> Rename function correctly

- scripts/ci-plutus-benchmark.sh
The whole block is going to the log, don't overwrite things.
> Fix the benchmark table printing

- plutus-ledger-api/src/Plutus/V1/Ledger/Api.hs
Done in https://github.com/input-output-hk/plutus/pull/4428 and then
accidentally re-introduced in
https://github.com/input-output-hk/plutus/pull/4522.
> Remove size limit again

- plutus-core/plutus-core/src/PlutusCore/Error.hs
This fixes GHC 9.2 support again.
- Branch
- PR
> plutus-core: Move TH stuff to end of file

- README.adoc
- plutus-core/plutus-core/src/PlutusCore/Default/Universe.hs
> Comments and README

- plutus-benchmark/common/PlutusBenchmark/Common.hs
- plutus-core/README.md
- plutus-core/plutus-core/src/PlutusCore/Evaluation/Machine/Exception.hs
- plutus-core/plutus-core/src/PlutusCore/Parser/Builtin.hs
- plutus-core/plutus-core/test/Evaluation/Machines.hs
- plutus-core/plutus-core/test/Spec.hs
- plutus-core/testlib/PlutusCore/Generators/Test.hs
- plutus-core/testlib/PlutusCore/Test.hs
- plutus-core/testlib/PlutusIR/Test.hs
- plutus-core/untyped-plutus-core/src/UntypedPlutusCore.hs
> Misc tidying: update comments, remove unused pragmas, and clean up imports.

- plutus-core/plutus-core/src/PlutusCore/Evaluation/Machine/BuiltinCostModel.hs
- plutus-core/plutus-core/src/PlutusCore/Evaluation/Machine/CostModelInterface.hs
- plutus-core/plutus-core/src/PlutusCore/Evaluation/Machine/MachineParameters.hs
- plutus-ledger-api/plutus-ledger-api.cabal
- plutus-ledger-api/src/Plutus/V1/Ledger/EvaluationContext.hs
- plutus-ledger-api/src/Plutus/V2/Ledger/EvaluationContext.hs
> SCP-3830: Trim serialiseData from v1-costmodel-params

- nix/pkgs/haskell/materialized-darwin/.plan.nix/plutus-ledger-api.nix
- nix/pkgs/haskell/materialized-linux/.plan.nix/plutus-ledger-api.nix
- nix/pkgs/haskell/materialized-windows/.plan.nix/plutus-ledger-api.nix
- plutus-core/plutus-core/src/PlutusCore/Evaluation/Machine/BuiltinCostModel.hs
- plutus-core/plutus-core/src/PlutusCore/Evaluation/Machine/CostModelInterface.hs
- plutus-core/plutus-core/src/PlutusCore/Evaluation/Machine/MachineParameters.hs
- plutus-ledger-api/plutus-ledger-api.cabal
- plutus-ledger-api/src/Plutus/V1/Ledger/EvaluationContext.hs
- plutus-ledger-api/src/Plutus/V2/Ledger/EvaluationContext.hs
> Backport: SCP-3830: Trim serialiseData from v1-costmodel-params

- flake.lock
- flake.nix
- nix/pkgs/haskell/haskell.nix
WIP, let hydra do some work for me.
> Bump HLS to 1.7

- plutus-ledger-api/src/Plutus/ApiCommon.hs
- plutus-ledger-api/test/Spec/Builtins.hs
- plutus-ledger-api/test/Spec/Eval.hs
It's 7, not 6. 6 was an intra-era HF inside Alonzo.
> Fix the protocol version for Vasil

- plutus-ledger-api/plutus-ledger-api.cabal
- plutus-ledger-api/src/Plutus/ApiCommon.hs
- plutus-ledger-api/test/Spec.hs
- plutus-ledger-api/test/Spec/Builtins.hs
- plutus-ledger-api/test/Spec/Eval.hs
- plutus-ledger-api/testlib/Plutus/Ledger/Test/ProtocolVersions.hs
We're only doing this in V2, not in V1 ever.
> SCP-3859: Restore the size limit in V2

- plutus-core/plutus-core/src/PlutusCore/DeBruijn/Internal.hs
I'm on my "make everything on the way of evaluation strict" crusade.
> [Names] Make 'NamedDeBruijn' strict

- plutus-ledger-api/src/Plutus/V1/Ledger/EvaluationContext.hs
> Remove EcdsaSecp256k1,SchnorrSecp256k1 from costparamnames

- plutus-core/plutus-core/test/TypeSynthesis/Golden/VerifyEd25519Signature.plc.golden
- plutus-tx-plugin/src/PlutusTx/Compiler/Expr.hs
- plutus-tx-plugin/test/Plugin/Coverage/Spec.hs
- plutus-tx-plugin/test/Plugin/Coverage/coverageCode.plc.golden
Tick unfloating is causing more issues than it's solving downstream, so better remove it.
- Branch
- PR
> Compiler Coverage: don't do tick unfloating

- plutus-core/plutus-core/test/TypeSynthesis/Golden/VerifyEd25519Signature.plc.golden
- plutus-tx-plugin/src/PlutusTx/Compiler/Expr.hs
- plutus-tx-plugin/test/Plugin/Coverage/Spec.hs
- plutus-tx-plugin/test/Plugin/Coverage/coverageCode.plc.golden
> Coverage: Remove unfloating on node 1.34

- CONTRIBUTING.adoc
> CONTRIBUTING.adoc: path doc fix

- plutus-core/plutus-core/src/PlutusCore/Evaluation/Machine/CostingFun/Core.hs
Just a tiny piece of docs, gonna merge right away.
> [Docs] [Builtins] Mention '-fpedantic-bottoms'

- plutus-core/plutus-core/src/PlutusCore/Data.hs
Just a tiny piece of docs, gonna merge right away.
> [Docs] [Builtins] Mention making 'Data' strict

- plutus-core/plutus-core/examples/PlutusCore/Examples/Builtins.hs
- plutus-core/plutus-core/src/PlutusCore/Default/Builtins.hs
- plutus-core/plutus-core/src/PlutusCore/TypeCheck/Internal.hs
- plutus-core/plutus-core/test/TypeSynthesis/Golden/IdIntegerAsBool.plc.golden
- plutus-core/plutus-core/test/TypeSynthesis/Golden/IsConstant.plc.golden
I think this is the last piece of docs that I want to write for this module (I'll move some existing notes into this module, though).
> [Docs] [Builtins] Add Note [Builtins and Plutus type checking]

- plutus-tx-plugin/src/PlutusTx/Options.hs
For `Bool` options, the "no-" version is automatically enabled.
> Only define positive versions of plugin options

- plutus-tx-plugin/src/PlutusTx/Options.hs
Add a description for each option.
> Add plugin option descriptions

- .github/PULL_REQUEST_TEMPLATE.md
> Update PULL_REQUEST_TEMPLATE.md, remove materialized Nix files in list.

- plutus-core/cost-model/print-cost-model/Main.hs
- plutus-core/plutus-core.cabal
- plutus-core/plutus-core/src/PlutusCore/Evaluation/Machine/BuiltinCostModel.hs
This is a quick PR to add an executable `print-cost-model` to `plutus-core`.  It takes a JSON builtin cost model file and converts it to a readable format (see below).  This is useful for getting a quick overview of the cost model and the output is also suitable for diff tools, making it easy to see how costs have changed when a new cost model is generated.  I'm sure the code could be improved, but it's just a quick implementation that isn't vital for anything else.
Sample output:
<details><summary>CPU model</summary>
```
addInteger                      : 303127 + 808*max(x,y)
appendByteString                : 436829 + 532*(x+y)
appendString                    : 421953 + 541*(x+y)
bData                           : 65454
blake2b_256                     : 104848 + 10459*x
chooseData …
```
> Kwxm/print cost model exe (SCP-3976)

- plutus-core/plutus-core/src/PlutusCore/Evaluation/Machine/CostModelInterface.hs
- plutus-core/plutus-core/test/CostModelInterface/Spec.hs
- plutus-ledger-api/src/Plutus/ApiCommon.hs
- plutus-ledger-api/src/Plutus/V1/Ledger/Api.hs
- plutus-ledger-api/src/Plutus/V1/Ledger/EvaluationContext.hs
- plutus-ledger-api/src/Plutus/V2/Ledger/Api.hs
- plutus-ledger-api/testlib/Plutus/Ledger/Test/EvaluationContext.hs
> PLT-250: mkEvaluationContext now lives in (MonadError CostModelApplyError)

- plutus-core/plutus-ir/src/PlutusIR/Compiler/Provenance.hs
Just occurred to me that Foldable can be derived :joy:
> Derive Foldable for Provenance

- CONTRIBUTING.adoc
- STYLEGUIDE.adoc
- I commented out a couple things that we aren't very sure about. Changed the wording a bit in a couple places. 
- Added a link under the "Working conventions" section, which maybe could use a tidy up now that we have the style guide. It's also OK as is, it's not very repetitive. 
- Branch
- PR
> PLT-97 Add style guide and a link to it from CONTRIBUTING doc.

- plutus-core/plutus-ir/test/Spec.hs
- plutus-core/plutus-ir/test/datatypes/dataEscape
- plutus-core/plutus-ir/test/datatypes/dataEscape.golden
Just checking that data escaping works the way I think it does.
Gonna merge without waiting for a review, since it's just a tiny test.
> [Test] [TypeCheck] Add a data escaping test

- plutus-core/plutus-core/src/PlutusCore/Builtin/Runtime.hs
- plutus-core/prelude/PlutusPrelude.hs
Checking if Marty's findings reproduce.
> [Refactoring] Remove some unused pragmas and imports

- doc/plutus/explanations/index.rst
- doc/plutus/explanations/language-versions.rst
- doc/plutus/explanations/ledger.rst
- doc/reference/index.rst
- doc/reference/language-changes.rst
> PLT-174: add some basic documentation on Plutus language versions

- plutus-core/plutus-core.cabal
- plutus-core/plutus-core/src/PlutusCore/Evaluation/Machine/MachineParameters.hs
- plutus-core/plutus-core/src/PlutusCore/Evaluation/Machine/MachineParameters/Default.hs
- plutus-core/plutus-core/src/PlutusCore/Evaluation/Machine/MachineParameters/DeferredMachineParameters.hs
- plutus-core/plutus-core/src/PlutusCore/Evaluation/Machine/MachineParameters/ImmediateMachineParameters.hs
- plutus-ledger-api/src/PlutusLedgerApi/Common.hs
- plutus-ledger-api/src/PlutusLedgerApi/Common/Eval.hs
This is so that I can look into the Core for builtins without waiting a ridiculous amount of time whenever I change something.
> [Builtins] Pull 'DefaultMachineParameters' into 'plutus-core'

- plutus-core/plutus-core/src/PlutusCore/TypeCheck.hs
- plutus-core/plutus-core/src/PlutusCore/TypeCheck/Internal.hs
- plutus-core/plutus-core/test/TypeSynthesis/Spec.hs
- plutus-core/testlib/PlutusCore/Generators/NEAT/Spec.hs
- plutus-metatheory/test/TestNEAT.hs
Just a small simplification of the kind checker API.
> [TypeCheck] Drop 'Maybe' from 'BuiltinTypes'

- plutus-core/plutus-ir/test/Spec.hs
- plutus-core/plutus-ir/test/recursion/factorial
- plutus-core/plutus-ir/test/recursion/factorial.golden
- plutus-core/testlib/PlutusIR/Test.hs
Just a test showcasing how we do recursive functions in Plutus IR for RV people to look at. Also shows how recursive functions are compiled to Untyped Plutus Core.
No mutual recursion for simplicity.
> [PIR] [Test] Add a 'factorial' example

- plutus-ledger-api/src/PlutusLedgerApi/V1/Value.hs
Fixes #4707
It would be nice to have a testcase that generates values, adds a currency with amount 0, and checks that the comparisons still have the same value. But since there isn't a generator for Values (right?) I skipped this.
- Branch
- PR
> Fix `lt` and `gt` for `Value`s

- plutus-ledger-api/src/Plutus/V1/Ledger/Value.hs
> Fix 4707 cherry pick

- nix/pkgs/fix-stylish-haskell/default.nix
- plutus-core/untyped-plutus-core/test/Evaluation/ApplyBuiltinName.hs
- prettyprinter-configurable/Setup.hs
stylish-haskell could not parse two files, but now it can.
> Applied small changes to make stylish-haskell able to parse all sources

- plutus-conformance/src/PlutusConformance/Common.hs
This is a possible alternative to the executable, which has the
advantage that we don't need to duplicate the traversal and evaluation
machinery.
Obviously the executable can do more stuff, but this seems maybe easier?
> Teach the UPLC evaluation test type the --accept option

- build/buildkite/script-evaluation-test.yml
- plutus-ledger-api/plutus-ledger-api.cabal
- plutus-ledger-api/test-onchain-evaluation/Main.hs
- plutus-ledger-api/testlib/PlutusLedgerApi/Test/EvaluationEvent.hs
Looking much better now: https://buildkite.com/input-output-hk/plutus-script-evaluation/builds/52#018191be-738b-48d0-b414-6d9a9f54f705
> Script evaluation test: one test case per dump file

- plutus-conformance/src/PlutusConformance/Common.hs
This makes it work like --accept in tasty-golden, which is what we
want.
> Make --accept write the file if it doesn't exist

- .github/workflows/hlint.yml
- CONTRIBUTING.adoc
I thought `hlint-run` doesn't support specifying hint files but @michaelpj discovered that it does. Also updated contribution doc.
> Use hlint-run action in CI

- .github/.hlint.yaml
> Remove unused pragma hint

- plutus-ledger-api/src/Plutus/ApiCommon.hs
This reverts commit 8cb94e1bd3e1aefd7e07da1dfd0b61073f158393.
> Delay SECP256k1 builtins to Chang

- plutus-ledger-api/src/PlutusLedgerApi/Common/Versions.hs
> Add Generic instance for LedgerPlutusVersion

- plutus-metatheory/src/Main.lagda
> Add comments to `runU`. (Follow up on PR #4800)

- plutus-benchmark/validation/BenchDec.hs
- plutus-ledger-api/src/Codec/CBOR/Extras.hs
- plutus-ledger-api/src/PlutusLedgerApi/Common.hs
- plutus-ledger-api/src/PlutusLedgerApi/Common/SerialisedScript.hs
- plutus-ledger-api/src/PlutusLedgerApi/V1.hs
- plutus-ledger-api/src/PlutusLedgerApi/V2.hs
- plutus-ledger-api/src/PlutusLedgerApi/V3.hs
- plutus-ledger-api/test/Spec/Builtins.hs
> PLT-580: Return more useful info from the `isScriptWellFormed` function

- plutus-core/plutus-core/src/PlutusCore/Evaluation/Machine/MachineParameters.hs
:cry: 
Also, apparently I've practically predicted that:
> [Docs] [Builtins] Add a comment about 'mkMachineParameters' failing to inline

- doc/README.md
- shell.nix
Exactly the same as in plutus-apps https://github.com/input-output-hk/plutus-apps/pull/562
> Enhance devx when modifying readthedocs documentation locally

- doc/adr/0001-record-architecture-decisions.rst
- doc/adr/index.rst
- doc/index.rst
> PLT-556: Copy ADR setup from plutus-apps

- plutus-tx/plutus-tx.cabal
- plutus-tx/test/Show/Spec.hs
- plutus-tx/test/Spec.hs
Added property tests for `show @Integer` and `show @BuiltinByteString`.
> PLT-424: Add some property tests for PlutusTx.Show

- plutus-core/plutus-core/src/PlutusCore/TypeCheck/Internal.hs
- plutus-core/plutus-ir/src/PlutusIR/Transform/Inline.hs
- plutus-core/untyped-plutus-core/src/UntypedPlutusCore/Transform/Inline.hs
PLT-339.  This seemed suspiciously easy.
- Branch
- PR
> PLT-339: use Dupable in inliners

- plutus-core/plutus-core/src/PlutusCore/Evaluation/Machine/Exception.hs
- plutus-errors/src/Errors.hs
> Remove the "dead" error about builtin arity

- cabal.project
- flake.lock
- nix/pkgs/haskell/extra.nix
- nix/pkgs/haskell/haskell.nix
- plutus-core/executables/Common.hs
- plutus-core/plutus-core.cabal
- plutus-core/plutus-ir/src/PlutusIR/Core/Plated.hs
- plutus-core/plutus-ir/src/PlutusIR/Transform/DeadCode.hs
- plutus-core/untyped-plutus-core/src/UntypedPlutusCore/Evaluation/Machine/Cek/ExBudgetMode.hs
- plutus-errors/plutus-errors.cabal
- plutus-tx-plugin/plutus-tx-plugin.cabal
> Bump hackage.nix, haskell.nix, and index-state

- doc/tutorials/BasicValidators.hs
- plutus-ledger-api/src/PlutusLedgerApi/V1.hs
- plutus-ledger-api/src/PlutusLedgerApi/V1/Address.hs
- plutus-ledger-api/src/PlutusLedgerApi/V1/Contexts.hs
- plutus-ledger-api/src/PlutusLedgerApi/V1/Credential.hs
- plutus-ledger-api/src/PlutusLedgerApi/V1/Scripts.hs
- plutus-ledger-api/src/PlutusLedgerApi/V1/Tx.hs
- plutus-ledger-api/src/PlutusLedgerApi/V1/Value.hs
- plutus-ledger-api/src/PlutusLedgerApi/V2.hs
- plutus-ledger-api/src/PlutusLedgerApi/V2/Contexts.hs
- plutus-ledger-api/src/PlutusLedgerApi/V2/Tx.hs
- plutus-ledger-api/src/PlutusLedgerApi/V3.hs
...along with the Hash types. These can be moved to plutus-apps if needed.
> PLT-724: Remove Validator, MintingPolicy and StakeValidator from ledger api

- plutus-core/plutus-core.cabal
- plutus-core/plutus-core/test/Spec.hs
- plutus-core/testlib/PlutusCore/Generators/NEAT/Spec.hs
- plutus-metatheory/test/TestNEAT.hs
-------
This is to make it easier for me (and perhaps someone else) to develop and
run the tests locally with -O0.
- Branch
- PR
> Added tasty options to allow easier neat tests at runtime

- doc/explanations/ledger.rst
Revised the ledger.rst file to add a link to the newly published EUTXO Handbook.
> added link to EUTXO Handbook on the What is a ledger? page

- plutus-ledger-api/src/PlutusLedgerApi/Common/ParamName.hs
> tagWithParamNames: remove redundant check

- CONTRIBUTING.adoc
Clarify a few things including merging PRs, force pushing and rebasing. These were originally written in a google doc.
> PLT-727: Update the contributing guide

- flake.lock
- flake.nix
- nix/pkgs/haskell/extra.nix
- release.nix
> Bump HLS to 1.8

- plutus-tx/src/PlutusTx/Builtins/Internal.hs
This fixes an incorrect error message.  I'll auto-merge it without review.
> Wrong error message for PlutusTx Ed25519 verification builtin

- __std__/README.md
- __std__/cells/plutus/devshells/plutus-shell.nix
- __std__/cells/toolchain/devshellProfiles/common.nix
- __std__/cells/toolchain/packages/default.nix
- __std__/cells/toolchain/packages/git-work-in-progress.nix
- Fixed some inconsistencies in README.me
- Added the `fix-*` scripts to the plutus shell
> Add useful commands to plutus-shell and fix nix README.me 

- cabal.project
Looks like this actually got a new release at some point!
> Remove allow-newer for size-based

- __std__/cells/plutus/devshells/plutus-shell.nix
- shell.nix
Also adds R to the shell regardless of system
> Add LOCALE_ARCHIVE to plutus devshell

- plutus-benchmark/common/PlutusBenchmark/Common.hs
- plutus-core/plutus-core/src/PlutusCore/Evaluation/Machine/CostModelInterface.hs
- plutus-ledger-api/src/PlutusLedgerApi/Common.hs
- plutus-ledger-api/src/PlutusLedgerApi/Common/Eval.hs
- plutus-ledger-api/src/PlutusLedgerApi/Common/ParamName.hs
- plutus-ledger-api/src/PlutusLedgerApi/Common/ProtocolVersions.hs
- plutus-ledger-api/src/PlutusLedgerApi/Common/SerialisedScript.hs
- plutus-ledger-api/src/PlutusLedgerApi/Common/Versions.hs
- plutus-ledger-api/src/PlutusLedgerApi/V1.hs
- plutus-ledger-api/src/PlutusLedgerApi/V1/Address.hs
- plutus-ledger-api/src/PlutusLedgerApi/V1/Bytes.hs
- plutus-ledger-api/src/PlutusLedgerApi/V1/Contexts.hs
- plutus-ledger-api/src/PlutusLedgerApi/V1/Credential.hs
- plutus-ledger-api/src/PlutusLedgerApi/V1/DCert.hs
- plutus-ledger-api/src/PlutusLedgerApi/V1/EvaluationContext.hs
- plutus-ledger-api/src/PlutusLedgerApi/V1/Interval.hs
- plutus-ledger-api/src/PlutusLedgerApi/V1/ParamName.hs
- plutus-ledger-api/src/PlutusLedgerApi/V1/Scripts.hs
- plutus-ledger-api/src/PlutusLedgerApi/V1/Tx.hs
- plutus-ledger-api/src/PlutusLedgerApi/V1/Value.hs
- plutus-ledger-api/src/PlutusLedgerApi/V2.hs
- plutus-ledger-api/src/PlutusLedgerApi/V2/Contexts.hs
- plutus-ledger-api/src/PlutusLedgerApi/V2/EvaluationContext.hs
- plutus-ledger-api/src/PlutusLedgerApi/V2/ParamName.hs
- plutus-ledger-api/src/PlutusLedgerApi/V3.hs
- plutus-ledger-api/src/PlutusLedgerApi/V3/EvaluationContext.hs
- plutus-ledger-api/src/PlutusLedgerApi/V3/ParamName.hs
- plutus-tx-plugin/src/PlutusTx/Plugin.hs
> PLT-743: Added more haddock to api

- __std__/cells/plutus/library/make-plutus-shell.nix
I was looking at it and this seems nicer!
> Make more shell inputs into commands

- __std__/cells/plutus/library/combine-haddock.nix
- __std__/cells/plutus/packages/read-the-docs-site.nix
- plutus-benchmark/plutus-benchmark.cabal
- plutus-core/plutus-core.cabal
- plutus-core/testlib/PlutusCore/Generators/QuickCheck/Utils.hs
> Replace * with Type in PlutusCore.Generators.QuickCheck.Utils.hs

- doc/srcspan.md
> PLT-832: Investigate ways to generate SrcSpan-annotated UPLC.

- flake.lock
- flake.nix
To fix libsodium warning error.
> Bump iohk-nix flake input

- README.adoc
Explain about CHaP, remove some old text.
> Fix a few things in the README

- plutus-core/plutus-core.cabal
- plutus-ledger-api/plutus-ledger-api.cabal
- plutus-tx-plugin/plutus-tx-plugin.cabal
- plutus-tx/plutus-tx.cabal
Not releasing prettyprinter-configurable or word-array, since there's no change.
> Version 1.1.1.0

- flake.lock
- flake.nix
- nix/cells/cloud/pipelines.nix
> fix(ci): only build the required derivation

- plutus-benchmark/plutus-benchmark.cabal
> Remove plutus-tx dependency from plutus-benchmark-script-contexts-tests

- plutus-core/plutus-core/examples/PlutusCore/Examples/Builtins.hs
- plutus-core/plutus-core/test/TypeSynthesis/Golden/ScottToMetaUnit.plc.golden
- plutus-core/untyped-plutus-core/test/Evaluation/Builtins/Common.hs
- plutus-core/untyped-plutus-core/test/Evaluation/Builtins/Definition.hs
As per the today's discussion.
> [Builtins] [Test] Add 'ScottToMetaUnit'

- plutus-ledger-api/src/PlutusLedgerApi/V1/Crypto.hs
I needed this in an example for readthedocs.
> Derive `PlutusTx.Show` for `PubKeyHash`

- .github/PULL_REQUEST_TEMPLATE.md
> Add a reminder about changelogs to the PR template

- plutus-core/plutus-core/src/PlutusCore/Subst.hs
- Makes them less tedious
- Avoids me writing more pointless cases in the sums and products branch
- Generalize over annotation, why not
> Simplify some substitution functions

- doc/read-the-docs-site/tutorials/BasicPolicies.hs
- doc/read-the-docs-site/tutorials/basic-minting-policies.rst
Fix minting policy in tutorial in light of https://www.tweag.io/blog/2022-03-25-minswap-lp-vulnerability
Co-authored-by: David Eichmann <EichmannD@gmail.com>
This PR was originally in plutus-apps: https://github.com/input-output-hk/plutus-apps/pull/379.
But since we removed the minting policy example in RTD, it makes more sense to update the equivalent page in `plutus`.
- Branch
- PR
> Fix minting policy in tutorial in light of https://www.tweag.io/blog/2022-03-25-minswap-lp-vulnerability

- plutus-core/changelog.d/20221130_100833_michael.peyton-jones_nothunks_data.md
- plutus-core/plutus-core/src/PlutusCore/Data.hs
So it doesn't have to live in the ledger.
Fixes #4983.
- Branch
- PR
> Add NoThunks instance for Data

- plutus-core/plutus-ir/src/PlutusIR/Transform/Inline.hs
- plutus-core/untyped-plutus-core/src/UntypedPlutusCore/Transform/Inline.hs
The inliner was written before the style guide existed. I've fixed the line lengths and added more Haddock as per the style guide.
- Branch
- PR
> Add Haddock to inliner

- nix/cells/automation/pipelines.nix
> Try to avoid the benchmarking regex crashing everything

- .github/workflows/test.yml
- nix/cells/automation/pipelines.nix
- Try to avoid the benchmarking regex crashing everything
- Try to fix it again, add smoke tests
- Branch
- PR
> mpj/try to fix cicero AGAIN

- plutus-core/plutus-ir/src/PlutusIR/Transform/Inline.hs
The same changes will happen in the UPLC inliner in another PR once this is approved.
I've made it so that we don't need to check the purity repeatedly, and avoided checking if it's immediately evaluated in more cases, which can be slow.
I understand that we don't care about performance very much here but there is almost no cost here (I think it's not harder to read?) so maybe it's worth doing? 
- Branch
- PR
> Optimize `maybeAddSubst` in the inliner.

- plutus-ledger-api/src/PlutusLedgerApi/Common.hs
- plutus-ledger-api/src/PlutusLedgerApi/Common/ParamName.hs
- plutus-ledger-api/src/PlutusLedgerApi/V1/EvaluationContext.hs
- plutus-ledger-api/src/PlutusLedgerApi/V2/EvaluationContext.hs
- plutus-ledger-api/src/PlutusLedgerApi/V3/EvaluationContext.hs
- plutus-ledger-api/testlib/PlutusLedgerApi/Test/EvaluationEvent.hs
> Exports Data&ExBudget from Api.Common

- plutus-core/untyped-plutus-core/src/UntypedPlutusCore/Transform/Inline.hs
Follow up on PR#4991.
- Branch
- PR
> Sync up the UPLC inliner with the PIR inliner.

- flake.lock
- nix/cells/plutus/library/make-plutus-shell.nix
- nix/cells/plutus/library/plutus-project-8107.nix
I run `nix flake lock --update-input haskell-nix --update-input hackage-nix`
Recent version of haskell.nix fixes https://github.com/input-output-hk/haskell.nix/issues/1753
> Remove pkg-config from the devshell packages

- README.adoc
- flake.lock
- flake.nix
Seems to work fine! Annoyingly there is a regression in `implicit-hie`
so you may now need a `hie-yaml` file like this:
```yaml
cradle:
cabal:
```
- Branch
- PR
> HLS 1.9.0.0

- plutus-core/plutus-ir/test/GeneratorSpec.hs
- plutus-core/plutus-ir/test/GeneratorSpec/Terms.hs
- plutus-core/plutus-ir/test/GeneratorSpec/Types.hs
- plutus-core/testlib/PlutusIR/Generators/QuickCheck/ShrinkTerms.hs
Same as #5036 except hopefully not stuck.
> [Bug] [Test] Fix shrinking issues

- plutus-core/plutus-core/src/PlutusCore/Evaluation/Machine/CostModelInterface.hs
Per @kwxm 's suggestion for #4962. Closes #4962.
- Branch
- PR
> Add comment about `applyCostModelParam` being costly.

- plutus-core/untyped-plutus-core/src/UntypedPlutusCore/Evaluation/Machine/Cek/Debug/Internal.hs
> Small fix after drop uni PR

- nix/cells/plutus/packages/cabal-fmt.nix
See https://github.com/phadej/cabal-fmt/pull/68
> Bump cabal-fmt

- plutus-core/untyped-plutus-core/src/UntypedPlutusCore/Core/Type.hs
This explains the underlying phenomenon, which is useful.
- Branch
- PR
> Add a reference to a GHC note

- plutus-core/changelog.d/20230207_100654_thealmartyblog_fix_term_parser.md
- plutus-core/plutus-core/src/PlutusCore/Parser.hs
- plutus-core/plutus-ir/src/PlutusIR/Parser.hs
- plutus-core/untyped-plutus-core/src/UntypedPlutusCore/Parser.hs
> Fix term parsers for PLC, UPLC, PIR. Now they can parse comments.

- plutus-core/plutus-core/examples/PlutusCore/Examples/Builtins.hs
- plutus-core/plutus-core/src/PlutusCore/Builtin/KnownTypeAst.hs
- plutus-core/plutus-core/test/TypeSynthesis/Golden/ForallFortyTwo.plc.golden
- plutus-core/untyped-plutus-core/test/Evaluation/Builtins/Definition.hs
Testing that builtins with one type argument and no term arguments are OK.
> [Test] [Builtin] Add 'ForallFortyTwo'

- .github/workflows/benchmark.yml
I'm giving up on `workflow_dispatch`: you *still* need to push to master for changes to `benchmark.yml` to take effect.
`workflow_dispatch` lets you choose which branch to run on, but it will still use the `benchmark.yml` from master.
> Fix benchmark.yml

- .github/workflows/benchmark.yml
It doesn't work, and it has little value anyway.
> Remove jobId from 'Publish Link To Action Run'

- doc/read-the-docs-site/requirements.txt
dependabot complained: https://github.com/input-output-hk/plutus/security/dependabot
> Bump some deps in read-the-docs-site/requirements.txt

- doc/changelog.d/20230209_110024_mjaskelioff_builtins_overview.rst
- doc/notes/plutus-core/Builtins_Overview.md
- doc/notes/plutus-core/README.md
A note based on the [google docs document](https://docs.google.com/document/d/1PndmLSI-150gCQ49nsricAc9BOzxgceYbNerMuFp25E/edit?usp=sharing) which provides an overview of built-ins in implementation, specification, and formalisation.
> PLT-1415 Added a note with an overview of builtins

- doc/read-the-docs-site/simple-example.rst
Corrects spelling error on plutus auction example
- Branch
- PR
> Correct spelling error within plutus docs

- .github/workflows/script-evaluation-test.yml
To match the config of the dump script in https://github.com/input-output-hk/plutus-apps/pull/955
> Update S3 link in script-evaluaton-test.yml

- plutus-core/changelog.d/20230215_132227_michael.peyton-jones_no_ann_version.md
- plutus-core/executables/src/PlutusCore/Executable/Common.hs
- plutus-core/plutus-core.cabal
- plutus-core/plutus-core/src/PlutusCore.hs
- plutus-core/plutus-core/src/PlutusCore/Core/Instance/Pretty/Common.hs
- plutus-core/plutus-core/src/PlutusCore/Core/Instance/Scoping.hs
- plutus-core/plutus-core/src/PlutusCore/Core/Type.hs
- plutus-core/plutus-core/src/PlutusCore/Flat.hs
- plutus-core/plutus-core/src/PlutusCore/Parser/ParserCommon.hs
- plutus-core/plutus-core/src/PlutusCore/Version.hs
- plutus-core/testlib/PlutusCore/Generators/Hedgehog/AST.hs
- plutus-core/testlib/PlutusCore/Generators/Hedgehog/Test.hs
- plutus-core/testlib/PlutusIR/Test.hs
- plutus-core/untyped-plutus-core/src/UntypedPlutusCore.hs
- plutus-core/untyped-plutus-core/src/UntypedPlutusCore/Core/Type.hs
- plutus-core/untyped-plutus-core/src/UntypedPlutusCore/Parser.hs
- plutus-ledger-api/src/PlutusLedgerApi/Common/Eval.hs
- plutus-ledger-api/test/Spec/Versions.hs
- plutus-ledger-api/testlib/PlutusLedgerApi/Test/Examples.hs
- plutus-tx-plugin/src/PlutusTx/Plugin.hs
- plutus-tx-plugin/test/IsData/Spec.hs
- plutus-tx/src/PlutusTx/Lift.hs
It's not useful, we don't need a position for it or any other kind of
annotation really.
- Branch
- PR
> Remove annotation from Version

- plutus-core/changelog.d/20230216_194718_bezirg_tx_optional.md
- plutus-core/executables/debugger/Draw.hs
- plutus-core/executables/debugger/Event.hs
- plutus-core/executables/debugger/Main.hs
- plutus-core/executables/debugger/Types.hs
> Debugger: make hs-file optional

- plutus-core/changelog.d/20230220_195818_bezirg_dbgr_errors.md
- plutus-core/executables/debugger/Draw.hs
- plutus-core/executables/debugger/Event.hs
- plutus-core/executables/debugger/Main.hs
- plutus-core/executables/debugger/Types.hs
- plutus-core/executables/uplc/Main.hs
- plutus-core/plutus-core.cabal
- plutus-core/untyped-plutus-core/src/UntypedPlutusCore/Evaluation/Machine/Cek/Debug/Driver.hs
- plutus-core/untyped-plutus-core/src/UntypedPlutusCore/Evaluation/Machine/Cek/Debug/Internal.hs
- plutus-core/untyped-plutus-core/src/UntypedPlutusCore/Evaluation/Machine/Cek/Internal.hs
- plutus-core/untyped-plutus-core/test/Evaluation/Debug.hs
- plutus-core/untyped-plutus-core/test/Evaluation/Debug/ex3.golden
- plutus-core/untyped-plutus-core/test/Evaluation/Debug/ex4.golden
I used a brick pane that was previously unused to show the errors.
- Branch
- PR
> PLT-1457: Handle CEK errors in the debug driver

- doc/notes/plutus-core/Builtins_Overview.md
No changelog required
- Branch
- PR
> Update of the builtin document

- cabal.project
- flake.lock
- plutus-core/plutus-core.cabal
> Update version bounds for cardano-crypto-class

- plutus-core/untyped-plutus-core/src/UntypedPlutusCore/Transform/Inline.hs
Remove a statement that hasn't been true for a long time.
> Update "Note [Differences from PIR inliner]"

- doc/read-the-docs-site/plutus-doc.cabal
- plutus-benchmark/plutus-benchmark.cabal
- plutus-conformance/plutus-conformance.cabal
- plutus-core/CHANGELOG.md
- plutus-core/changelog.d/20230228_155335_michael.peyton-jones_better_readable_pp.md
- plutus-core/changelog.d/20230228_215517_bezirg_dbg_budget.md
- plutus-core/plutus-core.cabal
- plutus-ledger-api/CHANGELOG.md
- plutus-ledger-api/changelog.d/20230302_163021_michael.peyton-jones_fix_interval.md
- plutus-ledger-api/plutus-ledger-api.cabal
- plutus-metatheory/plutus-metatheory.cabal
- plutus-tx-plugin/CHANGELOG.md
- plutus-tx-plugin/plutus-tx-plugin.cabal
- plutus-tx/CHANGELOG.md
- plutus-tx/changelog.d/20230227_054605_unsafeFixIO_foldr.md
- plutus-tx/plutus-tx.cabal
> version 1.3.0.0

- .github/workflows/check-changelog.yml
Maybe I should do this in the JS bit, not sure.
- Branch
- PR
> Don't require changelogs for draft PRs

- plutus-core/cost-model/budgeting-bench/Benchmarks/Crypto.hs
- plutus-core/cost-model/budgeting-bench/Main.hs
- plutus-core/plutus-core.cabal
This is just to rename a file that I've already renamed in another branch but which keeps causing me merge problems for some reason.  I don't think any review is required.
> CryptoAndHashes -> Crypto

- .github/workflows/longitudinal-benchmark.yml
> Try turning off pre-commit hooks so that the benchmarking action can commit

- .readthedocs.yml
- doc/read-the-docs-site/requirements.txt
Time moves on, Python 3.7 is old and not supported. The config file
format has changed too.
- Branch
- PR
> Fix RTD config file

- .github/workflows/haddock.yml
- .github/workflows/hlint.yml
- .github/workflows/pre-commit-check.yml
> Try downgrading the nix version in workflows

- cabal.project
- flake.lock
- plutus-core/plutus-core.cabal
- plutus-core/plutus-core/src/Universe/Core.hs
- Bound some to get a newer dependent-sum
- Bump hackage and CHaP
- Branch
- PR
> Fix dependent-sum issue through bounding some

- plutus-core/changelog.d/20230328_150430_michael.peyton-jones_remove_flat_instances.md
- plutus-core/plutus-core/src/PlutusCore/Flat.hs
> Addres comments on Flat PR

- plutus-core/changelog.d/20230404_120804_bezirg_fix_safeencodebits.md
- plutus-core/plutus-core/src/PlutusCore/Flat.hs
- plutus-core/plutus-ir/src/PlutusIR/Core/Instance/Flat.hs
- plutus-core/untyped-plutus-core/src/UntypedPlutusCore/Core/Instance/Flat.hs
> PLT-5498: Fix safeEncodeBits overflow

- plutus-metatheory/src/Algorithmic/BehaviouralEquivalence/CKvsCEK.lagda.md
- plutus-metatheory/src/Algorithmic/ReductionEC.lagda.md
This PR uses the typed CEK BUILTIN' implementation to implement the Reduction/CK BUILTIN' function, hence reducing the number of implementations of the BUILTIN function from 3 to 2.
> PLT-115 Merge CK and CEK BUILTIN function

- .gitattributes
- .gitignore
- .ignore
- NOTICE
- doc/read-the-docs-site/README.md
- nix/cells/plutus/packages/pre-commit-check.nix
- plutus-core/plutus-core.cabal
- plutus-core/plutus-core/src/PlutusCore/Evaluation/Machine/Exception.hs
- plutus-ledger-api/plutus-ledger-api.cabal
> Some cleanup

- plutus-core/untyped-plutus-core/src/UntypedPlutusCore/Transform/Inline.hs
That's just wrong. Hopefully this doesn't matter much.
- Branch
- PR
> UPLC inliner should not think force is cost-okay

- plutus-core/untyped-plutus-core/test/Evaluation/Builtins/Costing.hs
This adds a test that `flattenCostRose` is sufficiently lazy. I did check that making it overly strict results in the test failing.
> [Test] [Costing] Add 'test_flattenCostRoseHandlesBottom'

- plutus-core/plutus-core/examples/PlutusCore/Examples/Builtins.hs
- plutus-core/plutus-core/src/PlutusCore/Builtin/KnownTypeAst.hs
- plutus-core/plutus-core/src/PlutusCore/Builtin/Meaning.hs
Prompted by  #5204. This version of `ToBinds` should be much more efficient than the previous one, but it doesn't seem to matter at all. Still, why be slow if you can be fast with roughly the same complexity.
> [Builtins] Optimize 'ToBinds'

- plutus-core/changelog.d/20230418_193516_effectfully_newtype_intercept_and_slope.md
- plutus-core/cost-model/create-cost-model/CreateBuiltinCostModel.hs
- plutus-core/plutus-core/src/PlutusCore/Evaluation/Machine/BuiltinCostModel.hs
- plutus-core/plutus-core/src/PlutusCore/Evaluation/Machine/CostingFun/Core.hs
- plutus-core/plutus-core/src/PlutusCore/Evaluation/Machine/CostingFun/JSON.hs
To make sure we don't confuse the two.
> [Costing] 'newtype' 'intercept' and 'slope'

- plutus-ledger-api/changelog.d/20230418_152734_michael.peyton-jones_plutus_v3_in_conway.md
- plutus-ledger-api/src/PlutusLedgerApi/Common/ProtocolVersions.hs
- plutus-ledger-api/src/PlutusLedgerApi/Common/Versions.hs
- plutus-ledger-api/test/Spec/Versions.hs
Confirmed here: https://github.com/input-output-hk/cardano-ledger/pull/3365#issuecomment-1513083283
- Branch
- PR
> PlutusV3 will be in Conway which is PV 9

- plutus-core/plutus-ir/src/PlutusIR/Transform/Inline/Inline.hs
- plutus-core/plutus-ir/src/PlutusIR/Transform/Inline/Utils.hs
> Add a note about global uniqueness in the inliner

- plutus-conformance/agda/Spec.hs
- plutus-conformance/test-cases/uplc/evaluation/term/case/case-3/case-3.uplc
- plutus-conformance/test-cases/uplc/evaluation/term/case/case-8/case-8.uplc
- plutus-conformance/test-cases/uplc/evaluation/term/case/case-8/case-8.uplc.expected
- plutus-conformance/test-cases/uplc/evaluation/term/constr/constr-5/constr-5.uplc
- plutus-conformance/test-cases/uplc/evaluation/term/constr/constr-5/constr-5.uplc.expected
- plutus-core/plutus-core/src/PlutusCore/Check/Normal.hs
- plutus-core/plutus-core/src/PlutusCore/DeBruijn.hs
- plutus-core/plutus-core/test/Spec.hs
- plutus-core/untyped-plutus-core/src/UntypedPlutusCore/Evaluation/Machine/Cek/Internal.hs
- plutus-core/untyped-plutus-core/test/Generators.hs
> Address some comments on SOPs

- plutus-conformance/agda/Spec.hs
- plutus-conformance/test-cases/uplc/evaluation/term/case/case-9/case-9.uplc
- plutus-conformance/test-cases/uplc/evaluation/term/case/case-9/case-9.uplc.expected
- plutus-core/plutus-core/src/PlutusCore/Evaluation/Machine/Exception.hs
- plutus-core/untyped-plutus-core/src/UntypedPlutusCore/Evaluation/Machine/Cek/Internal.hs
- plutus-core/untyped-plutus-core/test/Evaluation/Golden/caseNonTag.plc.golden
- plutus-core/untyped-plutus-core/test/Evaluation/Golden/caseNonTag.uplc.golden
> Small fixes after my review of SOP

- plutus-core/plutus-ir/src/PlutusIR/Compiler/Let.hs
I don't even remember why I wrote that NOTE. `foldrM` is in base for a loooong time
> A small code refactor to use foldrM

- flake.lock
- nix/cells/plutus/library/make-plutus-project.nix
> Bump iohk-nix and remove now-unneeded hack

- plutus-core/plutus-core/src/PlutusCore/Core/Instance/Pretty/Readable.hs
- prettyprinter-configurable/src/Text/PrettyBy/Fixity.hs
- prettyprinter-configurable/src/Text/PrettyBy/Internal.hs
- prettyprinter-configurable/src/Text/PrettyBy/Monad.hs
I thought I'll reduce some noise while I came across these files.
- Branch
- PR
> Fix some line lengths and remove a few redundunt pragmas

- nix/cells/automation/ciJobs.nix
- plutus-core/untyped-plutus-core/src/UntypedPlutusCore/Evaluation/Machine/SteppableCek/DebugDriver.hs
- Build haddock in CI
- Fix haddock in DebugDriver under 8.10
- Branch
- PR
> Build all haddock in CI

- plutus-conformance/agda/Spec.hs
- plutus-metatheory/plutus-metatheory.cabal
- plutus-metatheory/src/RawU.lagda.md
- plutus-metatheory/src/Untyped.hs
- plutus-metatheory/src/Untyped.lagda.md
- plutus-metatheory/src/Untyped/CEK.lagda.md
- plutus-metatheory/src/Untyped/RenamingSubstitution.lagda.md
Implemented Sum of products for `plc-agda`'s UPLC.
All tests in the conformance test pass.
- Branch
- PR
> PLT-1030 Implemented SOPs for UPLC

- plutus-tx-plugin/src/PlutusTx/Plugin.hs
We learned something about the `sm_pre_inline` that was surprising from #5280. I've included what we learned in the note.
Also I fixed the line lengths of this module.
- Branch
- PR
> Update note of `sm_pre_inline`.

- plutus-core/plutus-core/src/PlutusCore/TypeCheck/Internal.hs
- plutus-core/plutus-ir/src/PlutusIR/TypeCheck/Internal.hs
> Address some comments

- plutus-tx-plugin/test/Lib.hs
- plutus-tx-plugin/test/Plugin/Data/Spec.hs
- plutus-tx-plugin/test/Plugin/Data/recursive/interListConstruct.tplc.golden
- plutus-tx-plugin/test/Plugin/Data/recursive/processInterListEval.ueval.golden
- plutus-tx/testlib/PlutusTx/Test.hs
This adds a test showing how compilation of a value of a non-regular data type to TPLC looks like.
> [PlutusTx] [Test] Add 'InterList'

- marlowe-cardano-minimal/app/Benchmark/Marlowe.hs
- marlowe-cardano-minimal/app/Benchmark/Marlowe/RolePayout.hs
- marlowe-cardano-minimal/app/Benchmark/Marlowe/Types.hs
- marlowe-cardano-minimal/app/Benchmark/Marlowe/Util.hs
- marlowe-cardano-minimal/app/Main.hs
- marlowe-cardano-minimal/marlowe-cardano-minimal.cabal
- marlowe-cardano-minimal/src/Language/Marlowe/Core/V1/Semantics.hs
- marlowe-cardano-minimal/src/Language/Marlowe/Core/V1/Semantics/Types.hs
- marlowe-cardano-minimal/src/Language/Marlowe/Scripts.hs
This adds a working benchmark that computes the execution cost of Marlowe's role-payout validator and compares it to the execution cost of the production version of that validator.
- Branch
- PR
> PLT-5596 Benchmark for Marlowe's role-payout validator.

- STYLEGUIDE.adoc
> Update style guide regarding indentation and type signature

- plutus-core/plutus-core/src/PlutusCore/Evaluation/Machine/CostModelInterface.hs
This is related to: https://github.com/input-output-hk/cardano-node/pull/5197
- Branch
- PR
> Add Data instance for CostModelApplyError for easier testing

- cabal.project
- flake.lock
> hex-text got updated on Hackage

- scripts/run-longitudinal-benchmarks.sh
> Try to fix the longitudinal benchmarking job

- CONTRIBUTING.adoc
- doc/read-the-docs-site/plutus-doc.cabal
- plutus-benchmark/ed25519-throughput/Main.hs
- plutus-benchmark/nofib/src/PlutusBenchmark/NoFib/LastPiece.hs
- plutus-benchmark/plutus-benchmark.cabal
- plutus-benchmark/script-contexts/src/PlutusBenchmark/ScriptContexts.hs
- plutus-core/changelog.d/20230518_105650_michael.peyton-jones_plugin_9_6.md
- plutus-ledger-api/changelog.d/20230518_105719_michael.peyton-jones_plugin_9_6.md
- plutus-tx-plugin/changelog.d/20230518_105617_michael.peyton-jones_plugin_9_6.md
- plutus-tx-plugin/plutus-tx-plugin.cabal
- plutus-tx-plugin/src/PlutusTx/Compiler/Expr.hs
- plutus-tx-plugin/src/PlutusTx/Compiler/Expr.hs-boot
- plutus-tx-plugin/src/PlutusTx/Compiler/Kind.hs
- plutus-tx-plugin/src/PlutusTx/Compiler/Type.hs
- plutus-tx-plugin/src/PlutusTx/Plugin.hs
- plutus-tx-plugin/test/Budget/Spec.hs
- plutus-tx-plugin/test/Plugin/Data/Spec.hs
- plutus-tx/changelog.d/20230518_105705_michael.peyton-jones_plugin_9_6.md
Amazingly, it builds fine and the tests all pass!
- Branch
- PR
> Support GHC 9.6 in the plugin

- cabal.project
- nix/cells/plutus/library/make-plutus-project.nix
- plutus-core/plutus-core.cabal
- Move some conditionals from Nix to cabal files
- Make cross-compiling conditional clearer
- Remove unnecessary flag setting
- Remove an unneeded sha256map entry
- Extend a note
- Delete some more unnecessary things
- Simplifiy Werror-ing
- Misc tidying
- Branch
- PR
> Misc tidying

- cabal.project
- flake.lock
- plutus-core/plutus-core.cabal
> Bump inline-r and remove s-r-p

- .github/workflows/longitudinal-benchmark.yml
This benchmark is actually very long and not as interesting as the
others.
- Branch
- PR
> Remove the lists benchmark from the longitudinal benchmarks

- cabal.project
- plutus-core/plutus-core.cabal
- plutus-core/plutus-core/src/GHC/Natural/Extras.hs
- plutus-core/plutus-core/src/PlutusCore/Default/Builtins.hs
- plutus-core/plutus-core/src/PlutusCore/Default/Universe.hs
- plutus-core/plutus-core/src/PlutusCore/Flat.hs
> PLT-6006: Purge the use of int-cast lib

- plutus-ledger-api/src/PlutusLedgerApi/V1/Crypto.hs
- plutus-ledger-api/src/PlutusLedgerApi/V1/Scripts.hs
- plutus-ledger-api/src/PlutusLedgerApi/V1/Tx.hs
- plutus-ledger-api/src/PlutusLedgerApi/V1/Value.hs
> Fix hash types documentation & spec links

- plutus-core/untyped-plutus-core/test/Transform/caseOfCase1.plc.golden
- plutus-core/untyped-plutus-core/test/Transform/caseOfCase2.plc.golden
- plutus-core/untyped-plutus-core/test/Transform/caseOfCase3.plc.golden
> plutus-core: Remove some dead golden files

- doc/read-the-docs-site/RELEASE.adoc
Sorry for the multiple PRs. I hit merge too soon last time.
- Branch
- PR
> Remove outdated info and fix alignment in Release.adoc

- plutus-ledger-api/src/PlutusLedgerApi/Common/Eval.hs
- plutus-ledger-api/src/PlutusLedgerApi/Common/SerialisedScript.hs
- plutus-ledger-api/test/Spec/Versions.hs
This moved a check from phase 2 to phase 1, which we can't do.
> Revert mistaken change

- plutus-benchmark/marlowe/bench/Bench.hs
- plutus-benchmark/marlowe/src/PlutusBenchmark/Marlowe/Core/V1/Semantics.hs
- plutus-benchmark/marlowe/src/PlutusBenchmark/Marlowe/Core/V1/Semantics/Types.hs
- plutus-benchmark/marlowe/src/PlutusBenchmark/Marlowe/Scripts.hs
- plutus-benchmark/marlowe/src/PlutusBenchmark/Marlowe/Scripts/RolePayout.hs
- plutus-benchmark/marlowe/src/PlutusBenchmark/Marlowe/Scripts/Semantics.hs
This should fix the problem of the role payout benchmarks having bad names, as [promised](https://github.com/input-output-hk/plutus/pull/5421#issuecomment-1636000977).
- Branch
- PR
> Fix rolepayout benchmarks.

- plutus-core/plutus-ir/src/PlutusIR/Compiler/Datatype.hs
> Address more comments on the SOPs in PIR

- README.adoc
> Fix doc links for another hydra move

- plutus-core/plutus-core/test/TypeSynthesis/Golden/Blake2b_224.plc.golden
- plutus-core/plutus-core/test/TypeSynthesis/Golden/Keccak_256.plc.golden
Forgot golden files for types of new builtins.  This probably doesn't need to be reviewed.
> Add missing golden files

- doc/read-the-docs-site/requirements.txt
As suggested by Dependant https://github.com/input-output-hk/plutus/security/dependabot/5
> Update certifi in ./doc/read-the-docs-site/requirements.txt

- flake.lock
- flake.nix
> Bump HLS to 2.0.0.1

- plutus-tx/src/PlutusTx/IsData/TH.hs
Addresses https://github.com/input-output-hk/plutus/pull/5442#pullrequestreview-1558923030
> Add Notes in `PlutusTx.IsData.TH` (PLT-5830)

- doc/read-the-docs-site/conf.py
fix 404 when "Edit on Github" button
- Branch
- PR
> Fix read-the-docs "Edit on Github" button

- cabal.project
- flake.lock
- nix/cells/plutus/devshells/plutus-shell-810.nix
- nix/cells/plutus/devshells/plutus-shell-92.nix
- nix/cells/plutus/devshells/plutus-shell-96.nix
- nix/cells/plutus/library/ghc-compiler-nix-name.nix
- nix/cells/plutus/library/make-plutus-project.nix
- nix/cells/plutus/library/plutus-project-810.nix
- nix/cells/plutus/library/plutus-project-92.nix
- nix/cells/plutus/library/plutus-project-96.nix
- nix/cells/plutus/packages/cabal-fmt.nix
- plutus-benchmark/plutus-benchmark.cabal
- plutus-conformance/plutus-conformance.cabal
- plutus-core/plutus-core.cabal
- plutus-ledger-api/plutus-ledger-api.cabal
- plutus-tx-plugin/plutus-tx-plugin.cabal
- plutus-tx/plutus-tx.cabal
- prettyprinter-configurable/prettyprinter-configurable.cabal
Using some new stuff in haskell.nix. Also bump everything.
> Simplify GHC version specification

- plutus-tx/src/PlutusTx/Lift/TH.hs
This appeases core lint on `PlutusTx.Lift.TH`. Hopefully it will prevent some weird errors from happening.
The core lint error was caused by the fact that in `liftExprs' = $$(TH.liftSplice $ tyListE liftExprs)`, `tyListE liftExprs` has the wrong type (it should have an impredicative type, but GHC inferred a non-impredicative type where `fun` is not in scope).
> Add one more impredicativity wrapper in PlutusTx.Lift.TH

- doc/read-the-docs-site/plutus-doc.cabal
- plutus-benchmark/plutus-benchmark.cabal
- plutus-conformance/plutus-conformance.cabal
- plutus-core/CHANGELOG.md
- plutus-core/changelog.d/20230811_174522_michael.peyton-jones_strictify_bindings.md
- plutus-core/plutus-core.cabal
- plutus-ledger-api/CHANGELOG.md
- plutus-ledger-api/changelog.d/20230801_162016_unsafeFixIO_1694.md
- plutus-ledger-api/changelog.d/20230808_144833_bezirg_cborfailureinterp.md
- plutus-ledger-api/changelog.d/20230816_201835_unsafeFixIO_sc_v3.md
- plutus-ledger-api/plutus-ledger-api.cabal
- plutus-metatheory/plutus-metatheory.cabal
- plutus-tx-plugin/CHANGELOG.md
- plutus-tx-plugin/changelog.d/20230818_143912_unsafeFixIO_debug_trace.md
- plutus-tx-plugin/changelog.d/20230821_154745_michael.peyton-jones_exponential_default_bodies.md
- plutus-tx-plugin/plutus-tx-plugin.cabal
- plutus-tx/plutus-tx.cabal
- prettyprinter-configurable/prettyprinter-configurable.cabal
> [Release] 1.11.0.0

- plutus-benchmark/nofib/test/Spec.hs
- plutus-benchmark/nofib/test/formulaBudget.pir-readable.golden
- plutus-benchmark/nofib/test/knightsBudget.pir-readable.golden
- plutus-benchmark/script-contexts/test/Spec.hs
- plutus-benchmark/script-contexts/test/checkScriptContext1.pir-readable.golden
- plutus-benchmark/script-contexts/test/checkScriptContext2.pir-readable.golden
This makes it easier to investigate when the sizes increase.
> Add a few more golden PIR tests

- plutus-core/plutus-ir/src/PlutusIR/Compiler/Let.hs
- plutus-core/plutus-ir/test/errors/recursiveTypeBind.golden
I was just adding this to investigate this error, we might as well keep the work.
- Branch
- PR
> Improve an error message of the compiler.

- plutus-tx-plugin/test/Plugin/Patterns/9.2/psym1.pir-readable.golden
- plutus-tx-plugin/test/Plugin/Patterns/9.2/psymRec.pir-readable.golden
- plutus-tx-plugin/test/Plugin/Patterns/9.6/psym1.pir-readable.golden
- plutus-tx-plugin/test/Plugin/Patterns/9.6/psymRec.pir-readable.golden
> Fix semantic merge conflict in test output

- plutus-ledger-api/changelog.d/20230904_141042_bezirg_fix_1_11.md
- plutus-ledger-api/src/PlutusLedgerApi/V3.hs
- plutus-tx/changelog.d/20230904_141050_bezirg_fix_1_11.md
- plutus-tx/src/PlutusTx/Builtins/Internal.hs
- plutus-tx/src/PlutusTx/Ratio.hs
> Fix for integration of cardano-ledger with plutus-1.11

- plutus-tx-plugin/test/StdLib/Spec.hs
Same problem as `testOrd` (https://github.com/input-output-hk/plutus/pull/5503)
> Fix testReduce

- plutus-tx-plugin/test/IsData/Spec.hs
- plutus-tx/src/PlutusTx/AsData.hs
This is much more ergonomic, and not much more nonsensical.
> AsData: transfer deriving clauses from the quoted declaration

- plutus-benchmark/marlowe/src/PlutusBenchmark/Marlowe/BenchUtil.hs
- plutus-benchmark/validation/BenchDec.hs
- plutus-benchmark/validation/BenchFull.hs
- plutus-ledger-api/changelog.d/20230915_103539_unsafeFixIO_major.md
- plutus-ledger-api/src/PlutusLedgerApi/Common.hs
- plutus-ledger-api/src/PlutusLedgerApi/Common/Eval.hs
- plutus-ledger-api/src/PlutusLedgerApi/Common/ProtocolVersions.hs
- plutus-ledger-api/src/PlutusLedgerApi/Common/SerialisedScript.hs
- plutus-ledger-api/src/PlutusLedgerApi/Common/Versions.hs
- plutus-ledger-api/src/PlutusLedgerApi/V1.hs
- plutus-ledger-api/src/PlutusLedgerApi/V2.hs
- plutus-ledger-api/src/PlutusLedgerApi/V3.hs
- plutus-ledger-api/test/Spec/Eval.hs
- plutus-ledger-api/test/Spec/Versions.hs
- plutus-ledger-api/testlib/PlutusLedgerApi/Test/EvaluationEvent.hs
See https://github.com/input-output-hk/plutus/pull/5538#discussion_r1327199658
> Replace ProtocolVersion with MajorProtocolVersion

- doc/read-the-docs-site/howtos/profiling-scripts.rst
> Add link to speedscope

- CONTRIBUTING.adoc
> Add testing section to CONTRIBUTING

- plutus-core/changelog.d/20231004_183608_bezirg_debug_multi.md
- plutus-core/changelog.d/20231006_150526_bezirg_dbg_emit.md
- plutus-core/executables/debugger/Event.hs
- plutus-core/executables/debugger/Main.hs
- plutus-core/executables/debugger/Types.hs
- plutus-core/executables/uplc/Main.hs
- plutus-core/plutus-core.cabal
- plutus-core/prelude/PlutusPrelude.hs
- plutus-core/untyped-plutus-core/src/UntypedPlutusCore/Evaluation/Machine/Cek/Internal.hs
- plutus-core/untyped-plutus-core/src/UntypedPlutusCore/Evaluation/Machine/SteppableCek/DebugDriver.hs
- plutus-core/untyped-plutus-core/src/UntypedPlutusCore/Evaluation/Machine/SteppableCek/Internal.hs
- plutus-core/untyped-plutus-core/test/Evaluation/Debug.hs
>  PLT-6543: Implement emitter tracing for debugger

- doc/read-the-docs-site/plutus-doc.cabal
- plutus-benchmark/plutus-benchmark.cabal
- plutus-conformance/plutus-conformance.cabal
- plutus-core/CHANGELOG.md
- plutus-core/changelog.d/20230921_180423_michael.peyton-jones_case_of_case.md
- plutus-core/changelog.d/20230928_102703_marty.stumpf_plt_1398_pir_typechecking_tests.md
- plutus-core/changelog.d/20231004_183608_bezirg_debug_multi.md
- plutus-core/changelog.d/20231006_150526_bezirg_dbg_emit.md
- plutus-core/plutus-core.cabal
- plutus-ledger-api/plutus-ledger-api.cabal
- plutus-metatheory/plutus-metatheory.cabal
- plutus-tx-plugin/plutus-tx-plugin.cabal
- plutus-tx/plutus-tx.cabal
- prettyprinter-configurable/prettyprinter-configurable.cabal
> Release 1.15.0

- plutus-tx-plugin/test/StdLib/Spec.hs
This fixes the `tryHard` bug subverting our CI and adds some code to make sure such bugs are triggered early if something breaks again.
> [Test] [Bug] Make 'tryHard' lazy again

- plutus-metatheory/src/Algorithmic/Erasure.lagda
- plutus-metatheory/src/Algorithmic/Erasure/RenamingSubstitution.lagda
- plutus-metatheory/src/Scoped/Extrication/RenamingSubstitution.lagda
- plutus-metatheory/src/Scoped/RenamingSubstitution.lagda
- plutus-metatheory/src/index.lagda.md
> PLT-7103 Adapt Scoped Renaming/Substitution and Extrication to SOPs in the metatheory

- plutus-metatheory/src/Algorithmic.lagda
- plutus-metatheory/src/Algorithmic/Reduction.lagda
- plutus-metatheory/src/Utils/List.lagda.md
- plutus-metatheory/src/index.lagda.md
> PLT-8103 Adapt Reduction proof to SOPs

- .github/workflows/haddock.yml
This attempts to fix  https://github.com/input-output-hk/plutus/actions/runs/6720177307/job/18263190343
> Remove nix version constraint in workflows/haddock.yml

- plutus-core/plutus-core/src/PlutusCore/Evaluation/Machine/CostModelInterface.hs
- plutus-ledger-api/src/PlutusLedgerApi/V1.hs
> Expose 'unSatInt' and 'fromSatInt' and add instances for 'CostModelApplyError'

- doc/read-the-docs-site/plutus-doc.cabal
- plutus-benchmark/plutus-benchmark.cabal
- plutus-conformance/plutus-conformance.cabal
- plutus-core/CHANGELOG.md
- plutus-core/changelog.d/20231027_133344_bezirg_pir_rewrite.md
- plutus-core/changelog.d/20231101_201807_bezirg_rewrite_more.md
- plutus-core/changelog.d/20231103_205517_effectfully_remove_dependent_sum_template.md
- plutus-core/plutus-core.cabal
- plutus-ledger-api/CHANGELOG.md
- plutus-ledger-api/changelog.d/20231010_053352_effectfully_experiment_with_MatchUnclear_and_tildas.md
- plutus-ledger-api/plutus-ledger-api.cabal
- plutus-metatheory/plutus-metatheory.cabal
- plutus-tx-plugin/plutus-tx-plugin.cabal
- plutus-tx/plutus-tx.cabal
- prettyprinter-configurable/prettyprinter-configurable.cabal
Updates for `plutus-16.0.0.0` (PLT-8179).
> Release 1.16.0.0

- plutus-metatheory/src/Cost.lagda.md
- plutus-metatheory/src/Untyped/CEK.lagda.md
- plutus-metatheory/src/Untyped/CEKWithCost.lagda.md
- plutus-metatheory/src/Utils.lagda
This PRs adds the basic definitions for costs, and a CEK machine for UPLC that computes costs.
- Branch
- PR
> PLT-1565 Add support for cost in the metatheory untyped CEK machine 

- doc/read-the-docs-site/plutus-doc.cabal
- plutus-benchmark/plutus-benchmark.cabal
- plutus-conformance/plutus-conformance.cabal
- plutus-core/CHANGELOG.md
- plutus-core/changelog.d/20231111_160632_unsafeFixIO_hash.md
- plutus-core/plutus-core.cabal
- plutus-ledger-api/CHANGELOG.md
- plutus-ledger-api/changelog.d/20231109_213954_effectfully_expose_fromSatInt_and_add_some_instances.md
- plutus-ledger-api/plutus-ledger-api.cabal
- plutus-metatheory/plutus-metatheory.cabal
- plutus-tx-plugin/plutus-tx-plugin.cabal
- plutus-tx/CHANGELOG.md
- plutus-tx/changelog.d/20231117_104859_michael.peyton-jones_more_efficient_unpacking.md
- plutus-tx/plutus-tx.cabal
- prettyprinter-configurable/prettyprinter-configurable.cabal
> Release 1.17.0.0

- doc/read-the-docs-site/plutus-doc.cabal
- plutus-benchmark/plutus-benchmark.cabal
- plutus-ledger-api/plutus-ledger-api.cabal
- plutus-tx-plugin/plutus-tx-plugin.cabal
> Fix buildability conditionals

- plutus-metatheory/plutus-metatheory.cabal
- plutus-metatheory/src/Builtin.lagda.md
- plutus-metatheory/src/Cost.lagda.md
- plutus-metatheory/src/Main.lagda
- plutus-metatheory/src/Opts.hs
- plutus-metatheory/src/Raw.hs
- plutus-metatheory/src/Untyped/CEK.lagda.md
- plutus-metatheory/src/Untyped/CEKWithCost.lagda.md
- plutus-metatheory/src/Utils/Reflection.lagda.md
Adds options `--counting` and `--tallying` for Untyped PLutus Core (--mode U).
> PLT-1567 Extend agda executable to handle costing reporting features

- plutus-core/plutus-ir/test/PlutusIR/Transform/Inline/Tests.hs
- plutus-core/plutus-ir/test/PlutusIR/Transform/Inline/multilet
- plutus-core/plutus-ir/test/PlutusIR/Transform/Inline/multilet.golden
The inliner currently does the wrong thing.
> Add a multilet test case for the PIR inliner

- plutus-core/untyped-plutus-core/test/Evaluation/Builtins/Definition.hs
Just testing that the costing machinery can handle even the impossible objects.
> [Test] [Costing] Test that serialising an impossible 'Data' object finishes

- doc/papers/system-f-in-agda/paper.lagda
> add missing word

- doc/read-the-docs-site/plutus-doc.cabal
- plutus-benchmark/plutus-benchmark.cabal
- plutus-conformance/plutus-conformance.cabal
- plutus-core/CHANGELOG.md
- plutus-core/changelog.d/20240117_230746_effectfully_expose_BuiltinResult.md
- plutus-core/plutus-core.cabal
- plutus-ledger-api/plutus-ledger-api.cabal
- plutus-metatheory/plutus-metatheory.cabal
- plutus-tx-plugin/plutus-tx-plugin.cabal
- plutus-tx/plutus-tx.cabal
- prettyprinter-configurable/prettyprinter-configurable.cabal
> Release 1.21.0.0

- plutus-metatheory/plutus-metatheory.cabal
- plutus-metatheory/src/Cost.lagda.md
- plutus-metatheory/src/Cost/Base.lagda.md
- plutus-metatheory/src/Cost/Model.lagda.md
- plutus-metatheory/src/Cost/Size.lagda.md
- plutus-metatheory/src/Untyped/CEKWithCost.lagda.md
> PLT-9372  Extend Agda costing infrastructure to accommodate `integerToByteString`

- plutus-core/testlib/PlutusCore/Generators/QuickCheck/Builtin.hs
- plutus-core/testlib/PlutusIR/Generators/QuickCheck/ShrinkTerms.hs
- plutus-core/testlib/PlutusIR/Pass/Test.hs
This improves term shrinking a bit and adds shrinking to a test.
> [Test] Improve term shrinking

- doc/read-the-docs-site/quick-start.rst
- doc/read-the-docs-site/tutorials/QuickStart.hs
> Minor documentation fixes

- plutus-core/plutus-core/src/PlutusCore/TypeCheck/Internal.hs
- plutus-core/plutus-core/test/type-errors/constrTooFew.plc
- plutus-core/plutus-core/test/type-errors/constrTooFew.plc.golden
- plutus-core/plutus-core/test/type-errors/constrTooMany.plc
- plutus-core/plutus-core/test/type-errors/constrTooMany.plc.golden
- plutus-core/prelude/PlutusPrelude.hs
This fixes the bug and adds a simple golden test for it, I want to have a better testing strategy, I'll create an issue about it, but for now let's just fix the bug.
> [Bug] [TypeCheck] Fix an off-by-maxBound error

- .github/ISSUE_TEMPLATE/config.yml
> Remove ISSUE_TEMPLATE/config.yml

- plutus-ledger-api/src/PlutusLedgerApi/V1/Value.hs
- plutus-tx/src/PlutusTx/AssocMap.hs
> Add Note [Optimising Value]

- plutus-core/cost-model/budgeting-bench/Benchmarks/Nops.hs
- plutus-core/plutus-core.cabal
- plutus-core/plutus-core/src/Data/Aeson/THReader.hs
- plutus-core/plutus-core/src/PlutusCore/Default/Builtins.hs
- plutus-core/plutus-core/src/PlutusCore/Evaluation/Machine/BuiltinCostModel.hs
- plutus-core/plutus-core/src/PlutusCore/Evaluation/Machine/ExBudget.hs
- plutus-core/prelude/PlutusPrelude.hs
- plutus-core/untyped-plutus-core/src/UntypedPlutusCore/Evaluation/Machine/Cek/CekMachineCosts.hs
- plutus-tx/src/PlutusTx/AssocMap.hs
> Changes needed for constitution

- plutus-core/plutus-ir/src/PlutusIR/Transform/Inline/Utils.hs
Adding @michaelpj 's comment from https://github.com/IntersectMBO/plutus/pull/5766/files/581699a2fdbdbf1730a483d91f41b05be4c1366d#r1494395447.
- Branch
- PR
> Add note on constant inlining

- plutus-ledger-api/src/PlutusLedgerApi/V3/Contexts.hs
> Document some variants for Plutus V3 ScriptContext

- doc/read-the-docs-site/plutus-doc.cabal
- plutus-benchmark/plutus-benchmark.cabal
- plutus-conformance/plutus-conformance.cabal
- plutus-core/CHANGELOG.md
- plutus-core/changelog.d/20240119_113221_kenneth.mackenzie_bitwise_costing.md
- plutus-core/plutus-core.cabal
- plutus-ledger-api/CHANGELOG.md
- plutus-ledger-api/changelog.d/20240119_113712_kenneth.mackenzie_bitwise_costing.md
- plutus-ledger-api/changelog.d/20240202_125923_Yuriy.Lazaryev_PLT_9420_TxId_constructor.md
- plutus-ledger-api/changelog.d/20240218_090310_unsafeFixIO_currencySymbolValueOf.md
- plutus-ledger-api/plutus-ledger-api.cabal
- plutus-metatheory/plutus-metatheory.cabal
- plutus-tx-plugin/CHANGELOG.md
- plutus-tx-plugin/changelog.d/20240119_114204_kenneth.mackenzie_bitwise_costing.md
- plutus-tx-plugin/changelog.d/20240213_184621_ana.pantilie95_plt_8176_inline_constants_pir.md
- plutus-tx-plugin/plutus-tx-plugin.cabal
- plutus-tx/CHANGELOG.md
- plutus-tx/changelog.d/20240119_114032_kenneth.mackenzie_bitwise_costing.md
- plutus-tx/changelog.d/20240201_123929_Yuriy.Lazaryev_PLT_9395_ratio_negative_denominator.md
- plutus-tx/plutus-tx.cabal
- prettyprinter-configurable/prettyprinter-configurable.cabal
As per instructions in the RELEASE.adoc
> [Release] 1.22.0.0

- plutus-core/untyped-plutus-core/src/UntypedPlutusCore/Transform/Inline.hs
Fixes this failure https://github.com/IntersectMBO/cardano-haskell-packages/actions/runs/8004482180/job/21862427753
> fix: another haddock parse error in GHC 8.10

- plutus-tx/src/PlutusTx/AssocMap.hs
> Some docs on AssocMap

- doc/read-the-docs-site/simple-example.rst
> Fixing typo in new caution message - simple-example.rst

- plutus-core/plutus-core.cabal
- plutus-ledger-api/plutus-ledger-api.cabal
- plutus-tx-plugin/plutus-tx-plugin.cabal
- plutus-tx/plutus-tx.cabal
- prettyprinter-configurable/prettyprinter-configurable.cabal
> 1.22.0.0 -> 1.22.1.0

- doc/read-the-docs-site/plutus-doc.cabal
- plutus-benchmark/plutus-benchmark.cabal
- plutus-conformance/plutus-conformance.cabal
- plutus-core/plutus-core.cabal
- plutus-ledger-api/plutus-ledger-api.cabal
- plutus-metatheory/plutus-metatheory.cabal
- plutus-tx-plugin/plutus-tx-plugin.cabal
- plutus-tx/plutus-tx.cabal
- prettyprinter-configurable/prettyprinter-configurable.cabal
Closed the previous PR/branch because as pointed out by @michaelpj I messed up the naming scheme :see_no_evil: . Sorry for the review spam!
- Branch
- PR
> [Release] 1.23.0.0

- doc/read-the-docs-site/howtos/asdata.rst
- doc/read-the-docs-site/howtos/index.rst
- doc/read-the-docs-site/tutorials/AuctionValidator.hs
This adds a basic howto guide showing how to use it and discussing what it does.
> Add documentation for AsData

- doc/read-the-docs-site/plutus-doc.cabal
- plutus-benchmark/plutus-benchmark.cabal
- plutus-conformance/plutus-conformance.cabal
- plutus-core/plutus-core.cabal
- plutus-ledger-api/plutus-ledger-api.cabal
- plutus-metatheory/plutus-metatheory.cabal
- plutus-tx-plugin/plutus-tx-plugin.cabal
- plutus-tx/CHANGELOG.md
- plutus-tx/changelog.d/20240315_151519_ana.pantilie95_plt_9511_audit_assocmap.md
- plutus-tx/plutus-tx.cabal
- prettyprinter-configurable/prettyprinter-configurable.cabal
> [Release] 1.24.0.0

- doc/docs-revamp/dev-onboarding-quick-setup.md
The changes here reflect feedback from Marshall on March 26, 2024, during our review discussion of this page.
> Incorporating-feedback_dev-onboarding-quick-setup.md

- README.adoc
Also remove the CEH badge as it's been superseded by Intersect policy.
> Add a matrix badge linking to our room

- scripts/check-Notes.awk
- scripts/check-Notes.sh
This just makes some minor changes to improve the output of the `check-Notes.sh` script.  I'll set it to auto-merge.
> Improve formatting of output of check-Notes

- doc/read-the-docs-site/plutus-doc.cabal
- plutus-benchmark/plutus-benchmark.cabal
- plutus-conformance/plutus-conformance.cabal
- plutus-core/CHANGELOG.md
- plutus-core/changelog.d/20240326_133744_Yuriy.Lazaryev_term_eval_order_builtin.md
- plutus-core/plutus-core.cabal
- plutus-ledger-api/plutus-ledger-api.cabal
- plutus-metatheory/plutus-metatheory.cabal
- plutus-tx-plugin/CHANGELOG.md
- plutus-tx-plugin/changelog.d/20240402_143807_Yuriy.Lazaryev_short_circuit_and_or.md
- plutus-tx-plugin/plutus-tx-plugin.cabal
- plutus-tx/plutus-tx.cabal
- prettyprinter-configurable/prettyprinter-configurable.cabal
> Release 1.25.0.0

- plutus-core/plutus-ir/src/PlutusIR/Compiler.hs
- plutus-core/plutus-ir/src/PlutusIR/Compiler/Types.hs
- plutus-core/plutus-ir/src/PlutusIR/Transform/DeadCode.hs
- plutus-tx-plugin/changelog.d/20240412_150720_Yuriy.Lazaryev_fix_remove_dead_bindings_flag.md
- plutus-tx-plugin/src/PlutusTx/Plugin.hs
The flag was parsed but not taken into account (DCE pass was happening regardless of the flag).
> fix: flag `simplifier-remove-dead-bindings`

- plutus-tx/changelog.d/20240412_060219_unsafeFixIO_indexBuiltinList.md
- plutus-tx/src/PlutusTx/ErrorCodes.hs
- plutus-tx/src/PlutusTx/List.hs
Is this useful? Let me know what you think.
> Add PlutusTx.List.indexBuiltinList

- plutus-tx-plugin/test/AsData/Budget/Spec.hs
- plutus-tx-plugin/test/Plugin/Basic/Spec.hs
I plan to add more tests to the `Plugin.Basic.Spec` module, 
and before doing it I want to refactor the module such that:
> Chore: formatting

- plutus-core/changelog.d/20240520_192738_effectfully_remove_UnknownBuiltin.md
- plutus-core/plutus-core/src/PlutusCore/Error.hs
- plutus-core/plutus-core/src/PlutusCore/Evaluation/Machine/Exception.hs
Those constructors have been dead for ages.
> [Refactoring] Remove 'UnknownBuiltin'

- plutus-metatheory/src/VerifiedCompilation/UntypedViews.lagda.md
> Possible Fix for Ramsay View problem

- plutus-ledger-api/changelog.d/20240607_213432_ana.pantilie95_fix_scriptcontext_pretty.md
- plutus-ledger-api/src/PlutusLedgerApi/V3/Contexts.hs
> Add Redeemer to V3 ScriptContext Pretty instance

- .github/workflows/combined-haddock.yml
- .gitignore
- flake.lock
- flake.nix
- nix/outputs.nix
- plutus-benchmark/lists/src/PlutusBenchmark/Lists/Sort/MergeSort.hs
- scripts/combined-haddock.sh
This PR introduces a new workflow that builds the combined haddock (including internal libraries) for plutus and publishes it to the *haddock/master* and *haddock/release/X* folders in the `gh-pages` branch.
An initial version can be viewed [here](https://intersectmbo.github.io/plutus/haddock/good-haddock)
> Combined Haddock Generation

- docusaurus/docs/getting-started-plutus-tx.md
- docusaurus/docs/index.md
> MK-5422 move getting started page fixing link

- plutus-core/plutus-ir/src/PlutusIR/Pass.hs
Removes warnings about unused imports.
> plutus-ir: fix redundant imports

- plutus-ledger-api/src/PlutusLedgerApi/V1/Data/Value.hs
> Add documentation to `Data.Value`

- doc/docusaurus/README.md
Making a spelling correction in the README file.
> making a spelling correction on the doc/docusaurus README file

- plutus-metatheory/src/Utils.lagda.md
- plutus-metatheory/src/VerifiedCompilation/Equality.lagda.md
> Fix equality Agda <-> Haskell

- doc/docusaurus/docusaurus-examples.cabal
- doc/docusaurus/static/code/AuctionValidator.hs
- doc/docusaurus/static/code/BasicPlutusTx.hs
- doc/docusaurus/static/code/BasicPolicies.hs
- doc/docusaurus/static/code/BasicValidators.hs
The checks were removed during the RTD -> Docusaurus migration.
> Restore CI checks for doc site code

- cabal.project
- cardano-constitution/cardano-constitution.cabal
- doc/docusaurus/docusaurus-examples.cabal
- plutus-benchmark/plutus-benchmark.cabal
- plutus-conformance/plutus-conformance.cabal
- plutus-core/CHANGELOG.md
- plutus-core/changelog.d/20240711_030856_kenneth.mackenzie_bitwise_4.md
- plutus-core/changelog.d/20240726_102834_bezirg_ratinteger.md
- plutus-core/changelog.d/20240726_165736_Yuriy.Lazaryev_nothunks_0_2.md
- plutus-core/plutus-core.cabal
- plutus-ledger-api/plutus-ledger-api.cabal
- plutus-metatheory/plutus-metatheory.cabal
- plutus-tx-plugin/plutus-tx-plugin.cabal
- plutus-tx-test-util/plutus-tx-test-util.cabal
- plutus-tx/CHANGELOG.md
- plutus-tx/changelog.d/20240731_145553_effectfully_add_general_mkNil.md
- plutus-tx/plutus-tx.cabal
- prettyprinter-configurable/prettyprinter-configurable.cabal
Result of `./scripts/prepare-release.sh "1.32.0.0"`
> Release 1.32.0.0

- plutus-core/testlib/PlutusCore/Generators/Hedgehog/Denotation.hs
- plutus-core/testlib/PlutusCore/Generators/NEAT/Term.hs
> Some comments on deprecated tests

- plutus-tx-plugin/plutus-tx-plugin.cabal
- plutus-tx-plugin/src/PlutusTx/Options.hs
> Remove PyF from plutus-tx-plugin

- cardano-constitution/cardano-constitution.cabal
- doc/docusaurus/docusaurus-examples.cabal
- plutus-benchmark/plutus-benchmark.cabal
- plutus-conformance/plutus-conformance.cabal
- plutus-core/CHANGELOG.md
- plutus-core/changelog.d/20240726_124910_bezirg_modexp.md
- plutus-core/changelog.d/20240806_115314_kenneth.mackenzie.md
- plutus-core/plutus-core.cabal
- plutus-ledger-api/CHANGELOG.md
- plutus-ledger-api/changelog.d/20240716_124825_ana.pantilie95_data_value_ledger_api.md
- plutus-ledger-api/changelog.d/20240726_125029_bezirg_modexp.md
- plutus-ledger-api/changelog.d/20240806_115735_kenneth.mackenzie_ripemd_160.md
- plutus-ledger-api/plutus-ledger-api.cabal
- plutus-metatheory/plutus-metatheory.cabal
- plutus-tx-plugin/CHANGELOG.md
- plutus-tx-plugin/changelog.d/20240726_125023_bezirg_modexp.md
- plutus-tx-plugin/plutus-tx-plugin.cabal
- plutus-tx-test-util/plutus-tx-test-util.cabal
- plutus-tx/CHANGELOG.md
- plutus-tx/changelog.d/20240726_125008_bezirg_modexp.md
- plutus-tx/changelog.d/20240806_115427_kenneth.mackenzie.md
- plutus-tx/plutus-tx.cabal
- prettyprinter-configurable/prettyprinter-configurable.cabal
> Release 1.33.0.0

- plutus-ledger-api/src/PlutusLedgerApi/V3/ParamName.hs
> Remove Haddock from inside data declaration

- plutus-core/plutus-core.cabal
- plutus-ledger-api/plutus-ledger-api.cabal
- plutus-tx-plugin/plutus-tx-plugin.cabal
- plutus-tx/plutus-tx.cabal
- prettyprinter-configurable/prettyprinter-configurable.cabal
> Release 1.33.1.0

- plutus-ledger-api/src/PlutusLedgerApi/V3/Contexts.hs
It should be "Note that deposit is mandatory".
- Branch
- PR
> Fix documentation typo

- RELEASE.adoc
> Add packages to CHaP release docs

- cabal.project
- cardano-constitution/README.md
- cardano-constitution/cardano-constitution.cabal
- doc/docusaurus/docusaurus-examples.cabal
- plutus-benchmark/plutus-benchmark.cabal
- plutus-conformance/plutus-conformance.cabal
- plutus-core/CHANGELOG.md
- plutus-core/changelog.d/20240903_180833_effectfully_swap_structural_and_operational_errors.md
- plutus-core/plutus-core.cabal
- plutus-ledger-api/CHANGELOG.md
- plutus-ledger-api/changelog.d/20240708_134138_Yuriy.Lazaryev_has_schema_instances.md
- plutus-ledger-api/plutus-ledger-api.cabal
- plutus-metatheory/plutus-metatheory.cabal
- plutus-tx-plugin/CHANGELOG.md
- plutus-tx-plugin/changelog.d/20240906_143413_unsafeFixIO_evaluate_builtins.md
- plutus-tx-plugin/plutus-tx-plugin.cabal
- plutus-tx-test-util/plutus-tx-test-util.cabal
- plutus-tx/CHANGELOG.md
- plutus-tx/changelog.d/20240708_134238_Yuriy.Lazaryev_has_schema_instances.md
- plutus-tx/plutus-tx.cabal
- prettyprinter-configurable/prettyprinter-configurable.cabal
> Release 1.34.0.0

- scripts/ci-plutus-benchmark.sh
This is an experiment for #6441.
> Put the TOTAL line for a benchmark comparison in a table of its own

- plutus-core/plutus-core/src/PlutusCore/Default/Builtins.hs
- scripts/ci-plutus-benchmark.sh
Still trying to put the benchmark total change in a little table of its own...
> Try yet again

- doc/plutus-core-spec/cardano/versions.tex
> [spec] update conway info

- doc/docusaurus/docs/delve-deeper/languages.md
Addresses additional review comments on https://github.com/IntersectMBO/plutus/pull/6409
> Address review comments on "Overview of Languages Compiling to UPLC"

- plutus-core/plutus-core/test/TypeSynthesis/Golden/ExtensionFun/IntNoIntegerNoWord.plc.golden
> [Test] Check in a forgotten golden file

- plutus-core/CHANGELOG.md
- plutus-core/changelog.d/20240904_214017_ana.pantilie95_add_certification_component.md
- plutus-core/changelog.d/20240913_101059_kenneth.mackenzie.md
- plutus-core/plutus-core.cabal
- plutus-ledger-api/plutus-ledger-api.cabal
- plutus-tx-plugin/plutus-tx-plugin.cabal
- plutus-tx/plutus-tx.cabal
- prettyprinter-configurable/prettyprinter-configurable.cabal
Release 1.34.1.0: fixes bug in`findFirstSetBit` builtin.
> Release 1.34.1.0

- nix/shell.nix
- scripts/prepare-bins.sh
Fixes https://github.com/IntersectMBO/plutus/issues/6494
>  Remove use of `--pure` in `scripts/prepare-bins.sh`

- scripts/combined-haddock.sh
Haddock index page should have a <select> element allowing the user to select older plutus versions or master
> Add version select to haddock index page

- doc/docusaurus/docs/delve-deeper/languages.md
Adding some more content and arguments.
> Expand "Overview of Languages Compiling to UPLC"

- doc/TRIAGE.md
> [Meta] Add CIPs to 'TRIAGE.md'

- doc/docusaurus/docs/delve-deeper/encoding.md
- doc/docusaurus/docs/working-with-scripts/optimizing-scripts-with-asData.md
- doc/docusaurus/docs/working-with-scripts/other-optimization-techniques.md
- doc/docusaurus/docs/working-with-scripts/profiling-budget-usage.md
Made a few minor improvements including updating the outdated instructions.
Also moved the script optimization pages from "delve-deeper" to "working with scripts", since these are relevant even for basic users.
> Polish the profiling guide

- plutus-core/executables/plutus/AnyProgram/Compile.hs
- plutus-core/plutus-core.cabal
- plutus-core/plutus-core/src/PlutusCore/Compiler.hs
- plutus-core/plutus-core/src/PlutusCore/Compiler/Types.hs
- plutus-core/plutus-ir/test/PlutusIR/Transform/StrictLetRec/Tests/Lib.hs
- plutus-core/testlib/PlutusCore/Test.hs
- plutus-core/untyped-plutus-core/src/UntypedPlutusCore/Simplify.hs
- plutus-core/untyped-plutus-core/src/UntypedPlutusCore/Transform/CaseOfCase.hs
- plutus-core/untyped-plutus-core/src/UntypedPlutusCore/Transform/CaseReduce.hs
- plutus-core/untyped-plutus-core/src/UntypedPlutusCore/Transform/Cse.hs
- plutus-core/untyped-plutus-core/src/UntypedPlutusCore/Transform/FloatDelay.hs
- plutus-core/untyped-plutus-core/src/UntypedPlutusCore/Transform/ForceDelay.hs
- plutus-core/untyped-plutus-core/src/UntypedPlutusCore/Transform/Inline.hs
- plutus-core/untyped-plutus-core/src/UntypedPlutusCore/Transform/Simplifier.hs
- plutus-core/untyped-plutus-core/test/Transform/CaseOfCase/Test.hs
- plutus-core/untyped-plutus-core/test/Transform/Simplify/Lib.hs
- plutus-executables/executables/pir/Main.hs
- plutus-executables/executables/uplc/Main.hs
- plutus-metatheory/plutus-metatheory.cabal
- plutus-metatheory/src/VerifiedCompilation.lagda.md
- plutus-metatheory/src/VerifiedCompilation/UCaseOfCase.lagda.md
- plutus-tx-plugin/src/PlutusTx/Plugin.hs
- plutus-tx/src/PlutusTx/Lift.hs
This cleans up the UPLC tracing infrastructure as requested by @effectfully and also provides some "compilations hints" to the certifier in the form of simplification stage tags.
- Branch
- PR
> Add simplifier tags in UPLC simplifier

- plutus-ledger-api/src/PlutusLedgerApi/V1/Credential.hs
- plutus-ledger-api/src/PlutusLedgerApi/V1/DCert.hs
- plutus-ledger-api/src/PlutusLedgerApi/V1/Scripts.hs
This makes debugging by tracing easier.
> derive PlutusTx.Show for some ledger api types

- .github/workflows/slack-message-broker.yml
> Amends to slack-message-broker

- plutus-core/testlib/PlutusCore/Generators/QuickCheck/Builtin.hs
- plutus-core/untyped-plutus-core/test/Evaluation/Builtins/Definition.hs
This makes one of the distribution tests display more info about the distribution.
> [Test] Mark more 'Integer's as interesting

- cabal.project
- doc/docusaurus/static/code/BasicPlutusTx.hs
- nix/project.nix
- plutus-core/plutus-core/src/PlutusCore/Evaluation/Machine/Ck.hs
- plutus-tx/plutus-tx.cabal
- plutus-tx/src/PlutusTx/Prelude.hs
- prettyprinter-configurable/src/Text/PrettyBy/Internal.hs
Too high maintenance cost for too little value (it's causing https://github.com/IntersectMBO/plutus/issues/6625 too)
> Remove doctest across whole repo

- fourmolu.yaml
Closes https://github.com/IntersectMBO/plutus-private/issues/1239
> fourmolu.yaml

- plutus-core/executables/plutus/AnyProgram/Run.hs
- plutus-ledger-api/src/PlutusLedgerApi/Common/Eval.hs
> Fix build ambiguous use of `show` with `text-2.1.2`

- cabal.project
- flake.lock
> nix flake update

- plutus-core/CHANGELOG.md
- plutus-ledger-api/src/PlutusLedgerApi/Common/ProtocolVersions.hs
- plutus-ledger-api/src/PlutusLedgerApi/Common/Versions.hs
- plutus-ledger-api/src/PlutusLedgerApi/V3/ParamName.hs
> Update hard fork name

- doc/plutus-core-spec/cardano/builtins4.tex
- doc/plutus-core-spec/plutus-core-specification.tex
This should fix the problems pointed out in https://github.com/IntersectMBO/plutus/issues/6761.
Thanks to @nielstron for raising this.
> Fix issues from #6761

- doc/plutus-core-spec/cardano/builtins1.tex
This fixes a couple of small typos.
> Fix a couple of small typos

- cabal.project
- doc/notes/model/UTxO.hsproj/UTxO.cabal
- flake.lock
- plutus-core/plutus-core.cabal
- plutus-metatheory/plutus-metatheory.cabal
> Finalize switch from cryptonite to crypton

- doc/docusaurus/static/code/Example/Cip57/Blueprint/Main.hs
- doc/docusaurus/static/plutus.json
Closes https://github.com/IntersectMBO/plutus/issues/6164
> Update CIP-57 example to use AssocMap

- doc/docusaurus/docs/working-with-scripts/ledger-language-version.md
Reported by [Marius Georgescu](https://x.com/georgescumarius) on Twitter.
> [Docs] [Bug] Replace 'minting' with 'spending'

- plutus-tx/src/PlutusTx/IsData/TH.hs
> Use more TH quotations in PlutusTx.IsData.TH

- plutus-tx-plugin/test/List/Spec.hs
- plutus-tx/changelog.d/20250226_231916_ana.pantilie95_complete_data_list.md
- plutus-tx/src/PlutusTx/Data/List.hs
Part of #6804
This adds a part of the functions in PlutusTx.List to PlutusTx.Data.List as well. They are tested to be functionally equivalent.
> Add missing functions to Data.List (part 1)

- plutus-benchmark/marlowe/bench/BenchAgdaCek.hs
- plutus-benchmark/marlowe/bench/BenchCek.hs
- plutus-benchmark/marlowe/bench/Shared.hs
- plutus-benchmark/marlowe/exe/Main.hs
- plutus-benchmark/marlowe/exe/PlutusBenchmark/Marlowe/RolePayout.hs
- plutus-benchmark/marlowe/exe/PlutusBenchmark/Marlowe/Semantics.hs
- plutus-benchmark/marlowe/exe/PlutusBenchmark/Marlowe/Util.hs
- plutus-benchmark/marlowe/src/PlutusBenchmark/Marlowe/BenchUtil.hs
- plutus-benchmark/marlowe/src/PlutusBenchmark/Marlowe/Core/V1/Semantics.hs
- plutus-benchmark/marlowe/src/PlutusBenchmark/Marlowe/Core/V1/Semantics/Types.hs
- plutus-benchmark/marlowe/src/PlutusBenchmark/Marlowe/Core/V1/Semantics/Types/Address.hs
- plutus-benchmark/marlowe/src/PlutusBenchmark/Marlowe/Scripts/RolePayout.hs
- plutus-benchmark/marlowe/src/PlutusBenchmark/Marlowe/Scripts/Semantics.hs
- plutus-benchmark/marlowe/src/PlutusBenchmark/Marlowe/Types.hs
As I was reading this code I took the opportunity to also re-format it along the way.
> chore: reformat more marlowe code with fourmolu

- plutus-core/plutus-core/src/PlutusCore/Evaluation/Machine/Ck.hs
- plutus-core/plutus-core/src/PlutusCore/Evaluation/Machine/Exception.hs
- plutus-core/untyped-plutus-core/src/UntypedPlutusCore/Evaluation/Machine/Cek/Internal.hs
- plutus-core/untyped-plutus-core/src/UntypedPlutusCore/Evaluation/Machine/SteppableCek/Internal.hs
- plutus-core/untyped-plutus-core/test/Evaluation/Golden.hs
- plutus-core/untyped-plutus-core/test/Evaluation/Golden/headSingletonException.type.golden
- plutus-core/untyped-plutus-core/test/Evaluation/Golden/headSingletonException.uplc.golden
I just suddenly got paranoid, hence this PR.
> [Evaluation] Catch more exceptions

- doc/docusaurus/package.json
This addresses https://github.com/IntersectMBO/plutus/security/dependabot/38
> Resolve dompurfy to version 3.2.4

- .github/workflows/changelog-label.yml
Addresses this -> https://www.stepsecurity.io/blog/harden-runner-detection-tj-actions-changed-files-action-is-compromised
> Replace tj-actions/changed-files with steo-security/changed-files in check-changelog.yml

- plutus-core/untyped-plutus-core/test/Analysis/Spec.hs
Auto-format one spec file before I started chaning it.
> chore: fourmolu

- doc/plutus-core-spec/plutus-core-specification.tex
Forgot to update the date in #6895.
> Update specification date

- doc/docusaurus/docs/auction-smart-contract/on-chain-code.md
- doc/docusaurus/docs/troubleshooting.md
- doc/docusaurus/docs/using-plinth/lifting.md
This doesn't currently have sufficient explanation.
> Explain lifting in the user guide

- plutus-core/plutus-core.cabal
- plutus-core/testlib/UntypedPlutusCore/Test/Term/Construction.hs
- plutus-core/untyped-plutus-core/test/Transform/Inline/Spec.hs
- plutus-core/untyped-plutus-core/test/Transform/Simplify.hs
- plutus-core/untyped-plutus-core/test/Transform/cse2.uplc.golden
Closes https://github.com/IntersectMBO/plutus/issues/7024
> UPLC Term construction functions for testing

- doc/docusaurus/docs/working-with-scripts/compile-time-evaluation.md
This topic recently came up in the plutus channel. This should help clarify things.
> Explain compile-time evaluation in the user guide

- plutus-core/plutus-core/src/PlutusCore/Default/Builtins.hs
Fix a mistake in the error message.
> fix: error message for the `listToArray` builtin meaning.

- doc/plutus-core-spec/cardano/builtins6.tex
- doc/plutus-core-spec/flat-serialisation.tex
Fixes https://github.com/IntersectMBO/plutus-private/issues/1429
> Specification of dropList

- cardano-constitution/cardano-constitution.cabal
- doc/docusaurus/docusaurus-examples.cabal
- plutus-benchmark/plutus-benchmark.cabal
- plutus-conformance/plutus-conformance.cabal
- plutus-core/CHANGELOG.md
- plutus-core/changelog.d/20250407_170833_Yuriy.Lazaryev_builtin_purity.md
- plutus-core/plutus-core.cabal
- plutus-executables/plutus-executables.cabal
- plutus-ledger-api/plutus-ledger-api.cabal
- plutus-metatheory/plutus-metatheory.cabal
- plutus-tx-plugin/plutus-tx-plugin.cabal
- plutus-tx-test-util/plutus-tx-test-util.cabal
- plutus-tx/CHANGELOG.md
- plutus-tx/changelog.d/20250410_095704_unsafeFixIO_builtinlist.md
- plutus-tx/plutus-tx.cabal
> Release 1.45.0.0

- plutus-core/changelog.d/20250429_201142_kenneth.mackenzie_changelog.md
- plutus-ledger-api/changelog.d/20250429_201143_kenneth.mackenzie_changelog.md
- plutus-tx-plugin/changelog.d/20250429_201142_kenneth.mackenzie_changelog.md
- plutus-tx/changelog.d/20250429_201150_kenneth.mackenzie_changelog.md
We forgot to add changelog entries in #7037.  This adds them
> Forgot changelog entries

- plutus-core/plutus-core/src/PlutusCore/DeBruijn/Internal.hs
- plutus-core/plutus-core/src/PlutusCore/Evaluation/Machine/Ck.hs
- plutus-core/plutus-core/src/PlutusCore/Evaluation/Machine/CostingFun/Core.hs
- plutus-executables/test/certifier/Test/Certifier/Executable.hs
Fixes https://github.com/IntersectMBO/plutus-private/issues/1550
Adds https://github.com/IntersectMBO/plutus-private/issues/1552, https://github.com/IntersectMBO/plutus-private/issues/1553, http://github.com/IntersectMBO/plutus-private/issues/1554, https://github.com/IntersectMBO/plutus-private/issues/1555 and https://github.com/IntersectMBO/plutus-private/issues/1556. These issues can either be picked up immediately or require more discussion. See the issues themselves for details.
> Add issues to a few fixmes

- plutus-tx/testlib/PlutusTx/Test.hs
> Explicit imports and fourmolu formatting for the `PlutusTx.Test`

- .github/workflows/slack-message-broker.yml
This reverts PR https://github.com/IntersectMBO/plutus/pull/7073
> Revert "chore(deps): bump slackapi/slack-github-action from 1.27.0 to 2.1.0"

- cardano-constitution/cardano-constitution.cabal
- doc/docusaurus/docusaurus-examples.cabal
- plutus-benchmark/plutus-benchmark.cabal
- plutus-conformance/plutus-conformance.cabal
- plutus-core/CHANGELOG.md
- plutus-core/changelog.d/20250415_124450_yuriy.lazaryev_1492_test_isFirstVarBeforeEffects.md
- plutus-core/changelog.d/20250415_161534_effectfully_force_ifThenElse_delay.md
- plutus-core/changelog.d/20250423_112457_unsafeFixIO_strictify.md
- plutus-core/changelog.d/20250429_201142_kenneth.mackenzie_changelog.md
- plutus-core/plutus-core.cabal
- plutus-executables/plutus-executables.cabal
- plutus-ledger-api/CHANGELOG.md
- plutus-ledger-api/changelog.d/20250429_201143_kenneth.mackenzie_changelog.md
- plutus-ledger-api/plutus-ledger-api.cabal
- plutus-metatheory/plutus-metatheory.cabal
- plutus-tx-plugin/CHANGELOG.md
- plutus-tx-plugin/changelog.d/20250429_201142_kenneth.mackenzie_changelog.md
- plutus-tx-plugin/changelog.d/20250502_105910_Yuriy.Lazaryev_from_string_inscruitable.md
- plutus-tx-plugin/plutus-tx-plugin.cabal
- plutus-tx-test-util/plutus-tx-test-util.cabal
- plutus-tx/CHANGELOG.md
- plutus-tx/changelog.d/20250429_201150_kenneth.mackenzie_changelog.md
- plutus-tx/plutus-tx.cabal
> Release 1.46.0.0

- plutus-core/docs/BuiltinsOverview.md
I was looking into this file and noticed that some of it bitrotted, so here are fixes.
> [Docs] Add 'BuiltinResult' to 'BuiltinsOverview.md'

- plutus-core/plutus-core.cabal
> pre-commit run --all-files

- plutus-ledger-api/test/Spec/CostModelParams.hs
- plutus-ledger-api/test/Spec/Data/CostModelParams.hs
- plutus-ledger-api/test/Spec/Data/Eval.hs
- plutus-ledger-api/test/Spec/Eval.hs
- plutus-ledger-api/testlib/PlutusLedgerApi/Test/V3/Data/EvaluationContext.hs
- plutus-ledger-api/testlib/PlutusLedgerApi/Test/V3/EvaluationContext.hs
- plutus-tx-plugin/test/Plugin/Errors/Spec.hs
- plutus-tx/src/PlutusTx/Builtins.hs
Fixes https://github.com/IntersectMBO/plutus-private/issues/1599
> Add issues to FIXMEs

- doc/docusaurus/package.json
- doc/docusaurus/yarn.lock
To address Dependabot alerts #49 and #50
> Bump webpack-dev-server to 5.2.1 in docusaurus website

- plutus-metatheory/src/MAlonzo/Code/Evaluator/Program.hs
- plutus-metatheory/src/MAlonzo/Code/Evaluator/Term.hs
- plutus-metatheory/src/MAlonzo/Code/Untyped.hs
- plutus-metatheory/src/MAlonzo/Code/VerifiedCompilation/UCaseReduce.hs
- plutus-metatheory/src/MAlonzo/Code/VerifiedCompilation/UForceDelay.hs
- plutus-metatheory/src/Untyped.lagda.md
Fixes https://github.com/IntersectMBO/plutus-private/issues/1603
> List handling in uglyTmCon

- cabal.project
- flake.lock
- nix/shell.nix
> cabal.project: Update index-states and drop un-needed SRPs

- doc/docusaurus/package.json
- doc/docusaurus/yarn.lock
This addresses https://github.com/IntersectMBO/plutus/security/dependabot/52
> Bump on-headers to 1.1.0 in doc/docusaurus/package.json

- cardano-constitution/cardano-constitution.cabal
- doc/docusaurus/docusaurus-examples.cabal
- plutus-benchmark/plutus-benchmark.cabal
- plutus-conformance/plutus-conformance.cabal
- plutus-core/CHANGELOG.md
- plutus-core/changelog.d/20250729_124809_me_reverse_list_case.md
- plutus-core/plutus-core.cabal
- plutus-executables/plutus-executables.cabal
- plutus-ledger-api/CHANGELOG.md
- plutus-ledger-api/changelog.d/20250718_072102_kenneth.mackenzie_enable_all_builtins_2.md
- plutus-ledger-api/plutus-ledger-api.cabal
- plutus-metatheory/plutus-metatheory.cabal
- plutus-tx-plugin/plutus-tx-plugin.cabal
- plutus-tx/CHANGELOG.md
- plutus-tx/changelog.d/20250703_120614_seungheon.ooh_p1602_coop.md
- plutus-tx/plutus-tx.cabal
> Release 1.51.0.0

- plutus-core/plutus-core.cabal
- plutus-core/testlib/PlutusCore/Generators/QuickCheck/Builtin.hs
- plutus-core/untyped-plutus-core/testlib/Evaluation/Builtins/BLS12_381.hs
- plutus-core/untyped-plutus-core/testlib/Evaluation/Builtins/Costing.hs
See https://input-output-rnd.slack.com/archives/C08UM0JQ3AR/p1757075023510759?thread_ts=1757071231.665249&cid=C08UM0JQ3AR
> Make plutus compile with both QuickCheck 2.15.. and 2.16

- plutus-benchmark/data/bench/Bench.hs
- plutus-benchmark/data/src/PlutusBenchmark/Data.hs
- plutus-benchmark/plutus-benchmark.cabal
benchmarks for data constructions
> Add data construction bench
