IntersectMBO/plutus

- stack.yaml
Resolves `* Missing C library: crypto` on nix-based stack builds.
> Add openssl for nix build

- src/Demo.pls
The README suggests trying an expression which relies on `id`, but it
is missing.
> Add `id` function to the demo program.

- language-plutus-core/language-plutus-core.cabal
- language-plutus-core/src/Language/PlutusCore/TypeSynthesis.hs
- language-plutus-core/test/Spec.hs
- language-plutus-core/test/types/addInteger.plc
- language-plutus-core/test/types/addIntegerCorrect.plc
- language-plutus-core/test/types/addIntegerCorrect.plc.golden
The allows us to express `(+2)` as a Plutus Core program, and fixes previously extant bugs with type application and term application.
> Bug fixes for type synthesis

- language-plutus-core/README.md
This is a first step. Once there is an example of how to parse and type check things, I'll define a combinator that allows to parse-typecheck-run a term using a single call and add an example of its usage to the readme.
> Described evaluation in the readme

- language-plutus-core/language-plutus-core.cabal
- language-plutus-core/src/Language/PlutusCore.hs
- language-plutus-core/src/Language/PlutusCore/Name.hs
- pkgs/default.nix
- stack.yaml
This isn't in the Stackage snapshot, which causes issues for packages that depend on `language-plutus-core`. For example, if package `A` from the snapshot depends on `containers`, then attempting to build `B` which depends on `A` and `language-plutus-core` will fail because we have two versions of the `containers` dependency. Concretely, this is a problem for https://github.com/input-output-hk/plutus-prototype/pull/33. 
We should probably try to stick within the Stackage snapshot as much as possible. We can of course update them, but the latest 11-series snapshot doesn't have `containers-5.11`, and the 12-series uses GHC 8.4.3, which isn't in our Nixpkgs pin.
We could update our Nixpkgs pin from the `18.03` release tag to the tip of the `18.03-release` branch, but I think it might be …
> language-plutus-core: drop containers-5.11 dependency

- default.nix
- language-plutus-core/shell.nix
- plutus-prototype/shell.nix
- Add `shell.nix` files in project subdirs for convenience
- Add `doBenchmark` to `language-plutus-core` so we get `criterion` in the corresponding shell env
> Minor dev env improvements

- language-plutus-core/README.md
- language-plutus-core/run-ck/Main.hs
Lucas said he now thinks a non-interactive version is preferable, so it's non-interactive now by default.
The interactive version is in the code, but I don't bother to add flags right now, because I may prefer to just use REPL in emacs.
> Made the 'run-ck' executable non-interactive

- language-plutus-core/language-plutus-core.cabal
- language-plutus-core/prelude/PlutusPrelude.hs
- language-plutus-core/src/Language/PlutusCore.hs
- language-plutus-core/src/Language/PlutusCore/Constant/Make.hs
- language-plutus-core/src/Language/PlutusCore/Constant/Prelude.hs
- language-plutus-core/src/Language/PlutusCore/Constant/Typed.hs
- language-plutus-core/src/Language/PlutusCore/Lexer.x
- language-plutus-core/src/Language/PlutusCore/Name.hs
- language-plutus-core/src/Language/PlutusCore/Parser.y
- language-plutus-core/src/Language/PlutusCore/Quote.hs
- language-plutus-core/src/Language/PlutusCore/Renamer.hs
- pkgs/default.nix
Concretely, this allows us to interleave running the parser and creating terms manually and have them all use the same fresh identifier state.
> language-plutus-core: use state-based mechanism for fresh names

- language-plutus-core/language-plutus-core.cabal
- language-plutus-core/prelude/PlutusPrelude.hs
- language-plutus-core/src/Language/PlutusCore.hs
- language-plutus-core/src/Language/PlutusCore/Constant/Prelude.hs
- language-plutus-core/src/Language/PlutusCore/Lexer.x
- language-plutus-core/src/Language/PlutusCore/Lexer/Type.hs
- language-plutus-core/src/Language/PlutusCore/Name.hs
- language-plutus-core/src/Language/PlutusCore/Parser.y
- language-plutus-core/src/Language/PlutusCore/Quote.hs
- language-plutus-core/src/Language/PlutusCore/Subst.hs
- language-plutus-core/src/Language/PlutusCore/TH.hs
- language-plutus-core/src/Language/PlutusCore/Type.hs
- language-plutus-core/test/Evaluation/Generator.hs
- language-plutus-core/test/Quotation/Spec.hs
- language-plutus-core/test/Quotation/bool.plc.golden
- language-plutus-core/test/Quotation/false.plc.golden
- language-plutus-core/test/Quotation/one.plc.golden
- language-plutus-core/test/Quotation/true.plc.golden
- language-plutus-core/test/Quotation/unit.plc.golden
- language-plutus-core/test/Spec.hs
- pkgs/default.nix
This adds a quasiquoter for PLC to `language-plutus-core`. In order to get it scope-safe I had to implement a capture-avoiding substitution function - I've put this in its own module since it seems reusable, and no doubt other people can make it more efficient!
I think this should be useful both for defining terms in `language-plutus-core` itself (e.g. in `Constant/Prelude.hs`), and when generating PLC programs in the PlutusTx compiler.
The approach I've taken for antiquotation is to use free object-level variables as metavariables. It's perhaps easiest to see how this works out with an example (taken from the tests):
```
unit = [plcType|(all a (type) (fun a a))|]
one = [plcTerm|(abs a (type) (lam x a x))|]
bool = [plcType|(all a (type) (fun (fun unit a) (fun (fun unit a) a))) |]
true = …
```
> language-plutus-core: add quasiquoter

- docs/extended-utxo/README.md
The data script hashes are part of the blockchain state provided for inputs and outputs of the validated transaction.
> Extended UTxO: blockchain state clarification

- language-plutus-core/language-plutus-core.cabal
- language-plutus-core/src/Language/PlutusCore/Constant/Typed.hs
- language-plutus-core/src/Language/PlutusCore/Lexer.x
- language-plutus-core/src/Language/PlutusCore/Lexer/Type.hs
- language-plutus-core/src/Language/PlutusCore/Name.hs
- language-plutus-core/src/Language/PlutusCore/Parser.y
- language-plutus-core/src/Language/PlutusCore/Quote.hs
- language-plutus-core/src/Language/PlutusCore/Renamer.hs
- language-plutus-core/src/Language/PlutusCore/Type.hs
- language-plutus-core/src/Language/PlutusCore/TypeSynthesis.hs
It got annoying.
- Obvious things (`ScopedTypeVariables`)
- Non-conflicty deriving things (in particular `DeriveAnyClass` sometimes conflicts with GND in an annoying way)
- Simple type class extensions for MTL-style classes.
`OverloadedStrings` is in nearly every file, so I think there's a good case for that too, but I'll leave it for now.
> language-plutus-core: move some things to default-extensions

- language-plutus-core/src/Language/PlutusCore/Constant/Prelude.hs
- language-plutus-core/src/Language/PlutusCore/TH.hs
- language-plutus-core/test/Quotation/Spec.hs
- language-plutus-core/test/Quotation/bool.plc.golden
- language-plutus-core/test/Quotation/false.plc.golden
- language-plutus-core/test/Quotation/free.plc.golden
- language-plutus-core/test/Quotation/true.plc.golden
- pkgs/default.nix
Usually you want to bind interpolated variables in a do block
beforehand, in which case they will not be in `Quote`. This is important
if you want to actually share a name - otherwise the computation will be
run at each occurrence, meaning you get different names!
(Test changes are due to the fact that the variables are now "run" before the main quoted term, rather than vice versa, which is what it was before)
> Quasiquoter: interpolated variables should not be in Quote

- language-plutus-core/src/Language/PlutusCore/Quote.hs
- language-plutus-core/src/Language/PlutusCore/Renamer.hs
- language-plutus-core/src/Language/PlutusCore/TH.hs
@vmchale this is what I was thinking.
This adds a `Quote` interface to annotating and typechecking. `QuoteT` already has a counter for the next `Unique` to use, so all we need to do is:
- Update the counter after we run `annotate` to the maximum of the previous value and the one output by `annotate`.
- I'm basing this on what is done for `programType`.
- It seems suspicious to me that `annotate` doesn't take a previous max unique value.
- Pass in our counter to `runTypeCheckM`.
I haven't replaced any of the other uses, although I think possibly they may prefer to use this in the long run if we keep using `QuoteT` as our primary "term construction monad".
As a side effect, this will let you typecheck your quasiquotes, which is nice.
> Quote: add interface to annotation and typechecking

- language-plutus-core/run-ck/Main.hs
- language-plutus-core/src/Language/PlutusCore.hs
- language-plutus-core/src/Language/PlutusCore/Error.hs
- language-plutus-core/src/Language/PlutusCore/Lexer.x
- language-plutus-core/src/Language/PlutusCore/Normalize.hs
- language-plutus-core/src/Language/PlutusCore/Parser.y
- language-plutus-core/src/Language/PlutusCore/Quote.hs
- language-plutus-core/src/Language/PlutusCore/Renamer.hs
- language-plutus-core/src/Language/PlutusCore/TH.hs
- language-plutus-core/src/Language/PlutusCore/TypeSynthesis.hs
Without this, we can't do annotating and typechecking with terms that aren't annotated with `AlexPosn`s (i.e. with synthetic terms), because we need to produce `Error`s which are locked to containing `AlexPosn`s. The end goal is the generalization of the functions in `Quote`.
I also added an `OtherError` constructor for things that haven't merited their own branch yet.
This change does mean that the errors won't have informative locations, but that's simply true for generated 
terms. (We could also add some explanatory text, but that can be a separate change).
> Give Error a type param, allow arbitrary other errors

- default.nix
This is IMO a horrifying misfeature which breaks nix builds in subtle ways. FYI @disassembler you might want to port this to Cardano in case anybody starts using `new-build` and wonders why everything is broken.
> Filter out .ghc.environment files

- language-plutus-core/plutus-exe/Main.hs
- language-plutus-core/src/Language/PlutusCore.hs
- language-plutus-core/src/Language/PlutusCore/Error.hs
- language-plutus-core/src/Language/PlutusCore/Parser.y
- language-plutus-core/src/Language/PlutusCore/Quote.hs
- language-plutus-core/src/Language/PlutusCore/Renamer.hs
- language-plutus-core/src/Language/PlutusCore/TH.hs
- language-plutus-core/src/Language/PlutusCore/Type.hs
- language-plutus-core/src/Language/PlutusCore/TypeSynthesis.hs
As noticed on Slack, it's annoying that `Quote` depends on other stuff so you get module cycles when using it. I have attempted to fix this by moving the functions that do typechecking etc. in `Quote` into the respective modules. Annoyingly, this introduces more cycles due to the `Error` type, so I've moved the error definitions into `Error` (mostly), which is annoying but doesn't seem too bad.
Finally, to avoid confusion, I've suffixed the quote commands with Q for now.
(Man, not having cyclic imports is annoying...)
> Improve dependencies relating to `Quote`

- language-plutus-core/plutus-exe/Main.hs
- language-plutus-core/src/Language/PlutusCore.hs
- language-plutus-core/src/Language/PlutusCore/Error.hs
- language-plutus-core/src/Language/PlutusCore/Normalize.hs
This now causes `plc typecheck` to reject the program in https://iohk.myjetbrains.com/youtrack/issue/CGP-268 at normalization time.
> plutus-exe: check before typechecking

- language-plutus-core/language-plutus-core.cabal
- language-plutus-core/plutus-exe/Main.hs
- language-plutus-core/src/Language/PlutusCore.hs
- language-plutus-core/src/Language/PlutusCore/Error.hs
- language-plutus-core/src/Language/PlutusCore/Parser.y
- language-plutus-core/src/Language/PlutusCore/PrettyCfg.hs
- language-plutus-core/src/Language/PlutusCore/Renamer.hs
- language-plutus-core/src/Language/PlutusCore/TH.hs
- language-plutus-core/src/Language/PlutusCore/Type.hs
- language-plutus-core/src/Language/PlutusCore/TypeSynthesis.hs
- language-plutus-core/test/Evaluation/TypeCheck.hs
- language-plutus-core/test/Spec.hs
- pkgs/default.nix
This gets us to the point where *most* of the bits of `language-plutus-core` are using a consistent interface, and there are significantly fewer ways of doing things floating around.
- Annotation and typechecking use `Quote` both externally and internally where appropriate.
- As a bonus, this means that we can use the stdlib definitions of booleans in the typechecker.
- Most of the modules just export top-level functions for working ontypes/terms/programs as appropriate.
The one bit that remains inconsistent is the parser/renamer, since they
share a bit of state that they pass around. I think the thing to do
would be to have the renamer just calculate its initial state from
the term it is passed in.
> language-plutus-core: standardise interface a bit more

- default.nix
I've verified that this *does* actually build the benchmarks. IMO this is a bug in `doBenchmark` and I'm going to open a PR upstream too.
FYI @disassembler @vmchale
> Build benchmarks

- language-plutus-core/stdlib/Language/PlutusCore/StdLib/Data/Bool.hs
- language-plutus-core/stdlib/Language/PlutusCore/StdLib/Data/Function.hs
- language-plutus-core/stdlib/Language/PlutusCore/StdLib/Data/List.hs
- language-plutus-core/stdlib/Language/PlutusCore/StdLib/Data/Nat.hs
This fixes duplicate names inside the stdlib where possible.
Now the problem: you cannot apply the same `list` to `A` and to `B` in a type as that would result in name sharing, because `list` binds an `r` deeply inside.
I will write more on the topic on our mailing list, but let's fix at least booleans for now.
> Fixed duplicate names where possible

- language-plutus-core/src/Language/PlutusCore/Lexer.x
This change looks like it sneaked into the spec without anyone noticing.
> Leading characters in identifiers can be upper or lower case

- release.nix
I've recently realised that we need to do this when we add a package if we want it to be built by the CI.
> Add plutus-core-interpreter to the CI

- release.nix
I think this is better as a hygiene thing, otherwise Hydra shows the darwin job as "removed", which is perhaps confusing.
> Only even try to build the spec on linux

- .hlint.yaml
- language-plutus-core/generators/Language/PlutusCore/Generators/Internal/Entity.hs
- language-plutus-core/src/Language/PlutusCore/Constant/Typed.hs
- language-plutus-core/src/Language/PlutusCore/Name.hs
For example
```
 prettyCfgString . runQuote $ typeOfBuiltinName ResizeInteger
"(all s0 (size) (all s1 (size) (fun [(con size) s1] (fun [(con integer) s0] [(con integer) s1]))))"
 prettyCfgString . runQuote $ typeOfBuiltinName IntToByteString
"(all s0 (size) (all s1 (size) (fun [(con size) s1] (fun [(con integer) s0] [(con bytestring) s1]))))"
 prettyCfgString . runQuote $ typeOfBuiltinName Concatenate
"(all s0 (size) (fun [(con bytestring) s0] (fun [(con bytestring) s0] [(con bytestring) s0])))"
 prettyCfgString . runQuote $ typeOfBuiltinName MultiplyInteger
"(all s0 (size) (fun [(con integer) s0] (fun [(con integer) s0] [(con integer) s0])))"
```
> Added 'typeOfBuiltinName'

- core-to-plc/src/Language/Plutus/CoreToPLC.hs
- core-to-plc/test/Spec.hs
- core-to-plc/test/basicNewtype.plc.golden
Ignoring these is definitely wrong. I think I know how to handle the newtype coercions, but for now make sure we don't blindly generate the wrong code!
> Plugin: fail on casts

- language-plutus-core/src/Language/PlutusCore.hs
- language-plutus-core/src/Language/PlutusCore/Error.hs
- language-plutus-core/src/Language/PlutusCore/Type.hs
- language-plutus-core/src/Language/PlutusCore/TypeSynthesis.hs
This adds a `NormalizedType` newtype wrapper for normalized types. It's not quite making illegal states unrepresentable, because there's nothing preventing you from lying, but I think the clarity improvement is just about worth the book-keeping.
The current approach highlights the places where we assert that types are normalized: when picking them up from terms, and (suspiciously) after we substitute during reduction. (I think this might be a bug).
In addition, I made `tySubstitute` take `NormalizedType`s. This is desirable - if we allow either of the arguments to be non-normalized we can create redundant work by substituting in/substituting into things that we're going to reduce away.
I also tried a more heavy-weight approach here: …
> Distinguish normalized types with a newtype wrapper

- core-to-plc/src/Language/Plutus/CoreToPLC.hs
- core-to-plc/src/Language/Plutus/CoreToPLC/Error.hs
- core-to-plc/src/Language/Plutus/CoreToPLC/Plugin.hs
Most of this PR is the machinery that made debugging this possible!
It's worth having a special case to error out early if we see `Integer`, because it has weird constructors which give unexpected error messages. With the context added in this PR you can still see it was due to `Integer`, but I expect this to be a common case so worth some effort.
> [CGP-287] Give a better error for use of `Integer`

- language-plutus-core/src/Language/PlutusCore/Lexer/Type.hs
- language-plutus-core/src/Language/PlutusCore/Parser.y
This uses prefixes, in accordance with @mchakravarty's suggestion.
> use prefixes

- core-to-plc/src/Language/Plutus/CoreToPLC.hs
- core-to-plc/src/Language/Plutus/CoreToPLC/Plugin.hs
Annoyingly, it appears that GHC no longer tracks whether types are recursive for us (from about https://phabricator.haskell.org/D2360 onwards). This means we're going to have to track this information ourselves. This fix is therefore geared towards the expectation that we're going to be remembering information about types.
For now, we just cache all of our type conversions. This allows us to mark types as "blackholed" while we're converting them, so we can fail if we see them again. As a side benefit, it saves us some repeated work.
I have verified that this gives errors in the cases we expect. I'm working on making it easier to test cases that produce compile errors, but I'll put that up separately so we can get this in sooner.
> [CGP-285] Cache type conversion state and emit errors for recursion

- core-to-plc/core-to-plc.cabal
- core-to-plc/src/Language/Plutus/CoreToPLC.hs
- core-to-plc/src/Language/Plutus/CoreToPLC/Error.hs
- core-to-plc/src/Language/Plutus/CoreToPLC/Plugin.hs
- core-to-plc/test/IllTyped.hs
- core-to-plc/test/Spec.hs
- core-to-plc/test/free.plc.golden
- core-to-plc/test/integer.plc.golden
- core-to-plc/test/list.plc.golden
- Typecheck things that we are able to.
- I added an option to disable typechecking, and put the things that don't typecheck in a separate module with that option on, so at least we can typecheck the things that work.
- Throw `GhcException` instead of our own exception.
- Slightly nicer error contexts.
- Allow deferring plugin errors to runtime.
- This means the value will blow up with the error as an exception when you touch it. This is only really useful for testing, but it's quite useful there! I added a test to demonstrate.
> Plugin: several improvements to error handling

- core-to-plc/src/Language/Plutus/CoreToPLC.hs
- core-to-plc/test/Spec.hs
- core-to-plc/test/nestedNewtypeMatch.plc.golden
- core-to-plc/test/newtypeCreate.plc.golden
- core-to-plc/test/newtypeMatch.plc.golden
This adds support for newtypes by treating them as data constructors with a single constructor. We handle coercions by looking for coercions between a newtype and its definition. If we find such a wrap or unwrap, we handle it by either creating a trivial match or wrapping up the value.
It would be nice to also offer GHC's guarantee that newtypes are represented exactly as the underlying type, but I think we can view that as future optimization (I'll open a ticket).
> [CGP-286] Convert newtype coercions into explicit wraps and unwraps

- core-to-plc/src/Language/Plutus/CoreToPLC.hs
- core-to-plc/test/IllTyped.hs
- core-to-plc/test/Spec.hs
- core-to-plc/test/void.plc.golden
These are the uninhabited type and an inhabitant for that type (to use
in unreachable cases).
In Plutus we can represent `Void#` as `(all a (type) a)`, which is
uninhabited, and then fortunately we can actually create a value to put
there, namely `(abs a (type) (error a))`.
> [CGP-296] Support Void# and void#

- default.nix
- pkgs/default.nix
- release.nix
- stack.yaml
- wallet-api/LICENSE
- wallet-api/README.md
- wallet-api/shell.nix
- wallet-api/src/Wallet/Emulator/Types.hs
- wallet-api/wallet-api.cabal
This is an actually-working version of the types @j-mueller and I sketched out yesterday.
I implemented the tiniest part of the emulated wallet (submitting a fake transaction), so there is an actual example you can run! You can load up the file in GHCI and then run `runState (runExceptT (process trace)) emptyEmulatorState`.
> Sketch of Plutus chain emulator

- core-to-plc/src/Language/Plutus/CoreToPLC.hs
- core-to-plc/src/Language/Plutus/CoreToPLC/Error.hs
- core-to-plc/src/Language/Plutus/CoreToPLC/Primitives.hs
- core-to-plc/test/Spec.hs
- core-to-plc/test/error.plc.golden
- core-to-plc/test/valueRestriction.plc.golden
- core-to-plc/test/void.plc.golden
- language-plutus-core/src/Language/PlutusCore.hs
- language-plutus-core/src/Language/PlutusCore/Normalize.hs
- plutus-use-cases/shell.nix
- plutus-use-cases/src/Language/Plutus/Coordination/Contracts/CrowdFunding.hs
- plutus-use-cases/src/Language/Plutus/Coordination/Contracts/Swap.hs
As discussed on the call, we're keeping the value restriction, at least for now.
There are two ways we can deal with this:
1. Mangle all our `TyForall`s, `TyAbs`s, and `TyInst`s to delay and force all over the place.
2. Pass on the value restriction to users as an error.
I've opted to go for 2. at the moment, after discussion with @mchakravarty. See the note in the source for more details, and a few wrinkles we need to deal with. As evidence that this will not be a problem for users, I had to actually try quite hard to get an example where we hit the error.
The only user-facing change is that the primitive `error` we export now has type `forall a . () -> a` instead of `forall a. a` (we in fact can make no terms of that type!).
> core-to-plc: handle the value restriction

- core-to-plc/core-to-plc.cabal
- core-to-plc/src/Language/Plutus/CoreToPLC.hs
- core-to-plc/src/Language/Plutus/CoreToPLC/Builtins.hs
- core-to-plc/src/Language/Plutus/CoreToPLC/Laziness.hs
- core-to-plc/src/Language/Plutus/CoreToPLC/Primitives.hs
- core-to-plc/test/IllTyped.hs
- core-to-plc/test/Spec.hs
- core-to-plc/test/ifThenElse.plc.golden
- core-to-plc/test/intCompare.plc.golden
- core-to-plc/test/intEq.plc.golden
- core-to-plc/test/letFun.plc.golden
- core-to-plc/test/void.plc.golden
As I recently noticed (cf my email today), the booleans in the spec are not the usual Scott-encoded booleans, because they bake in the lazy matching. Regardless of whether this is a good idea or not, this means that we need to convert the spec-booleans that come out of builtins into our booleans. This is something of a hassle, since we'd been translating to builtins as functions, so we need to post-compose the conversion function, which adds some ceremony. I ended up restructuring some of the primitive code a bit to make this less annoying.
(And I realised this should almost certainly use Roman's typed builtin work in some way, but I'm leaving that for now).
The resulting code is somewhat painful, but it will get nicer again if we bring our booleans into sync.
On top of the value …
> core-to-plc: correctly convert spec booleans into our booleans

- .hlint.yaml
Not actually used anywhere, and the comment is false as far as I can tell.
> remove ignored hint

- pkgs/default.nix
- wallet-api/src/Wallet/Emulator.hs
- wallet-api/src/Wallet/Emulator/Types.hs
- wallet-api/src/Wallet/UTXO.hs
- wallet-api/test/Generators.hs
- wallet-api/test/Spec.hs
- wallet-api/wallet-api.cabal
* Add UTXO transaction types based on the code docs/model/UTxO.hsproj
* The main changes to this model are
a) Use actual PlcCode types for scripts
b) Add data scripts and make sure that scripts/script hashes are in
the correct place
* We can now properly validate transactions in the emulator
(the next PR will be importing the wallet reference implementation)
> [CGP-307] Add transaction types to `wallet-api`

- .hlint.yaml
Reverts input-output-hk/plutus-prototype#134
Here's an example 
```
let tuple = foldl' (\acc rhs -> PLC.Apply () acc rhs) tupleConstructor rhss
```
I *could* delete the lambda arguments, but I think that's less clear since it's a coincidence that `PLC.Apply` happens to take the argument s this way around.
> Revert "remove ignored hint"

- core-to-plc/src/Language/Plutus/CoreToPLC.hs
- core-to-plc/src/Language/Plutus/CoreToPLC/Laziness.hs
- core-to-plc/test/Spec.hs
- core-to-plc/test/defaultCase.plc.golden
- core-to-plc/test/monoCase.plc.golden
- core-to-plc/test/nonValueCase.plc.golden
- core-to-plc/test/tupleMatch.plc.golden
- core-to-plc/test/void.plc.golden
- plutus-th/test/and.plc.golden
- plutus-th/test/simple.plc.golden
I realised that we only actually *need* to compile case expressions lazily when they might unexpectedly evaluate some non-value terms. However, in the common case (where the datatype branch has arguments) we are guaranteed to be passing a lambda. So the only times we might need to do this are for alternatives for constructors without arguments or (potentially) default cases. 
This is then fairly easy to check. The result shaves potentially quite a bit of most case expressions, which is nice. I think it's worth it - we don't get many codegen wins! But it does make our codegen less uniform, which is potentially bad.
(Interestingly, the `void` test case doesn't benefit, because it gets some "impossible" pattern match branches. These have evaluations in their RHSs - which will indeed evaluate …
> core-to-plc: avoid lazy case expressions where possible

- pkgs/default.nix
- wallet-api/src/Wallet/Emulator/Types.hs
- wallet-api/src/Wallet/UTXO.hs
- wallet-api/test/Generators.hs
- wallet-api/test/Spec.hs
- wallet-api/wallet-api.cabal
* Change UTXO model in `wallet-api` to match the reference implementation in cardano-sl/new-wallet/test/unit where applicable
* Nicer API for `Wallet.Emulator.Types`
* Generate transactions with multiple outputs in emulator tests; add parameters for mockchain size and fee estimation
> wallet emulator import & API

- plutus-core-spec/figures/PlutusCoreBuiltins.tex
> s_01i -> s_0!i

- language-plutus-core/src/Language/PlutusCore.hs
- plutus-exe/src/Main.hs
- wallet-api/src/Wallet/UTXO.hs
- wallet-api/wallet-api.cabal
They're all trivial atm, but I have verified that this does fail to validate transactions if you mess up the definition of e.g. the validator.
> wallet-api: typecheck and run scripts in the emulator

- plutus-use-cases/src/Language/Plutus/Coordination/Contracts/CrowdFunding.hs
- wallet-api/src/Wallet/UTXO.hs
* Use untyped TH splices to allow hlint and stylish-haskell to work
* see https://github.com/haskell-suite/haskell-src-exts/issues/383
* Unfortunately this reverses some of the formatting changes from c907023
> Untyped TH to appease hs-src-exts

- .hlint.yaml
- core-to-plc/src/Language/Plutus/CoreToPLC.hs
- language-plutus-core/generators/Language/PlutusCore/Generators/Interesting.hs
- language-plutus-core/language-plutus-core.cabal
- language-plutus-core/src/Language/PlutusCore/MkPlc.hs
- language-plutus-core/src/Language/PlutusCore/Quote.hs
- language-plutus-core/stdlib/Language/PlutusCore/StdLib/Data/Bool.hs
- language-plutus-core/stdlib/Language/PlutusCore/StdLib/Data/ChurchNat.hs
- language-plutus-core/stdlib/Language/PlutusCore/StdLib/Data/Function.hs
- language-plutus-core/stdlib/Language/PlutusCore/StdLib/Data/List.hs
- language-plutus-core/stdlib/Language/PlutusCore/StdLib/Data/Nat.hs
We do a lot of similar kinds of task when constructing Plutus Core programs that can easily be abstracted out.
This PR introduced term construction functions for:
- Various kinds of iterated application and abstraction. I find these much easier than remembering the arguments to `foldl` and `foldr` every time.
- Making "lets" using lambdas and type abstractions.
The latter also comes with a `Quote` version that I hope will make our lives easier with having to define multiple copies of things to make sure we have global uniqueness. Instead we can just let-bind the damn thing and reference it as a variable. This has the advantage of reducing code size too!
I used this on the examples in `Bool`, but I stalled a bit on the recursive type case (which would also benefit from it). The problem is …
> language-plutus-core: add useful term construction functions

- language-plutus-core/stdlib/Language/PlutusCore/StdLib/Data/Bool.hs
I made a mistake.
Type abstractions are *opaque* inside the abstraction, so this won't typecheck because we can't tell that our `unitval` is actually of the (opaque) type `unit`. We would need to bind them together, as is generally going to be the case for types and their constructors/destructors.
> Revert changes to `ifThenElse`

- language-plutus-core/src/Language/PlutusCore/Type.hs
This is in order to make the `Eq` instance for `Type` the same as the derived instances of `Kind`, `Constant`, `Term`, etc.
However there is
```haskell
instance Eq (Name a) where
(==) = (==) `on` nameUnique
```
Should we also check for equality the annotations here? I believe we have to be consistent.
> [CGP-349] Fixed the Eq instance for Type

- cabal.project
I'm pretty sure I'm the only one who uses this, but it will be good to be able to use `cabal` when we upload this Hackage.
> Fix cabal.project

- language-plutus-core/src/Language/PlutusCore/TypeSynthesis.hs
- language-plutus-core/test/Spec.hs
This fixes another bunch of bugs in the type checker which finally allows us to type check the standard library.
It also showcases how we should comment each of the cases:
```
-- G |- term : nTermTy, ty ~>* nTy, [fix n nTy / n] nTy ~>* nTermTy', nTermTy ~ nTermTy'
-- -------------------------------------------------------------------------------------
-- G |- wrap n ty term : fix n nTy
```
I'll write more on that on the mailing list, but hey, we can type check the standard library.
> Fixed the wrap case in the type checker

- language-plutus-core/prelude/PlutusPrelude.hs
- language-plutus-core/src/Language/PlutusCore.hs
- language-plutus-core/src/Language/PlutusCore/Type.hs
- language-plutus-core/src/Language/PlutusCore/TypeSynthesis.hs
- language-plutus-core/test/Spec.hs
This introduces
```haskell
newtype Normalized a = Normalized { getNormalized :: a }
```
and uses its `Functor`, `Applicative`, `Traversable` instances in order to reduce clutter. Backwards compatibility is preserved via
```haskell
type NormalizedType tyname a = Normalized (Type tyname a)
pattern NormalizedType :: Type tyname a -> NormalizedType tyname a
pattern NormalizedType ty = Normalized ty
getNormalizedType :: NormalizedType tyname a -> Type tyname a
getNormalizedType (Normalized ty) = ty
```
which can be kept or removed in another PR.
I also removed several uses of the `NormalizedType`, because there was at least one bug previously related to inaccurate use of `NormalizedType`.
I also renamed `tyReduce` to `normalizeType` and simplified it (as per the latest call). Replaced …
> [CGP-360] [Type checker] Reduced 'NormalizedType' clutter

- plutus-core-spec/figures/PlutusCoreTypeCorrectness.tex
Too small of a typo to get lost in spec-typos branch.
> Spec typo in context definition

- .hlint.yaml
- language-plutus-core/src/Language/PlutusCore.hs
- language-plutus-core/src/Language/PlutusCore/Error.hs
- language-plutus-core/src/Language/PlutusCore/TypeSynthesis.hs
This removes `BuiltinTable` and all associated machinery (including `InternalError`) in favor of `typeOfBuiltinName`.
> [CGP-362] [Type checker] Remove 'BuiltinTable' in favor of 'typeOfBuiltinName'

- .hlint.yaml
- pkgs/default.nix
- plutus-use-cases/plutus-use-cases.cabal
- plutus-use-cases/src/Language/Plutus/Coordination/Contracts/CrowdFunding.hs
- plutus-use-cases/src/Language/Plutus/Coordination/Contracts/Vesting.hs
- plutus-use-cases/test/Spec/Crowdfunding.hs
- plutus-use-cases/test/Spec/TH.hs
- plutus-use-cases/test/Spec/Vesting.hs
- wallet-api/src/Wallet/UTXO.hs
* Add a Spec.TH module with quoted expressions for creating `PendingTx`
values
> use-cases: Add TH module for tests

- core-to-plc/test/IllTyped.hs
- core-to-plc/test/Spec.hs
The remainder are waiting on CGP-324 so we can fix on types of arbitrary kind.
> core-to-plc: move some tests that now typecheck

- plutus-use-cases/test/Spec.hs
This reduces the time of the test suite from 8.5s to 3.4s on my machine.
I don't think we should go below 5 successful tests. The most important parameter that varies in the generated chains is the distribution of coins to transaction outputs in the initial transaction, which in turn has an impact on coin selection. And we should at least cover a small number of different distributions here.
> plutus-use-cases: reduce test limit

- core-to-plc/src/Language/Plutus/CoreToPLC/Plugin.hs
- language-plutus-core/bench/Bench.hs
- language-plutus-core/language-plutus-core.cabal
- language-plutus-core/src/Language/PlutusCore.hs
- language-plutus-core/src/Language/PlutusCore/CBOR.hs
- language-plutus-core/test/Spec.hs
- pkgs/default.nix
This has a number of benefits:
- Avoid proliferation of functions, and redefinition of functions
already provided by `serialise` (`serialise`, `deserialiseOrFail`, etc.)
- Simplify clients of serialisation (e.g. the plugin)
- Open a natural avenue for serializing dynamic builtins by requiring
something like `Serialize dyn => Serialize (Term TyName Name dyn ())`
I didn't change anything in the serialization scheme itself, although it
occurs to me that it would now be quite easy to make it serialise the
annotations if they are serialisable. This would have some advantages:
for example, it would allow us to give better diagnostics when running
things on the mockchain if we serialized positions too.
> CBOR: use Serialise throughout

- wallet-api/emulator/Main.hs
- wallet-api/src/Wallet/Emulator/Http.hs
- wallet-api/src/Wallet/Emulator/Types.hs
- wallet-api/src/Wallet/UTXO.hs
This commit adds new endpoints to trigger validation
and notifications.
The next stage is to create a client and try to fit
it into the Trace api. The only issue I see is assertions.
Since these are Haskell functions, we cannot serialize
them. It may be that we can remove them from the Trace API
and run them separately. We may need more endpoints for
this in order to see more state within the emulator.
> HTTP MockChain Part 2

- language-plutus-core/language-plutus-core.cabal
- language-plutus-core/src/Language/PlutusCore/Constant/Typed.hs
- language-plutus-core/src/Language/PlutusCore/TypeSynthesis.hs
This adds `Semigroup` instances so that, among other things, this builds with GHC 8.6.1.
I also added `-Wnoncanonical-monoid-instances` so that noncanonical monoid instances don't pass CI in the future.
> add Semigroup instances

- README.md
You can find these if you poke around `cardano-sl`, but better to have them in our README, since it's very useful.
> README: add instructions for adding binary caches

- .hlint.yaml
- core-to-plc/src/Language/Plutus/CoreToPLC/Plugin.hs
- core-to-plc/test/IllTyped.hs
- core-to-plc/test/Spec.hs
- core-to-plc/test/data/monomorphic/nonValueCase.plc.golden
- core-to-plc/test/data/newtypes/nestedNewtypeMatch.plc.golden
- core-to-plc/test/errors/free.plc.golden
- core-to-plc/test/errors/integer.plc.golden
- core-to-plc/test/errors/valueRestriction.plc.golden
- plutus-th/src/Language/Plutus/TH.hs
- plutus-th/test/Spec.hs
- plutus-th/test/TestTH.hs
- plutus-use-cases/src/Language/Plutus/Coordination/Contracts/CrowdFunding.hs
- plutus-use-cases/src/Language/Plutus/Coordination/Contracts/Swap.hs
- plutus-use-cases/src/Language/Plutus/Coordination/Contracts/Vesting.hs
- plutus-use-cases/test/Spec/Crowdfunding.hs
- plutus-use-cases/test/Spec/Vesting.hs
- wallet-api/src/Wallet/UTXO/Types.hs
This allows us to pass the location of the overall splice in to the plugin from TH as a type level literal (trick once again stolen from `inline-java`, but we do it better with `TypeApplications` rather than `Proxy`s). Unfortunately this does require `DataKinds` (ping @mchakravarty for the UI issue).
You would think that we could get this information from Core, but apparently not. Only names have locations, and those often aren't where you'd expect, since things can have been lifted etc. The TH locations are reliably where the user put them.
There's a bunch of noise for `core-to-plc`'s tests since they don't use the TH stuff so have to pass something themselves.
I also removed some unnecessary debug printing that might have been part of why `plutus-use-cases` has been slow, since it'll be …
> core-to-plc: allow passing locations as type lits

- wallet-api/src/Wallet/Emulator/Types.hs
- wallet-api/src/Wallet/UTXO/Index.hs
- wallet-api/src/Wallet/UTXO/Types.hs
- wallet-api/test/Spec.hs
* Extend the `LookupError` type to cover all possible validation errors
* Add `validateTransaction` which produces much more detailed errors
than `validate`
* Change the `BlockchainLookup` type to `ValidationMonad`
After I started building the new runtime validation stuff I realised that the `LookupError` is only relevant when validating a transaction, and decided to add a more detailed error type that covers all failure conditions. Even if we don't get such precise errors from the real blockchain it is useful to have them in the emulator for writing plutus contracts.
> wallet-api: Better validation errors

- language-plutus-core/src/Language/PlutusCore.hs
- language-plutus-core/src/Language/PlutusCore/Renamer.hs
I need the renamer to run in `Quote` rather than the custom monad it's currently running in. But once I started to change things, I realized there is a nicer way the renamer can be defined.
> [CGP-387] Rewrote the renamer

- core-to-plc/src/Language/Plutus/CoreToPLC/Plugin.hs
* Fixes compiler warnings in Language.Plutus.CoreToPLC.Plugin which
caused the build to fail when the `development` flag is enabled
> core-to-plc: Fix warnings

- pkgs/default.nix
- stack.yaml
- wallet-api/src/Wallet/Emulator/Client.hs
- wallet-api/src/Wallet/Emulator/Http.hs
- wallet-api/src/Wallet/Emulator/Types.hs
- wallet-api/src/Wallet/UTXO/Types.hs
- wallet-api/wallet-api.cabal
There are 2 parts to this PR (in 2 commits)
1. Clean up the HTTP server so that it reuses the existing machinery from `Trace`
2. Create an HTTP client for all the endpoints
I am actually unsure where to go from here. The client can't fit into `Trace` since that contains `EmulatedWalletApi` which is a wrapper around `StateT WalletState`. Basically I'm unsure how or where we now use this client?
Anyway, that would be the remit of another PR, I don't think it should stop this PR being merged.
> Http client

- default.nix
- plutus-use-cases/src/Language/Plutus/Coordination/Contracts/CrowdFunding.hs
- plutus-use-cases/src/Language/Plutus/Coordination/Contracts/Swap.hs
It seems like most people run with `-Werror` locally, so we should do it on CI too.
Why not do this in the cabal file? I think (like most people) that I often have warnings while I'm developing, and it would be annoying if it failed to compile at that point. So I think having it only turned on for CI is good behaviour.
> nix build: set -Werror

- core-to-plc/src/Language/Plutus/CoreToPLC/Compiler/Binders.hs
- core-to-plc/src/Language/Plutus/CoreToPLC/Compiler/Expr.hs
- core-to-plc/src/Language/Plutus/CoreToPLC/Compiler/Names.hs
- core-to-plc/src/Language/Plutus/CoreToPLC/Compiler/Type.hs
- core-to-plc/src/Language/Plutus/CoreToPLC/Compiler/Types.hs
Just a little refactoring - it makes sense for things in the scope envs to be vars rather than just names.
> Use PLCVar and PLCTyVar in a few more places

- .hlint.yaml
- language-plutus-core/generate-evaluation-test/Main.hs
- language-plutus-core/generators/Language/PlutusCore/Generators/Interesting.hs
- language-plutus-core/generators/Language/PlutusCore/Generators/Internal/TypedBuiltinGen.hs
- language-plutus-core/generators/Language/PlutusCore/Generators/Internal/Utils.hs
- language-plutus-core/generators/Language/PlutusCore/Generators/Test.hs
- language-plutus-core/src/Language/PlutusCore.hs
- language-plutus-core/src/Language/PlutusCore/Evaluation/CkMachine.hs
- language-plutus-core/src/Language/PlutusCore/Evaluation/Result.hs
- language-plutus-core/test/Evaluation/CkMachine.hs
- plutus-core-interpreter/src/Language/PlutusCore/Interpreter/CekMachine.hs
- plutus-core-interpreter/test/CekMachine.hs
The main thing here is
```haskell
-- | Generate a pair of files: @<folder>.<name>.plc@ and @<folder>.<name>.plc.golden@.
-- The first file contains a term generated by a term generator (wrapped in 'Program'),
-- the second file contains the result of evaluation of the term.
sampleProgramValueGolden
```
I need this in order to pass tests to the RV team.
Others are just refactoring and reduced code duplication.
> [CGP-398] [Test] Added a way to conveniently export interesting test files

- default.nix
- pkgs/default.nix
- plutus-ir/LICENSE
- plutus-ir/README.md
- plutus-ir/plutus-ir.cabal
- plutus-ir/shell.nix
- plutus-ir/src/Language/PlutusIR.hs
- plutus-ir/test/Spec.hs
- plutus-ir/test/prettyprinting/basic.plc.golden
- plutus-ir/test/prettyprinting/datatype.plc.golden
- release.nix
- stack.yaml
This adds the AST and some basic support functions for Plutus IR, following the design doc.
I've made the whole thing completely separate from `language-plutus-core` at the minute, which I think is the right thing to do. The `Term` AST is completely reproduced, since I don't think there's a clean way to reuse the PLC `Term` AST without using a "Trees that Grow"-style approach which I don't think we want to do yet, if ever. We do use the `Type` AST from PLC as-is, however.
> plutus-ir: init (CGP-395)

- plutus-core-spec/figures/PlutusCoreBuiltins.tex
This fixes a few bugs in the spec relating to builtin type arguments. Mostly these are cosmetic, but the first one makes it look like `resizeInteger` doesn't have failure conditions, which it certainly does.
> Spec: fix a few builtin type arguments

- core-to-plc/core-to-plc.cabal
- core-to-plc/src/Language/Plutus/CoreToPLC/Plugin.hs
- pkgs/default.nix
- plutus-th/src/Language/Plutus/TH.hs
- plutus-use-cases/src/Language/Plutus/Coordination/Contracts/CrowdFunding.hs
- plutus-use-cases/src/Language/Plutus/Coordination/Contracts/Swap.hs
- plutus-use-cases/src/Language/Plutus/Coordination/Contracts/Vesting.hs
- wallet-api/src/Wallet/UTXO/Index.hs
- wallet-api/src/Wallet/UTXO/Types.hs
This makes `PlcCode` something that's only used by the plugin, which is good, because then we can change its internal representation without affecting anything else (and that internal representation is largely determined by what is convenient for the plugin).
Therefore `wallet-api` gains a new `Script` type, along with functions for interacting with it. This is also nice because it makes our implementation closer to the original model, where `Script` was opaque.
I also did another quick change which I've meant to do for a while, which is to make `plutus-th` re-export the builtin names from `core-to-plc`. That way you can reference them without explicitly using the `core-to-plc` package. Eventually users shouldn't use that at all, once we can finally use `addCorePlugin`.
> wallet-api: gain own abstract Script type

- language-plutus-core/test/TypeSynthesis/Golden/ModInteger.plc.golden
- language-plutus-core/test/TypeSynthesis/Golden/QuotientInteger.plc.golden
These just needed to be committed - `cabal test` just generates them and succeeds otherwise.
I noticed they also popped up in https://github.com/input-output-hk/plutus/pull/236, presumably for a similar reason.
> Add two missing golden files

- core-to-plc/src/Language/Plutus/CoreToPLC/Compiler/Binders.hs
- core-to-plc/src/Language/Plutus/CoreToPLC/Compiler/Definitions.hs
- core-to-plc/src/Language/Plutus/CoreToPLC/Compiler/Expr.hs
- core-to-plc/src/Language/Plutus/CoreToPLC/Compiler/Names.hs
- core-to-plc/src/Language/Plutus/CoreToPLC/Compiler/Type.hs
- core-to-plc/src/Language/Plutus/CoreToPLC/PLCTypes.hs
- core-to-plc/src/Language/Plutus/Lift.hs
- language-plutus-core/src/Language/PlutusCore/MkPlc.hs
- language-plutus-core/src/Language/PlutusCore/Quote.hs
- language-plutus-core/stdlib/Language/PlutusCore/StdLib/Data/Bool.hs
- language-plutus-core/stdlib/Language/PlutusCore/StdLib/Data/Function.hs
- plutus-ir/src/Language/PlutusIR.hs
- plutus-ir/src/Language/PlutusIR/Compiler/Datatype.hs
- plutus-ir/src/Language/PlutusIR/Compiler/Recursion.hs
- plutus-ir/src/Language/PlutusIR/Compiler/Term.hs
- plutus-ir/src/Language/PlutusIR/Compiler/Types.hs
- plutus-ir/test/Spec.hs
Share the VarDecl types across language-plutus-core and dependents
This makes the interface to `MkPlc` a bit more expressively typed,
namely we add
- `VarDecl` and `TyVarDecl` representing "declarations" of variables,
i.e. pais of names and types/kinds.
- `Def` (and applied synonyms `TermDef` and `TypeDef`) representing a
pair of a variable declaration and a value.
We then use these in the `MkPlc` functions.
We can furthermore use them in both `core-to-plc` and `plutus-ir`, which
both have similar notions. In `plutus-ir` we actually use them as part
of the AST, which saves us a great deal of shuffling back and forth when
using the `MkPlc` functions.
> Share the VarDecl types across language-plutus-core and dependents

- language-plutus-core/src/Language/PlutusCore/Constant/Make.hs
The toBoundsInt function is called after every operation on sized integers.  It was previously evaluating 2^(8*size-1), which took a long time for large sizes.  This PR uses Data.Bits.bit to set the appropriate bit directly, which is much quicker.  For large values of `size` this can still allocate huge amounts of memory very quickly, but we'll let the cost model deal with that instead of enforcing a hard limit.
> Improve bounds check for sized integers

- language-plutus-core/language-plutus-core.cabal
- language-plutus-core/src/Language/PlutusCore.hs
- plutus-ir/src/Language/PlutusIR/Compiler.hs
- plutus-ir/src/Language/PlutusIR/Compiler/Datatype.hs
- plutus-ir/src/Language/PlutusIR/Compiler/Error.hs
- plutus-ir/src/Language/PlutusIR/Compiler/Term.hs
- plutus-ir/src/Language/PlutusIR/Compiler/Types.hs
- plutus-ir/test/Spec.hs
- plutus-ir/test/datatypes/listMatch.plc.golden
- plutus-ir/test/datatypes/listMatchEval.plc.golden
- plutus-ir/test/datatypes/maybe.plc.golden
- plutus-ir/test/recursion/even3.plc.golden
- plutus-ir/test/recursion/even3Eval.plc.golden
Non-exhaustive list:
- Need to run PIR term generation and compilation in the same `Quote`
monad to avoid compilation introducing names that are not fresh.
- The types of constructors weren't quantifying out the type variables.
- Various subtleties about making sure that we use the abstract/concrete
version of types where we need to.
List-based examples don't work, of course, since we still can't
typecheck that stuff.
> plutus-ir: typecheck test output and fix many bugs

- shell.nix
fd is parallel, this gives a nice 4x speedup on my machine.
`stylish-haskell` itself seems to take almost 5 times longer to start in the nix shell than in my shell, but I leave that mystery for another time.
> Use fd instead of find to speedup fixStylishHaskell

- plutus-use-cases/src/Language/Plutus/Coordination/Contracts/Vesting.hs
- plutus-use-cases/src/Language/Plutus/Runtime/TH.hs
- plutus-use-cases/test/Spec/Vesting.hs
- wallet-api/src/Wallet/UTXO/Index.hs
- wallet-api/src/Wallet/UTXO/Runtime.hs
- wallet-api/src/Wallet/UTXO/Types.hs
* Previously the `PendingTx` type (representing the transaction that is
being validated in a PLC validator script) used `Int`s instead of
`ByteString`s for hashes
* With this commit we use the correct `ByteString` type and get all
hashes from the mockchain, instead of having to use stand-in values
* Note that this also changes the UTXO model in `Wallet.UTXO.Types`:
The `PayToScript` constructor of `TxOutType` now contains the hash of
the validator script as a field, where previously that hash was included
implicitly, in the address generated by `scriptTxOut` in the same
module.
The address is a combined hash of value, validator and data script.
However, if we want to ensure that transaction outputs are locked by a
specific validator script, we need to look at the hash of that script
on …
> [CGP-400] Use bytestrings and proper hashes

- language-plutus-core/src/Language/PlutusCore.hs
Added in both https://github.com/input-output-hk/plutus/pull/246 and https://github.com/input-output-hk/plutus/pull/235, semantic merge conflict.
> Fix duplicate export

- core-to-plc/src/Language/Plutus/CoreToPLC/Compiler/Definitions.hs
- core-to-plc/src/Language/Plutus/CoreToPLC/Compiler/Names.hs
- core-to-plc/src/Language/Plutus/CoreToPLC/Compiler/Type.hs
- core-to-plc/test/IllTyped.hs
- core-to-plc/test/Spec.hs
- core-to-plc/test/data/monomorphic/nonValueCase.plc.golden
- core-to-plc/test/data/newtypes/nestedNewtypeMatch.plc.golden
- core-to-plc/test/recursiveTypes/ptreeConstruct.plc.golden
- core-to-plc/test/recursiveTypes/ptreeMatch.plc.golden
These had crept in as testing the error message when they shouldn't be failing at all. Two bugs (see commit messages for details):
- Dependencies were the wrong way around (not sure how that happened
- Unit needs to be non-abstract (*shakes fist at value restriction*)
- Move a test that does in fact typecheck
> core-to-plc: fix a couple of bugs

- core-to-plc/src/Language/Plutus/CoreToPLC/Compiler/Definitions.hs
- core-to-plc/src/Language/Plutus/CoreToPLC/Compiler/Expr.hs
- core-to-plc/src/Language/Plutus/CoreToPLC/Compiler/Type.hs
- core-to-plc/src/Language/Plutus/Lift.hs
- language-plutus-core/generators/Language/PlutusCore/Generators/Interesting.hs
- language-plutus-core/src/Language/PlutusCore/Constant/Make.hs
- language-plutus-core/src/Language/PlutusCore/MkPlc.hs
- language-plutus-core/stdlib/Language/PlutusCore/StdLib/Data/Bool.hs
- language-plutus-core/stdlib/Language/PlutusCore/StdLib/Data/ChurchNat.hs
- language-plutus-core/stdlib/Language/PlutusCore/StdLib/Data/Function.hs
- language-plutus-core/stdlib/Language/PlutusCore/StdLib/Data/Integer.hs
- language-plutus-core/stdlib/Language/PlutusCore/StdLib/Data/List.hs
- language-plutus-core/stdlib/Language/PlutusCore/StdLib/Data/Nat.hs
- language-plutus-core/stdlib/Language/PlutusCore/StdLib/Meta.hs
- language-plutus-core/stdlib/Language/PlutusCore/StdLib/Meta/Data/Tuple.hs
- plutus-ir/src/Language/PlutusIR/Compiler/Datatype.hs
- plutus-ir/src/Language/PlutusIR/Compiler/Recursion.hs
- plutus-ir/src/Language/PlutusIR/Compiler/Term.hs
- plutus-ir/test/Spec.hs
I would like to give proper annotations to some of the PLC and PIR that
I'm generating, with at least some kind of identifying information.
So I need the `MkPlc` functions to take an annotation for the new terms.
I think this is not *too* bad - we have to scatter some more `()`s
around, but we already have to do this for more-or-less every term
construction.
> MkPlc: take annotation for new constructs

- wallet-api/src/Wallet/UTXO/Index.hs
- wallet-api/src/Wallet/UTXO/Types.hs
The concept of "funds at an address" only makes sense if the address (a hash) doesn't include the value.
> wallet-api: Address should not include value

- plutus-ir/plutus-ir.cabal
- plutus-ir/src/Language/PlutusIR/Value.hs
This is based on whether the compiled PIR term will be a PLC value. Fortunately, we can determine this statically without compiling the term: the only interesting case is `let`, which will always not be a value, since it compiles into applications/type instantiations.
This is used `core-to-plc`, so we need a PIR version.
> pir: add an isTermValue function

- core-to-plc/src/Language/Plutus/CoreToPLC/Compiler/Type.hs
- core-to-plc/src/Language/Plutus/Lift.hs
- language-plutus-core/src/Language/PlutusCore.hs
- language-plutus-core/src/Language/PlutusCore/MkPlc.hs
- language-plutus-core/stdlib/Language/PlutusCore/StdLib/Data/Function.hs
- language-plutus-core/stdlib/Language/PlutusCore/StdLib/Meta/Data/Tuple.hs
- plutus-ir/plutus-ir.cabal
- plutus-ir/src/Language/PlutusIR.hs
- plutus-ir/src/Language/PlutusIR/Compiler.hs
- plutus-ir/src/Language/PlutusIR/Compiler/Datatype.hs
- plutus-ir/src/Language/PlutusIR/Compiler/Error.hs
- plutus-ir/src/Language/PlutusIR/Compiler/Provenance.hs
- plutus-ir/src/Language/PlutusIR/Compiler/Recursion.hs
- plutus-ir/src/Language/PlutusIR/Compiler/Term.hs
- plutus-ir/src/Language/PlutusIR/Compiler/Term.hs-boot
- plutus-ir/src/Language/PlutusIR/Compiler/Types.hs
- plutus-ir/test/Spec.hs
- plutus-ir/test/errors/mutuallyRecursiveTypes.plc.golden
- plutus-ir/test/errors/mutuallyRecursiveValues.plc.golden
This adds the concept of a `Provenance` to PIR. A `Provenance` is either an underlying annotation, or a piece of context relating the current term to another `Provenance`.
In practice this means that we can say something like `A type error occurred in the pattern functor for List; at <location>`, which is handy.
At the moment we don't have any terms with interesting underlying annotations, so this is not so useful. Even once we hook this up to `core-to-plc`, that still gives everything annotation `()`! But that can be changed - the nice thing about `Provenance`s is that they make sense across domains. So we can eventually say `A type error occurred in the pattern functor for List; from the Haskell datatype List; at <location>`.
This also answers a separate question: don't I already do …
> PIR: learn about provenances

- language-plutus-core/generators/Language/PlutusCore/Generators/Interesting.hs
- language-plutus-core/language-plutus-core.cabal
- language-plutus-core/src/Language/PlutusCore.hs
- language-plutus-core/src/Language/PlutusCore/Check/Normal.hs
- language-plutus-core/src/Language/PlutusCore/Normalize.hs
- language-plutus-core/src/Language/PlutusCore/TypeSynthesis.hs
This
1. moves `Language.PlutusCore.Normalize` to `Language.PlutusCore.Check.Normal`. We will have more checks (at least three more), so I made a folder for that
2. Unties type normalization from type checking
3. Sprinkles `rename` on term generators, because I was too lazy to prepare a separate pull request
I'll add some more docs, so do not merge yet.
> [CGP-405] Separated type normalization from type checking

- plutus-use-cases/plutus-use-cases.cabal
- plutus-use-cases/src/Language/Plutus/Coordination/Contracts/CrowdFunding.hs
- plutus-use-cases/src/Language/Plutus/Coordination/Contracts/Future.hs
- plutus-use-cases/src/Language/Plutus/Coordination/Contracts/Swap.hs
- plutus-use-cases/src/Language/Plutus/Coordination/Contracts/Vesting.hs
- plutus-use-cases/src/Language/Plutus/Runtime.hs
- plutus-use-cases/src/Language/Plutus/Runtime/TH.hs
- plutus-use-cases/test/Spec.hs
- plutus-use-cases/test/Spec/Future.hs
- wallet-api/src/Wallet/UTXO/Index.hs
- wallet-api/src/Wallet/UTXO/Runtime.hs
* Add a futures contract that demonstrates variable margins, oracles and
"actions" that can be performed on a contract (through the redeemer
script)
> use-cases: Add futures contract

- core-to-plc/test/Spec.hs
- language-plutus-core/common/PlcTestUtils.hs
- pkgs/default.nix
- plutus-ir/plutus-ir.cabal
- plutus-ir/test/Spec.hs
This makes `getProgram` do less, by:
- Not trying to be clever about catching exceptions. The class method
now expects the exceptions to be caught, and the non-catching test
methods just rethrow them to fail the test.
- Not trying to be clever about turning lots of things into `Program`s,
in favour of just scattering a few more explicit conversions around.
> plc testlib: make less implicit

- .hlint.yaml
- language-plutus-core/language-plutus-core.cabal
- plutus-ir/plutus-ir.cabal
- plutus-ir/src/Language/PlutusIR/Optimizer/DeadCode.hs
- plutus-ir/test/OptimizerSpec.hs
- plutus-ir/test/Spec.hs
- plutus-ir/test/TestLib.hs
- plutus-ir/test/optimizer/deadCode/datatypeDead.plc.golden
- plutus-ir/test/optimizer/deadCode/datatypeLiveConstr.plc.golden
- plutus-ir/test/optimizer/deadCode/datatypeLiveDestr.plc.golden
- plutus-ir/test/optimizer/deadCode/datatypeLiveType.plc.golden
- plutus-ir/test/optimizer/deadCode/nestedBindings.plc.golden
- plutus-ir/test/optimizer/deadCode/recBindingComplex.plc.golden
- plutus-ir/test/optimizer/deadCode/recBindingSimple.plc.golden
- plutus-ir/test/optimizer/deadCode/singleBinding.plc.golden
- plutus-ir/test/optimizer/deadCode/termLet.plc.golden
- plutus-ir/test/optimizer/deadCode/typeLet.plc.golden
This adds a simple optimization pass to the PIR library that removes
unused let bindings. At the moment it is fairly stupid, and doesn't
attempt to separate out usage checking or handle complex recursive
bindings.
The context for this is that I am planning to change the codegen for builtins in the plugin to unconditionally generate bindings for all the builtins. Most of these won't be used, so this pass will clear that up so we don't get illegible codegen for simple cases.
(If anyone has any clever suggestions about how to separate out the usage analysis or handle recursive bindings cleanly then let me know - I have some ideas but they'd be a bit more work).
> pir: add a simple dead binding removal pass

- default.nix
- iohk-nix.json
- pkgs/default.nix
- pkgs/regen.nix
- stack.yaml
This gets us to the last major version of GHC, which seems like a good place to be. Also there are a few bits and pieces from some of the newer package versions that I've wanted to use, so that's nice.
I've tested that this evaluates properly, but I haven't built things yet since it needs to rebuild the deps, and I want to let the CI do that for me :)
@disassembler  I think the first commit here might be of particular interest to you - I imagine this will bite anywhere else we're using `stack2nix`, but the fix is straightforward. It manifested as me getting errors because on my host machine's version of `nixos-unstable` they've removed `ghc843`.
> Update stackage snapshot to 12.14

- core-to-plc/test/recursiveFunctions/fib.plc.golden
I don't understand how this can have ended up failing on master. I'm a little worried that maybe something like the SCC algorithm I'm using is non-deterministic, but for now, fix the problem.
> core-to-plc: Fix mysteriously failing test

- .hlint.yaml
- core-to-plc/core-to-plc.cabal
- core-to-plc/src/Language/Plutus/CoreToPLC/Builtins.hs
- core-to-plc/src/Language/Plutus/CoreToPLC/Compiler/Builtins.hs
- core-to-plc/src/Language/Plutus/CoreToPLC/Compiler/Definitions.hs
- core-to-plc/src/Language/Plutus/CoreToPLC/Compiler/Error.hs
- core-to-plc/src/Language/Plutus/CoreToPLC/Compiler/Expr.hs
- core-to-plc/src/Language/Plutus/CoreToPLC/Compiler/Kind.hs
- core-to-plc/src/Language/Plutus/CoreToPLC/Compiler/Laziness.hs
- core-to-plc/src/Language/Plutus/CoreToPLC/Compiler/Names.hs
- core-to-plc/src/Language/Plutus/CoreToPLC/Compiler/Primitives.hs
- core-to-plc/src/Language/Plutus/CoreToPLC/Compiler/Type.hs
- core-to-plc/src/Language/Plutus/CoreToPLC/Compiler/Types.hs
- core-to-plc/src/Language/Plutus/CoreToPLC/Compiler/Utils.hs
- core-to-plc/src/Language/Plutus/CoreToPLC/Compiler/ValueRestriction.hs
- core-to-plc/src/Language/Plutus/CoreToPLC/Plugin.hs
- core-to-plc/src/Language/Plutus/CoreToPLC/Utils.hs
- core-to-plc/src/Language/Plutus/Lift.hs
- plutus-ir/src/Language/PlutusIR/Compiler.hs
- plutus-ir/src/Language/PlutusIR/Compiler/Error.hs
- plutus-ir/src/Language/PlutusIR/Compiler/Types.hs
- plutus-ir/test/Spec.hs
- Rename `CompError` to `Error` for consistency.
- Add an export list to `Builitns`
- Move a couple of modules to more logical locations.
> core-to-plc/pir: minor tidying

- core-to-plc/src/Language/Plutus/CoreToPLC/Compiler/Expr.hs
- core-to-plc/src/Language/Plutus/CoreToPLC/Compiler/Type.hs
- core-to-plc/test/Spec.hs
- core-to-plc/test/data/monomorphic/monoCase.plc.golden
- core-to-plc/test/data/polymorphic/defaultCasePoly.plc.golden
We were using the wrong types for the arguments for the default case.
e.g. for `Just Int` we need a function that takes an `Int` but we were
trying to create on that takes an `a`! So we need to get the
instantiated argument types instead, which fortunately we can do.
I'm pretty sure this fixes CGP-327 as well.
> core-to-plc: fix default cases for polymorphic datatypes

- plutus-th/src/Language/Plutus/TH.hs
- plutus-th/test/Spec.hs
This means that users of the TH function don't need the `OPTIONS`
pragma unless they actually need to pass options to the plugin. Sadly,
most of the current users do, since they need to turn off typechecking
until we sort out recursive types.
> plutus-th: use addCorePlugin

- language-plutus-core/generators/Language/PlutusCore/Generators/Internal/Denotation.hs
- language-plutus-core/prelude/PlutusPrelude.hs
- language-plutus-core/test/Evaluation/Constant/Failure.hs
- language-plutus-core/test/Evaluation/Constant/Success.hs
- language-plutus-core/test/Evaluation/Constant/SuccessFailure.hs
- plutus-core-interpreter/test/Main.hs
- plutus-exe/src/Main.hs
- plutus-ir/src/Language/PlutusIR/Compiler/Datatype.hs
- wallet-api/src/Wallet/UTXO/Types.hs
Our CI `-Werror` got lost when we switched to `iohk-nix`. I'm working with @disassembler to get it working, but we do need to stay warning-free othewise that PR will be a pain!
This fixes a few warnings that have snuck in, mainly due to the newer version of `base` that we're compiling with. (We *do* have the correct bounds for `base` in our cabal files - `Semigroup` was added in 4.9. I'm not sure how this worked before TBH).
> Fix some warnings

- pkgs/default.nix
- plutus-use-cases/src/Language/Plutus/Coordination/Contracts/CrowdFunding.hs
- plutus-use-cases/src/Language/Plutus/Coordination/Contracts/Vesting.hs
- wallet-api/src/Wallet/API.hs
- wallet-api/src/Wallet/Emulator/AddressMap.hs
- wallet-api/src/Wallet/Emulator/Client.hs
- wallet-api/src/Wallet/Emulator/Http.hs
- wallet-api/src/Wallet/Emulator/Types.hs
- wallet-api/src/Wallet/UTXO/Index.hs
- wallet-api/src/Wallet/UTXO/Runtime.hs
- wallet-api/src/Wallet/UTXO/Types.hs
- wallet-api/test/Spec.hs
- wallet-api/wallet-api.cabal
* Implement `register :: EventTrigger -> m () -> m ()` (part of the `WalletAPI` class) for emulator
* Each wallet has a list of registered event triggers that it checks whenever a `NotifyBlock` notification is received from the blockchain
* The `fundsAtAddress` condition required some changes in the way we keep track of funds at an address. Previously each wallet was only interested in a single address (that of its own keypair), but now we have a list of arbitrary addresses with their unspent transaction outputs.
* Also, the address of a pay-to-script output is now the hash of its validator script *only*. Previously it included the hash of the data script. Now we can have a plutus contract with a single address where each payment to that address has a different data script, for example to …
> [CGP-376] Blockchain event triggers in wallet API

- plutus-ir/src/Language/PlutusIR/Compiler/Datatype.hs
- plutus-ir/src/Language/PlutusIR/Compiler/Types.hs
This delegates the job of building the `Fix` types and `Wrap`s to the `RecursiveType` functions in the stdlib. In fact this not doing any work for us at all - we are just hiding our normal construction inside it. However, we should be able to just drop in `makeRecursiveType` from https://github.com/input-output-hk/plutus/pull/245 and have this work with the `ifix` machinery.
Usually when using this you would want to be using `rename` appropriately, but in the PIR compiler we just run it at the end, so we don't bother here.
As a minor bonus we can use whether or not we have a `RecursiveType` to make decisions about whether or not to wrap, rather than passing around a `Recursivity`, which was slightly overloading the meaning of that type anyway.
> plutus-ir: use the stdlib's RecursiveType machinery

- language-plutus-core/src/Language/PlutusCore/CBOR.hs
- language-plutus-core/test/Spec.hs
Serialize annotations on PLC terms. This is helpful because we want to
serialize position/provenance information along with terms on the
mockchain for diagnostic purposes.
As a proof of concept, the round-tripping test now includes the positions.
This *does* change the encoding of the PLC that we will put on the chain,
because now we write in all the unit annotations. However, it doesn't
put us in danger of the encoding changing in future, because we will
always be setting the annotation type to `()`. I don't think the additional
cost of serializing a byte for each unit annotation is a problem in
terms of serialization size, so I'm inclined to just accept that for
simplicity.
I've written a more extensive note about making sure the encoding is
stable in the code. I think at some point we …
> language-plutus-core: serialize annotations

- pkgs/default.nix
- plutus-ir/plutus-ir.cabal
- plutus-ir/src/Language/PlutusIR/Analysis/Dependencies.hs
- plutus-ir/src/Language/PlutusIR/Analysis/Usages.hs
- plutus-ir/src/Language/PlutusIR/Optimizer/DeadCode.hs
- plutus-ir/test/OptimizerSpec.hs
- plutus-ir/test/optimizer/deadCode/recBindingComplex.plc.golden
This is a pretty inessential PR implemented mostly for my own satisfaction. It makes things a bit nicer and a bit more made of separately usable components. As a bonus, it does now have better handling of recursive lets, improving the results on one of the tests.
- PIR learns a variable usage analysis
- The usage analysis for types could be moved to `language-plutus-core` in future.
- PIR learns a variable dependency graph analysis using algebraic graphs
- This delegates to the usage analysis in the case of types, as they have no internal let-bindings.
- The dead-binding analysis simply uses the dependency graph to compute the set of live bindings, and then uses that.
> plutus-ir: implement dead-code checker in terms of dependency graphs

- plutus-core-spec/figures/PlutusCoreReduction.tex
- plutus-core-spec/figures/PlutusCoreTypeCorrectness.tex
- plutus-core-spec/main.tex
Pursuant to [CGP 411](https://iohk.myjetbrains.com/youtrack/issue/CGP-411).
This branch replaces the main type system we currently have w/ one that uses a declarative equality for types only. In all the places where we rely on type normalization and normality, we explicit reduction and equality.
Of particular note, the judgment `Γ ⊢ M : S` is now `Γ ⊢ M : A` where the type can be an arbitrary type, thereby necessitating that every places we relied on its normality, we instead explicitly reduce. This means that in eliminators, where we would normally simply "match" on the synthesized type to verify that it has the right form (eg. `A → B` or `∀a. B`), we instead have to reduce it (eg. `C →ty* A → B`). Equality itself is only ever used to equate two synthesized types (i.e. in the rule for …
> [CGP-411] Declarative Type System

- default.nix
- iohk-nix.json
- lib.nix
- nix/overlays/required.nix
- nixpkgs-src.json
- plutus-ir/src/Language/PlutusIR/Compiler/Term.hs
- release.nix
@michaelpj This switches plutus to use the nixpkgs-src.json set by default in iohk-nix.
> iohk-nix bump and improvements

- core-to-plc/src/Language/Plutus/CoreToPLC/Compiler/Expr.hs
- core-to-plc/src/Language/Plutus/CoreToPLC/Compiler/Primitives.hs
- core-to-plc/test/Plugin/Spec.hs
- core-to-plc/test/Plugin/primitives/intDiv.plc.golden
Need this for `div` and `rem` on `Int`.
> core-to-plc: support integral methods

- README.md
- default.nix
- docs/fomega/lazy-machine/README.md
- docs/fomega/lazy-machine/default.nix
- release.nix
So the lazy machine doc can be built with nix and built by CI.
I tried to make it so everything in the `docs` attr set gets built on linux, let's see if I succeeded.
> Build: build lazy machine doc with nix and on CI

- pkgs/default.nix
- plutus-use-cases/plutus-use-cases.cabal
- plutus-use-cases/src/Language/Plutus/Coordination/Contracts/CrowdFunding.hs
- plutus-use-cases/src/Language/Plutus/Coordination/Contracts/Future.hs
- plutus-use-cases/src/Language/Plutus/Coordination/Contracts/Vesting.hs
- plutus-use-cases/src/Language/Plutus/Runtime/TH.hs
- plutus-use-cases/test/Spec/Crowdfunding.hs
- plutus-use-cases/test/Spec/Future.hs
- plutus-use-cases/test/Spec/Vesting.hs
- wallet-api/src/Wallet/API.hs
- wallet-api/src/Wallet/Emulator/AddressMap.hs
- wallet-api/src/Wallet/Emulator/Client.hs
- wallet-api/src/Wallet/Emulator/Http.hs
- wallet-api/src/Wallet/Emulator/Types.hs
- wallet-api/src/Wallet/UTXO/Runtime.hs
- wallet-api/test/Spec.hs
* Use blockchain triggers to handle refund and collect outcomes of the contract
* Extend contract to handle an arbitrary number of contributions
* Remove most type annotations in the script
* When registering an action in the wallet API, the user now gets the list of the unspent outputs at the relevant addresses (otherwise we can't consume anything from that address in response to the trigger)
> plutus-use-cases: Crowdfunding improvements

- plutus-th/src/Language/Plutus/TH.hs
- plutus-th/test/Spec.hs
- plutus-th/test/TestTH.hs
- plutus-use-cases/src/Language/Plutus/Coordination/Contracts/CrowdFunding.hs
- plutus-use-cases/src/Language/Plutus/Coordination/Contracts/Future.hs
- plutus-use-cases/src/Language/Plutus/Coordination/Contracts/Swap.hs
- plutus-use-cases/src/Language/Plutus/Coordination/Contracts/Vesting.hs
- wallet-api/src/Wallet/UTXO/Types.hs
We used to have a typed TH version of the `plutus` function, but I removed it because I couldn't do the type literal stuff properly with typed TH and I was squeamish about `unsafeTExpCoerce`.
Writing a tutorial for using `plutus-th`, I was embarassed not to have the typed TH function available, since it's just a lot better to work with. So I've got over my queasiness and boxed the `unsafeTExpCoerce` into a small box.
I also made it the default, and replaced the current usages with `plutusUntyped`. I think @j-mueller wanted the typed version anyway, but using it properly will require changing all the helper functions in `plutus-use-cases` to be typed too, so I'll let him do that as and when he feels like it.
> plutus-th: add back typed TH function, make it the default

- wallet-api/src/Wallet/Emulator/Http.hs
- wallet-api/src/Wallet/Emulator/Log.hs
- wallet-api/src/Wallet/Emulator/Types.hs
- wallet-api/src/Wallet/UTXO/Index.hs
- wallet-api/test/Spec.hs
- wallet-api/wallet-api.cabal
* Emulator keeps a log of blockchain-related events such as transaction
validation
> [CGP-424] Add emulator events

- language-plutus-core/language-plutus-core.cabal
- language-plutus-core/src/Language/PlutusCore/CBOR.hs
- language-plutus-core/src/Language/PlutusCore/Constant/Apply.hs
- language-plutus-core/src/Language/PlutusCore/Constant/Dynamic.hs
- language-plutus-core/src/Language/PlutusCore/Constant/Dynamic/BuiltinName.hs
- language-plutus-core/src/Language/PlutusCore/Constant/Dynamic/Instances.hs
- language-plutus-core/src/Language/PlutusCore/Constant/Make.hs
- language-plutus-core/src/Language/PlutusCore/Lexer/Type.hs
- language-plutus-core/src/Language/PlutusCore/Pretty/Classic.hs
- language-plutus-core/src/Language/PlutusCore/Pretty/Readable.hs
- language-plutus-core/src/Language/PlutusCore/Type.hs
- language-plutus-core/src/Language/PlutusCore/TypeSynthesis.hs
- plutus-core-interpreter/test/DynamicBuiltins/Logging.hs
- plutus-core-interpreter/test/DynamicBuiltins/String.hs
Turns out to be trivial.
A bit hacky, because we just do everything through `KnownDynamicBuiltinType` (which I now realize should be renamed to `KnownBuiltinType`), but it's hacky not because we use `KnownDynamicBuiltinType`, but because we do not use it for old stuff like `boolean` and perhaps even `integer` and others.
This does not solve the problem with logging and the heavy handling machinery. We still need to emit strings somehow. Unless you want to juggle them on the PLC side which is fine, but I think is tedious.
Two tests are commented out, because they no longer work, because we can't convert a `Char` or a `[String]` to PLC.
Feel free to merge or ignore.
> [CGP-418] [AST] Added 'String's to the AST

- default.nix
- pkgs/default.nix
- plutus-tx/README.lhs
- plutus-tx/README.md
- plutus-tx/doctests.hs
- plutus-tx/plutus-tx.cabal
- plutus-tx/src/Language/PlutusTx/TH.hs
- plutus-use-cases/src/Language/Plutus/Coordination/Contracts/CrowdFunding.hs
- plutus-use-cases/src/Language/Plutus/Coordination/Contracts/Future.hs
- plutus-use-cases/src/Language/Plutus/Coordination/Contracts/Swap.hs
- plutus-use-cases/src/Language/Plutus/Coordination/Contracts/Vesting.hs
- plutus-use-cases/src/Language/Plutus/Runtime/TH.hs
- release.nix
This adds a basic tutorial on PlutusTx. It's focussed on just the PlutusTx bit, so nothing about how to actually write contracts, just how to use the plugin and the TH stuff.
I've used `markdown-unlits` and `doctest` to extract the Haskell from the tutorial and compile and doctest it,  thus ensuring that it actually works and continues working!
In the process I noticed a number of things that were not good, some of which I have fixed and others of which have TODOs.
Other fixes:
- I didn't realise this, but https://github.com/input-output-hk/plutus/pull/326 changes the shape of the generated expression so we can't recognize it unless GHC does some simplification first! This is very bad, so I went back to the old way, although it means `unsafeTExpCoerce` gets a little further out of its …
> plutus-tx: add a basic tutorial

- language-plutus-core/language-plutus-core.cabal
- language-plutus-core/prelude/PlutusPrelude.hs
- language-plutus-core/src/Language/PlutusCore.hs
- language-plutus-core/src/Language/PlutusCore/Analysis/Definitions.hs
- language-plutus-core/src/Language/PlutusCore/Check/Uniques.hs
- language-plutus-core/src/Language/PlutusCore/Error.hs
- language-plutus-core/src/Language/PlutusCore/Lexer.x
- language-plutus-core/src/Language/PlutusCore/Name.hs
- language-plutus-core/src/Language/PlutusCore/Quote.hs
- language-plutus-core/src/Language/PlutusCore/Type.hs
- language-plutus-core/test/Check/Spec.hs
- language-plutus-core/test/Spec.hs
- language-plutus-core/test/types/addInteger.plc
- language-plutus-core/test/types/addInteger.plc.golden
This adds some analysis code for variable usages, along with a
checker for a number of issues:
- Free variables
- Incoherently used variables (i.e. in both the term and type scopes)
- Multiply defined variables
We can then check that after running the renamer we pass the appropriate
checks.
This turned up one annoying issue. The renamer normally fixes "incoherent usage" issues for bound variables by renaming the two definitions (and hence uses) to be separate. However, it doesn't rename free variables, so if you have incoherently used free variables it won't fix it.
> Add basic sanity checking for unique usage

- language-plutus-core/src/Language/PlutusCore/Check/Normal.hs
- language-plutus-core/test/types/addInteger.plc
- language-plutus-core/test/types/addInteger.plc.golden
As we discussed in a meeting some time ago (and is detailed in https://iohk.myjetbrains.com/youtrack/issue/CGP-295), the old version of the spec lacked a special case to make builtin type applications into type values, which means that you can't typecheck any programs with integer types in annotations in on-chain mode. (The reason this hasn't been driving me up the wall is that all the programs I generate get typechecked in off-chain mode, but I believe it's annoying @kwxm a fair bit.)
The approach we decided to take was to switch to fully-saturated builtins, and @psygnisfive has made this change in the spec. However, the implementation hasn't caught up, and is unlikely to catch up for some time (likely well after PlutusFest). So we are still stuck with the bug at the moment.
However, …
> [CGP-295] Consider builtin type applications to be neutral

- plutus-use-cases/src/Language/Plutus/Coordination/Contracts/CrowdFunding.hs
- plutus-use-cases/src/Language/Plutus/Coordination/Contracts/Future.hs
- plutus-use-cases/src/Language/Plutus/Coordination/Contracts/Vesting.hs
- plutus-use-cases/test/Spec/Future.hs
- plutus-use-cases/test/Spec/Vesting.hs
- wallet-api/src/Wallet/UTXO/Index.hs
- wallet-api/src/Wallet/UTXO/Runtime.hs
- wallet-api/src/Wallet/UTXO/Types.hs
* `newtype Value = Value Int` means we can use the same type for ada
values PLC and Haskell, which allows us to get rid of a few
`fromIntegral`s
> wallet-api: Int instead Integer for value

- wallet-api/src/Wallet/UTXO/Types.hs
Among other things, this gives JSON instances that are naturally
compatible with PureScript bridge.
> Deriving many wallet JSON instances via `anyclass`.

- wallet-api/src/Wallet/Emulator/Http.hs
- wallet-api/src/Wallet/Emulator/Types.hs
- wallet-api/test/Spec.hs
* Field name indicates the order of blocks in the blockchain
> wallet-api: Be explicit about block order

- language-plutus-core/src/Language/PlutusCore.hs
- language-plutus-core/src/Language/PlutusCore/TypeSynthesis.hs
- plutus-exe/src/Main.hs
This fixes the following bug:
> We duplicate things during the annotation step, annotate each term-level variable with its type and then simply return that type while type checking instead of renaming it
Which reveals another bug: we `runQuoteT` right after parsing a program which is way too early. This is fixed too.
> [Uniques] Added renaming of types of variables during type checking

- default.nix
- plutus-tx/src/Language/PlutusTx/Prelude.hs
- plutus-use-cases/plutus-use-cases.cabal
- plutus-use-cases/src/Language/PlutusTx/Coordination/Contracts.hs
- plutus-use-cases/src/Language/PlutusTx/Coordination/Contracts/CrowdFunding.hs
- plutus-use-cases/src/Language/PlutusTx/Coordination/Contracts/Future.hs
- plutus-use-cases/src/Language/PlutusTx/Coordination/Contracts/Swap.hs
- plutus-use-cases/src/Language/PlutusTx/Coordination/Contracts/Vesting.hs
- plutus-use-cases/src/Language/PlutusTx/Validation.hs
- plutus-use-cases/src/Language/PlutusTx/Validation/TH.hs
- plutus-use-cases/test/Spec/Crowdfunding.hs
- plutus-use-cases/test/Spec/Future.hs
- plutus-use-cases/test/Spec/Vesting.hs
- wallet-api/src/Ledger.hs
- wallet-api/src/Ledger/Index.hs
- wallet-api/src/Ledger/Types.hs
- wallet-api/src/Ledger/Validation.hs
- wallet-api/src/Wallet.hs
- wallet-api/src/Wallet/API.hs
- wallet-api/src/Wallet/Emulator.hs
- wallet-api/src/Wallet/Emulator/AddressMap.hs
- wallet-api/src/Wallet/Emulator/Client.hs
- wallet-api/src/Wallet/Emulator/Http.hs
- wallet-api/src/Wallet/Emulator/Types.hs
- wallet-api/src/Wallet/Generators.hs
- wallet-api/src/Wallet/UTXO.hs
- wallet-api/test/Spec.hs
- wallet-api/wallet-api.cabal
wallet-api:
- `Wallet.UTXO` -> `Ledger`
- `Wallet.UTXO.Runtime` -> `Ledger.Validation`
- Trimmed some export lists to not re-export too much.
plutus-use-cases:
- `Language.Plutus` -> `Language.PlutusTx`
- `Language.Plutus.Runtime` -> `Language.PlutusTx.Validation`
- I also moved a bunch of the general functions from here to the PlutusTx Prelude, so this now only contains functions that work on the validation types.
- Possibly this should also move to `wallet-api`.
At this point you need the following imports to write a contract:
- `Language.PlutusTx` (PlutusTx functions)
- `Wallet` (wallet API types and functions)
- `Ledger` (transaction types and functions)
- `Ledger.Validation` (runtime validation types and functions)
- `Language.PlutusTx.Validation` (PlutusTx functions for working with …
> wallet-api/plutus-use-cases: more module shuffling

- plutus-exe/plutus-exe.cabal
- plutus-exe/src/Main.hs
Adds example types and programs to `plutus-exe`. There are two commands
```
~/code/iohk/plutus$ plc example --available
succInteger : (all s (size) (fun [(con integer) s] [(con integer) s]))
unit :: (type)
unitval : (all a (type) (fun a a))
bool :: (type)
true : (all a (type) (fun a (fun a a)))
false : (all a (type) (fun a (fun a a)))
churchNat :: (type)
churchZero : (all r (type) (fun r (fun (fun r r) r)))
churchSucc : (all r (type) (fun r (fun (fun r r) r)))
```
and
```
~/code/iohk/plutus$ plc example --single unitval
(program 1.0.0
(abs a (type) (lam x a x))
)
```
(where `unitval` can be any "available" name). There are intentionally no available tests with recursive types inside, because the RV team got confused (and rightfully so) about our partial implementation of elimination …
> [plutus-exe] Added examples

- plutus-ir/plutus-ir.cabal
- plutus-tx/plutus-tx.cabal
I used `weeder` to identify redundant library depends and removed them. I also used `cabal format` on a couple files to standardize things.
> Remove redundant library dependencies identified by weeder

- release.nix
For derivations where the check phase isn't split, we don't put anything
into the required jobset for them. This is okay if they're depended on,
but is a bit sketchy.
What we should do is include the main derivation in (at least) this
case, as it will include the tests.
I think I would prefer to just include all the main derivation to be
sure, but I can't figure out how to do that.
> CI: use the main derivation as the test derivation for things that aren't split check

- plutus-use-cases/tutorial/Tutorial.md
- wallet-api/src/Wallet/Emulator.hs
It's generally bad hygiene to re-export your dependencies, and I think
we want to emphasise that the wallet bits and the emulator bits come
from different places.
> wallet-api: don't re-export Wallet from Wallet.Emulator

- pkgs/default.nix
- plutus-playground/plutus-playground-lib/plutus-playground-lib.cabal
- plutus-playground/plutus-playground-lib/src/Playground/API.hs
- plutus-playground/plutus-playground-lib/src/Playground/TH.hs
- plutus-playground/plutus-playground-lib/tests/Spec.hs
* Add a test for `mkFunction` with some of the signatures that we expect to work. In particular we would like to use the concrete `MockWallet` monad instead of the `WalletAPI m` constraints.
* Change `Playground.TH.args` to support functions that end in `MockWallet ()`
> playground: Add test for mkFunction

- plutus-tx/src/Language/PlutusTx/Prelude.hs
- plutus-use-cases/src/Language/PlutusTx/Coordination/Contracts/CrowdFunding.hs
- plutus-use-cases/src/Language/PlutusTx/Coordination/Contracts/Future.hs
- plutus-use-cases/src/Language/PlutusTx/Coordination/Contracts/Swap.hs
- plutus-use-cases/src/Language/PlutusTx/Coordination/Contracts/Vesting.hs
- wallet-api/tutorial/Tutorial.md
* By exporting `Builtins.error` as a quoted expression we ensure that it
is used in exactly the same way as everything else that is exported from
that module
> plutus-tx: Prelude exports quoted Builtins.error

- plutus-tx/src/Language/PlutusTx/Prelude.hs
- plutus-tx/tutorial/tutorial-doctests.hs
* Better haddocks for the PlutusTx prelude, and some doctests
* Note: Some of the doctests for the TH quotes only work if the entire
expression is wrapped in the splicing operator. For example,
`$$(isJust) (Just "a")` fails to evaluate, but
`$$([|| $$(isJust) (Just "a") ]])` works. To make the
documentation consistent I wrote all of the doctests that way.
> plutus-tx: Improve documentation

- .hlint.yaml
- plutus-tx-plugin/plutus-tx-plugin.cabal
- plutus-tx-plugin/src/Language/PlutusTx/Lift.hs
- plutus-tx-plugin/src/Language/PlutusTx/Lift/Class.hs
- plutus-tx-plugin/src/Language/PlutusTx/Lift/Instances.hs
- plutus-tx-plugin/src/Language/PlutusTx/Plugin.hs
- plutus-tx-plugin/test/Lift/Spec.hs
- plutus-tx-plugin/test/Plugin/Spec.hs
- plutus-tx/tutorial/Tutorial.md
- wallet-api/src/Ledger/Types.hs
It's better not to try and indicate what we're lifting "to" in the
names, as TH does.
Just pushing through a few final renames for friendliness.
> Strip suffixes from the Lift class

- plutus-playground/plutus-playground-server/usecases/Vesting.hs
- plutus-use-cases/src/Language/PlutusTx/Coordination/Contracts/Future.hs
- plutus-use-cases/src/Language/PlutusTx/Coordination/Contracts/Vesting.hs
- wallet-api/src/Wallet/API.hs
- wallet-api/src/Wallet/Emulator/Client.hs
- wallet-api/src/Wallet/Emulator/Http.hs
- wallet-api/src/Wallet/Emulator/Types.hs
* Currently when we call `createPaymentWithChange` and happen to have
the exact amount, we get a transaction output containing the change of
zero. This is not incorrect - there are no fees in the
emulator, so even for the zero-cost output the cost of spending it is
not higher than its value. (That is, we can't have "dust" in the
mockchain).
* However, this might cause some problems in the playground, so it's
best to get rid of this behaviour.
> wallet-api: Do not return zero change

- docs/fomega/lazy-machine/cekmachine.tex
- docs/fomega/lazy-machine/ckmachine.tex
- docs/fomega/lazy-machine/lmachine.tex
There's a minor error that's propagated from the spec to the lazy evaluation document.  I'm just going to fix it directly since no-one cares much about this particular document.
> Fix persistent error in machine descriptions (lazy evaluation document)

- plutus-playground/plutus-playground-server/usecases/CrowdFunding.hs
- plutus-playground/plutus-playground-server/usecases/Game.hs
- plutus-playground/plutus-playground-server/usecases/Vesting.hs
- plutus-tx-plugin/src/Language/PlutusTx/Plugin.hs
- plutus-tx-plugin/test/Plugin/IllTyped.hs
- plutus-tx-plugin/test/Plugin/Spec.hs
- plutus-tx/src/Language/PlutusTx/TH.hs
- plutus-tx/test/Spec.hs
- plutus-tx/tutorial/Tutorial.md
- plutus-use-cases/src/Language/PlutusTx/Coordination/Contracts/CrowdFunding.hs
- plutus-use-cases/src/Language/PlutusTx/Coordination/Contracts/Future.hs
- plutus-use-cases/src/Language/PlutusTx/Coordination/Contracts/Swap.hs
- plutus-use-cases/src/Language/PlutusTx/Coordination/Contracts/Vesting.hs
- wallet-api/src/Ledger/Types.hs
- wallet-api/test/Spec.hs
- wallet-api/tutorial/Tutorial.md
These are I think the last things I want to rename before the conference.
- `PlcCode` -> `CompiledCode`
- I want to avoid mentioning PLC as much as possible.
- The more "opaque" the name here the better, since in future we may end up stuffing even more things in here (like additional debug information).
- Alternatives:
- `Code` (too generic IMO)
- `StagedCode`
- `plutus` -> `compile`
- This makes it much clearer what is actually happening, IMO.
- Fits nicely with `CompiledCode`: `compile :: TH.TExp a -> CompiledCode`
- Alternatives:
- `plutusTx` (I was originally going to use this, but then I thought of `compile`)
The `plutus` rename is the most user-facing one, so I'd like some opinions on that.
> PlutusTx: two final renames

- wallet-api/src/Wallet/Emulator/Types.hs
Wallets need to be notified after each block, otherwise the triggers will fire too late
> wallet-api: Notify after each block

- plutus-playground/plutus-playground-client/default.nix
- release.nix
We're not building it or running the tests, which is bad.
I think this adds it to `release.nix`, but in the process I discovered it doesn't build. Probably sandboxing issues.
I've fixed one (missing `python2` dep), but now I'm getting networking errors.
> [WIP] Build `plutus-playground-client` on Hydra

- plutus-playground/plutus-playground-client/webpack.config.js
It's still too big, but this does make it more reasonable.
> Playground: Enabling purescript bundling for an improved compilation artifact size.

- default.nix
- plutus-playground/README.md
- plutus-playground/deployment/nixops/playground.nix
- plutus-playground/plutus-playground-client/default.nix
- release.nix
Commit-by-commit should be clear.
Most controversial thing is probably moving the non-haskell playground expressions to a sub-attr-set, but I think this is a bit clearer.
I tried to override the version of purescript in the main package to the version David said we needed, but it doesn't build with the default GHC in that package set (8.4), and I couldn't be bothered to try overriding that too. So we're still stuck with the additional pinned nixpkgs for now, but I'd like to try and understand what we need to do to get rid of it.
> Various misc nix improvements, mostly to playground expressions

- plutus-tx-plugin/src/Language/PlutusTx/Plugin.hs
- plutus-tx-plugin/test/Plugin/IllTyped.hs
- plutus-tx-plugin/test/Plugin/Spec.hs
- plutus-tx/src/Language/PlutusTx/TH.hs
- plutus-tx/test/Spec.hs
- plutus-tx/tutorial/Tutorial.md
- wallet-api/src/Ledger/Types.hs
This tracks the type of the Haskell that was compiled, and hence
implicitly (insofar as we believe that the compiation is
type-preserving) the type of the compiled code. This can be used to
ensure that application of compiled programs is well-typed - however in
our primary setting in `wallet-api` we simply have programs as
unknown serialized blobs, and so we cannot make use of this facility.
I considered using existentials in `wallet-api` so we could at least
enforce the *shape* of a validator script as a function of the
appropriate arity, but this makes things quite a bit more complicated,
and would give users confusing error messages, so I've decided not to do
that for now.
> plutus-tx-plugin: use a phantom type parameter for CompiledCode

- language-plutus-core/prelude/PlutusPrelude.hs
- language-plutus-core/src/Language/PlutusCore/Evaluation/Result.hs
- language-plutus-core/src/Language/PlutusCore/Pretty.hs
- language-plutus-core/src/Language/PlutusCore/Pretty/Classic.hs
- language-plutus-core/src/Language/PlutusCore/Pretty/Plc.hs
- language-plutus-core/src/Language/PlutusCore/Pretty/Readable.hs
- pkgs/default.nix
- plutus-ir/plutus-ir.cabal
- plutus-ir/src/Language/PlutusIR.hs
- plutus-ir/test/TestLib.hs
- plutus-tx-plugin/plutus-tx-plugin.cabal
- plutus-tx-plugin/test/Plugin/Spec.hs
- plutus-tx/.ghci
- plutus-tx/plutus-tx.cabal
- plutus-tx/test/Spec.hs
- plutus-tx/tutorial/Tutorial.md
While the full-on pretty-printing machinery is useful, and we do want it
for PIR (so we can e.g. get debug printing of uniques), it's nice to
have a default implementation of plain `Pretty` for "boring" usage.
As a side benefit, this lets me define a printing function that works
for both PLC and PIR, which will be helpful for my demo. (Possibly we
can do this already but I am unable to figure out how to.)
> language-plutus-core/plutus-ir: add default Pretty instances

- language-plutus-core/generators/Language/PlutusCore/Generators/Internal/TypeEvalCheck.hs
- language-plutus-core/language-plutus-core.cabal
- language-plutus-core/src/Language/PlutusCore.hs
- language-plutus-core/src/Language/PlutusCore/Normalize.hs
- language-plutus-core/src/Language/PlutusCore/Quote.hs
- language-plutus-core/src/Language/PlutusCore/Type.hs
- language-plutus-core/src/Language/PlutusCore/TypeSynthesis.hs
- language-plutus-core/test/Generators.hs
- language-plutus-core/test/Normalization/Type.hs
- language-plutus-core/test/Spec.hs
Changes:
1. type normalization runs in a monad transformer now
2. in the finite gas case a `TypeError` is no longer returned (because type normalization is unrelated to type checking and it's type checking that can return `TypeError`s), instead we just use `MaybeT`
3. in the infinite gas case type normalization runs without `StateT` and `MaybeT`, hence no need for the user to handle the impossible case of running out of infinite gas (which was the case before)
4. type normalization no longer throws away annotations
5. added `normalizeTypesIn` which allows to normalize all types in a term
6. `Gas` is a `newtype` around `Natural` now (we need to do the same for `Size` later)
7. some cosmetic changes in the type checking algorithm to ease migration to `ifix`
> [NormalizeType] 'NormalizeTypeM' -> 'NormalizeTypeT'

- plutus-tx/src/Language/PlutusTx/Prelude.hs
These builtins (take, drop, concat) which work with ByteStrings exist but have not currently been added to the PlutusTx Prelude. This causes a bit of a mess to need to work with both the builtins and splicing from the Prelude, so I've added them to the Prelude.
> Added Take/Drop/Concat ByteString Builtins To PlutusTx Prelude

- plutus-tx-plugin/README.md
- plutus-tx-plugin/src/Language/PlutusTx/Compiler/Expr.hs
- plutus-tx-plugin/test/Plugin/Spec.hs
If you pass `-g` you get source spans in Core `Tick`s. We can hoist
these out and use them in error contexts. They also get printed in the
Core, which is a nice bonus too.
No test changes, because I'm still stripping context from the errors in
the tests. Possibly I should change it to by default only strip out the
detailed printing of all the expressions.
(Thanks go to Simon PJ for the tip-off!)
> plutus-tx-plugin: use source spans from -g

- language-plutus-core/language-plutus-core.cabal
- language-plutus-core/src/Language/PlutusCore/FsTree.hs
- language-plutus-core/stdlib/Language/PlutusCore/StdLib/Everything.hs
- language-plutus-core/test/Pretty/Readable.hs
- language-plutus-core/test/Spec.hs
- language-plutus-core/test/TypeSynthesis/Spec.hs
Golden tests refactoring. Needed, because the `ifix` PR adds `examples` in addition to `stdlib`, so hardcoding "automatic" golden testing to `stdlib` no longer works.
> [Test] Added 'FsTree'

- plutus-ir/src/Language/PlutusIR/Value.hs
- plutus-tx-plugin/test/Lift/boolInterop.plc.golden
- plutus-tx-plugin/test/Plugin/primitives/and.plc.golden
- plutus-tx-plugin/test/Plugin/primitives/andApply.plc.golden
- plutus-tx-plugin/test/Plugin/primitives/ifThenElse.plc.golden
- plutus-tx/test/and.plc.golden
As in PLC. The place where this matters is deciding whether we need to
do a lazy match, so this removes a few of those.
> PIR: variables are values

- language-plutus-core/src/Language/PlutusCore/MkPlc.hs
- plutus-ir/src/Language/PlutusIR/Analysis/Dependencies.hs
- plutus-ir/test/OptimizerSpec.hs
- plutus-ir/test/optimizer/deadCode/nestedBindingsIndirect.plc.golden
- plutus-tx-plugin/src/Language/PlutusTx/Compiler/Type.hs
- plutus-tx-plugin/test/Plugin/Spec.hs
- plutus-tx-plugin/test/Plugin/data/monomorphic/recordNewtype.plc.golden
This is slightly subtle. Naively, we might think that the datatype
variable `A` does not depend on the constructor `MkA`. However, this is
not true: we cannot remove the latter from the program without removing
the former, because they are defined in the same binding. Hence there
*is* a dependency.
Missing this causes us to miss that the dependencies of `MkA` are also
live in this instance, causing us to erroneously remove them.
Also a drive-by fix for using the right GHC method for getting datatype args,
although that turned out not to be the problem.
Fixes one of the type errors on the ifix branch.
> plutus-ir: datatype vars have dependencies on each other

- plutus-tx-plugin/src/Language/PlutusTx/Compiler/Builtins.hs
- plutus-tx-plugin/test/Lift/boolInterop.plc.golden
- plutus-tx-plugin/test/Plugin/Spec.hs
- plutus-tx-plugin/test/Plugin/basic/monoId.plc.golden
- plutus-tx-plugin/test/Plugin/basic/monoK.plc.golden
- plutus-tx-plugin/test/Plugin/primitives/andApply.plc.golden
- plutus-tx-plugin/test/Plugin/primitives/equalsByteString.plc.golden
- plutus-tx-plugin/test/Plugin/primitives/intEqApply.plc.golden
- plutus-tx-plugin/test/Plugin/primitives/trace.plc.golden
- plutus-tx-plugin/test/Plugin/recursiveFunctions/even3.plc.golden
- plutus-tx-plugin/test/Plugin/recursiveFunctions/even4.plc.golden
- plutus-tx-plugin/test/Plugin/structure/letFun.plc.golden
`trace` returns unit, but a Scott-encoded unit, so we need to do the
same wrapping trick that we do for builtins that return a bool and add
an adapter that converts the result to a Haskell unit.
This should fix another one of the typechecking errors with ifix.
> plutus-tx-plugin: wrap trace

- plutus-playground/plutus-playground-lib/src/Playground/Interpreter/Util.hs
- plutus-use-cases/src/Language/PlutusTx/Coordination/Contracts/CrowdFunding.hs
- wallet-api/src/Wallet/API.hs
- wallet-api/src/Wallet/Emulator/AddressMap.hs
- wallet-api/src/Wallet/Emulator/Types.hs
- wallet-api/test/Spec.hs
* `AddressMap` keeps track of `TxOut` instead of `TxOutRef`. This means we get the data script of the output as well
* Add a `payToScripts` function in `Wallet.API` that lets us pay to multiple script addresses using our own funds
> wallet-api: Improvements

- language-plutus-core/test/Generators.hs
- language-plutus-core/test/Spec.hs
This fixes https://github.com/input-output-hk/plutus/issues/438
Before, we generated bad data for constants sometimes. This filters out that bad data (viz., integers which are out of range), which means that we no longer have to allow errors in the parser roundtrip tests.
> Generate more sensible constants

- plutus-playground/plutus-playground-server/usecases/CrowdFunding.hs
- plutus-playground/plutus-playground-server/usecases/Messages.hs
- plutus-playground/plutus-playground-server/usecases/Vesting.hs
- plutus-use-cases/src/Language/PlutusTx/Coordination/Contracts/CrowdFunding.hs
- plutus-use-cases/src/Language/PlutusTx/Coordination/Contracts/Future.hs
- plutus-use-cases/src/Language/PlutusTx/Coordination/Contracts/Swap.hs
- plutus-use-cases/src/Language/PlutusTx/Coordination/Contracts/Vesting.hs
- wallet-api/src/Ledger/Index.hs
- wallet-api/src/Ledger/Types.hs
- wallet-api/src/Ledger/Validation.hs
- wallet-api/src/Wallet/API.hs
- wallet-api/src/Wallet/Generators.hs
- wallet-api/tutorial/Tutorial.md
Currently we have a bit misleading API with regards to `Signatures` in `PendingTx` API, and `UtxoIndex`.
newtype UtxoIndex = UtxoIndex { getIndex :: Map.Map TxOutRef' (TxOut', [Signature]) }
`UtxoIndex` contains `Signature`s of unspent `TxOut` which is inconsistent with current Cardano SL, because those are witnesses of actual spending of the transaction input.
This Pull Request aims to fix the inconsistency.
> Remove [Signature] from UtxoIndex and PendingTx API.

- plutus-playground/plutus-playground-server/usecases/CrowdFunding.hs
- plutus-playground/plutus-playground-server/usecases/Game.hs
- plutus-playground/plutus-playground-server/usecases/Vesting.hs
- plutus-use-cases/src/Language/PlutusTx/Coordination/Contracts/CrowdFunding.hs
- plutus-use-cases/src/Language/PlutusTx/Coordination/Contracts/Future.hs
- plutus-use-cases/src/Language/PlutusTx/Coordination/Contracts/Game.hs
- plutus-use-cases/src/Language/PlutusTx/Coordination/Contracts/Swap.hs
- plutus-use-cases/src/Language/PlutusTx/Coordination/Contracts/Vesting.hs
- wallet-api/src/Ledger/Index.hs
- wallet-api/src/Ledger/Validation.hs
- wallet-api/tutorial/Tutorial.md
Instead of `pendingTxOwnHash`, I suggest to add current validating `PendingTxIn` in `PendingTx`. 
This way, contract authors do not need to search for own script `TxOut` in `PendingTx` inputs, and could easily get to script value, hashes, etc.
> Add a reference to currently validating TxIn in PendingTx.

- language-plutus-core/src/Language/PlutusCore/MkPlc.hs
- language-plutus-core/stdlib/Language/PlutusCore/StdLib/Data/Bool.hs
- language-plutus-core/stdlib/Language/PlutusCore/StdLib/Data/Function.hs
- language-plutus-core/stdlib/Language/PlutusCore/StdLib/Meta/Data/Tuple.hs
- language-plutus-core/stdlib/Language/PlutusCore/StdLib/Type.hs
- plutus-ir/src/Language/PlutusIR/Compiler/Datatype.hs
- plutus-ir/src/Language/PlutusIR/Compiler/Recursion.hs
As per an old discussion with @michaelpj.
> [Plutus Core] Keep annotations in 'mkIterForall' and 'mkIterTyLam'

- default.nix
- nix/haddock-combine.nix
This glues together the Haddock generated for the various packages.
- There is an index and contents
- Links to the index/contents from component packages will go to
the combined index.
- All the links that go to component are relativized, so the result
is relocatable.
- Links to other packages will still be broken.
- You can provide a prologue that goes on the main page.
- No symlinks.
We still need to serve this somewhere, but this is a start.
Also, some of our modules are missing, but that's because we're not
generating Haddock for them properly, which is a separate problem.
> Hack together combined Haddock output

- language-plutus-core/generators/Language/PlutusCore/Generators/Internal/TypeEvalCheck.hs
- language-plutus-core/src/Language/PlutusCore.hs
- language-plutus-core/src/Language/PlutusCore/Constant/Dynamic/Emit.hs
- language-plutus-core/src/Language/PlutusCore/Error.hs
- language-plutus-core/src/Language/PlutusCore/Renamer.hs
- language-plutus-core/src/Language/PlutusCore/Type.hs
- language-plutus-core/src/Language/PlutusCore/TypeSynthesis.hs
- language-plutus-core/test/TypeSynthesis/Spec.hs
- plutus-core-interpreter/test/DynamicBuiltins/Common.hs
- plutus-core-interpreter/test/DynamicBuiltins/Factorial.hs
- plutus-core-interpreter/test/DynamicBuiltins/Logging.hs
- plutus-core-interpreter/test/DynamicBuiltins/String.hs
- plutus-exe/src/Main.hs
- plutus-ir/src/Language/PlutusIR/Compiler/Error.hs
- plutus-ir/test/Spec.hs
- plutus-tx-plugin/src/Language/PlutusTx/Compiler/Error.hs
- plutus-tx-plugin/src/Language/PlutusTx/Plugin.hs
This removes the annotation machinery and all the `TyNameWithKind`, `NameWithType`, `RenameError`, `AsRenameError`, etc business.
Pros:
- Terms with types involving dynamic builtin types type check just fine. Previously they did not type check and instead we were getting errors from the annotation machinery for whatever reasons.
- Type rules contain contexts and finally look sensible and the way one would expect.
- No need to renormalize the type of a variable at each usage of this variable like this was previously.
- Less code.
Cons:
- You tell me.
> [PlutusCore] [TypeCheck] Removed the annotation machinery

- plutus-core-spec/CHANGELOG.md
- plutus-core-spec/figures/PlutusCoreBuiltins.tex
- plutus-core-spec/figures/PlutusCoreGrammar.tex
- plutus-core-spec/figures/PlutusCoreLexicalGrammar.tex
- plutus-core-spec/figures/PlutusCoreReduction-Algorithmic-Restricted.tex
- plutus-core-spec/figures/PlutusCoreReduction.tex
- plutus-core-spec/figures/PlutusCoreTypeCorrectness-Algorithmic-Restricted.tex
- plutus-core-spec/figures/PlutusCoreTypeCorrectness.tex
- plutus-core-spec/main.tex
- plutus-core-spec/plutus-core-specification.tex
This PR will create mildly broken results b/c of Kenneth's previous PR which reorgs. I expect the big issue will be files have been moved around, but there will also be some merge conflicts in some files that hopefully can be resolved easily enough b/c they shouldn't be very overlapping.
- Add CHANGELOG.md to track changes.
- Changes the lexical syntax for sizes to include the `bytes` suffixe so that
one can write, e.g., `10bytes` instead of just `10` for sizes.
- Replaces the old definition of fixed points with the new canonical indexed
fixed point definition of fixed point types.
- Replaces the reduction based type equality with declarative equality of types
that includes standard properties for equality (i.e. symmetry, transitivity,
and congruence).
- Fix typos in the definition of the …
> Spec modifications 2018 11 26

- .gitignore
- README.md
- deploy-docs.sh
At the moment the only place we really have to host our docs is the GH pages site associated with this repo.
Automatically deploying to this site is a bit of a pain, so I've written a script to make at least the actual deployment part automated. We still need to run this script manually whenever we want to deploy the docs. (When do we do that? Who knows, we don't exactly have releases or anything.)
> Docs: add a script to deploy the combined Haddock to GH pages

- language-plutus-core/common/PlcTestUtils.hs
- language-plutus-core/examples/Language/PlutusCore/Examples/Data/InterList.hs
- language-plutus-core/examples/Language/PlutusCore/Examples/Data/TreeForest.hs
- language-plutus-core/language-plutus-core.cabal
- language-plutus-core/src/Language/PlutusCore/CBOR.hs
- language-plutus-core/src/Language/PlutusCore/DeBruijn.hs
- language-plutus-core/test/Spec.hs
- pkgs/default.nix
- plutus-ir/test/Spec.hs
- plutus-ir/test/datatypes/listMatch.plc.golden
- plutus-ir/test/datatypes/maybe.plc.golden
- plutus-ir/test/recursion/even3.plc.golden
- plutus-ir/test/recursion/mutuallyRecursiveValues.plc.golden
- plutus-tx-plugin/test/Lift/list.plc.golden
- plutus-tx-plugin/test/Lift/mono.plc.golden
- plutus-tx-plugin/test/Lift/nested.plc.golden
- plutus-tx-plugin/test/Lift/poly.plc.golden
- plutus-tx-plugin/test/Lift/record.plc.golden
- plutus-tx-plugin/test/Lift/tuple.plc.golden
- plutus-tx-plugin/test/Plugin/Spec.hs
- plutus-tx-plugin/test/Plugin/basic/monoId.plc.golden
- plutus-tx-plugin/test/Plugin/basic/monoK.plc.golden
- plutus-tx-plugin/test/Plugin/recursiveTypes/sameEmptyRose.plc.golden
- plutus-tx-plugin/test/Plugin/structure/letFun.plc.golden
This seems useful to have, for tests if nothing else. I haven't implemented using it for serialization, as suggested in https://github.com/input-output-hk/plutus/issues/471, but it's there if we want it.
- Add de Bruijn indices as kinds of name.
- Adds transformations between terms with uniques and terms with de Bruijn indices.
- Also check that these round-trip. (We have to use the "interesting" term generator, since we need the terms to be well-scoped, so we can't use the simple term generator.)
- Debruijnify terms before printing them in tests, making them more robust to changes.
- I noticed that the PIR-producing tests aren't producing debug output, which they should be, will fix later. Although maybe I'll need to write another debruijnifier for PIR...
> Add support for de Bruijn indices

- default.nix
Inexplicably removed in 6ea46bb6599f744eab2bb602aa57ccd8611d07b4 (@shmish111 wot?)
I honestly don't know how anything works with this, given that iohk-nix
will then try and override the compiler for the package set to 8.2.2!
In fact, this seems to have no effect. I think perhaps overriding several times just doesn't work, so the one in `iohk-nix` is ineffective.
> Pass compiler to iohk-nix again

- plutus-playground/plutus-playground-server/usecases/CrowdFunding.hs
- plutus-playground/plutus-playground-server/usecases/Game.hs
- plutus-playground/plutus-playground-server/usecases/Vesting.hs
- plutus-use-cases/src/Language/PlutusTx/Coordination/Contracts/CrowdFunding.hs
- plutus-use-cases/src/Language/PlutusTx/Coordination/Contracts/Future.hs
- plutus-use-cases/src/Language/PlutusTx/Coordination/Contracts/Game.hs
- plutus-use-cases/src/Language/PlutusTx/Coordination/Contracts/Swap.hs
- plutus-use-cases/src/Language/PlutusTx/Coordination/Contracts/Vesting.hs
- wallet-api/src/Ledger/Types.hs
- wallet-api/src/Wallet/Generators.hs
- wallet-api/test/Spec.hs
* Delete some old validation code from 'Ledger.Types' (the real
validation code lives in 'Ledger.Index')
* Add 'compileScript' which removes 1 function application from every
validator script in the contracts
> wallet-api: Delete dead code

- pkgs/default.nix
- plutus-playground/plutus-playground-server/usecases/CrowdFunding.hs
- plutus-playground/plutus-playground-server/usecases/Game.hs
- plutus-playground/plutus-playground-server/usecases/Messages.hs
- plutus-playground/plutus-playground-server/usecases/Vesting.hs
- wallet-api/src/Wallet/API.hs
- wallet-api/tutorial/Tutorial.md
- wallet-api/wallet-api.cabal
* Enable building of the tutorial in wallet-api.cabal
* Add a constraint `MonadWallet` that combines `WalletAPI` and `WalletDiagnostics` because they are usually used together.
> wallet-api: Build tutorial, nicer type

- language-plutus-core/src/Language/PlutusCore/Lexer.x
- language-plutus-core/test/normalize-types/addIntegerCorrect.plc
Right now all it does it handle the byte case. It will need full compliance with the spec, which will require some changes to the AST.
> Update for better compliance with the spec

- cabal.project
- stack.yaml
This removes it from the `cabal.project` file.
> Remove servant subscriber from github

- cabal.project
- plutus-tx/plutus-tx.cabal
This is mostly for my purposes, but it additionally makes bounds for `plutus-tx` correct.
> Add ghc <= 8.4 for plutus-tx and add ghc-8.4.4 to the cabal.project file

- cabal.project
- plutus-playground/plutus-playground-server/plutus-playground-server.cabal
This restricts newer versions of `servant` and `http-api-data` for now, so that `Servant.Extra` doesn't cause problems.
> Fix builds for cabal

- language-plutus-core/language-plutus-core.cabal
- language-plutus-core/src/Language/PlutusCore.hs
- language-plutus-core/src/Language/PlutusCore/Size.hs
This adds a function `sizeTerm` which is the canonical size of a Plutus Core term. It is used for benchmarking.
> Add sizeTerm

- language-plutus-core/src/Language/PlutusCore/CBOR.hs
- language-plutus-core/src/Language/PlutusCore/Constant/Apply.hs
- language-plutus-core/src/Language/PlutusCore/Constant/Function.hs
- language-plutus-core/src/Language/PlutusCore/Constant/Name.hs
- language-plutus-core/src/Language/PlutusCore/Lexer.x
- language-plutus-core/src/Language/PlutusCore/Lexer/Type.hs
- language-plutus-core/test/TypeSynthesis/Golden/BlockNum.plc.golden
- language-plutus-core/test/TypeSynthesis/Golden/TxHash.plc.golden
- language-plutus-core/test/types/verifyIdentity.plc
- language-plutus-core/test/types/verifyIdentity.plc.golden
- plutus-tx/compiler/Language/PlutusTx/Builtins.hs
- plutus-tx/compiler/Language/PlutusTx/Compiler/Builtins.hs
- plutus-tx/src/Language/PlutusTx/Prelude.hs
- plutus-tx/src/Language/PlutusTx/Prelude/Stage0.hs
- plutus-tx/test/Lift/boolInterop.plc.golden
- plutus-tx/test/Plugin/primitives/andApply.plc.golden
- plutus-tx/test/Plugin/primitives/equalsByteString.plc.golden
- plutus-tx/test/Plugin/primitives/intEqApply.plc.golden
- plutus-tx/test/Plugin/recursiveFunctions/even3.plc.golden
- plutus-tx/test/Plugin/recursiveFunctions/even4.plc.golden
- plutus-tx/test/Plugin/recursiveTypes/sameEmptyRoseEval.plc.golden
- plutus-tx/test/TH/all.plc.golden
This deletes the `BlockNum` and `TxHash` builtins. Fixes #568.
> [Plutus Core] [Builtins] Deleted the 'BlockNum' and 'TxHash' builtin names

- language-plutus-core/generators/Language/PlutusCore/Generators/AST.hs
- language-plutus-core/language-plutus-core.cabal
- language-plutus-core/test/Check/Spec.hs
- language-plutus-core/test/Normalization/Type.hs
- language-plutus-core/test/Spec.hs
- pkgs/default.nix
- plutus-ir/plutus-ir.cabal
- plutus-ir/src/Language/PlutusIR/Generators/AST.hs
- plutus-ir/src/Language/PlutusIR/Parser.hs
- plutus-ir/test/ParserSpec.hs
- plutus-ir/test/Spec.hs
- plutus-playground/plutus-playground-server/src/Playground/Interpreter.hs
A parser for plutus IR, written in Megaparsec. Should be able to parse any and all plutus-core programs (except ones that use PIR keywords as identifiers).
> plutus-ir: parser for plutus IR

- plutus-ir/plutus-ir.cabal
Tightens bounds on `megaparsec` appropriately.
> Restrict megaparsec bounds

- plutus-ir/plutus-ir.cabal
- plutus-ir/src/Language/PlutusIR/Parser.hs
- plutus-ir/test/ParserSpec.hs
Switched the underlying stream type of the pir-parser to use Text instead of String for performance.
> plutus-ir: switched pir-parser to Text

- language-plutus-core/examples/Language/PlutusCore/Examples/Data/TreeForest.hs
- language-plutus-core/generators/Language/PlutusCore/Generators/Internal/TypeEvalCheck.hs
- language-plutus-core/language-plutus-core.cabal
- language-plutus-core/prelude/PlutusPrelude.hs
- language-plutus-core/src/Language/PlutusCore.hs
- language-plutus-core/src/Language/PlutusCore/Constant/Function.hs
- language-plutus-core/src/Language/PlutusCore/Error.hs
- language-plutus-core/src/Language/PlutusCore/Normalize.hs
- language-plutus-core/src/Language/PlutusCore/Normalize/Internal.hs
- language-plutus-core/src/Language/PlutusCore/Quote.hs
- language-plutus-core/src/Language/PlutusCore/Rename.hs
- language-plutus-core/src/Language/PlutusCore/Type.hs
- language-plutus-core/src/Language/PlutusCore/TypeCheck.hs
- language-plutus-core/src/Language/PlutusCore/TypeCheck/Internal.hs
- language-plutus-core/test/Check/Spec.hs
- language-plutus-core/test/Normalization/Type.hs
- plutus-exe/src/Main.hs
This splits the normalizer into
1. internals which rely on global uniqueness and are used by the type checker
2. the safe user-facing API that performs renaming on types before normalizing them
I also deleted the `NormalizedType tyname ann` alias and its pattern synonym. `Normalized (Type tyname ann)` is not much more verbose, but saves the reader from thinking what `NormalizedType` is, and indicates that you can use the `Functor`/`Foldable`/`Traversable` instances of `Normalized`.
See some comments below.
> [PlutusCore] Split the normalizer

- plutus-playground/plutus-playground-client/src/Action.purs
- plutus-playground/plutus-playground-client/src/Editor.purs
- plutus-playground/plutus-playground-client/src/MainFrame.purs
- plutus-playground/plutus-playground-client/src/Types.purs
- plutus-playground/plutus-playground-client/src/Wallet.purs
This required a bit of a reshuffle of the core `State` type.
> Fix #462 - conditionally clearing out actions when the underlying program is incompatible.

- .gitignore
- marlowe/src/Language/Marlowe/Client.hs
- marlowe/src/Language/Marlowe/Common.hs
- plutus-playground/plutus-playground-client/src/Chain.purs
- plutus-playground/plutus-playground-client/test/evaluation_response1.json
- plutus-playground/plutus-playground-client/test/evaluation_response2.json
- plutus-playground/plutus-playground-lib/src/Playground/API.hs
- plutus-playground/plutus-playground-lib/src/Playground/Interpreter/Util.hs
- plutus-playground/plutus-playground-server/app/PSGenerator.hs
- plutus-playground/plutus-playground-server/src/Playground/Interpreter.hs
- plutus-playground/plutus-playground-server/test/Playground/UsecasesSpec.hs
- plutus-tx/src/Language/PlutusTx/Prelude.hs
- plutus-tx/src/Language/PlutusTx/Prelude/Stage1.hs
- wallet-api/src/Ledger/Ada/TH.hs
- wallet-api/src/Ledger/Value.hs
- wallet-api/src/Ledger/Value/TH.hs
- wallet-api/src/Wallet/Emulator/Types.hs
- wallet-api/src/Wallet/Generators.hs
- wallet-api/src/Wallet/Graph.hs
- wallet-api/test/Spec.hs
Change the definition of `Value` to `[(Int, Int)]`. We use a list of
key-value pairs for now and will change it to an `IntMap` later. None
of the examples use more than one currency anyway.
> wallet-api: Value is Map Currency Int

- plutus-playground/plutus-playground-lib/plutus-playground-lib.cabal
This fixes builds for both `stack` and `cabal`. I'm not entirely sure what was up with CI but we may want to fix them to prevent such things from happening.
> Remove second cabal-version field

- wallet-api/src/Ledger/Index.hs
- wallet-api/src/Wallet/Emulator/Http.hs
- wallet-api/src/Wallet/Emulator/Types.hs
- wallet-api/test/Spec.hs
* Fix a bug in the emulator where the UTXO set would only be updated
after each block (instead of each transaction)
There is a unit test for this at the moment, but I'll improve the test suite for the emulator next week so we should get better tests soon.
> wallet-api: Fix bug in emulator

- language-plutus-core/src/Language/PlutusCore.hs
- language-plutus-core/src/Language/PlutusCore/Size.hs
- plutus-use-cases/src/Language/PlutusTx/Coordination/Contracts/CrowdFunding.hs
- plutus-use-cases/src/Language/PlutusTx/Coordination/Contracts/Game.hs
- plutus-use-cases/src/Language/PlutusTx/Coordination/Contracts/Swap.hs
- plutus-use-cases/src/Language/PlutusTx/Coordination/Contracts/Vesting.hs
- plutus-use-cases/test/Spec/Crowdfunding.hs
- plutus-use-cases/test/Spec/Future.hs
- plutus-use-cases/test/Spec/Game.hs
- plutus-use-cases/test/Spec/Vesting.hs
- wallet-api/src/Ledger/Types.hs
I was investigating whether we're getting a script size blowup, and a first step is measuring what they currently are. I wrote some tests for the existing use cases to check that they stay within a reasonable bound of where they are (or more realistically: we know when they get bigger).
The sizes are in number of AST nodes, which I think is actually more useful than number of serialized bytes, although I added a function for that too and I'd expect them to be more or less proportional.
TBH, ~50k AST nodes for the Futures contract is already ridiculously high. I suspect this is due to duplication because of the way we're using TH, see https://github.com/input-output-hk/plutus/issues/693.
> Measure script sizes and add tests that they're reasonalbe for use cases

- docs/multi-currency/multi-currency.md
Change terminology in the multi-currency example from mirror currency to reserve currency.
> multi-currency: Mirror -> reserve

- marlowe/src/Language/Marlowe/Common.hs
- plutus-playground-server/usecases/CrowdFunding.hs
- plutus-playground-server/usecases/Game.hs
- plutus-playground-server/usecases/Vesting.hs
- plutus-tutorial/doctest/Tutorial/02-validator-scripts.md
- plutus-tutorial/doctest/Tutorial/03-wallet-api.md
- plutus-tutorial/tutorial/Tutorial/Solutions2.hs
- plutus-tutorial/tutorial/Tutorial/Vesting.hs
- plutus-use-cases/src/Language/PlutusTx/Coordination/Contracts/CrowdFunding.hs
- plutus-use-cases/src/Language/PlutusTx/Coordination/Contracts/Future.hs
- plutus-use-cases/src/Language/PlutusTx/Coordination/Contracts/Game.hs
- plutus-use-cases/src/Language/PlutusTx/Coordination/Contracts/Swap.hs
- plutus-use-cases/src/Language/PlutusTx/Coordination/Contracts/Vesting.hs
- wallet-api/src/Ledger/Index.hs
- wallet-api/src/Ledger/Types.hs
Change the order of arguments of validator scripts to the more intuitive
`DataScript -> RedeemerScript -> PendingTx -> ()`
ie. the chronological order.
> wallet-api: order of validator script arguments

- language-plutus-core/src/Language/PlutusCore/MkPlc.hs
- plutus-ir/src/Language/PlutusIR.hs
- plutus-ir/src/Language/PlutusIR/Compiler/Definitions.hs
- plutus-ir/src/Language/PlutusIR/MkPir.hs
- plutus-ir/src/Language/PlutusIR/Parser.hs
- plutus-ir/src/Language/PlutusIR/Transform/ThunkRecursions.hs
- plutus-tx/compiler/Language/PlutusTx/Compiler/Builtins.hs
- plutus-tx/compiler/Language/PlutusTx/Compiler/Expr.hs
- plutus-tx/compiler/Language/PlutusTx/Compiler/Type.hs
- plutus-tx/compiler/Language/PlutusTx/Plugin.hs
We have a `TermLike` class now so we can delete a bunch of code in `MkPir.hs` and reuse the entirety of the PIR parser to parse PLC code.
> [plutus-ir] Switched the pir parser to using TermLike

- default.nix
- iohk-nix.json
- plutus-playground-server/src/Playground/Interpreter.hs
My GHC PR is approved (not merged yet, but I expect it will be), and the patch is applied in iohk-nix.
The nixpkgs PR is merged upstream, and the patch is applied in our nixpkgs fork.
So after updating `iohk-nix` we can now delete the workaround for good!
> Finally remove workaround for GHC bug

- marlowe/src/Language/Marlowe/Common.hs
- plutus-tutorial/doctest/Tutorial/01-plutus-tx.md
- plutus-tutorial/doctest/Tutorial/03-wallet-api.md
- plutus-tutorial/tutorial/Tutorial/Solutions1.hs
- plutus-tutorial/tutorial/Tutorial/TH.hs
- plutus-tx/compiler/Language/PlutusTx/Compiler/Expr.hs
- plutus-tx/compiler/Language/PlutusTx/Compiler/Primitives.hs
- plutus-tx/src/Language/PlutusTx/Prelude/Stage0.hs
- plutus-tx/test/Plugin/Spec.hs
- plutus-tx/test/TH/Spec.hs
- plutus-tx/test/TH/TestTH.hs
- plutus-use-cases/src/Language/PlutusTx/Coordination/Contracts/Swap.hs
- wallet-api/src/Ledger/Interval.hs
- wallet-api/src/Ledger/Validation.hs
This is misleading and suggests that we have more support for
typeclasses than we do. In addition, it complicates doing things
generically with GHC names since some of them are special.
Clients who want to avoid TH splices can still use the names in
`Language.PlutusTx.Builtins`, those who wish to have a consistent
interface can use the quotes in `Language.PlutusTx.Prelude`.
> plutus-tx: remove special case handling of typeclass methods

- plutus-tutorial/doctest/Tutorial/03-wallet-api.md
This adds a note in the wallet-API tutorial about `applyScript`.
The wider issue of explaining Template Haskell in the tutorials is captured by #736.
> tutorial: Document use of applyScript

- default.nix
- interpreter/LICENSE
- interpreter/NOTICE
- interpreter/interpreter.cabal
- interpreter/shell.nix
- pkgs/default.nix
- plutus-playground-lib/shell.nix
- plutus-playground-server/shell.nix
Done by setting `GHCRTS`, which is apparently the most reliable way to do this when using `runghc`. 2GB should be enough for anyone :trollface: 
This stops my branch from OOMing these tests, instead it just takes forever, presumably because GHC is GCing furiously to stay below the limit.
Also some minor fixes to the interpreter project, most importantly the license.
> Add memory limits to playground interpreter processes

- plutus-playground-server/src/Playground/Interpreter.hs
This is fixed upstream, and patched in our GHCs in Nix. However, not
everyone is getting GHC from Nix, so we can't rely on this :(
> Restore workaround

- default.nix
- lib.nix
- pkgs/generate.sh
- release.nix
- shell.nix
It's jolly annoying when Hydra builds all our packages but doesn't build the dependencies of some of the dev scripts you use. Similarly, although the `hlint` test will pass on darwin iff it passes on linux, running it on both means that the dependencies are definitely in the cache for local use.
The solution to this is conceptually obvious: add them to `release.nix`. However, in practice in the process of understanding what on Earth was going on in there I more or less rewrote it to something that makes more sense.
However, we'll have to see what Hydra makes of it...
> Seriously rework release.nix, include dev scripts for all platforms

- interpreter/interpreter.cabal
- interpreter/src/Language/Haskell/Interpreter.hs
- meadow-client/src/Editor.purs
- meadow-client/src/MainFrame.purs
- meadow-client/src/Types.purs
- meadow/app/PSGenerator.hs
- meadow/meadow.cabal
- meadow/src/API.hs
- meadow/src/Interpreter.hs
- meadow/src/Server.hs
- meadow/test/Spec.hs
- pkgs/default.nix
- plutus-playground-client/src/Editor.purs
- plutus-playground-client/src/Gists.purs
- plutus-playground-client/src/MainFrame.purs
- plutus-playground-client/src/MonadApp.purs
- plutus-playground-client/src/Types.purs
- plutus-playground-client/test/BridgeTests.purs
- plutus-playground-client/test/MainFrameTests.purs
- plutus-playground-client/test/compilation_response1.json
- plutus-playground-lib/src/Playground/API.hs
- plutus-playground-server/app/PSGenerator.hs
- plutus-playground-server/plutus-playground-server.cabal
- plutus-playground-server/src/Playground/Interpreter.hs
- plutus-playground-server/src/Playground/Server.hs
- plutus-playground-server/test/Playground/UsecasesSpec.hs
- stack.yaml
Apart from a bit of reduction in duplication, the main point here is that we will be able to use the same Editor.purs for both meadow and the playground. The editor is a tool for use with the interpreter, with this change I think we can separate the Editor as a something that is aligned with the interpreter.
> refactor playground errors to make them more generic

- .gitattributes
Modifies the `.gitattributes` file so that github will (correctly) detect this repository as mostly Haskell.
> Ignore yarn.nix for github

- plutus-ir/src/Language/PlutusIR/Compiler/Error.hs
- plutus-ir/src/Language/PlutusIR/Compiler/Term.hs
- plutus-ir/test/errors/mutuallyRecursiveTypes.golden
- plutus-tx/compiler/Language/PlutusTx/Compiler/Builtins.hs
- plutus-tx/compiler/Language/PlutusTx/Compiler/Error.hs
- plutus-tx/compiler/Language/PlutusTx/Compiler/Expr.hs
- plutus-tx/compiler/Language/PlutusTx/Compiler/Kind.hs
- plutus-tx/compiler/Language/PlutusTx/Compiler/Type.hs
- plutus-tx/compiler/Language/PlutusTx/Compiler/ValueRestriction.hs
- plutus-tx/compiler/Language/PlutusTx/Plugin.hs
- plutus-tx/test/Plugin/Spec.hs
- plutus-tx/test/Plugin/errors/emptyRoseId1.plc.golden
- plutus-tx/test/Plugin/errors/free.plc.golden
- plutus-tx/test/Plugin/errors/integer.plc.golden
- plutus-tx/test/Plugin/errors/recordSelector.plc.golden
- plutus-tx/test/Plugin/errors/valueRestriction.plc.golden
- Moderately improve some error messages
- Give priorities to contexts, so we only print those that are useful for locating the error by default.
> plutus-tx: moderately improve errors

- plutus-playground-client/src/Chain/BlockchainExploration.purs
- plutus-playground-client/test/evaluation_response1.json
- plutus-playground-server/app/PSGenerator.hs
- plutus-playground-server/test/Playground/UsecasesSpec.hs
- plutus-tutorial/tutorial/Tutorial/Emulator.hs
- plutus-tutorial/tutorial/Tutorial/Vesting.hs
- wallet-api/src/Ledger/Map.hs
- wallet-api/src/Ledger/Map/TH.hs
- wallet-api/src/Ledger/These.hs
- wallet-api/src/Ledger/These/TH.hs
- wallet-api/src/Ledger/Value/TH.hs
- wallet-api/wallet-api.cabal
Move the map implementation from `Ledger.Value.TH` to its own module. That
way we can easily replace it with the real map once it's available.
This changes the JSON representation of the `Value` type slightly, so a
couple of tests in the tutorials and playground projects had to be
changed.
> wallet-api: Extract map

- language-plutus-core/language-plutus-core.cabal
To allow plutus-metatheory to use the language-plutus-core lexer and
parser the following additional modules need to be exposed:
Language.PlutusCore.Type
Language.PlutusCore.Lexer
Language.PlutusCore.Lexer.Type
Language.PlutusCore.Parser
> expose Lexer and Parser in language-plutus-core

- language-plutus-core/language-plutus-core.cabal
To validate signatures in `plc-agda` I would like to use this module.
> expose Crypto module for use in plc-agda

- default.nix
- lib.nix
- pkgs/default.nix
- plutus-contract-exe/LICENSE
- plutus-contract-exe/NOTICE
- plutus-contract-exe/README.md
- plutus-contract-exe/examples/guessing-game/Main.hs
- plutus-contract-exe/plutus-contract-exe.cabal
- plutus-contract-exe/shell.nix
- plutus-contract-exe/src/Language/Plutus/Contract.hs
- plutus-use-cases/src/Language/PlutusTx/Coordination/Contracts/Game.hs
- release.nix
- stack.yaml
- wallet-api/src/Wallet/API.hs
Add 'plutus-contract-exe' with a sample executable contract
@rhyslbw @Sam-Jeston  The most important part is the event types in plutus-contract-exe/src/Language/Plutus/Contract.hs (see comments in that file). 
Things to consider:
* If we have the event based interface, do we need contract-specific HTTP endpoints at all? There could also be another event for "activating contract endpoint"
* Where should the trigger mechanism be implemented? If the contract is notified of changes to the addresses it is interested in, and of slots passing, then it could check the more complex conditions itself (by that I mean the `EventTrigger` type in [`Wallet.API`](https://github.com/input-output-hk/plutus/blob/master/wallet-api/src/Wallet/API.hs#L120))
* Checkpoints & merging of event lists - not …
> plutus-contract-exe: Init

- plutus-playground-client/src/Chain.purs
We weren't correctly handling situations where one wallet didn't have a
given balance. So instead of generating a series like `[ 50, null, 10 ]`
we'd generate `[ 50, 10 ]`, which sortof shuffled all those balances
left, giving silly results.
Fixes #820.
> Playground: Bugfix for the balances chart.

- plutus-tx/plutus-tx.cabal
As of the last update, `plutus-tx` no longer builds with GHC 8.4.4. We should reflect that in the `.cabal` file so that everything is well when we upload to Hackage.
> Restrict plutus tx package bounds

- default.nix
- meadow-client/src/MainFrame.purs
- meadow/app/Main.hs
- meadow/app/PSGenerator.hs
- meadow/app/Webserver.hs
- meadow/meadow.cabal
- meadow/src/Git.hs
- nix/overlays/git-module.nix
- nix/overlays/required.nix
- plutus-playground-client/src/MainFrame.purs
- plutus-playground-server/app/Main.hs
- plutus-playground-server/app/PSGenerator.hs
- plutus-playground-server/app/Webserver.hs
- plutus-playground-server/playground.yaml.sample
- plutus-playground-server/plutus-playground-server.cabal
- plutus-playground-server/src/Git.hs
* They need a default playground.yaml
* we can now mount a local playground.yaml
* fix --version flag by having nix generate a patch for Git.hs
* fix the tutorial link on the playground; it will point to the current
revision if built with nix and will default to point to master
if built with cabal or stack
> Default docker config

- default.nix
- nix/overlays/git-module.nix
- release.nix
Also docker images are in their own attribute now so we don't need to explicitly ignore them, just don't add them to the release.
> add some notes on git version overlay

- plutus-use-cases/plutus-use-cases.cabal
This adds the `-rtsopts` to the test suite. Shouldn't be a security risk since it's just our test.
> Add -rtsopts flag to test suite and format .cabal file

- plutus-tx/src/Language/PlutusTx/Prelude/Stage1.hs
- plutus-use-cases/plutus-use-cases.cabal
- plutus-use-cases/src/Language/PlutusTx/Coordination/Contracts/MultiSig.hs
- plutus-use-cases/test/Spec.hs
- plutus-use-cases/test/Spec/MultiSig.hs
- wallet-api/src/Wallet/Emulator/Client.hs
- wallet-api/src/Wallet/Emulator/Types.hs
This implements the simple multisig contract, where the spending transaction needs to be passed around via a separate channel.
> use-cases: Add multi sig contract

- plutus-playground-lib/src/Playground/Contract.hs
- plutus-playground-server/test/Playground/UsecasesSpec.hs
- wallet-api/src/Wallet/Emulator/Types.hs
payToPubKey_ now takes a hash, instead of an Int ID. payToWallet_
behaves the way payToPubKey_ used to, and so works the way you want it
to in the frontend.
> Replacing the payToPubKey_ function with payToWallet_.

- plutus-tutorial/doctest/Tutorial/01-plutus-tx.md
- plutus-tx/compiler/Language/PlutusTx/Code.hs
- plutus-tx/compiler/Language/PlutusTx/Lift.hs
- plutus-tx/compiler/Language/PlutusTx/Plugin.hs
- plutus-tx/plutus-tx.cabal
- plutus-tx/src/Language/PlutusTx.hs
- plutus-tx/src/Language/PlutusTx/TH.hs
- plutus-tx/test/Lift/Spec.hs
- plutus-tx/test/Plugin/ReadValue.hs
- plutus-tx/test/Plugin/Spec.hs
- plutus-tx/test/TH/Spec.hs
- wallet-api/src/Ledger/Scripts.hs
- Put it in its own module.
- Allow it to contain a deserialized program too, and for the PIR
to be optional.
- Expose a typed `applyCode`.
- Expose a `liftCode` that produces `CompiledCode`.
- Use in tutorial.
> plutus-tx: improve interface to CompiledCode

- deployment/nixops/default-machine.nix
- deployment/nixops/default.nix
- deployment/nixops/prometheus.nix
- deployment/nixops/secrets.json.example
- deployment/nixops/server.nix
- deployment/terraform/templates/nixops_configuration.nix
This PR sends alerts to pager duty. I have tested this on a staging environment and saw the expected debug logs despite using a fake pager duty key.
Also we change from my fork of nixpkgs changes to the prometheus module to jbgi's changes merged in to my branch. This is because the branch https://github.com/NixOS/nixpkgs/pull/58255 is based on seemed to have some unrelated errors. We will look to upgrade our servers with the next NixOS release which should include this stuff.
> prometheus alert manager

- default.nix
- nix/git-rev.nix
- nix/overlays/git-module.nix
- release.nix
This is much more reliable than looking inside `.git`, which can be in
weird states and is best not to make assumptions about.
Wonderfully, since Nix is lazy, we can do this despite IFD being
disallowed on Hydra: in that case we'll have `declInput` so we'll never
evaluate the bit that needs IFD.
XXX: does not work for worktrees yet
> Get current git revision using IFD if we are not on Hydra

- plutus-playground-client/src/MainFrame.purs
- plutus-playground-client/src/Types.purs
Changing the list of available currencies has to have a knock-on
effect on the wallets and actions.
> Playground: Fixing #898.

- plutus-playground-lib/test/Playground/APISpec.hs
- plutus-playground-server/test/Playground/UsecasesSpec.hs
- plutus-tutorial/tutorial/Tutorial/Emulator.hs
- plutus-tutorial/tutorial/Tutorial/Vesting.hs
- plutus-tx/src/Language/PlutusTx/Prelude.hs
- plutus-tx/src/Language/PlutusTx/Prelude/Stage0.hs
- plutus-use-cases/plutus-use-cases.cabal
- plutus-use-cases/src/Language/PlutusTx/Coordination/Contracts/CrowdFunding.hs
- plutus-use-cases/src/Language/PlutusTx/Coordination/Contracts/Currency.hs
- plutus-use-cases/src/Language/PlutusTx/Coordination/Contracts/Currency/Stage0.hs
- plutus-use-cases/src/Language/PlutusTx/Coordination/Contracts/PubKey.hs
- plutus-use-cases/test/Spec.hs
- plutus-use-cases/test/Spec/Crowdfunding.hs
- plutus-use-cases/test/Spec/Currency.hs
- plutus-use-cases/test/Spec/Future.hs
- plutus-use-cases/test/Spec/Game.hs
- plutus-use-cases/test/Spec/Size.hs
- wallet-api/src/Ledger/Map.hs
- wallet-api/src/Ledger/Map/TH.hs
- wallet-api/src/Ledger/Validation.hs
- wallet-api/src/Ledger/Value.hs
- wallet-api/src/Ledger/Value/TH.hs
- wallet-api/src/Wallet/API.hs
- wallet-api/src/Wallet/Emulator/Client.hs
- wallet-api/src/Wallet/Emulator/Types.hs
- wallet-api/test/Spec.hs
Add a contract that creates a simple currency.
Also improve the way blockchain triggers work: WalletAPI now has a
function `registerOnce` that deletes the handler after the trigger has
fired once. `register`, the old function, is now implemented in terms of
`registerOnce`.
Depends on #866
> use-cases: Add currency contract

- plutus-playground-server/src/Playground/Server.hs
Double the server timeout to 20s in order to allow the state-machine based guessing game to go through.
https://gist.github.com/j-mueller/47b1dcfbfb1478537acf3aa505ffb0cb
> playground: Increase timeout

- ci/check-hydra.sh
Otherwise it will try and build the git revs, which we don't want.
Attempt no 2
> Pass an argument that hydra passes to prevent CI doing something different

- docs/extended-utxo/README.md
Fixes some small typos in the `README.md` for the extended UTxO
> Fix some typos in the mardown for the extended UTxO

- cabal.project
This bumps to GHC 8.6.5 in the cabal.project file, since that is what I have installed now.
> Bump to GHC 8.6.5 in cabal.project file

- plutus-tx/plutus-tx.cabal
This restricts `th-abstraction` bounds, as the latest release contains some breaking changes.
> Restrict th-abstraction bounds

- metatheory/Algorithmic/Erasure.lagda
- metatheory/Declarative/Erasure.lagda
- metatheory/Everything.lagda
- metatheory/Main.lagda
- metatheory/Scoped.lagda
- metatheory/Type/BetaNBE/RenamingSubstitution.lagda
- metatheory/Untyped.lagda
- metatheory/plc-agda.cabal
i.e. where meaning is given by erasure to untyped terms. So, we need to prove that it given a decl. term converting to an alg. term and then erasing gives the same result as erasing immediately.
This was suggested by an anonymous reviewer.
~~proof~~
> erasure of declarative and algorithmic terms

- plutus-playground-client/src/MainFrame.purs
- plutus-playground-client/src/MonadApp.purs
- plutus-playground-client/test/MainFrameTests.purs
It seems Firefox needs a couple of extra changes for drag and drop to work.
> Playground: Bugfix for drag and drop actions on Firefox.

- plutus-use-cases/plutus-use-cases.cabal
- plutus-use-cases/src/Language/PlutusTx/Coordination/Contracts/GameStateMachine.hs
- plutus-use-cases/src/Language/PlutusTx/Coordination/Contracts/MultiSig/Stage0.hs
- plutus-use-cases/src/Language/PlutusTx/Coordination/Contracts/MultiSigStateMachine.hs
- plutus-use-cases/test/Spec.hs
- plutus-use-cases/test/Spec/MultiSigStateMachine.hs
- plutus-wallet-api/ledger/Ledger/Slot.hs
- plutus-wallet-api/ledger/Ledger/Validation.hs
- plutus-wallet-api/src/Language/PlutusTx/StateMachine.hs
- plutus-wallet-api/src/Wallet/API.hs
Another implementation of the n-out-of-m multisig contract. It uses a state machine to implement a proposal system where people can attach their signatures to a proposed payment. This removes the need for the _n_ signatories to all sign the same transaction (which requires off-chain coordination via email etc.)
I only added two unit tests because they take relatively long.
```
multi sig state machine tests
lock, propose, sign 3x, pay - SUCCESS:     OK (125.93s)
lock, propose, sign 2x, pay - FAILURE:     OK (109.45s)
script size is reasonable:                 Script size: 328114
```
Also the script size seems to be quite large (10x the size of the crowdfunding script for example).
> use-cases: Add state-machine based multisig contract

- .hlint.yaml
- language-plutus-core/generators/Language/PlutusCore/Generators/Interesting.hs
- language-plutus-core/generators/Language/PlutusCore/Generators/Internal/Denotation.hs
- language-plutus-core/generators/Language/PlutusCore/Generators/Internal/Dependent.hs
- language-plutus-core/generators/Language/PlutusCore/Generators/Internal/Entity.hs
- language-plutus-core/generators/Language/PlutusCore/Generators/Internal/TypeEvalCheck.hs
- language-plutus-core/generators/Language/PlutusCore/Generators/Internal/Utils.hs
- language-plutus-core/generators/Language/PlutusCore/Generators/Test.hs
- language-plutus-core/src/Language/PlutusCore/Constant/Apply.hs
- language-plutus-core/src/Language/PlutusCore/Constant/Name.hs
- language-plutus-core/src/Language/PlutusCore/Evaluation/CkMachine.hs
- language-plutus-core/src/Language/PlutusCore/Evaluation/Result.hs
- language-plutus-core/src/Language/PlutusCore/View.hs
- language-plutus-core/test/Evaluation/Constant/Success.hs
- language-plutus-core/test/Evaluation/Golden/verifySignatureError.plc.golden
This fixes the `1/0` bug, but disables term-generation tests related to division (and `verifySignature`), because test generation is broken for them. There is now a dedicated test that checks that division by zero is handled properly, though.
> [PLC] [Builtins] Made 1/0 evaluate to 'Error'

- plutus-tx/compiler/Language/PlutusTx/Compiler/Expr.hs
- plutus-tx/compiler/Language/PlutusTx/Plugin.hs
- plutus-tx/test/Plugin/errors/machInt.plc.golden
- plutus-wallet-api/ledger/Ledger/Validation.hs
There are so many ways to make string literals!
This one I think is something of an artifact of the way we use `INLINABLE`, but this at least deals with it a bit better than having to turn off rewrite rules...
Few minor refactorings and a fix too.
> plutus-tx: deal with unpackCStringFoldr#

- language-plutus-core/language-plutus-core.cabal
Forbid latest hedgehog release, so that our packages can be built with `cabal`.
> Forbid hedgehog 1.0

- language-plutus-core/src/Language/PlutusCore/MkPlc.hs
- language-plutus-core/stdlib/Language/PlutusCore/StdLib/Meta/Data/Tuple.hs
- plutus-ir/src/Language/PlutusIR.hs
- plutus-ir/src/Language/PlutusIR/Compiler.hs
- plutus-ir/src/Language/PlutusIR/Compiler/Datatype.hs
- plutus-ir/src/Language/PlutusIR/Compiler/Let.hs
- plutus-ir/src/Language/PlutusIR/Compiler/Recursion.hs
- plutus-ir/src/Language/PlutusIR/Compiler/Types.hs
- plutus-ir/test/Spec.hs
- plutus-ir/test/datatypes/listMatchEval.golden
- plutus-ir/test/recursion/even3.golden
- plutus-ir/test/recursion/even3Eval.golden
- plutus-ir/test/recursion/mutuallyRecursiveValues.golden
- plutus-tx/compiler/Language/PlutusTx/Lift.hs
- plutus-tx/compiler/Language/PlutusTx/Plugin.hs
- plutus-tx/test/Lift/boolInterop.plc.golden
- plutus-tx/test/Plugin/Data/recursive/sameEmptyRoseEval.plc.golden
- plutus-tx/test/Plugin/Functions/recursive/even3.plc.golden
- plutus-tx/test/Plugin/Functions/recursive/even4.plc.golden
- plutus-tx/test/Plugin/Laziness/joinErrorEval.plc.golden
- plutus-tx/test/Plugin/Primitives/andApply.plc.golden
- plutus-tx/test/Plugin/Primitives/equalsByteString.plc.golden
- plutus-tx/test/Plugin/Primitives/intEqApply.plc.golden
- plutus-tx/test/TH/all.plc.golden
This implements the other main suggestion in #610, by generating PIR let-bindings during compilation of recursive bindings. These can then be eliminated with another dead-binding pass.
The main effect of this is when we have a pair of mutually recursive functions of which only one is used in the body - in this case we can delete the "forwarding" binding that converts from the tuple form we use for the recursion combinator into a form that's easier to consume. We can see this firing in a number of cases in our tests.
A minor win, but every little helps.
I also did some refactoring to have an "optimization on" compilation option. One wrinkle is that in the plugin we want to manually run the simplifier once before we hand over to the PIR compiler, so that we can store/dump slightly better …
> plutus-ir: use let-bindings in compilation, exploit with later dead-binding removal

- plutus-playground-server/usecases/CrowdFunding.hs
- plutus-playground-server/usecases/Game.hs
- plutus-playground-server/usecases/Vesting.hs
- plutus-use-cases/src/Language/PlutusTx/Coordination/Contracts/CrowdFunding.hs
- plutus-use-cases/src/Language/PlutusTx/Coordination/Contracts/Vesting.hs
Analogously but not identically to the ones in `plutus-use-cases`
I also added a simplification to the vesting examples, which I think make them a lot easier to read.
> plutus-playground: refactor usecases

- nix/overlays/required.nix
Significantly improves the slow doctest problem!
Time for `plutus-tx` went from 350s to 35s, `plutus-tutorial` from 150s to 25s.
> Build doctest with --enable-executable dynamic

- nix/overlays/required.nix
- pkgs/default.nix
- plutus-playground-server/app/PSGenerator.hs
- plutus-playground-server/plutus-playground-server.cabal
- plutus-playground-server/src/Playground/Server.hs
- plutus-playground-server/src/Playground/Usecases.hs
- plutus-playground-server/test/Playground/UsecasesSpec.hs
- plutus-playground-server/usecases/CrowdFunding.hs
- plutus-playground-server/usecases/Game.hs
- plutus-playground-server/usecases/Messages.hs
- plutus-playground-server/usecases/Vesting.hs
This makes them *much* easier to work on. The tests are hard to run and
slow, this way you can check that they at least compile with a normal
build.
However, we now need a module header and pragmas. Those need to be stripped off for use, but that's easy enough.
I also needed to include the workaround for Haddock with the plugin.
> plutus-use-cases: compile the usecases normally

- pkgs/default.nix
- plutus-contract-exe/src/Language/Plutus/Contract.hs
- plutus-emulator/plutus-emulator.cabal
- plutus-emulator/src/Wallet/Emulator/Types.hs
- plutus-emulator/test/Spec.hs
- plutus-playground-server/usecases/CrowdFunding.hs
- plutus-tutorial/doctest/Tutorial/03-wallet-api.md
- plutus-tutorial/tutorial/Tutorial/Solutions0.hs
- plutus-use-cases/src/Language/PlutusTx/Coordination/Contracts/CrowdFunding.hs
- plutus-use-cases/src/Language/PlutusTx/Coordination/Contracts/Currency.hs
- plutus-use-cases/src/Language/PlutusTx/Coordination/Contracts/GameStateMachine.hs
- plutus-wallet-api/ledger/Ledger/Index.hs
- plutus-wallet-api/ledger/Ledger/Interval.hs
- plutus-wallet-api/ledger/Ledger/Map.hs
- plutus-wallet-api/ledger/Ledger/Slot.hs
- plutus-wallet-api/ledger/Ledger/Tx.hs
- plutus-wallet-api/ledger/Ledger/Value.hs
- plutus-wallet-api/plutus-wallet-api.cabal
- plutus-wallet-api/src/Wallet/API.hs
It's only a partial order, so it's misleading. Two large-ish changes were needed:
- We put a derived type in a `Map`, which won't fly. Fortunately, `HashMap` works fine, but I had to add a bunch of instances.
- We use it in an `Interval` for `fundsAtAddress`. This is questionable given it being a partial order, and we only actually check whether funds are greater than something, so we use that. That also has the advantage of being more honest, since we can't tell if funds are less than something, given that we're only watching a subset of the funds. Possibly it should be `geq`, though.
I then found an awful bug in `Value.lt` and `Value.gt`, which were saying that `zero lt zero` and `zero gt zero`, since there's a degenerate case where both maps are empty.
> Remove the `Ord` instnance for `Value`

- nix/overlays/required.nix
- plutus-playground-server/usecases/CrowdFunding.hs
- plutus-playground-server/usecases/Game.hs
- plutus-playground-server/usecases/Vesting.hs
- plutus-tutorial/doctest/Tutorial/02-validator-scripts.md
- plutus-tutorial/doctest/Tutorial/03-wallet-api.md
- plutus-tutorial/tutorial/Tutorial/Solutions0.hs
- plutus-tutorial/tutorial/Tutorial/Solutions2.hs
- plutus-tutorial/tutorial/Tutorial/Vesting.hs
- plutus-tx/src/Language/PlutusTx/Prelude.hs
- plutus-use-cases/src/Language/PlutusTx/Coordination/Contracts/CrowdFunding.hs
- plutus-use-cases/src/Language/PlutusTx/Coordination/Contracts/Currency.hs
- plutus-use-cases/src/Language/PlutusTx/Coordination/Contracts/Future.hs
- plutus-use-cases/src/Language/PlutusTx/Coordination/Contracts/Game.hs
- plutus-use-cases/src/Language/PlutusTx/Coordination/Contracts/GameStateMachine.hs
- plutus-use-cases/src/Language/PlutusTx/Coordination/Contracts/MultiSig.hs
- plutus-use-cases/src/Language/PlutusTx/Coordination/Contracts/MultiSigStateMachine.hs
- plutus-use-cases/src/Language/PlutusTx/Coordination/Contracts/PubKey.hs
- plutus-use-cases/src/Language/PlutusTx/Coordination/Contracts/Swap.hs
- plutus-use-cases/src/Language/PlutusTx/Coordination/Contracts/Vesting.hs
- plutus-wallet-api/ledger/Ledger/Scripts.hs
- plutus-wallet-api/plutus-wallet-api.cabal
- plutus-wallet-api/src/Language/PlutusTx/StateMachine.hs
See the note in `Index.hs`.
This makes things easier for script authors. We do need to apply an
adaptor during validation so we can still have a simple check (is it
error or not).
> plutus-wallet-api: make the result type of validator scripts be Bool

- pkgs/default.nix
- plutus-ir/plutus-ir.cabal
- plutus-ir/src/Language/PlutusIR.hs
- plutus-ir/src/Language/PlutusIR/Analysis/Dependencies.hs
- plutus-ir/src/Language/PlutusIR/Analysis/Usages.hs
- plutus-ir/src/Language/PlutusIR/Compiler/Let.hs
- plutus-ir/src/Language/PlutusIR/Optimizer/DeadCode.hs
- plutus-ir/src/Language/PlutusIR/Transform/Substitute.hs
- plutus-ir/src/Language/PlutusIR/Transform/ThunkRecursions.hs
A slightly more experimental refactoring here.
We can't (easily) use `recursion-schemes` for the PIR AST, because it has two mutually recursive datatypes, `Term` and `Binding`. However, we can get a lot of the benefit by defining suitable `Traversal`s for getting sub-terms/types of our AST. In particular, we can get the sub-terms of a `Term`, looking through `Binding`s. Then we can use combinators from `Lens.Plated` to do nice bottom-up recursive traversals and generic operations.
This lets us ditch a lot of boilerplate. I think it's no weirder to think about than the `recursion-schemes` approach, so overall I think I like it.
As a bonus, you can naturally do fusion of optimization/compilation passes with this approach. I'm not going to do that here, because I don't think it gains us …
> plutus-ir: use lens-based traversals

- plutus-playground-lib/src/Playground/Contract.hs
- plutus-playground-server/test/Playground/UsecasesSpec.hs
The `SlotRange` type isn't displayed very nicely in the Playground, and the validity range doesn't matter for normal payments between wallets anyway. We can just use the default validity range everywhere.
> playground: Remove validity range parameter from payToWallet_

- plutus-wallet-api/plutus-wallet-api.cabal
This is for the `cabal new-build` workflow I use, but serves a purpose if we release for Hackage.
> Restrict swagger2 library bounds

- plutus-tx/compiler/Language/PlutusTx/Compiler/Binders.hs
- plutus-tx/compiler/Language/PlutusTx/Compiler/Builtins.hs
- plutus-tx/compiler/Language/PlutusTx/Compiler/Error.hs
- plutus-tx/compiler/Language/PlutusTx/Compiler/Expr.hs
- plutus-tx/compiler/Language/PlutusTx/Compiler/Expr.hs-boot
- plutus-tx/compiler/Language/PlutusTx/Compiler/Kind.hs
- plutus-tx/compiler/Language/PlutusTx/Compiler/Laziness.hs
- plutus-tx/compiler/Language/PlutusTx/Compiler/Names.hs
- plutus-tx/compiler/Language/PlutusTx/Compiler/Primitives.hs
- plutus-tx/compiler/Language/PlutusTx/Compiler/Type.hs
- plutus-tx/compiler/Language/PlutusTx/Compiler/Type.hs-boot
- plutus-tx/compiler/Language/PlutusTx/Compiler/Types.hs
- plutus-tx/compiler/Language/PlutusTx/Compiler/Utils.hs
- plutus-tx/compiler/Language/PlutusTx/Compiler/ValueRestriction.hs
- plutus-tx/compiler/Language/PlutusTx/Plugin.hs
- plutus-tx/test/Plugin/Errors/machInt.plc.golden
- Refactor a couple of functions in `Type`
- Use "compile" uniformly instead of "convert". I don't know what past-me was thinking.
- Move a function to `Expr`
Mostly of interest to me, I suspect.
> plutus-tx: minor refactorings

- marlowe/src/Language/Marlowe/Common.hs
- plutus-playground-server/usecases/CrowdFunding.hs
- plutus-playground-server/usecases/Vesting.hs
- plutus-tutorial/doctest/Tutorial/03-wallet-api.md
- plutus-tutorial/tutorial/Tutorial/Solutions0.hs
- plutus-tutorial/tutorial/Tutorial/Vesting.hs
- plutus-tx/src/Language/PlutusTx/Prelude.hs
- plutus-use-cases/src/Language/PlutusTx/Coordination/Contracts/CrowdFunding.hs
- plutus-use-cases/src/Language/PlutusTx/Coordination/Contracts/Currency.hs
- plutus-use-cases/src/Language/PlutusTx/Coordination/Contracts/Future.hs
- plutus-use-cases/src/Language/PlutusTx/Coordination/Contracts/GameStateMachine.hs
- plutus-use-cases/src/Language/PlutusTx/Coordination/Contracts/MultiSigStateMachine.hs
- plutus-use-cases/src/Language/PlutusTx/Coordination/Contracts/Swap.hs
- plutus-use-cases/src/Language/PlutusTx/Coordination/Contracts/Vesting.hs
- plutus-wallet-api/ledger/Ledger/Map.hs
- plutus-wallet-api/ledger/Ledger/Validation.hs
- plutus-wallet-api/ledger/Ledger/Value.hs
- plutus-wallet-api/src/Language/PlutusTx/StateMachine.hs
As discussed on Slack. This is significantly better, although only really when imported unqualified. That means a few more instances of `import Prelude hiding`.
> plutus-tx: 'and' -> '&&', 'or' -> '||'

- cabal.project
cc @shmish111 but I do not believe this needs review
This makes `cabal new-build` work the same as `stack build`
> Add purescript-bridge to cabal.project matching stack.yaml

- plutus-playground-server/plutus-playground-server.cabal
Intero (or possibly cabal) has problems if the library sections aren't
put before the executable ones, it seems. :-/
> Moving the cabal library definition of plutus-playground-usecases.

- marlowe/src/Language/Marlowe/Common.hs
- plutus-playground-server/src/Playground/Server.hs
- plutus-tutorial/doctest/Tutorial/01-plutus-tx.md
- plutus-tx/src/Language/PlutusTx/Prelude.hs
- plutus-tx/test/TH/all.plc.golden
- plutus-wallet-api/ledger/Ledger/Ada.hs
- plutus-wallet-api/ledger/Ledger/Map.hs
- plutus-wallet-api/ledger/Ledger/These.hs
- plutus-wallet-api/ledger/Ledger/Validation.hs
- plutus-wallet-api/ledger/Ledger/Value.hs
- plutus-wallet-api/src/Language/PlutusTx/StateMachine.hs
This makes us more sensitive to compiler behaviour, which is undesirable.
> Back out use of `-fexpose-all-unfoldings`

- default.nix
- deploy-docs.sh
- lib.nix
- shell.nix
We don't want to e.g. have all the tutorial modules appearing in the
published Haddock.
Also having a list of "public" packages may be useful for publishing to
Hackage later.
> Only put "public" packages into the published Haddock

- language-plutus-core/src/Language/PlutusCore.hs
- language-plutus-core/src/Language/PlutusCore/Normalize/Internal.hs
- language-plutus-core/src/Language/PlutusCore/Subst.hs
- language-plutus-core/src/Language/PlutusCore/TH.hs
- language-plutus-core/src/Language/PlutusCore/Type.hs
- plutus-ir/src/Language/PlutusIR.hs
- plutus-ir/src/Language/PlutusIR/Compiler/Datatype.hs
- plutus-ir/src/Language/PlutusIR/Transform/Substitute.hs
Since I've learned how to do this, might as well push it a bit.
A few wrinkles have emerged:
- `transformMOf` is very nice, but it doesn't work well where you want to do something based on the current node before recursing, e.g. in the renamer with freshening names. So we need to keep the manual recursion there.
- Possibly we could write a hairy function that did this. Maybe something like this [ADI stuff](http://www.newartisans.com/2018/04/win-for-recursion-schemes/).
- The traversals are type-preserving, so we can't e.g. change the type of names, so we cant' use this for `DeBruijn`, which would benefit a lot from it.
- I think this is fundamental: using the `Traversable` instance for `TermF` we can have the subterms transformed to have a new name type, after which we fiddle with bound …
> language-plutus-core: use traversals to cut down on some boilerplate

- default.nix
- plutus-tutorial/doc/default.nix
This is a self-contained site that can be deployed with the
Playground.
We need to set the relative URLs that correspond to how things are going
to be served, but this can adjusted when we actually start doing that.
> Build: build a documentation site for the Playground

- plutus-tx/src/Language/PlutusTx/Prelude.hs
- plutus-wallet-api/ledger/Ledger/Map.hs
This is the last operator in the Prelude that should really be symbolic.
(Note that `gt`, `eq` etc should *not* be, since then they would shadow
the Haskell Preldue ones, but they're monomorphic and
not appropriate replacements for the Haskell Prelude's
typeclass-polymorphic functions.)
> plutus-tx: append -> ++

- plutus-playground-client/src/MonadApp.purs
- plutus-playground-client/test/MainFrameTests.purs
When I originally wrote this code I didn't know PureScript could do
this. :-D
> Replacing some hand-rolled instances with `derive newtype ...`.

- language-plutus-core/bench/Bench.hs
- language-plutus-core/generators/Language/PlutusCore/Generators/Internal/TypeEvalCheck.hs
- language-plutus-core/language-plutus-core.cabal
- language-plutus-core/src/Language/PlutusCore.hs
- language-plutus-core/src/Language/PlutusCore/Check/Normal.hs
- language-plutus-core/src/Language/PlutusCore/Check/Uniques.hs
- language-plutus-core/src/Language/PlutusCore/Check/Value.hs
- language-plutus-core/src/Language/PlutusCore/Normalize.hs
- language-plutus-core/src/Language/PlutusCore/View.hs
- language-plutus-core/test/Check/Spec.hs
- language-plutus-core/test/Normalization/Check.hs
- language-plutus-core/test/TypeSynthesis/Spec.hs
- plutus-emulator/test/Spec.hs
- plutus-tx/compiler/Language/PlutusTx/Code.hs
- plutus-tx/compiler/Language/PlutusTx/Compiler/Error.hs
- plutus-tx/compiler/Language/PlutusTx/Compiler/Types.hs
- plutus-tx/compiler/Language/PlutusTx/Compiler/ValueRestriction.hs
- plutus-tx/compiler/Language/PlutusTx/Plugin.hs
- plutus-wallet-api/ledger/Ledger/Scripts.hs
This started off as an attempt to finish off https://github.com/input-output-hk/plutus/pull/925, but the rabbit hole became rather deeper than I expected.
Commit messages should explain each in turn.
Overall this:
- Disentangles term value checking and type normalization checking.
- Normalizes types in `plutus-wallet-api`.
- Makes `plutus-wallet-api` actually do the typechecking as it's supposed to do it in the real implementation.
Notes:
- There were several things that were suspicious about value checking. One notable one is that I asserted in the note that builtin application should be a value. This is precisely the confusion I mentioned: they are in *normal form*, but they are *not* values. In particular, they can evaluate to `error`, so have visibly different behaviour under a type …
> plutus-wallet-api: typecheck scripts as we are supposed to

- language-plutus-core/src/Language/PlutusCore/CBOR.hs
- language-plutus-core/src/Language/PlutusCore/Constant/Apply.hs
- language-plutus-core/src/Language/PlutusCore/Constant/Name.hs
- language-plutus-core/src/Language/PlutusCore/Lexer.x
- language-plutus-core/src/Language/PlutusCore/Lexer/Type.hs
- plutus-core-spec/figures/Builtins.tex
- plutus-tx/compiler/Language/PlutusTx/Builtins.hs
- plutus-tx/compiler/Language/PlutusTx/Compiler/Builtins.hs
- plutus-tx/src/Language/PlutusTx/Prelude.hs
- plutus-tx/test/Plugin/Primitives/Spec.hs
- plutus-tx/test/Plugin/Primitives/ltByteString.plc.golden
This means we can do `Ord`-like things with bytestrings, like use them
as the keys of binary search trees.
I don't think we can get away without adding more builtins for these things, alas.
> language-plutus-core: add lessThanByteString and greaterThanByteString

- plutus-book/doc/01-preface.adoc
- plutus-book/doc/02-glossary.adoc
- plutus-book/doc/03-UTxO.adoc
- plutus-book/doc/04-smartcont.adoc
- plutus-book/doc/05-welcome.adoc
- plutus-book/doc/06-lifecycle.adoc
- plutus-book/doc/07-tour.adoc
- plutus-book/doc/08-testing.adoc
- plutus-book/doc/09-extended.adoc
- plutus-book/doc/plutus.adoc
Adding a bit of text and some possible chapters to the book
> Try out adoc

- pkgs/default.nix
- stack.yaml
Apparently this was ancient legacy syntax that they've finally removed.
Also regenerated the package set.
> Fix stack file syntax

- pkgs/default.nix
- plutus-emulator/test/Spec.hs
- plutus-playground-lib/plutus-playground-lib.cabal
- plutus-playground-lib/src/Playground/API.hs
- plutus-playground-server/app/PSGenerator.hs
- plutus-tx/plutus-tx.cabal
- plutus-tx/src/Language/PlutusTx/AssocMap.hs
- plutus-tx/src/Language/PlutusTx/These.hs
- plutus-use-cases/src/Language/PlutusTx/Coordination/Contracts/Currency.hs
- plutus-wallet-api/ledger/Ledger/Value.hs
- plutus-wallet-api/plutus-wallet-api.cabal
- plutus-wallet-api/test/Spec.hs
I found myself moving these in a couple of other branches, so I thought
I'd just do it on master.
`plutus-tx` feels like a more natural home for these, since that's where
our "standard library" lives, and they're pretty general data
structures, rather than being ledger-specific.
> plutus-tx: absorb Map and These modules

- pkgs/default.nix
- plutus-use-cases/bench/Bench.hs
- plutus-use-cases/bench/IFix.hs
- plutus-use-cases/bench/Recursion.hs
- plutus-use-cases/bench/Scott.hs
- plutus-use-cases/plutus-use-cases.cabal
- plutus-wallet-api/ledger/Ledger/Index.hs
- plutus-wallet-api/ledger/Ledger/Scripts.hs
- plutus-wallet-api/ledger/Ledger/Validation.hs
This adds some very basic benchmarks comparing:
- Signature verification, which is the main cryptographic operation that
we perform.
- Hashing.
- Execution of a trivial validator that returns `True`.
- Execution of `fib`.
- Execution of `sum`.
- Execution of `tail`.
- Execution of the multi-sig contract. Multi-sig is more-or-less the
simplest contract that we have which does some reasonable work.
I haven't added any of the other use-cases yet, or other cryptographic
functions.
High-level takeaways:
- Both signature verification and simple script execution come out at
~50 microseconds on my machine.
- As scripts get more complex execution easily gets into 100s of
microseconds.
- Note that multi-sig does some signature validation, so is inflated
by that.
- Computing fibonnaci numbers can …
> plutus-use-cases: add some benchmarks for crypto and multisig

- plutus-playground-client/src/MainFrame.purs
The changelog should be append-only, so it should be okay to just send
people to the latest one.
This also removes another usage of the baked-in git revision.
(I'm not 100% sure this is a good idea, but I think it is.)
> Playgrounds: link to the master version of the changelog

- plutus-tx/compiler/Language/PlutusTx/Compiler/Names.hs
- plutus-tx/compiler/Language/PlutusTx/Compiler/Type.hs
- plutus-tx/test/Plugin/Data/monomorphic/defaultCase.plc.golden
- plutus-tx/test/Plugin/Data/monomorphic/enum.plc.golden
- plutus-tx/test/Plugin/Data/monomorphic/irrefutableMatch.plc.golden
- plutus-tx/test/Plugin/Data/monomorphic/monoCase.plc.golden
- plutus-tx/test/Plugin/Data/monomorphic/monoConstructed.plc.golden
- plutus-tx/test/Plugin/Data/monomorphic/monoConstructor.plc.golden
- plutus-tx/test/Plugin/Data/monomorphic/monoDataType.plc.golden
- plutus-tx/test/Plugin/Data/monomorphic/nonValueCase.plc.golden
- plutus-tx/test/Plugin/Data/polymorphic/defaultCasePoly.plc.golden
- plutus-tx/test/Plugin/Data/polymorphic/polyConstructed.plc.golden
- plutus-tx/test/Plugin/Data/polymorphic/polyDataType.plc.golden
- plutus-tx/test/Plugin/Functions/unfoldings/recordSelector.plc.golden
- plutus-tx/test/Plugin/Functions/unfoldings/recordSelectorExternal.plc.golden
- plutus-tx/test/Plugin/Laziness/joinError.plc.golden
- plutus-tx/test/Plugin/Typeclasses/defaultMethods.plc.golden
I've observed these being nondeterministic on bigger examples (possibly
related to the order in which modules are processed). So we kind of have
to strip them.
This has two annoying downsides:
- We strip "real" trailing digits from names (witness the diffs in the
`plutus-tx` tests).
- We lose the disambiguation they provide. This is especially annoying
for generated names like the many occurrences of `ds`.
We could regain the disambiguation by running our *own* disambiguation
pass, which would be deterministic. Not sure if this is worth it, I'll
probably just see how annoying it is in practice.
I hope this will fix https://github.com/input-output-hk/plutus/pull/1167.
> plutus-tx: reverse GHC's OccName tidying

- .gitattributes
I think this will stop them contributing to our stats. Ideally I'd mark
them as "no language" but I can't find out how to do that.
> Mark .pir files as linguist-detectable=false

- pkgs/default.nix
- stack.yaml
MPJ needed to patch shmish111/servant-purescript, but the patch was
applied to the wrong branch. It was applied to `master`, should have
been against `purs012`.
Fixed and fixed.
> Fix for the fix to 1180.

- plutus-playground-client/src/Chain/BlockchainExploration.purs
- plutus-playground-client/src/ValueEditor.purs
- plutus-playground-client/test/TypesTests.purs
- plutus-playground-client/test/compilation_response1.json
- plutus-playground-client/test/evaluation_response1.json
- plutus-playground-client/test/known_currency.json
The playground used currency symbol "5fff" for Ada, whereas `Ledger.Ada` used the empty string. I changed all occurences of "5fff" to "".
> fixed bug #1005

- plutus-playground-lib/test/Playground/APISpec.hs
- plutus-wallet-api/ledger/Ledger/Validation.hs
The reason for the spurious 5fff hash was that the `ToJSON` instance of `ValidatorHash` serialised the hash before `toJSON`ing it, so it included some extra bytes from the serialised representation.
> ledger: Fix JSON instances for ValidatorHash et al.

- deployment-server/app/Main.hs
- deployment-server/src/Deploy/Types.hs
- deployment-server/src/Deploy/Worker.hs
- deployment/nixops/prometheus.nix
This should give us lower risk deployment, if the health check endpoints fail on availability zone A then the deployment will stop and the playgrounds will still be running on availability zone B. When health checks fail then those instances will be removed from the AWS ALB so no traffic will be routed to them. The window of possible user errors should be the ALB health check interval which is 30 seconds.
This is difficult to test in any way other than end2end so I tested it on my own full environment, I can curl to the public facing url that github would talk to. I managed to deal with errors and also successfully redeploy master to my own environment so it looks good.
> rolling deploy

- plutus-book/doc/default.nix
- plutus-tutorial/doc/default.nix
The default is FATAL, which is only for really bad stuff like the main
file not being there. We definitely want it to fail on ERROR, which
includes things like "you tried to include a nonexistent file".
> asciidoctor: fail if an error-level message is emitted

- plutus-tutorial/README.adoc
Linking the README.adoc file to the overview.adoc in the doc directory causes all links on the first page not to work.
My fix removes the overview.adoc, and moves it into the root as README.adoc with updated references (so the links still work). I also replaced filenames with a textual representation (ex: doc/intro.adoc with `Introduction`).
This is a very small change, but I think it is important not to have broken links on the first tutorial page, and would like to merge it sooner rather than later.
> Fix broken links on the main page.

- marlowe-playground-server/app/PSGenerator.hs
- plutus-playground-server/app/PSGenerator.hs
`gitRev` is not used in any purescript code any more so this should avoid the need to rebuild the purescript code on every git commit.
> remove gitRev from purescript

- extended-utxo-spec/extended-utxo-specification.tex
I accidentally merged a draft of the eutxo specification with the master branch a while ago. This PR is just to turn off the todo notes,  since it's publicly visible.  We could also delete it pending a final version, but this version isn't too bad.
> Turn off the todo notes in the eutxo spec

- plutus-core-spec/figures/CkMachine.tex
- plutus-core-spec/figures/TermReduction.tex
- plutus-core-spec/plutus-core-specification.tex
As suggested a while ago, I've modified the evaluation rules in the PLC spec to include type instantiation.  I've left the CK machine unchanged and added some remarks pointing out the differences and claiming that we can prove that it doesn't make too much difference.  We may eventually want to modify the CK machine to match, and say that we do something different in practice (or even have two different versions of the machine).  See https://github.com/input-output-hk/plutus/issues/1145 in connection with this.
There are still a number of unresolved issues, like whether we want unsaturated builtins: see https://github.com/input-output-hk/plutus/pull/1162 . I was hoping for some input from Manuel, but he's away for a couple of weeks and will presumably have a lot of catching up to do when …
> Modify reduction rules to include type instantiation

- plutus-book/doc/non-fungible/nonfungible8.adoc
- plutus-book/test/NonFungible/NonFungible8Spec.hs
Otherwise it was using a hardcoded hash, which breaks easily.
> Make plutus book test more reliable

- marlowe/test/Spec/Common.hs
- plutus-book/test/NonFungible/NonFungible2Spec.hs
- plutus-book/test/NonFungible/NonFungible4Spec.hs
- plutus-emulator/src/Wallet/Emulator/Types.hs
- plutus-emulator/test/Spec.hs
- plutus-use-cases/test/Spec/Future.hs
- plutus-use-cases/test/Spec/Vesting.hs
This is usually what you want, and makes failing tests stop a lot
sooner. Users can explicitly say they want an action to fail, as well.
> plutus-emulator: make walletAction assert success by default

- plutus-playground-client/package.json
There was an extra space in the command line call, which meant that
"jump to definition" didn't work.
> Fixing a bug on the purs:ide invoker.

- marlowe-playground-server/test/Spec.hs
- plutus-book/doc/marlowe/Language/Marlowe/common.adoc
- plutus-playground-server/test/Playground/UsecasesSpec.hs
I'm not sure this should be here at all, but anyway it had a conflict
after merging.
> Fix a semantic merge conflict in a copy (?!) of the Marlowe interpreter

- plutus-tx/src/Language/PlutusTx/List.hs
- plutus-tx/src/Language/PlutusTx/Prelude.hs
I added `(!!) :: [a] -> Integer -> a` to `Language.PlutusTx.List`. The behavior should be the same as the one from `GHC.List` - in particular it is an error to have the index out of bound.
> PlutusTx version of GHC.List.(!!)

- CONTRIBUTING.adoc
- default.nix
- language-plutus-core/shell.nix
- marlowe/shell.nix
- playground-common/shell.nix
- plutus-contract/shell.nix
- plutus-core-interpreter/shell.nix
- plutus-emulator/shell.nix
- plutus-exe/shell.nix
- plutus-ir/shell.nix
- plutus-playground-lib/shell.nix
- plutus-playground-server/shell.nix
- plutus-tutorial/shell.nix
- plutus-tx/shell.nix
- plutus-use-cases/shell.nix
- plutus-wallet-api/shell.nix
These were just confusing. There are instructions in `CONTRIBUTING.adoc`
for what to do if you really ned a per-package env.
> Remove per-package shell.nix files

- plutus-emulator/src/Wallet/Emulator/Types.hs
- plutus-playground-client/src/Action.purs
- plutus-playground-client/src/MainFrame.purs
- plutus-playground-client/src/MonadApp.purs
- plutus-playground-client/src/Types.purs
- plutus-playground-lib/src/Playground/API.hs
- plutus-playground-server/app/PSGenerator.hs
- plutus-playground-server/src/Playground/Interpreter.hs
- plutus-playground-server/src/Playground/Server.hs
This should fix https://github.com/input-output-hk/plutus/issues/1365
I have done 2 things:
1. Made the `/evaluate` endpoint return errors correctly, previously if any errors occurred we got a decoding error as we were trying to decode to a successful evaluation. We shouldn't really get any errors here but if we do we can deal with them in a better way, for example I've dealt with a timeout error with a proper message.
2. `runWalletActionAndProcessPending` was creating a `Failure` action if an error is thrown in the wallet action. This was caused by https://github.com/input-output-hk/plutus/pull/1329 but I don't think it's what we want in this particular function as it causes the whole trace to fail. Rather we want  the function to carry on if the wallet action has a failure in it so that …
> Playground errors weren't working correctly

- plutus-playground-client/src/Data/String/Extra.purs
`String.length` is relatively slow in PureScript (compared to the
native JavaScript function) because unlike JavaScript, they take pains
to handle Unicode correctly.
Normally that wouldn't matter much, but the BlockchainExploration code
can end up calling `abbreviate` on some datascript hashes which can
get _very_ large (megabytes worth of strings). That just bit us in issue
1391. Chewing through all those megabytes (several times) just to
abbreviate them wa making some scenarios pathologically slow.
There are two solutions to this:
1) Use `Data.String.CodeUnits.length`, which is just the native
JavaScript call.
2) Only consider the first N characters in our abbreviation algorithm.
In practice they're both inperceptibly fast, so I'm going with 2 as
it's the more correct (unicode-aware) …
> Performance enhancement for `abbreviate`.

- plutus-tx/compiler/Language/PlutusTx/Lift.hs
- plutus-tx/compiler/Language/PlutusTx/Lift/Class.hs
- plutus-tx/compiler/Language/PlutusTx/Lift/THUtils.hs
- plutus-tx/test/Lift/Spec.hs
- plutus-tx/test/Lift/syn.plc.golden
- plutus-wallet-api/ledger/Ledger/Validation.hs
I took the old approach of "refactor until the change you want to make is easy". In this case that involved quite a bit of chopping and changing, but I think the result is somewhat more comprehensible.
Probably not worth that much review, it took me about a day to load this back into my brain, I don't wish that on anyone else.
Fixes #1409.
> Fix handling of type synonyms when generating `Lift`

- default.nix
* A docker image that can be used to build the example in `example/`
Output:
```
jann@iohk-dev-vm:~/plutus-example$ sudo docker run -w /app -v "$(pwd)":/app -v ~/tmp:/tmp --name dev plutus-development:iwhhac55vfnwgqff1v29scc6g2gdw2dw cabal new-build .
Config file path source is default config file.
Config file //.cabal/config not found.
Writing default configuration to //.cabal/config
Build profile: -w ghc-8.6.4 -O1
In order, the following will be built (use -v for more details):
- example-0.1.0.0 (lib) (first run)
- example-0.1.0.0 (exe:example-exe) (first run)
Preprocessing library for example-0.1.0.0..
Building library for example-0.1.0.0..
Configuring executable 'example-exe' for example-0.1.0.0..
Preprocessing executable 'example-exe' for example-0.1.0.0..
Building executable …
```
> nix: Docker image for development

- plutus-tx/src/Language/PlutusTx/Prelude.hs
- plutus-tx/test/Plugin/Functions/Spec.hs
- plutus-tx/test/Plugin/Functions/unfoldings/applicationFunction.plc.golden
The real `$` has a scary levity-polymorphic type that we balk at. This
one is "boring" function application, which should work fine.
AFAIK, the only things that will go wrong if you use this instead of the
normal `$` are:
- Code that works with unlifted values (not much of that in what we're
writing).
- Code that uses `$` with `runST`, given that there's a special case for
that baked into GHC!
Fixes #1432. Also FYI @brunjlar who I know wanted this in the past.
> plutus-tx: add a version of $ that we can handle

- plutus-tutorial/doc/plutus-tx.adoc
- plutus-tx/compiler/Language/PlutusTx/Lift.hs
- plutus-tx/src/Language/PlutusTx.hs
- plutus-tx/test/Lift/Spec.hs
- plutus-tx/test/Plugin/Primitives/Spec.hs
- plutus-use-cases/src/Language/PlutusTx/Coordination/Contracts/CrowdFunding.hs
- plutus-use-cases/src/Language/PlutusTx/Coordination/Contracts/MultiSigStateMachine.hs
- plutus-wallet-api/ledger/Ledger/Scripts.hs
- plutus-wallet-api/ledger/Ledger/Typed/Tx.hs
- plutus-wallet-api/src/Wallet/Typed/StateMachine.hs
In practice the "unsafe" variants were the ones that everyone used
anyway, and having the prefix made it look more dangerous than it
actually is.
Fixes #1430.
> plutus-tx: rename some functions

- web-common/src/Editor.purs
The vertical line at column 80. Fixes #1440.
> Playground: Reemoving the editor's print marker.

- README.adoc
Adds a `mount` option to the docker command in README.adoc to avoid access permission problem (thanks to David Smith).
> Minor correction to docker instructions in README

- plutus-playground-client/src/Chain/Types.purs
- plutus-playground-client/src/Chain/View.purs
FocusAddress was something I'd planned in prototyping the new frontend
visualisation. But it ended up not being as useful as I'd thought.
Fixes #1451.
> Frontend: Removing an obsolete constructor.

- plutus-book/doc/auction/english.adoc
- plutus-book/doc/non-fungible/nonfungible8.adoc
- plutus-contract/src/Language/Plutus/Contract/Wallet.hs
- plutus-emulator/src/Wallet/Emulator/Types.hs
- plutus-use-cases/src/Language/PlutusTx/Coordination/Contracts/Future.hs
- plutus-use-cases/src/Language/PlutusTx/Coordination/Contracts/Vesting.hs
- plutus-wallet-api/ledger/Ledger/Tx.hs
- plutus-wallet-api/src/Wallet/API.hs
- plutus-wallet-api/src/Wallet/Generators.hs
This improvement gives user an easy way to write contract code where
the value spent is specified in several iterations, giving more control
over the inputs used by the wallet (for example, to cover fees).
We tried to cover a couple of use cases (mostly used for covering
fees):
1) If we have a set of inputs specified, when we add a fee, we would
like to make it easy to choose to cover fees from the remaining change,
or to use new inputs to cover fees.
2) Make it easy to automate spending behaviors across all contract
code where, for example, for each spending of funds, you need to
add some extra book-keeping transactions.
3) In general, if we have a transaction where some inputs have already
been specified, we need to provide a way to spend more without
using the previously added inputs. …
> Improve the API for payment selection.

- plutus-contract/doc/contract-api.adoc
- plutus-contract/plutus-contract.cabal
- plutus-contract/src/Language/Plutus/Contract.hs
- plutus-contract/src/Language/Plutus/Contract/Effects/UtxoAt.hs
- plutus-contract/src/Language/Plutus/Contract/Trace.hs
- plutus-emulator/src/Wallet/Emulator/Types.hs
- plutus-use-cases/src/Language/PlutusTx/Coordination/Contracts/CrowdFunding.hs
- plutus-wallet-api/ledger/Ledger/Tx.hs
* Add the `UtxoAt` effect with
`utxoAt :: HasUtxoAt s => Address -> Contract s AddressMap`, allowing
contracts to query the UTXO set through the node client.
* Note that this also changes the way `WalletAPI` is implemented in the
emulator: Wallets now keep track of the entire UTXO set, not just the
subset of unspent outputs at the adddresses they are interested in. So
the behaviour of `WalletAPI` in this regard is now that of a node
client.
Implements #1468
> contract: Add UtxoAt effect

- plutus-contract/doc/contract-api.adoc
- plutus-contract/src/Language/Plutus/Contract/Effects/WriteTx.hs
- plutus-contract/src/Language/Plutus/Contract/Trace.hs
- plutus-contract/src/Language/Plutus/Contract/Wallet.hs
- plutus-emulator/src/Wallet/Emulator/Types.hs
- plutus-playground-lib/src/Playground/Contract.hs
- plutus-use-cases/src/Language/PlutusTx/Coordination/Contracts/CrowdFunding.hs
* `writeTx` now returns the ID of the final transaction that was submitted, or the `WalletAPI` error if balancing / signing failed.
> contract: WriteTx returns txID

- default.nix
Because without this it swallows an error on OSX.
> Pinning the version of node that the updateClientDeps script uses.

- plutus-contract/src/Language/Plutus/Contract.hs
- plutus-contract/src/Language/Plutus/Contract/Request.hs
- plutus-contract/src/Language/Plutus/Contract/Resumable.hs
- plutus-contract/src/Language/Plutus/Contract/Schema.hs
- plutus-contract/src/Language/Plutus/Contract/Servant.hs
- plutus-contract/src/Language/Plutus/Contract/Test.hs
- plutus-contract/src/Language/Plutus/Contract/Trace.hs
- plutus-contract/test/Spec/Contract.hs
- plutus-contract/test/Spec/State.hs
* Add a `CError` constructor to deal with errors that happen during
contract execution
> contract: Add error handling

- plutus-playground-server/test/Playground/Rollup/renderCrowdfunding.txt
- plutus-playground-server/test/Playground/Rollup/renderVestFunds.txt
- plutus-tx/README.md
- plutus-tx/compiler/Language/PlutusTx/Compiler/Expr.hs
- plutus-tx/compiler/Language/PlutusTx/Compiler/Type.hs
- plutus-tx/plutus-tx.cabal
- plutus-tx/test/Plugin/Data/Spec.hs
- plutus-tx/test/Plugin/Data/monomorphic/strictPattern.plc.golden
- plutus-tx/test/Plugin/Errors/Spec.hs
- plutus-tx/test/Plugin/Errors/caseInt.plc.golden
- plutus-use-cases/test/Spec/crowdfunding.pir
- plutus-use-cases/test/Spec/multisigStateMachine.pir
- plutus-use-cases/test/Spec/vesting.pir
Improve the errors seen in https://github.com/input-output-hk/plutus/issues/1495 (I can't actually fix the issues directly, I don't think), and handle the odd case expressions introduced by bang patterns.
> plutus-tx: improve some errors and handle an odd case

- extended-utxo-spec/extended-utxo-specification.tex
This replaces validator and redeemer scripts with `Data` objects, getting rid of `Sealed` in the process.  I need to give it another pass before merging, but I hope it's approximately correct.  It says that `PendingTx` is translated into `Data` for validation, which is a bit premature, but we can change that back if need be.  
It has some todo notes which need to be hidden before merging.
> Starting to remove Sealed from the EUTXO spec

- deployment/terraform/marlowe-symbolic-lambda.tf
- deployment/terraform/variables.tf
This is a temporary solution that requires the terraform user to have the lambda package on their local filesystem. In a separate PR we will change this so it can be done from the nixops machine and will also be part of the continuous delivery server.
> make lambda deployable to any environment

- plutus-contract/test/Spec/Contract.hs
- plutus-playground-server/test/Playground/Rollup/renderCrowdfunding.txt
- plutus-playground-server/test/Playground/Rollup/renderVestFunds.txt
- plutus-use-cases/bench/Bench.hs
- plutus-wallet-api/ledger/Ledger/Index.hs
- plutus-wallet-api/ledger/Ledger/Scripts.hs
- plutus-wallet-api/ledger/Ledger/Scripts.hs-boot
- plutus-wallet-api/ledger/Ledger/Typed/Scripts.hs
- plutus-wallet-api/ledger/Ledger/Validation.hs
- plutus-wallet-api/ledger/Ledger/Validation.hs-boot
Fixes #1481.
Thanks to the existing wrappers and so on, this is a pleasantly small PR.
The main question is: should we do this? I think so, mainly because it makes the specification simpler. Now the *only* thing that the validating node needs to be able to do is pass `Data` to a script. If we make `Data` a builtin type then we can actually specify how to write a validating process entirely independently of Haskell (you still need the PLC typechecker/evaluator, obviously), which seems pretty good.
> ledger: pass PendingTx as Data

- deployment/terraform/marlowe-symbolic-lambda.tf
It seems that if you set the version then you need to manually go to the AWS console and redeploy the API. Otherwise you get 500 errors caused by some weird issue with the lambda permissions.
> setting version on api gateway causes issues

- plutus-contract/src/Language/Plutus/Contract.hs
- plutus-use-cases/plutus-use-cases.cabal
- plutus-use-cases/src/Language/PlutusTx/Coordination/Contracts/CrowdFunding.hs
- plutus-use-cases/src/Language/PlutusTx/Coordination/Contracts/Escrow.hs
- plutus-use-cases/test/Spec.hs
- plutus-use-cases/test/Spec/Escrow.hs
- plutus-wallet-api/ledger/Ledger/Interval.hs
- plutus-wallet-api/ledger/Ledger/Scripts.hs
- plutus-wallet-api/ledger/Ledger/TxId.hs
* Adds an escrow contract that can be used not just on its own but also
as part of the setup of another contract (collecting the initial
contributions from the parties involved)
* The contract works like the crowdfunding one in that the contributions
can be made in parallel
> use-cases: Add escrow contract

- extended-utxo-spec/extended-utxo-specification.tex
Looking through the EUTXO spec there were a few things that stood out:
- The use of `Map`s is still a bit tricky. Using finitely-supported functions a lot of the complexity goes away, especially in the ledger rules.
- Intervals were represented differently than they are in the real implementation.
- The representation of transactions with multi-currency had two fields for values, one for the native currency and one for custom currencies. This would make sense, but isn't what we're actually doing.
I have some more changes that I'd like to make, but these are the big ones.
Unfortunately Kenneth is on holiday, so he'll have to review this when he gets back. I'd like to merge it soon because Polina is going to be referring to it.
> EUXO spec: finitely-supported functions, intervals, and multi-currency

- extended-utxo-spec/extended-utxo-specification.tex
Based on https://github.com/input-output-hk/plutus/pull/1514. I'm not done yet, but this was already starting to get out of hand, and I wanted somewhere to refer to.
Ongoing work on the spec. It's difficult to break up into "features", so this is a bit of a mess. Should be lightly reviewable commit-by-commit (obviously start after the previous PR finishes, or just wait until it's merged), then I recommend just looking at the rendered new version.
Highlights:
- Fixed a few bugs in the validation rules.
- More explicit about a few things.
- Moved more notes out of the main text.
- Rearranged figures, so we have a single one for the non-ledger-specific types; with the ledger-specific ones per-section.
- Generally more consistency about macro usage.
> EUTXO spec: more work

- extended-utxo-spec/extended-utxo-specification.tex
Non-negativity of outputs is ensured with an additional validation rule.
This matches what the implementation and the Cardano spec do, so I think
we have to do it.
> EUTXO spec: allow negative values in the representation

- plutus-core-interpreter/bench/Bench.hs
- plutus-core-interpreter/src/Language/PlutusCore/Interpreter/CekMachine.hs
- plutus-core-interpreter/test/CekMachine.hs
- plutus-core-interpreter/test/DynamicBuiltins/Common.hs
- plutus-core-interpreter/weigh/Bench.hs
- plutus-exe/src/Main.hs
- plutus-tx/src/Language/PlutusTx/Evaluation.hs
- plutus-tx/test/TH/Spec.hs
- plutus-use-cases/bench/Bench.hs
- plutus-wallet-api/ledger/Ledger/Scripts.hs
These should certainly fail validation.
Arguably, the validating node should just be catching all kinds of
exceptions and treating them as failures. I don't think this is right:
the exceptions we get here are *non-transient* errors determined by the
program we've been given, rather than e.g. ambient machine conditions.
So these really do indicate that the script is bad, whereas other
exceptions may not.
As mentioned in https://github.com/input-output-hk/plutus/issues/1524, this is more relevant if we start erasing things.
> ledger: handle machine exceptions

- default.nix
This means you can't invoke it directly with `$(nix-build ...)`, which I
like to do.
Seems to be an unrelated change that snuck in with the PS upgrade.
> Don't use writeScriptBin for stylish script

- plutus-tx/plutus-tx.cabal
- plutus-tx/src/Language/PlutusTx/Eq.hs
- plutus-tx/test/StdLib/Spec.hs
* adds a missing case for the `List` constructor
* Also changes the pattern matches to ensure that a warning is produced when/if a new constructor is added to `Data`
> plutus-tx: Add missing case to Eq @Data

- plutus-contract/doc/contract-api.adoc
- plutus-contract/src/Language/Plutus/Contract.hs
- plutus-contract/src/Language/Plutus/Contract/App.hs
- plutus-contract/src/Language/Plutus/Contract/Effects/AwaitSlot.hs
- plutus-contract/src/Language/Plutus/Contract/Effects/ExposeEndpoint.hs
- plutus-contract/src/Language/Plutus/Contract/Effects/UtxoAt.hs
- plutus-contract/src/Language/Plutus/Contract/Effects/WatchAddress.hs
- plutus-contract/src/Language/Plutus/Contract/Effects/WriteTx.hs
- plutus-contract/src/Language/Plutus/Contract/Request.hs
- plutus-contract/src/Language/Plutus/Contract/Servant.hs
- plutus-contract/src/Language/Plutus/Contract/Test.hs
- plutus-contract/src/Language/Plutus/Contract/Trace.hs
- plutus-contract/test/Spec/Contract.hs
- plutus-contract/test/Spec/State.hs
- plutus-use-cases/exe/crowdfunding/Main.hs
- plutus-use-cases/exe/game/Main.hs
- plutus-use-cases/src/Language/PlutusTx/Coordination/Contracts/CrowdFunding.hs
- plutus-use-cases/src/Language/PlutusTx/Coordination/Contracts/Currency.hs
- plutus-use-cases/src/Language/PlutusTx/Coordination/Contracts/Escrow.hs
- plutus-use-cases/src/Language/PlutusTx/Coordination/Contracts/Game.hs
- plutus-use-cases/src/Language/PlutusTx/Coordination/Contracts/PubKey.hs
- plutus-use-cases/test/Spec/Crowdfunding.hs
- plutus-use-cases/test/Spec/Currency.hs
- plutus-use-cases/test/Spec/PubKey.hs
This lets users pick what they want to put here, which is important
since it's supposed to be a carrier for user errors too. The old version
handled this by turning everything into `Text`, which is also non-ideal.
Really, we should do this with more types and an approach like the
various `As*Error` classes used in the compiler. But this is a lot more
machinery for something we're barely using yet, so for now I've stuck to
abusing `IsString`.
> plutus-contract: generalize the error type

- language-plutus-core/generate-evaluation-test/Main.hs
- language-plutus-core/generators/Language/PlutusCore/Generators/Internal/Entity.hs
- language-plutus-core/generators/Language/PlutusCore/Generators/Internal/TypeEvalCheck.hs
- language-plutus-core/generators/Language/PlutusCore/Generators/Internal/Utils.hs
- language-plutus-core/generators/Language/PlutusCore/Generators/Test.hs
- language-plutus-core/language-plutus-core.cabal
- language-plutus-core/test/Evaluation/Constant/Success.hs
- plutus-exe/src/Main.hs
`plc example -a` was trying really hard to produce something that doesn't evaluate to `Failure`, but we have a test that always contains division by zero...
This PR allows `plc example` to generate a term that evaluates to `Failure`.
> [Bug] [PlutusExe] Fixed looping 'plc example -a'

- plutus-contract/src/Language/Plutus/Contract/App.hs
- plutus-contract/src/Language/Plutus/Contract/Request.hs
- plutus-contract/src/Language/Plutus/Contract/Test.hs
- plutus-contract/src/Language/Plutus/Contract/Trace.hs
- plutus-contract/test/Spec/Contract.hs
- plutus-emulator/src/Wallet/Emulator/Types.hs
- plutus-use-cases/src/Language/PlutusTx/Coordination/Contracts/CrowdFunding.hs
- plutus-use-cases/src/Language/PlutusTx/Coordination/Contracts/Game.hs
- plutus-use-cases/test/Spec/Game.hs
- plutus-use-cases/test/Spec/GameStateMachine.hs
- plutus-use-cases/test/Spec/MultiSig.hs
- plutus-use-cases/test/Spec/MultiSigStateMachine.hs
- plutus-use-cases/test/Spec/Rollup.hs
This is pretty grim, but I don't have a nicer solution.
We have a pervasive pair of `m` and `e` type arguments, representing the
base monad that the contract runs in and the error type. However, when
we run a trace, `m` has to do double duty as the emulator monad. This
means that we end up with two conflicting `MonadError` instances:
- One for the user's error type.
- One for the assertion errors that the emulator can throw.
What to do? This PR takes the route we're already using elsewhere, and
weakens the `MonadError` constraint from the emulator to only require
that `AssertionError` be injectable into the main error type.
The main downside of this is that the error type is now ambiguous if
it's unconstrained, which is a massive pain and requires type
annotations at the use site. But I …
> emulator: require only that assertions be injectable into the error type

- metatheory/Check.lagda.md
- metatheory/Main.lagda
- metatheory/TestDetailed.hs
- metatheory/TestSimple.hs
`IfIntegers`, `ApplyAdd1` and `ApplyAdd2` are disabled. In the process of creating this pull request I found that `plc-agda` _sometimes_ fails on them:
```
$ plc example -s ApplyAdd1 | plc-agda typecheck --stdin
(con integer)
$ plc example -s ApplyAdd1 | plc-agda typecheck --stdin
builtinError
```
Note: `plc example` generates slightly different examples each time.
> typechecking tests `plc` vs `plc-agda`.

- marlowe-playground-client/src/Marlowe/Blockly.purs
- marlowe-playground-client/src/Marlowe/Gen.purs
- marlowe-playground-client/src/Marlowe/Parser.purs
- marlowe-playground-client/src/Marlowe/Semantics.purs
- marlowe-playground-client/src/MonadApp.purs
- marlowe-playground-client/src/Simulation.purs
- marlowe-playground-client/src/Types.purs
I am being temporarily re-assigned so I want to get this PR through as it deals with what should be most of the machinery required. After this it should just be a matter of front-end work.
Overall the idea will be to display a list of holes with their type which you can expand to give options for the constructors. You can then click on a constructor which will replace the hole in the editor. E.g. `?contract1` would appear in a card on the left, clicking on it would give options for `Close`, `Pay`, `If`, `When` and `Let`, each with some documentation. If you then click on `Let` then the hole will be replaced with `(Let ?valueId1 ?value1 ?contract1)` or something similar.
> machinery to get a map of all holes from parser

- plutus-contract/test/Spec/Contract.hs
- plutus-use-cases/bench/Bench.hs
- plutus-use-cases/test/Spec/renderCrowdfunding.txt
- plutus-use-cases/test/Spec/renderGuess.txt
- plutus-wallet-api/ledger/Ledger/Scripts.hs
- plutus-wallet-api/ledger/Ledger/Typed/Scripts.hs
This finally makes the type of validators on-chain independent of our
datatype encoding scheme, since they can now return anything and must
signal failure via an error.
I haven't changed the type in the EUTXO spec, because that specifies the
type of the *interface* to validation, which can wrap up the error
handling and actually return a bool.
As a side effect, this removes the only use of the Plutus Tx plugin in
`plutus-wallet-api` (see https://github.com/input-output-hk/plutus/pull/1557
for why this is desirable).
> ledger: move application of 'check' into 'wrapValidator'

- plutus-contract/src/Language/Plutus/Contract/Trace.hs
- plutus-use-cases/test/Spec/Crowdfunding.hs
- plutus-use-cases/test/Spec/crowdfundingTestOutput.txt
- plutus-wallet-api/ledger/Ledger/Scripts.hs
- plutus-wallet-api/ledger/Ledger/Tx.hs
* `addTxEvents` used to add multiple events to the logs of all wallets, with every new transaction. It now only adds events the wallets that are actually interested in them. As a result, there are fewer events in the log and the log is much more informative.
* Also improves the rendering of transactions
> contracts: Better test output

- plutus-contract/src/Language/Plutus/Contract/Trace.hs
- plutus-contract/test/Spec/Contract.hs
* It makes sense to have this as a separate `Trace` action since transferring funds is a function of the wallet, not of the contracts
> contracts: Add `payToWallet` action

- marlowe-symbolic/src/Language/Marlowe/Analysis/FSSemantics.hs
Add a restriction to symbolic execution mechanism that forces initial slot number of counter-example traces to be greater or equal to zero.
> Restrict symbolic execution to non-negative initial slot numbers

- plutus-use-cases/plutus-use-cases.cabal
- plutus-use-cases/src/Language/PlutusTx/Coordination/Contracts/CrowdFunding.hs
- plutus-use-cases/test/Spec/crowdfundingTestOutput.txt
* Add contributor's public key to required signatures
(This causes a WalletAPIError if the contributor's key
is different from the that of the wallet that submits it)
* Use a proper datatype instead of a tuple for the contribution
> usecases: Crowdfunding tweaks

- plutus-contract/src/Language/Plutus/Contract/Test.hs
- plutus-contract/src/Language/Plutus/Contract/Trace.hs
- plutus-use-cases/test/Spec/Rollup.hs
* Cache the handlers that a contract has registered until a new event is added to the contract's trace
* This has a slight impact on the tests (122s down to 112s on my machine) but the primary target is the playground where we call `handleBlockchainEvents` much more frequently than we do in the tests
> contracts: Don't compute the handlers of a contract over and over again

- deployment/README.md
- deployment/terraform/variables.tf
- marlowe-playground-client/src/Marlowe/Parser.purs
- marlowe-symbolic/marlowe-symbolic.cabal
- marlowe-symbolic/src/App.hs
- marlowe/src/Language/Marlowe/Pretty.hs
- marlowe/src/Language/Marlowe/Semantics.hs
Extend pretty printing to include `TransactionInput` and `TransactionWarning` and modify symbolic execution result to use pretty-printing.
> Fix serialisation of symbolic execution result

- language-plutus-core/prelude/PlutusPrelude.hs
- language-plutus-core/src/Language/PlutusCore.hs
- language-plutus-core/src/Language/PlutusCore/Analysis/Definitions.hs
- language-plutus-core/src/Language/PlutusCore/CBOR.hs
- language-plutus-core/src/Language/PlutusCore/Check/Normal.hs
- language-plutus-core/src/Language/PlutusCore/Check/Uniques.hs
- language-plutus-core/src/Language/PlutusCore/Check/Value.hs
- language-plutus-core/src/Language/PlutusCore/DeBruijn.hs
- language-plutus-core/src/Language/PlutusCore/Error.hs
- language-plutus-core/src/Language/PlutusCore/Lexer/Type.hs
- language-plutus-core/src/Language/PlutusCore/MkPlc.hs
- language-plutus-core/src/Language/PlutusCore/Name.hs
- language-plutus-core/src/Language/PlutusCore/Pretty.hs
- language-plutus-core/src/Language/PlutusCore/Pretty/Plc.hs
- language-plutus-core/src/Language/PlutusCore/Quote.hs
- language-plutus-core/src/Language/PlutusCore/Size.hs
- language-plutus-core/src/Language/PlutusCore/Subst.hs
- language-plutus-core/src/Language/PlutusCore/Type.hs
- language-plutus-core/test/Check/Spec.hs
- language-plutus-core/test/Spec.hs
- plutus-tx/compiler/Language/PlutusTx/Compiler/Error.hs
This
1. makes export lists always indented by 4 spaces. It's diff-friendly, copy-paste-friendly, module-name-changing-friendly and to me it's also eyes-friendly. Also aligns data type declarations in the same way.
2. renames annotations everywhere to `ann`. They were called `a`, `x`, `l`, `pos` and some other names I think. I believe `ann` is more appropriate. I don't like `a`, because sometimes you have some polymorphic functions that deal with annotated things and I want `a` to be reserved for polymorphism
3. renames `NormalizationError` to `NormCheckError`, because the original name never made any sense
4. removes functions needed for handling sizes in Plutus Core
5. splits too long lines into shorter ones
> [PLC] [Refac] Changed some indentation, renamed annotation variables

- marlowe-playground-client/src/Halogen/Blockly.purs
- marlowe-playground-client/src/MainFrame.purs
- marlowe-playground-client/src/Marlowe/Blockly.purs
- marlowe-playground-client/src/Marlowe/Gen.purs
- marlowe-playground-client/src/Marlowe/Holes.purs
- marlowe-playground-client/src/Marlowe/Parser.purs
- marlowe-playground-client/src/Marlowe/Semantics.purs
- marlowe-playground-client/src/MonadApp.purs
- marlowe-playground-client/src/Simulation.purs
- marlowe-playground-client/src/Text/Parsing/Parser/Basic.purs
- marlowe-playground-client/src/Types.purs
- marlowe-playground-client/static/main.scss
- marlowe-playground-client/test/Marlowe/BlocklyTests.purs
- marlowe-playground-client/test/Marlowe/ContractTests.purs
- marlowe-playground-client/test/Marlowe/ParserTests.purs
- web-common/src/Bootstrap.purs
- web-common/src/Bootstrap/Extra.purs
Deployed to https://david.marlowe.iohkdev.io/ go to the Simulation tab and enter `?contract` in the editor. You can play from there.
Styling and UX suggestions welcome.
As part of this I had to remove parametrized marlowe types. In the end it was possibly impossible to do what I wanted and even if it was possible the complexity cost had started to outweigh the cost of having duplicate types.
> Fill in Marlowe holes from dropdown

- nix/purescript.nix
We were copying in some dependencies that could easily be symlinked.
This is prompted by a discussion with @michaelpj on PR #1625.
> Minor PS build improvement.

- marlowe-playground-client/spago.dhall
- marlowe-playground-client/src/MainFrame.purs
- marlowe-playground-client/src/MonadApp.purs
- marlowe-playground-client/src/Types.purs
- plutus-playground-client/spago.dhall
- plutus-playground-client/src/MainFrame.purs
- plutus-playground-client/src/Types.purs
- plutus-playground-client/src/View.purs
- plutus-playground-client/test/MainFrameTests.purs
- web-common/.gitignore
- web-common/packages.dhall
- web-common/spago.dhall
- web-common/src/Editor.purs
- web-common/src/Gists.purs
- web-common/src/Halogen/HTML/Extra.purs
Both frontend projects depend on web-common, which in turn depends on
some code from that project. If that sounds confusing or bad, it's
because it is, and this commit removes most of that complexity.
This address most - but not all - of #1077.
> Frontend: Removing the circular dependencies from web-common.

- plutus-book/plutus-book.cabal
As discussed on the mailing list.
- This is a maintenance headache for various reasons.
- The examples will largely need to be rewritten to use the new contract
API anyway.
- We're not publishing the master version of this anywhere.
With that in mind, we've decided to stop compiling and testing the
examples for now.
> book: disable

- .gitignore
- shell.nix
Apparently this trips up lorri: https://github.com/target/lorri#lorri-reevaluates-more-than-expected
Also ignore `.envrc` - this is going to depend on what people want to do locally.
> Import default.nix rather than ./.

- cabal.project
- metatheory/plc-agda.cabal
With `metatheory` listed as a package in `cabal.project`
```
$ cabal v2-install language-plutus-core
```
gives this error message:
```
...
cabal: Error: Could not find module: MAlonzo.Code.Main with any suffix:
["gc","chs","hsc","x","y","ly","cpphs","hs","lhs","hsig","lhsig"]. If the
module is autogenerated it should be added to 'autogen-modules'.
```
The modules `MAlonzo.*` are autogenerated. I tried moving them from `other-modules` to `autogen-modules` in `metatheory/plc-agda.cabal` as suggested by the error message. It seems to work for me.
> marking `MAlonzo.*` as `autogen-modules`; restoring`metatheory` to `cabal.project`

- plutus-contract/src/Language/Plutus/Contract/Effects/AwaitSlot.hs
- plutus-contract/src/Language/Plutus/Contract/Effects/ExposeEndpoint.hs
- plutus-contract/src/Language/Plutus/Contract/Effects/WriteTx.hs
- plutus-contract/src/Language/Plutus/Contract/Test.hs
- plutus-contract/src/Language/Plutus/Contract/Tx.hs
- plutus-contract/src/Language/Plutus/Contract/Wallet.hs
- plutus-emulator/src/Wallet/Emulator/Types.hs
- plutus-emulator/src/Wallet/Rollup/Render.hs
- plutus-use-cases/test/Spec/contractError.txt
- plutus-use-cases/test/Spec/crowdfundingTestOutput.txt
- plutus-use-cases/test/Spec/renderCrowdfunding.txt
- plutus-use-cases/test/Spec/renderGuess.txt
- plutus-use-cases/test/Spec/renderVesting.txt
- plutus-wallet-api/ledger/Data/Text/Prettyprint/Doc/Extras.hs
- plutus-wallet-api/ledger/Ledger/Ada.hs
- plutus-wallet-api/ledger/Ledger/Address.hs
- plutus-wallet-api/ledger/Ledger/Crypto.hs
- plutus-wallet-api/ledger/Ledger/Scripts.hs
- plutus-wallet-api/ledger/Ledger/TxId.hs
- plutus-wallet-api/ledger/Ledger/Value.hs
- plutus-wallet-api/ledger/LedgerBytes.hs
* Adds an `instance Pretty (Tagged a b)` and uses it to derive `Pretty` instances for the various hashes that we have
* One effect of this PR is that the prefix `5f582` disappears from a number of hashes in the pretty-printed .txt files. Presumably this is an artefact of the serialisation and not of the hash itself. 
Also, there seem to be two different approaches to pretty-printing things that are wrapped in newtypes (say `newtype A = A b`)
1. Include the name of the newtype in the Pretty instance of `A`
2. Derive `Pretty A` via `b` and include the name of `A` only in `Pretty` instances of types that contain an `A`. The main use for this is in `Wallet.Rollup.Render` where the names of the newtypes and their values are aligned vertically
I decided to go with (2) in all the `Pretty` …
> wallet-api/contract: Pretty print hashes

- plutus-playground-lib/src/Playground/Contract.hs
- plutus-playground-lib/src/Playground/Interpreter/Util.hs
- plutus-playground-lib/src/Playground/Types.hs
- plutus-playground-server/test/Playground/UsecasesSpec.hs
We were getting JSON decoding errors when the frontend sent a
`payToWallet_` call. This fixes it by handling more like a every other
contract schema call. (It still needs a bit of special handling, but not
nearly as much.)
> Playground: Fixing a bug with PayToWallet.

- default.nix
This makes it easy to ensure we're using the same version as the
project.
> Making our code-formatting tools available from devTools.

- plutus-wallet-api/ledger/Ledger/Address.hs
- plutus-wallet-api/ledger/Ledger/Scripts.hs
- plutus-wallet-api/ledger/Ledger/TxId.hs
- plutus-wallet-api/ledger/Ledger/Value.hs
psbridge assumes that all JSON instances for newtypes will be derived
from `anyclass`, so if they go to the frontend, they must be.
(This isn't really psbridge's fault. It's weird that Aeson has
different representations for different deriving strategies. I guess
psbridge has to pick one.)
> Correcting some of our JSON instances to work correctly with purescript-bridge.

- plutus-contract/src/Language/Plutus/Contract/Typed/Tx.hs
- plutus-use-cases/src/Language/PlutusTx/Coordination/Contracts/MultiSigStateMachine.hs
- plutus-use-cases/test/Spec/MultiSigStateMachine.hs
* Use the new contracts API in `MultiSigStateMachine`
* It now gets the current state of the contract from the chain (an improvement over the old version), but doing this is still a bit awkward
* Tests and error handling are also better now
* I tried to use the state machine & typed transaction libs where possible but I think what we really need is a `TypedUnbalancedTx`
> contracts: Update MultiSigStateMachine

- plutus-emulator/src/Wallet/Emulator/Types.hs
- plutus-emulator/test/Spec.hs
- plutus-tutorial/doctest/Main.hs
- plutus-tutorial/plutus-tutorial.cabal
- plutus-wallet-api/src/Wallet/API.hs
They're unused, and a pain to support.
I've just turned off the tutorial module that uses them - it needs to be rewritten with the new API anyway.
> wallet-api: delete event handlers

- language-plutus-core/common/PlcTestUtils.hs
- language-plutus-core/generators/Language/PlutusCore/Generators/Internal/TypeEvalCheck.hs
- language-plutus-core/generators/Language/PlutusCore/Generators/Test.hs
- language-plutus-core/test/Evaluation/CkMachine.hs
- plutus-core-interpreter/src/Language/PlutusCore/Interpreter/LMachine.hs
- plutus-core-interpreter/test/CekMachine.hs
- plutus-core-interpreter/test/LMachine.hs
@reactormonk stumbled upon a UX bug where `hedgehog` won't print an exception that comes from the CEK machine. I spent a couple of hours and was unable to understand why (it seems to print exceptions coming from the CK machine just well), so I just made errors explicit.
> [PLC] [Test] Explicit errors in 'TypeEvalCheck' tests

- plutus-contract/plutus-contract.cabal
- plutus-contract/src/Language/Plutus/Contract/StateMachine.hs
- plutus-contract/src/Language/Plutus/Contract/Tx.hs
- plutus-contract/src/Language/Plutus/Contract/Wallet.hs
- plutus-use-cases/src/Language/PlutusTx/Coordination/Contracts/GameStateMachine.hs
- plutus-use-cases/src/Language/PlutusTx/Coordination/Contracts/MultiSigStateMachine.hs
- plutus-use-cases/test/Spec/GameStateMachine.hs
- plutus-use-cases/test/Spec/MultiSigStateMachine.hs
- plutus-use-cases/test/Spec/gameStateMachine.pir
- plutus-wallet-api/ledger/Ledger/Typed/Tx.hs
- plutus-wallet-api/src/Language/PlutusTx/StateMachine.hs
- plutus-wallet-api/src/Wallet/Typed/StateMachine.hs
* Adds the `Language.Plutus.Contract.StateMachine` module, implementing
the client-side bits of the typed state machine in the new contract API
* Based on
https://github.com/michaelpj/plutus/commit/045e20770be415f3ebe86ce0df912782273371d8
* I was able to merge mkStep/runStep and mkHalt/runHalt
- There is a slight annoyance, namely that the we have to check
the value allocation and throw an error if a non-zero value is
allocated to the contract in the final state
* This also adds a `valueMoved` field to the `UnbalancedTx` type
- One more step towards the constraints approach
> contracts: State machine client code

- marlowe-playground-client/src/Marlowe/Semantics.purs
- marlowe-symbolic/src/Language/Marlowe/Analysis/FSSemantics.hs
- marlowe/src/Language/Marlowe/Semantics.hs
- plutus-emulator/test/Spec.hs
- plutus-tx/src/Language/PlutusTx/AssocMap.hs
Currently, Marlowe semantics is only checking whether a contract has been modified to decide whether a transaction is useless. This adds the condition that accounts have to be empty too, in case for some reason a contract consists only of `Close` but has accounts with money on them (this should not happen in practice, but it is more consistent this way).
> Fix UselessTransaction check

- cabal.project
I don't think these flags needed to be there:
- Optimization level 2 is the default anyway.
- The backjumps thing seems to not be needed, and is better in a
`cabal.project.local` anyway.
- The program options and allow-newer don't seem to be needed.
> Tidy cabal.project

- plutus-contract/src/Language/Plutus/Contract/StateMachine.hs
- plutus-contract/src/Language/Plutus/Contract/Trace.hs
- plutus-use-cases/bench/Bench.hs
- plutus-use-cases/plutus-use-cases.cabal
- plutus-use-cases/src/Language/PlutusTx/Coordination/Contracts/Escrow.hs
- plutus-use-cases/src/Language/PlutusTx/Coordination/Contracts/Future.hs
- plutus-use-cases/src/Language/PlutusTx/Coordination/Contracts/GameStateMachine.hs
- plutus-use-cases/src/Language/PlutusTx/Coordination/Contracts/MultiSigStateMachine.hs
- plutus-use-cases/src/Language/PlutusTx/Coordination/Contracts/PubKey.hs
- plutus-use-cases/src/Language/PlutusTx/Coordination/Contracts/TokenAccount.hs
- plutus-use-cases/test/Spec/Escrow.hs
- plutus-use-cases/test/Spec/Future.hs
- plutus-use-cases/test/Spec/contractError.txt
- plutus-use-cases/test/Spec/future.pir
- plutus-wallet-api/ledger/Ledger/Scripts.hs
- plutus-wallet-api/ledger/Ledger/Typed/Scripts.hs
* Use the state machine client lib. in the futures contract
* We want to avoid computing the actual validator
validator script of the contract too often. The approach is similar to what
was done in the `MultiSigStateMachine` contract: Re-use the
contract's `ScriptInstance` as much as possible. This is
achieved by sharing the script instance value instead of computing it
from scratch, and by checkpointing it after it has been created.
* Test times are now down from ~30s to 5-8s - still not perfect but
tolerable IMO.
> usecases: Future state machine client

- plutus-contract/src/Language/Plutus/Contract/Tx.hs
- plutus-contract/src/Language/Plutus/Contract/Wallet.hs
- plutus-contract/test/Spec/Contract.hs
- plutus-playground-lib/src/Playground/Contract.hs
- plutus-playground-server/usecases/Crowdfunding.hs
- plutus-playground-server/usecases/Vesting.hs
- plutus-use-cases/src/Language/PlutusTx/Coordination/Contracts/Crowdfunding.hs
- plutus-use-cases/src/Language/PlutusTx/Coordination/Contracts/Currency.hs
- plutus-use-cases/src/Language/PlutusTx/Coordination/Contracts/Escrow.hs
- plutus-use-cases/src/Language/PlutusTx/Coordination/Contracts/Future.hs
- plutus-use-cases/src/Language/PlutusTx/Coordination/Contracts/MultiSig.hs
- plutus-use-cases/src/Language/PlutusTx/Coordination/Contracts/TokenAccount.hs
- plutus-use-cases/src/Language/PlutusTx/Coordination/Contracts/Vesting.hs
- plutus-use-cases/test/Spec/PubKey.hs
This is what I did initially when working on #1753 before I realised I was going in the wrong direction. (we can't actually use `UnbalancedTx` in on-chain code because it includes validator, redeemer & data values in full, not just hashed). So this PR just makes the syntax a bit nicer by removing the need for `lens`. 
It does add new instances of our prelude's semigroup and monoid classes, which goes against the principle of using those classes in on-chain code only. So, feel free to reject this if you feel strongly about it.
> contracts: Better interface for UnbalancedTx

- web-common/src/Editor.purs
It's annoying to click on an error, jump there, and not be able to
edit straight away. This fixes this by making a jump to a cursor
position also grab the focus.
> Frontend: Scrolling to a particular line should also take focus.

- plutus-tx/compiler/Language/PlutusTx/Compiler/Expr.hs
- plutus-tx/test/Plugin/Errors/Spec.hs
- plutus-tx/test/Plugin/Errors/literalCaseBs.plc.golden
- plutus-tx/test/Plugin/Errors/literalCaseInt.plc.golden
- plutus-tx/test/Plugin/Errors/literalCaseOther.plc.golden
Fixes #1737 (more-or-less).
This is annoying, for the reasons described in the issue. Nonetheless,
we can still give better errors for the special cases of Integer and
ByteString, since we can recognize the inlined versions.
> plutus-tx: try and give better errors for uses of == arising from literal patterns

- language-plutus-core/stdlib/Language/PlutusCore/StdLib/Data/Function.hs
- language-plutus-core/stdlib/Language/PlutusCore/StdLib/Everything.hs
- language-plutus-core/test/Evaluation/Golden.hs
- plutus-ir/src/Language/PlutusIR/Compiler/Let.hs
- plutus-ir/src/Language/PlutusIR/Compiler/Recursion.hs
- plutus-ir/src/Language/PlutusIR/Compiler/Types.hs
- plutus-ir/test/recursion/even3.golden
- plutus-ir/test/recursion/even3Eval.golden
- plutus-ir/test/recursion/mutuallyRecursiveValues.golden
- plutus-tx/test/Plugin/Data/recursive/sameEmptyRose.plc.golden
- plutus-tx/test/Plugin/Data/recursive/sameEmptyRoseEval.plc.golden
- plutus-tx/test/Plugin/Functions/recursive/even3.plc.golden
- plutus-tx/test/Plugin/Functions/recursive/even4.plc.golden
- plutus-tx/test/TH/all.plc.golden
- plutus-use-cases/test/Spec/Future.hs
- plutus-use-cases/test/Spec/TokenAccount.hs
- plutus-use-cases/test/Spec/crowdfundingTestOutput.txt
- plutus-use-cases/test/Spec/renderCrowdfunding.txt
- plutus-use-cases/test/Spec/renderGuess.txt
- plutus-use-cases/test/Spec/renderVesting.txt
Fixes #1657.
These can be quite big, and otherwise we were making one per recursive
function. We still have one per arity of recursive function, but it
seems to save us ~10% on program size, which is nice.
The `language-plutus-core` changes are pretty minimal: `getMutualFixOf`
lets us provide the fixpoint function ourselves (or - a variable
reference to one), and `fixN` also provides the type, which we need for
creating variable bindings.
I think we want to use `DefT` some more in the PIR compilation pipeline,
particularly for sharing all the units in `NonStrict`, but I've kept it
simple for now.
> plutus-ir: share fixpoint combinator

- language-plutus-core/src/Language/PlutusCore/Constant/Typed.hs
This deletes an incorrect (thanks @reactormonk) and seemingly not used instance.
> [PLC] [Builtins] Deleted a broken 'Alternative' instance of 'ReflectT'

- lib.nix
- pkgs/default.nix
- stack.yaml
We were on 1.4.2.0. The error messages were hugely improved in 1.4.3.0,
so I want at least that version. (And while I'm here, I might as well go
to 1.4.6.0., which is the latest minor version.)
> Bumping our Aeson version.

- marlowe-symbolic/src/Language/Marlowe/Analysis/FSSemantics.hs
See issue #1782.
Deployed in https://pablo.marlowe.iohkdev.io/
> Reduce number of max inputs per transaction to 1 in Marlowe symbolic

- plutus-contract-tasty/src/Language/Plutus/Contract/Test.hs
- plutus-contract/src/Language/Plutus/Contract/Resumable.hs
- plutus-contract/src/Language/Plutus/Contract/Servant.hs
- plutus-contract/src/Language/Plutus/Contract/Trace.hs
- plutus-contract/test/Spec/State.hs
- plutus-use-cases/src/Language/PlutusTx/Coordination/Contracts/Future.hs
- plutus-use-cases/test/Spec/Future.hs
- plutus-use-cases/test/Spec/TokenAccount.hs
Fixes #1730
* Add a quick-and-dirty way to get the result of a contract: `evalTrace`
* Use `evalTrace` in tests to compute the hashes
* Clean up some of the return types in `Language.Plutus.Contract.Resumable`
> use-cases: Remove hard-coded hashes from tests

- marlowe-playground-server/app/Main.hs
- plutus-playground-server/app/Main.hs
`plutus-playground-server` and `marlowe-playground-server` now show
usage and help if you enter an incorrect command.
> Improving error messages when you call one of the servers incorrectly.

- plutus-ir/src/Language/PlutusIR/Compiler/Let.hs
- plutus-ir/test/Spec.hs
- plutus-ir/test/lets/letDep
- plutus-ir/test/lets/letDep.golden
- plutus-ir/test/recursion/even3.golden
This allows PlutusIR's Let non-rec bindings  to be scoped in a linear order fashion.
This partially resolves the feature #1683 .
Example:
```
let b1 = rhs1
b2 = rhs2  (b1 is visible in rhs2)
```
> Changed PIR compiler to compile lets in their order of definition.

- marlowe/src/Language/Marlowe/Client.hs
- plutus-emulator/src/Wallet/Emulator/Wallet.hs
- plutus-wallet-api/src/Wallet/API.hs
- plutus-wallet-api/src/Wallet/Typed/API.hs
This gives a bit more clarity on which parts rely on the wallet, and
which actually need a node.
> Splitting the WalletAPI class up into WalletAPI and NodeAPI.

- plutus-contract/src/Language/Plutus/Contract/Trace.hs
- plutus-emulator/src/Wallet/Emulator/Chain.hs
- plutus-emulator/src/Wallet/Emulator/Types.hs
- plutus-wallet-api/ledger/Ledger/Blockchain.hs
- plutus-wallet-api/src/Wallet/Generators.hs
* To get the current slot we previously simply counted the number of blocks in the blockchain. This is bad because (a) querying for the current slot should be done in constant time and (b) it assumes that there is exactly one block per slot
* (a) hasn't mattered so far because our tests usually don't go above 20 blocks, but it could become quite annoying in the SCB. And it has been bugging me for a while.
* This PR fixes (a) and makes it easier to fix (b) in the future
> emulator: Add slot number field to chain state

- plutus-scb/src/Cardano/Node/API.hs
- plutus-scb/src/Cardano/Node/Client.hs
- plutus-scb/src/Cardano/Node/MockServer.hs
* Add  a `utxo-at` route to get the unspent outputs at an address
> mock node server: Add 'utxo-at' route

- language-plutus-core/stdlib/Language/PlutusCore/StdLib/Data/Function.hs
- language-plutus-core/stdlib/Language/PlutusCore/StdLib/Everything.hs
- language-plutus-core/stdlib/Language/PlutusCore/StdLib/Meta/Data/Tuple.hs
- language-plutus-core/test/Evaluation/Golden.hs
- plutus-ir/src/Language/PlutusIR/Compiler/Definitions.hs
- plutus-ir/src/Language/PlutusIR/Compiler/Let.hs
- plutus-ir/src/Language/PlutusIR/Compiler/Recursion.hs
- plutus-ir/src/Language/PlutusIR/Compiler/Types.hs
- plutus-ir/test/Spec.hs
- plutus-ir/test/recursion/even3.golden
- plutus-ir/test/recursion/even3Eval.golden
- plutus-ir/test/recursion/mutuallyRecursiveValues.golden
- plutus-ir/test/recursion/stupidZero
- plutus-ir/test/recursion/stupidZero.golden
- plutus-tx-plugin/test/Plugin/Data/recursive/sameEmptyRose.plc.golden
- plutus-tx-plugin/test/Plugin/Data/recursive/sameEmptyRoseEval.plc.golden
- plutus-tx-plugin/test/Plugin/Functions/recursive/even3.plc.golden
- plutus-tx-plugin/test/Plugin/Functions/recursive/even4.plc.golden
- plutus-tx-plugin/test/TH/all.plc.golden
- plutus-use-cases/test/Spec/crowdfundingTestOutput.txt
- plutus-use-cases/test/Spec/renderCrowdfunding.txt
- plutus-use-cases/test/Spec/renderGuess.txt
- plutus-use-cases/test/Spec/renderVesting.txt
Fixes #1774, and also I shared `fixBy` since it's used by all `fixN`s.
The first change saves us a few hundred AST nodes for our standard programs, for a modest win. The second one has no effect, since shockingly we have *no* uses of mutually recursive functions in our example usecases. All the recursive functions are self-recursive!
> plutus-ir: use fix1, share fixBy

- plutus-contract/src/Language/Plutus/Contract/StateMachine.hs
One of the things that are problematic in Ethereum is that when you submit a transaction, you can't know the state of the contract at the point in time when your transaction will be processed. In Plutus, on the other hand, you construct the full transaction before submitting it, so if something has changed in the meantime, your transaction will simply be rejected. That's very good!
However, I noticed that the state machine mechanism provided in the Plutus libraries partially gives away this advantage: Even though the wallet has the full information when it constructs the transaction for a transition step, it does not (easily) allow to not proceed (depending on the state it finds).
I suggest to provide an extended version of `Language.Plutus.Contract.StateMachine.runStep`, …
> added runGuardedStep

- plutus-emulator/src/Wallet/Emulator/ChainIndex.hs
- plutus-playground-client/src/Chain.purs
- plutus-scb/app/Main.hs
- plutus-scb/plutus-scb.cabal
- plutus-scb/plutus-scb.yaml.sample
- plutus-scb/src/Cardano/ChainIndex/API.hs
- plutus-scb/src/Cardano/ChainIndex/Server.hs
- plutus-scb/src/Cardano/ChainIndex/Types.hs
- plutus-scb/src/Cardano/Node/API.hs
- plutus-scb/src/Cardano/Node/Client.hs
- plutus-scb/src/Cardano/Node/Follower.hs
- plutus-scb/src/Cardano/Node/Mock.hs
- plutus-scb/src/Cardano/Node/RandomTx.hs
- plutus-scb/src/Cardano/Node/Server.hs
- plutus-scb/src/Cardano/Node/Types.hs
- plutus-scb/src/Plutus/SCB/Types.hs
* Add a chain index that keeps track of unspent outputs and the transactions that produced them (so that we can get data values, etc. from them)
* Add a stateful chain follower protocol to the mock node, so that we can query for the most recent blocks only and don't need to transmit the entire blockchain every time
> scb: Add a chain index & node follower protocol

- plutus-core-spec/figures/TermReduction.tex
- plutus-core-spec/plutus-core-specification.tex
This fixes a problem in the reduction rules pointed out by @jmchapman:  `(error B)` does not progress, so we had no way to reduce `f{(error B)}`.
> Fix problem in reduction rules due to lack of progress for 'error'

- extended-utxo-spec/Makefile
- extended-utxo-spec/extended-utxo-specification.tex
@omelkonian pointed out that we need a rule to make sure that data values match their hashes.  This is in the EUTXO paper, but was missing here.  This commit amends the EUTXO-1 and EUTXO-2 validity rules to add that.
> Add missing rule about data script hashes

- papers/eutxo/eutxo.bib
- papers/eutxo/eutxo.tex
- papers/eutxo/formal-model.tex
- papers/eutxo/formal-verification.tex
- papers/eutxo/informal-eutxo.tex
- papers/eutxo/intro.tex
- papers/eutxo/related-work.tex
This updates the EUTXO paper to use "datum" instead of "data value" and "Context" instead of "TxInfo" (previously "PendingTx"), as decided in the Plutus call of 25th February 2020.  
Please don't merge this just yet: let's make sure that everyone approves first.
> Update terminology in EUTXO paper

- extended-utxo-spec/extended-utxo-specification.tex
Accidental 'r' at end of line while resolving conflicts in the previous version.
> Remove spurious character

- plutus-ir/plutus-ir.cabal
- plutus-ir/src/Language/PlutusIR.hs
- plutus-ir/src/Language/PlutusIR/Analysis/Dependencies.hs
- plutus-ir/src/Language/PlutusIR/Compiler/Datatype.hs
- plutus-ir/src/Language/PlutusIR/Compiler/Let.hs
- plutus-ir/src/Language/PlutusIR/Generators/AST.hs
- plutus-ir/src/Language/PlutusIR/MkPir.hs
- plutus-ir/src/Language/PlutusIR/Optimizer/DeadCode.hs
- plutus-ir/src/Language/PlutusIR/Parser.hs
- plutus-ir/src/Language/PlutusIR/Transform/Rename.hs
- plutus-tx-plugin/src/Language/PlutusTx/Compiler/Expr.hs
We do not allow empty lets in Plutus IR.
This PR restricts it at the typelevel.
However, GHC allows empty lets. The `mkLet` smart constructor makes sure that empty ghc lets are skipped.
> Change PIR.Let constructor to take a NonEmpty list

- marlowe-playground-client/src/Marlowe/Blockly.purs
- marlowe-playground-client/src/Marlowe/Semantics.purs
- Change labels of blockly to be more concise
- Inline "into account" in `Deposit` and `Pay`
- Make `Scale` more structured in primitive
- Add custom `Eq` instance to `Rational` in purescript
> Fixes to blockly

- marlowe-playground-client/src/Marlowe/Blockly.purs
Ada is meant to be a smart constructor, so having the Blockly block to be uppercase is inconsistent with it. This pull request changes the capitalisation of the label in the Blockly block to be lowercase like the smart constructor.
> Make Ada block lowercase

- marlowe-tutorial/doc/overview.adoc
- marlowe-tutorial/doc/potential-problems-with-contracts.adoc
Add taxonomy of potential problems when designing and using Marlowe contracts to the Marlowe tutorial.
> Add section to tutorial about potential problems

- GLOSSARY.adoc
- README.adoc
My goal with this is that it should be an authoritative source for the
words we use for things. So if we change something here we should also
rename it in the rest of the codebase.
With that in mind, we shouldn't merge this until we've resolved some of
the ongoing naming discussions.
> docs: add a glossary

- nix/haskell-extra.nix
- shell.nix
Until https://github.com/input-output-hk/haskell.nix/issues/422 is
fixed, we can't use the one we build with `haskell.nix`.
This does bump us to using `cabal-install` 3.0.0.0, but that seems to be
fine. As a bonus, this version makes `v2` commands the default!
> Take cabal-install from nixpkgs as dev cabal for now

- nix/haskell.nix
We had this set up before, this gets us back to that position so we keep ourselves warning-clean.
Sadly it's somewhat annoying, see https://github.com/input-output-hk/haskell.nix/issues/519.
> Set `-Werror` in the Nix build only

- nix/haskell.nix
I'm afraid I'm out of my depth here, this came up in the deployment server with:
```
building all machine configurations...
trace: [alex-plan-to-nix-pkgs] cabal new-configure --with-ghc=ghc --with-ghc-pkg=ghc-pkg
trace: [happy-plan-to-nix-pkgs] cabal new-configure --with-ghc=ghc --with-ghc-pkg=ghc-pkg
trace: [hscolour-plan-to-nix-pkgs] cabal new-configure --with-ghc=ghc --with-ghc-pkg=ghc-pkg
trace: To materialize, point `materialized` to a copy of /nix/store/q09xn5njhi80cb4fjb2x59i0vmgxlnzh-stack-to-nix-pkgs
building '/nix/store/17djfqkhw7rm69pc8xyya01pnd9my8vv-stack-to-nix-pkgs.drv'...
substituteStream(): WARNING: pattern '/nix/store/y28jgvngfk5v0b2mnzixnxbklywqsyla-plutus' doesn't match anything in file '/nix/store/q09xn5njhi80cb4fjb2x59i0vmgxlnzh-stack-to-nix-pkgs/pkgs.nix' …
```
> fix deployment

- ci.nix
- default.nix
- nix/haskell-extra.nix
- nix/haskell.nix
- release.nix
When set, this actually does the full IFD and checks that the hashes
we've given are correct. This is helpful, but we only set it on the CI
build to keep saving us time locally.
> Set checkMaterialization when building in the CI

- marlowe-playground-client/src/Marlowe/Holes.purs
- marlowe-playground-client/src/Marlowe/Linter.purs
- marlowe-playground-client/src/Marlowe/Semantics.purs
- marlowe-playground-client/webpack.config.js
Refine linting mechanism to include constant simplification suggestions, unreachable `Case` and `Contract` and to use a `State` monad and separate `Environment`.
> SCP-179 - Improvements to linting mechanism

- nix/haskell.nix
@michaelpj this has happened again, any idea how it is managing to get into master? 
This looks to be the PR that causes it this time https://github.com/input-output-hk/plutus/pull/1923 which looks like things will break any time a cabal file is changed?
> fix nix build

- ci.nix
- default.nix
- nix/sources.json
- nixpkgs.json
- release.nix
- Set `checkMaterialization` there too
- Support `supportedSystems`, which is handy (stole this from the `haskell.nix` `ci.nix` where I implemented it before)
> A few minor improvements to ci.nix

- marlowe-playground-client/src/HaskellEditor.purs
- marlowe-playground-client/src/MainFrame.purs
- marlowe-playground-client/src/MonadApp.purs
- marlowe-playground-client/src/Simulation.purs
- marlowe-playground-client/src/Simulation/BottomPanel.purs
- marlowe-playground-client/test/Marlowe/ContractTests.purs
Splitting this issue in an effort to keep PRs small.
- make bottom panel pop up when you click on one of the tabs
- rename incorrect heading in Haskell panel
- make help dialogue scroll into view when you click on a help ball
- tutorial link should open a new tab
> Scp 166 - part 1

- plutus-ledger/src/Ledger/Crypto.hs
- plutus-ledger/src/Ledger/TxId.hs
These types print as a garble of escape codes without it.
> Replacing some stock Show instances with `deriving via LedgerBytes` ones.

- marlowe-playground-client/src/MainFrame.purs
- marlowe-playground-client/src/MonadApp.purs
- marlowe-playground-client/src/Simulation.purs
- marlowe-playground-client/src/Simulation/BottomPanel.purs
- marlowe-playground-client/src/StaticData.purs
- marlowe-playground-client/static/css/main-tabs.css
- marlowe-playground-client/static/css/panels.css
* move input and transaction composer buttons to be after text
* reduce the size of the side bar
* add an empty contract example
* make non-clickable items in bottom panel not look like the clickable ones
* supportive message when there are no warnings and errors
* change Analysis Result: Failed to Analysis Result: Warnings Found
> Some improvements to the playground design

- plutus-ir/src/Language/PlutusIR/Parser.hs
This removes the Overflow error constructor from the PlutusIR parser.  I think that that was left over from when we had sizes (so that the parser could reject things like 321!1), so it's not needed now.  There's a similar thing in PlutusCore which I've removed in a separate PR for the  PLC parser.
> Remove obsolete Overflow error

- extended-utxo-spec/extended-utxo-specification.tex
This adds separate monetary policy scripts to the EUTXO document.  I based this on #1827 and the implementation, then looked at the version in multicurrency paper once I'd done that.  They look pretty similar, so that's reassuring.  I've used the version that allows redundant MPSs.
Two minor differences from the paper:
* The spec says `forgeScripts`, the paper says `MPScripts`.  The latter maybe sounds a bit more meaningful, so we might want to say that instead.
* I notice that I've allowed a set of MPSs, but the paper requires a finite set.  I reckon that this is just an implementation detail: the only reason you'd care is that computers are too feeble to run infinitely many scripts in a finite amount of time. Mathematically I think we're OK.
Also, no redeemers for MPSs.
If this looks OK …
> Add monetary policy scripts

- marlowe/src/Language/Marlowe/Client.hs
- plutus-emulator/src/Wallet/API.hs
- plutus-emulator/src/Wallet/Effects.hs
- plutus-emulator/src/Wallet/Emulator/Wallet.hs
- plutus-scb/app/Main.hs
- plutus-scb/src/Cardano/Wallet/API.hs
- plutus-scb/src/Cardano/Wallet/Client.hs
- plutus-scb/src/Cardano/Wallet/Mock.hs
- plutus-scb/src/Cardano/Wallet/Server.hs
- plutus-scb/test/Plutus/SCB/TestApp.hs
* There were two different handlers of the `WalletEffect` type
1. `Wallet.Emulator.Wallet.handleWallet`  delegates most of the work to the chain index & node client, using only the wallet's own private key as its state
2. `Cardano.Wallet.Mock.handleWallet` does not require a chain index but instead keeps its own internal index of the unspent outputs that it cares about.
* Both are valid behaviors, but (1) is simpler because it re-uses the chain index instead of implementing some of the index functionality on its own, so I decided to use `Wallet.Emulator.Wallet.handleWallet` in the SCB, instead of moving the SCB version to the emulator and using it.
* I also changed `Cardano.Wallet.API.API` to mirror the `WalletEffect` methods, just like it is done for the HTTP APIs of the other components …
> scb: Make wallet work more like emulator

- marlowe-playground-client/src/MainFrame.purs
- marlowe-playground-client/src/Simulation.purs
- marlowe-playground-client/static/css/github-input.css
- marlowe-playground-client/static/css/main.scss
- marlowe-playground-client/static/css/panel-mobile.css
- marlowe-playground-client/static/css/panels.css
* controls are now a bit smaller so whole gist id fits in
* loading/publishing controls have improved icons, they don't resize etc
* tooltip contains errors
* after an error, when you start typing in the input box the errors are removed
* controls now get hidden with the side panel on smaller screens
* made the side panel hide on a wider screen, it was unusable between 1025px and 1200px
> Improve github controls

- extended-utxo-spec/extended-utxo-specification.tex
Clarifies some issues relating to transaction IDs and removes spurious use of old <> notation for tx lookup.
> Clarify behaviour of lookupTx function and remove superseded <> notation

- marlowe-playground-client/grammar.ne
- marlowe-playground-client/src/Help.purs
- marlowe-playground-client/src/Marlowe/Blockly.purs
- marlowe-playground-client/src/Marlowe/Gen.purs
- marlowe-playground-client/src/Marlowe/Holes.purs
- marlowe-playground-client/src/Marlowe/Linter.purs
- marlowe-playground-client/src/Marlowe/Parser.purs
- marlowe-playground-client/test/Main.purs
- marlowe-playground-client/test/Marlowe/CompletionItemsTests.purs
This will make it possible to have holes in Blockly since its not possible to have null values (hence a hole) for strings and numbers.
Note that for linting to work correctly, Marlowe.Holes.Timeout records its position.
> Use default values instead of holes for strings and numbers

- README.adoc
The attribute names changed, so these were pointing to old versions.
> Fix hydra links in readme

- nix/haskell.nix
- plutus-scb/app/Main.hs
- plutus-scb/plutus-scb.cabal
- plutus-scb/src/Plutus/SCB/App.hs
- plutus-scb/src/Plutus/SCB/Command.hs
- plutus-scb/src/Plutus/SCB/Core.hs
- plutus-scb/src/Plutus/SCB/Effects/Contract.hs
- plutus-scb/src/Plutus/SCB/Events.hs
- plutus-scb/src/Plutus/SCB/Events/User.hs
- plutus-scb/src/Plutus/SCB/Query.hs
- plutus-scb/src/Plutus/SCB/Types.hs
- plutus-scb/test/Plutus/SCB/CoreSpec.hs
- plutus-scb/test/Plutus/SCB/Effects/ContractTest.hs
- plutus-scb/test/Plutus/SCB/Effects/MultiAgent.hs
- plutus-scb/test/Plutus/SCB/TestApp.hs
* Add a type parameter for the type of contract identifiers to the SCB
* In the actual application this is instantiated to `ContractExe`, ie. the
location of the executable in the file system.
* In the tests we can use a type like `data TestContracts = Game |
Currency` which is nicer than working with magic strings.
> scb: Add a type parameter for contracts

- nix/haskell.nix
The hash seems to have been wrong a previous commit.  Let's see if this fixes it.
> Update hash in nix/haskell.nix

- plutus-scb/app/Main.hs
Looks like a copy & paste error confused the "start webserver" and
"report TX history" commands.
> SCB: Bugfix for the command line parser.

- language-plutus-core/exe/Main.hs
- language-plutus-core/src/Language/PlutusCore/CBOR.hs
- language-plutus-core/test/Spec.hs
- plutus-ledger/src/Data/Aeson/Extras.hs
- plutus-ledger/src/Ledger/Scripts.hs
- plutus-use-cases/test/Spec/crowdfundingTestOutput.txt
- plutus-use-cases/test/Spec/renderCrowdfunding.txt
- plutus-use-cases/test/Spec/renderGuess.txt
- plutus-use-cases/test/Spec/renderVesting.txt
This updates the serialisation code so that unit annotations aren't included in CBOR.  See #1818 and https://jira.iohk.io/browse/SCP-391.  This replaces #1991.  See in particular the notes at the end of CBOR.hs.
@j-mueller : is there anywhere else that we have to worry about serialising Plutus Core? Anything that's not wrapped in a Script will be serialised inefficiently.
> SCP-391: Don't serialise unit annotations

- marlowe-playground-client/src/HaskellEditor.purs
- marlowe-playground-client/src/Simulation.purs
- marlowe-playground-client/src/Simulation/BottomPanel.purs
- marlowe-playground-client/static/css/main-tabs.css
- marlowe-playground-client/static/css/main.scss
- marlowe-playground-client/static/css/panel-mobile.css
- marlowe-playground-client/static/css/panels.css
- stop simulation tab icon moving
- move bottom panel minimize button to left so that it is visible when covered by right panel
- make width breakpoint earlier so that transaction composer doesn't get squashed
- hide gist buttons when right panel contracted
- make sure "to blockly" button not hidden when right panel contracted
- make bottom panel a bit bigger
> Various marlowe playground layout improvements

- marlowe-playground-client/src/Halogen/Classes.purs
- marlowe-playground-client/src/MonadApp.purs
- marlowe-playground-client/src/Simulation/BottomPanel.purs
- marlowe-playground-client/src/Types.purs
- marlowe-playground-client/static/css/table.css
* Moved "CurrentSlot" and "Expiration Block" to "Current State" tab to give more space
* Add transaction inputs to new "logs" tab
> Add simulation logs

- marlowe-playground-client/src/Marlowe/Linter.purs
- marlowe-playground-client/test/Marlowe/LintTests.purs
A choice with an empty list of options can never be satisfied, it is equivalent to Notify FalseObs, thus, it necessarily implies a part of the contract is unreachable and there should be a warning for it.
> SCP-350 - Add warning for empty choice list to linting

- plutus-scb/app/Main.hs
- plutus-scb/src/Cardano/ChainIndex/Server.hs
We have a constraint that the wallet needs to call startWatching on
the chain index before the chain index sees the first transaction.
I've address this by making the index not bother to fetch new blocks
when there are no watched addresses. Same effect, and feels like a
logical thing to do regardless.
> SCB: Fixing a problem with the chainindex startup sequence.

- nix/haskell.nix
- plutus-ledger/src/Ledger/Scripts.hs
- plutus-scb/src/Plutus/SCB/Arbitrary.hs
We can fix it to not use the plugin pretty easily, just export some
accepting validators from `Scripts`, which seems handy anyway.
> Fix haddock for plutus-scb

- CONTRIBUTING.adoc
- cabal.project
- default.nix
- lib.nix
- Pin the index state, this means we don't need a freeze file any more.
- Get the index state from the cabal file for our other stuff.
- Remove a rogue source dependency that was breaking things.
> Cabal improvements

- cabal.project
Typical, last minute comment change breaks things. Amusingly, none of our CI actually relies on cabal.project, apparently.
> Fix comment syntax

- marlowe/marlowe.cabal
- marlowe/src/Language/Marlowe.hs
- marlowe/src/Language/Marlowe/Pretty.hs
- marlowe/src/Language/Marlowe/Semantics.hs
- marlowe/test/Spec.hs
- marlowe/test/Spec/Marlowe/Common.hs
- marlowe/test/Spec/Marlowe/Marlowe.hs
- nix/stack.materialized/marlowe.nix
- Fix several `Show` instances
- Add Plutus Ratio `%` operator to `Language.Marlowe`
- Add QuickCheck test to ensure `Show` instances work
> SCP-264 - Ensure Show result can be used with ghc/ghci

- language-plutus-core/bench/Bench.hs
- nix/haskell.nix
- release.nix
Things not required by tests (e.g. benchmarks or exes) weren't required, so could get through being broken.
> Add all components to required job

- nix/stack.materialized/plutus-scb.nix
- plutus-scb/app/Main.hs
- plutus-scb/plutus-scb.cabal
- plutus-scb/src/Cardano/ChainIndex/Server.hs
- plutus-scb/src/Cardano/Node/Server.hs
- plutus-scb/src/Cardano/SigningProcess/Server.hs
- plutus-scb/src/Cardano/Wallet/Server.hs
- plutus-scb/src/Control/Concurrent/Availability.hs
- plutus-scb/src/Plutus/SCB/Webserver/Server.hs
There's a problem with the dependency graph of the test servers - we
need some to be available before others can start.  But just forking the
threads in the right order isn't enough to guarantee availability. The
threads start up practically instantaneously, so if one of the required
servers takes a little longer to get going, we get an intermittent
timing error.
What we really need is to start each server and have it tell us when
it's ready to serve requests, before we move on to starting the next.
This commit accomplishes that, by passing a semophore to the server
threads and having them flag up when they're available.
Note that there's no noticable performance difference to the user. This
really was a timing issue that came down to a matter of milliseconds.
> SCB: Fixing a startup timing issue for the 'all-servers' command.

- marlowe-playground-client/src/Marlowe/Semantics.purs
- marlowe-playground-client/src/Simulation.purs
- marlowe-playground-client/src/Simulation/BottomPanel.purs
- marlowe-playground-client/src/Simulation/State.purs
- Move payments to log tab.
- Change transaction interval to (slot, slot), instead of (slot, slot + 1).
- Fix bug in `above` function.
- Simplify way of storing pending inputs.
> SCP-659 - Move payments to Log tab

- nix/stack.materialized/plutus-scb.nix
- plutus-scb/app/PSGenerator.hs
- plutus-scb/atomic-swap-contract/Main.hs
- plutus-scb/plutus-scb.cabal
- plutus-scb/src/Plutus/SCB/Effects/ContractTest.hs
- plutus-scb/src/Plutus/SCB/Effects/ContractTest/AtomicSwap.hs
* Adds a simple atomic swap contract (based on `Language.PlutusTx.Coordination.Contracts.Escrow`) that demonstrates the atomic, decentralised exchange of on-chain assets
> PAB: Add 'AtomicSwap' contract for testing/demo purposes

- CONTRIBUTING.adoc
- marlowe-symbolic/lambda.nix
- nix/default.nix
- nix/haskell-extra.nix
- nix/haskell.nix
- nix/sources.json
- stack.yaml
They're only needed by Nix, better to keep them with the Nix configuration,
rather than in magic comments.
Also will make it easier to switch to using the cabal build later.
(Annoyingly needs a haskell.nix bump for the `sha256map` argument.)
> Use sha256map, move hashes out of stack.yaml

- plutus-contract/src/Language/Plutus/Contract.hs
- plutus-contract/src/Language/Plutus/Contract/Effects/ExposeEndpoint.hs
- plutus-scb/app/PSGenerator.hs
- plutus-scb/src/Plutus/SCB/Arbitrary.hs
- plutus-scb/src/Plutus/SCB/Core/ContractInstance.hs
- plutus-scb/src/Plutus/SCB/Events/Contract.hs
- plutus-scb/test/Plutus/SCB/Events/ContractSpec.hs
- plutus-use-cases/test/Spec/crowdfundingTestOutput.txt
* Add a field `aeMetadata :: Maybe JSON.Value` field to the `EndpointDescription` type
* This field can be used to pass arbitrary JSON values to the user when exposing an endpoint
I thought about adding a type variable for the metadata, but: (1) we already have enough type parameters, (2) we don't do anything with the metadata on the contract side, it exists only to carry information for the frontaned and (3) whatever value we put in there we will have to serialise to JSON anyway.
>  SCP-660: metadata for endpoints 

- plutus-contract/src/Control/Monad/Freer/Log.hs
- plutus-contract/src/Language/Plutus/Contract/Effects/WatchAddress.hs
- plutus-contract/src/Language/Plutus/Contract/Trace.hs
- plutus-contract/src/Language/Plutus/Contract/Trace/RequestHandler.hs
- plutus-contract/src/Language/Plutus/Contract/Wallet.hs
- plutus-scb/src/Cardano/Node/Types.hs
- plutus-scb/src/Plutus/SCB/Core/ContractInstance.hs
The code that uses `WalletEffects` to deal with contracts' requests was duplicated, this PR fixes it.
> SCP-787: Merge request handlers in PAB and emulator

- ci.nix
- nix/tests/purty.nix
- nix/tests/stylish-haskell.nix
- plutus-contract/src/Language/Plutus/Contract/Effects/WatchAddress.hs
- plutus-scb/src/Cardano/Node/Types.hs
I'm not really sure what was going on here: I think when these used to be checked by buildkite the main point of the hydra job was to build the diff as an output so people can apply it. I'm pretty sure we don't want this any more.
> Formatter tests shouldn't always succeed!

- plutus-scb/app/Main.hs
- plutus-scb/plutus-scb.yaml.sample
- plutus-scb/src/Plutus/SCB/Types.hs
To date, it's been something you enable or disable with a command line
flag, but I think you probably either always want it or never want it,
so putting in the config file makes more sense.
> SCB: Moving the EKG config into the YAML file.

- marlowe-playground-client/src/Marlowe/Linter.purs
- marlowe-playground-client/test/Marlowe/LintTests.purs
- Make deposit warnings specific to token type not only account
- Consider payments between accounts
- Add warnings for insufficient deposits when using constant values (or simplifiable values)
- Add tests
> SCP-266 - Add linting for PartialPay and PartialDeposit (with constants)

- .gitignore
- default.nix
- doc/conf.py
- doc/default.nix
- doc/exts/hs_domain.py
- doc/requirements.txt
- doc/tutorials/plutus-tx.rst
- nix/haddock-combine.nix
- nix/sources.json
- shell.nix
This uses https://github.com/michaelpj/sphinxcontrib-haddock to build intersphinx inventories for our Haddock and wire them all up in the build.
This means that we can do things like `:hs:hsobj:Language.PlutusTx.compile` and have it go to the corresponding Haddock, with an error if it can't find it. Some examples are in there already.
> Sphinx site: build with support for linking into Haddock

- marlowe-playground-client/src/Marlowe/Holes.purs
- marlowe-playground-client/src/Marlowe/Linter.purs
- marlowe-playground-client/src/Marlowe/Monaco.js
- marlowe-playground-client/src/Marlowe/Monaco.purs
- marlowe-playground-client/src/Marlowe/Monaco.ts
- marlowe-playground-client/src/Monaco.purs
- marlowe-playground-client/src/Simulation/BottomPanel.purs
Here we change the type-ahead so that it includes all constructors for a data type, not just the one that starts with what you typed.
It places the one you started typing at the top of the list of suggestions though and makes sure it is selected.
> SCP-730 - Improve monaco type-ahead

- marlowe-playground-client/src/Marlowe/Linter.purs
- marlowe-playground-client/src/Simulation/BottomPanel.purs
- marlowe-playground-client/test/Marlowe/LintTests.purs
Deployed in https://pablo.marlowe.iohkdev.io/
> SCP-845 - Add linting for undefined ChoiceValue usage

- marlowe-playground-client/grammar.ne
- marlowe-playground-client/src/Halogen/Blockly.purs
- marlowe-playground-client/src/Marlowe/Blockly.purs
- marlowe-playground-client/src/Marlowe/Gen.purs
- marlowe-playground-client/src/Marlowe/Holes.purs
- marlowe-playground-client/src/Marlowe/Linter.purs
- marlowe-playground-client/src/Marlowe/Parser.purs
- marlowe-playground-client/src/Monaco.purs
- marlowe-playground-client/src/Simulation.purs
- marlowe-playground-client/src/Simulation/Types.purs
- marlowe-playground-client/test/Marlowe/BlocklyTests.purs
- marlowe-playground-client/test/Marlowe/CompletionItemsTests.purs
This is part one of SCP-905, we need to get the start position and end position of all terms when parsing, this way we can use the monaco API to do replacements which requires the rang that you are replacing. Once this is merged we can do any sort of refactoring of Marlowe we want, such as removing dead code.
> Change Marlowe Term to include end position

- marlowe-playground-client/src/Marlowe/Semantics.purs
- marlowe/src/Language/Marlowe/Analysis/FSSemantics.hs
- marlowe/src/Language/Marlowe/Semantics.hs
- marlowe/test/OldAnalysis/FSSemantics.hs
- marlowe/test/Spec.hs
- marlowe/test/Spec/Marlowe/Marlowe.hs
Simplify implementation of Scale, and change it to `Round half away from zero`.
Also added detection for shadowed `Let` variables in new static analysis implementation.
> SCP-644 - Simplify Scale implementation

- ci.nix
- release.nix
- shell.nix
For some reason I had previously felt like it was unhygienic to build the shell expression in CI, but on reflection I think it's just a good idea, and the best way to ensure that the actual shell expression continues to build on all platforms.
> Build `shell.nix` in CI

- deployment/nixops/server.nix
Rather than broken link to the old `plutus-tutorial` attribute.
Also, the haddock goes alongside it instead of being deployed separately
now, might need to revisit later, but this should work for now.
Meant to fix this before, forgot. FYI @shmish111 , not sure how to test this so may just merge and see if it succeeds.
> Use Sphinx site in Plutus Playground doc

- cabal.project
- nix/dev.nix
- nix/haskell-extra.nix
- shell.nix
- The haskell.nix cabal now works, so that's nice.
- We can use the nice multiple-subdirs feature in cabal.project to cut
out a lot of repetition.
Note we get annoying warnings about extraneous version ranges due to
https://github.com/haskell/cabal/issues/5119.
(I noticed this issue was marked as fixed for 3.2, thought I'd try it, and lo and behold it works. Seems nice.)
> Bump dev cabal to 3.2 and use multiple subdirs feature

- language-plutus-core/exe/Main.hs
The `plc` command was just running with an empty set of dynamic builtins, meaning that it couldn't typecheck or run programs involving the standard dynamic builtins.  I noticed this yesterday when Nikos was asking about a related problem.  I'm sure I've added this at least once or twice before, but I think it's perhaps been accidentally reverted.
Anyway, this is just a small PR to add those builtins.  It turned out to be quite tricky to get the types to work, and I had to add a cal  to `runQuoteT` at one point.  I'm not sure whether or not this is safe...
> Add standard dynamic builtins to plc-exe

- language-plutus-core/exe/Main.hs
- language-plutus-core/language-plutus-core.cabal
- nix/stack.materialized/language-plutus-core.nix
This is a minor PR to add an option to make `plc` report the execution time of a program.  The issue is that I want to get some idea of the execution time of a PLC program without including the time taken by parsing or deserialisation: timing things on the command line, I was seeing large variations due to minor changes in formatting of the input program.
I'm using `rnf` to make sure the AST's been fully computed before starting to evaluate it. I'm not totally confident that this is the right way to do it, but I have been using this code in my recent CEK experiments and I haven't noticed anything unexpected happening.
(Including @reactormonk because he was asking about forcing evaluation recently on Slack so might know what's going on.)
> Add timing option to plc command

- marlowe-playground-client/src/HaskellEditor.purs
- marlowe-playground-client/static/css/panels.css
When you compile code successfully, it will be displayed with line numbers in a way that looks similar to the marlowe editor.
When you have a compile error it will be displayed in a `pre` as it was previously.
> make haskell result pretty

- marlowe-playground-client/grammar.ne
- marlowe-playground-client/package.json
- marlowe-playground-client/src/HaskellEditor.purs
- marlowe-playground-client/src/Marlowe/Holes.purs
- marlowe-playground-client/src/Marlowe/Parser.js
- marlowe-playground-client/src/Marlowe/Parser.purs
- marlowe-playground-client/yarn.lock
- marlowe-playground-client/yarn.nix
I used to have a fork of the nearley webpack plugin that enabled you to inject something into the generated javascript however I realised this is not necessary as I can simple call compiled purescript directly from the `ne` file.
> get rid of nearley hack

- cabal.project
See https://github.com/haskell/cabal/issues/7006 for details
To reproduce this issue in this repo:
```
nix-shell
cabal build lib:cardano-prelude
```
> Work around cabal issue 7006

- language-plutus-core/src/Language/PlutusCore/CBOR.hs
A small update to CBOR.hs.  See [Note: Don't use catamorphisms!] for an explanation.
> Remove catamorphisms from CBOR encoder (SCP-1033)

- marlowe-playground-client/src/HaskellEditor.purs
- marlowe-playground-client/src/MainFrame.purs
- marlowe-playground-client/src/Reachability.purs
- marlowe-playground-client/src/Simulation.purs
- marlowe-playground-client/src/Simulation/Types.purs
- marlowe-playground-client/src/Types.purs
part of an ongoing effort to get rid of halogen components for all purescript code, use components only for javascript things that need to be wrapped up. Functions like `toSimulation` can enable you to split the concerns in a very similar way without the 'component' needing to be stateful in itself.
> mp refactor - get rid of simulation component

- plutus-scb-client/src/MainFrame.purs
- plutus-scb-client/src/MonadApp.purs
- plutus-scb-client/test/MainFrameTests.purs
Similar to the other two frontends, we introduce `MonadApp` for all the
side-effecting calls, so we can replace them with mock implementations in a
test environment.
> SCB: Adding the scaffolding for better frontend tests.

- marlowe-playground-client/spago-packages.nix
- marlowe-playground-client/spago.dhall
- marlowe-playground-client/src/Main.purs
- marlowe-playground-client/src/MainFrame.purs
- marlowe-playground-client/src/Router.purs
- marlowe-playground-client/src/Types.purs
- marlowe-playground-client/yarn.nix
We now have URL routes `#/simulation`, `#/haskell`, `#/blockly` and `#/wallets` that direct to the various views. This means you can bookmark a page and lays the foundation for more complex routes in the future, such as short urls for a saved workspace etc.
> add URL routing to Marlowe Playground

- marlowe-playground-client/src/Marlowe/Semantics.purs
- marlowe-playground-client/src/Simulation.purs
- marlowe-playground-client/src/Simulation/BottomPanel.purs
- marlowe-playground-client/src/Simulation/State.purs
- marlowe-playground-client/src/Simulation/Types.purs
- marlowe-playground-client/src/Wallet.purs
- marlowe-playground-client/static/css/panels.css
- marlowe-playground-client/test/Marlowe/ContractTests.purs
* If a contract is inside a When that has a Notify and that Notify evaluates to true then an input button "Notify" should be displayed.
* If we pass over a timeout by progressing the slot number, an empty transaction should be submitted automatically
* It should not possible to submit a transaction that causes an error
Note that this is for the simulation tab only and the wallets simulation remains unchanged
Deployed to https://david.marlowe.iohkdev.io/#/simulation
> remove input composer in simulation

- marlowe-playground-client/src/Halogen/Blockly.purs
It turns out that it is no longer possible to get blockly to return an error because we have holes and blockly won't let you put bad values in. I don't think it's useful to a user to have any additional information because if something breaks it is a bug, not a user error however I have changed the error to be an 'unexpected' error and improved the message to include details of how to raise an issue on github.
> improve error message

- nix/sources.json
Our shell depended on *building* plutus-use-cases, which is not so good.
I fixed it in `haskell.nix`, this updates us to get the fix.
> Fix excess shell dependencies

- language-plutus-core/untyped-plutus-core-test/Evaluation/ApplyBuiltinName.hs
Semantic merge conflict between the UPLC PR and the CEK PR. Fairly sure this is the right thing (at least the tests pass).
> Fix untyped PLC tests

- plutus-contract/src/Language/Plutus/Contract/Trace/RequestHandler.hs
If we ask the chain index for transactions that were confirmed in the current slot, we always get an empty list, because the chain index only learns about those transactions at the beginning of the next slot.
> Fix an off-by-one error in the chain index

- plutus-contract/src/Language/Plutus/Contract/StateMachine.hs
- plutus-use-cases/src/Language/PlutusTx/Coordination/Contracts/PingPong.hs
- plutus-use-cases/test/Spec/PingPong.hs
Change `waitForUpdate` to return `Nothing` if the new state after the update is the final state. (Previously it would throw an error)
> SCP-1097: State machine client handles final state

- plutus-contract/src/Language/Plutus/Contract.hs
- plutus-contract/src/Language/Plutus/Contract/App.hs
- plutus-contract/src/Language/Plutus/Contract/Servant.hs
- plutus-contract/src/Language/Plutus/Contract/State.hs
- plutus-contract/src/Language/Plutus/Contract/Test.hs
- plutus-contract/src/Language/Plutus/Contract/Trace.hs
- plutus-contract/src/Language/Plutus/Contract/Types.hs
- plutus-scb/app/PSGenerator.hs
- plutus-scb/src/Plutus/SCB/ContractCLI.hs
- plutus-scb/src/Plutus/SCB/Effects/ContractTest.hs
- plutus-scb/src/Plutus/SCB/Events/Contract.hs
- plutus-use-cases/src/Language/PlutusTx/Coordination/Contracts/Crowdfunding.hs
- plutus-use-cases/test/Spec/crowdfundingTestOutput.txt
We can now use 'Control.Monad.Freer.Log' inside of contracts. The type
of log messages is 'Data.Aeson.Value', because all contract outputs are
serialised to JSON when they cross the process boundary anyway.
I also changed the `ResumableResult` type to include possible errors that happened during contract execution. So we went from
`Either e (ResumableResult i o a)` to `ResumableResult e i o a`, which is a bit nicer because it lets you look at the log outputs and the contract state even if there is an error.
> SCP-855: Add logging to contracts

- plutus-ledger/src/Ledger/Generators.hs
- plutus-ledger/src/Ledger/Value.hs
- plutus-ledger/test/Spec.hs
Most people would expect TokenName to be UTF-8 encoded. 
Allows to use Unicode for tokens! ₳₿
> SCP-944 Use UTF-8 for TokenName.

- nix/stack.materialized/playground-common.nix
- playground-common/playground-common.cabal
- playground-common/src/Playground/Interpreter/Util.hs
- plutus-contract/src/Language/Plutus/Contract/App.hs
- plutus-contract/src/Language/Plutus/Contract/Test.hs
- plutus-contract/src/Language/Plutus/Contract/Trace.hs
- plutus-contract/src/Wallet/Emulator/Types.hs
- plutus-use-cases/src/Language/PlutusTx/Coordination/Contracts/Crowdfunding.hs
- plutus-use-cases/src/Language/PlutusTx/Coordination/Contracts/Game.hs
- plutus-use-cases/test/Spec/Crowdfunding.hs
- plutus-use-cases/test/Spec/Future.hs
- plutus-use-cases/test/Spec/GameStateMachine.hs
- plutus-use-cases/test/Spec/MultiSigStateMachine.hs
- plutus-use-cases/test/Spec/Rollup.hs
- plutus-use-cases/test/Spec/Vesting.hs
* Replace 'MonadEmulator' and 'EmulatorAction' types with their
equivalents from `freer-simple`
* Get rid of a couple of constraints at call-sites
> plutus-contract: Scrap MonadEmulator MTL effects

- plutus-core/src/Language/PlutusCore/Constant/Apply.hs
- plutus-core/src/Language/PlutusCore/Evaluation/Machine/Cek.hs
- plutus-core/src/Language/PlutusCore/Evaluation/Machine/Ck.hs
- plutus-core/src/Language/PlutusCore/Evaluation/Machine/ExBudgeting.hs
- plutus-core/test/Evaluation/ApplyBuiltinName.hs
- plutus-core/untyped-plutus-core-test/Evaluation/ApplyBuiltinName.hs
- plutus-tx-plugin/test/TH/Spec.hs
- plutus-tx/src/Language/PlutusTx/Evaluation.hs
Now instead of having a hardcoded `ExBudgetCategory` we parameterize `SpendBudget` by an `exBudgetCategory` as per discussion in slack.
> [PLC] [Costing] Generalized 'ExBudgetCategory'

- default.nix
- deployment/README.md
- deployment/default.nix
- deployment/provider-path.patch
- deployment/terraform.nix
- deployment/terraform/gateway.tf
- deployment/terraform/loadbalancing.tf
- deployment/terraform/machines.tf
- deployment/terraform/main.tf
- deployment/terraform/marlowe-symbolic-lambda.tf
- deployment/terraform/marlowe.tf
- deployment/terraform/network.tf
- deployment/terraform/nixops.tf
- deployment/terraform/plutus.tf
- deployment/terraform/ssh_config.tf
- deployment/terraform/static.tf
- deployment/terraform/variables.tf
- deployment/terraform/webghc.tf
- marlowe-playground-client/src/Simulation.purs
- marlowe-playground-client/static/error.html
- shell.nix
This PR is part of the ongoing process of upgrading the infrastructure. In this PR we:
* upgrade terraform
* wrap up terraform deployment in scripts that are built with nix
* copy marlowe playground static files to S3
* serve the lambda and static files over api gateway
Currently none of the S3 stuff is used but it can be accessed, e.g. https://lambda-david.marlowe.iohkdev.io/#/simulation. Next we need to proxy the marlowe-playground-server and web-ghc through the api gateway so that everything can be accessed through API gateway. Once this is done we can change the frontend client to use the API gateway directly instead of the ALB.
> Move static files to S3

- plutus-scb/src/Plutus/SCB/Core/ContractInstance.hs
- plutus-scb/test/Plutus/SCB/CoreSpec.hs
* `processContractOutboxes` kept servicing the same requests for each
contract instance, instead of updating them. That way it would never
make any progress.
* As a result we can get rid of one call to `syncAll` in the tests
* I also ran it in interactive mode, and noticed a speedup in the
currency contract.
> SCP-1145: Fix a bug in process contract outboxes

- nix/stack.materialized/plutus-scb.nix
- plutus-scb/plutus-scb.cabal
- plutus-scb/src/Plutus/SCB/Swagger.hs
- plutus-scb/src/Plutus/SCB/Webserver/API.hs
- plutus-scb/src/Plutus/SCB/Webserver/Server.hs
Adding swagger to the webservers is a two part affair - figure out how to plumb it in, then add a gajillion instances of `Data.Swagger.ToSchema` everywhere. (Most of those instances can be derived with generics, but plenty cannot.) This is a classic "brainwork / legwork" split.
There was a discussion in last week's planning meeting as to whether this was worth the effort, given that the API is still changing and the team(s) that want us to support swagger won't actually need it for several months.
As a balance, I propose this change. It merges the plumbing I've already figured out, so the brainwork is kept. And we can save the legwork of adding instances for when we actually have a consumer.
> Plumbing in the Swagger API for the SCB server.

- plutus-contract/src/Control/Monad/Freer/Log.hs
I would like to use `handleLogTrace`, but its type signature too
restrictive. It claims to be limited to strings, but it will actually
work with anything `Pretty`.
> Generalising an unnecessarily specific type signature.

- marlowe-playground-client/spago-packages.nix
- marlowe-playground-client/spago.dhall
- marlowe-playground-client/src/Examples/JS/Contracts.purs
- marlowe-playground-client/src/Halogen/Monaco.purs
- marlowe-playground-client/src/Language/Javascript/Interpreter.js
- marlowe-playground-client/src/Language/Javascript/Interpreter.purs
- marlowe-playground-client/src/Language/Javascript/MarloweJS.ts
- marlowe-playground-client/src/MainFrame.purs
- marlowe-playground-client/src/Monaco.js
- marlowe-playground-client/src/StaticData.purs
- Modify JS evaluation process so that it uses Monaco editor's `TS -> JS` transpilation.
- Overload API to support `(string | number | bignumber.BigNumber)`, which I have called `SomeNumber`, and removes the need to use the `BigNumber` constructor for small numbers (or if using a string).
- Overload API to support `SomeNumber | Value` which I have called `EValue`, and removes the need to use the `constant` constructor.
- Add API types to JS import.
- Add type annotations to JS examples (now TS examples), to illustrate how to take advantage of TypeScript.
- Fix evaluation process so that it doesn't crash in the absence of the `/*  === Code above this comment  ...` comment.
- Fix some issues with transition from BigInt to BigNumber.
> SCP-1188 - Remove need for bigInt constructor and get TS to compile in JS tab

- nix/stack.materialized/plutus-core.nix
- plutus-core/plutus-core.cabal
- plutus-core/src/Language/PlutusCore/CBOR.hs
- plutus-core/src/Language/PlutusCore/Core/Type.hs
- plutus-core/src/Language/PlutusCore/DeBruijn.hs
- plutus-core/src/Language/PlutusCore/DeBruijn/Internal.hs
- plutus-core/test/Spec.hs
- plutus-core/untyped-plutus-core/Language/UntypedPlutusCore.hs
- plutus-core/untyped-plutus-core/Language/UntypedPlutusCore/Core.hs
- plutus-core/untyped-plutus-core/Language/UntypedPlutusCore/Core/Instance/CBOR.hs
- plutus-core/untyped-plutus-core/Language/UntypedPlutusCore/Core/Plated.hs
- plutus-core/untyped-plutus-core/Language/UntypedPlutusCore/Core/Type.hs
- plutus-core/untyped-plutus-core/Language/UntypedPlutusCore/DeBruijn.hs
- plutus-core/untyped-plutus-core/Language/UntypedPlutusCore/Subst.hs
- plutus-ledger/src/Ledger/Scripts.hs
- plutus-metatheory/src/Main.lagda
- plutus-metatheory/src/Raw.hs
- plutus-playground-server/usecases/Crowdfunding.hs
- plutus-tx-plugin/src/Language/PlutusTx/Plugin.hs
- plutus-use-cases/src/Language/PlutusTx/Coordination/Contracts/Crowdfunding.hs
- plutus-use-cases/test/Spec/crowdfundingTestOutput.txt
- plutus-use-cases/test/Spec/renderCrowdfunding.txt
- plutus-use-cases/test/Spec/renderGuess.txt
- plutus-use-cases/test/Spec/renderVesting.txt
Fixes SCP-616
This corresponds to using de-bruijn indices on-chain, since `Script`s
are our representation of "a PLC program in a transaction".
Note, this currently has an `error` in it. I'm trying to decide whether it's evil or whether it should be turned into a proper `throw` of some kind of "impossible" exception. It can only happen if the script does not typecheck, which shouldn't be possible at this stage.
> plutus-ledger: use de-bruijn indices for Scripts

- marlowe-playground-client/src/Marlowe/Semantics.purs
- marlowe/src/Language/Marlowe/Semantics.hs
Decoding the result of static analysis got values out of order for the `TransactionPartialPay` warning
> Fix order of elements in TransactionPartialPay JSON decoding

- nix/stack.materialized/plutus-core.nix
- plutus-core/bench/Bench.hs
- plutus-core/plutus-core.cabal
- plutus-core/src/Language/PlutusCore.hs
- plutus-core/src/Language/PlutusCore/Lexer.x
- plutus-core/src/Language/PlutusCore/Lexer/Type.hs
- plutus-core/src/Language/PlutusCore/Parser/Internal.hs
- plutus-core/test/Spec.hs
- plutus-core/untyped-plutus-core/Language/UntypedPlutusCore/Core/Type.hs
- plutus-core/untyped-plutus-core/Language/UntypedPlutusCore/Parser.y
- plutus-metatheory/src/Main.lagda
- Augment the TPLC lexer and share it: doesn't seem worth having another
lexer.
- Add a UPLC parser that's mostly a copy of the TPLC parser.
- Pull out some helper stuff from the TPLC parser to reduce the
duplication a bit.
- Kill some pointless extra functions we had lying around.
> plutus-core: add a UPLC parser

- plutus-ledger/src/Ledger/Typed/Scripts.hs
- plutus-ledger/src/Ledger/Typed/Scripts/Validators.hs
The forwarding policy should look at the transaction's *inputs*, not at its outputs, because the input scripts are the ones that get run when the tx is being validated.
> ledger: Fix a bug in the forwarding MPS

- plutus-core/plutus-ir-test/type-errors/nonSelfRecursive.golden
- plutus-core/plutus-ir-test/type-errors/wrongDataConstrReturnType.golden
- plutus-core/plutus-ir/Language/PlutusIR/Compiler.hs
- plutus-core/plutus-ir/Language/PlutusIR/Compiler/Types.hs
- plutus-core/plutus-ir/Language/PlutusIR/Error.hs
- plutus-core/plutus-ir/Language/PlutusIR/TypeCheck.hs
- plutus-core/plutus-ir/Language/PlutusIR/TypeCheck/Internal.hs
- plutus-core/src/Language/PlutusCore.hs
- plutus-core/src/Language/PlutusCore/TypeCheck/Internal.hs
- plutus-tx-plugin/src/Language/PlutusTx/Plugin.hs
This adresses the following:
1) Allows PIR programs to escape types at top-level only
2) By default, the escape types cannot be seen by the user; only that the PIR program is well-typed. Testing/debugging code can use Internal module
3) Added back the `G !- inTerm:: *` rule to run only inside nested lets (not top-level)
About the implementation:
- Used an extra Reader flag for `TypeCheckM` monad to be aware if the current input `Term` to be typechecked is at top-level vs nested position
- This flag is automatically set to top-level by the `runTypeCheckTerm` which runs the typechecker monad. So I assume that runTypecheckTerm and its callers (inferType,checkType,PIR.Compiler.compileTerm) are actually inputted **top-level PIR terms**, aka PIR programs. This flag is automatically set to …
> Pir tc escaping through a reader "mode"

- .gitignore
If you have a socket-type file in the source repo, the nix build will
choke on it with an error like:
```
error: file '.../node-server.sock' has an unsupported type
```
Webpack creates temporary socket files, so if you're doing frontend work
this is a huge pain.
> Filter unknown file types from the nix build.

- plutus-scb/src/Cardano/Metadata/Server.hs
- plutus-scb/src/Cardano/Metadata/Types.hs
- plutus-scb/src/Plutus/SCB/Webserver/Handler.hs
- plutus-scb/test/Cardano/Metadata/ServerSpec.hs
Writing up the spec made me realise we should be using `propertyNames`
instead of `properties` as the field name.
> SCB: Minor change the metadata batch query structure.

- deployment/default.nix
- shell.nix
If you don't have `pass` available, or pointing to the right password
store, the error was silently being ignored and terraform would deploy
with any information we get from pass set to the empty string.
This fixes that issue.
It's disappointing to see that the heart of the fix comes from realising
that in bash:
export FOO=$(command)
...will swallow an error, whereas:
FOO=$(command)
export FOO
...will throw it.
> Fixing a deployment bug when pass is not available.

- shell.nix
A long time ago, Nikos pointed out to me that running the tests inside
`nix-shell` was much slower than outside it. I don't notice since I'm
using `lorri`, but this is quite annoying. I never figured out what the
issue was, it didn't seem to be environments or anything.
Someone else recently noticed something similar, and managed to  track it down
to a Nix bug where it sets the processor affinity wrong
(https://github.com/NixOS/nix/issues/3345). I didn't even know about
processor affinity! (Don't mutate global state while forking processes,
kids.)
The fix is a `shellHook` to put it back to something sensible, which
indeed gives us the behaviour we expect.
> Fix nix-shell CPU affinity

- default.nix
- pab-demo-scripts.nix
- plutus-scb/app/Main.hs
* `start-all-servers.sh` runs the PAB with all servers incl. mock node
* `start-second-scb.sh` runs a second instance of the PAB that connects
to the same mock node as the first one (so they see the same blockchain)
* Both instances have a couple of demo contracts pre-installed.
Fixes SCP-871
> PAB: Shell scripts for a demo environment

- nix/stack.materialized/plutus-metatheory.nix
- plutus-metatheory/.gitignore
- plutus-metatheory/Setup.hs
- plutus-metatheory/plutus-metatheory.cabal
Two tricks:
- Run Agda in both a post-configure hook and a pre-build hook, so it
runs before Haddock and also before any build. This won't waste work due
to Agda being good at not redoing work.
- Put the Agda sources in `extra-source-files`, which apparently makes
Cabal rebuild if they change!
> Re-run Agda properly in plutus-metatheory

- marlowe-playground-client/src/Simulation.purs
- marlowe-playground-client/src/Simulation/BottomPanel.purs
- marlowe-playground-client/src/Simulation/State.purs
- marlowe-playground-client/src/Simulation/Types.purs
- marlowe-playground-client/src/Wallet.purs
- marlowe-playground-client/static/css/panels.scss
- marlowe-playground-client/test/Marlowe/ContractTests.purs
Use start button to reduce initial contract when it doesn't start with a When.
It was impossible to just reduce the contract for a particular slot if it doesn't start with When or Close. We would need an option that allows you to reduce the contract without issuing any actions (empty transaction).
It can be exposed by trying to falsify the assertion in the following contract, which seemed impossible to do in the simulator before this fix:
```
Let
"value"
SlotIntervalStart
(When
[Case
(Deposit
(Role "role")
(Role "role")
(Token "" "")
(AddValue
(UseValue "value")
SlotIntervalStart
)
)
(Assert
(ValueEQ
(AvailableMoney
(Role "role")
(Token "" "")
)
(Scale
(2%1)
(UseValue "value")
)
)
Close
)]
10 Close
)
```
> SCP-1245 - Cannot reduce contract when it doesn't start with When

- nix/stack.materialized/plutus-tx.nix
- plutus-tx/plutus-tx.cabal
- plutus-tx/src/Language/PlutusTx/Data.hs
- plutus-tx/test/Spec.hs
- plutus-use-cases/test/Spec/crowdfundingTestOutput.txt
- plutus-use-cases/test/Spec/renderCrowdfunding.txt
- plutus-use-cases/test/Spec/renderGuess.txt
- plutus-use-cases/test/Spec/renderVesting.txt
I added a roundtrip property test that fails on some kind of nested map (example below).
```
Data serialisation
should round-trip: FAIL (0.26s)
✗ should round-trip failed at test/Spec.hs:29:5
after 40 tests and 20 shrinks.
forAll0 =
Left (DeserialiseFailure 22 "expected integer")
forAll1 =
List
[ Constr
0
[ Map
[ ( I (-100000)
, Map
[ ( Map [ ( I (-100000) , Map [ ( I (-100000) , Constr 2 [] ) ] ) ]
, I (-100000)
)
]
)
]
]
]
This failure can be reproduced by running:
> recheck (Size 39) (Seed 18069878865127360370 1302055943076871483) should round-trip
Use '--hedgehog-replay "Size 39 Seed 18069878865127360370 1302055943076871483"' to reproduce.
```
> Serialise instance of Data is broken

- marlowe-playground-client/grammar.ne
- marlowe-playground-client/src/Marlowe/Gen.purs
- marlowe-playground-client/src/Marlowe/Semantics.purs
- Make public keys that do not conform with base16 a parsing error.
- Update generators to only generate valid base16.
- Change `Eq` and `Ord` instances to be case-insensitive.
- Change `Show` instance to use lower case.
> SCP-1211 - Show warning for non-hexit error in playground

- shell.nix
This enables the shellcheck pre-commit check of pre-commit-hooks.nix
The hook will be enabled on the first invocation of `shellHook` which
occurs either when entering a `nix-shell` or via `.envrc` in case
your integration is configured to evaluate shell hooks.
> Enable shellcheck pre-commit hook

- nix/dev.nix
- plutus-scb/src/Cardano/Metadata/API.hs
- plutus-scb/src/Cardano/Metadata/Client.hs
- plutus-scb/src/Cardano/Metadata/Server.hs
- plutus-scb/src/Cardano/Metadata/Types.hs
- plutus-scb/src/Plutus/SCB/Webserver/Handler.hs
- plutus-scb/test/Cardano/Metadata/ServerSpec.hs
- plutus-scb/test/Cardano/Metadata/TypesSpec.hs
- plutus-scb/test/Cardano/Metadata/query_response1.json
- plutus-scb/test/Cardano/Metadata/query_response2.json
This final metadata change essentially just wraps the existing batch
query in a result object (`QueryResult`) to comply to the JSON spec,
which says the top-level type _must_ be an object.
> Batch queries against the live metadata server.

- marlowe/test/contract.json
- nix/stack.materialized/plutus-ledger.nix
- plutus-ledger/plutus-ledger.cabal
- plutus-ledger/src/Ledger/Crypto.hs
- plutus-ledger/src/Ledger/Validation.hs
- plutus-ledger/test/Spec.hs
- plutus-use-cases/src/Language/PlutusTx/Coordination/Contracts/Crowdfunding.hs
- plutus-use-cases/test/Spec/crowdfundingTestOutput.txt
- plutus-use-cases/test/Spec/renderCrowdfunding.txt
- plutus-use-cases/test/Spec/renderGuess.txt
- plutus-use-cases/test/Spec/renderVesting.txt
* The sha2_256 functions works in principle, but the off-chain version of `pubKeyHash` used the wrong bytestring.
* `Ledger.Validation` now also exports `pubKeyHash`
> Fix pubKeyHash in off-chain code

- shell.nix
Work around https://github.com/cachix/pre-commit-hooks.nix/issues/76.
I think everyone has git anyway, and I don't think we're likely to have
issues due to different versions, so it's not a big deal if we don't
provide it in the shell.
> Remove git from shell

- shell.nix
Unfortunately the pre-commit invocations appear to ignore the exludes
specified in .ignore so this has to be fixed with the `excludes`
option of the hook config.
> Configure nixpkgs pre-commit hook excludes

- nix/stack.materialized/plutus-benchmark.nix
- plutus-benchmark/README.md
- plutus-benchmark/nofib/bench/BenchHaskell.hs
- plutus-benchmark/nofib/src/Plutus/Benchmark/Knights/ChessSetList.hs
- plutus-benchmark/nofib/src/Plutus/Benchmark/Prime.hs
- plutus-benchmark/nofib/src/Plutus/Benchmark/Queens.hs
- plutus-benchmark/plutus-benchmark.cabal
The `nofib-hs` benchmarks were in fact benchmarking the plutus-tx compilation times of the nofib examples, not the execution times.  I think this should fix it.  
Maybe we should keep the compliation time benchmarks, since it'd be cheap to do so.
> nofib-hs was benchmarking compilation times, not execution times

- marlowe-playground-client/src/Monaco.js
- marlowe-playground-client/src/Monaco.purs
- web-common/src/Data/Default.purs
- web-common/static/main.scss
* Playground: Bugfix for the editor's mode selector.
* Removing Monaco's default text.
* Extracting a PureScript Data.Default equivalent to its own file.
> A few frontend tweaks.

- nix/dev.nix
On OSX, clang++ is required, but may not be available. It is now.
> Fixing a dependncy problem with the OSX Marlowe build.

- marlowe/src/Language/Marlowe/Pretty.hs
Contracts with non-empty PK identifiers are interpreted as base16 strings, instead of passed directly to simulator.
This fixes the pretty printer to return the base16 representation instead.
> SCP-1171 - Fix Haskell to Marlowe conversion of PK hashes

- marlowe-playground-client/src/Simulation.purs
- marlowe-playground-client/src/Simulation/State.purs
- Unify choices with the same `ChoiceId` in the same option in the input composer
- Simplify choice bound lists by sorting and minimising the number of intervals
Deployed in: https://pablo.marlowe.iohkdev.io/
> SCP-1251 - Unify choices in Marlowe Playground simulation

- CONTRIBUTING.adoc
- default.nix
Quick patch to make sure everything is at least accessible from `default.nix` until we work out where we want to put things.
- Branch
- PR
> Expose pkgsLocal again

- plutus-contract/src/Language/Plutus/Contract.hs
- plutus-contract/src/Language/Plutus/Contract/Types.hs
For some reason we had things like `mapError` but not `handleError`. This PR fixes that.
> plutus-contract: Expose `handleError`

- ci.nix
- default.nix
This changes the the attribute set that the `dimension` function
receives such that everything doesn't get instantiated multiple times.
The fact that this is happening could actually been noticed through the
trace messages that are being printed during instantiation.
- Branch
- PR
> Fix ci.nix to avoid importing everything 3 times

- plutus-playground-client/test/Data/String/ExtraTests.purs
Turns out it was the test at fault, in two ways. It was supposed to
compare applying the function once, and applying it twice, and expect
the same result. In reality, was comparing double-abbreviation with no
abbrevation at all, but choosing such a large maximum string length
that it didn't matter, most of the time. :laugh: :sob:
- Branch
- PR
> Fixing a bug with the Data.String.Extra.abbreviate tests.

- default.nix
- deployment/default.nix
- nix/pkgs/default.nix
- nix/pkgs/thorp/default.nix
- nix/pkgs/thorp/mvn2nix-lock.json
- nix/sources.json
This PR uses https://github.com/kemitix/thorp to sync the static content of the playgrounds with S3. This has two positive effects:
1. files were getting left in the buckets (david.marlowe had more than 1000 superfluous files)
2. it is _much_ faster to sync if not all files have changed. For example, a no-op sync of all files (including tutorials/haddock) took more than 10 mins with a decent internet connection, now it takes less than 20 seconds)
This may be the best value-for-money PR I have ever made 😄 
- Branch
- PR
> use hashes to sync s3 files

- nix/sources.json
This PR fixes **purty pre-commit invocation**: This switches to a fork of pre-commit-hooks.nix where purty works
correctly even when multiple files have been altered.
@krisajenkins had noticed that purty actually fails when multiple files are being specified. Unfortunately purty simply can't handle taking more than one file on the command line and the pre-commit-hooks machinery doesn't work around that by default. 
----
- Branch
- PR
> Fix purty pre-commit

- doc/tutorials/BasicPolicies.hs
- doc/tutorials/BasicValidators.hs
- doc/tutorials/PlutusTx.hs
- doc/tutorials/plutus-tx.rst
- marlowe/src/Language/Marlowe/Client.hs
- plutus-ledger/src/Ledger/Scripts.hs
- plutus-ledger/src/Ledger/Typed/Scripts.hs
- plutus-ledger/test/Spec.hs
- plutus-tx-plugin/src/Language/PlutusTx/Plugin.hs
- plutus-tx-plugin/test/Lib.hs
- plutus-tx-plugin/test/Plugin/Basic/Spec.hs
- plutus-tx-plugin/test/Plugin/Data/Spec.hs
- plutus-tx-plugin/test/Plugin/Errors/Spec.hs
- plutus-tx-plugin/test/Plugin/Functions/Spec.hs
- plutus-tx-plugin/test/Plugin/Laziness/Spec.hs
- plutus-tx-plugin/test/Plugin/Primitives/Spec.hs
- plutus-tx-plugin/test/Plugin/Typeclasses/Spec.hs
- plutus-tx-plugin/test/StdLib/Spec.hs
- plutus-tx-plugin/test/TH/Spec.hs
- plutus-tx/src/Language/PlutusTx.hs
- plutus-tx/src/Language/PlutusTx/Code.hs
- plutus-tx/src/Language/PlutusTx/Lift.hs
- plutus-tx/src/Language/PlutusTx/Plugin/Utils.hs
- plutus-tx/src/Language/PlutusTx/TH.hs
- plutus-use-cases/src/Language/PlutusTx/Coordination/Contracts/MultiSigStateMachine.hs
- plutus-use-cases/test/Spec/Lib.hs
Now `CompiledCode` is named `CompiledCodeIn` and I added
```haskell
type CompiledCode = CompiledCodeIn PLC.DefaultUni PLC.DefaultFun
```
as per discussion that we had in the extensible built-in functions PR.
- Branch
- PR
> [Refac] 'CompiledCode' -> 'CompiledCodeIn'

- plutus-core/generators/Language/PlutusCore/Generators/AST.hs
- plutus-core/plutus-ir-test/OptimizerSpec.hs
- plutus-core/plutus-ir-test/ParserSpec.hs
- plutus-core/plutus-ir-test/Spec.hs
- plutus-core/plutus-ir-test/TransformSpec.hs
- plutus-core/plutus-ir/Language/PlutusIR/Parser.hs
- plutus-core/src/Language/PlutusCore/Constant/Meaning.hs
- plutus-core/src/Language/PlutusCore/Parsable.hs
- plutus-core/src/Language/PlutusCore/Parser.y
- plutus-core/src/Language/PlutusCore/Parser/Internal.hs
- plutus-core/src/Language/PlutusCore/Universe/Default.hs
- plutus-core/untyped-plutus-core/Language/UntypedPlutusCore/Parser.y
The PLC parser is not updated fully due to me not getting along with `happy`.
- Branch
- PR
> Generalized the parsing machineries to work over any 'uni' and 'fun'

- plutus-core/exe/Main.hs
This fixes a problem with the output format for the plc erase command pointed out by @raduom: asking to output erased code in Flat format actually output CBOR. It's a one-word change so I'll probably just merge it without review.
- Branch
- PR
> Fix erasure output format bug

- default.nix
- marlowe-playground-client/default.nix
- plutus-playground-client/default.nix
- plutus-scb-client/default.nix
`generated-purescript` is useful during development and thus needs to be
externally accessible.
- Branch
- PR
> Expose generated-purescript for all clients

- marlowe-playground-client/README.md
- marlowe-playground-client/src/MainFrame/View.purs
This PR solves issue [SCP-1471](https://jira.iohk.io/projects/SCP/issues/SCP-1471).
- Branch
- PR
> SCP-1471: Marlowe Playground: dont show save, save as and rename in the home page

- nix/docker.nix
Update the server-invoker reference which isn't available as passthru
attribute anymore.
- Branch
- PR
> Fix broken server-invoker reference

- plutus-benchmark/nofib/src/Plutus/Benchmark/Prime.hs
- plutus-tx-plugin/src/Language/PlutusTx/Compiler/Builtins.hs
- plutus-tx-plugin/test/StdLib/Spec.hs
- plutus-tx/src/Language/PlutusTx/Builtins.hs
- plutus-tx/src/Language/PlutusTx/Prelude.hs
- plutus-tx/src/Language/PlutusTx/Ratio.hs
This fixes a long-standing problem with integer division (see https://jira.iohk.io/browse/SCP-1176).  PlutusTx provided two integer division operations:  `div` and `rem`, but this was a bad combination since in general `(a 'div' b)*b + a 'rem'  b` is not equal to `a`.  I've added `mod` and `quot` operations, and I'm tempted to leave only `div` and `mod`.  See the lengthy comment on integer division in Ratio.hs.
A couple of questions:
* What is the purpose of the functions in PlututsTx.Prelude?  That has entries for `divide` and `remainder` (which are just aliases for the corresponding things in PlutusTx.Builtins) but not for any other arthimetic operations.  Is that because it's easier for the compiler to spot things like `+` and `*`?  I've added entries for `modulo` and `quotient` there. …
> Kwxm/fix integer division (SCP-1176)

- plutus-benchmark/flat/Codec.hs
- plutus-benchmark/nofib/exe/Main.hs
- plutus-core/exe/Main.hs
- plutus-core/src/Language/PlutusCore/CBOR.hs
- plutus-core/untyped-plutus-core/Language/UntypedPlutusCore/Core/Instance/CBOR.hs
As discussed in a recent Slack thread, we went to some trouble to enable PLC ASTs to be serialised to CBOR without including unit annotations, but then failed to use that in a number of places where we should have.  This PR fixes that: ASTs are now serialised without units in the `plc` and `nofib-exe` excutables and in the `plutus-benchmarks:flat` benchmarks; I also restored unit-less serialisation for typed ASTs.  There are a number of other places where `serialise` is used, for example in the typed and untyped versions of `Size.hs`, where serialisation is used to compute script sizes; there's also something going on in `plutus-tx-plugin`, but I'm not sure what.  I haven't attempted to fix these (but perhaps I should) because @raduom is currently working to get rid of CBOR and these uses …
> Ensure that CBOR serialisation omits unit annotations (SCP-1489)

- marlowe-playground-client/src/HaskellEditor/State.purs
- marlowe-playground-client/src/Marlowe/Linter.purs
- marlowe-playground-client/src/Reachability.purs
- marlowe-playground-client/src/Simulation.purs
- marlowe-playground-client/src/Simulation/BottomPanel.purs
- marlowe-playground-client/src/Simulation/State.purs
- marlowe-playground-client/src/Simulation/Types.purs
- marlowe-playground-client/src/Wallet.purs
- marlowe-playground-client/test/Marlowe/ContractTests.purs
- marlowe-playground-client/test/Marlowe/LintTests.purs
Contents:
- Only show unreachable subtrees only once in linting (even if there are several reasons it is unreachable)
- Refactor code so that we can add the results of the static analysis to the linting (preparation for SCP-952)
* This required moving types from `marlowe-playground-client/src/Simulation/State.purs` to `marlowe-playground-client/src/Simulation/Types.purs`, in order to avoid cyclic dependency
Deployed in: https://pablo.marlowe.iohkdev.io/
Example test:
```haskell
If FalseObs (If TrueObs (If FalseObs (If TrueObs (Assert TrueObs Close) (Assert TrueObs Close)) (If TrueObs (Assert TrueObs Close) (Assert TrueObs  Close))) (If FalseObs (If TrueObs (Assert TrueObs Close) (Assert TrueObs Close)) (If TrueObs (Assert TrueObs Close) (Assert TrueObs Close)))) (If TrueObs (If FalseObs …
```
> SCP-1496 - Linting: only show unreachable subtrees once

- web-common/src/Halogen/Monaco.purs
- web-common/src/Monaco.purs
Currently on master, when you load the main page you get the following JS error
I found out that the reason was that even if the editor is running (probably hiding), the [getDecorationRange](https://microsoft.github.io/monaco-editor/api/interfaces/monaco.editor.itextmodel.html#getdecorationrange) was returning null, which is one of the expected results according to the documentation. 
To solve this I modified the FFI so that it returns a `Nullable` and then convert it to `Maybe`, and also made the function Effectful.
While implementing the handleQuery, I found out that I couldn't just use `withEditor` because it doesn't offer a way for the callback function to fail, which ended up becoming a pattern matching mess :/. Please @palas, @shmish111, if you know a way of using a pattern to avoid …
> Fix end line number error

- nix/pkgs/default.nix
- nix/pkgs/purty-pre-commit/default.nix
- shell.nix
Introduce `purty-pre-commit` wrapper script to be used
for pinning purty in the hooks `tools` attribute.
The issue is that purty cannot handle being passed multiple paths
but that is exactly what pre-commmit wants to do. In order to deal
with that i added a wrapper script in pre-commit-hooks.nix but the
moment we specify *our* version of purty this wrapper is overwritten
so we have to provide our own.
On the plus side it is now using the recently added `validate`
command which leads to better output when linting fails.
**PS**: Careful while reviewing this PR, i might have sneezed on it ...
------
- Branch
- PR
> Fix purty (yet) again

- .github/dependabot.yml
- .github/workflows/niv-update.yml
This adds a niv-updater action which runs `niv update` daily and creates
PRs when there are updates. It also adds a `dependabot.yml` file which
will create PRs for any enabled github action when a new version of the
action is available.
- Branch
- PR
> Add niv-updater-action / dependabot

- hie-cabal.yaml
- hie-stack.yaml
- marlowe-playground-server/marlowe-playground-server.cabal
- nix/pkgs/default.nix
- nix/pkgs/fix-purty/default.nix
- nix/pkgs/fix-stylish-haskell/default.nix
- nix/pkgs/haskell/extra.nix
- nix/pkgs/purty-pre-commit/default.nix
- nix/pkgs/update-client-deps/default.nix
- nix/pkgs/update-hie/default.nix
- nix/pkgs/update-metadata-samples/default.nix
- plutus-contract/plutus-contract.cabal
- plutus-scb/plutus-scb.cabal
- shell.nix
`implcit-hie` is the project that HLS uses to generate a cradle for a
cabal project when you don't have a `hie.yaml`. You can also just use it
to generate literal `hie.yaml` files, which is what I've done here, for both
the Cabal and Stack versions.
This is therefore a halfway house towards not needing the
`hie-*.yaml` files: they're checked in, so we can edit them if necessary,
or see where the generated output goes wrong (I had to make a few changes
to `.cabal` files to work around bugs).
Becuase I think we might want to tweak the otuput, I'm not asserting that the
checked-in files are exactly the output of `gen-hie` in CI, but there is an `update-hie`
script that will regenerate them. So as long as we keep the structure
broadly the same, you should be able to update them by running …
> Use implicit-hie to generate hie-*.yaml

- .github/workflows/test.yml
This PR adds a Github Action workflow which:
- runs `nix-instantiate release.nix --restrict-eval` on linux and macos
- runs `nix-build -A tests` on linux
---
- **Q**: We already have hydra, why would we want this? 
- **A**: I have tested various versions of this setup and my hydra job hasn't even been queued yet. The idea is not to replace hydra with this, but to get much earlier feedback on possible instantiation errors. Especially since we have 2 platforms and developers don't usually check both of them locally.
Quite some time is spent just for downloading stuff each time and i wonder if i could do some caching of `/nix/store` in some way to improve this but i couldn't find anything conclusive and it is still way faster than hydra anyway.
-----
- Branch
- PR …
> Create github workflow for tests

- nix/pkgs/default.nix
This changes the npmlock2nix import into a callPackage statement. Using
the import caused npmlock2nix to use its internally pinned version of
nixpkgs
- Branch
- PR
> Fix npmlock2nix import

- release.nix
This updates the job constituents as follows:
- adds plutus-playground and marlowe-playground on darwin
- removes obsolete `dev.scripts` attributes
- Branch
- PR
> hydra: update required job constituents

- marlowe/src/Language/Marlowe/Client.hs
- marlowe/test/Spec/Marlowe/AutoExecute.hs
- plutus-contract/src/Language/Plutus/Contract/StateMachine.hs
- plutus-use-cases/src/Language/PlutusTx/Coordination/Contracts/PingPong.hs
Marlowe and other contracts can re-use `getOnChainState` and handle the case when no onchain state is currently present.
> StateMachine.getOnChainState throws NoOnChainState

- marlowe/src/Language/Marlowe/Client.hs
- plutus-contract/src/Language/Plutus/Contract/StateMachine.hs
- plutus-contract/src/Language/Plutus/Contract/StateMachine/OnChain.hs
- plutus-use-cases/src/Language/PlutusTx/Coordination/Contracts/Future.hs
- plutus-use-cases/src/Language/PlutusTx/Coordination/Contracts/GameStateMachine.hs
- plutus-use-cases/src/Language/PlutusTx/Coordination/Contracts/MultiSigStateMachine.hs
- plutus-use-cases/src/Language/PlutusTx/Coordination/Contracts/PingPong.hs
- plutus-use-cases/src/Language/PlutusTx/Coordination/Contracts/Prism/CredentialManager.hs
- plutus-use-cases/src/Language/PlutusTx/Coordination/Contracts/Prism/Mirror.hs
- plutus-use-cases/src/Language/PlutusTx/Coordination/Contracts/Stablecoin.hs
- plutus-use-cases/test/Spec/MultiSigStateMachine.hs
* Remove the `InvalidTransition s i` branch from `SMContractError`
* As a result, contracts that don't handle the invalid transition error don't immediately fail when an invalid transition is attempted
- Branch
- PR
> SCP-1330: State machine handles invalid transition

- plutus-core/plutus-ir-test/TestLib.hs
- plutus-core/plutus-ir/Language/PlutusIR/Compiler.hs
- plutus-core/plutus-ir/Language/PlutusIR/Compiler/Types.hs
- plutus-tx-plugin/src/Language/PlutusTx/Compiler/Error.hs
- plutus-tx-plugin/src/Language/PlutusTx/Compiler/Types.hs
- plutus-tx-plugin/src/Language/PlutusTx/Plugin.hs
- plutus-tx/src/Language/PlutusTx/Lift.hs
The biggest change is the addition of an `type ECore = ExceptT CoreM` monad, so we can manage the errors ourselves.
Added some comments and tried to make the code more readable and shorter. Unfortunately I used implicitparams, because i think here it makes it cleaner.
> Refactored Plugin.hs

- plutus-core/generators/Language/PlutusCore/Generators/Internal/Denotation.hs
- plutus-core/generators/Language/PlutusCore/Generators/Internal/Dependent.hs
- plutus-core/generators/Language/PlutusCore/Generators/Internal/Entity.hs
- plutus-core/plutus-ir/Language/PlutusIR/Purity.hs
- plutus-core/src/Language/PlutusCore/Builtins.hs
- plutus-core/src/Language/PlutusCore/Constant/Apply.hs
- plutus-core/src/Language/PlutusCore/Constant/Function.hs
- plutus-core/src/Language/PlutusCore/Constant/Meaning.hs
- plutus-core/src/Language/PlutusCore/Constant/Typed.hs
- plutus-core/test/Evaluation/DynamicBuiltins/Definition.hs
- plutus-core/untyped-plutus-core-test/Evaluation/ApplyBuiltinName.hs
This
1. adds handling of higher-kinded type variables by the machinery that automatically derives type schemes
2. makes reflected types intrinsically typed. Now if you attempt to define a built-in function whose type is ill-kinded, GHC will tell you there's a kidn mismatch. Kinds do not need to be specified explicitly anymore as they are inferred automatically by GHC (unless there's an actual ambiguity)
> [Builtins] Automatially kind check types of built-in functions

- plutus-playground-client/src/MainFrame.purs
- plutus-playground-client/src/Types.purs
This will allow comparing with the current code/simulation to check for changes. Specifically, this will enable us to disable the simulate/transactions buttons on the new interface when the code or simulation changes, forcing the user to recompile/reevaluate.
- Branch
- PR
> Adding last compiled code and last evaluated simulation to state.

- plutus-contract/src/Data/Row/Extras.hs
- plutus-contract/src/Language/Plutus/Contract.hs
- plutus-use-cases/src/Language/PlutusTx/Coordination/Contracts/Prism.hs
GHC really doesn't like the one from row-types when there are many overlapping rows. This
bites us in the Prism use-case, where we combine four different schemas that all contain
BlockchainActions.
- Branch
- PR
> GHC-friendly implementation of Data.Row.(.\/)

- nix/pkgs/default.nix
- nix/sources.json
This uses `nix/default.nix` from pre-commit-hooks.nix which allows us to
specify _our_ pinned nixpkgs instead of relying on the one
pre-commit-hooks.nix uses.
- Branch
- PR
> Use pre-commit-hooks.nix with our nixpkgs

- .github/workflows/niv-update.yml
It gets updated frequently with irrelevant ops stuff.
- Branch
- PR
> Blacklist iohk-nix in niv updater

- plutus-ledger/src/Ledger/Constraints/OffChain.hs
tl;dr The constraint solver treated burn constraints as negative inputs, forcing it to add an extra pair of input/output to make up the "required spend" of zero tokens.
Transactions are constructed in three phases:
1. `Ledger.Constraints.OffChain.processContraints`:
The constraints are traversed computing inputs, outputs and forges, and tracking two quantities: valueSpentActual, and valueSpentRequired.
2. `Ledger.Constraints.OffChain.addMissingValueSpent`:
The positive part of `valueSpentRequired - valueSpentActual` is added as outputs to the pubkey signing the transaction.
3. `Language.Plutus.Contract.Wallet.balanceWallet`:
The transaction is balanced, adding inputs and outputs to/from the wallet to make the sum of inputs, outputs and forges zero.
So what counts as valueSpentActual and …
> Fix problem with burning tokens

- plutus-ledger/src/Ledger/Constraints/OffChain.hs
(follow-up from https://github.com/input-output-hk/plutus/pull/2534)
* Replace `valueSpentRequired` and `valueSpentActual` by a single field `valueSpentBalance`
* `valueSpentBalance` holds the difference (`valueSpentRequired - valueSpentActual`)
* I decided not to follow the second suggestion of adding up inputs and outputs at the end. Transaction inputs (of type `TxIn`) don't have a value attached to them, so we'd have to use `lookupTxOutRef` in order to get the value. But we already do this lookup when we handle `MustSpendPubKeyOutput` in `processConstraint`, so we can just add modify `valueSpentBalance` in there. 
- Branch
- PR …
> Simplify 'processConstraint' and 'addMissingValueSpent'

- marlowe-playground-client/src/MainFrame/State.purs
- plutus-playground-client/src/MainFrame.purs
- web-common/src/AjaxUtils.purs
- web-common/src/Gists/Types.purs
The new design for the Plutus playground refresh calls for the Ajax error pane in the Gist widget to be closeable. This PR adds the bones to make that possible. It requires adding a new `GistAction` (in `web-common/src/Gists/Types.purs`), which the Marlowe playground also uses. I think all that's needed is an extra case in the `MainFrame/State.purs` module to cover the new action (and do nothing with it). But I don't have the Marlowe playground running in my dev environment, so I'm hoping e.g. Hernan can check this quickly.
- Branch
- PR
> Adding skeleton code for a closeable ajax error pane, which will be needed for the Plutus playground refresh.

- marlowe-playground-client/webpack.config.js
This PR fixes the Webpack configuration for local development. This is needed for opening/saving Gists within local development.
- Branch
- PR
> Marlowe playground FE: Fix webpack configuration

- .github/workflows/niv-update.yml
See comment in the workflow. It's basically always a mass-rebuild, and
it doesn't gain us much.
I considered just making the updater action run less frequently, but I
don't think we even want to update it every month!
- Branch
- PR
> niv-updater: also blacklist nixpkgs

- marlowe-playground-client/src/MainFrame/State.purs
- marlowe-playground-client/src/Wallet.purs
- plutus-playground-client/src/MainFrame.purs
- plutus-playground-client/src/Types.purs
- web-common/src/Halogen/Analytics.purs
I happened upon a TODO warning about renaming the analytics tracking function in web-common, and thought I might as well do it.
Then I noticed that the Marlowe playground was making use of the web-common module, while the Plutus playground had some local duplicate functions. So I tried refactoring to use the web-common functions instead. I got most of the way, but got blinded by the Monads at the last step. @krisajenkins can you give me a hint, or just take us over the finish line yourself?
Unless of course you guys had some other plans for any of this, in which case, don't mind me.
> Analytics name fix

- plutus-core/exe/Main.hs
The `convert` option of the `plc` command can convert Plutus Core between various formats (textual, CBOR, Flat, ...).  For some reason, I'd made it add a newline at the end when it was writing to stdout, even for binary formats.  This is just annoying, so this two-line PR removes it.
- Branch
- PR
> Fix annoyance in output of serialised code in PLC command

- nix/lib/ci.nix
- release.nix
This seems to speed up Hydra evaluation by a lot, and is more robust to
boot.
- Branch
- PR
> Try out string names in the required job

- nix/pkgs/haskell/default.nix
- nix/pkgs/haskell/extra.nix
- nix/sources.json
I want this since it finally uses a different build dir for `hie-bios`,
thus preventing the `cabal configure` thrashing when you run a cabal
command in the terminal while HLS is running.
- Branch
- PR
> Bump HLS to 0.8.0

- plutus-ledger/src/Ledger/Generators.hs
- plutus-scb/src/Cardano/Node/RandomTx.hs
I pulled out of the interpreter a function that generates a random Tx,
so we can avoid calling `createSystemRandom` on each run of the
function.
I will need a fast way of generating transactions, so I also removed all
of the other effects (like logging) which don't make much sense for my
use case.
I found some surprising behaviour when benchmarking some of the Tx
generation code and added some comments to try and explain why the
generating functions behave the way they do.
- Branch
- PR
> Refactor the generator interpreter.

- nix/stack.materialized/plutus-tx.nix
- plutus-tx/plutus-tx.cabal
- plutus-tx/src/Language/PlutusTx/Either.hs
- plutus-tx/src/Language/PlutusTx/Prelude.hs
- plutus-use-cases/src/Language/PlutusTx/Coordination/Contracts/Stablecoin.hs
- plutus-use-cases/test/Spec/Stablecoin.hs
* Add a maxReserveRatio parameter to the stablecoin
* Prevent transitions that would bring the reserve ratio above the maximum
* Add some logging to inform of invalid transitions
* Add either functions to prelude
- Branch
- PR
> SCP-1355: Add max reserve ratio to stablecoin

- marlowe-playground-client/src/Blockly/Events.purs
- marlowe-playground-client/src/Blockly/Types.purs
- marlowe-playground-client/src/Halogen/ActusBlockly.purs
- marlowe-playground-client/src/Halogen/Blockly.purs
- marlowe-playground-client/src/Halogen/BlocklyCommons.purs
- marlowe-playground-client/src/HaskellEditor/State.purs
- marlowe-playground-client/src/HaskellEditor/Types.purs
- marlowe-playground-client/src/JavascriptEditor/State.purs
- marlowe-playground-client/src/JavascriptEditor/Types.purs
- marlowe-playground-client/src/MainFrame/State.purs
- marlowe-playground-client/src/MainFrame/Types.purs
- marlowe-playground-client/src/MarloweEditor/State.purs
- marlowe-playground-client/src/MarloweEditor/Types.purs
- marlowe-playground-client/src/SimulationPage/Types.purs
- web-common/src/Halogen/Monaco.purs
Detecting if a project has unsaved changes and dealing with it correctly is quite tricky. We were in a situation where we had a lot of state duplicated so I have managed to remove that duplication. In addition there was an issue where it is difficult to know when a user has made a change to blockly or if code was moved from the marlowe editor. In the case where code is moved from marlowe editor to blockly, we don't want to mark as having unsaved changes (because the marlowe editor and blockly are considered "views" of the same code) however if the user changes something then of course we do. Since blockly was doing loads of stuff asynchronously and since the `finished_loading` doesn't actually mean that loading has finished 😒  we need a way to detect this. I realised that `ui` events are …
> Mp save refactoring

- plutus-playground-client/src/Chain.purs
- web-common/src/Playground/Lenses.purs
* Instead of showing the contract instance tag and the message, it showed the message twice
- Branch
- PR
> plutus-playground: Fix the display of contract instance log messages

- ci.nix
- default.nix
- We weren't recursing into `plutus-scb` due to a missing
`recurseIntoAttrs`
- Some of the lambdas were not listed (we should check they build!)
- Branch
- PR
> Fix some more things that were missing from Hydra

- marlowe-playground-client/default.nix
- nix/lib/purescript.nix
- plutus-playground-client/default.nix
- plutus-scb-client/default.nix
**summary**
This PR fixes the compilation/test execution of all frontend clients.
**some background**:
Compile all required sources and execute unit tests during the checkPhase.
The `checkPhase` is now a required argument to `buildPursPackage`. It
would be just always execute `npm run test` but this fails in cases
where `spago test` is used which (always) tries to download remote files.
**Notes**
- The scb-client is not currently being built by hydra so #2597 should be merged before this one
- Once scb-client *is* actually built by hydra it will fail because of some naming conflict. So we also need to wait for that.
--------
- Branch
- PR
- If you changed any Purescript …
> buildPursPackage: fix compilation/test execution

- plutus-playground-server/usecases/GameSimulations.hs
I noticed the Basic Game simulation had three wallets, but only needed two. A tiny thing, but it seems to me this eliminates a bit of unnecessary "noise" for the user.
> Removing third wallet from basic game simulation.

- playground-common/src/Playground/Interpreter/Util.hs
- playground-common/src/Playground/Types.hs
- plutus-playground-client/src/Types.purs
- plutus-playground-server/test/Playground/UsecasesSpec.hs
The field is not used anywhere on the client, and it's redundant anyway because the `resultRollup` field contains all the transactions.
- Branch
- PR
> plutus-playground: Delete unused field from EvaluationResult

- marlowe-playground-client/src/BlocklyEditor/State.purs
- marlowe-playground-client/src/BlocklyEditor/Types.purs
- marlowe-playground-client/src/BlocklyEditor/View.purs
- marlowe-playground-client/src/Halogen/Blockly.purs
- marlowe-playground-client/src/HaskellEditor/State.purs
- marlowe-playground-client/src/HaskellEditor/Types.purs
- marlowe-playground-client/src/JavascriptEditor/State.purs
- marlowe-playground-client/src/JavascriptEditor/Types.purs
- marlowe-playground-client/src/MainFrame/State.purs
- marlowe-playground-client/src/MainFrame/Types.purs
- marlowe-playground-client/src/MainFrame/View.purs
- marlowe-playground-client/src/Marlowe/Gists.purs
- marlowe-playground-client/src/SimulationPage/State.purs
- marlowe-playground-client/src/SimulationPage/Types.purs
Still need to try to remove anything marlowe-specific from Halogen.Blockly but I think we can leave this for another PR
deployed to https://david.marlowe.iohkdev.io/#/
- Branch
- PR
> wrap blockly in a TEA-style submodule

- plutus-core/src/Language/PlutusCore/Builtins.hs
- plutus-core/src/Language/PlutusCore/Constant/Meaning.hs
- plutus-core/src/Language/PlutusCore/Constant/Typed.hs
- plutus-core/test/Evaluation/DynamicBuiltins/Definition.hs
I got curious if there was any way to infer type schemes for polymorphic built-in functions with providing only those types that help resolve inherent ambiguity. I.e. no types at all for functions like `IfThenElse`, `Id` and `Const` and minimal types for functions with higher-kinded type variables. This PR shows how to do that. Note that the shiny new automatic inference machinery does not break the "I'll specify the type signature manually" case.
Supporting the higher-kinds case costs a lot in terms of code complexty and we don't seem to need that at this point and due to stupid behaviour of GHC I can't handle the general case anyway, so I'm going to rewrite this to handle only type variables of kind `*`. But the temptation to show off was too high, so I couldn't resist showing this …
> [Builtins] Type scheme inference for polymorphic built-in functions

- marlowe-playground-client/README.md
- marlowe-playground-client/package.json
- marlowe-playground-client/spago.dhall
- marlowe-playground-client/web-common
- marlowe-playground-client/webpack.config.js
- marlowe-playground-client/webpack.test.config.js
- nix/lib/purescript.nix
- plutus-playground-client/README.md
- plutus-playground-client/package.json
- plutus-playground-client/spago.dhall
- plutus-playground-client/static/main.scss
- plutus-playground-client/static/transactions.scss
- plutus-playground-client/web-common
- plutus-playground-client/webpack.config.js
- plutus-scb-client/package.json
- plutus-scb-client/spago.dhall
- plutus-scb-client/static/main.scss
- plutus-scb-client/web-common
- plutus-scb-client/webpack.config.js
- shell.nix
This PR addresses some discrepancies between the usual developer workflow for the frontend clients and the nix build - more specifically the handling of `web-common`. More specifically this PR:
- symlinks `web-common` to plutus,marlowe and scb-client
- updates references to `../web-common`
- updates the webpack configuration so npm dependencies can be found when loaded from `web-common`
Additionally this PR introduces scripts to execute the purescript code generation:
- `plutus-playground-generate-purs`
- `marlowe-playground-generate-purs`
- `plutus-scb-generate-purs`
When executed they will write the respective code to `./generated` (after removing any potentially existing previous `generated` directory).
**Note**: nix builds and the development cycle workflow both seem to be working …
> Improve nix/purescript workflow

- plutus-playground-server/usecases/HelloWorldSimulations.hs
#2610 added a `simulationId` to fix the simulation tab naming issue. Sorry, I meant to mention this would be necessary before merging #2603, but wasn't sure which would be merged first. And then it momentarily slipped my mind.
> Adding simulationId to hello world simulation.

- doc/tutorials/basic-forging-policies.rst
Monetary policy scripts/forging policies just have 2 arguments (ctrl+v/c is evil) 😄 
- Branch
- PR
> Update basic-forging-policies.rst wrong number of arguments

- default.nix
- marlowe-playground-client/README.md
- marlowe-playground-client/default.nix
- plutus-playground-client/README.md
- plutus-playground-client/default.nix
- plutus-scb-client/default.nix
- shell.nix
https://github.com/input-output-hk/plutus/pull/2608 made the shell
depend on `plutus-playground-server`, and hence
transitively all our Haskell packages, and hence every Haskell source
file. This is slow, and makes lorri etc. thrash horribly.
This is why we don't have e.g. `updateMaterialized` as a shell script in
the shell, it has the same problem.
To prevent this happening in future, I put `plutus-core` in
`disallowedRequisites`.
This makes the workflow a bit worse, but the alternative is worse, I fear.
- Branch
- PR
> Fix shell dependency on plutus-playground-server

- doc/plutus-doc.cabal
- doc/tutorials/HelloWorldApp.hs
- nix/stack.materialized/plutus-doc.nix
* Add `HelloWorldApp` to `plutus-doc.cabal` and make it compile
- Branch
- PR
> plutus-doc: Add a missing module

- plutus-core/src/Language/PlutusCore/Evaluation/Machine/Cek.hs
- plutus-core/untyped-plutus-core/Language/UntypedPlutusCore/Evaluation/Machine/Cek.hs
When working on the specification, I noticed that the `VBuiltin` value used by the CEK machines contains an environment which is never used.  I think it was originally there for evaluation of the arguments to a builtin, but the appropriate environments are actually saved in the `[_ (N,ρ)]` frame (`FrameApplyArg`).  This removes the environment from `VBuiltin`.  
I think the comments in the CEK machine could do with some maintenance as well.  I'll make an issue so I don't forget that.
- Branch
- PR
> Remove superfluous environments from CEK VBuiltin values

- marlowe-playground-client/src/MainFrame/State.purs
- marlowe-playground-client/src/MainFrame/Types.purs
- marlowe-playground-client/src/Projects/Types.purs
- marlowe-playground-client/src/StaticData.purs
- web-common/src/SessionStorage.js
- web-common/src/SessionStorage.purs
This PR fixes bug 1650, where the edit source button in the simulation did not work after a refresh.
- Branch
- PR
> SCP-1650 Marlowe Playground Frontend: Fix edit source button in the simulation

- marlowe/src/Language/Marlowe/Analysis/FSSemantics.hs
Small refactoring that adds the padding (with -1) to the end of the symbolic trace instead of the beginning. This will make formal verification easier
- Branch
- PR
> SCP-1701 - Move padding to be the suffix of the symbolic trace

- marlowe/src/Language/Marlowe/Analysis/FSSemantics.hs
Change order in static analysis of Choice and Notify to be consistent with Deposit
- Branch
- PR
> SCP-1729 - Fix ordering of traces in static analysis implementation

- marlowe-playground-client/src/MainFrame/State.purs
There was a problem in marlowe playground where it asked you to save progress when transitioning from home.
- Branch
- PR
> SCP-1711 Marlowe Playground Frontend: Fix unsaved changes regression

- marlowe/src/Language/Marlowe/Analysis/FSSemantics.hs
When testing the function that calculates hidden variables, it became apparent that the discrepancy between it and the static analysis implementation was due to the fact that static analysis was checking the bounds of choices after choosing which branch was activated in the When.
- Branch
- PR
> SCP-1731 - Static analysis checks choice bounds after picking a branch in Choice (instead of before)

- ci.nix
- shell.nix
This is a useful guard, but it breaks lorri due to a bug. Not sure when
we'll be able to resolve that, but in the mean time we can just set it
on the version that's built in CI, so we'll still catch the problem but
it won't trip up lorri.
- Branch
- PR
> Move disallowedRequisites only to the CI build

- marlowe-playground-client/src/MarloweEditor/BottomPanel.purs
- marlowe-playground-client/src/MarloweEditor/State.purs
- marlowe-playground-client/src/MarloweEditor/Types.purs
- marlowe-playground-client/src/StaticAnalysis/CloseAnalysis.purs
- marlowe-playground-client/src/StaticAnalysis/Reachability.purs
- marlowe-playground-client/src/StaticAnalysis/StaticTools.purs
This PR implements a static analysis functionality that checks whether there is any `Close` construct that may refund money under some circumstances (any implicit refund caused by a `Close` construct):
Example that passes the analysis:
```haskell
When [(Case (Deposit (Role "party1") (Role "party1") (Token "" "") (Constant 500)) (When [(Case (Deposit (Role "party2") (Role "party2") (Token "" "") (Constant 300)) (Pay (Role "party1") (Party (Role "party2")) (Token "" "") (Constant 500) (Pay (Role "party2") (Party (Role "party1")) (Token "" "") (Constant 300) Close)))] 20 (Pay (Role "party1") (Party (Role "party1")) (Token "" "") (Constant 500) Close)))] 15 Close
```
Example that has one counter-example: Swap
- Branch
- PR
- …
> SCP-1589 - Static analysis for finding which Close constructs return money

- plutus-playground-client/spago.dhall
#2639 separated out some common code into `web-common-playground`, but didn't include this as a source in `plutus-playground-client/spago.dhall`. Just fixing that.
> Adding web-common-playground to plutus playground spago sources.

- marlowe-playground-client/src/BottomPanel/State.purs
- marlowe-playground-client/src/BottomPanel/Types.purs
- marlowe-playground-client/src/BottomPanel/View.purs
- marlowe-playground-client/src/Halogen/Classes.purs
- marlowe-playground-client/src/HaskellEditor/State.purs
- marlowe-playground-client/src/HaskellEditor/Types.purs
- marlowe-playground-client/src/HaskellEditor/View.purs
- marlowe-playground-client/src/JavascriptEditor/State.purs
- marlowe-playground-client/src/JavascriptEditor/Types.purs
- marlowe-playground-client/src/JavascriptEditor/View.purs
- marlowe-playground-client/src/MarloweEditor/BottomPanel.purs
- marlowe-playground-client/src/MarloweEditor/State.purs
- marlowe-playground-client/src/MarloweEditor/Types.purs
- marlowe-playground-client/src/MarloweEditor/View.purs
- marlowe-playground-client/src/SimulationPage/BottomPanel.purs
- marlowe-playground-client/src/SimulationPage/State.purs
- marlowe-playground-client/src/SimulationPage/Types.purs
- marlowe-playground-client/src/SimulationPage/View.purs
This PR refactors the bottom panel functionality that was shared through copy and paste in the HaskellEditor, JavaScriptEditor, MarloweEditor and Simulator pages into a single reusable component.
This way, the functionalities are reused and they share visual aspects. Before this PR for example, there was no way of "switching tabs" between generated code and code errors in the Javascript and Haskell editor. Granted, there can never coexist at the same time, but, they also didn't have a title that indicated what were the possible tabs.
We should take special attention to the types described in `BottomPanel.Types`, which defines the first use case we had for a sub-component to be able to display HTML and fire actions inside the sub-component but the actions being defined in the parent. Kind …
> SCP-1733 Marlowe Playground Frontend: Refactor the bottom panel into a reusable component

- marlowe-playground-client/src/BlocklyEditor/State.purs
- marlowe-playground-client/src/BlocklyEditor/Types.purs
- marlowe-playground-client/src/BlocklyEditor/View.purs
- marlowe-playground-client/src/Marlowe/Holes.purs
- marlowe-playground-client/src/Marlowe/Linter.purs
This pull request runs the linter on the blockly generated code and disables the "send to simulator" button if the contract has holes.
By doing this PR I found an inconsistency with the `CodeChange` message fired by blockly. When you add a block to a contract, the `CodeChange` event is fired successfully, but when you remove a block from a contract, the event is fired while you are still dragging, so the code hasn't actually change yet. 
This causes a bug, as the linter thinks the contract has no holes while it does, and a separate  `CodeChange` needs to be fired before it disables the button.
I submit this PR as is because the changes needed to correctly track `CodeChange` is way bigger than this, and will be done in a separate PR.
- Branch
- PR
- If you updated any …
> SCP-1647 Marlowe Playground Frontend - Disable send to simulator if blockly has holes

- CONTRIBUTING.adoc
- default.nix
- nix/default.nix
- nix/pkgs/default.nix
- nix/pkgs/haskell/default.nix
- nix/pkgs/haskell/haskell.nix
- shell.nix
Also exposes it in the shell, so you can do
`nix-shell --arg enableHaskellProfiling true`
and get a shell with profiling libraries. Does require rebuilding the
world though, maybe we should cache it.
- Branch
- PR
> Add a parameter for enabling Haskell profiling

- doc/tutorials/basic-apps.rst
I started going through the plutus tutorials and this line threw me off, I couldn't find a reference to `SplitValue` anywhere so I assumed it actually meant `SplitData`.
If it turns out `SplitValue` is actually the correct term, can we add some context here?
> Basic Apps tutorial typo: `SplitValue` should be `SplitData`

- default.nix
- marlowe-dashboard-client/default.nix
- marlowe-playground-client/default.nix
- nix/lib/purescript.nix
- nix/overlays/nixpkgs-overrides.nix
- nix/pkgs/default.nix
- nix/pkgs/haskell/default.nix
- nix/pkgs/haskell/haskell.nix
- nix/sources.json
- plutus-pab-client/default.nix
- plutus-playground-client/default.nix
- web-common-marlowe/default.nix
- web-common-playground/default.nix
- web-common-plutus/default.nix
- web-common/default.nix
I do remember this being problematic before, switching to the more
maintained project immediately gave us a 2x eval speedup...
- Branch
- PR
> Switch to hercules-ci/gitignore.nix for a cool 2x eval speedup

- marlowe-playground-client/src/Blockly/Events.purs
- marlowe-playground-client/src/Blockly/Internal.js
- marlowe-playground-client/src/Blockly/Internal.purs
- marlowe-playground-client/src/Blockly/Types.purs
- marlowe-playground-client/src/BlocklyComponent/State.purs
- marlowe-playground-client/src/BlocklyComponent/Types.purs
- marlowe-playground-client/src/BlocklyEditor/State.purs
- marlowe-playground-client/src/Halogen/ActusBlockly.purs
- marlowe-playground-client/src/Halogen/BlocklyCommons.purs
- marlowe-playground-client/src/LoginPopup.purs
- marlowe-playground-client/src/MainFrame/State.purs
This PR solves 2 bugs that were related:
* The has unsaved changes indicator was being triggered when loading up a project.
* The "send to simulation" button was not disable when we had a full contract and we detach a node.
Both bugs were related to the CodeChange Blockly event not being fired correctly.
- Branch
- PR
> SCP-1796 Marlowe Playground Frontend - Fix blockly CodeChange event

- marlowe-playground-client/src/HaskellEditor/State.purs
- marlowe-playground-client/src/JavascriptEditor/State.purs
- marlowe-playground-client/src/JavascriptEditor/Types.purs
- marlowe-playground-client/src/Language/Javascript/Interpreter.purs
- marlowe-playground-client/src/Marlowe/Blockly.purs
- marlowe-playground-client/src/Marlowe/Extended.purs
- marlowe-playground-client/src/Marlowe/ExtendedMarlowe.purs
- marlowe-playground-client/src/Marlowe/Gen.purs
- marlowe-playground-client/src/Marlowe/Holes.purs
- marlowe-playground-client/src/Marlowe/Linter.purs
- marlowe-playground-client/src/Marlowe/Parser.purs
- marlowe-playground-client/src/MarloweEditor/State.purs
- marlowe-playground-client/src/Simulator.purs
- marlowe-playground-client/src/StaticAnalysis/BottomPanel.purs
- marlowe-playground-client/src/StaticAnalysis/CloseAnalysis.purs
- marlowe-playground-client/src/StaticAnalysis/Reachability.purs
- marlowe-playground-client/src/StaticAnalysis/StaticTools.purs
- marlowe-playground-client/src/StaticAnalysis/Types.purs
- marlowe-playground-client/src/Types.purs
- marlowe-playground-client/src/Wallet.purs
- marlowe-playground-client/test/Marlowe/CompletionItemsTests.purs
This is a refactoring that aims to split Marlowe in two:
* "Marlowe Core" is the original `Semantics.purs`, and is used for static analysis and simulation
* and `Extended.purs` (Extended Marlowe) is, so far, essentially a copy of some key types of `Semantics.purs` that will eventually be modified to include template constructors. I have left out base constructs like `Party` and `ChoiceId`. I think it could be a good idea to eventually get rid of `Party` from "Extended Marlowe", in fact.
`Party` is a weird case, because it is not in the "Extended Marlowe" module but, because it has holes, I had to create two parsers for it, one that accepts holes and one that doesn't. Because I can only generate "Extended Marlowe" from the parser with holes, and Party is also in things like Inputs, which …
> SCP-1825 - Split Marlowe into "Marlowe Core" and "Extended Marlowe" in Playground

- marlowe-playground-client/src/AppM.purs
- marlowe-playground-client/src/Blockly/Types.purs
- marlowe-playground-client/src/Env.purs
- marlowe-playground-client/src/HaskellEditor/State.purs
- marlowe-playground-client/src/JavascriptEditor/State.purs
- marlowe-playground-client/src/Main.purs
- marlowe-playground-client/src/MainFrame/State.purs
- marlowe-playground-client/src/MainFrame/View.purs
- marlowe-playground-client/src/MarloweEditor/State.purs
- marlowe-playground-client/src/Projects/State.purs
- marlowe-playground-client/src/Rename/State.purs
- marlowe-playground-client/src/SaveAs/State.purs
- marlowe-playground-client/src/SimulationPage/State.purs
- marlowe-playground-client/src/StaticAnalysis/CloseAnalysis.purs
- marlowe-playground-client/src/StaticAnalysis/Reachability.purs
- marlowe-playground-client/src/StaticAnalysis/StaticTools.purs
This PR creates an AppM shell to run the Halogen app to provide ReaderT capabilities and avoid having to manually pass the settings in all handleAction's. It also serves as a starting point to use the capabilities pattern, and be able to share functionality between the plutus playground and the Marlowe Dashboard.
One thing I wasn't able to do was to simplify the `runAjax` helpers located in different locations. For the `Env` data type, I decided to use an object that contains the current settings to communicate to the backend under a `ajaxSettings` key, and this way allow the Env to grow in the future. The code generated by Servant, like `getApiGists` used in `Project.State` requires to be executed in a monad with a `MonadAsk (SPSettings_ SPParams_) m` restriction, but our handleAction's …
> SCP-1766 Marlowe Playground Frontend: Refactor settings to halogen AppM

- default.nix
- marlowe-dashboard-client/default.nix
- marlowe-playground-client/default.nix
- nix/lib/filter-npm.nix
- nix/pkgs/default.nix
- plutus-pab-client/default.nix
- plutus-playground-client/default.nix
**Summary**: filter down the source for buildModules to just `package.json` and
`package-lock.json` to avoid useless rebuilds.
I have been annoyed for quite a while by seeing countless rebuilds of `nodeModules` of any of the clients which includes lengthy rebuilds of sass and libxml. With the changes of this PR this won't be happening anymore.
-----
- Branch
- PR
> buildNodeModules: filter src

- marlowe-playground-client/grammar.ne
- marlowe-playground-client/src/Help.purs
- marlowe-playground-client/src/Marlowe/Blockly.purs
- marlowe-playground-client/src/Marlowe/Extended.purs
- marlowe-playground-client/src/Marlowe/Gen.purs
- marlowe-playground-client/src/Marlowe/Holes.purs
- marlowe-playground-client/src/Marlowe/Linter.purs
- marlowe-playground-client/src/Marlowe/Monaco.js
- marlowe-playground-client/src/Marlowe/Monaco.ts
- marlowe-playground-client/src/Marlowe/Parser.purs
- marlowe-playground-client/test/Marlowe/CompletionItemsTests.purs
This PR adds two constructs:
* `ConstantParam` (of type `Value`)
* `SlotParam` (of type `ExtendedTimeout`)
Originally, `Timeout` was simply a number, and `ExtendedTimeout` still accepts that, but also `SlotParam "string"`, which is a bit odd with `Term` and blockly, but it seems I got it to work more or less sensibly. I changed it in blockly to be a `string` instead of a number, and it will write a `SlotParam` if you write anything that doesn't parse as a number. Feels a bit like an easter egg, but the alternative was to adding a `Slot` type of block, and it seemed a worse solution, maybe we'll have to eventually.
I haven't added them to Haskell, or JavaScript, or added interface for instantiating in the simulator. There are Jira tickets for all of those in the pipeline, but I don't want …
> SCP-1792 - Add template variables to Extended Marlowe language and Blockly

- deployment/default.nix
Deployment to s3 only worked if your deployment region matched the
default set in `~/.aws/config`. That's now fixed.
- Branch
- PR
> Fixing a deployment bug.

- plutus-contract/src/Plutus/Trace/Effects/EmulatorControl.hs
- plutus-contract/src/Plutus/Trace/Effects/RunContract.hs
- plutus-contract/src/Plutus/Trace/Effects/RunContractPlayground.hs
- plutus-contract/src/Plutus/Trace/Effects/Waiting.hs
- plutus-contract/src/Plutus/Trace/Emulator.hs
- plutus-contract/src/Plutus/Trace/Emulator/ContractInstance.hs
- plutus-contract/src/Plutus/Trace/Emulator/System.hs
- plutus-contract/src/Plutus/Trace/Emulator/Types.hs
- plutus-contract/src/Plutus/Trace/Playground.hs
- plutus-contract/src/Plutus/Trace/Scheduler.hs
* Split the `SysCall` type in the emulator into two
* My end goal is to call `Plutus.Trace.Emulator.ContractInstance.runInstance` from the PAB, with different effect handlers than we have in the emulator
* This is much easier if the thread related operations in  `SysCall` are removed from the message related ones
* `runInstance` only uses the latter
* In the interest of having small PRs I'm going to split it up across several commits that can be reviewed individually
* This PR is a purely syntactical change in `plutus-contract/src/Plutus/Trace/Scheduler.hs` and propagated from there
- Branch
- PR
> SCP-1835: Split up 'SysCall'

- nix/pkgs/haskell/materialized-musl/.plan.nix/plutus-pab.nix
- nix/pkgs/haskell/materialized-unix/.plan.nix/plutus-pab.nix
- plutus-pab/app/Main.hs
- plutus-pab/plutus-pab.cabal
- plutus-pab/src/Cardano/ChainIndex/Server.hs
- plutus-pab/src/Cardano/ChainIndex/Types.hs
- plutus-pab/src/Cardano/SigningProcess/Server.hs
- plutus-pab/src/Cardano/SigningProcess/Types.hs
- plutus-pab/src/Plutus/PAB/App.hs
- plutus-pab/src/Plutus/PAB/MonadLoggerBridge.hs
- plutus-pab/src/Plutus/PAB/Monitoring.hs
- plutus-pab/src/Plutus/PAB/PABLogMsg.hs
**Description**:
Change `ChainIndex` and `SigningProcess` to use Tracer via `Freer.Log` (part of SCP-1687).
**Details**:
- Moved some definitions to local Type Module to resolve circular imports
- Additional minor refactorings
- Added some comments
-----
- Branch
- PR
> Plutus pab logging: ChainIndex / SigningProcess (SCP-1687)

- marlowe-playground-client/src/AppM.purs
- marlowe-playground-client/src/BlocklyComponent/State.purs
- marlowe-playground-client/src/Marlowe/Blockly.purs
- marlowe-playground-client/src/Marlowe/Gen.purs
- marlowe-playground-client/src/Marlowe/Holes.purs
- marlowe-playground-client/src/Marlowe/Linter.purs
- marlowe-playground-client/src/Marlowe/LinterText.purs
- marlowe-playground-client/src/Marlowe/Monaco.purs
- marlowe-playground-client/src/Marlowe/Parser.js
- marlowe-playground-client/src/Marlowe/Parser.purs
- marlowe-playground-client/src/MarloweEditor/State.purs
- marlowe-playground-client/test/Marlowe/CompletionItemsTests.purs
This PR modifies the `Term` data type to use `Location`s instead of `Range`s. This is a required step before being able to add warnings and static analysis to Blockly.
Initially the idea was to make `Term` polymorphic to not just `a` but also to a `loc`. 
but this data type spread to virtually all data types in Marlowe.Hole, introducing a lot of complexity just to guarantee at the type level that we always use the same Location type. Instead, this approach uses a Sum type in Location and runtime exceptions in the places that they are used to guarantee (at runtime) that we don't mix locations.
- Branch
- PR
> SCP-1832 Marlowe Playground Frontend: Refactor term to accept blockly locations (concrete type version)

- nix/pkgs/default.nix
Replace the iohkNix commitIdFromGitRepo with the one from nixpkgs
- Branch
- PR
> Use nixpgks commitIdFromGitRepo

- plutus-contract/src/Plutus/Trace/Effects/RunContract.hs
- plutus-contract/src/Plutus/Trace/Effects/RunContractPlayground.hs
- plutus-contract/src/Plutus/Trace/Emulator/ContractInstance.hs
- plutus-contract/src/Plutus/Trace/Emulator/Types.hs
- plutus-contract/src/Plutus/Trace/Scheduler.hs
* That way we can use `runThread` in other (non-emulator) contexts such as the PAB.
- Branch
- PR
> SCP-1836: Change "runInstance" to use only message related syscalls

- plutus-contract/src/Plutus/Trace/Effects/EmulatorControl.hs
- plutus-contract/src/Plutus/Trace/Emulator.hs
- plutus-contract/src/Plutus/Trace/Emulator/System.hs
- plutus-contract/src/Plutus/Trace/Playground.hs
- plutus-contract/src/Wallet/Emulator/MultiAgent.hs
- plutus-contract/src/Wallet/Emulator/Stream.hs
- plutus-contract/src/Wallet/Emulator/Types.hs
* `MultiAgentEffect` currently has emulator actions and emulator control actions
* We need to extract emulator control actions so that functions that only use regular emulator actions can also run in other contexts, such as the PAB
- Branch
- PR
> SCP-1847: Extract control effects from "MultiAgentEffect"

- marlowe-playground-client/src/MainFrame/State.purs
- marlowe-playground-client/src/SimulationPage/State.purs
- marlowe-playground-client/src/SimulationPage/Types.purs
- marlowe-playground-client/src/SimulationPage/View.purs
- marlowe-playground-client/src/Simulator.purs
- marlowe-playground-client/src/Wallet.purs
- marlowe-playground-client/test/Marlowe/ContractTests.purs
In preparation for template instantiation, it is necessary to refactor the types in Simulator so that we use Core Marlowe for the simulation phase and Extended Marlowe for the instantiation phase.
There are also some vestiges of previous functionalities that are no longer used and clutter the implementation. For example, there is an `oldContract` field which @hrajchert already flagged with a comment, there is functionality for removing inputs which is not accessible anywhere, and there are snippets of code that are meant to do the same thing but either are implemented slightly differently or are just duplicated.
This PR:
- Adds "Start simulation" to history (so that it is affected by "Undo")
- Unifies calls to SendToSimulator
- Cleans-up and removes several spurious vestiges in Simulator …
> SCP-1791 - Split Contract in simulator and clean-up

- nix/pkgs/haskell/materialized-musl/.plan.nix/plutus-metatheory.nix
- nix/pkgs/haskell/materialized-unix/.plan.nix/plutus-metatheory.nix
- plutus-core/generators/Language/PlutusCore/Generators/NEAT/Spec.hs
- plutus-metatheory/plutus-metatheory.cabal
- plutus-metatheory/src/Main.lagda
- plutus-metatheory/src/Opts.hs
- plutus-metatheory/src/Raw.hs
- plutus-metatheory/src/Untyped.hs
- plutus-metatheory/src/Untyped.lagda
- plutus-metatheory/src/Untyped.lagda.md
- plutus-metatheory/src/Untyped/Reduction.lagda
- plutus-metatheory/src/Untyped/Reduction.lagda.md
- plutus-metatheory/src/Untyped/RenamingSubstitution.lagda.md
- plutus-metatheory/src/Utils.lagda
- plutus-metatheory/test/TestDetailed.hs
- plutus-metatheory/test/TestNEAT.hs
- plutus-metatheory/test/TestSimple.hs
So far I have reinstated untyped evaluation in plc-agda. It takes a typed term, erases it, reduces it and then prints it out using my 'ugly printer'.
This is ok for testing against other plc-agda modes but to test against the plutus-core evaluator will require reusing plutus-core untyped machinery.
- Branch
- PR
> SCP-1823 untyped evaluation in plc-agda

- plutus-contract/src/Language/Plutus/Contract/Trace.hs
- plutus-contract/src/Plutus/Trace/Effects/RunContract.hs
- plutus-contract/src/Plutus/Trace/Emulator/ContractInstance.hs
- plutus-contract/src/Plutus/Trace/Emulator/Types.hs
- plutus-contract/src/Wallet/Emulator/MultiAgent.hs
* In each contract instance thread we only use a single agent and this doesn't change during the lifetime of the instance
* So we don't actually need `MultiAgentEffect` inside `runInstance`
* This is the last of the emulator changes, after this we can actually use `runInstance` from inside the PAB \o/
- Branch
- PR
> SCP-1848: Contract instance doesn't need MultiAgent effect

- default.nix
- nix/pkgs/fix-purty/default.nix
- nix/pkgs/fix-stylish-haskell/default.nix
- nix/tests/default.nix
- nix/tests/purty.nix
- nix/tests/stylish-haskell.nix
Some time ago, I changed them to use `fd`, which is significantly
faster. However, `fd` recently changed its behaviour: it used to be that
it matched `find`, whereby it would keep going if any individual `exec`
command failed. Now it stops. This interacts badly with our formatters,
which don't like all the files in our repo, and occasionally fail on one
or the other. We would prefer this not to stop them formatting the rest
of the files!
So we switch back to using `find`, which is slower but does what we
want.
I also shared the fixing script between the shell function and the CI
check, so they will line up better.
(Annals of failed changes: originally this PR included a change to use `execdir`, because if `stylish-haskell` is run from the file's directory instead of the project root then …
> Change the formatter fixing scripts to use find again

- marlowe-playground-client/src/Help.purs
- marlowe-playground-client/src/Marlowe/Parser.js
- marlowe/doc/marlowe-data.adoc
- marlowe/doc/marlowe-step-by-step.adoc
- marlowe/src/Language/Marlowe/Semantics.hs
This PR solves the following bug:
If you create a new Marlowe contract and type a valid but incomplete top level contract such as 
```
Assert TrueObs 
```
then the parser yield's an undefined value, which ends up causing a runtime error somewhere else in the code.
With this PR now it produces a parsing error (ideally this should be solved in the grammar, but this checks whatever reason the parser cant produce an output)
- Branch
- PR
> Marlowe Playground Client: Fix runtime error on incomplete top level contract

- plutus-pab/app/Main.hs
- plutus-pab/src/Cardano/Node/API.hs
- plutus-pab/src/Cardano/Node/Client.hs
- plutus-pab/src/Cardano/Node/Follower.hs
- plutus-pab/src/Cardano/Node/Mock.hs
- plutus-pab/src/Cardano/Node/RandomTx.hs
- plutus-pab/src/Cardano/Node/Server.hs
- plutus-pab/src/Cardano/Node/Types.hs
- plutus-pab/src/Cardano/Protocol/ChainEffect.hs
- plutus-pab/src/Cardano/Protocol/FollowerEffect.hs
- plutus-pab/src/Plutus/PAB/Effects/MultiAgent.hs
- plutus-pab/src/Plutus/PAB/MockApp.hs
- plutus-pab/src/Plutus/PAB/PABLogMsg.hs
**TL;DR**: Update Node Mock Server to use the tracer from iohk-monitoring
- Introduce Cardano.Node.Types.MockServerLogMsg
- Refactor Cardano.Node.Server.main
----
- Branch
- PR
> SCP-1687: use freer logging in Cardano.Node.Server

- plutus-metatheory/src/Type/CC.lagda.md
- plutus-metatheory/src/Type/CK.lagda.md
- plutus-metatheory/src/Type/Reduction.lagda.md
- plutus-metatheory/src/Type/ReductionC.lagda.md
- plutus-metatheory/src/Type/ReductionF.lagda.md
- plutus-metatheory/src/Type/ReductionS.lagda.md
- plutus-metatheory/src/index.lagda.md
In this PR 
1. refactor reduction, progress, val 'xor' reduction, and determinism proofs to use frames.
2. Define CC machine.
For later:
3. Prove equivalence of CC machine and reduction.
4. Refactor CK machine to be relational.
5. Prove equivalence of CC and CK machine.
- Branch
- PR
> SCP-1890 refactor type reduction machinery + implement CC machine

- plutus-core/exe/Main.hs
- plutus-core/plutus-core.cabal
This improves the timing feature in the plc command, so it should now be possible to quickly get reasonable benchmark times without having to set up lots of Criterion stuff.  You can now say `plc evaluate <prog> -X <N>` to run a program N times and see the mean execution time.  You can also use `-x` for 100 repetitions.
This turned out to be more difficult than I expected.  I had a version using `Criterion.Measurement.measure` (see the [documentation](http://hackage.haskell.org/package/criterion-measurement-0.1.2.0/docs/Criterion-Measurement.html)), which evaluates a function a given number of times and returns various statistics, including the total execution time.  However, this gives odd results.  It turns out that if you repeatedly execute a PLC program on the CEK machine the first …
> Kwxm/improve plc timing  (SCP-1872)

- marlowe-playground-client/src/HaskellEditor/State.purs
- marlowe-playground-client/src/HaskellEditor/Types.purs
- marlowe-playground-client/src/HaskellEditor/View.purs
- marlowe-playground-client/src/JavascriptEditor/State.purs
- marlowe-playground-client/src/JavascriptEditor/Types.purs
- marlowe-playground-client/src/JavascriptEditor/View.purs
- marlowe-playground-client/src/Marlowe/Extended.purs
- marlowe-playground-client/src/Marlowe/Linter.purs
- marlowe-playground-client/src/MarloweEditor/BottomPanel.purs
- marlowe-playground-client/src/MarloweEditor/State.purs
- marlowe-playground-client/src/MarloweEditor/Types.purs
- marlowe-playground-client/src/SimulationPage/State.purs
- marlowe-playground-client/src/SimulationPage/Types.purs
- marlowe-playground-client/src/SimulationPage/View.purs
- marlowe-playground-client/src/StaticAnalysis/BottomPanel.purs
- marlowe-playground-client/src/StaticAnalysis/CloseAnalysis.purs
- marlowe-playground-client/src/StaticAnalysis/Reachability.purs
- marlowe-playground-client/src/StaticAnalysis/StaticTools.purs
- marlowe-playground-client/src/StaticAnalysis/Types.purs
- marlowe-playground-client/static/css/panels.scss
This PR adds the instantiation mechanism to the UI, both to the Marlowe Editor's static analysis (before analysis) and the Simulation (before starting simulation).
It was necessary to add a "Clear" button for Marlowe Editor's static analysis, because otherwise you can only set the parameters onces. You can still do that, but if you add new parameters you need to `Clear` and instantiate the new ones. This also allows the user to clear the results from reachability analysis without starting a new analysis.
For Haskell and JavaScript, we are going to need an initialisation phase, with Marlowe we can get away with having the template instantiation update automatically with the contract.
Example contract with parameters:
```haskell
When [Case (Deposit (Role "alice") (Role "alice") (Token "" …
```
> SCP-1849 - Add template instantiation mechanism to Marlowe UI in playground

- plutus-pab/app/Main.hs
- plutus-pab/src/Cardano/ChainIndex/Server.hs
- plutus-pab/src/Cardano/ChainIndex/Types.hs
- plutus-pab/src/Cardano/Node/Mock.hs
- plutus-pab/src/Cardano/Wallet/Server.hs
- plutus-pab/src/Cardano/Wallet/Types.hs
- plutus-pab/src/Control/Monad/Freer/Extra/Log.hs
- plutus-pab/src/Plutus/PAB/Monitoring.hs
runStderrLog should already have been replaced with handleLogMsgTrace
everywhere when switchign to the simple-freer based logging but some
occuoccurrences were still left.
This PR removes all of them and also drops `runStderrLog` itself since
it is now redundant.
- Branch
- PR
> SCP-1903: Remove runStderrLog

- marlowe-playground-client/src/BlocklyComponent/State.purs
- marlowe-playground-client/src/BlocklyEditor/State.purs
- marlowe-playground-client/src/BlocklyEditor/Types.purs
- marlowe-playground-client/src/HaskellEditor/State.purs
- marlowe-playground-client/src/JavascriptEditor/State.purs
- marlowe-playground-client/src/Main.purs
- marlowe-playground-client/src/MainFrame/State.purs
- marlowe-playground-client/src/MarloweEditor/State.purs
- marlowe-playground-client/src/SimulationPage/State.purs
This PR solves a bug in where every time you refresh the browser in the blockly editor you lose the current contract.
It also changed the place where we store the contracts from local storage to session storage. This way we can have multiple tabs of the browser working on different contracts at the same time, without one disrupting another.
I've used the same key for Marlowe and Blockly editors as they should be interchangeable, and the session is stored as marlowe code, not XML nodes.
- Branch
- PR
> SCP-1648 Marlowe Playground Client: Fix blockly losing its state after refresh

- nix/pkgs/haskell/materialized-musl/.plan.nix/plutus-pab.nix
- nix/pkgs/haskell/materialized-unix/.plan.nix/plutus-pab.nix
- plutus-pab/app/Cli.hs
- plutus-pab/app/Command.hs
- plutus-pab/app/CommandParser.hs
- plutus-pab/app/Main.hs
- plutus-pab/plutus-pab.cabal
Split the (pretty big) Main module up:
- `Command` : data type representing all available commands
- `CommandParser`: command line parser for all commands
- `Cli`: command interpreter for all commands
Nothing too fancy going on here. I just find it helps to separate concerns and narrow down things. 
----------------
- Branch
- PR
> plutus-pab: split Main

- freer-extras/freer-extras.cabal
- nix/pkgs/haskell/materialized-musl/.plan.nix/freer-extras.nix
- nix/pkgs/haskell/materialized-unix/.plan.nix/freer-extras.nix
```
Warning: File listed in freer-extras/freer-extras.cabal file does not exist: CHANGELOG.md
```
----
- Branch
- PR
> freer-extras: drop Changelog reference from cabal

- marlowe-playground-client/src/HaskellEditor/State.purs
- marlowe-playground-client/src/HaskellEditor/Types.purs
- marlowe-playground-client/src/HaskellEditor/View.purs
- marlowe-playground-server/app/PSGenerator.hs
- marlowe-playground-server/contracts/ContractForDifference.hs
- marlowe-playground-server/contracts/CouponBondGuaranteed.hs
- marlowe-playground-server/contracts/Escrow.hs
- marlowe-playground-server/contracts/EscrowWithCollateral.hs
- marlowe-playground-server/contracts/Example.hs
- marlowe-playground-server/contracts/Option.hs
- marlowe-playground-server/contracts/Swap.hs
- marlowe-playground-server/contracts/ZeroCouponBond.hs
- marlowe/marlowe.cabal
- marlowe/src/Language/Marlowe/Extended.hs
- marlowe/src/Language/Marlowe/Pretty.hs
- nix/pkgs/haskell/materialized-musl/.plan.nix/marlowe.nix
- nix/pkgs/haskell/materialized-unix/.plan.nix/marlowe.nix
This PR adds support to the Haskell tab for Extended Marlowe, in particular:
- Implements Haskell version of Extended Marlowe (Extended.hs)
- Disables analyse buttons when not compiled
- Adds "Clear" button to Static Analysis
- Updates template parameters on compilation
- Adapts Haskell examples to use Extended Marlowe (and other dependencies like PSGenerator)
Example:
```haskell
{-# LANGUAGE OverloadedStrings #-}
module Escrow where
import           Language.Marlowe.Extended
main :: IO ()
main = print . pretty $ contract
{- What does the vanilla contract look like?
- if Alice and Bob choose
- and agree: do it
- and disagree: Carol decides
- Carol also decides if timeout after one choice has been made;
- refund if no choices are made.
-}
contract :: Contract
contract = When [Case (Deposit …
```
> SCP-1790 - Add "Extended Marlowe" types in Haskell language

- marlowe-dashboard-client/src/Contract/State.purs
- marlowe-dashboard-client/src/Contract/View.purs
- marlowe-dashboard-client/src/MainFrame/Lenses.purs
- marlowe-dashboard-client/src/MainFrame/State.purs
- marlowe-dashboard-client/src/MainFrame/Types.purs
- marlowe-dashboard-client/src/MainFrame/View.purs
- marlowe-dashboard-client/src/Template/Lenses.purs
- marlowe-dashboard-client/src/Template/Library.purs
- marlowe-dashboard-client/src/Template/State.purs
- marlowe-dashboard-client/src/Template/Types.purs
- marlowe-dashboard-client/src/Template/Validation.purs
- marlowe-dashboard-client/src/Template/View.purs
- marlowe-dashboard-client/src/WalletData/Types.purs
- marlowe-dashboard-client/src/WalletData/Validation.purs
- marlowe-dashboard-client/src/WalletData/View.purs
- marlowe-dashboard-client/static/css/main.css
- marlowe-dashboard-client/tailwind.config.js
- web-common-marlowe/src/Marlowe/Extended.purs
- web-common/src/Halogen/Extra.purs
Work in progress, but this seems as good a moment as any to open a PR... A few comments:
- It's not possible yet, in the contract setup, to create a contact and immediately assign it to a role - that can wait for another PR. Otherwise, all the contract setup workflow is in place.
- Validation of number inputs is a pain. I had the same problem with the Plutus playground and never quite got to the bottom of it. But I think we've probably got enough validation here for the prototype.
- It looks as though there is a proper `Template.State` submodule, but there isn't. I've just separated out some template-related `MainFrame.State` code into a separate module for readability. Compare with `Contract.State`. Not sure which way is better. 🤷‍♂️ 
@palas, I've changed `Marlowe.Extended` slightly: …
> Adding wireframe contract setup workflow.

- plutus-core/exe/Main.hs
Removed an unnecessary call to `runQuote` when "debruij-ning" terms in the plc-exe.
- Branch
- PR
> [plutus-core/exe] Remove small unnecessary code

- plutus-contract/src/Language/Plutus/Contract/Schema.hs
- plutus-contract/src/Plutus/Trace/Effects/RunContract.hs
- plutus-contract/test/Spec/Contract.hs
* Change `activeEndpoints` to return a list of `ActiveEndpoint` values, which include metadata
* Also fix a bug in `activeEndpoints`  where it would return the previously active endpoints, not the currently active ones.
- Branch
- PR
> SCP-1944: Active endpoints

- nix/pkgs/haskell/haskell.nix
- nix/pkgs/haskell/materialized-musl/.plan.nix/plutus-core.nix
- nix/pkgs/haskell/materialized-unix/.plan.nix/plutus-core.nix
- plutus-core/plutus-core.cabal
We're having problems in CI due to timeouts during `plutus-core:plutus-core-cost-model-tests`.  This PR turns the test into a benchmark so that it doesn't get run in CI but we can still run it manually.  See SCP-1956.
- Branch
- PR
> Turn the cost model tests into a benchmark

- nix/pkgs/haskell/materialized-musl/.plan.nix/plutus-pab.nix
- nix/pkgs/haskell/materialized-unix/.plan.nix/plutus-pab.nix
- plutus-pab/app/Cli.hs
- plutus-pab/app/Main.hs
- plutus-pab/plutus-pab.cabal
- plutus-pab/src/Cardano/ChainIndex/ChainIndex.hs
- plutus-pab/src/Cardano/ChainIndex/Server.hs
- plutus-pab/src/Cardano/Metadata/Server.hs
- plutus-pab/src/Cardano/Node/Mock.hs
- plutus-pab/src/Cardano/Node/Server.hs
- plutus-pab/src/Cardano/SigningProcess/Server.hs
- plutus-pab/src/Cardano/Wallet/Mock.hs
- plutus-pab/src/Cardano/Wallet/Server.hs
- plutus-pab/src/Plutus/PAB/App.hs
- plutus-pab/src/Plutus/PAB/Monitoring/Config.hs
- plutus-pab/src/Plutus/PAB/Monitoring/MonadLoggerBridge.hs
- plutus-pab/src/Plutus/PAB/Monitoring/Monitoring.hs
- plutus-pab/src/Plutus/PAB/Monitoring/PABLogMsg.hs
- plutus-pab/src/Plutus/PAB/Monitoring/Util.hs
- plutus-pab/src/Plutus/PAB/Webserver/Handler.hs
- plutus-pab/src/Plutus/PAB/Webserver/Server.hs
- plutus-pab/src/Plutus/PAB/Webserver/WebSocket.hs
Introduce better encapulsation for everything monitoring/logging related
under Plutus.PAB.Monitoring.
- Group some modules under `PAB.Monitoring`
- Move monadLoggerTracer to `Monitoring.MonadLoggerBridge`
- Use `LM` (*L*ogging and *M*onitoring) qualified imports
- Branch
- PR
> plutus-pab: Monitoring module

- doc/plutus-doc.cabal
- plutus-benchmark/plutus-benchmark.cabal
- plutus-contract/plutus-contract.cabal
- plutus-core/plutus-core.cabal
- plutus-errors/plutus-errors.cabal
- plutus-ledger-api/plutus-ledger-api.cabal
- plutus-ledger/plutus-ledger.cabal
- plutus-pab/plutus-pab.cabal
- plutus-tx-plugin/plutus-tx-plugin.cabal
- plutus-tx/plutus-tx.cabal
It is difficult to maintain `other-extensions` so let's remove them.
- Branch
- PR
> Get rid of 'other-extensions' in .cabal files

- nix/pkgs/haskell/materialized-musl/.plan.nix/plutus-core.nix
- nix/pkgs/haskell/materialized-unix/.plan.nix/plutus-core.nix
- plutus-core/plutus-core.cabal
- plutus-core/plutus-ir/Language/PlutusIR/Compiler/Error.hs
PIR.Compiler.Error was missing from cabal so it was failing to compile all this time. Fix its compilation.
- Branch
- PR
> Fix small compilation problem for PIR.Compiler.Error

- marlowe-playground-client/src/Blockly/Internal.js
- marlowe-playground-client/src/Blockly/Internal.purs
- marlowe-playground-client/src/BlocklyComponent/State.purs
- marlowe-playground-client/src/BlocklyComponent/Types.purs
- marlowe-playground-client/src/BlocklyComponent/View.purs
- marlowe-playground-client/src/BlocklyEditor/State.purs
- marlowe-playground-client/src/BlocklyEditor/Types.purs
- marlowe-playground-client/src/BlocklyEditor/View.purs
- marlowe-playground-client/src/MainFrame/State.purs
- marlowe-playground-client/static/css/modal.scss
- web-common/src/Halogen/ElementVisible.purs
- web-common/src/Web/DOM/IntersectionObserver.js
- web-common/src/Web/DOM/IntersectionObserver.purs
- web-common/src/Web/DOM/ResizeObserver.purs
This PR resolves 2 visual errors with Blockly. The first was that the toolbar had more visibility than the overlay, so you could click it when you had a modal.
**Blockly editor before**
**Blockly editor now**
The second problem happened when you were modifying a field and you switched views. A visual indicator was stuck on the screen. I used the IntersectionObserver to detect when the editor was no longer visible and called `blockly.hideChaff()`
You can see the changes in https://hernan.marlowe.iohkdev.io/
- Branch
- PR
> SCP-1551 Marlowe Playground Client: fix blockly visual problems

- marlowe-playground-client/default.nix
- marlowe-playground-client/entry.js
- marlowe-playground-client/package-lock.json
- marlowe-playground-client/package.json
- marlowe-playground-client/src/Blockly/Events.js
- marlowe-playground-client/src/Blockly/Events.purs
- marlowe-playground-client/src/Blockly/Internal.js
- marlowe-playground-client/src/Blockly/Internal.purs
- marlowe-playground-client/src/Blockly/Toolbox.purs
- marlowe-playground-client/src/Blockly/Types.purs
- marlowe-playground-client/src/BlocklyComponent/State.purs
- marlowe-playground-client/src/BlocklyComponent/Types.purs
- marlowe-playground-client/src/BlocklyEditor/State.purs
- marlowe-playground-client/src/BlocklyEditor/View.purs
- marlowe-playground-client/src/Halogen/ActusBlockly.purs
- marlowe-playground-client/src/Halogen/BlocklyCommons.purs
- marlowe-playground-client/src/MainFrame/View.purs
- marlowe-playground-client/src/Marlowe/ActusBlockly.purs
- marlowe-playground-client/src/Marlowe/Blockly.purs
- marlowe-playground-client/test/Blockly/Headless.js
This PR implements blockly holes, which is a way to suggest to the user what blocks could fit into the selected block.
I had to upgrade blockly to the latest version (and while I was at it modify the source to the official one) as it was necessary for defining the Toolbox as JSON. Then I re-implement the toolbox from XML to Json and finally added the mechanism to modify the Toolbox with the hole information.
As a "weird" usability issue, the names of the toolbox categories correspond to the name of the holes rather than the name of the block. But trying to change that broke the CodeToBlocklyToCode quick check, as the names of the holes is tightly coupled to the block definition, and the quick check verifies that the names of the holes are preserved.
The code is deployed here: …
> SCP-1861 Marlowe Playground Client: Implement holes in blockly

- marlowe-playground-client/src/BlocklyEditor/BottomPanel.purs
- marlowe-playground-client/src/BlocklyEditor/State.purs
- marlowe-playground-client/src/MarloweEditor/BottomPanel.purs
- marlowe-playground-client/src/MarloweEditor/State.purs
- marlowe-playground-client/src/MarloweEditor/Types.purs
This PR Fixes a bug both in Marlowe and Blockly were you were able to select a static analysis for a contract with holes. Because the handleAction was using `for_` with Maybe's, the code didn't execute, but also didn't warn you about the problem.
Now it shows the following message:
I also took the opportunity to tidy up the processMarloweCode and editorSetMarkers
- Branch
- PR
> SCP-1929 Marlowe Playground Client: dont do static analysis with holes

- marlowe-dashboard-client/webpack.config.js
- plutus-pab-client/webpack.config.js
This PR fixes the dashboard client webpack configuration so that it doesn't crash if it has a problem with the web socket.
- Branch
- PR
> Avoid crashing when the FE can’t connect to the web socket

- plutus-metatheory/src/Type/CC.lagda.md
- plutus-metatheory/src/Type/ReductionC.lagda.md
- plutus-metatheory/src/Type/ReductionCI.lagda.md
some properties:
Refactoring:
```
M -> M'
-----------------
E [ M ] ~> E [ M']
```
where `->` is a relation containing only beta reduction on types.
- Branch
- PR
> SCP-2009 towards successful EC reduction implies successful CC execution for types

- plutus-playground-client/package-lock.json
- web-common/src/Analytics.js
- web-common/src/Analytics.purs
I've taken the low-maintenance approach for this, by
keeping the way we track invididual events to Google Analytics, and then
massaging that data into Segment's shape.
An obvious alternative would be to have a second set of events (and
maybe even a second typeclass), which represents something more
bespoke, but keeping two descriptions of analytics events seems like
more of a maintenance problem than it's worth.
- Branch
- PR
> Adding in fine-grined Segment Event tracking.

- .gitignore
- default.nix
- marlowe-dashboard-client/README.md
- marlowe-dashboard-client/plutus-pab.yaml
- marlowe-dashboard-client/webpack.config.js
- plutus-pab-client/default.nix
- shell.nix
This PR adds two new nix scripts to the PAB: one to migrate the database, and another to start all servers.
It also updates the Marlowe Dashboard README, with instructions to invoke these to get the backend up and running easily.
> Updating the Marlowe dashboard README and adding some useful PAB nix scripts.

- marlowe-dashboard-client/src/Contract/View.purs
- marlowe-dashboard-client/src/Icons.purs
- marlowe-dashboard-client/src/MainFrame/Lenses.purs
- marlowe-dashboard-client/src/MainFrame/State.purs
- marlowe-dashboard-client/src/MainFrame/Types.purs
- marlowe-dashboard-client/src/MainFrame/View.purs
- marlowe-dashboard-client/src/Pickup/State.purs
- marlowe-dashboard-client/src/Pickup/Types.purs
- marlowe-dashboard-client/src/Pickup/View.purs
- marlowe-dashboard-client/src/Play/Lenses.purs
- marlowe-dashboard-client/src/Play/State.purs
- marlowe-dashboard-client/src/Play/Types.purs
- marlowe-dashboard-client/src/Play/View.purs
- marlowe-dashboard-client/src/StaticData.purs
- marlowe-dashboard-client/src/Template/Validation.purs
- marlowe-dashboard-client/src/Template/View.purs
- marlowe-dashboard-client/src/WalletData/Lenses.purs
- marlowe-dashboard-client/src/WalletData/Types.purs
- marlowe-dashboard-client/src/WalletData/Validation.purs
- marlowe-dashboard-client/src/WalletData/View.purs
The original plan was to identify wallets by their public key. But in discussions earlier this week we realised we were going to need a "wallet companion" contract running for each wallet (listening for changes to that wallet in advance of other contracts being started). The ID of this companion contract is what will primarily be used to identify wallets on the frontend, but we still need the public key as well. This PR changes the data model and the wallet generation/pickup workflow accordingly.
While I was at it, I removed the GDPR screen (since it's been confirmed we don't need this) and tidied up the icons based on the new designs.
> Marlowe redo wallet workflow

- web-common/src/Analytics.js
Fix on the `if` that checks whether `analytics` is available (currently crashes)
- Branch
- PR
- ~[ ] Reviewer requested~ Too simple and urgent
- ~[ ] Someone approved it~ Too simple and urgent
> Fix analytics check

- plutus-pab/src/Cardano/Metadata/Mock.hs
- plutus-pab/src/Cardano/Metadata/Server.hs
- plutus-pab/src/Plutus/PAB/Core/ContractInstance.hs
* Reduce the logging output of the PAB on info level a little bit
* It still produces a lot of noise (mostly coming from the mock node I think)
- Branch
- PR
> PAB: Clean up some log messages

- freer-extras/src/Control/Monad/Freer/Extras/Modify.hs
- plutus-contract/src/Language/Plutus/Contract/Types.hs
- plutus-contract/src/Plutus/Trace/Emulator.hs
- plutus-contract/src/Plutus/Trace/Emulator/ContractInstance.hs
- plutus-contract/src/Plutus/Trace/Playground.hs
- plutus-contract/src/Wallet/Emulator/MultiAgent.hs
- plutus-contract/src/Wallet/Emulator/Stream.hs
- plutus-pab/src/Cardano/Wallet/Mock.hs
- plutus-pab/src/Plutus/PAB/Effects/MultiAgent.hs
While going through the code, this bit jumped out and it was too tempting to try to improve it. This approach might very well already have been considered, so feel free to close this in that case.
- Branch
- PR
> Replace raiseEndN's with general raiseEnd

- plutus-core/plc/Main.hs
Interchanging the `-r` and `-R` options in the plc command for consistency with `-x` and `-X` (default -> lower case).
- Branch
- PR
> Interchange -r and -R options in plc command

- shell.nix
I think since it's a python package it messes around with
`propagatedBuildDependencies`, and as a result we end up with systemd
binaries in the shell, which we don't want as it can interfere with
people's use of their own system's systemd!
- Branch
- PR
> Remove yubikey-manager from the shell, it somehow pulls in a systemd

- .gitignore
I use `direnv` with `use nix` in `.envrc` and this puts cached derivations in the `.direnv` directory.
> Add .direnv/ to .gitignore

- web-common-marlowe/src/Marlowe/Slot.purs
This PR adds Slot to DateTime utilities to the marlowe web commons. 
- Branch
- PR
> Add Slot to datetime converters

- nix/lib/haddock-combine.nix
Following this example: https://github.com/input-output-hk/ouroboros-network/blob/2068d091bc7dcd3f4538fb76f1b598f219d1e0c8/scripts/haddocs.sh#L87 we add a step after the haddock generation to write a combined `doc-index.json` so that searching works! Note that for searching to work locally, you need to open the HTML files through a webserver (if we wanted to serve the docs via a webserver I can look into that, perhaps as a separate item?).
Fixes SCP-1900
I'm just assuming this will work when the docs get pushed; I'm hoping I can check this via one of the CI actions?
- Branch
- PR
> SCP-1900: Build combined doc-index.json

- marlowe-playground-client/src/MainFrame/State.purs
- marlowe-playground-client/src/MainFrame/Types.purs
- marlowe-playground-client/src/MainFrame/View.purs
- marlowe-playground-client/src/Marlowe/Gists.purs
- marlowe-playground-client/src/MarloweEditor/BottomPanel.purs
- marlowe-playground-client/src/MarloweEditor/State.purs
- marlowe-playground-client/src/MarloweEditor/Types.purs
- marlowe-playground-client/src/MarloweEditor/View.purs
- marlowe-playground-client/src/SimulationPage/State.purs
- marlowe-playground-client/src/SimulationPage/Types.purs
- marlowe-playground-client/src/StaticData.purs
- marlowe-playground-client/static/css/panels.scss
- web-common-marlowe/src/Marlowe/Extended.purs
Adds a metadata editor to a bottom tab in the Marlowe editor, and it adds metadata to the global state and saves it when publishing gists and local storage. There are a couple of to-dos that I have written in the comments and I have assigned them new tickets.
Since meta-data is saved, we do not add and remove fields automatically, we have buttons for adding and removing fields, but we do hint to the fields that exist in the contract.
- Branch
- PR
> SCP-1793 - Add metadata to Marlowe editor in Playground

- deployment/morph/configurations.nix
- deployment/morph/default-machine.nix
- deployment/terraform/templates/default_configuration.nix
These are some first *small* steps in improving parts of the deployment:
- Use nixpkgs pinned via `niv`: We don't want to use different nixpkgs versions so instead of hard-coding some nixpkgs url the deployments should use the nixpkgs version from `nix/sources.json`
- Enable path substitution for deployments (*)
(*) Unfortunately this doesn't really quite work yet. We are currently running into a bug with the deployment which is caused by Nix leaking file descriptors. As a result the target starts fetching binaries from cache.nixos.org and hydra.iohk.io until after some time file descriptors run out and there is an error - After that the fallback is that the deployment machine is scp'ing all store paths again. The problem is now being worked on but unfortunately all workarounds i tried …
> Deployment fixes

- marlowe-playground-client/src/MarloweEditor/BottomPanel.purs
- marlowe-playground-client/static/css/panels.scss
This PR applies the CSS grid layout to the form for editing metadata, so that fields and buttons are aligned.
- Branch
- PR
> SCP-2025 - Even out the layout of the metadata form

- example/README.md
Because there is "example-exe" and "example-test" the "cabal v2-run" command gives an error:
```
cabal: The run command is for running a single executable at once. The target
'' refers to the package example-0.1.0.0 which includes the executable
'example-exe' and the test suite 'example-test'.
```
- Branch
- PR
> fix "cabal v2-run" commands in example

- nix/docs.nix
- nix/pkgs/default.nix
- nix/pkgs/serve-dir/default.nix
- shell.nix
Specifically so we can view the haddocks (and make use of the search
capability).
Related to SCP-1900.
@gilligan Adding you as a reviewer so you can let me know if I've done this nix stuff in a nice way ... :) Very happy to change/receive some suggestions on how to do it better.
- Branch
- PR
> Script to spin up a webserver for the docs

- nix/docs.nix
- nix/pkgs/default.nix
- nix/pkgs/serve-dir/default.nix
- shell.nix
Simpler version of https://github.com/input-output-hk/plutus/pull/2858 that doesn't build the docs on shell entry anymore; just writes a script that both builds _and_ serves.
I just moved everything into docs to avoid over-complicating it.
Hope this makes sense :)
- Branch
- PR
> Don't build docs on shell entry; simple script to build and serve docs

- plutus-core/plutus-core/src/PlutusCore/Evaluation/Machine/Ck.hs
- plutus-core/untyped-plutus-core/src/UntypedPlutusCore/Evaluation/Machine/Cek.hs
- plutus-core/untyped-plutus-core/src/UntypedPlutusCore/Evaluation/Machine/Cek/Internal.hs
I was looking at GHC Core and realized that most constraints in the machines are redundant. This PR fixes that.
> [Evaluation] Dropped redundant constraints

- marlowe-playground-client/src/BottomPanel/View.purs
- marlowe-playground-client/src/ConfirmUnsavedNavigation/View.purs
- marlowe-playground-client/src/Halogen/Classes.purs
- web-common/src/Bootstrap.purs
The Plutus playground view depended on Bootstrap's `d-none` class, which was changed to `hidden` for the Marlowe playground. This fix changes it back, and removes the Marlowe playground's dependency on the `web-commom/Bootstrap` module.
> Fixing some CSS in the playgrounds.

- plutus-pab-client/config.nix
- plutus-pab-client/webpack.config.js
- plutus-pab/README.md
To reflect the demo scripts changes in 63493b4cb7c7ea53eee4825e200caef60cc4f55a.
I'm not sure if these changes make sense, or users are supposed to tweak their own demo scripts.
But the current `plutus-pab` README instructions aren't working and I think we should do something about it.
- Branch
- PR
> Update PAB ports & demo doc

- plutus-core/generators/PlutusCore/Generators/Internal/Denotation.hs
- plutus-core/plutus-core/examples/PlutusCore/Examples/Builtins.hs
- plutus-core/plutus-core/src/PlutusCore/Builtins.hs
- plutus-core/plutus-core/src/PlutusCore/Constant/Meaning.hs
- plutus-core/plutus-core/src/PlutusCore/Evaluation/Machine/Ck.hs
- plutus-core/plutus-core/src/PlutusCore/Flat.hs
- plutus-core/plutus-core/src/PlutusCore/Lexer.x
- plutus-core/plutus-core/src/PlutusCore/Parser/Internal.hs
- plutus-core/plutus-core/test/Evaluation/ApplyBuiltinName.hs
- plutus-core/plutus-core/test/Evaluation/DynamicBuiltins/MakeRead.hs
- plutus-core/plutus-core/test/Evaluation/Spec.hs
- plutus-core/untyped-plutus-core/test/Evaluation/ApplyBuiltinName.hs
- plutus-core/untyped-plutus-core/test/Evaluation/Machines.hs
- plutus-core/untyped-plutus-core/test/Spec.hs
- plutus-ledger-api/src/Plutus/V1/Ledger/Api.hs
This removes the `DynamicPart` part of the meaning of a built-in function, since we no longer need this extensibility as we were only using it for tracing and now we handle tracing differently.
> [Builtins] [Refactoring] Removed 'DynamicPart'

- marlowe-playground-client/src/BlocklyEditor/BottomPanel.purs
- marlowe-playground-client/src/BlocklyEditor/View.purs
- marlowe-playground-client/src/Halogen/Classes.purs
- marlowe-playground-client/src/HaskellEditor/View.purs
- marlowe-playground-client/src/JavascriptEditor/View.purs
- marlowe-playground-client/src/MainFrame/View.purs
- marlowe-playground-client/src/MarloweEditor/BottomPanel.purs
- marlowe-playground-client/src/Pretty.purs
- marlowe-playground-client/src/SimulationPage/BottomPanel.purs
- marlowe-playground-client/src/SimulationPage/View.purs
- marlowe-playground-client/src/StaticAnalysis/BottomPanel.purs
- marlowe-playground-client/src/Wallet.purs
- marlowe-playground-client/static/css/main.scss
- marlowe-playground-client/static/css/panels.scss
This PR displays the metadata in the simulator and instantiation form:
- Adds explanation to the places where it is relevant
- Adds explanation to the hints (abbr) that already existed for roles
- Fixes several glitches in the CSS of the simulator (in order to make it more responsive)
- Branch
- PR
> SCP-2021 - Add metadata to simulator

- marlowe-playground-client/README.md
- marlowe-playground-client/src/Marlowe/Linter.purs
- marlowe-playground-client/src/Marlowe/LinterText.purs
- marlowe-playground-client/src/Marlowe/Monaco.purs
- marlowe-playground-client/src/MarloweEditor/State.purs
This PR changes the function that calculates the metadata needed (extracts metadata hints) to support holes.
- We reuse the linting function for efficiency and to avoid extra boilerplate
- Additionally, now we don't update the metadata hints unless the contract parses (because it is probably more useful to the user this way)
- Also updates the command for running the server in the `README.md` of `marlowe-playground-client`
- Branch
- PR
> SCP-2012 - Get metadata hints from function that supports holes

- plutus-benchmark/nofib/exe/Main.hs
- plutus-core/plc/Main.hs
- plutus-core/untyped-plutus-core/src/UntypedPlutusCore/Evaluation/Machine/Cek/ExBudgetMode.hs
The nofib-exe program has an option to compile its examples from Haskell and then output them as textual PLC.  This was producing programs that couldn't be executed, I think because I had failed to un-DeBruijnify them.  This should fix that, although I'm currently rather confused about all the possible formats.  I'll need to sleep on that before merging.
- Branch
- PR
> Kwxm/fix nofib exe output problem (SCP-1896)

- marlowe-dashboard-client/src/Contract/Lenses.purs
- marlowe-dashboard-client/src/Contract/State.purs
- marlowe-dashboard-client/src/Contract/Types.purs
- marlowe-dashboard-client/src/Contract/View.purs
- marlowe-dashboard-client/src/ContractHome/Lenses.purs
- marlowe-dashboard-client/src/ContractHome/State.purs
- marlowe-dashboard-client/src/ContractHome/Types.purs
- marlowe-dashboard-client/src/ContractHome/View.purs
- marlowe-dashboard-client/src/Marlowe/Execution.purs
- marlowe-dashboard-client/src/Play/Lenses.purs
- marlowe-dashboard-client/src/Play/State.purs
- marlowe-dashboard-client/src/Play/View.purs
- marlowe-dashboard-client/src/Template/View.purs
This PR consists of three changes:
* It changes how we manage the current step of a contract. Before we were using a field in the Contract.State now we are counting the step history and renamed the field so that it indicates which step is the selected one (not using that info for the moment)
* It fixes a problem in the extractNamedAction that was using minSlot to calculate if a step had timeout (need review by @nau) 
* It adds a "hardcoded" way to advance the contract. We are not calling the PAB yet and we are assuming that the InputTransaction was processed successfully. In order to do this, I also needed to change the way we select contracts. We were using `selectedContract :: Maybe Contract`, but that was losing all changes when we deselected the contract.
- …
> scp-1862 - Marlowe Dashboard Client - Improve contract semantics

- cabal.project
- nix/pkgs/default.nix
- nix/pkgs/haskell/haskell.nix
- nix/pkgs/haskell/materialized-unix/default.nix
We're trying to use the Agda nixpkgs infrastructure with our own GHC. I
hadn't done quite enough overriding, so a reference to the nixpkgs GHC
was still sneaking in there!
- Branch
- PR
> Avoid our Agda depending on GHC from nixpkgs

- deployment/morph/configurations.nix
- deployment/terraform/locals.tf
In latest deployments I could not access the dashboard, and I think it was because this PR #2884 changed the port in the PAB webserver. So I have changed the port in the `morph` and `terraform` files.
- Branch
- PR
- ~Reviewer requested~ (tiny fix)
- ~Someone approved it~ (tiny fix)
> Fix port in firewall to match PAB webserver

- deployment/terraform/locals.tf
Revert one of the changes made by #2920, because it makes CI fail
- Branch
- PR
- ~Reviewer requested~
- ~Someone approved it~
> Revert port change that seems to make CI fail

- deployment/terraform/locals.tf
Reverts input-output-hk/plutus#2922.
After testing #2920, it seems the original change was in the right direction and the reason the CI failed was probably some other non-deterministic problem that just happened to occur at the same time
> Revert "Revert port change that seems to make CI fail"

- marlowe-dashboard-client/src/Contract/State.purs
- marlowe-dashboard-client/src/Contract/Types.purs
- marlowe-dashboard-client/src/Contract/View.purs
- marlowe-dashboard-client/src/Icons.purs
- marlowe-dashboard-client/src/Marlowe/Execution.purs
- marlowe-dashboard-client/src/Play/State.purs
- marlowe-dashboard-client/src/Play/View.purs
- marlowe-dashboard-client/static/css/icons.css
- marlowe-dashboard-client/tailwind.config.js
This PR implements the layout for the timeout and close contract cards and the first version of the past step cards with the navigation buttons. It also changes the chose selector so that if it is a single option, it displays a button instead of an input field.
It is not possible to reach the timeout step as all times are hardcoded at the moment, but we can force a timeout to see how it looks like.
The implementation differs from the design in a couple of points in order to make the deadline:
* In the design the mobile version has parts of the previous and next steps on the left and right of the selected step. For this version I've hidden those steps, and the only way to navigate is through the navigation buttons (no scrollbar)
* In the design of the desktop version, the selected step is …
> scp-1862: Marlowe Dashboard Client - Implement past contract cards

- plutus-benchmark/templates/with-iterations.tpl
I seem to have accidentally pasted some spurious text into the `with-iterations.tpl` template file for the benchmarks.  This fixes that.
- Branch
- PR
> Fix typo in with-iterations.tpl

- doc/tutorials/plutus-playground.rst
According to the documentation, the 'Hello World' app should display ten Lovelace. The playground however shows us one hundred Lovelace. This is just a quick fix.
> [DOC] correct plutus-playground.rst

- marlowe-playground-client/test/Main.purs
- marlowe-playground-client/test/Marlowe/DeinstantiatorTests.purs
- web-common-marlowe/src/Marlowe/Deinstantiate.purs
Hack function that checks which example template matches with a given instance of a contract in core Marlowe. It checks each contract in the list and it returns Just if there is exactly one match.
Also a test that makes sure at least it works for escrow.
I used this opportunity to learn about Generics and it seems it worked :)
- Branch
- PR
> SCP-2085 - Write hack to identify templates from instances of contracts

- .github/workflows/test.yml
Disable nix-instantiate test for macos hosts because they are not
reliable and testing instntiation on linux is sufficient.
- Branch
- PR
> github-actions: Execute on linux only

- nix/pkgs/default.nix
- nix/pkgs/haskell/extra.nix
It looks like we don't actually need the library interface files, the reference from the Agda executable is just fine.
This makes the devcontainer a bit smaller.
- Branch
- PR
> Slim down our Agda

- marlowe-playground-client/README.md
- marlowe-playground-client/src/StaticAnalysis/StaticTools.purs
- marlowe-playground-server/app/PSGenerator.hs
- marlowe-symbolic/marlowe-symbolic.cabal
- marlowe-symbolic/src/Marlowe/Symbolic/Server.hs
- marlowe-symbolic/src/Marlowe/Symbolic/Types/Response.hs
- nix/pkgs/haskell/materialized-unix/.plan.nix/marlowe-symbolic.nix
- web-common/src/Analytics.purs
This PR:
- Removes `killall` from the static analysis script.
- Measures time it takes to run static analysis and sends it to the analytics service.
- Updates instructions to generate purescript in the README.md
- Branch
- PR
> SCP-2052 - Remove killallz3 invocation from static analysis and add monitoring

- default.nix
- marlowe-dashboard-client/.gitignore
- marlowe-dashboard-client/default.nix
- marlowe-dashboard-client/package.json
Add an `extraSrcs` input that symlinks `contracts/contracts.json` into
the build. In order to get the same folder during development the
`package.json` provides a `link-contracts` script:
```
$ npm run link-contracts
```
The invocation of the above has also been added to the `start` script.
----
- Branch
- PR
> marlowe-dashboard-client: provide contracts.json

- plutus-pab/README.md
This is a minor change to the plutus-pab's README that highlights the fact users should use `nix` and `nix-shell`.
> Emphasize the use of nix to start Plutus PAB

- README.adoc
The present link links to the _first_ nix title; i.e. the one you're reading! This makes it link to the intended spot.
- Branch
- PR
> fix nix link in docs

- default.nix
This is just a tiny cleanup to remove some leftovers:
- `deployment` was a leftover from the old setup
----
- Branch
- PR
> Drop deployment from default.nix

- deployment/shell.nix
- nix/overlays/nixpkgs-overrides.nix
- nix/pkgs/morph/sshopts.patch
Pass the ssh configuration file created by terraform to morph. This way
no modifications to the local ssh configuration are necessary.
NOTE: the latest released morph does allow passing in the ssh config
file but the feature is broken. That's why this change also includes
a patch to make this work.
- Branch
- PR
> deployment/morph: specify ssh config

- marlowe-dashboard-client/src/Bridge.purs
- marlowe-dashboard-client/src/Capability/Ajax.purs
- marlowe-dashboard-client/src/Capability/Contract.purs
- marlowe-dashboard-client/src/Capability/ContractExe.js
- marlowe-dashboard-client/src/Capability/ContractExe.purs
- marlowe-dashboard-client/src/Capability/Marlowe.purs
- marlowe-dashboard-client/src/Capability/Wallet.purs
- marlowe-dashboard-client/src/Capability/Websocket.purs
- marlowe-dashboard-client/src/Contract/Lenses.purs
- marlowe-dashboard-client/src/Contract/State.purs
- marlowe-dashboard-client/src/Contract/Types.purs
- marlowe-dashboard-client/src/Css.purs
- marlowe-dashboard-client/src/Main.purs
- marlowe-dashboard-client/src/MainFrame/Lenses.purs
- marlowe-dashboard-client/src/MainFrame/State.purs
- marlowe-dashboard-client/src/MainFrame/Types.purs
- marlowe-dashboard-client/src/MainFrame/View.purs
- marlowe-dashboard-client/src/Pickup/Types.purs
- marlowe-dashboard-client/src/Pickup/View.purs
- marlowe-dashboard-client/src/Play/State.purs
- marlowe-dashboard-client/src/Play/Types.purs
- marlowe-dashboard-client/src/Play/View.purs
- marlowe-dashboard-client/src/Template/State.purs
- marlowe-dashboard-client/src/Types.purs
- marlowe-dashboard-client/src/WalletData/Lenses.purs
- marlowe-dashboard-client/src/WalletData/Types.purs
- marlowe-dashboard-client/src/WalletData/Validation.purs
- marlowe-dashboard-client/src/WalletData/View.purs
- marlowe-dashboard-client/tailwind.config.js
- marlowe-dashboard-client/webpack.config.js
This PR starts putting the framework in place for communicating with the new PAB and mock wallet server. Apart from some little tweaks here and there, the main changes are:
1. Added some Capability modules for interacting with the websocket and the APIs. I've started to sketch out a Marlowe capability with specific Marlowe interactions, but that's not ready yet.
2. Added a Bridge module for aligning the frontend and backend types. I haven't started on an instance for the Marlowe `Contract` yet, which may require a bit of work still...
3. Started to wire up wallet generation and pickup. You can now generate a wallet and pick it up, and you will get its pubkey and current balance, and subscribe to balance changes through the websocket. What's missing is creating a wallet companion contract …
> Integrating Marlowe Run with the new PAB.

- default.nix
- marlowe-dashboard-client/README.md
- marlowe-dashboard-client/default.nix
- marlowe-dashboard-client/package.json
This PR adds a nix script (and npm invoker) for installing the Marlowe contracts. (Only one contract at the moment, but shortly to include the wallet companion contract as well.) And it modifies the README accordingly.
> Making development setup easier.

- deployment/morph/machines/playground.nix
- deployment/morph/network.nix
Fix the reference to the documentation files in the playground nginx
configuration.
- Branch
- PR
> Fix docs reference in playgrounds machine

- marlowe-playground-client/static/css/modal.scss
Just changes the `z-index` of the header of the modal so that buttons don't hover over.
Before:
After:
- Branch
- PR
> SCP-2041 - Buttons hover over "open example" window's title

- marlowe-dashboard-client/src/ContractHome/State.purs
- marlowe-dashboard-client/src/ContractHome/Types.purs
- marlowe-dashboard-client/src/ContractHome/View.purs
- marlowe-dashboard-client/src/Css.purs
- marlowe-dashboard-client/src/MainFrame/State.purs
- marlowe-dashboard-client/src/Play/Lenses.purs
- marlowe-dashboard-client/src/Play/State.purs
- marlowe-dashboard-client/src/Play/Types.purs
- marlowe-dashboard-client/src/Play/View.purs
- marlowe-dashboard-client/src/Template/Types.purs
- marlowe-dashboard-client/src/Template/View.purs
- marlowe-dashboard-client/src/WalletData/View.purs
- marlowe-dashboard-client/tailwind.config.js
Previously we could only have one card open at a time, but we need to allow for multiple cards to be stacked on top of each other. Later on we could have a card component. In the meantime, this seems to work.
While I was at it, I noticed that the `ToggleCard` functionality was unnecessary, so I removed it.
> Implementing a card stack.

- shell.nix
I think I just missed adding this at the time!
This time, it has no impact in the shell opening because, as discussed last time, now it just writes the shell script; the building happens when you run `build-and-serve-docs` from within the nix shell :)
- Branch
- PR
> add the generation of the doc serve script to shell.nix

- ci.nix
- default.nix
- deployment/morph/default.nix
- deployment/morph/machines.nix
- deployment/morph/machines/marlowe-dash.nix
- deployment/morph/machines/playground.nix
- deployment/morph/machines/std.nix
- deployment/morph/machines/web-ghc.nix
- deployment/morph/mk-machine.nix
- deployment/morph/network.nix
**Summary**
Build the deployment machines as part of the CI
**Details**
Previously all of the deployment processing was completely outside of the CI. While some nixos vm tests have already been added that at least verify the NixOS modules used in the configurations that we deploy, the actual machine derivations were never built. This PR adds `deployment/morph/default.nix` which builds all machines that are actually deployed.
---
- Branch
- PR
> Build deployments

- nix/pkgs/haskell/materialized-unix/.plan.nix/plutus-core.nix
- plutus-core/plutus-core.cabal
- plutus-core/plutus-core/src/PlutusCore/Constant/Apply.hs
- plutus-core/plutus-core/src/PlutusCore/Constant/Dynamic/Emit.hs
- plutus-core/plutus-core/src/PlutusCore/Constant/Meaning.hs
- plutus-core/plutus-core/src/PlutusCore/Evaluation/Machine/Ck.hs
- plutus-core/plutus-core/src/PlutusCore/Evaluation/Machine/ExBudget.hs
- plutus-core/plutus-core/src/PlutusCore/Evaluation/Machine/Exception.hs
- plutus-core/plutus-core/test/Evaluation/ApplyBuiltinName.hs
- plutus-core/untyped-plutus-core/src/UntypedPlutusCore/Evaluation/Machine/Cek.hs
- plutus-core/untyped-plutus-core/src/UntypedPlutusCore/Evaluation/Machine/Cek/ExBudgetMode.hs
- plutus-core/untyped-plutus-core/src/UntypedPlutusCore/Evaluation/Machine/Cek/Internal.hs
- plutus-core/untyped-plutus-core/test/Evaluation/ApplyBuiltinName.hs
- plutus-core/untyped-plutus-core/test/Evaluation/Machines.hs
This refactors the CEK machine to use exceptions instead of `ExceptT`.
This results in a substantial (30-50%) speedup on the validation
benchmarks. (Will post benchmark results in a comment.)
The cost is some evil in `runCekM` which we should inspect *very*
carefully. We also need some more type applications since we no longer
have the nice `MonadError` functional depenency that fixes the error
type.
So far I *haven't* pushed this down into the constant application
machinery. The main reason for this is that we have some awkwardness at
the interface of `applyTypeSchemed` where we need to change the `cause`
part of the error from a value into a term, and I don't want to have to
catch and rethrow an exception there if we can avoid it. It's also
convenient for other users of the CAM to have …
> SCP-2133: use exceptions in the CEK machine

- nix/pkgs/haskell/materialized-unix/.plan.nix/plutus-core.nix
- nix/pkgs/haskell/materialized-unix/.plan.nix/plutus-ledger-api.nix
- plutus-core/plutus-core.cabal
- plutus-core/plutus-core/src/Data/Aeson/Flatten.hs
- plutus-core/plutus-core/src/PlutusCore/Evaluation/Machine/ExBudgeting.hs
- plutus-core/plutus-core/src/PlutusCore/Evaluation/Machine/ExBudgetingDefaults.hs
- plutus-ledger-api/plutus-ledger-api.cabal
- plutus-ledger-api/src/Plutus/V1/Ledger/Api.hs
- plutus-ledger-api/test/Spec.hs
This gives the ledger an interface that looks like a bag of named
integer parameters.
The implementation is ugly. I wanted this to work today, so I went with
something cheap and unpleasant: it would be nice to have something more
principled, but the current version does work.
We may want to revisit any number of these things. We can get rid of
some ugliness once we also use integetrs internally. But also stuff
like: the set of keys is derived from our current JSONification, which
isn't ideal, it should be highly stable. However, apparently it's okay
if we change the keys a bit before the testnet, so we can come back to
this.
Finally, I added some actual tests that the example scripts work, which
is helpful!
- Branch
- PR
> SCP-2123: Add a nicer interface to the cost model for the ledger

- default.nix
- deployment/morph/mk-machine.nix
Fix the `plutus-docs` reference which was correct for `deployment`
but broken for `morph build`: `plutus-docs <-> docs`
- Branch
- PR
> deployment: fix plutus-docs reference

- deployment/terraform/locals.tf
Drop the unused liva-infra-staging ssh keys from the terraform config
- Branch
- PR
> deployment: drop live-infra-staging
